// E26 "Guess the Airline" — answer = airline name, image = official airline logo.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
// Hard content rules: no Israeli airlines (El Al, Israir, Arkia, Sundor) — screened out entirely.
export const AIRLINE_LOGOS_E26 = [
  // EASY (18) — globally iconic, instantly recognized worldwide
  { slug: "american-airlines", name: "American Airlines", level: "easy" },
  { slug: "delta-air-lines", name: "Delta Air Lines", level: "easy" },
  { slug: "united-airlines", name: "United Airlines", level: "easy" },
  { slug: "emirates", name: "Emirates", level: "easy" },
  { slug: "qatar-airways", name: "Qatar Airways", level: "easy" },
  { slug: "lufthansa", name: "Lufthansa", level: "easy" },
  { slug: "british-airways", name: "British Airways", level: "easy" },
  { slug: "air-france", name: "Air France", level: "easy" },
  { slug: "singapore-airlines", name: "Singapore Airlines", level: "easy" },
  { slug: "southwest-airlines", name: "Southwest Airlines", level: "easy" },
  { slug: "ryanair", name: "Ryanair", level: "easy" },
  { slug: "easyjet", name: "easyJet", level: "easy" },
  { slug: "qantas", name: "Qantas", level: "easy" },
  { slug: "air-canada", name: "Air Canada", level: "easy" },
  { slug: "turkish-airlines", name: "Turkish Airlines", level: "easy" },
  { slug: "klm", name: "KLM", level: "easy" },
  { slug: "etihad-airways", name: "Etihad Airways", level: "easy" },
  { slug: "cathay-pacific", name: "Cathay Pacific", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "jetblue", name: "JetBlue", level: "medium" },
  { slug: "alaska-airlines", name: "Alaska Airlines", level: "medium" },
  { slug: "virgin-atlantic", name: "Virgin Atlantic", level: "medium" },
  { slug: "air-india", name: "Air India", level: "medium" },
  { slug: "china-southern-airlines", name: "China Southern Airlines", level: "medium" },
  { slug: "all-nippon-airways", name: "All Nippon Airways", level: "medium" },
  { slug: "japan-airlines", name: "Japan Airlines", level: "medium" },
  { slug: "thai-airways", name: "Thai Airways", level: "medium" },
  { slug: "iberia", name: "Iberia", level: "medium" },
  { slug: "swiss-international-air-lines", name: "Swiss International Air Lines", level: "medium" },
  { slug: "finnair", name: "Finnair", level: "medium" },
  { slug: "aeroflot", name: "Aeroflot", level: "medium" },
  { slug: "latam-airlines", name: "LATAM Airlines", level: "medium" },
  { slug: "norwegian-air-shuttle", name: "Norwegian Air Shuttle", level: "medium" },
  { slug: "vietnam-airlines", name: "Vietnam Airlines", level: "medium" },
  { slug: "malaysia-airlines", name: "Malaysia Airlines", level: "medium" },
  { slug: "south-african-airways", name: "South African Airways", level: "medium" },
  { slug: "air-new-zealand", name: "Air New Zealand", level: "medium" },

  // HARD (18) — recognizable to frequent flyers/aviation enthusiasts
  { slug: "aer-lingus", name: "Aer Lingus", level: "hard" },
  { slug: "austrian-airlines", name: "Austrian Airlines", level: "hard" },
  { slug: "tap-air-portugal", name: "TAP Air Portugal", level: "hard" },
  { slug: "scandinavian-airlines", name: "Scandinavian Airlines", level: "hard" },
  { slug: "egyptair", name: "EgyptAir", level: "hard" },
  { slug: "royal-jordanian", name: "Royal Jordanian", level: "hard" },
  { slug: "kuwait-airways", name: "Kuwait Airways", level: "hard" },
  { slug: "saudia", name: "Saudia", level: "hard" },
  { slug: "philippine-airlines", name: "Philippine Airlines", level: "hard" },
  { slug: "garuda-indonesia", name: "Garuda Indonesia", level: "hard" },
  { slug: "china-eastern-airlines", name: "China Eastern Airlines", level: "hard" },
  { slug: "air-china", name: "Air China", level: "hard" },
  { slug: "copa-airlines", name: "Copa Airlines", level: "hard" },
  { slug: "avianca", name: "Avianca", level: "hard" },
  { slug: "aeromexico", name: "Aeromexico", level: "hard" },
  { slug: "westjet", name: "WestJet", level: "hard" },
  { slug: "icelandair", name: "Icelandair", level: "hard" },
  { slug: "ethiopian-airlines", name: "Ethiopian Airlines", level: "hard" },

  // IMPOSSIBLE (17) — obscure even to enthusiasts
  { slug: "royal-air-maroc", name: "Royal Air Maroc", level: "impossible" },
  { slug: "kenya-airways", name: "Kenya Airways", level: "impossible" },
  { slug: "tunisair", name: "Tunisair", level: "impossible" },
  { slug: "azerbaijan-airlines", name: "Azerbaijan Airlines", level: "impossible" },
  { slug: "uzbekistan-airways", name: "Uzbekistan Airways", level: "impossible" },
  { slug: "air-serbia", name: "Air Serbia", level: "impossible" },
  { slug: "lot-polish-airlines", name: "LOT Polish Airlines", level: "impossible" },
  { slug: "tarom", name: "TAROM", level: "impossible" },
  { slug: "air-baltic", name: "Air Baltic", level: "impossible" },
  { slug: "bulgaria-air", name: "Bulgaria Air", level: "impossible" },
  { slug: "cyprus-airways", name: "Cyprus Airways", level: "impossible" },
  { slug: "nepal-airlines", name: "Nepal Airlines", level: "impossible" },
  { slug: "myanmar-airways", name: "Myanmar Airways International", level: "impossible" },
  { slug: "air-mauritius", name: "Air Mauritius", level: "impossible" },
  { slug: "fiji-airways", name: "Fiji Airways", level: "impossible" },
  { slug: "surinam-airways", name: "Surinam Airways", level: "impossible" },
  { slug: "croatia-airlines", name: "Croatia Airlines", level: "impossible" },
];
