export const AIRLINE_LOGOS_E26_FACTS = {
  "american-airlines": "American Airlines operates one of the world's largest airline fleets.",
  "delta-air-lines": "Delta Air Lines traces its roots to a crop-dusting company.",
  "united-airlines": "United Airlines was formed from a 1920s mail-carrying route.",
  "emirates": "Emirates is based in Dubai and flies an all-widebody fleet.",
  "qatar-airways": "Qatar Airways is based at Hamad International Airport in Doha.",
  "lufthansa": "Lufthansa's crane logo is one of the oldest airline emblems.",
  "british-airways": "British Airways formed from a merger of state airlines in 1974.",
  "air-france": "Air France's hub is Paris Charles de Gaulle Airport.",
  "singapore-airlines": "Singapore Airlines was the launch customer for the Airbus A380.",
  "southwest-airlines": "Southwest Airlines pioneered the low-cost airline model in the US.",
  "ryanair": "Ryanair carries more passengers than any other European airline.",
  "easyjet": "easyJet was founded in 1995 as a low-cost UK airline.",
  "qantas": "Qantas is one of the world's oldest continuously operating airlines.",
  "air-canada": "Air Canada's maple leaf logo represents its home country.",
  "turkish-airlines": "Turkish Airlines flies to more countries than any other airline.",
  "klm": "KLM is the oldest airline still operating under its original name.",
  "etihad-airways": "Etihad Airways is the flag carrier of the United Arab Emirates.",
  "cathay-pacific": "Cathay Pacific is based at Hong Kong International Airport.",

  "jetblue": "JetBlue is known for offering free in-flight snacks and TV.",
  "alaska-airlines": "Alaska Airlines merged with Virgin America in 2018.",
  "virgin-atlantic": "Virgin Atlantic was founded by entrepreneur Richard Branson.",
  "air-india": "Air India was founded by industrialist J.R.D. Tata in 1932.",
  "china-southern-airlines": "China Southern Airlines is one of China's 'Big Three' carriers.",
  "all-nippon-airways": "All Nippon Airways is Japan's largest airline by fleet size.",
  "japan-airlines": "Japan Airlines' crane logo represents good fortune in Japan.",
  "thai-airways": "Thai Airways' orchid emblem reflects Thailand's national flower.",
  "iberia": "Iberia is the flag carrier and largest airline of Spain.",
  "swiss-international-air-lines": "Swiss International Air Lines formed after Swissair's collapse.",
  "finnair": "Finnair is one of the world's oldest airlines still flying.",
  "aeroflot": "Aeroflot was once the world's largest airline during Soviet times.",
  "latam-airlines": "LATAM Airlines formed from a merger of LAN and TAM.",
  "norwegian-air-shuttle": "Norwegian Air Shuttle puts famous Norwegians' faces on its tailfins.",
  "vietnam-airlines": "Vietnam Airlines' logo is a golden lotus flower.",
  "malaysia-airlines": "Malaysia Airlines' logo is a stylized kite called a wau.",
  "south-african-airways": "South African Airways is one of Africa's oldest airlines.",
  "air-new-zealand": "Air New Zealand's logo features a stylized silver fern.",

  "aer-lingus": "Aer Lingus takes its shamrock logo from Ireland's symbol.",
  "austrian-airlines": "Austrian Airlines is the flag carrier of Austria.",
  "tap-air-portugal": "TAP Air Portugal was founded in 1945.",
  "scandinavian-airlines": "Scandinavian Airlines is jointly owned by three Nordic countries.",
  "egyptair": "EgyptAir is one of Africa's oldest airlines still operating.",
  "royal-jordanian": "Royal Jordanian is Jordan's national flag carrier.",
  "kuwait-airways": "Kuwait Airways is the flag carrier of Kuwait.",
  "saudia": "Saudia's logo features a green palm tree and crossed swords.",
  "philippine-airlines": "Philippine Airlines is Asia's oldest active commercial airline.",
  "garuda-indonesia": "Garuda Indonesia is named after a mythical bird from Hindu myth.",
  "china-eastern-airlines": "China Eastern Airlines is based in Shanghai.",
  "air-china": "Air China's logo features a stylized phoenix.",
  "copa-airlines": "Copa Airlines is the flag carrier of Panama.",
  "avianca": "Avianca is one of the oldest continuously operating airlines.",
  "aeromexico": "Aeromexico is the flag carrier and largest airline of Mexico.",
  "westjet": "WestJet was founded in 1996 as a low-cost Canadian airline.",
  "icelandair": "Icelandair's route network is built around its Reykjavik hub.",
  "ethiopian-airlines": "Ethiopian Airlines is one of Africa's largest airlines.",

  "royal-air-maroc": "Royal Air Maroc is the flag carrier of Morocco.",
  "kenya-airways": "Kenya Airways is nicknamed 'The Pride of Africa'.",
  "tunisair": "Tunisair is the flag carrier of Tunisia, founded in 1948.",
  "azerbaijan-airlines": "Azerbaijan Airlines is the state flag carrier of Azerbaijan.",
  "uzbekistan-airways": "Uzbekistan Airways is the national airline of Uzbekistan.",
  "air-serbia": "Air Serbia was formed from the former airline JAT Airways.",
  "lot-polish-airlines": "LOT Polish Airlines is one of the world's oldest airlines.",
  "tarom": "TAROM is Romania's national flag carrier airline.",
  "air-baltic": "airBaltic is based in Riga, the capital of Latvia.",
  "bulgaria-air": "Bulgaria Air is the flag carrier of Bulgaria.",
  "cyprus-airways": "Cyprus Airways was relaunched in 2017 after a 2015 shutdown.",
  "nepal-airlines": "Nepal Airlines is the state-owned flag carrier of Nepal.",
  "myanmar-airways": "Myanmar Airways International serves routes across Southeast Asia.",
  "air-mauritius": "Air Mauritius is the national airline of the island of Mauritius.",
  "fiji-airways": "Fiji Airways is the flag carrier of the Pacific island nation.",
  "surinam-airways": "Surinam Airways is the flag carrier of Suriname in South America.",
  "croatia-airlines": "Croatia Airlines is the flag carrier of Croatia, founded 1989.",
};
