// E76 "Guess the Airplane" — 70 real fixed-wing aircraft, easy->impossible. First
// aviation-themed episode on the channel (distinct from every prior car/motorcycle episode).
export const AIRPLANES_E76 = [
  // EASY (18): Boeing 747, Airbus A380, Boeing 737, Concorde, Supermarine Spitfire,
  //   Air Force One, Boeing 787 Dreamliner, Wright Flyer, P-51 Mustang, B-52
  //   Stratofortress, F-16 Fighting Falcon, Airbus A320, SR-71 Blackbird, F-22 Raptor,
  //   Boeing 767, Cessna 172, Airbus A350, Boeing 777
  { slug: "boeing-747", name: "Boeing 747", wiki: "Boeing 747", level: "easy" },
  { slug: "airbus-a380", name: "Airbus A380", wiki: "Airbus A380", level: "easy" },
  { slug: "boeing-737", name: "Boeing 737", wiki: "Boeing 737", level: "easy" },
  { slug: "concorde", name: "Concorde", wiki: "Concorde", level: "easy" },
  { slug: "supermarine-spitfire", name: "Supermarine Spitfire", wiki: "Supermarine Spitfire", level: "easy" },
  { slug: "air-force-one", name: "Air Force One", wiki: "Boeing VC-25", level: "easy" },
  { slug: "boeing-787", name: "Boeing 787 Dreamliner", wiki: "Boeing 787 Dreamliner", level: "easy" },
  { slug: "wright-flyer", name: "Wright Flyer", wiki: "Wright Flyer", level: "easy" },
  { slug: "p-51-mustang", name: "P-51 Mustang", wiki: "North American P-51 Mustang", level: "easy" },
  { slug: "b-52-stratofortress", name: "B-52 Stratofortress", wiki: "Boeing B-52 Stratofortress", level: "easy" },
  { slug: "f-16-fighting-falcon", name: "F-16 Fighting Falcon", wiki: "General Dynamics F-16 Fighting Falcon", level: "easy" },
  { slug: "airbus-a320", name: "Airbus A320", wiki: "Airbus A320 family", level: "easy" },
  { slug: "sr-71-blackbird", name: "SR-71 Blackbird", wiki: "Lockheed SR-71 Blackbird", level: "easy" },
  { slug: "f-22-raptor", name: "F-22 Raptor", wiki: "Lockheed Martin F-22 Raptor", level: "easy" },
  { slug: "boeing-767", name: "Boeing 767", wiki: "Boeing 767", level: "easy" },
  { slug: "cessna-172", name: "Cessna 172", wiki: "Cessna 172", level: "easy" },
  { slug: "airbus-a350", name: "Airbus A350", wiki: "Airbus A350", level: "easy" },
  { slug: "boeing-777", name: "Boeing 777", wiki: "Boeing 777", level: "easy" },

  // MEDIUM (18): F-35 Lightning II, Boeing 727, Douglas DC-3, Airbus A330, Boeing 757,
  //   C-130 Hercules, Eurofighter Typhoon, Mitsubishi A6M Zero, B-2 Spirit, Boeing 707,
  //   Antonov An-225 Mriya, F-14 Tomcat, Piper J-3 Cub, Douglas DC-9, Boeing 717,
  //   Fokker Dr.I, Bombardier CRJ, Embraer E190
  { slug: "f-35-lightning-ii", name: "F-35 Lightning II", wiki: "Lockheed Martin F-35 Lightning II", level: "medium" },
  { slug: "boeing-727", name: "Boeing 727", wiki: "Boeing 727", level: "medium" },
  { slug: "douglas-dc-3", name: "Douglas DC-3", wiki: "Douglas DC-3", level: "medium" },
  { slug: "airbus-a330", name: "Airbus A330", wiki: "Airbus A330", level: "medium" },
  { slug: "boeing-757", name: "Boeing 757", wiki: "Boeing 757", level: "medium" },
  { slug: "c-130-hercules", name: "C-130 Hercules", wiki: "Lockheed C-130 Hercules", level: "medium" },
  { slug: "eurofighter-typhoon", name: "Eurofighter Typhoon", wiki: "Eurofighter Typhoon", level: "medium" },
  { slug: "mitsubishi-zero", name: "Mitsubishi Zero", wiki: "Mitsubishi A6M Zero", level: "medium" },
  { slug: "b-2-spirit", name: "B-2 Spirit", wiki: "Northrop Grumman B-2 Spirit", level: "medium" },
  { slug: "boeing-707", name: "Boeing 707", wiki: "Boeing 707", level: "medium" },
  { slug: "antonov-an-225", name: "Antonov An-225 Mriya", wiki: "Antonov An-225 Mriya", level: "medium" },
  { slug: "f-14-tomcat", name: "F-14 Tomcat", wiki: "Grumman F-14 Tomcat", level: "medium" },
  { slug: "piper-cub", name: "Piper J-3 Cub", wiki: "Piper J-3 Cub", level: "medium" },
  { slug: "douglas-dc-9", name: "Douglas DC-9", wiki: "Douglas DC-9", level: "medium" },
  { slug: "boeing-717", name: "Boeing 717", wiki: "Boeing 717", level: "medium" },
  { slug: "fokker-dr1", name: "Fokker Dr.I", wiki: "Fokker Dr.I", level: "medium" },
  { slug: "bombardier-crj", name: "Bombardier CRJ", wiki: "Bombardier CRJ", level: "medium" },
  { slug: "embraer-e190", name: "Embraer E190", wiki: "Embraer E-Jet family", level: "medium" },

  // HARD (16): Messerschmitt Bf 109, Junkers Ju 87 Stuka, Avro Lancaster, KC-135
  //   Stratotanker, B-1 Lancer, Sopwith Camel, Boeing 247, Lockheed U-2, F4F Wildcat,
  //   Hawker Hurricane, Convair B-36 Peacemaker, F4U Corsair, de Havilland Mosquito,
  //   Handley Page Victor, Yakovlev Yak-9, Ilyushin Il-2 Sturmovik
  { slug: "messerschmitt-bf109", name: "Messerschmitt Bf 109", wiki: "Messerschmitt Bf 109", level: "hard" },
  { slug: "junkers-ju87-stuka", name: "Junkers Ju 87 Stuka", wiki: "Junkers Ju 87", level: "hard" },
  { slug: "avro-lancaster", name: "Avro Lancaster", wiki: "Avro Lancaster", level: "hard" },
  { slug: "kc-135-stratotanker", name: "KC-135 Stratotanker", wiki: "Boeing KC-135 Stratotanker", level: "hard" },
  { slug: "b-1-lancer", name: "B-1 Lancer", wiki: "Rockwell B-1 Lancer", level: "hard" },
  { slug: "sopwith-camel", name: "Sopwith Camel", wiki: "Sopwith Camel", level: "hard" },
  { slug: "boeing-247", name: "Boeing 247", wiki: "Boeing 247", level: "hard" },
  { slug: "lockheed-u-2", name: "Lockheed U-2", wiki: "Lockheed U-2", level: "hard" },
  { slug: "f4f-wildcat", name: "F4F Wildcat", wiki: "Grumman F4F Wildcat", level: "hard" },
  { slug: "hawker-hurricane", name: "Hawker Hurricane", wiki: "Hawker Hurricane", level: "hard" },
  { slug: "convair-b-36", name: "Convair B-36 Peacemaker", wiki: "Convair B-36 Peacemaker", level: "hard" },
  { slug: "f4u-corsair", name: "F4U Corsair", wiki: "Vought F4U Corsair", level: "hard" },
  { slug: "de-havilland-mosquito", name: "de Havilland Mosquito", wiki: "De Havilland Mosquito", level: "hard" },
  { slug: "handley-page-victor", name: "Handley Page Victor", wiki: "Handley Page Victor", level: "hard" },
  { slug: "yakovlev-yak-9", name: "Yakovlev Yak-9", wiki: "Yakovlev Yak-9", level: "hard" },
  { slug: "ilyushin-il-2", name: "Ilyushin Il-2 Sturmovik", wiki: "Ilyushin Il-2 Shturmovik", level: "hard" },

  // IMPOSSIBLE (18): Fairey Swordfish, Blohm & Voss BV 141, Vickers Vimy, Caproni Ca.60,
  //   Bristol Beaufighter, Gloster Meteor, Heinkel He 178, Bell X-1, North American X-15,
  //   Convair XFY Pogo, Vought V-173, Antonov An-2, Beriev Be-200, Tupolev Tu-144,
  //   Saab 37 Viggen, Dassault Mirage III, Hawker Siddeley Harrier, Fieseler Fi 156 Storch
  { slug: "fairey-swordfish", name: "Fairey Swordfish", wiki: "Fairey Swordfish", level: "impossible" },
  { slug: "blohm-voss-bv141", name: "Blohm & Voss BV 141", wiki: "Blohm & Voss BV 141", level: "impossible" },
  { slug: "vickers-vimy", name: "Vickers Vimy", wiki: "Vickers Vimy", level: "impossible" },
  { slug: "caproni-ca60", name: "Caproni Ca.60", wiki: "Caproni Ca.60", level: "impossible" },
  { slug: "bristol-beaufighter", name: "Bristol Beaufighter", wiki: "Bristol Beaufighter", level: "impossible" },
  { slug: "gloster-meteor", name: "Gloster Meteor", wiki: "Gloster Meteor", level: "impossible" },
  { slug: "heinkel-he178", name: "Heinkel He 178", wiki: "Heinkel He 178", level: "impossible" },
  { slug: "bell-x-1", name: "Bell X-1", wiki: "Bell X-1", level: "impossible" },
  { slug: "north-american-x-15", name: "North American X-15", wiki: "North American X-15", level: "impossible" },
  { slug: "convair-xfy-pogo", name: "Convair XFY Pogo", wiki: "Convair XFY Pogo", level: "impossible" },
  { slug: "vought-v173", name: "Vought V-173", wiki: "Vought V-173", level: "impossible" },
  { slug: "antonov-an-2", name: "Antonov An-2", wiki: "Antonov An-2", level: "impossible" },
  { slug: "beriev-be-200", name: "Beriev Be-200", wiki: "Beriev Be-200", level: "impossible" },
  { slug: "tupolev-tu-144", name: "Tupolev Tu-144", wiki: "Tupolev Tu-144", level: "impossible" },
  { slug: "saab-37-viggen", name: "Saab 37 Viggen", wiki: "Saab 37 Viggen", level: "impossible" },
  { slug: "dassault-mirage-iii", name: "Dassault Mirage III", wiki: "Dassault Mirage III", level: "impossible" },
  { slug: "hawker-siddeley-harrier", name: "Hawker Siddeley Harrier", wiki: "Hawker Siddeley Harrier", level: "impossible" },
  { slug: "fieseler-storch", name: "Fieseler Fi 156 Storch", wiki: "Fieseler Fi 156 Storch", level: "impossible" },
];

export default AIRPLANES_E76;
