export const AIRPLANES_E76_FACTS = {
  "boeing-747": "Nicknamed the 'Queen of the Skies' for its iconic hump.",
  "airbus-a380": "The world's largest passenger airliner, with two full decks.",
  "boeing-737": "The best-selling commercial jetliner in aviation history.",
  "concorde": "Could cross the Atlantic in under 3.5 hours at twice sound speed.",
  "supermarine-spitfire": "Its elliptical wing became a defining shape of WWII fighters.",
  "air-force-one": "The callsign for any Air Force jet carrying the US President.",
  "boeing-787": "Made largely of carbon-fiber composite instead of aluminum.",
  "wright-flyer": "Made the first sustained, controlled powered flight in 1903.",
  "p-51-mustang": "A Merlin-engine upgrade turned it into WWII's top escort fighter.",
  "b-52-stratofortress": "Still flying missions over 70 years after its first flight.",
  "f-16-fighting-falcon": "Flown by more air forces worldwide than any other fighter jet.",
  "airbus-a320": "The first airliner with digital fly-by-wire flight controls.",
  "sr-71-blackbird": "Still holds the record for fastest air-breathing manned aircraft.",
  "f-22-raptor": "The US never sold this stealth fighter to any other country.",
  "boeing-767": "The first Boeing jet designed with a two-person cockpit crew.",
  "cessna-172": "The most-produced airplane in aviation history.",
  "airbus-a350": "In a ground stress test, its wingtip flexed upward 5.2 meters.",
  "boeing-777": "The first airliner designed entirely using 3D computer modeling.",
  "f-35-lightning-ii": "Built in three versions, including one that lands vertically.",
  "boeing-727": "Once the world's best-selling jetliner, with over 1,800 built.",
  "douglas-dc-3": "So rugged that hundreds still fly commercially today.",
  "airbus-a330": "Shares a cockpit design with the larger four-engine A340.",
  "boeing-757": "Its powerful engines let it use much shorter runways than rivals.",
  "c-130-hercules": "Has served in more roles than almost any military aircraft.",
  "eurofighter-typhoon": "Built jointly by the UK, Germany, Italy, and Spain.",
  "mitsubishi-zero": "Its light airframe gave it startling range and agility in 1940.",
  "b-2-spirit": "Its flying-wing shape helps it evade enemy radar.",
  "boeing-707": "Launched the jet age for American commercial airliners.",
  "antonov-an-225": "The heaviest aircraft ever built, with six jet engines.",
  "f-14-tomcat": "Its wings sweep back automatically at high speed.",
  "piper-cub": "This tiny yellow trainer taught countless WWII-era pilots to fly.",
  "douglas-dc-9": "Its tail-mounted engines inspired many later regional jets.",
  "boeing-717": "Originally launched as the McDonnell Douglas MD-95.",
  "fokker-dr1": "The three-wing fighter flown by the 'Red Baron.'",
  "bombardier-crj": "A regional jet family built in Montreal, Canada.",
  "embraer-e190": "Built by Brazil's largest aerospace manufacturer.",
  "messerschmitt-bf109": "Produced in greater numbers than any other fighter in history.",
  "junkers-ju87-stuka": "Its sirens screamed on purpose to terrify people below.",
  "avro-lancaster": "Carried the largest bombs of any WWII aircraft.",
  "kc-135-stratotanker": "Refuels other aircraft mid-flight through a rear boom.",
  "b-1-lancer": "Its wings sweep back for supersonic dashes at low altitude.",
  "sopwith-camel": "Downed more enemy aircraft than any other WWI fighter.",
  "boeing-247": "Considered the first truly modern all-metal airliner.",
  "lockheed-u-2": "Flies so high its pilots must wear full pressure suits.",
  "f4f-wildcat": "Outmatched by the Zero, but its pilots still held the line.",
  "hawker-hurricane": "Shot down more enemy planes than any other Battle of Britain type.",
  "convair-b-36": "Its ten engines made it the largest mass-produced piston bomber.",
  "f4u-corsair": "Its bent gull wings let it carry a huge propeller safely.",
  "de-havilland-mosquito": "Built almost entirely of wood, earning it the name 'Wooden Wonder.'",
  "handley-page-victor": "One of Britain's three V-bombers of the Cold War era.",
  "yakovlev-yak-9": "The most-produced Soviet fighter of the Second World War.",
  "ilyushin-il-2": "So vital to the Red Army that Stalin called it 'daily bread.'",
  "fairey-swordfish": "This 'obsolete' biplane helped cripple the Bismarck in 1941.",
  "blohm-voss-bv141": "Its oddly lopsided design gave the pilot an unobstructed view.",
  "vickers-vimy": "Made the first nonstop transatlantic flight in 1919.",
  "caproni-ca60": "A nine-wing flying boat that crashed during 1921 flight testing.",
  "bristol-beaufighter": "Nicknamed 'Whispering Death' for its near-silent engines.",
  "gloster-meteor": "The only Allied jet to see combat in World War II.",
  "heinkel-he178": "The world's first aircraft to fly on jet power alone.",
  "bell-x-1": "The first plane to fly faster than the speed of sound.",
  "north-american-x-15": "A rocket plane that reached the edge of space.",
  "convair-xfy-pogo": "This prop plane took off and landed standing on its tail.",
  "vought-v173": "Its disc-shaped wing earned it the nickname 'Flying Pancake.'",
  "antonov-an-2": "This single-engine biplane can fly as slow as 30 mph.",
  "beriev-be-200": "A jet-powered flying boat used for firefighting and rescue.",
  "tupolev-tu-144": "The Soviet supersonic jet nicknamed 'Concordski' for its look.",
  "saab-37-viggen": "Built to land and take off from short Swedish highway strips.",
  "dassault-mirage-iii": "Its delta-wing shape became a French fighter trademark.",
  "hawker-siddeley-harrier": "A jet fighter that can hover and land straight down.",
  "fieseler-storch": "Could take off in under 200 feet thanks to its slow-flight wing.",
};

export default AIRPLANES_E76_FACTS;
