// E35 "Guess the Ancient Ruin" — answer = ruin/archaeological site name, image = real photo of the site.
// Different angle from E09 World Landmarks (which covers general iconic/modern landmarks) —
// E35 focuses specifically on ancient ruins/archaeological sites, no overlap with E09's list.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
export const ANCIENT_RUINS_E35 = [
  // EASY (18) — globally iconic ancient ruins
  { slug: "pompeii", name: "Pompeii", country: "Italy", level: "easy" },
  { slug: "persepolis", name: "Persepolis", country: "Iran", level: "easy" },
  { slug: "ephesus", name: "Ephesus", country: "Turkey", level: "easy" },
  { slug: "karnak-temple", name: "Karnak Temple", country: "Egypt", level: "easy" },
  { slug: "luxor-temple", name: "Luxor Temple", country: "Egypt", level: "easy" },
  { slug: "abu-simbel", name: "Abu Simbel", country: "Egypt", level: "easy" },
  { slug: "teotihuacan", name: "Teotihuacan", country: "Mexico", level: "easy" },
  { slug: "tikal", name: "Tikal", country: "Guatemala", level: "easy" },
  { slug: "delphi", name: "Delphi", country: "Greece", level: "easy" },
  { slug: "knossos", name: "Knossos", country: "Greece", level: "easy" },
  { slug: "mycenae", name: "Mycenae", country: "Greece", level: "easy" },
  { slug: "olympia-ancient", name: "Ancient Olympia", country: "Greece", level: "easy" },
  { slug: "palmyra", name: "Palmyra", country: "Syria", level: "easy" },
  { slug: "baalbek", name: "Baalbek", country: "Lebanon", level: "easy" },
  { slug: "nazca-lines", name: "Nazca Lines", country: "Peru", level: "easy" },
  { slug: "sacsayhuaman", name: "Sacsayhuamán", country: "Peru", level: "easy" },
  { slug: "terracotta-army", name: "Terracotta Army", country: "China", level: "easy" },
  { slug: "agrigento-valley-of-temples", name: "Valley of the Temples", country: "Italy", level: "easy" },

  // MEDIUM (18)
  { slug: "herculaneum", name: "Herculaneum", country: "Italy", level: "medium" },
  { slug: "ostia-antica", name: "Ostia Antica", country: "Italy", level: "medium" },
  { slug: "segesta", name: "Segesta", country: "Italy", level: "medium" },
  { slug: "selinunte", name: "Selinunte", country: "Italy", level: "medium" },
  { slug: "paestum", name: "Paestum", country: "Italy", level: "medium" },
  { slug: "jerash", name: "Jerash", country: "Jordan", level: "medium" },
  { slug: "hattusa", name: "Hattusa", country: "Turkey", level: "medium" },
  { slug: "mount-nemrut", name: "Mount Nemrut", country: "Turkey", level: "medium" },
  { slug: "philae", name: "Philae", country: "Egypt", level: "medium" },
  { slug: "mohenjo-daro", name: "Mohenjo-daro", country: "Pakistan", level: "medium" },
  { slug: "gobekli-tepe", name: "Göbekli Tepe", country: "Turkey", level: "medium" },
  { slug: "palenque", name: "Palenque", country: "Mexico", level: "medium" },
  { slug: "copan", name: "Copán", country: "Honduras", level: "medium" },
  { slug: "uxmal", name: "Uxmal", country: "Mexico", level: "medium" },
  { slug: "monte-alban", name: "Monte Albán", country: "Mexico", level: "medium" },
  { slug: "sigiriya", name: "Sigiriya", country: "Sri Lanka", level: "medium" },
  { slug: "hampi", name: "Hampi", country: "India", level: "medium" },
  { slug: "mahabalipuram", name: "Mahabalipuram", country: "India", level: "medium" },

  // HARD (18)
  { slug: "leptis-magna", name: "Leptis Magna", country: "Libya", level: "hard" },
  { slug: "sabratha", name: "Sabratha", country: "Libya", level: "hard" },
  { slug: "volubilis", name: "Volubilis", country: "Morocco", level: "hard" },
  { slug: "timgad", name: "Timgad", country: "Algeria", level: "hard" },
  { slug: "djemila", name: "Djemila", country: "Algeria", level: "hard" },
  { slug: "cyrene", name: "Cyrene", country: "Libya", level: "hard" },
  { slug: "epidaurus", name: "Epidaurus", country: "Greece", level: "hard" },
  { slug: "delos", name: "Delos", country: "Greece", level: "hard" },
  { slug: "caral", name: "Caral", country: "Peru", level: "hard" },
  { slug: "tiwanaku", name: "Tiwanaku", country: "Bolivia", level: "hard" },
  { slug: "chan-chan", name: "Chan Chan", country: "Peru", level: "hard" },
  { slug: "ollantaytambo", name: "Ollantaytambo", country: "Peru", level: "hard" },
  { slug: "skara-brae", name: "Skara Brae", country: "Scotland", level: "hard" },
  { slug: "newgrange", name: "Newgrange", country: "Ireland", level: "hard" },
  { slug: "avebury", name: "Avebury", country: "England", level: "hard" },
  { slug: "carnac-stones", name: "Carnac Stones", country: "France", level: "hard" },
  { slug: "prambanan", name: "Prambanan", country: "Indonesia", level: "hard" },
  { slug: "polonnaruwa", name: "Polonnaruwa", country: "Sri Lanka", level: "hard" },

  // IMPOSSIBLE (17)
  { slug: "chaco-canyon", name: "Chaco Canyon", country: "United States", level: "impossible" },
  { slug: "mesa-verde-cliff-palace", name: "Cliff Palace, Mesa Verde", country: "United States", level: "impossible" },
  { slug: "cahokia-mounds", name: "Cahokia Mounds", country: "United States", level: "impossible" },
  { slug: "great-serpent-mound", name: "Great Serpent Mound", country: "United States", level: "impossible" },
  { slug: "anuradhapura", name: "Anuradhapura", country: "Sri Lanka", level: "impossible" },
  { slug: "my-son-sanctuary", name: "My Son Sanctuary", country: "Vietnam", level: "impossible" },
  { slug: "meroe-pyramids", name: "Pyramids of Meroë", country: "Sudan", level: "impossible" },
  { slug: "aksum-obelisks", name: "Obelisks of Aksum", country: "Ethiopia", level: "impossible" },
  { slug: "kilwa-kisiwani", name: "Kilwa Kisiwani", country: "Tanzania", level: "impossible" },
  { slug: "loulan-ruins", name: "Loulan Ruins", country: "China", level: "impossible" },
  { slug: "jiaohe-ruins", name: "Jiaohe Ruins", country: "China", level: "impossible" },
  { slug: "ur-iraq", name: "Ur", country: "Iraq", level: "impossible" },
  { slug: "babylon-ruins", name: "Babylon", country: "Iraq", level: "impossible" },
  { slug: "nineveh", name: "Nineveh", country: "Iraq", level: "impossible" },
  { slug: "byblos", name: "Byblos", country: "Lebanon", level: "impossible" },
  { slug: "jericho", name: "Jericho", country: "Palestine", level: "impossible" },
  { slug: "ai-khanoum", name: "Ai-Khanoum", country: "Afghanistan", level: "impossible" },
];
