export const ANCIENT_RUINS_E35_FACTS = {
  "pompeii": "Pompeii was buried and preserved by Vesuvius's 79 AD eruption.",
  "persepolis": "Persepolis was the ceremonial capital of the Persian Empire.",
  "ephesus": "Ephesus once held one of the Seven Wonders, the Temple of Artemis.",
  "karnak-temple": "Karnak is the largest ancient religious site ever built.",
  "luxor-temple": "Luxor Temple was built for the annual Opet Festival.",
  "abu-simbel": "Abu Simbel's temples were moved to avoid a 1960s dam flood.",
  "teotihuacan": "Teotihuacan's builders remain unidentified by historians.",
  "tikal": "Tikal was a major Maya city hidden deep in the jungle canopy.",
  "delphi": "Delphi housed the Oracle consulted by ancient Greek rulers.",
  "knossos": "Knossos is linked to the legendary Minotaur's labyrinth myth.",
  "mycenae": "Mycenae gave its name to an entire era of Greek civilization.",
  "olympia-ancient": "Ancient Olympia hosted the original Olympic Games.",
  "palmyra": "Palmyra was a wealthy caravan oasis on the Silk Road.",
  "baalbek": "Baalbek holds some of the largest stone blocks ever quarried.",
  "nazca-lines": "The Nazca Lines are best appreciated from the air.",
  "sacsayhuaman": "Sacsayhuamán's walls use stones fitted without mortar.",
  "terracotta-army": "The Terracotta Army guards Emperor Qin Shi Huang's tomb.",
  "agrigento-valley-of-temples": "The Valley of the Temples has Doric ruins older than the Parthenon.",
  "herculaneum": "Herculaneum was buried by the same eruption that hit Pompeii.",
  "ostia-antica": "Ostia Antica was ancient Rome's busy harbor town.",
  "segesta": "Segesta's temple was never finished, missing its roof and cella.",
  "selinunte": "Selinunte is one of the largest archaeological parks in Europe.",
  "paestum": "Paestum has three of the best-preserved Greek temples anywhere.",
  "jerash": "Jerash preserves one of the best-kept Roman colonnaded streets.",
  "hattusa": "Hattusa was the capital of the ancient Hittite Empire.",
  "mount-nemrut": "Mount Nemrut's summit hides giant royal stone heads.",
  "philae": "Philae's temple was relocated island to island to escape flooding.",
  "mohenjo-daro": "Mohenjo-daro had advanced drainage 4,500 years ago.",
  "gobekli-tepe": "Göbekli Tepe may be the oldest known temple on Earth.",
  "palenque": "Palenque's tomb of Pakal was found still sealed in 1952.",
  "copan": "Copán is famed for its detailed carved hieroglyphic stairway.",
  "uxmal": "Uxmal's Pyramid of the Magician has unusually rounded sides.",
  "monte-alban": "Monte Albán was one of the first true cities in the Americas.",
  "sigiriya": "Sigiriya's rock fortress rises 200 meters above the plain.",
  "hampi": "Hampi was once the second-largest city on Earth, in the 1500s.",
  "mahabalipuram": "Mahabalipuram's Shore Temple has withstood ocean waves for centuries.",
  "leptis-magna": "Leptis Magna was the birthplace of Roman emperor Septimius Severus.",
  "sabratha": "Sabratha's Roman theater once seated thousands of spectators.",
  "volubilis": "Volubilis was the capital of ancient Mauretania.",
  "timgad": "Timgad's Roman street grid is remarkably well preserved.",
  "djemila": "Djemila clings to a narrow mountain ridge in Algeria.",
  "cyrene": "Cyrene was founded by Greek colonists over 2,600 years ago.",
  "epidaurus": "Epidaurus's ancient theater is famed for its remarkable acoustics.",
  "delos": "Delos was believed to be the mythical birthplace of Apollo.",
  "caral": "Caral is among the oldest cities in the Americas, 5,000 years old.",
  "tiwanaku": "Tiwanaku sits over 3,800 meters above sea level in the Andes.",
  "chan-chan": "Chan Chan was the largest adobe city in the ancient world.",
  "ollantaytambo": "Ollantaytambo was a fortress guarding the road to Machu Picchu.",
  "skara-brae": "Skara Brae is a Stone Age village older than Stonehenge.",
  "newgrange": "Newgrange's chamber aligns with sunrise on the winter solstice.",
  "avebury": "Avebury's stone circle encloses part of a whole village.",
  "carnac-stones": "The Carnac Stones form the largest megalithic site on Earth.",
  "prambanan": "Prambanan is Indonesia's largest ancient Hindu temple complex.",
  "polonnaruwa": "Polonnaruwa was Sri Lanka's medieval royal capital.",
  "chaco-canyon": "Chaco Canyon's buildings align precisely with the solstices.",
  "mesa-verde-cliff-palace": "Cliff Palace is the largest cliff dwelling in North America.",
  "cahokia-mounds": "Cahokia was once larger than London at its peak, circa 1100.",
  "great-serpent-mound": "The Great Serpent Mound stretches over 400 meters long.",
  "anuradhapura": "Anuradhapura's sacred fig tree is over 2,300 years old.",
  "my-son-sanctuary": "My Son was a religious center of the ancient Champa kingdom.",
  "meroe-pyramids": "Sudan has more pyramids than Egypt, clustered at Meroë.",
  "aksum-obelisks": "Aksum's tallest obelisk once toppled and lay broken for centuries.",
  "kilwa-kisiwani": "Kilwa Kisiwani was a powerful medieval Swahili trading port.",
  "loulan-ruins": "Loulan was a Silk Road city swallowed by shifting desert sands.",
  "jiaohe-ruins": "Jiaohe was carved into a plateau between two river channels.",
  "ur-iraq": "Ur is traditionally named as the birthplace of Abraham.",
  "babylon-ruins": "Babylon was traditionally said to hold the legendary Hanging Gardens.",
  "nineveh": "Nineveh was the largest city in the world around 700 BC.",
  "byblos": "Byblos claims to be among the oldest continuously inhabited cities.",
  "jericho": "Jericho is considered one of the oldest cities ever inhabited.",
  "ai-khanoum": "Ai-Khanoum was a Greek city founded after Alexander's conquests.",
};
