// Episode 5 "Guess the Animal by Silhouette" — 98 items, absolute-difficulty calibrated.
// 25/24/25/24 split — dropped generic "Bird" and "Fish" (impossible tier) to avoid answer
// ambiguity against the specific species (dove/swan/duck/etc., shark/tropical-fish/etc.)
// already in the pool; moved "Chicken" medium->impossible after GATE 1 found its OpenMoji
// silhouette is a head-only shape, unrecognizable as a full animal outline. Images: OpenMoji
// color SVGs (CC BY-SA 4.0), all fills forced to solid black for a silhouette effect.
export const ANIMAL_SILHOUETTES_E05 = [
  // EASY (25)
  { slug: "elephant", name: "Elephant", level: "easy" },
  { slug: "giraffe", name: "Giraffe", level: "easy" },
  { slug: "kangaroo", name: "Kangaroo", level: "easy" },
  { slug: "zebra", name: "Zebra", level: "easy" },
  { slug: "lion", name: "Lion", level: "easy" },
  { slug: "tiger", name: "Tiger", level: "easy" },
  { slug: "horse", name: "Horse", level: "easy" },
  { slug: "cow", name: "Cow", level: "easy" },
  { slug: "dog", name: "Dog", level: "easy" },
  { slug: "cat", name: "Cat", level: "easy" },
  { slug: "rabbit", name: "Rabbit", level: "easy" },
  { slug: "owl", name: "Owl", level: "easy" },
  { slug: "penguin", name: "Penguin", level: "easy" },
  { slug: "dolphin", name: "Dolphin", level: "easy" },
  { slug: "whale", name: "Whale", level: "easy" },
  { slug: "shark", name: "Shark", level: "easy" },
  { slug: "octopus", name: "Octopus", level: "easy" },
  { slug: "snake", name: "Snake", level: "easy" },
  { slug: "turtle", name: "Turtle", level: "easy" },
  { slug: "duck", name: "Duck", level: "easy" },
  { slug: "camel", name: "Camel", level: "easy" },
  { slug: "deer", name: "Deer", level: "easy" },
  { slug: "monkey", name: "Monkey", level: "easy" },
  { slug: "gorilla", name: "Gorilla", level: "easy" },
  { slug: "pig", name: "Pig", level: "easy" },
  // MEDIUM (25)
  { slug: "wolf", name: "Wolf", level: "medium" },
  { slug: "fox", name: "Fox", level: "medium" },
  { slug: "leopard", name: "Leopard", level: "medium" },
  { slug: "bear", name: "Bear", level: "medium" },
  { slug: "polar-bear", name: "Polar Bear", level: "medium" },
  { slug: "koala", name: "Koala", level: "medium" },
  { slug: "panda", name: "Panda", level: "medium" },
  { slug: "donkey", name: "Donkey", level: "medium" },
  { slug: "bison", name: "Bison", level: "medium" },
  { slug: "goat", name: "Goat", level: "medium" },
  { slug: "mouse", name: "Mouse", level: "medium" },
  { slug: "bat", name: "Bat", level: "medium" },
  { slug: "rooster", name: "Rooster", level: "medium" },
  { slug: "eagle", name: "Eagle", level: "medium" },
  { slug: "parrot", name: "Parrot", level: "medium" },
  { slug: "flamingo", name: "Flamingo", level: "medium" },
  { slug: "peacock", name: "Peacock", level: "medium" },
  { slug: "frog", name: "Frog", level: "medium" },
  { slug: "crocodile", name: "Crocodile", level: "medium" },
  { slug: "lizard", name: "Lizard", level: "medium" },
  { slug: "crab", name: "Crab", level: "medium" },
  { slug: "butterfly", name: "Butterfly", level: "medium" },
  { slug: "spider", name: "Spider", level: "medium" },
  { slug: "hippopotamus", name: "Hippopotamus", level: "medium" },
  // HARD (25)
  { slug: "raccoon", name: "Raccoon", level: "hard" },
  { slug: "skunk", name: "Skunk", level: "hard" },
  { slug: "otter", name: "Otter", level: "hard" },
  { slug: "beaver", name: "Beaver", level: "hard" },
  { slug: "hedgehog", name: "Hedgehog", level: "hard" },
  { slug: "chipmunk", name: "Chipmunk", level: "hard" },
  { slug: "hamster", name: "Hamster", level: "hard" },
  { slug: "badger", name: "Badger", level: "hard" },
  { slug: "moose", name: "Moose", level: "hard" },
  { slug: "ox", name: "Ox", level: "hard" },
  { slug: "water-buffalo", name: "Water Buffalo", level: "hard" },
  { slug: "llama", name: "Llama", level: "hard" },
  { slug: "goose", name: "Goose", level: "hard" },
  { slug: "orca", name: "Orca", level: "hard" },
  { slug: "seal", name: "Seal", level: "hard" },
  { slug: "tropical-fish", name: "Tropical Fish", level: "hard" },
  { slug: "blowfish", name: "Blowfish", level: "hard" },
  { slug: "jellyfish", name: "Jellyfish", level: "hard" },
  { slug: "shrimp", name: "Shrimp", level: "hard" },
  { slug: "snail", name: "Snail", level: "hard" },
  { slug: "ant", name: "Ant", level: "hard" },
  { slug: "bee", name: "Bee", level: "hard" },
  { slug: "beetle", name: "Beetle", level: "hard" },
  { slug: "cockroach", name: "Cockroach", level: "hard" },
  { slug: "rhinoceros", name: "Rhinoceros", level: "hard" },
  // IMPOSSIBLE (25)
  { slug: "chicken", name: "Chicken", level: "impossible" },
  { slug: "mammoth", name: "Mammoth", level: "impossible" },
  { slug: "sauropod", name: "Sauropod", level: "impossible" },
  { slug: "t-rex", name: "T-Rex", level: "impossible" },
  { slug: "sloth", name: "Sloth", level: "impossible" },
  { slug: "boar", name: "Boar", level: "impossible" },
  { slug: "ram", name: "Ram", level: "impossible" },
  { slug: "ewe", name: "Ewe", level: "impossible" },
  { slug: "rat", name: "Rat", level: "impossible" },
  { slug: "dodo", name: "Dodo", level: "impossible" },
  { slug: "bactrian-camel", name: "Bactrian Camel", level: "impossible" },
  { slug: "orangutan", name: "Orangutan", level: "impossible" },
  { slug: "turkey", name: "Turkey", level: "impossible" },
  { slug: "dove", name: "Dove", level: "impossible" },
  { slug: "swan", name: "Swan", level: "impossible" },
  { slug: "squid", name: "Squid", level: "impossible" },
  { slug: "oyster", name: "Oyster", level: "impossible" },
  { slug: "scorpion", name: "Scorpion", level: "impossible" },
  { slug: "lobster", name: "Lobster", level: "impossible" },
  { slug: "cricket", name: "Cricket", level: "impossible" },
  { slug: "ladybug", name: "Ladybug", level: "impossible" },
  { slug: "mosquito", name: "Mosquito", level: "impossible" },
  { slug: "fly", name: "Fly", level: "impossible" },
  { slug: "worm", name: "Worm", level: "impossible" },
];
export default ANIMAL_SILHOUETTES_E05;
