// Episode 5 "Guess the Animal by Silhouette" — one verified ≤70-char fact per animal, keyed by slug.
// Verified via 4 parallel research agents (WebSearch-sourced) + quiz-fact-verifier pass.
export const ANIMAL_SILHOUETTES_E05_FACTS = {
  // EASY
  "elephant": "Elephants can't jump, unlike most other mammals.",
  "giraffe": "A giraffe's tongue can grow up to 20 inches long.",
  "kangaroo": "Kangaroos are physically unable to walk backwards.",
  "zebra": "No two zebras have the exact same stripe pattern.",
  "lion": "A lion's roar can be heard up to 5 miles away.",
  "tiger": "A tiger's stripes are on its skin, not just its fur.",
  "horse": "Horses can sleep both standing up and lying down.",
  "cow": "Cows form best friends and get stressed when apart.",
  "dog": "A dog's nose print is as unique as a fingerprint.",
  "cat": "Cats can't taste sweetness — they lack the receptor.",
  "rabbit": "Rabbits are physically unable to vomit.",
  "owl": "Owls can't move their eyeballs at all.",
  "penguin": "Emperor penguins can dive deeper than 500 meters.",
  "dolphin": "Dolphins give each other name-like whistle calls.",
  "whale": "A blue whale's call is louder than a jet engine.",
  "shark": "Sharks are older than trees by about 50 million years.",
  "octopus": "Octopuses have three hearts and blue blood.",
  "snake": "Snakes use their tongue to smell, not to taste.",
  "turtle": "Some turtles can breathe through their rear end.",
  "duck": "Ducks sleep with one eye open to watch for danger.",
  "camel": "A camel's hump stores fat, not water.",
  "deer": "Deer are colorblind and can't see the color orange.",
  "monkey": "Some monkeys use stone tools to crack open nuts.",
  "gorilla": "Gorillas share about 98% of their DNA with humans.",
  "pig": "Pigs have been trained to play simple video games.",

  // MEDIUM
  "wolf": "A wolf's howl can be heard up to 10 miles away.",
  "fox": "Foxes use Earth's magnetic field like a targeting scope.",
  "leopard": "A leopard can drag prey twice its own body weight up a tree.",
  "bear": "Grizzly bears can smell food from 18 miles away.",
  "polar-bear": "Polar bears have black skin hidden under white fur.",
  "koala": "Koala fingerprints look almost like human fingerprints.",
  "panda": "Giant pandas eat bamboo for up to 12 hours a day.",
  "donkey": "Donkeys can remember other donkeys for 25 years.",
  "bison": "American bison can clear a 5-foot fence from a stand.",
  "goat": "Goats have rectangular pupils and 320-degree vision.",
  "mouse": "A mouse's heart beats up to 600 times a minute.",
  "bat": "Bats are the only mammals capable of true flight.",
  "chicken": "Chickens can recognize over 100 different faces.",
  "rooster": "A rooster's ear canal closes to protect its hearing.",
  "eagle": "Bald eagles can spot fish from a mile away.",
  "parrot": "Some cockatoos can live over 80 years.",
  "flamingo": "Flamingo chicks are born gray, not pink.",
  "peacock": "Only males are called peacocks; females are peahens.",
  "frog": "Wood frogs freeze solid in winter and thaw alive.",
  "crocodile": "A crocodile's tongue is attached, so it can't stick it out.",
  "lizard": "Many lizards can shed their tail to escape predators.",
  "crab": "Most crabs can walk in any direction, not just sideways.",
  "butterfly": "Butterflies taste food using sensors on their feet.",
  "spider": "Spider silk is stronger than steel by weight.",
  "hippopotamus": "Hippos secrete a red oily fluid that acts as sunscreen.",

  // HARD
  "raccoon": "Raccoons can remember how to solve a puzzle for 3 years.",
  "skunk": "Skunks can accurately spray predators up to 15 feet away.",
  "otter": "Sea otters hold hands while sleeping so they don't drift apart.",
  "beaver": "A beaver's teeth are orange because they're reinforced with iron.",
  "hedgehog": "Hedgehogs chew new smells into foam and lick it onto their spines.",
  "chipmunk": "A chipmunk's cheek pouches can stretch 3 times its head's size.",
  "hamster": "Wild hamsters can run up to 5-9 miles foraging in a single night.",
  "badger": "Badgers team up with coyotes to hunt prairie dogs together.",
  "moose": "Moose can dive 20 feet underwater to eat plants on lake bottoms.",
  "ox": "Oxen have pulled plows and carts for over 6,000 years.",
  "water-buffalo": "Water buffalo have the widest horns of any living animal.",
  "llama": "Llamas hum to express feelings like curiosity or anxiety.",
  "goose": "A Scotch whisky distillery once used geese as security guards.",
  "orca": "Orcas, or killer whales, are actually the world's largest dolphins.",
  "seal": "Elephant seals can dive nearly 1.5 miles deep in the ocean.",
  "tropical-fish": "Reefs cover under 1% of the seafloor yet hold 25% of fish species.",
  "blowfish": "A pufferfish's toxin can be 1,000+ times deadlier than cyanide.",
  "jellyfish": "Jellyfish have no brain, no heart, and no blood at all.",
  "shrimp": "A shrimp's heart is located inside its head, not its chest.",
  "snail": "Some snails can hibernate inside their shell for up to 3 years.",
  "ant": "Some queen ants can live up to 30 years, unlike worker ants.",
  "bee": "Bees dance to tell hivemates exactly where flowers are.",
  "beetle": "Beetles make up roughly 25% of all known animal species.",
  "cockroach": "A cockroach can survive up to a week without its head.",
  "rhinoceros": "A rhino's horn is made of keratin, just like human hair and nails.",

  // IMPOSSIBLE
  "mammoth": "Woolly mammoths were still alive when the pyramids were built.",
  "sauropod": "Sauropods had hollow, air-filled bones like modern birds.",
  "t-rex": "T-Rex lived closer in time to humans than to Stegosaurus.",
  "sloth": "Sloths poop only once a week, losing up to 1/3 body weight.",
  "boar": "A wild boar once swam 7 miles from France to an island.",
  "ram": "A ram can charge and headbutt at speeds up to 30 mph.",
  "ewe": "Ewes can remember other sheep's faces for over two years.",
  "rat": "Rats laugh — they emit ultrasonic chirps when tickled.",
  "dodo": "Dodos were roughly the size of a large turkey.",
  "bactrian-camel": "A thirsty Bactrian camel can drink 30 gallons in 13 minutes.",
  "orangutan": "Orangutans share about 97% of their DNA with humans.",
  "turkey": "Wild turkeys can run 25 mph and fly up to 55 mph.",
  "dove": "A dove's crop milk is richer in protein than cow's milk.",
  "swan": "A tundra swan can have over 25,000 feathers on its body.",
  "squid": "A giant squid's eyeball can be as big as a basketball.",
  "oyster": "Oysters can switch back and forth between male and female.",
  "scorpion": "Nearly every scorpion glows greenish-blue under UV light.",
  "lobster": "Lobsters were once so common they were used as fertilizer.",
  "cricket": "You can guess the temperature just by counting cricket chirps.",
  "ladybug": "Ladybugs ooze smelly yellow blood when they feel threatened.",
  "mosquito": "Only female mosquitoes bite; males just drink nectar.",
  "fly": "A housefly's wings can beat about 200 times every second.",
  "worm": "Earthworms have five pairs of hearts, not just one.",
};
export default ANIMAL_SILHOUETTES_E05_FACTS;
