// Episode 1 "Guess the Animal" — 100 items, absolute-difficulty calibrated (25/tier).
// Calibrated via quiz-difficulty-calibration methodology (global recognizability from a photo).
export const ANIMALS_E01 = [
  // EASY (25) — ~70-95% globally recognize
  { slug: "dog", name: "Dog", level: "easy" },
  { slug: "cat", name: "Cat", level: "easy" },
  { slug: "horse", name: "Horse", level: "easy" },
  { slug: "cow", name: "Cow", level: "easy" },
  { slug: "giraffe", name: "Giraffe", level: "easy" },
  { slug: "tiger", name: "Tiger", level: "easy" },
  { slug: "giant-panda", name: "Giant Panda", level: "easy" },
  { slug: "chicken", name: "Chicken", level: "easy" },
  { slug: "pig", name: "Pig", level: "easy" },
  { slug: "zebra", name: "Zebra", level: "easy" },
  { slug: "dolphin", name: "Dolphin", level: "easy" },
  { slug: "penguin", name: "Penguin", level: "easy" },
  { slug: "rabbit", name: "Rabbit", level: "easy" },
  { slug: "duck", name: "Duck", level: "easy" },
  { slug: "great-white-shark", name: "Great White Shark", level: "easy" },
  { slug: "sheep", name: "Sheep", level: "easy" },
  { slug: "gorilla", name: "Gorilla", level: "easy" },
  { slug: "camel", name: "Camel", level: "easy" },
  { slug: "polar-bear", name: "Polar Bear", level: "easy" },
  { slug: "chimpanzee", name: "Chimpanzee", level: "easy" },
  { slug: "crocodile", name: "Crocodile", level: "easy" },
  { slug: "wolf", name: "Wolf", level: "easy" },
  { slug: "owl", name: "Owl", level: "easy" },
  { slug: "fox", name: "Fox", level: "easy" },
  { slug: "deer", name: "Deer", level: "easy" },

  // MEDIUM (25) — ~35-70%
  { slug: "cheetah", name: "Cheetah", level: "medium" },
  { slug: "kangaroo", name: "Kangaroo", level: "medium" },
  { slug: "eagle", name: "Eagle", level: "medium" },
  { slug: "hippopotamus", name: "Hippopotamus", level: "medium" },
  { slug: "rhinoceros", name: "Rhinoceros", level: "medium" },
  { slug: "peacock", name: "Peacock", level: "medium" },
  { slug: "octopus", name: "Octopus", level: "medium" },
  { slug: "parrot", name: "Parrot", level: "medium" },
  { slug: "sloth", name: "Sloth", level: "medium" },
  { slug: "flamingo", name: "Flamingo", level: "medium" },
  { slug: "raccoon", name: "Raccoon", level: "medium" },
  { slug: "starfish", name: "Starfish", level: "medium" },
  { slug: "otter", name: "Otter", level: "medium" },
  { slug: "orangutan", name: "Orangutan", level: "medium" },
  { slug: "leopard", name: "Leopard", level: "medium" },
  { slug: "jellyfish", name: "Jellyfish", level: "medium" },
  { slug: "walrus", name: "Walrus", level: "medium" },
  { slug: "bison", name: "Bison", level: "medium" },
  { slug: "moose", name: "Moose", level: "medium" },
  { slug: "platypus", name: "Platypus", level: "medium" },
  { slug: "hyena", name: "Hyena", level: "medium" },
  { slug: "red-panda", name: "Red Panda", level: "medium" },
  { slug: "snow-leopard", name: "Snow Leopard", level: "medium" },
  { slug: "vulture", name: "Vulture", level: "medium" },
  { slug: "capybara", name: "Capybara", level: "medium" },

  // HARD (25) — ~10-35%
  { slug: "komodo-dragon", name: "Komodo Dragon", level: "hard" },
  { slug: "meerkat", name: "Meerkat", level: "hard" },
  { slug: "armadillo", name: "Armadillo", level: "hard" },
  { slug: "tasmanian-devil", name: "Tasmanian Devil", level: "hard" },
  { slug: "wombat", name: "Wombat", level: "hard" },
  { slug: "narwhal", name: "Narwhal", level: "hard" },
  { slug: "quokka", name: "Quokka", level: "hard" },
  { slug: "manatee", name: "Manatee", level: "hard" },
  { slug: "aardvark", name: "Aardvark", level: "hard" },
  { slug: "echidna", name: "Echidna", level: "hard" },
  { slug: "tapir", name: "Tapir", level: "hard" },
  { slug: "mandrill", name: "Mandrill", level: "hard" },
  { slug: "proboscis-monkey", name: "Proboscis Monkey", level: "hard" },
  { slug: "okapi", name: "Okapi", level: "hard" },
  { slug: "tarsier", name: "Tarsier", level: "hard" },
  { slug: "honey-badger", name: "Honey Badger", level: "hard" },
  { slug: "fennec-fox", name: "Fennec Fox", level: "hard" },
  { slug: "secretary-bird", name: "Secretary Bird", level: "hard" },
  { slug: "cassowary", name: "Cassowary", level: "hard" },
  { slug: "kiwi-bird", name: "Kiwi Bird", level: "hard" },
  { slug: "dhole", name: "Dhole", level: "hard" },
  { slug: "binturong", name: "Binturong", level: "hard" },
  { slug: "quoll", name: "Quoll", level: "hard" },
  { slug: "numbat", name: "Numbat", level: "hard" },
  { slug: "pygmy-hippopotamus", name: "Pygmy Hippopotamus", level: "hard" },

  // IMPOSSIBLE (25) — <10%, hardest <3%
  { slug: "saiga-antelope", name: "Saiga Antelope", level: "impossible" },
  { slug: "fossa", name: "Fossa", level: "impossible" },
  { slug: "solenodon", name: "Solenodon", level: "impossible" },
  { slug: "pudu", name: "Pudu", level: "impossible" },
  { slug: "markhor", name: "Markhor", level: "impossible" },
  { slug: "gharial", name: "Gharial", level: "impossible" },
  { slug: "sun-bear", name: "Sun Bear", level: "impossible" },
  { slug: "kinkajou", name: "Kinkajou", level: "impossible" },
  { slug: "maned-wolf", name: "Maned Wolf", level: "impossible" },
  { slug: "aardwolf", name: "Aardwolf", level: "impossible" },
  { slug: "tuatara", name: "Tuatara", level: "impossible" },
  { slug: "babirusa", name: "Babirusa", level: "impossible" },
  { slug: "takin", name: "Takin", level: "impossible" },
  { slug: "bongo-antelope", name: "Bongo Antelope", level: "impossible" },
  { slug: "nyala", name: "Nyala", level: "impossible" },
  { slug: "gerenuk", name: "Gerenuk", level: "impossible" },
  { slug: "chevrotain", name: "Chevrotain", level: "impossible" },
  { slug: "colugo", name: "Colugo", level: "impossible" },
  { slug: "sifaka", name: "Sifaka", level: "impossible" },
  { slug: "indri", name: "Indri", level: "impossible" },
  { slug: "kakapo", name: "Kakapo", level: "impossible" },
  { slug: "kagu", name: "Kagu", level: "impossible" },
  { slug: "pacarana", name: "Pacarana", level: "impossible" },
  { slug: "olinguito", name: "Olinguito", level: "impossible" },
  { slug: "saola", name: "Saola", level: "impossible" },
];
export default ANIMALS_E01;
