// Episode 1 "Guess the Animal" — one verified ≤70-char fact per item, keyed by slug.
// Verified via quiz-fact-verifier agent pass (2 corrections applied: sloth, quokka).
export const ANIMALS_E01_FACTS = {
  "dog": "A dog's nose print is unique, like a human fingerprint.",
  "cat": "Cats can't taste sweetness at all.",
  "horse": "Horses can sleep both lying down and standing up.",
  "cow": "A cow's eyes give it a nearly 360-degree view.",
  "giraffe": "A giraffe's tongue can grow up to 18 inches long.",
  "tiger": "A tiger's skin is striped, just like its fur.",
  "giant-panda": "Giant pandas have an extra 'thumb' to grip bamboo.",
  "chicken": "Chickens can recognize and remember individual faces.",
  "pig": "Pigs are among the most intelligent farm animals.",
  "zebra": "Every zebra has a unique stripe pattern, like a fingerprint.",
  "dolphin": "Dolphins call each other by unique signature whistles.",
  "penguin": "Emperor penguins can dive over 500 meters deep.",
  "rabbit": "Rabbits can see nearly 360 degrees around them.",
  "duck": "Ducks have waterproof feathers thanks to an oil gland.",
  "great-white-shark": "Great white sharks have an extraordinary sense of smell.",
  "sheep": "Sheep can recognize and remember individual faces.",
  "gorilla": "Gorillas are mostly herbivores, eating plants and fruit.",
  "camel": "Camels store fat, not water, in their humps.",
  "polar-bear": "Polar bears have black skin under their white fur.",
  "chimpanzee": "Chimpanzees share about 98% of their DNA with humans.",
  "crocodile": "A crocodile's tongue is attached and can't move much.",
  "wolf": "A wolf pack is usually led by a breeding pair.",
  "owl": "Owls can turn their heads about 270 degrees.",
  "fox": "Foxes use Earth's magnetic field to help them hunt.",
  "deer": "Male deer regrow their antlers completely every year.",
  "cheetah": "Cheetahs can accelerate faster than most sports cars.",
  "kangaroo": "Kangaroos cannot walk backwards easily.",
  "eagle": "Eagles have eyesight several times sharper than humans.",
  "hippopotamus": "Hippos secrete their own natural sunscreen.",
  "rhinoceros": "A rhino's horn is made of keratin, like hair.",
  "peacock": "Only male peafowl are technically called peacocks.",
  "octopus": "Octopuses have three hearts and blue blood.",
  "parrot": "Some parrot species can live more than 80 years.",
  "sloth": "Sloths halve their heart rate to conserve oxygen while swimming.",
  "flamingo": "Flamingos get their pink color from the food they eat.",
  "raccoon": "Raccoons have extremely sensitive front paws.",
  "starfish": "Starfish have no brain but can regrow lost arms.",
  "otter": "Sea otters hold hands while sleeping so they don't drift apart.",
  "orangutan": "Orangutans share about 97% of their DNA with humans.",
  "leopard": "Leopards can drag prey twice their weight up trees.",
  "jellyfish": "Jellyfish have no brain, heart, or bones.",
  "walrus": "A walrus's tusks are actually elongated canine teeth.",
  "bison": "American bison can jump nearly six feet high.",
  "moose": "Moose can dive completely underwater to feed.",
  "platypus": "Male platypuses have venomous spurs on their legs.",
  "hyena": "Female spotted hyenas are usually more dominant than males.",
  "red-panda": "Red pandas wrap their tails around themselves for warmth.",
  "snow-leopard": "Snow leopards cannot roar like other big cats.",
  "vulture": "Vultures' stomach acid can destroy deadly bacteria.",
  "capybara": "Capybaras are the largest rodents in the world.",
  "komodo-dragon": "Komodo dragons have venom glands, not just dirty saliva.",
  "meerkat": "Meerkats post sentries to watch for predators while others feed.",
  "armadillo": "Nine-banded armadillos always give birth to identical quadruplets.",
  "tasmanian-devil": "Tasmanian devils have the strongest bite force for their size.",
  "wombat": "Wombats produce cube-shaped droppings so they don't roll away.",
  "narwhal": "A narwhal's tusk is actually a long spiral canine tooth.",
  "quokka": "Rottnest Island was named after quokkas, mistaken for giant rats.",
  "manatee": "Manatees' closest living relatives are elephants, not dolphins.",
  "aardvark": "An aardvark can eat over 50,000 insects in a single night.",
  "echidna": "Echidnas and platypuses are the only egg-laying mammals alive.",
  "tapir": "Tapirs are more closely related to horses and rhinos than pigs.",
  "mandrill": "Mandrills are the world's most colorful mammal species.",
  "proboscis-monkey": "Male proboscis monkeys use their big nose to amplify calls.",
  "okapi": "The okapi is the giraffe's only living close relative.",
  "tarsier": "Tarsiers are the only primates that eat solely meat, no plants.",
  "honey-badger": "A honey badger's thick skin can shrug off bee stings and bites.",
  "fennec-fox": "Fennec foxes have huge ears that help release body heat.",
  "secretary-bird": "A secretary bird's kick can hit with five times its body weight.",
  "cassowary": "Cassowaries have a dagger-like claw that can reach 12cm long.",
  "kiwi-bird": "A kiwi egg can weigh up to a fifth of the mother's body weight.",
  "dhole": "Dholes, or Asiatic wild dogs, hunt in packs and whistle to talk.",
  "binturong": "A binturong's scent famously smells like buttered popcorn.",
  "quoll": "Quolls are carnivorous marsupials with distinctive spotted fur.",
  "numbat": "A numbat can eat up to 20,000 termites in a single day.",
  "pygmy-hippopotamus": "Pygmy hippos are shy, solitary, and mostly nocturnal.",
  "saiga-antelope": "Its bulbous nose filters dust and warms cold air.",
  "fossa": "Madagascar's largest predator is a mongoose relative.",
  "solenodon": "It's one of the few mammals with venomous saliva.",
  "pudu": "The pudu is the world's smallest deer species.",
  "markhor": "Its corkscrew horns can grow over five feet long.",
  "gharial": "Males grow a bulbous nose knob called a 'ghara'.",
  "sun-bear": "Sun bears have the longest tongue of any bear.",
  "kinkajou": "This raccoon relative has a prehensile tail.",
  "maned-wolf": "Its urine smells strikingly like cannabis.",
  "aardwolf": "It can eat up to 300,000 termites in one night.",
  "tuatara": "It has a light-sensing 'third eye' on its head.",
  "babirusa": "Male tusks curve backward, growing into the skull.",
  "takin": "Its oily coat repels rain in the Himalayas.",
  "bongo-antelope": "It's the largest forest antelope in Africa.",
  "nyala": "It's considered the most sexually dimorphic antelope.",
  "gerenuk": "It stands on hind legs to browse tall bushes.",
  "chevrotain": "This mouse-deer is the smallest hoofed mammal.",
  "colugo": "It's the best gliding mammal, but it cannot fly.",
  "sifaka": "It's nicknamed the 'dancing lemur' for its hops.",
  "indri": "Its call can be heard over a mile through forest.",
  "kakapo": "It's the world's only flightless, nocturnal parrot.",
  "kagu": "This flightless bird makes a dog-like barking call.",
  "pacarana": "It's the last species in an ancient rodent family.",
  "olinguito": "It was identified as a new species only in 2013.",
  "saola": "Discovered in 1992, it's nicknamed the Asian unicorn.",
};
export default ANIMALS_E01_FACTS;
