// E41 "Guess the App Icon" — recognizability of the ICON MARK ALONE, not company fame.
// Israel-screened: excluded ICQ, Waze, Moovit, Gett, Wix, Fiverr, monday.com, Payoneer,
// Lightricks, ironSource, Playtika-owned games, Houzz, Talkspace, "Yo".
export const APP_ICONS_E41 = [
  // EASY (18)
  { slug: "whatsapp", name: "WhatsApp", category: "messaging", level: "easy" },
  { slug: "instagram", name: "Instagram", category: "social", level: "easy" },
  { slug: "facebook", name: "Facebook", category: "social", level: "easy" },
  { slug: "youtube", name: "YouTube", category: "streaming", level: "easy" },
  { slug: "tiktok", name: "TikTok", category: "social", level: "easy" },
  { slug: "google", name: "Google", category: "utility", level: "easy" },
  { slug: "gmail", name: "Gmail", category: "productivity", level: "easy" },
  { slug: "google-maps", name: "Google Maps", category: "utility", level: "easy" },
  { slug: "x-twitter", name: "X (Twitter)", category: "social", level: "easy" },
  { slug: "netflix", name: "Netflix", category: "streaming", level: "easy" },
  { slug: "spotify", name: "Spotify", category: "streaming", level: "easy" },
  { slug: "uber", name: "Uber", category: "travel", level: "easy" },
  { slug: "amazon", name: "Amazon", category: "shopping", level: "easy" },
  { slug: "paypal", name: "PayPal", category: "finance", level: "easy" },
  { slug: "zoom", name: "Zoom", category: "productivity", level: "easy" },
  { slug: "telegram", name: "Telegram", category: "messaging", level: "easy" },
  { slug: "facebook-messenger", name: "Facebook Messenger", category: "messaging", level: "easy" },
  { slug: "snapchat", name: "Snapchat", category: "social", level: "easy" },

  // MEDIUM (18)
  { slug: "linkedin", name: "LinkedIn", category: "social", level: "medium" },
  { slug: "pinterest", name: "Pinterest", category: "social", level: "medium" },
  { slug: "discord", name: "Discord", category: "social", level: "medium" },
  { slug: "reddit", name: "Reddit", category: "social", level: "medium" },
  { slug: "skype", name: "Skype", category: "messaging", level: "medium" },
  { slug: "wechat", name: "WeChat", category: "messaging", level: "medium" },
  { slug: "twitch", name: "Twitch", category: "streaming", level: "medium" },
  { slug: "airbnb", name: "Airbnb", category: "travel", level: "medium" },
  { slug: "ebay", name: "eBay", category: "shopping", level: "medium" },
  { slug: "google-drive", name: "Google Drive", category: "productivity", level: "medium" },
  { slug: "dropbox", name: "Dropbox", category: "productivity", level: "medium" },
  { slug: "roblox", name: "Roblox", category: "game", level: "medium" },
  { slug: "booking-com", name: "Booking.com", category: "travel", level: "medium" },
  { slug: "duolingo", name: "Duolingo", category: "education", level: "medium" },
  { slug: "shazam", name: "Shazam", category: "music", level: "medium" },
  { slug: "vlc", name: "VLC Media Player", category: "utility", level: "medium" },
  { slug: "tripadvisor", name: "TripAdvisor", category: "travel", level: "medium" },
  { slug: "google-photos", name: "Google Photos", category: "utility", level: "medium" },

  // HARD (18)
  { slug: "notion", name: "Notion", category: "productivity", level: "hard" },
  { slug: "slack", name: "Slack", category: "productivity", level: "hard" },
  { slug: "trello", name: "Trello", category: "productivity", level: "hard" },
  { slug: "threads", name: "Threads", category: "social", level: "hard" },
  { slug: "bereal", name: "BeReal", category: "social", level: "hard" },
  { slug: "signal", name: "Signal", category: "messaging", level: "hard" },
  { slug: "capcut", name: "CapCut", category: "entertainment", level: "hard" },
  { slug: "headspace", name: "Headspace", category: "health", level: "hard" },
  { slug: "calm", name: "Calm", category: "health", level: "hard" },
  { slug: "fitbit", name: "Fitbit", category: "health", level: "hard" },
  { slug: "strava", name: "Strava", category: "health", level: "hard" },
  { slug: "venmo", name: "Venmo", category: "finance", level: "hard" },
  { slug: "robinhood", name: "Robinhood", category: "finance", level: "hard" },
  { slug: "coinbase", name: "Coinbase", category: "finance", level: "hard" },
  { slug: "line-app", name: "LINE", category: "messaging", level: "hard" },
  { slug: "letterboxd", name: "Letterboxd", category: "entertainment", level: "hard" },
  { slug: "evernote", name: "Evernote", category: "productivity", level: "hard" },
  { slug: "revolut", name: "Revolut", category: "finance", level: "hard" },

  // IMPOSSIBLE (18)
  { slug: "obsidian", name: "Obsidian", category: "productivity", level: "impossible" },
  { slug: "todoist", name: "Todoist", category: "productivity", level: "impossible" },
  { slug: "figma", name: "Figma", category: "design", level: "impossible" },
  { slug: "postman", name: "Postman", category: "dev-tool", level: "impossible" },
  { slug: "onepassword", name: "1Password", category: "security", level: "impossible" },
  { slug: "bitwarden", name: "Bitwarden", category: "security", level: "impossible" },
  { slug: "feedly", name: "Feedly", category: "utility", level: "impossible" },
  { slug: "asana", name: "Asana", category: "productivity", level: "impossible" },
  { slug: "basecamp", name: "Basecamp", category: "productivity", level: "impossible" },
  { slug: "yelp", name: "Yelp", category: "utility", level: "impossible" },
  { slug: "nextdoor", name: "Nextdoor", category: "social", level: "impossible" },
  { slug: "goodreads", name: "Goodreads", category: "entertainment", level: "impossible" },
  { slug: "flipboard", name: "Flipboard", category: "utility", level: "impossible" },
  { slug: "overcast", name: "Overcast", category: "entertainment", level: "impossible" },
  { slug: "anki", name: "Anki", category: "education", level: "impossible" },
  { slug: "toggl-track", name: "Toggl Track", category: "productivity", level: "impossible" },
  { slug: "grab", name: "Grab", category: "travel", level: "impossible" },
  { slug: "kakaotalk", name: "KakaoTalk", category: "messaging", level: "impossible" },
];
