export const APP_ICONS_E41_FACTS = {
  "whatsapp": "Meta bought WhatsApp in 2014 for around $19 billion.",
  "instagram": "Instagram's original name was 'Burbn' before its 2010 launch.",
  "facebook": "Facebook is blue because Zuckerberg is red-green colorblind.",
  "youtube": "The first YouTube video, 'Me at the zoo,' was posted in 2005.",
  "tiktok": "TikTok is called Douyin in mainland China, its home market.",
  "google": "Google's four-color logo intentionally breaks its own brand rules.",
  "gmail": "Gmail launched on April 1, 2004, and was mistaken for a prank.",
  "google-maps": "Google Maps launched in 2005 and now covers 250+ countries.",
  "x-twitter": "Twitter rebranded to X in 2023, dropping its iconic bird logo.",
  "netflix": "Netflix began in 1997 as a DVD-by-mail rental service.",
  "spotify": "Spotify officially launched to the public in October 2008.",
  "uber": "Uber was originally called UberCab when it launched in 2009.",
  "amazon": "Amazon's logo arrow runs A to Z and doubles as a smile.",
  "paypal": "PayPal began in 1998 as a security firm called Confinity.",
  "zoom": "Zoom's daily meeting users grew about 30x during 2020.",
  "telegram": "Telegram was founded by the brothers who built VKontakte.",
  "facebook-messenger": "Facebook forced users onto standalone Messenger in 2014.",
  "snapchat": "Snapchat's ghost mascot is officially named Ghostface Chillah.",

  "linkedin": "LinkedIn launched from a founder's living room in 2003.",
  "pinterest": "Pinterest's name blends the words 'pin' and 'interest.'",
  "discord": "Discord was originally built for gamers, launching in 2015.",
  "reddit": "Reddit's alien mascot is officially named Snoo.",
  "skype": "Skype's name evolved from the phrase 'Sky peer-to-peer.'",
  "wechat": "WeChat has over a billion monthly users, mostly in China.",
  "twitch": "Twitch spun off from a lifecasting site called Justin.tv.",
  "airbnb": "Airbnb began by renting air mattresses in a San Francisco flat.",
  "ebay": "eBay was founded in 1995 under the original name AuctionWeb.",
  "google-drive": "Google Drive launched in 2012 with 5GB of free storage.",
  "dropbox": "Dropbox's early demo video waitlist grew to 75,000 overnight.",
  "roblox": "Roblox lets players build and publish their own games.",
  "booking-com": "Booking.com started as a small Dutch startup in 1996.",
  "duolingo": "Duolingo's owl mascot Duo is known for guilt-trip reminders.",
  "shazam": "Shazam once worked by dialing a phone number, before smartphones.",
  "vlc": "VLC's traffic-cone icon has never had an official explanation.",
  "tripadvisor": "TripAdvisor was founded in 2000 near Boston, Massachusetts.",
  "google-photos": "Google Photos offered unlimited free storage until mid-2021.",

  "notion": "Notion nearly shut down before pivoting to its current app.",
  "slack": "Slack began as an internal tool for a failed video game studio.",
  "trello": "Trello's board layout is based on the Japanese kanban method.",
  "threads": "Threads gained 100 million signups within its first five days.",
  "bereal": "BeReal sends its daily photo notification at a random time.",
  "signal": "Signal is run by a nonprofit foundation, not a company.",
  "capcut": "CapCut is made by ByteDance, the company behind TikTok.",
  "headspace": "Headspace was co-founded by a former Buddhist monk.",
  "calm": "Calm's sleep stories have been narrated by Matthew McConaughey.",
  "fitbit": "Fitbit's first tracker shipped to backers in 2009.",
  "strava": "Strava means 'to strive' in Swedish.",
  "venmo": "Venmo began as a way to split a restaurant bill by text.",
  "robinhood": "Robinhood helped pioneer commission-free stock trading in the US.",
  "coinbase": "Coinbase went public via a direct listing on Nasdaq in 2021.",
  "line-app": "LINE was created in Japan after the 2011 earthquake and tsunami.",
  "letterboxd": "Letterboxd was built by two friends in New Zealand.",
  "evernote": "Evernote's elephant logo nods to 'elephants never forget.'",
  "revolut": "Revolut started as a prepaid travel card company in 2015.",

  "obsidian": "Obsidian stores all notes as local, plain-text markdown files.",
  "todoist": "Todoist was created solo by developer Amir Salihefendić in 2007.",
  "figma": "Figma runs entirely in a web browser, with no install needed.",
  "postman": "Postman began as a side-project Chrome extension in 2012.",
  "onepassword": "1Password was built by a small independent team in Canada.",
  "bitwarden": "Bitwarden's code is fully open-source and publicly auditable.",
  "feedly": "Feedly surged in users after Google Reader shut down in 2013.",
  "asana": "Asana was founded by a Facebook co-founder and an engineer.",
  "basecamp": "Basecamp's maker, 37signals, also created Ruby on Rails.",
  "yelp": "Yelp originally launched as an email referral network in 2004.",
  "nextdoor": "Nextdoor requires members to verify a real home address.",
  "goodreads": "Goodreads was acquired by Amazon back in 2013.",
  "flipboard": "Flipboard turns social feeds into a magazine-style layout.",
  "overcast": "Overcast is a podcast app built by one independent developer.",
  "anki": "Anki uses spaced repetition, a memory trick, for flashcards.",
  "toggl-track": "Toggl Track was built by a small team based in Estonia.",
  "grab": "Grab began as a taxi-hailing app in Malaysia back in 2012.",
  "kakaotalk": "KakaoTalk is used by over 90% of smartphone users in Korea.",
};
