export const APPLE_E66_FACTS = {
  "airpods-1st-generation": "Mocked online as 'toothbrush heads' when first unveiled.",
  "iphone-x": "First iPhone with Face ID and no home button, priced at $999.",
  "apple-watch-1st-generation": "Apple's first all-new product category since the iPad.",
  "iphone-6": "iPhone 6 and 6 Plus combined are Apple's best-selling iPhones ever.",
  "iphone-11": "Introduced the dual-camera square bump design on a non-Pro iPhone.",
  "airpods-pro": "First AirPods with silicone ear tips and active noise cancellation.",
  "ipad-1st-generation": "Sold 300,000 units on its very first day on sale.",
  "iphone-12": "Brought back flat edges, echoing the iPhone 4's design language.",
  "imac-g3": "Original Bondi Blue color started a translucent-plastic design fad.",
  "macbook-air-2008": "Revealed by Steve Jobs sliding it out of a manila envelope.",
  "iphone-14-pro": "Introduced the pill-shaped Dynamic Island cutout.",
  "macintosh-128k": "Launched with Apple's famous '1984' Super Bowl commercial.",
  "macbook-pro-2021-m1-pro": "Brought back MagSafe charging and a screen notch.",
  "ipad-10th-generation": "First base iPad with flat edges and colorful anodized aluminum.",
  "imac-2021-m1": "Just 11.5mm thin, sold in seven bright colors.",
  "ipod-1st-generation": "Marketed with the tagline '1,000 songs in your pocket'.",
  "apple-watch-ultra": "Rugged titanium case rated for scuba diving to 40 meters.",
  "macbook-pro-2016-touch-bar": "Replaced the function-key row with a touch-sensitive OLED strip.",
  "ipad-pro-3rd-generation": "First iPad with Face ID and a Lightning-free USB-C port.",
  "macbook-2006-white": "Replaced the iBook as Apple's white polycarbonate consumer laptop.",
  "macbook-air-2020-m1": "First MacBook Air with Apple silicon and a completely fanless design.",
  "ipod-classic": "Final click-wheel iPod, offered with up to 160GB storage.",
  "ipod-touch-1st-generation": "Essentially an iPhone without the phone, camera, or GPS.",
  "ipod-nano-1st-generation": "Replaced the iPod Mini and was thinner than a pencil.",
  "airpods-max": "Apple's first over-ear headphones, with a stainless-steel headband.",
  "iphone-3g": "First iPhone with a plastic back, sold in black or white.",
  "imac-g4": "Nicknamed the 'lamp' or 'sunflower' for its dome-and-arm shape.",
  "ipod-mini": "First iPod sold in multiple anodized aluminum colors.",
  "apple-watch-series-4": "First redesign with a larger, edge-to-edge display.",
  "iphone-5": "First iPhone with an aluminum unibody and a taller 4-inch screen.",
  "ipad-mini-1st-generation": "Shrunk the iPad to a 7.9-inch screen without a Retina display.",
  "mac-mini-2020-m1": "First Mac mini with Apple's own M1 chip instead of Intel.",
  "apple-tv-4k": "Current small black-puck streaming box with a Siri Remote.",
  "ipad-air-1st-generation": "20% thinner and 28% lighter than the iPad it replaced.",
  "macbook-pro-2008-unibody": "First laptop milled from a single block of aluminum.",
  "ipod-shuffle-1st-generation": "Shaped like a USB stick with no screen at all.",
  "ibook-clamshell": "Rounded, colorful laptop with a built-in carrying handle.",
  "apple-vision-pro": "Apple's first headset, controlled entirely by eyes, hands, and voice.",
  "ipad-mini-6th-generation": "First iPad mini redesign since 2012, with flat edges and USB-C.",
  "mac-pro-2006": "Nicknamed the 'cheese grater' for its perforated aluminum front.",
  "powerbook-g4-titanium": "First laptop with a titanium case and a widescreen display.",
  "homepod": "Cylindrical smart speaker with a glowing touch-sensitive top.",
  "ipod-nano-6th-generation": "Shrunk to a square touchscreen small enough to wear as a watch.",
  "apple-tv-1st-generation": "Steve Jobs originally called it a 'hobby' product.",
  "power-mac-g4-cube": "Fanless 8-inch cube; a commercial flop with only 150,000 sold.",
  "mac-pro-2019": "Revived the cheese-grater look with a lattice-drilled aluminum shell.",
  "apple-pencil-1st-generation": "Charges by plugging directly into the iPad's Lightning port.",
  "imac-pro": "Only iMac ever sold exclusively in a dark 'space gray' finish.",
  "mac-studio": "Compact square desktop about the height of a stack of pucks.",
  "macintosh-se": "First compact Mac with an internal expansion slot.",
  "emac": "Budget all-in-one built for schools; the 'e' stood for education.",
  "powerbook-100": "First laptop with the trackball placed in front of the keyboard.",
  "powerbook-g3": "Nicknamed 'Kanga'; the last PowerBook with a beige case.",
  "ipod-shuffle-3rd-generation": "Had no buttons at all; controls moved to the earbud cable.",
  "airport-extreme-base-station": "White flying-saucer-shaped router; Apple's first 802.11g base station.",
  "powerbook-duo": "Ultra-light subnotebook that could slide into a desktop Duo Dock.",
  "ipod-hi-fi": "Apple's boombox-style speaker dock, discontinued after just 554 days.",
  "apple-ii": "One of the first mass-produced personal computers with color graphics.",
  "macintosh-color-classic": "First compact all-in-one Mac with a built-in color screen.",
  "apple-i": "Sold as a bare circuit board; buyers added their own keyboard.",
  "apple-newton-messagepad": "Coined the term 'personal digital assistant'; mocked by The Simpsons.",
  "apple-lisa": "First Apple computer with a mouse-driven graphical interface.",
  "apple-iigs": "The 'GS' stood for Graphics and Sound, its biggest upgrades.",
  "apple-studio-display-crt": "Bulky bubble-shaped monitor that matched the iMac G3's colors.",
  "apple-iii": "Steve Jobs banned its cooling fan; chips loosened from overheating.",
  "twentieth-anniversary-macintosh": "Limited-edition Mac that launched at a steep $7,499.",
  "apple-quicktake-100": "One of the first consumer digital cameras, built with Kodak.",
  "macintosh-tv": "First black desktop Mac; only 10,000 units were made.",
  "apple-emate-300": "Only Newton with a keyboard; its case design inspired the iBook.",
  "apple-pippin": "Apple's short-lived game console, built in partnership with Bandai.",
};

export default APPLE_E66_FACTS;