export const BIRDS_E22_FACTS = {
  "bald-eagle": "The Bald Eagle is the national bird and symbol of the United States.",
  "peacock": "Only male peafowl grow the iconic, colorful tail feathers.",
  "flamingo": "Flamingos turn pink from pigments in the shrimp and algae they eat.",
  "emperor-penguin": "Emperor Penguins can dive deeper than 500 meters underwater.",
  "ostrich": "The Ostrich is the world's largest living bird but cannot fly.",
  "barn-owl": "Barn Owls can catch prey in total darkness using hearing alone.",
  "scarlet-macaw": "Scarlet Macaws can live 40 to 50 years in the wild.",
  "toco-toucan": "The Toco Toucan's giant bill helps it regulate body heat.",
  "hummingbird": "Hummingbirds are the only birds that can fly backwards.",
  "mute-swan": "Despite the name, Mute Swans can hiss and grunt loudly.",
  "pelican": "A pelican's throat pouch can hold more than its stomach.",
  "robin": "The American Robin is one of the first birds to sing at dawn.",
  "house-sparrow": "House Sparrows are one of the most widespread birds on Earth.",
  "rock-pigeon": "Rock Pigeons can find their way home from hundreds of miles away.",
  "kingfisher": "Kingfishers dive headfirst into water to catch fish.",
  "woodpecker": "Woodpeckers have tongues that wrap around the back of their skull.",
  "cardinal": "Only male Northern Cardinals have bright red plumage.",
  "snowy-owl": "Snowy Owls hunt during daylight, unlike most other owls.",
  "wild-turkey": "Wild Turkeys can run at speeds up to 25 miles per hour.",
  "canada-goose": "Canada Geese fly in a V formation to save energy.",
  "mallard": "Male Mallards have an iridescent green head; females are brown.",
  "great-blue-heron": "Great Blue Herons can strike prey in a fraction of a second.",
  "european-robin": "The European Robin will sing through the night under streetlights.",
  "blue-jay": "Blue Jays can mimic the calls of hawks to scare off other birds.",
  "common-raven": "Common Ravens are among the most intelligent birds alive.",
  "golden-eagle": "Golden Eagles can spot prey from over a mile away.",
  "atlantic-puffin": "Atlantic Puffins can hold several small fish in their beak at once.",
  "secretary-bird": "The Secretary Bird kills snakes by stomping them with its long legs.",
  "roadrunner": "The Greater Roadrunner can sprint up to 20 miles per hour.",
  "kookaburra": "The Kookaburra's call sounds like loud human laughter.",
  "cassowary": "The Cassowary is considered one of the most dangerous birds alive.",
  "andean-condor": "The Andean Condor has one of the largest wingspans of any bird.",
  "great-horned-owl": "Great Horned Owls have no true horns — they are feather tufts.",
  "mandarin-duck": "Male Mandarin Ducks are famous for their strikingly colorful plumage.",
  "common-loon": "Common Loons have solid bones, unlike most birds, helping them dive.",
  "whooping-crane": "The Whooping Crane is North America's tallest bird.",
  "shoebill": "The Shoebill can stand motionless for hours waiting to strike.",
  "kakapo": "The Kakapo is the world's only flightless, nocturnal parrot.",
  "hoatzin": "Hoatzin chicks have claws on their wings to help them climb trees.",
  "resplendent-quetzal": "The male Resplendent Quetzal grows tail feathers over two feet long.",
  "marabou-stork": "The Marabou Stork has a wingspan among the largest of any land bird.",
  "harpy-eagle": "The Harpy Eagle's talons can be as large as a grizzly bear's claws.",
  "king-vulture": "The King Vulture's bald head helps it stay clean while eating carrion.",
  "belted-kingfisher": "Female Belted Kingfishers are more colorful than the males.",
  "great-hornbill": "The Great Hornbill's wingbeats can be heard from far away in flight.",
  "frigatebird": "Male Frigatebirds inflate a bright red throat pouch to attract mates.",
  "wandering-albatross": "The Wandering Albatross has the longest wingspan of any living bird.",
  "superb-lyrebird": "The Superb Lyrebird can mimic almost any sound, even chainsaws.",
  "sword-billed-hummingbird": "Its beak is longer than its own body, the only bird with that trait.",
  "bee-eater": "Bee-eaters remove stingers by beating bees against a branch.",
  "kagu": "The nearly flightless Kagu lives only on New Caledonia.",
  "stellers-sea-eagle": "Steller's Sea Eagle is one of the heaviest eagles in the world.",
  "bearded-vulture": "The Bearded Vulture drops bones from great heights to crack them open.",
  "turquoise-browed-motmot": "The Turquoise-browed Motmot is the national bird of El Salvador.",
  "kiwi": "The Kiwi lays the largest egg relative to body size of any bird.",
  "takahe": "The Takahe was thought extinct for 50 years, rediscovered in 1948.",
  "bird-of-paradise": "Male birds-of-paradise perform elaborate dances to attract mates.",
  "ivory-billed-woodpecker": "The Ivory-billed Woodpecker is so rare some believe it may be extinct.",
  "philippine-eagle": "The Philippine Eagle is one of the largest and rarest eagles on Earth.",
  "california-condor": "Every wild condor descends from just 27 birds saved in the 1980s.",
  "snowy-sheathbill": "The Snowy Sheathbill is the only Antarctic bird without webbed feet.",
  "andean-cock-of-the-rock": "The Andean Cock-of-the-Rock is the national bird of Peru.",
  "great-potoo": "The Great Potoo camouflages as a broken tree stump during the day.",
  "regent-honeyeater": "Fewer than 400 Regent Honeyeaters remain in the wild today.",
  "kea": "The Kea is the world's only alpine parrot, found in New Zealand.",
  "long-wattled-umbrellabird": "Its dangling throat wattle can stretch up to 14 inches long.",
  "inaccessible-island-rail": "It is the smallest surviving flightless bird in the world.",
  "christmas-island-frigatebird": "It breeds almost nowhere but Christmas Island in the Indian Ocean.",
  "palila": "The Palila survives in one small forest patch on Hawaii's Mauna Kea.",
  "horned-screamer": "The Horned Screamer has a strange spike growing from its forehead.",
  "cock-tailed-tyrant": "The male Cock-tailed Tyrant flips its tail feathers up like a fan.",
};
