// E22 "Guess the Bird" — answer = bird name.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
// Hard content rules: no Israel/Jerusalem/West Bank/Gaza content, no disputed-territory ambiguity.
export const BIRDS_E22 = [
  // EASY (18) — instantly recognizable worldwide
  { slug: "bald-eagle", name: "Bald Eagle", sci: "Haliaeetus leucocephalus", level: "easy" },
  { slug: "peacock", name: "Peacock", sci: "Pavo cristatus", level: "easy" },
  { slug: "flamingo", name: "Flamingo", sci: "Phoenicopterus roseus", level: "easy" },
  { slug: "emperor-penguin", name: "Emperor Penguin", sci: "Aptenodytes forsteri", level: "easy" },
  { slug: "ostrich", name: "Ostrich", sci: "Struthio camelus", level: "easy" },
  { slug: "barn-owl", name: "Barn Owl", sci: "Tyto alba", level: "easy" },
  { slug: "scarlet-macaw", name: "Scarlet Macaw", sci: "Ara macao", level: "easy" },
  { slug: "toco-toucan", name: "Toco Toucan", sci: "Ramphastos toco", level: "easy" },
  { slug: "hummingbird", name: "Ruby-throated Hummingbird", sci: "Archilochus colubris", level: "easy" },
  { slug: "mute-swan", name: "Mute Swan", sci: "Cygnus olor", level: "easy" },
  { slug: "pelican", name: "American White Pelican", sci: "Pelecanus erythrorhynchos", level: "easy" },
  { slug: "robin", name: "American Robin", sci: "Turdus migratorius", level: "easy" },
  { slug: "house-sparrow", name: "House Sparrow", sci: "Passer domesticus", level: "easy" },
  { slug: "rock-pigeon", name: "Rock Pigeon", sci: "Columba livia", level: "easy" },
  { slug: "kingfisher", name: "Common Kingfisher", sci: "Alcedo atthis", level: "easy" },
  { slug: "woodpecker", name: "Great Spotted Woodpecker", sci: "Dendrocopos major", level: "easy" },
  { slug: "cardinal", name: "Northern Cardinal", sci: "Cardinalis cardinalis", level: "easy" },
  { slug: "snowy-owl", name: "Snowy Owl", sci: "Bubo scandiacus", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "wild-turkey", name: "Wild Turkey", sci: "Meleagris gallopavo", level: "medium" },
  { slug: "canada-goose", name: "Canada Goose", sci: "Branta canadensis", level: "medium" },
  { slug: "mallard", name: "Mallard Duck", sci: "Anas platyrhynchos", level: "medium" },
  { slug: "great-blue-heron", name: "Great Blue Heron", sci: "Ardea herodias", level: "medium" },
  { slug: "european-robin", name: "European Robin", sci: "Erithacus rubecula", level: "medium" },
  { slug: "blue-jay", name: "Blue Jay", sci: "Cyanocitta cristata", level: "medium" },
  { slug: "common-raven", name: "Common Raven", sci: "Corvus corax", level: "medium" },
  { slug: "golden-eagle", name: "Golden Eagle", sci: "Aquila chrysaetos", level: "medium" },
  { slug: "atlantic-puffin", name: "Atlantic Puffin", sci: "Fratercula arctica", level: "medium" },
  { slug: "secretary-bird", name: "Secretary Bird", sci: "Sagittarius serpentarius", level: "medium" },
  { slug: "roadrunner", name: "Greater Roadrunner", sci: "Geococcyx californianus", level: "medium" },
  { slug: "kookaburra", name: "Kookaburra", sci: "Dacelo novaeguineae", level: "medium" },
  { slug: "cassowary", name: "Cassowary", sci: "Casuarius casuarius", level: "medium" },
  { slug: "andean-condor", name: "Andean Condor", sci: "Vultur gryphus", level: "medium" },
  { slug: "great-horned-owl", name: "Great Horned Owl", sci: "Bubo virginianus", level: "medium" },
  { slug: "mandarin-duck", name: "Mandarin Duck", sci: "Aix galericulata", level: "medium" },
  { slug: "common-loon", name: "Common Loon", sci: "Gavia immer", level: "medium" },
  { slug: "whooping-crane", name: "Whooping Crane", sci: "Grus americana", level: "medium" },

  // HARD (18) — recognizable to enthusiasts
  { slug: "shoebill", name: "Shoebill", sci: "Balaeniceps rex", level: "hard" },
  { slug: "kakapo", name: "Kakapo", sci: "Strigops habroptilus", level: "hard" },
  { slug: "hoatzin", name: "Hoatzin", sci: "Opisthocomus hoazin", level: "hard" },
  { slug: "resplendent-quetzal", name: "Resplendent Quetzal", sci: "Pharomachrus mocinno", level: "hard" },
  { slug: "marabou-stork", name: "Marabou Stork", sci: "Leptoptilos crumenifer", level: "hard" },
  { slug: "harpy-eagle", name: "Harpy Eagle", sci: "Harpia harpyja", level: "hard" },
  { slug: "king-vulture", name: "King Vulture", sci: "Sarcoramphus papa", level: "hard" },
  { slug: "belted-kingfisher", name: "Belted Kingfisher", sci: "Megaceryle alcyon", level: "hard" },
  { slug: "great-hornbill", name: "Great Hornbill", sci: "Buceros bicornis", level: "hard" },
  { slug: "frigatebird", name: "Magnificent Frigatebird", sci: "Fregata magnificens", level: "hard" },
  { slug: "wandering-albatross", name: "Wandering Albatross", sci: "Diomedea exulans", level: "hard" },
  { slug: "superb-lyrebird", name: "Superb Lyrebird", sci: "Menura novaehollandiae", level: "hard" },
  { slug: "sword-billed-hummingbird", name: "Sword-billed Hummingbird", sci: "Ensifera ensifera", level: "hard" },
  { slug: "bee-eater", name: "European Bee-eater", sci: "Merops apiaster", level: "hard" },
  { slug: "kagu", name: "Kagu", sci: "Rhynochetos jubatus", level: "hard" },
  { slug: "stellers-sea-eagle", name: "Steller's Sea Eagle", sci: "Haliaeetus pelagicus", level: "hard" },
  { slug: "bearded-vulture", name: "Bearded Vulture", sci: "Gypaetus barbatus", level: "hard" },
  { slug: "turquoise-browed-motmot", name: "Turquoise-browed Motmot", sci: "Eumomota superciliosa", level: "hard" },

  // IMPOSSIBLE (17) — obscure even to enthusiasts
  { slug: "kiwi", name: "North Island Brown Kiwi", sci: "Apteryx mantelli", level: "impossible" },
  { slug: "takahe", name: "Takahe", sci: "Porphyrio hochstetteri", level: "impossible" },
  { slug: "bird-of-paradise", name: "Raggiana Bird-of-Paradise", sci: "Paradisaea raggiana", level: "impossible" },
  { slug: "ivory-billed-woodpecker", name: "Ivory-billed Woodpecker", sci: "Campephilus principalis", level: "impossible" },
  { slug: "philippine-eagle", name: "Philippine Eagle", sci: "Pithecophaga jefferyi", level: "impossible" },
  { slug: "california-condor", name: "California Condor", sci: "Gymnogyps californianus", level: "impossible" },
  { slug: "snowy-sheathbill", name: "Snowy Sheathbill", sci: "Chionis albus", level: "impossible" },
  { slug: "andean-cock-of-the-rock", name: "Andean Cock-of-the-Rock", sci: "Rupicola peruvianus", level: "impossible" },
  { slug: "great-potoo", name: "Great Potoo", sci: "Nyctibius grandis", level: "impossible" },
  { slug: "regent-honeyeater", name: "Regent Honeyeater", sci: "Anthochaera phrygia", level: "impossible" },
  { slug: "kea", name: "Kea", sci: "Nestor notabilis", level: "impossible" },
  { slug: "long-wattled-umbrellabird", name: "Long-wattled Umbrellabird", sci: "Cephalopterus penduliger", level: "impossible" },
  { slug: "inaccessible-island-rail", name: "Inaccessible Island Rail", sci: "Atlantisia rogersi", level: "impossible" },
  { slug: "christmas-island-frigatebird", name: "Christmas Island Frigatebird", sci: "Fregata andrewsi", level: "impossible" },
  { slug: "palila", name: "Palila", sci: "Loxioides bailleui", level: "impossible" },
  { slug: "horned-screamer", name: "Horned Screamer", sci: "Anhima cornuta", level: "impossible" },
  { slug: "cock-tailed-tyrant", name: "Cock-tailed Tyrant", sci: "Alectrurus tricolor", level: "impossible" },
];
