export const BODY_PARTS_E94_FACTS = {
  heart: "The heart beats roughly 100,000 times a day, pumping blood through about 60,000 miles of blood vessels.",
  brain: "The brain itself has no pain receptors, which is why surgeons can safely operate on brain tissue while a patient is awake.",
  eye: "The eye can distinguish millions of different shades of color.",
  ear: "The ear keeps working even during sleep, continuing to send sound signals to the brain.",
  nose: "The human nose can detect thousands of different odors and scents.",
  hand: "Each hand contains 27 separate bones, together making up about a quarter of all the bones in the human body.",
  foot: "Each foot has 26 bones and more than 100 muscles, tendons, and ligaments working together.",
  lung: "The right lung has three lobes and is slightly larger than the left lung, which has only two lobes to make room for the heart.",
  stomach: "The stomach lining replaces itself every few days so it doesn't digest itself with its own acid.",
  skin: "Skin is the body's largest organ, covering an area of about 20 square feet in an average adult.",
  tooth: "Tooth enamel is the hardest substance in the human body, even harder than bone.",
  tongue: "The tongue is made up of eight muscles with no bone to support it, a structure similar to an elephant's trunk.",
  mouth: "The mouth produces about half a liter to a liter and a half of saliva every day.",
  knee: "The knee is the largest and one of the most complex joints in the human body.",
  elbow: "The 'funny bone' isn't a bone at all — it's the ulnar nerve, which runs close to the skin at the elbow.",
  skull: "The skull is made of 22 individual bones fused together, not one solid piece.",
  "rib-cage": "Most people have 24 ribs in 12 pairs, though about 1 in 200 people are born with an extra rib.",
  bicep: "The biceps gets its name from Latin for 'two-headed,' referring to its two separate points of origin at the shoulder.",
  liver: "The liver can regenerate — even after losing up to 75% of its tissue, it can regrow to full size within weeks.",
  kidney: "The kidneys filter about 150 quarts of blood every day, producing roughly 1 to 2 quarts of urine.",
  spine: "The spine has four natural curves that work together like a spring to absorb shock during walking or running.",
  bladder: "The bladder can stretch to hold about 16 ounces of urine, roughly the size of a large mug.",
  spleen: "The spleen filters old and damaged red blood cells out of the bloodstream and helps fight certain infections.",
  pancreas: "The pancreas makes insulin and also produces digestive enzymes powerful enough to damage its own tissue if activated too early.",
  gallbladder: "The gallbladder stores and concentrates bile made by the liver, releasing it to help digest fatty foods.",
  femur: "The femur is the longest and strongest bone in the human body, able to bear many times a person's body weight.",
  tonsils: "Tonsils act as an early immune defense, trapping germs that enter through the mouth and nose.",
  cartilage: "Cartilage has no blood supply of its own, which is why cartilage injuries heal much more slowly than bone.",
  ligament: "Ligaments connect bone to bone, while the similarly named tendons connect muscle to bone.",
  "achilles-tendon": "The Achilles tendon is the thickest and strongest tendon in the body, yet it's also the one most commonly ruptured.",
  coccyx: "The coccyx is made of several small vertebrae fused together and is considered a vestigial remnant of a tail.",
  patella: "The patella is the largest sesamoid bone in the human body — a bone that forms inside a tendon rather than linking directly to other bones.",
  clavicle: "The collarbone is the most frequently broken bone in the human body, often from falls onto an outstretched arm.",
  trachea: "The trachea is reinforced by 16 to 20 C-shaped rings of cartilage that hold it open while letting it flex.",
  "vocal-cords": "Vocal cords vibrate hundreds of times per second to produce sound, with pitch controlled by how tightly they're stretched.",
  "small-intestine": "The small intestine is about 20 feet long, several times longer than the person it's coiled inside.",
  appendix: "Long dismissed as useless, research now suggests the appendix may act as a safe-house that helps restock beneficial gut bacteria.",
  thyroid: "The thyroid produces hormones that regulate metabolism, controlling how fast or slow the body uses energy.",
  cornea: "The cornea has no blood vessels — it gets its oxygen directly from the air and from tears instead.",
  esophagus: "The esophagus pushes food down using rhythmic muscle contractions called peristalsis, so swallowing works even upside down.",
  diaphragm: "The diaphragm is the main muscle used in breathing, contracting and flattening to pull air into the lungs.",
  sternum: "The sternum is one of the few bones commonly sampled for bone marrow because of its rich marrow content.",
  larynx: "The larynx houses the vocal cords and also protects the airway by closing off during swallowing.",
  retina: "The retina contains about 120 million rod cells for detecting light and roughly 6 million cone cells for detecting color.",
  "adrenal-gland": "The adrenal glands release adrenaline within seconds of a perceived threat, triggering the body's 'fight or flight' response.",
  "sciatic-nerve": "The sciatic nerve is the longest and widest single nerve in the human body, running from the lower back to the foot.",
  amygdala: "The amygdala plays a central role in processing fear and other strong emotional reactions.",
  hippocampus: "The hippocampus is named for its seahorse-like shape and plays a key role in forming new long-term memories.",
  cerebellum: "Although it is only about 10% of the brain's volume, the cerebellum contains more than half of the brain's total neurons.",
  epiglottis: "The epiglottis folds down like a lid during swallowing to stop food and liquid from entering the windpipe.",
  uvula: "The uvula helps stop food and liquid from entering the nasal cavity while swallowing and plays a role in certain speech sounds.",
  deltoid: "The deltoid is named after the Greek letter delta because of its triangular shape.",
  "pineal-gland": "The pineal gland produces melatonin, the hormone that signals the body when it's time to sleep based on light and darkness.",
  "semicircular-canals": "The three semicircular canals sense rotational head movement in different planes, helping the brain maintain balance.",
  "corpus-callosum": "The corpus callosum is the brain's largest bundle of nerve fibers, with roughly 200 million connections linking the two hemispheres.",
  "islets-of-langerhans": "The islets of Langerhans contain the cells that produce insulin and glucagon, the hormones that control blood sugar levels.",
  stapes: "The stapes is the smallest bone in the human body, measuring only about 3 millimeters long.",
  duodenum: "The duodenum is where bile from the gallbladder and enzymes from the pancreas first mix with food to continue digestion.",
  "xiphoid-process": "The xiphoid process is used as a hand-positioning landmark by rescuers performing chest compressions during CPR.",
  "vomer-bone": "The vomer's name comes from the Latin word for 'ploughshare' because of its thin, blade-like shape.",
  cochlea: "The cochlea's name comes from the Greek word for 'snail' due to its coiled shape, and it converts sound vibrations into nerve signals.",
  glottis: "The glottis is the space between the vocal cords, opening and closing rapidly to help produce sound.",
  meninges: "The meninges are three protective membrane layers that cushion the brain and spinal cord and contain the fluid surrounding them.",
  peritoneum: "The peritoneum is the body's largest membrane and helps hold the abdominal organs in place while reducing friction between them.",
  trapezius: "The trapezius gets its name from its broad, four-sided diamond shape and helps move and stabilize the shoulder blades.",
  "sphenoid-bone": "The sphenoid bone's name comes from the Greek word for 'wedge,' and it forms part of the eye socket, temple, and skull base.",
  "pia-mater": "The pia mater is the thinnest and most delicate of the three meningeal layers and closely follows the brain's surface contours.",
  cecum: "The cecum acts as a junction pouch between the small and large intestine, and in humans the appendix is attached to it.",
  ileum: "The ileum is the longest section of the small intestine and is specialized for absorbing vitamin B12 and bile salts.",
  hypothalamus: "The hypothalamus regulates body temperature, hunger, thirst, and sleep, acting as a link between the nervous and hormonal systems.",
};
