export const BOOKS_E89_FACTS = {
  "pride-and-prejudice": "Austen originally titled it 'First Impressions' and sold the copyright outright for just £110.",
  "a-tale-of-two-cities": "Guinness World Records credits it as the best-selling novel of all time, with an estimated 200 million copies sold.",
  "moby-dick": "It sold fewer than 4,000 copies in Melville's lifetime and wasn't hailed as a masterpiece until the 1920s.",
  "1984": "It introduced now-everyday terms like 'Big Brother,' 'doublethink,' and 'thoughtcrime' into English.",
  "harry-potter-and-the-sorcerers-stone": "The U.S. publisher renamed it from 'Philosopher's Stone,' fearing kids wouldn't want the word 'philosopher.'",
  "the-hobbit": "Tolkien said the opening line came to him out of nowhere while grading student exam papers.",
  "anna-karenina": "Tolstoy partly based Anna's death on a real suicide near his estate, whose autopsy he reportedly attended.",
  "alices-adventures-in-wonderland": "The story began as one Carroll improvised for the Liddell sisters during a rowing trip in 1862.",
  "the-catcher-in-the-rye": "Salinger became famously reclusive and refused nearly every offer to adapt it into a film.",
  "to-kill-a-mockingbird": "The character Dill was inspired by Harper Lee's real childhood friend and neighbor, Truman Capote.",
  "peter-pan": "Barrie donated all royalties from the story to a London children's hospital.",
  frankenstein: "Shelley wrote it at age 18 during a ghost-story contest with Lord Byron at Lake Geneva.",
  "the-great-gatsby": "It sold poorly and Fitzgerald died believing it a failure; its fame grew only after WWII.",
  "one-hundred-years-of-solitude": "García Márquez's family reportedly pawned appliances to mail the finished manuscript to his publisher.",
  "the-lion-the-witch-and-the-wardrobe": "Lewis said the story grew from a mental image he'd carried since age 16 of a faun in a snowy wood.",
  "charlottes-web": "White kept real spiders in his barn, studying their webs for months to get Charlotte's behavior right.",
  "the-wonderful-wizard-of-oz": "Baum claimed he picked the name 'Oz' after glancing at a filing cabinet drawer labeled 'O-Z.'",
  "a-christmas-carol": "Dickens wrote it in about six weeks and paid for its publication himself to cover his debts.",
  "adventures-of-huckleberry-finn": "A Massachusetts library banned it within months of publication, calling it unfit trash.",
  neuromancer: "Gibson wrote it on a manual typewriter despite never having used a computer.",
  "fahrenheit-451": "Bradbury wrote the first draft on a coin-operated library typewriter, paying a dime per 30 minutes.",
  "brave-new-world": "Huxley wrote it in under four months, partly as a satire of H.G. Wells's utopian fiction.",
  "the-handmaids-tale": "Atwood said she included nothing in the novel that hadn't already happened somewhere in real history.",
  "the-metamorphosis": "Kafka begged his publisher to never picture the insect on the cover.",
  rebecca: "The novel's narrator is never given a first name in the entire book.",
  "the-bell-jar": "Plath first published it under a pseudonym; her own name wasn't used until after her death.",
  "slaughterhouse-five": "It draws on Vonnegut's own survival of the Allied firebombing of Dresden as a POW.",
  "one-flew-over-the-cuckoos-nest": "Kesey wrote much of it after volunteering for a government study involving hallucinogens.",
  "the-road": "McCarthy said the idea came to him imagining his hotel's city, decades later, in ruins.",
  beloved: "It was inspired by the real case of an enslaved woman who killed her own child rather than see her re-enslaved.",
  "the-kite-runner": "It was Hosseini's debut novel, expanded from an earlier short story.",
  "life-of-pi": "The manuscript was rejected by several publishers before winning the 2002 Booker Prize.",
  "the-old-man-and-the-sea": "It won the Pulitzer Prize and was cited when Hemingway won the Nobel Prize the next year.",
  "jane-eyre": "It was first published under the male pen name 'Currer Bell.'",
  "wuthering-heights": "It was met with harsh reviews at release and only gained its classic status decades later.",
  "great-expectations": "Dickens rewrote its original bleaker ending after a friend urged him to soften it.",
  "crime-and-punishment": "Dostoevsky was writing it under such debt that he simultaneously dictated another novel to a stenographer he later married.",
  "the-trial": "Kafka left it unfinished and asked a friend to burn it after his death — his friend refused.",
  "a-room-with-a-view": "Forster called it his 'nicest' novel, the only one of his books with a happy ending.",
  "to-the-lighthouse": "It grew out of Woolf's own childhood memories of summers spent in Cornwall.",
  "the-sound-and-the-fury": "Its opening section is narrated entirely from a cognitively disabled character's perspective.",
  ulysses: "It was banned for obscenity in the US and UK for over a decade after publication.",
  "gravitys-rainbow": "A Pulitzer jury recommended it in 1974, but the board overruled them and gave no fiction prize that year.",
  "midnights-children": "It won the Booker Prize and was later twice voted the best novel in the prize's history.",
  "the-stranger": "Its famous first line was long translated as 'Mother died today' before a 1988 translation restored 'Maman.'",
  "their-eyes-were-watching-god": "It fell out of print for decades until Alice Walker helped revive Hurston's work in the 1970s.",
  "as-i-lay-dying": "Faulkner claimed to have written it in six weeks on night shifts, never revising a word.",
  "blood-meridian": "It sold modestly at release, but critic Harold Bloom later called it a landmark American novel.",
  "the-grapes-of-wrath": "It was publicly burned and banned in parts of California over its depiction of migrant workers.",
  "catch-22": "Heller's original title, 'Catch-18,' was changed to avoid clashing with another new novel.",
  "don-quixote": "It's often called the best-selling novel ever written, with estimates as high as 500 million copies.",
  "the-idiot": "Dostoevsky said his goal was to portray 'a truly beautiful soul' in the main character.",
  "finnegans-wake": "Joyce spent 17 years writing it, and its unfinished final sentence loops back into this opening line.",
  "the-unbearable-lightness-of-being": "Kundera's books were banned in Communist Czechoslovakia, pushing him into French exile.",
  "under-the-volcano": "Its entire plot unfolds across a single day, the Mexican Day of the Dead.",
  "house-of-leaves": "Before formal publication, it circulated online and in photocopies, gathering a cult following.",
  "the-waves": "It has almost no conventional plot, built instead from six characters' interior monologues.",
  "absalom-absalom": "The book contains a single sentence elsewhere running over 1,200 words.",
  "naked-lunch": "Its 1966 obscenity trial in Boston was one of the last major literary censorship cases in the US.",
  "the-confidence-man": "It was the last novel Melville published in his lifetime before working as a customs inspector.",
  "pale-fire": "It's structured as a 999-line poem followed by an increasingly unhinged scholarly commentary.",
  "a-clockwork-orange": "US editions for decades cut its final redemptive chapter, the version Kubrick's film was based on.",
  "the-sot-weed-factor": "It's a pastiche built around a real 1708 satirical poem by an actual colonial-era writer.",
  "foucaults-pendulum": "Eco wove real occult lore in so convincingly some readers mistook the plot for genuine history.",
  "the-man-without-qualities": "Musil worked on it for the last two decades of his life and died in 1942 with it unfinished.",
  "tristram-shandy": "It's famous for typographic tricks, including a solid black mourning page.",
  "the-golden-notebook": "Lessing said she was frustrated it was read almost only as a feminist tract.",
  middlemarch: "Virginia Woolf famously called it 'one of the few English novels written for grown-up people.'",
  "vanity-fair": "It was originally serialized monthly with illustrations drawn by Thackeray himself.",
  "wide-sargasso-sea": "It's a prequel imagining the earlier life of the 'madwoman in the attic' from Jane Eyre.",
};

export default BOOKS_E89_FACTS;
