export const BRIDGES_E47_FACTS = {
  "golden-gate-bridge": "Its rust-orange paint is called International Orange.",
  "tower-bridge": "Its bascules once opened 17 times a day; now just twice.",
  "brooklyn-bridge": "It was the world's first steel-wire suspension bridge.",
  "sydney-harbour-bridge": "Locals call it 'The Coathanger' for its arch shape.",
  "rialto-bridge": "Its single stone arch spans nearly 29 meters.",
  "ponte-vecchio": "Its shops switched from butchers to goldsmiths in 1593.",
  "charles-bridge": "Legend says egg whites were mixed into its mortar.",
  "chain-bridge-budapest": "Its stone lions are wrongly rumored to have no tongues.",
  "millau-viaduct": "Its tallest mast is taller than the Eiffel Tower.",
  "pont-alexandre-iii": "Built for the 1900 World's Fair, named for a Russian tsar.",
  "bridge-of-sighs": "Byron is said to have named it after prisoners' sighs.",
  "stari-most": "Rebuilt stone-by-stone after being shelled apart in 1993.",
  "forth-bridge": "'Painting the Forth Bridge' once meant a never-ending job.",
  "golden-bridge-da-nang": "Appears cradled by two giant hands on a hillside.",
  "ponte-25-de-abril": "Built by the same firm behind San Francisco's Bay Bridge.",
  "kapellbrucke": "Most of its historic paintings burned in a 1993 fire.",
  "pont-du-gard": "This Roman aqueduct bridge was built without any mortar.",
  "akashi-kaikyo-bridge": "A 1995 earthquake stretched its towers further apart.",

  "rainbow-bridge-tokyo": "Its name was chosen through a public naming contest.",
  "george-washington-bridge": "It's the world's only suspension bridge with 14 lanes.",
  "clifton-suspension-bridge": "Finished in 1864 with chains from Brunel's Hungerford Bridge.",
  "galata-bridge": "Anglers have fished from its deck for generations.",
  "bosphorus-bridge": "It links Europe and Asia across the Bosphorus Strait.",
  "pont-neuf": "Despite its name, it's actually the oldest bridge in Paris.",
  "howrah-bridge": "Its 26,500 tons of steel are joined only by rivets.",
  "puente-nuevo-ronda": "Its central chamber once served as a prison.",
  "zhangjiajie-glass-bridge": "Its glass floor sits 300 meters above the canyon.",
  "hapenny-bridge": "Crossing it once cost a half-penny toll.",
  "palace-bridge": "Its center splits open nightly for ships on the Neva.",
  "victoria-falls-bridge": "It was prefabricated in England, then shipped to Africa.",
  "storseisundet-bridge": "Its curved deck creates a 'road to nowhere' illusion.",
  "hong-kong-zhuhai-macau-bridge": "One of the world's longest sea-crossing bridges.",
  "capilano-suspension-bridge": "First built in 1889 with hemp rope and cedar planks.",
  "bandra-worli-sea-link": "Its steel cables total roughly Earth's circumference.",
  "rakotzbrucke": "Its reflection forms a perfect stone circle in the water.",
  "banpo-bridge": "Its fountain shoots recycled river water lit up at night.",

  "erasmusbrug": "Locals call it 'The Swan' for its curved white pylon.",
  "dragon-bridge-ljubljana": "Four copper dragon statues guard its corners.",
  "puente-de-la-mujer": "Its center section can rotate 90 degrees for boats.",
  "juscelino-kubitschek-bridge": "Three asymmetric arches crisscross diagonally overhead.",
  "royal-gorge-bridge": "It was the world's highest suspension bridge for 72 years.",
  "ponte-sant-angelo": "Ten Bernini-designed angel statues line its railings.",
  "oresund-bridge": "It turns into a tunnel partway across, via a man-made island.",
  "pulteney-bridge": "One of few bridges worldwide lined with shops both sides.",
  "iron-bridge-shropshire": "It was the world's first bridge cast entirely in iron.",
  "mackinac-bridge": "It can sway up to 35 feet in high winds.",
  "lions-gate-bridge": "The Guinness brewing family funded its construction.",
  "auckland-harbour-bridge": "Japanese-built 'clip-ons' doubled its traffic lanes in 1969.",
  "si-o-se-pol": "Its name means 'Bridge of 33 Arches' in Persian.",
  "khaju-bridge": "It doubles as a dam regulating the Zayandeh River.",
  "nelson-mandela-bridge": "It was built directly over 42 live railway lines.",
  "sunshine-skyway-bridge": "Its predecessor partly collapsed after a 1980 ship strike.",
  "vasco-da-gama-bridge": "At 17.2 km, it was once the world's longest bridge.",
  "humber-bridge": "It held the longest single-span record for 17 years.",

  "ponte-milvio": "Site of Constantine's decisive 312 AD battle.",
  "pons-fabricius": "Built in 62 BC, it's Rome's oldest surviving bridge.",
  "legion-bridge-prague": "Its name has changed repeatedly across political eras.",
  "kramerbrucke": "Europe's longest bridge still lined with houses.",
  "stone-bridge-regensburg": "Crusaders once marched across it toward the Holy Land.",
  "triple-bridge-ljubljana": "Plečnik added two footbridges beside an 1842 original.",
  "confederation-bridge": "It's the longest bridge over ice-covered water on Earth.",
  "nanjing-yangtze-river-bridge": "China's first Yangtze bridge built without foreign help.",
  "hangzhou-bay-bridge": "It cut the Ningbo-Shanghai drive time roughly in half.",
  "danyang-kunshan-grand-bridge": "At 164 km long, it's the longest bridge on Earth.",
  "trajans-bridge": "Its Roman spans stood as the longest for over 1,000 years.",
  "alcantara-bridge": "Its Roman granite arches were built without mortar.",
  "6-october-bridge": "It crosses the Nile twice along its route.",
  "rio-niteroi-bridge": "It's the longest bridge in the Southern Hemisphere.",
  "king-fahd-causeway": "It links Saudi Arabia and Bahrain across 25 km of sea.",
  "padma-bridge": "Its foundation piles reach a record 127 meters deep.",
  "vidyasagar-setu": "India's first cable-stayed bridge, opened in 1992.",
  "chesapeake-bay-bridge-tunnel": "It dips into tunnels twice to let ships pass overhead.",
};
