export const BUTTERFLIES_E45_FACTS = {
  "monarch-butterfly": "Migrates up to 3,000 miles between Canada and Mexico each year.",
  "blue-morpho": "Its iridescent blue wings are caused by structure, not pigment.",
  "painted-lady": "One of the most widely distributed butterflies on Earth.",
  "swallowtail-butterfly": "Named for the long tail streamers resembling a swallow's tail.",
  "eastern-tiger-swallowtail": "Some females turn black to mimic a toxic swallowtail.",
  "cabbage-white": "One of the most common butterflies seen in gardens worldwide.",
  "peacock-butterfly": "Eyespots on its wings scare off birds by mimicking eyes.",
  "red-admiral": "Some migrate from North Africa to the UK each spring.",
  "common-buckeye": "Large eyespots on its wings may startle predator birds.",
  "small-tortoiseshell": "Caterpillars feed almost only on stinging nettles.",
  "zebra-longwing": "Florida's state butterfly; can live several months as adult.",
  "giant-swallowtail": "Largest butterfly in North America, with a 6-inch wingspan.",
  "owl-butterfly": "Underwing eyespots mimic an owl's eyes to scare predators.",
  "viceroy-butterfly": "Closely mimics the toxic Monarch's color pattern.",
  "glasswing-butterfly": "Its see-through wings help it hide from predators.",
  "postman-butterfly": "Named for its habit of flying the same route daily.",
  "mourning-cloak": "Can live up to 11 months, among the longest-lived butterflies.",
  "cloudless-sulphur": "Bright yellow migrant common across the Americas.",

  "ulysses-butterfly": "Its electric-blue wings inspired Australia's tourism logo.",
  "julia-butterfly": "Drinks turtle tears for extra sodium in the Amazon.",
  "gulf-fritillary": "Bright orange with silver-spangled patches on its underwings.",
  "malachite-butterfly": "Named for the green mineral its wing patches resemble.",
  "comma-butterfly": "Named for a small white comma mark on its hindwing.",
  "purple-emperor": "Males feed on tree sap, dung, and rotting matter, not flowers.",
  "apollo-butterfly": "A protected mountain species found across Europe and Asia.",
  "common-mormon": "Females mimic toxic swallowtails in several wing forms.",
  "plain-tiger": "Also called the African Monarch; toxic to predators.",
  "paper-kite-butterfly": "A popular butterfly-house species, also called Rice Paper.",
  "eighty-eight-butterfly": "Underwing markings form a natural number '88' pattern.",
  "great-spangled-fritillary": "Caterpillars hatch, then hibernate without eating all winter.",
  "question-mark-butterfly": "Named for a silver question-mark shape on its hindwing.",
  "white-admiral": "Favors shady woodland rides across Europe and Asia.",
  "adonis-blue": "Males show a vivid sky-blue rarely seen in European insects.",
  "common-rose": "A toxic swallowtail widely mimicked by other species.",
  "kaiser-i-hind": "A prized Himalayan species; its name means 'Emperor of India'.",
  "chalkhill-blue": "Pale silvery-blue males form large chalk-grassland colonies.",

  "queen-alexandras-birdwing": "World's largest butterfly; females can span 30 cm.",
  "homerus-swallowtail": "Jamaica's largest butterfly, now critically endangered.",
  "large-blue-butterfly": "Went extinct in the UK in 1979, then was reintroduced.",
  "karner-blue": "Caterpillars feed only on wild lupine; now endangered.",
  "duke-of-burgundy": "A declining European species despite its royal name.",
  "marsh-fritillary": "Caterpillars spin communal silk webs before hibernating.",
  "bhutan-glory": "A rare Himalayan swallowtail with tiger-striped wings.",
  "golden-birdwing": "Males' fluorescent yellow wings help attract mates.",
  "corsican-swallowtail": "Found only on Corsica and Sardinia; strictly protected.",
  "regal-fritillary": "Vanishing from US prairies as native grasslands disappear.",
  "schaus-swallowtail": "One of the rarest US butterflies, found only in the Florida Keys.",
  "bay-checkerspot": "Depends on rare serpentine soil grasslands near San Francisco.",
  "large-copper": "Went extinct in Britain in the 1850s; a Dutch form was introduced.",
  "cracker-butterfly": "Males make a loud clicking sound while flying to defend territory.",
  "silver-spotted-skipper": "A fast, darting skipper named for a silver underwing patch.",
  "regent-skipper": "An ancient Australian skipper with moth-like wing coupling.",
  "luzon-peacock-swallowtail": "An endangered Philippine mountain endemic, protected under CITES.",
  "mission-blue-butterfly": "An endangered San Francisco Bay Area butterfly on lupine.",

  "fenders-blue": "Thought extinct for decades until rediscovered in Oregon in 1989.",
  "palos-verdes-blue": "Declared extinct in 1983, then rediscovered nearby in 1994.",
  "el-segundo-blue": "Survives only on California coastal dunes near LAX airport.",
  "saint-francis-satyr": "One of America's rarest butterflies, found on one army base.",
  "uncompahgre-fritillary": "Survives only on a few alpine peaks in Colorado.",
  "poweshiek-skipperling": "A prairie skipper that's nearly vanished in a few decades.",
  "langes-metalmark": "Clings to survival on one California sand dune reserve.",
  "miami-blue": "Possibly the rarest insect in the US; down to a few refuges.",
  "table-mountain-beauty": "Sole pollinator of South Africa's rare red disa orchid.",
  "san-bruno-elfin": "An endangered butterfly restricted to San Mateo County, California.",
  "hermes-copper": "Survives in a few San Diego canyons, threatened by wildfire.",
  "bartrams-scrub-hairstreak": "A tiny endangered hairstreak from South Florida pine rockland.",
  "mitchells-satyr": "A federally endangered satyr from a handful of US wetlands.",
  "crystal-skipper": "Named a full species only in 2015, found on NC barrier islands.",
  "behrens-silverspot": "Clings on along a shrinking stretch of California coastline.",
  "oregon-silverspot": "A threatened coastal fritillary needing rare violet host plants.",
  "xerces-blue": "Extinct since the 1940s, first US butterfly lost to cities.",
};
