export const CAPITALS_E63_FACTS = {
  "us": "Named after the country's first president, George Washington.",
  "fr": "Home to the Eiffel Tower and the Louvre museum.",
  "gb": "Sits on the River Thames, home of Big Ben.",
  "jp": "The world's most populous metropolitan area.",
  "cn": "Hosted the Summer Olympics in 2008 and Winter Games in 2022.",
  "ru": "Home to the Kremlin and Red Square.",
  "it": "Known as the Eternal City, over 2,700 years old.",
  "de": "Once divided by a wall for nearly 30 years.",
  "es": "Europe's highest-altitude capital city.",
  "eg": "The largest city in the Arab world.",
  "ca": "Chosen as capital partly for sitting between Toronto and Quebec.",
  "au": "Purpose-built as a compromise between Sydney and Melbourne.",
  "in": "Built next to Old Delhi in the early 20th century.",
  "br": "A planned city built from scratch, opened in 1960.",
  "kr": "One of the world's most densely populated major cities.",
  "mx": "Built atop the ruins of the Aztec capital Tenochtitlan.",
  "gr": "Home to the ancient Acropolis and Parthenon.",
  "th": "Its full ceremonial name is one of the longest place names on Earth.",
  "at": "Famous for classical music, home to Mozart and Beethoven's legacy.",
  "nl": "Famous for its canals and narrow leaning houses.",
  "be": "Headquarters of the European Union's main institutions.",
  "pt": "Built across seven hills beside the Tagus River.",
  "se": "Spread across 14 islands connected by bridges.",
  "no": "Awards the Nobel Peace Prize every year.",
  "dk": "Home to the Little Mermaid statue.",
  "fi": "Known as the 'Daughter of the Baltic'.",
  "ie": "Split by the River Liffey, birthplace of Guinness.",
  "pl": "Rebuilt almost entirely after near-total destruction in WWII.",
  "cz": "Nicknamed the 'City of a Hundred Spires'.",
  "hu": "Formed by merging two cities on opposite banks of the Danube.",
  "id": "One of the fastest-sinking cities in the world.",
  "ph": "One of the most densely populated cities on Earth.",
  "cu": "Its old town is a UNESCO World Heritage Site.",
  "ar": "Its name means 'good airs' in Spanish.",
  "cl": "Sits in a valley surrounded by the Andes Mountains.",
  "sa": "Grew from a walled desert town into a modern metropolis.",
  "tr": "Became capital in 1923, replacing Istanbul.",
  "nz": "The world's southernmost national capital.",
  "ch": "Its old town is a UNESCO World Heritage Site.",
  "za": "One of South Africa's three capital cities.",
  "ng": "Purpose-built to replace Lagos as capital in 1991.",
  "mm": "A purpose-built capital opened in 2005, replacing Yangon.",
  "kz": "Renamed twice this century before reverting to its original name.",
  "pk": "A planned city built in the 1960s to replace Karachi.",
  "ma": "Sits on the Atlantic coast, distinct from nearby Casablanca.",
  "ua": "One of Eastern Europe's oldest cities, over 1,500 years old.",
  "ro": "Once nicknamed 'Little Paris' for its architecture.",
  "bg": "Named after a nearby mountain, Vitosha.",
  "hr": "Formed by the merger of two medieval hilltop towns.",
  "rs": "Its name means 'white city' in Serbian.",
  "vn": "Its old quarter has 36 streets, each named for a trade guild.",
  "my": "Home to the Petronas Twin Towers.",
  "ke": "Its name comes from a Maasai phrase for 'cool water'.",
  "pe": "Founded by Spanish conquistador Francisco Pizarro in 1535.",
  "bo": "The constitutional capital, though government sits in La Paz.",
  "ci": "Named after a former local ruler; a giant basilica towers over it.",
  "to": "Home to fewer than 25,000 people.",
  "lk": "One of the longest city names in the world.",
  "bj": "The official capital, though the government sits in Cotonou.",
  "nr": "Home to fewer than 1,000 people, world's smallest capital.",
  "li": "Overlooked by a medieval castle still used by the royal family.",
  "bi": "Replaced Bujumbura as official capital in 2019.",
  "tz": "Chosen for its central location within the country.",
  "bf": "Its name roughly translates to 'come and rest'.",
  "mr": "Founded in 1958 on the site of a small fishing village.",
  "gw": "A former Portuguese colonial trading port.",
  "gq": "Located on an island, not the country's mainland.",
  "bt": "The only capital in the world with no traffic lights.",
  "la": "Sits on a bend of the Mekong River.",
  "sr": "Its old town is a mix of Dutch colonial architecture.",
};

export default CAPITALS_E63_FACTS;
