// Episode 10 "Guess the Capital City" — one verified <=70-char fact per item, keyed by slug.
export const CAPITAL_CITIES_E10_FACTS = {
  paris: "Paris has been France's capital for over 1,000 years.",
  london: "London was founded by the Romans as Londinium.",
  tokyo: "Tokyo became Japan's capital in 1868, replacing Kyoto.",
  "washington-dc": "Washington, D.C. was named the U.S. capital in 1790.",
  rome: "Rome is called 'the Eternal City' for its ancient history.",
  berlin: "Berlin was divided by a wall from 1961 to 1989.",
  moscow: "Moscow's Red Square gets its name from its beauty, not communism.",
  beijing: "Beijing's name means 'Northern Capital' in Chinese.",
  cairo: "Cairo sits right next to the ancient pyramids of Giza.",
  seoul: "Seoul has been a capital city for over 600 years.",
  bangkok: "Bangkok's full ceremonial name is one of the longest in the world.",
  "new-delhi": "New Delhi was built to replace Calcutta as India's capital in 1911.",
  "mexico-city": "Mexico City was built on the ruins of the Aztec capital.",
  "buenos-aires": "Buenos Aires means 'good airs' in Spanish.",
  madrid: "Madrid is one of Europe's highest-altitude capitals.",
  amsterdam: "Amsterdam has more canals than Venice.",
  brasilia: "Brasília was purpose-built as a new capital in 1960.",
  athens: "Athens is one of the oldest continuously inhabited cities on Earth.",
  vienna: "Vienna was long the seat of the Habsburg Empire.",
  brussels: "Brussels hosts the headquarters of the European Union.",
  dublin: "Dublin's name comes from Irish words meaning 'black pool.'",
  stockholm: "Stockholm is built across 14 islands.",
  warsaw: "Warsaw was almost completely rebuilt after World War II.",
  budapest: "Budapest formed when three cities merged in 1873.",
  jakarta: "Jakarta remains Indonesia's capital as a new one is being built.",
  manila: "Manila is one of the most densely populated cities on Earth.",
  "kuala-lumpur": "Kuala Lumpur's name means 'muddy river confluence.'",
  riyadh: "Riyadh sits in the middle of the Arabian Desert.",
  hanoi: "Hanoi has served as a capital on and off for over 1,000 years.",
  ottawa: "Ottawa was chosen as Canada's capital partly to end city rivalries.",
  havana: "Havana's old town is a UNESCO World Heritage Site.",
  lima: "Lima was founded by Spanish conquistadors in 1535.",
  bogota: "Bogotá sits over 2,600 meters above sea level.",
  nairobi: "Nairobi's name comes from a Maasai phrase for 'cool water.'",
  "addis-ababa": "Addis Ababa's name means 'new flower' in Amharic.",
  canberra: "Canberra was chosen as a compromise between Sydney and Melbourne.",
  bern: "Legend says Bern is named after a bear, its heraldic symbol.",
  reykjavik: "Reykjavik means 'smoky bay' after its geothermal steam.",
  helsinki: "Helsinki's harbor rarely freezes solid despite the cold.",
  bratislava: "Bratislava is the only capital bordering two other countries.",
  zagreb: "Zagreb grew from two neighboring medieval towns.",
  sofia: "Sofia is named after a church, not a person.",
  bucharest: "Bucharest is nicknamed 'Little Paris' for its architecture.",
  ankara: "Ankara became Turkey's capital instead of Istanbul in 1923.",
  kathmandu: "Kathmandu's valley holds seven UNESCO World Heritage sites.",
  islamabad: "Islamabad was purpose-built as a planned capital in the 1960s.",
  kabul: "Kabul sits at over 1,700 meters, one of the highest capitals.",
  "phnom-penh": "Phnom Penh sits where three rivers meet.",
  ulaanbaatar: "Ulaanbaatar is the world's coldest capital city.",
  wellington: "Wellington is the world's southernmost national capital.",
  quito: "Quito sits high in the Andes, near the equator's line.",
  "panama-city": "Panama City is the only capital with a rainforest within its limits.",
  kigali: "Kigali is known as one of Africa's cleanest capital cities.",
  astana: "Astana was renamed Nur-Sultan for a few years, then changed back.",
  naypyidaw: "Naypyidaw replaced Yangon as Myanmar's capital in 2005.",
  ouagadougou: "Ouagadougou's name is often shortened to 'Ouaga.'",
  vaduz: "Vaduz is capital of Liechtenstein, a tiny European microstate.",
  bissau: "Bissau sits on an estuary of the Geba River.",
  vientiane: "Vientiane sits directly across the Mekong River from Thailand.",
  thimphu: "Thimphu has no traffic lights anywhere in the city.",
  "bandar-seri-begawan": "Bandar Seri Begawan is home to a famous golden-domed mosque.",
  male: "Malé is one of the most densely populated islands on Earth.",
  suva: "Suva is one of the wettest capital cities in the world.",
  nukualofa: "Nuku'alofa means 'abode of love' in Tongan.",
  apia: "Apia is Samoa's only city and R.L. Stevenson's burial site.",
  majuro: "Majuro is built along a narrow coral atoll.",
  praia: "Praia sits on a volcanic plateau above the Atlantic.",
  moroni: "Moroni sits at the foot of an active volcano.",
  yamoussoukro: "Yamoussoukro has a basilica larger than St. Peter's in Rome.",
  juba: "Juba became South Sudan's capital at independence in 2011.",
  mogadishu: "Mogadishu was once called 'the White Pearl of the Indian Ocean.'",
};
export default CAPITAL_CITIES_E10_FACTS;
