export const CAPITALS_E64_FACTS = {
  "sg": "Both a city and an entire country at once.",
  "kp": "Home to the world's largest stadium by capacity.",
  "tw": "Home to Taipei 101, once the world's tallest building.",
  "is": "Powered almost entirely by geothermal and hydro energy.",
  "ir": "One of the world's oldest continuous civilizations.",
  "iq": "Home to the ancient ruins of Babylon.",
  "co": "Produces more coffee than almost any other country.",
  "ve": "Home to Angel Falls, the world's tallest waterfall.",
  "gh": "The first sub-Saharan African country to gain independence.",
  "kh": "Home to the ancient temple complex of Angkor Wat.",
  "mt": "One of the most densely populated countries on Earth.",
  "lu": "One of the world's wealthiest countries per capita.",
  "qa": "Hosted the 2022 FIFA World Cup.",
  "kw": "Sits atop some of the world's largest oil reserves.",
  "pa": "Home to a canal linking the Atlantic and Pacific oceans.",
  "cr": "Has no standing army, abolished in 1948.",
  "jm": "Birthplace of reggae music.",
  "gt": "Home to Tikal, one of the greatest ancient Maya cities.",
  "et": "Successfully repelled Italy's colonial invasion at Adwa in 1896.",
  "cd": "Home to the world's second-largest rainforest.",
  "np": "Home to Mount Everest, the world's tallest peak.",
  "ge": "One of the first nations to adopt Christianity as a state religion.",
  "am": "Home to Lake Sevan, one of the world's largest high-altitude lakes.",
  "az": "Known as the 'Land of Fire' for its natural gas flames.",
  "lt": "The geographic center of Europe lies within its borders.",
  "lv": "Home to Ventas Rumba, the widest waterfall in Europe.",
  "ee": "A pioneer in digital government, with e-residency for anyone.",
  "ec": "Named after the equator, which runs through it.",
  "do": "Shares its island with Haiti.",
  "fj": "Made up of more than 300 islands.",
  "om": "One of the oldest independent states in the Arab world.",
  "ye": "Home to Socotra, an island called the 'Alien Island'.",
  "bd": "One of the most densely populated countries on Earth.",
  "mg": "Home to over 90% of its wildlife found nowhere else.",
  "uz": "One of only two doubly landlocked countries on Earth.",
  "tj": "Over 90% of its land is mountainous.",
  "al": "Its flag features a black double-headed eagle.",
  "ao": "One of Africa's largest oil producers.",
  "ba": "Hosted the 1984 Winter Olympics.",
  "mn": "One of the least densely populated countries on Earth.",
  "bw": "Home to a large portion of the Kalahari Desert.",
  "bz": "The only Central American nation with English as its official tongue.",
  "cm": "Nicknamed 'Africa in miniature' for its varied landscapes.",
  "cv": "A volcanic archipelago off West Africa's coast.",
  "gm": "Africa's smallest mainland country.",
  "gy": "The only English-speaking country in South America.",
  "ls": "Entirely surrounded by another country, South Africa.",
  "ly": "Home to over 90% desert terrain.",
  "ml": "Home to the fabled city of Timbuktu.",
  "mw": "Contains one of Africa's largest lakes.",
  "mz": "Its coastline stretches nearly 2,500 kilometers.",
  "na": "Home to the world's oldest desert, the Namib.",
  "ne": "Named after the Niger River.",
  "md": "One of Europe's leading wine-producing nations per capita.",
  "dj": "Sits at the mouth of the Red Sea, a key shipping route.",
  "er": "Once part of Ethiopia until independence in 1993.",
  "kg": "Almost 90% of its land sits above 1,500 meters.",
  "py": "One of only two landlocked countries in South America.",
  "rw": "Known as the 'Land of a Thousand Hills'.",
  "sb": "The site of major WWII Pacific battles, including Guadalcanal.",
  "sd": "Home to more ancient pyramids than Egypt.",
  "si": "More than half its territory is covered in forest.",
  "sk": "Home to hundreds of castles and châteaus.",
  "sn": "The westernmost country on mainland Africa.",
  "so": "Has the longest coastline on mainland Africa.",
  "ss": "The world's newest country, independent since 2011.",
  "td": "Named after Lake Chad, once one of Africa's largest lakes.",
  "tl": "One of Asia's newest nations, independent since 2002.",
  "ug": "Straddles the equator and source of the Nile.",
  "vu": "Home to some of the world's most active volcanoes.",
};

export default CAPITALS_E64_FACTS;
