// Episode 7 "Guess the Car Logo" — one verified ≤70-char fact per brand, keyed by slug.
export const CAR_LOGOS_E07_FACTS = {
  toyota: "Toyota was founded in Japan in 1937 by Kiichiro Toyoda.",
  ford: "Ford Motor Company was founded by Henry Ford in 1903.",
  bmw: "BMW started out making aircraft engines in 1916.",
  "mercedes-benz": "Mercedes-Benz traces back to the first car, built in 1886.",
  ferrari: "Ferrari began as a racing team before selling road cars.",
  lamborghini: "Lamborghini was founded by a tractor maker in 1963.",
  porsche: "The Porsche 911 has kept its shape since 1963.",
  honda: "Honda started out building motorcycles, not cars.",
  tesla: "Tesla was founded in 2003, named after Nikola Tesla.",
  volkswagen: "Volkswagen means 'people's car' in German.",
  audi: "Audi's four rings represent four merged German automakers.",
  chevrolet: "Chevrolet was founded in 1911 by Louis Chevrolet.",
  nissan: "Nissan's cars were sold as Datsun for much of the 20th century.",
  hyundai: "Hyundai means 'modernity' in Korean.",
  kia: "Kia is South Korea's oldest car maker, founded in 1944.",
  mazda: "Mazda is named after Ahura Mazda, a Zoroastrian god.",
  jeep: "The Jeep began as a military vehicle in World War II.",
  volvo: "Volvo means 'I roll' in Latin.",
  "land-rover": "The first Land Rover was sketched in beach sand in 1947.",
  jaguar: "Jaguar started out as a motorcycle sidecar maker.",
  mini: "The Mini was designed to fit inside a box 10 feet cubed.",
  bentley: "Bentley was founded by W.O. Bentley in 1919.",
  "rolls-royce": "The Rolls-Royce hood ornament is called Spirit of Ecstasy.",
  "aston-martin": "Aston Martin is famous as James Bond's car of choice.",
  bugatti: "Bugatti was founded by an Italian in Alsace in 1909.",
  maserati: "Maserati's trident logo honors a fountain in Bologna.",
  "alfa-romeo": "Alfa Romeo's badge carries Milan's cross and serpent.",
  citroen: "Citroen's double-chevron logo represents its gear tech.",
  skoda: "Skoda is one of the world's oldest car makers, from 1895.",
  mitsubishi: "Mitsubishi's 3-diamond logo means 'three water chestnuts.'",
  suzuki: "Suzuki began in 1909 making weaving looms, not cars.",
  lexus: "Lexus is Toyota's luxury division, launched in 1989.",
  infiniti: "Infiniti is Nissan's luxury brand, launched in 1989.",
  acura: "Acura was Honda's first luxury brand, launched in 1986.",
  cadillac: "Cadillac is named after the French founder of Detroit.",
  buick: "Buick is GM's oldest surviving brand, founded in 1899.",
  gmc: "GMC has built trucks almost exclusively since 1912.",
  chrysler: "Chrysler was founded by Walter Chrysler in 1925.",
  dodge: "Dodge began as a parts supplier before making full cars.",
  opel: "Opel started out making sewing machines and bicycles.",
  mclaren: "McLaren began as a Formula 1 racing team in 1963.",
  genesis: "Genesis is Hyundai's luxury brand, launched in 2015.",
  oldsmobile: "Oldsmobile was one of the earliest US car brands, from 1897.",
  hummer: "Hummer grew out of the military Humvee vehicle.",
  scion: "Scion was Toyota's youth-focused brand, 2003 to 2016.",
  daewoo: "Daewoo's car business was later absorbed into GM Korea.",
  ssangyong: "SsangYong means 'double dragon' in Korean.",
  proton: "Proton is Malaysia's first national car maker, from 1983.",
  perodua: "Perodua is one of Malaysia's two national car brands.",
  daihatsu: "Daihatsu is one of Japan's oldest car makers, from 1907.",
  saturn: "Saturn was a GM brand created to compete with imports.",
  lada: "Lada is Russia's best-known car brand, launched in 1973.",
  rivian: "Rivian focuses on electric trucks and SUVs.",
  "lucid-motors": "Lucid Motors builds electric cars in California.",
  polestar: "Polestar started out as a Volvo racing team.",
  "ds-automobiles": "DS Automobiles split off from Citroen as its own brand.",
  abarth: "Abarth's scorpion badge nods to founder Carlo Abarth's zodiac sign.",
  lancia: "Lancia is one of the oldest car brands still around, from 1906.",
  koenigsegg: "Koenigsegg is a tiny Swedish maker of hypercars.",
  triumph: "Triumph's classic cars included the Spitfire and TR6.",
  "tata-motors": "Tata Motors owns Jaguar Land Rover in the UK.",
  mahindra: "Mahindra began building Jeeps under license in India.",
  mg: "MG stands for Morris Garages, its founding company.",
  chery: "Chery has exported Chinese-made cars since 2001.",
  dacia: "Dacia is Renault's budget brand, based in Romania.",
  wuling: "Wuling makes China's popular tiny Hongguang Mini EV.",
  changan: "Changan traces its roots to an 1862 Qing dynasty arsenal.",
  baic: "BAIC is a major state-owned Chinese automaker.",
  eagle: "Eagle was a short-lived Chrysler brand from 1988-1998.",
  studebaker: "Studebaker started out building wagons in 1852.",
  xpeng: "XPeng is a Chinese EV maker known for smart-driving tech.",
};
export default CAR_LOGOS_E07_FACTS;
