export const CAT_BREEDS_E56_FACTS = {
  // EASY
  "persian": "Known for its flat face and long coat since the 1600s.",
  "siamese": "One of the oldest recognized Asian cat breeds.",
  "maine-coon": "One of the largest domestic cat breeds, native to Maine.",
  "sphynx": "A hairless breed developed from a 1966 Canadian mutation.",
  "british-shorthair": "Nicknamed the teddy-bear cat for its round, plush face.",
  "scottish-fold": "Its folded ears come from a natural gene mutation.",
  "ragdoll": "Goes limp and relaxed when picked up, hence the name.",
  "bengal": "Bred to have a wild leopard-like spotted coat.",
  "munchkin": "Known for its very short legs from a genetic mutation.",
  "russian-blue": "Has a dense silvery-blue double coat and green eyes.",
  "abyssinian": "Has a ticked coat where each hair has multiple colors.",
  "himalayan": "A Persian-Siamese mix with pointed coloring.",
  "norwegian-forest-cat": "A sturdy, long-haired breed built for cold climates.",
  "turkish-van": "Known for actually enjoying swimming in water.",
  "manx": "Famous for being naturally born without a tail.",
  "american-shorthair": "Descended from cats brought over on European ships.",
  "devon-rex": "Has large ears and a soft, curly wave-patterned coat.",
  "cornish-rex": "Has only the soft undercoat, giving it a curly, wavy fur.",

  // MEDIUM
  "burmese": "Developed in the US from a single cat named Wong Mau.",
  "tonkinese": "A cross between the Siamese and Burmese breeds.",
  "egyptian-mau": "One of the few naturally spotted domestic cat breeds.",
  "birman": "Always has white 'gloves' on all four paws.",
  "ocicat": "Has a wild spotted look but no wild cat ancestry.",
  "somali": "Essentially a long-haired version of the Abyssinian.",
  "balinese": "A long-haired Siamese with the same pointed coloring.",
  "selkirk-rex": "Nicknamed the 'cat in sheep's clothing' for its curls.",
  "american-curl": "Kittens are born straight-eared; ears curl back within days.",
  "exotic-shorthair": "Called the 'lazy man's Persian' for its short coat.",
  "british-longhair": "A long-haired variant of the British Shorthair.",
  "chartreux": "A French breed with a blue-grey coat and copper eyes.",
  "turkish-angora": "One of the oldest natural cat breeds from Turkey.",
  "japanese-bobtail": "Has a short, pom-pom-like tail unique to each cat.",
  "siberian": "Russia's native long-haired forest cat breed.",
  "nebelung": "A rare long-haired cousin of the Russian Blue.",
  "laperm": "Has a curly, permed-looking coat from a 1980s mutation.",
  "singapura": "One of the smallest cat breeds, named after Singapore.",

  // HARD
  "korat": "A silver-blue Thai breed said to bring good luck.",
  "havana-brown": "Named for its rich, solid mahogany-brown coat.",
  "bombay": "Bred to resemble a miniature black panther.",
  "snowshoe": "A Siamese mix with white 'snowshoe' paws.",
  "ragamuffin": "A separately bred cousin of the Ragdoll cat.",
  "american-bobtail": "Has a naturally short, expressive bobbed tail.",
  "pixie-bob": "Bred to resemble a wild bobcat, often polydactyl.",
  "chausie": "A hybrid breed developed from the jungle cat.",
  "colorpoint-shorthair": "A Siamese-bodied cat bred in extra point colors.",
  "oriental-shorthair": "A Siamese-bodied cat bred in over 300 colors.",
  "cymric": "Simply a long-haired variety of the tailless Manx.",
  "american-wirehair": "Has a springy, wiry coat from a 1966 barn mutation.",
  "kurilian-bobtail": "A Russian bobtail breed from the Kuril Islands.",
  "sokoke": "A rare natural breed from Kenya's Arabuko-Sokoke forest.",
  "australian-mist": "Australia's own spotted and marbled cat breed.",
  "british-semi-longhair": "A fluffier-coated cousin of the British Shorthair.",
  "lykoi": "Nicknamed the 'werewolf cat' for its patchy fur.",

  // IMPOSSIBLE
  "minskin": "A tiny short-legged breed with a mostly hairless body.",
  "toybob": "A Russian breed that stays kitten-sized as an adult.",
  "ukrainian-levkoy": "A hairless breed with folded ears from Ukraine.",
  "peterbald": "A Russian hairless breed with a whippy, elegant body.",
  "highlander-cat": "A wild-looking breed with curled ears and a bobtail.",
  "napoleon-minuet": "A short-legged breed inspired by the Munchkin.",
  "serengeti-cat": "Bred to mimic the look of a wild African serval.",
  "chantilly-tiffany": "A rare long-haired breed once thought extinct.",
  "foldex": "A folded-ear breed crossing the Fold and Exotic cats.",
  "donskoy": "A Russian hairless breed with wrinkled skin.",
  "khao-manee": "An ancient Thai breed often born with two eye colors.",
  "dragon-li": "A native Chinese breed with a brown-striped tabby coat.",
  "arabian-mau": "A natural desert breed from the Arabian Peninsula.",
  "german-rex": "One of Europe's earliest recorded curly-coated cats.",
};

export default CAT_BREEDS_E56_FACTS;
