export const CATHEDRALS_E60_FACTS = {
  // EASY
  "notre-dame-paris": "Reopened in 2024 after the devastating 2019 fire.",
  "st-peters-basilica": "The largest church interior in the world.",
  "sagrada-familia": "Still under construction since 1882.",
  "st-basils-cathedral": "Famous for its colorful, onion-domed towers.",
  "hagia-sophia": "Was a church, then a mosque, then a museum, now a mosque.",
  "st-pauls-cathedral": "Sir Christopher Wren rebuilt it after the Great Fire.",
  "cologne-cathedral": "Took over 600 years to complete.",
  "milan-cathedral": "Its roof holds over 3,400 statues.",
  "florence-cathedral": "Its dome inspired the U.S. Capitol's design.",
  "seville-cathedral": "The largest Gothic cathedral in the world.",
  "st-stephens-cathedral-vienna": "Its roof is covered in 230,000 glazed tiles.",
  "st-vitus-cathedral": "Took nearly 600 years to finish.",
  "chartres-cathedral": "Famous for its original medieval stained glass.",
  "reims-cathedral": "Where French kings were traditionally crowned.",
  "canterbury-cathedral": "The seat of the Archbishop of Canterbury.",
  "washington-national-cathedral": "The 6th-largest cathedral in the world.",
  "st-patricks-cathedral-nyc": "The largest Gothic Catholic cathedral in the US.",
  "brasilia-cathedral": "Its hyperboloid shape opened in 1970.",
  "mexico-city-cathedral": "The largest cathedral in the Americas.",

  // MEDIUM
  "york-minster": "One of the largest Gothic cathedrals in Europe.",
  "salisbury-cathedral": "Home to Britain's tallest church spire.",
  "strasbourg-cathedral": "Was the world's tallest building for 227 years.",
  "burgos-cathedral": "A UNESCO site on the Camino de Santiago route.",
  "toledo-cathedral": "One of Spain's greatest Gothic structures.",
  "santiago-de-compostela-cathedral": "The famed pilgrimage route's final destination.",
  "aachen-cathedral": "Charlemagne is buried inside it.",
  "speyer-cathedral": "The largest Romanesque church still standing.",
  "ulm-minster": "Home to the tallest church steeple on Earth.",
  "siena-cathedral": "Its facade blends black and white marble stripes.",
  "orvieto-cathedral": "Its facade is famed for golden mosaics.",
  "palermo-cathedral": "Blends Norman, Gothic, and Islamic styles.",
  "matthias-church": "Its roof is covered in colorful glazed tiles.",
  "wawel-cathedral": "Poland's kings were once crowned here.",
  "st-sophia-cathedral-kyiv": "Ukraine's first UNESCO World Heritage site.",
  "cathedral-of-christ-the-saviour": "Rebuilt in the 1990s after being demolished in 1931.",
  "uppsala-cathedral": "Scandinavia's tallest cathedral.",
  "nidaros-cathedral": "Norway's medieval kings are buried here.",
  "helsinki-cathedral": "Its bright white facade overlooks Senate Square.",

  // HARD
  "liverpool-cathedral": "The largest cathedral in Britain.",
  "wells-cathedral": "Famed for its striking scissor arches.",
  "trier-cathedral": "Germany's oldest cathedral.",
  "naples-cathedral": "Home to a vial said to hold a saint's blood.",
  "monreale-cathedral": "Famous for its gold Byzantine mosaics.",
  "riga-cathedral": "The largest medieval church in the Baltics.",
  "vilnius-cathedral": "Lithuania's grand duke's are entombed within.",
  "zagreb-cathedral": "Rebuilt with twin spires after a 1880 earthquake.",
  "alexander-nevsky-cathedral": "One of the largest Orthodox cathedrals in the Balkans.",
  "bucharest-patriarchal-cathedral": "The seat of Romania's Orthodox Church.",
  "etchmiadzin-cathedral": "Widely called the world's oldest cathedral.",
  "sameba-cathedral": "One of the world's tallest Orthodox cathedrals.",
  "manila-cathedral": "Rebuilt eight times after fires and wars.",
  "lima-cathedral": "Conquistador Francisco Pizarro is entombed here.",
  "buenos-aires-cathedral": "Pope Francis once served as its archbishop.",
  "havana-cathedral": "Its facade blends into Old Havana's colonial square.",
  "quebec-cathedral": "The oldest parish north of Mexico.",
  "sydney-st-marys-cathedral": "Australia's largest Catholic cathedral.",

  // IMPOSSIBLE
  "holy-trinity-cathedral-addis-ababa": "Emperor Haile Selassie is buried here.",
  "coptic-cathedral-cairo": "The seat of Egypt's Coptic Orthodox Church.",
  "santo-domingo-cathedral": "The oldest cathedral in the Americas.",
  "quito-cathedral": "Sits on Ecuador's central Independence Square.",
  "bogota-cathedral": "The largest cathedral in Colombia.",
  "guatemala-cathedral": "Survived multiple devastating earthquakes.",
  "san-salvador-cathedral": "Overlooks the capital's central plaza.",
  "new-orleans-st-louis-cathedral": "The oldest cathedral in continuous use in the US.",
  "toronto-st-michaels-cathedral": "The seat of Toronto's Catholic archdiocese.",
  "christchurch-cathedral": "Heavily damaged by the 2011 earthquake.",
  "myeongdong-cathedral": "Korea's first Gothic-style cathedral.",
  "se-cathedral-goa": "One of Asia's largest churches.",
  "jakarta-cathedral": "Stands right across from Indonesia's largest mosque.",
  "colombo-cathedral": "The seat of Sri Lanka's Catholic archdiocese.",
  "yangon-cathedral": "Myanmar's largest Catholic cathedral.",
  "asuncion-cathedral": "Sits on Paraguay's central Plaza de la Independencia.",
  "la-paz-cathedral": "Built at over 3,600 meters above sea level.",
  "montevideo-cathedral": "Uruguay's oldest building still in use.",
};

export default CATHEDRALS_E60_FACTS;
