export const CHEESE_E98_FACTS = {
  // EASY
  cheddar: "In 1170, King Henry II reportedly bought over 10,000 pounds of cheddar cheese at a farthing a pound — the earliest known record of it.",
  mozzarella: "Fresh mozzarella's name comes from the Italian verb 'mozzare' ('to cut'), referring to how the curd is hand-cut during cheesemaking.",
  parmesan: "Genuine Parmigiano-Reggiano can legally be made in only five Italian provinces, and every wheel is aged at least 12 months before sale.",
  brie: "Though many cheeses are sold as 'Brie,' the French government officially certifies only two: Brie de Meaux and Brie de Melun.",
  gouda: "Gouda isn't named for where it's made — it's named after the Dutch city that once held the sole right to trade the cheese at market.",
  feta: "Feta must be at least 70% sheep's milk under EU rules, and its name comes from the Italian word 'fetta,' meaning slice.",
  "swiss-cheese": "The holes in Swiss-style cheese, called 'eyes,' form when carbon dioxide gas released by bacteria gets trapped inside the aging wheel.",
  "blue-cheese": "Analysis of ancient human waste in Austria's Hallstatt salt mines shows people were already eating blue cheese around 800 BC.",
  "cream-cheese": "Cream cheese was invented in the 1870s by dairyman William Lawrence in Chester, New York — not in Philadelphia, despite the famous brand name.",
  "cottage-cheese": "Cottage cheese got its name because American farm families originally made it in their cottages using milk left over from churning butter.",
  ricotta: "Ricotta means 'cooked again' in Italian — it's made by re-cooking the leftover whey from producing other cheeses like mozzarella.",
  camembert: "The wooden box now iconic for Camembert wasn't invented until 1890 — its padding let the soft cheese survive the long trip to America.",
  provolone: "Provolone curd is so pliable while warm that cheesemakers have traditionally molded it into shapes like sausages, pears, and even pigs.",
  gruyere: "Despite being sold as 'Swiss cheese' abroad, authentic Gruyère usually has few or no holes at all, unlike its cousin Emmental.",
  halloumi: "Halloumi's unusually high melting point lets it be fried or grilled without falling apart, and by law it can only be made in Cyprus.",
  mascarpone: "Mascarpone isn't technically a cheese at all — it's cream thickened with acid, made without any rennet or true curd formation.",
  "monterey-jack": "Monterey Jack traces back to 18th-century Franciscan friars in Spanish colonial California, making it one of the few cheeses invented in the US.",
  colby: "Colby, invented in 1885 in Colby, Wisconsin, is made by skipping cheddar's 'cheddaring' step and washing the curd with cold water.",

  // MEDIUM
  manchego: "Manchego must be made from the milk of Manchega sheep in Spain's La Mancha region, and can be aged from 60 days up to two years.",
  roquefort: "By French law, only cheese aged in the natural limestone caves around the village of Roquefort-sur-Soulzon can be called Roquefort.",
  gorgonzola: "Gorgonzola comes in two styles — mild, buttery 'dolce' and firmer, sharper 'piccante' — and is named after a town near Milan.",
  havarti: "Havarti was originally called 'Danish Tilsiter' before being renamed in 1952 after Havartigården, the farm of pioneer Hanne Nielsen.",
  fontina: "Authentic Italian Fontina from the Aosta Valley has been made since the 12th century and is stamped with an image of the Matterhorn.",
  "pecorino-romano": "Despite its name, most Pecorino Romano is now made on the island of Sardinia rather than near Rome, and it once fed Roman legionaries.",
  burrata: "Burrata was invented in Puglia in the 1920s as a way to use up mozzarella scraps, which are stuffed inside as its creamy filling.",
  paneer: "Unlike most cheeses, paneer doesn't melt when heated, which is why it can be cubed and fried directly into curries without falling apart.",
  "queso-fresco": "Queso fresco is often made without rennet at all, using just vinegar or lemon juice to curdle the milk, and it spoils quickly once cut.",
  stilton: "Stilton cheese cannot legally be made in the village of Stilton it's named after — only in Derbyshire, Leicestershire, or Nottinghamshire.",
  asiago: "Asiago was traditionally made from sheep's milk, but today's version is cow's milk, ranging from smooth and fresh to crumbly and aged.",
  muenster: "American Muenster was created by German immigrants imitating France's pungent Munster cheese, though the US version is milder and dyed orange.",
  edam: "Edam's wax coating and resistance to spoiling made it the world's most popular cheese between the 14th and 18th centuries, especially at sea.",
  "oaxaca-cheese": "Oaxaca cheese is stretched and wound into balls of cheese 'string,' a technique reportedly brought to Mexico by Dominican friars.",
  jarlsberg: "Jarlsberg is named after a Norwegian manor house, and its yellow wax rind and large holes make it a cousin of Swiss Emmental.",
  "port-salut": "Port Salut was developed by Trappist monks who fled France during the Revolution and later returned to their abbey to resume cheesemaking.",
  "grana-padano": "Grana Padano was created nearly 1,000 years ago by Cistercian monks preserving surplus milk, and its crunchy specks are crystallized amino acids.",
  cheshire: "Cheshire, England's oldest named cheese, dates back to Roman Britain and is even referenced in the Domesday Book.",

  // HARD
  comte: "Comté is France's top-selling PDO cheese, with about 65,000 tonnes made yearly using techniques from the Jura mountains dating back 1,000 years.",
  caerphilly: "Caerphilly cheese was created around 1830 specifically as a practical snack for Welsh coal miners, thanks to its salt and thick rind.",
  reblochon: "Reblochon's name means 're-pinching' a cow's udder — 14th-century farmers under-milked for tax collectors, then finished secretly to make cheese.",
  appenzeller: "Appenzeller's tangy bite comes from a secret herbal brine called 'Sulz,' made from over 25 herbs and known to only a handful of people.",
  chevre: "Goat cheese is one of humanity's oldest dairy foods, with evidence of production dating back roughly 10,000 years to the Fertile Crescent.",
  "munster-french": "Munster cheese takes its name from the Alsatian town where Vosges monasteries once aged and stored it in their monastery cellars.",
  cotija: "Named after a Mexican town, Cotija softens but never fully melts when heated, and its aged form is often compared in taste to Parmesan.",
  caciocavallo: "Caciocavallo means 'horse cheese' in Italian, from tying paired cheeses with rope and draping them over a beam to age 'a cavallo' (astride).",
  kefalotyri: "Kefalotyri, a hard salty Greek cheese dating to the Byzantine era, is the classic choice for saganaki, the flaming fried-cheese dish.",
  "vacherin-mont-dor": "Vacherin Mont d'Or is bound in a strip of spruce bark harvested by specialists called 'sangliers,' which perfumes the cheese as it ages.",
  kashkaval: "Kashkaval is nicknamed the 'Cheddar of the Balkans' for its taste, and its name is believed to derive from the Italian cheese caciocavallo.",
  brunost: "Brunost gets its caramel-brown color from slowly boiling whey, milk, and cream for hours until the milk sugars caramelize.",
  idiazabal: "Idiazábal cheese takes its name from a small Basque town and is traditionally made only from the raw milk of native Latxa sheep.",
  "paski-sir": "Paški sir gets its bite from salty Adriatic wind that blows onto the Croatian island of Pag, seasoning the sage the local sheep graze on.",
  sirene: "Sirene, Bulgaria's answer to feta, is typically smoother and creamier than Greek feta because it holds on to more moisture.",
  "queijo-coalho": "Queijo coalho is a popular beach snack in northeastern Brazil, grilled on a stick over charcoal until it gets a golden, charred crust.",

  // IMPOSSIBLE
  "formaggio-di-fossa": "Formaggio di fossa is aged for months inside pits dug into volcanic tufa rock, an Italian tradition dating back to the 14th century.",
  maroilles: "Maroilles has such a strong smell that the mild flavor underneath comes as a surprise — it's sold in rectangular blocks with a moist orange rind.",
  "stinking-bishop": "Stinking Bishop cheese is washed in perry made from a pear variety named after a real 19th-century farmer nicknamed 'Stinking Bishop.'",
  langres: "Langres cheese is never flipped during aging, so a natural dimple called the 'fontaine' forms on top, traditionally filled with Champagne.",
  mimolette: "Mimolette's crusty grey rind comes from cheese mites deliberately added during aging; the US restricted its import over mite counts until 2014.",
  cabrales: "Cabrales blue cheese is aged for months inside natural limestone caves in Spain's Picos de Europa mountains.",
  "tomme-de-savoie": "Tomme de Savoie was traditionally made from the low-fat milk left over after farmers skimmed the cream to make butter or richer cheeses.",
  telemea: "Telemea has been a protected Romanian PDO cheese since 2005, with distinct regional versions from towns like Sibiu, Brașov, and Ibănești.",
  livarot: "Livarot is bound with five strips of reed that once held the wheel together on stagecoach journeys, earning it the nickname 'the Colonel.'",
  "kesong-puti": "Kesong puti, the Philippines' classic fresh cheese, is traditionally made from carabao (water buffalo) milk and sold wrapped in banana leaves.",
  wagasi: "Wagasi, made by Fulani herders in West Africa, is traditionally curdled using leaves from the local 'fromager' tree instead of animal rennet.",
  "murcia-al-vino": "Murcia al Vino cheese gets its striking purple-red rind from being repeatedly bathed in red wine as it matures.",
  shanklish: "Shanklish is rolled into balls from strained fermented yogurt and coated in za'atar or Aleppo pepper, growing more pungent as it ages.",
  kalari: "Kalari, sometimes called the 'mozzarella of Kashmir,' is sun-dried in small leaf bowls before being pan-fried in its own fat to serve.",
  sulguni: "Sulguni is nicknamed Georgia's 'pickled cheese' for its tangy sourness, and it's often deep-fried, which helps mask its pungent smell.",
  "crottin-de-chavignol": "This tiny goat cheese takes its name from the clay molds once used to drain it, shaped like the oil lamps called 'crots' in the local dialect.",
  "ossau-iraty": "Ossau-Iraty is a French sheep's-milk cheese made by a tradition roughly 3,000 years old, and is traditionally served with black cherry jam.",
  bryndza: "Bryndza's name comes from the Romanian word for cheese, 'brânză,' brought to Slovakia centuries ago by migrating Vlach shepherds.",
};
