export const CHEESE_E98 = [
  // ===== EASY (18) =====
  { slug: "cheddar", name: "Cheddar", level: "easy", wiki: "Cheddar cheese" },
  { slug: "mozzarella", name: "Mozzarella", level: "easy", wiki: "Mozzarella" },
  { slug: "parmesan", name: "Parmesan", level: "easy", wiki: "Parmesan" },
  { slug: "brie", name: "Brie", level: "easy", wiki: "Brie" },
  { slug: "gouda", name: "Gouda", level: "easy", wiki: "Gouda cheese" },
  { slug: "feta", name: "Feta", level: "easy", wiki: "Feta" },
  { slug: "swiss-cheese", name: "Swiss Cheese", level: "easy", wiki: "Swiss cheese (North America)" },
  { slug: "blue-cheese", name: "Blue Cheese", level: "easy", wiki: "Blue cheese" },
  { slug: "cream-cheese", name: "Cream Cheese", level: "easy", wiki: "Cream cheese" },
  { slug: "cottage-cheese", name: "Cottage Cheese", level: "easy", wiki: "Cottage cheese" },
  { slug: "ricotta", name: "Ricotta", level: "easy", wiki: "Ricotta" },
  { slug: "camembert", name: "Camembert", level: "easy", wiki: "Camembert" },
  { slug: "provolone", name: "Provolone", level: "easy", wiki: "Provolone" },
  { slug: "gruyere", name: "Gruyère", level: "easy", wiki: "Gruyère cheese" },
  { slug: "halloumi", name: "Halloumi", level: "easy", wiki: "Halloumi" },
  { slug: "mascarpone", name: "Mascarpone", level: "easy", wiki: "Mascarpone" },
  { slug: "monterey-jack", name: "Monterey Jack", level: "easy", wiki: "Monterey Jack" },
  { slug: "colby", name: "Colby", level: "easy", wiki: "Colby cheese" },

  // ===== MEDIUM (18) =====
  { slug: "manchego", name: "Manchego", level: "medium", wiki: "Manchego" },
  { slug: "roquefort", name: "Roquefort", level: "medium", wiki: "Roquefort" },
  { slug: "gorgonzola", name: "Gorgonzola", level: "medium", wiki: "Gorgonzola" },
  { slug: "havarti", name: "Havarti", level: "medium", wiki: "Havarti" },
  { slug: "fontina", name: "Fontina", level: "medium", wiki: "Fontina" },
  { slug: "pecorino-romano", name: "Pecorino Romano", level: "medium", wiki: "Pecorino romano" },
  { slug: "burrata", name: "Burrata", level: "medium", wiki: "Burrata" },
  { slug: "paneer", name: "Paneer", level: "medium", wiki: "Paneer" },
  { slug: "queso-fresco", name: "Queso Fresco", level: "medium", wiki: "White cheese" },
  { slug: "stilton", name: "Stilton", level: "medium", wiki: "Stilton cheese" },
  { slug: "asiago", name: "Asiago", level: "medium", wiki: "Asiago cheese" },
  { slug: "muenster", name: "Muenster", level: "medium", wiki: "Muenster cheese" },
  { slug: "edam", name: "Edam", level: "medium", wiki: "Edam cheese" },
  { slug: "oaxaca-cheese", name: "Oaxaca Cheese", level: "medium", wiki: "Oaxaca cheese" },
  { slug: "raclette", name: "Raclette", level: "medium", wiki: "Raclette" },
  { slug: "port-salut", name: "Port Salut", level: "medium", wiki: "Port Salut" },
  { slug: "grana-padano", name: "Grana Padano", level: "medium", wiki: "Grana Padano" },
  { slug: "cheshire", name: "Cheshire Cheese", level: "medium", wiki: "Cheshire cheese" },

  // ===== HARD (16) =====
  { slug: "comte", name: "Comté", level: "hard", wiki: "Comté cheese" },
  { slug: "caerphilly", name: "Caerphilly", level: "hard", wiki: "Caerphilly cheese" },
  { slug: "reblochon", name: "Reblochon", level: "hard", wiki: "Reblochon" },
  { slug: "appenzeller", name: "Appenzeller", level: "hard", wiki: "Appenzeller cheese" },
  { slug: "chevre", name: "Chèvre", level: "hard", wiki: "Goat cheese" },
  { slug: "munster-french", name: "Munster (France)", level: "hard", wiki: "Munster cheese" },
  { slug: "cotija", name: "Cotija", level: "hard", wiki: "Cotija cheese" },
  { slug: "caciocavallo", name: "Caciocavallo", level: "hard", wiki: "Caciocavallo" },
  { slug: "kefalotyri", name: "Kefalotyri", level: "hard", wiki: "Kefalotyri" },
  { slug: "vacherin-mont-dor", name: "Vacherin Mont d'Or", level: "hard", wiki: "Vacherin Mont d'Or" },
  { slug: "kashkaval", name: "Kashkaval", level: "hard", wiki: "Kashkaval" },
  { slug: "brunost", name: "Brunost", level: "hard", wiki: "Brunost" },
  { slug: "idiazabal", name: "Idiazábal", level: "hard", wiki: "Idiazabal cheese" },
  { slug: "paski-sir", name: "Paški Sir", level: "hard", wiki: "Paški sir" },
  { slug: "sirene", name: "Sirene", level: "hard", wiki: "Sirene" },
  { slug: "queijo-coalho", name: "Queijo Coalho", level: "hard", wiki: "Queijo coalho" },

  // ===== IMPOSSIBLE (18) =====
  { slug: "formaggio-di-fossa", name: "Formaggio di Fossa", level: "impossible", wiki: "Formaggio di fossa" },
  { slug: "maroilles", name: "Maroilles", level: "impossible", wiki: "Maroilles cheese" },
  { slug: "stinking-bishop", name: "Stinking Bishop", level: "impossible", wiki: "Stinking Bishop (cheese)" },
  { slug: "langres", name: "Langres", level: "impossible", wiki: "Langres cheese" },
  { slug: "mimolette", name: "Mimolette", level: "impossible", wiki: "Mimolette" },
  { slug: "cabrales", name: "Cabrales", level: "impossible", wiki: "Cabrales cheese" },
  { slug: "tomme-de-savoie", name: "Tomme de Savoie", level: "impossible", wiki: "Tomme de Savoie" },
  { slug: "telemea", name: "Telemea", level: "impossible", wiki: "Telemea" },
  { slug: "livarot", name: "Livarot", level: "impossible", wiki: "Livarot cheese" },
  { slug: "kesong-puti", name: "Kesong Puti", level: "impossible", wiki: "Kesong puti" },
  { slug: "wagasi", name: "Wagasi", level: "impossible", wiki: "Wagasi" },
  { slug: "murcia-al-vino", name: "Murcia al Vino", level: "impossible", wiki: "Murcian wine cheese" },
  { slug: "shanklish", name: "Shanklish", level: "impossible", wiki: "Shanklish" },
  { slug: "kalari", name: "Kalari", level: "impossible", wiki: "Kalari cheese" },
  { slug: "sulguni", name: "Sulguni", level: "impossible", wiki: "Sulguni" },
  { slug: "crottin-de-chavignol", name: "Crottin de Chavignol", level: "impossible", wiki: "Crottin de Chavignol" },
  { slug: "ossau-iraty", name: "Ossau-Iraty", level: "impossible", wiki: "Ossau-Iraty" },
  { slug: "bryndza", name: "Bryndza", level: "impossible", wiki: "Bryndza" },
];
