// E21 "Guess the City by Skyline" — answer = city name.
// Calibrated by global skyline recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
// Hard content rules: no Israel/Jerusalem/West Bank/Gaza content, no disputed-territory ambiguity.
export const CITY_SKYLINE_E21 = [
  // EASY (18) — instantly recognizable skylines worldwide
  { slug: "new-york-city", city: "New York City", level: "easy" },
  { slug: "dubai", city: "Dubai", level: "easy" },
  { slug: "hong-kong", city: "Hong Kong", level: "easy" },
  { slug: "shanghai", city: "Shanghai", level: "easy" },
  { slug: "chicago", city: "Chicago", level: "easy" },
  { slug: "london", city: "London", level: "easy" },
  { slug: "paris", city: "Paris", level: "easy" },
  { slug: "tokyo", city: "Tokyo", level: "easy" },
  { slug: "singapore", city: "Singapore", level: "easy" },
  { slug: "sydney", city: "Sydney", level: "easy" },
  { slug: "toronto", city: "Toronto", level: "easy" },
  { slug: "los-angeles", city: "Los Angeles", level: "easy" },
  { slug: "las-vegas", city: "Las Vegas", level: "easy" },
  { slug: "san-francisco", city: "San Francisco", level: "easy" },
  { slug: "miami", city: "Miami", level: "easy" },
  { slug: "doha", city: "Doha", level: "easy" },
  { slug: "kuala-lumpur", city: "Kuala Lumpur", level: "easy" },
  { slug: "seoul", city: "Seoul", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "bangkok", city: "Bangkok", level: "medium" },
  { slug: "mumbai", city: "Mumbai", level: "medium" },
  { slug: "moscow", city: "Moscow", level: "medium" },
  { slug: "istanbul", city: "Istanbul", level: "medium" },
  { slug: "vancouver", city: "Vancouver", level: "medium" },
  { slug: "melbourne", city: "Melbourne", level: "medium" },
  { slug: "frankfurt", city: "Frankfurt", level: "medium" },
  { slug: "shenzhen", city: "Shenzhen", level: "medium" },
  { slug: "guangzhou", city: "Guangzhou", level: "medium" },
  { slug: "taipei", city: "Taipei", level: "medium" },
  { slug: "rio-de-janeiro", city: "Rio de Janeiro", level: "medium" },
  { slug: "sao-paulo", city: "São Paulo", level: "medium" },
  { slug: "mexico-city", city: "Mexico City", level: "medium" },
  { slug: "boston", city: "Boston", level: "medium" },
  { slug: "philadelphia", city: "Philadelphia", level: "medium" },
  { slug: "houston", city: "Houston", level: "medium" },
  { slug: "dallas", city: "Dallas", level: "medium" },
  { slug: "atlanta", city: "Atlanta", level: "medium" },

  // HARD (18) — recognizable to well-traveled/enthusiast viewers
  { slug: "jakarta", city: "Jakarta", level: "hard" },
  { slug: "manila", city: "Manila", level: "hard" },
  { slug: "busan", city: "Busan", level: "hard" },
  { slug: "panama-city", city: "Panama City", level: "hard" },
  { slug: "beijing", city: "Beijing", level: "hard" },
  { slug: "nanjing", city: "Nanjing", level: "hard" },
  { slug: "wuhan", city: "Wuhan", level: "hard" },
  { slug: "chongqing", city: "Chongqing", level: "hard" },
  { slug: "warsaw", city: "Warsaw", level: "hard" },
  { slug: "kyiv", city: "Kyiv", level: "hard" },
  { slug: "casablanca", city: "Casablanca", level: "hard" },
  { slug: "nairobi", city: "Nairobi", level: "hard" },
  { slug: "cape-town", city: "Cape Town", level: "hard" },
  { slug: "johannesburg", city: "Johannesburg", level: "hard" },
  { slug: "manama", city: "Manama", level: "hard" },
  { slug: "astana", city: "Astana", level: "hard" },
  { slug: "baku", city: "Baku", level: "hard" },
  { slug: "tashkent", city: "Tashkent", level: "hard" },

  // IMPOSSIBLE (17) — obscure even to enthusiasts
  { slug: "almaty", city: "Almaty", level: "impossible" },
  { slug: "bishkek", city: "Bishkek", level: "impossible" },
  { slug: "dushanbe", city: "Dushanbe", level: "impossible" },
  { slug: "ashgabat", city: "Ashgabat", level: "impossible" },
  { slug: "ulaanbaatar", city: "Ulaanbaatar", level: "impossible" },
  { slug: "vientiane", city: "Vientiane", level: "impossible" },
  { slug: "phnom-penh", city: "Phnom Penh", level: "impossible" },
  { slug: "yangon", city: "Yangon", level: "impossible" },
  { slug: "dhaka", city: "Dhaka", level: "impossible" },
  { slug: "colombo", city: "Colombo", level: "impossible" },
  { slug: "kathmandu", city: "Kathmandu", level: "impossible" },
  { slug: "tbilisi", city: "Tbilisi", level: "impossible" },
  { slug: "yerevan", city: "Yerevan", level: "impossible" },
  { slug: "chisinau", city: "Chisinau", level: "impossible" },
  { slug: "minsk", city: "Minsk", level: "impossible" },
  { slug: "bratislava", city: "Bratislava", level: "impossible" },
  { slug: "ljubljana", city: "Ljubljana", level: "impossible" },
];
