export const CITY_SKYLINE_E21_FACTS = {
  "new-york-city": "The Empire State Building has its own zip code, 10118.",
  "dubai": "Dubai's Burj Khalifa is the tallest building on Earth.",
  "hong-kong": "Hong Kong has more skyscrapers than any other city on Earth.",
  "shanghai": "Shanghai's Tower spirals upward with a 120-degree twist.",
  "chicago": "Chicago's Home Insurance Building (1885) is the first skyscraper.",
  "london": "London's Shard has 72 habitable floors of glass.",
  "paris": "Paris limits most buildings to under 37 meters by law.",
  "tokyo": "Tokyo's skyline hides over 13 million residents below it.",
  "singapore": "Marina Bay Sands' rooftop pool sits 57 stories up.",
  "sydney": "Sydney Tower stands taller than any other structure in the city.",
  "toronto": "The CN Tower held the world's tallest freestanding title for 32 years.",
  "los-angeles": "Downtown LA's height limit wasn't lifted until 1957.",
  "las-vegas": "The Las Vegas Strip is technically outside city limits.",
  "san-francisco": "The Salesforce Tower is San Francisco's tallest building.",
  "miami": "Almost all of Miami's tallest towers were built after the year 2000.",
  "doha": "Doha's skyline sprouted almost entirely after the year 2000.",
  "kuala-lumpur": "The Petronas Towers were the world's tallest buildings until 2004.",
  "seoul": "Seoul's Lotte World Tower has 123 floors.",
  "bangkok": "Bangkok's King Power Mahanakhon has a glass \"pixelated\" design.",
  "mumbai": "Mumbai has more skyscrapers than any other Indian city.",
  "moscow": "Moscow City's towers form Europe's tallest skyscraper cluster.",
  "istanbul": "Istanbul is the only major city spanning two continents.",
  "vancouver": "Vancouver pioneered the slim glass-tower style called \"Vancouverism\".",
  "melbourne": "Eureka Tower once had the Southern Hemisphere's highest skydeck.",
  "frankfurt": "Frankfurt's skyline earned it the nickname \"Mainhattan\".",
  "shenzhen": "Shenzhen grew from a fishing village into a skyscraper city since 1980",
  "guangzhou": "Guangzhou's Canton Tower twists like a spiraling hourglass.",
  "taipei": "Taipei 101 was the world's tallest building from 2004 to 2010.",
  "rio-de-janeiro": "Rio's skyline sits between mountains and Guanabara Bay.",
  "sao-paulo": "Sao Paulo has the world's largest helicopter fleet, ahead of New York.",
  "mexico-city": "Mexico City's towers are engineered for a major earthquake zone.",
  "boston": "Boston's Hancock Tower is famed for its mirrored glass facade.",
  "philadelphia": "Philadelphia's height limit once capped buildings at City Hall's top.",
  "houston": "Houston's skyline has no citywide zoning code restricting it.",
  "dallas": "Dallas's Reunion Tower is topped by a glowing geodesic dome.",
  "atlanta": "Atlanta's Bank of America Plaza is the tallest tower in the US South.",
  "jakarta": "Jakarta's skyline sits on land that is slowly sinking each year.",
  "manila": "Manila's Makati district is the Philippines' financial hub.",
  "busan": "Busan's Haeundae district has some of Korea's tallest towers.",
  "panama-city": "Panama City's skyline rivals Miami's along the canal's edge.",
  "beijing": "Beijing's CCTV Headquarters forms a bent loop shape.",
  "nanjing": "Nanjing's Zifeng Tower rises beside the centuries-old Ming Drum Tower.",
  "wuhan": "Wuhan sits where the Han River meets the mighty Yangtze.",
  "chongqing": "Chongqing's hilly terrain gives it a stacked, layered skyline.",
  "warsaw": "Warsaw's Palace of Culture was a gift from the Soviet Union in 1955.",
  "kyiv": "Kyiv's golden-domed churches rise above the Dnipro River.",
  "casablanca": "Casablanca is Morocco's largest city and economic center.",
  "nairobi": "Nairobi National Park sits right beside its modern skyline.",
  "cape-town": "Cape Town's skyline sits in the shadow of Table Mountain.",
  "johannesburg": "Johannesburg was built on the world's richest gold reef.",
  "manama": "Manama's World Trade Center towers have wind turbines between them.",
  "astana": "Astana's Bayterek Tower symbolizes a poplar tree in local legend.",
  "baku": "Baku's Flame Towers glow at night to resemble fire.",
  "tashkent": "Tashkent was almost entirely rebuilt after a 1966 earthquake.",
  "almaty": "Almaty served as Kazakhstan's capital until 1997.",
  "bishkek": "Bishkek sits at the foot of the snow-capped Tian Shan mountains.",
  "dushanbe": "Dushanbe means \"Monday\" in Tajik, named for its market day.",
  "ashgabat": "Ashgabat holds a Guinness record for its density of marble buildings.",
  "ulaanbaatar": "Ulaanbaatar is the coldest capital city on Earth.",
  "vientiane": "Vientiane's Patuxai monument was built partly with US-donated cement.",
  "phnom-penh": "Phnom Penh sits where the Mekong and Tonle Sap rivers meet.",
  "yangon": "Yangon's skyline is anchored by the golden Shwedagon Pagoda.",
  "dhaka": "Dhaka is one of the most densely populated cities on Earth.",
  "colombo": "Colombo's Lotus Tower is South Asia's tallest self-supported tower.",
  "kathmandu": "Kathmandu sits in a valley ringed by Himalayan foothills.",
  "tbilisi": "Tbilisi's name comes from the Georgian word for \"warm\" springs.",
  "yerevan": "Yerevan is older than Rome, founded in 782 BC.",
  "chisinau": "Chisinau is built across seven hills, much like Rome.",
  "minsk": "Minsk was almost completely rebuilt after WWII devastation.",
  "bratislava": "Bratislava is the only capital bordering two countries.",
  "ljubljana": "Ljubljana's castle overlooks a skyline of red-tiled roofs.",
};
