export const CLASSIC_CARS_E53_FACTS = {
  // EASY
  "volkswagen-beetle": "In production 1938-2003; over 21 million built worldwide.",
  "mini-cooper": "Designed by Alec Issigonis in 1959 to fit four adults in 10 feet.",
  "ford-mustang": "Launched in 1964; sold over a million units in its first 18 months.",
  "delorean-dmc-12": "Its gullwing doors and steel body starred in Back to the Future.",
  "volkswagen-bus": "Nicknamed the Microbus; a 1960s counterculture road-trip icon.",
  "fiat-500-classic": "The 1957 Nuova 500 was Italy's tiny answer to the VW Beetle.",
  "porsche-911": "In continuous production since 1964 with its rear-engine layout.",
  "chevrolet-corvette": "America's first mass-produced fiberglass-bodied sports car.",
  "jeep-wrangler": "Descends directly from the WWII military Willys Jeep.",
  "citroen-2cv": "Designed for French farmers to carry eggs over a plowed field.",
  "land-rover-defender": "Its boxy aluminum body barely changed shape for over 60 years.",
  "rolls-royce-silver-shadow": "The first Rolls-Royce with a modern monocoque body, from 1965.",
  "lamborghini-countach": "Its 1974 wedge shape and scissor doors defined 1980s poster cars.",
  "ferrari-testarossa": "Famous for the side strakes cooling its rear-mounted radiators.",
  "cadillac-eldorado": "The 1959 model wore the tallest tailfins Cadillac ever built.",
  "smart-fortwo": "Just 2.5 meters long, it can often park nose-in to the curb.",
  "ford-model-t": "The 1908 car that put America on wheels via the moving assembly line.",
  "volkswagen-golf": "Replaced the Beetle in 1974 and became Europe's best-selling car.",
  "austin-fx4-london-taxi": "London's black cab shape stayed on the road from 1958 to 1997.",

  // MEDIUM
  "toyota-corolla": "The best-selling car nameplate in automotive history since 1966.",
  "honda-civic": "Launched in 1972; helped Honda survive the 1970s oil crisis.",
  "chevrolet-camaro": "Built to rival the Mustang as Chevrolet's 1967 pony car answer.",
  "dodge-charger": "The 1969 Charger played the General Lee in Dukes of Hazzard.",
  "ferrari-250-gto": "Only 36 were built; one later sold for over $70 million.",
  "nissan-skyline-gtr-r34": "Nicknamed Godzilla; famous from 2 Fast 2 Furious.",
  "toyota-supra-a80": "Its 2JZ engine became a legend in tuning and drift culture.",
  "mazda-mx5-miata": "The best-selling two-seat convertible sports car ever made.",
  "range-rover-classic": "Launched in 1970; the first Range Rover hung in the Louvre as art.",
  "volvo-240": "Boxy and famously safe; some owners report 500,000+ miles.",
  "fiat-panda": "A boxy 1980 city car designed by Giorgetto Giugiaro's studio.",
  "renault-4": "France's answer to the 2CV; over 8 million were built by 1992.",
  "chevrolet-bel-air-1957": "Its chrome and tailfins made 1957 the classic American car year.",
  "hummer-h2": "A civilian SUV styled after the military Humvee, launched in 2002.",
  "volkswagen-karmann-ghia": "An Italian-styled coupe body built on humble Beetle underpinnings.",
  "toyota-land-cruiser": "Toyota's toughest SUV, in continuous production since 1951.",
  "mercedes-g-class": "Its boxy shape has barely changed since debuting in 1979.",
  "ford-focus": "A 1998 compact praised for handling that changed its whole class.",
  "audi-quattro": "Its 1980 all-wheel-drive system rewrote rally racing history.",

  // HARD
  "lancia-delta-integrale": "A boxy hatchback that won the WRC manufacturers' title six times.",
  "datsun-240z": "Its 1969 launch brought an affordable sports car GT to America.",
  "alfa-romeo-giulietta": "A 1950s Italian sedan and coupe prized for its light, sporty feel.",
  "peugeot-205-gti": "A featherweight 1984 hot hatch enthusiasts still chase today.",
  "renault-5-turbo": "Its engine moved behind the seats for 1980s rally homologation.",
  "saab-900": "Known for its curved windshield and aircraft-inspired cockpit.",
  "triumph-spitfire": "A British roadster with a nose that tilts forward to open.",
  "mgb": "One of Britain's most popular sports cars, built from 1962 to 1980.",
  "opel-manta": "A 1970s German coupe later mocked in British tuner-car jokes.",
  "toyota-ae86": "This 1980s Corolla coupe became an icon through Initial D.",
  "honda-nsx": "A 1990 supercar engineered with input from F1 driver Ayrton Senna.",
  "mitsubishi-lancer-evolution": "A rally-bred sedan built to chase the Subaru WRX STI.",
  "subaru-impreza-wrx-sti": "Its rally pedigree comes with a signature hood scoop.",
  "volkswagen-corrado": "A sleek 1988 coupe with a rear spoiler that rises at speed.",
  "datsun-510": "A budget 1968 sedan nicknamed the poor man's BMW for its handling.",
  "alpine-a110": "A featherweight 1961 French coupe that won the first WRC title.",
  "lotus-esprit": "James Bond drove one that transformed into a submarine on-screen.",
  "plymouth-superbird": "Its huge rear wing and pointed nose chased NASCAR aero records.",

  // IMPOSSIBLE
  "citroen-ds": "Its hydropneumatic suspension let it drive on three wheels.",
  "saab-92": "Saab's first car, from 1949, shaped by aircraft aerodynamics.",
  "trabant-601": "East Germany's car had a plastic body and a two-stroke engine.",
  "bristol-400": "A rare 1947 British grand tourer built by an aircraft maker.",
  "skoda-1000mb": "A 1964 Czechoslovak sedan with its engine mounted in the rear.",
  "tatra-77": "A 1934 Czech car among the first with true streamlined aerodynamics.",
  "wartburg-353": "An East German family car known for its smoky two-stroke exhaust.",
  "reliant-robin": "A British three-wheeler famously prone to tipping over in turns.",
  "bmw-isetta": "This 1955 bubble car's entire front end swings open as the door.",
  "subaru-360": "A tiny rear-engined kei car that launched Subaru in the US in 1968.",
  "honda-n360": "Honda's first mass-market kei car, launched in Japan in 1967.",
  "daihatsu-midget": "A three-wheeled mini truck steered with motorcycle handlebars.",
  "amphicar": "A 1960s convertible that could drive straight into a lake.",
  "messerschmitt-kr200": "A former aircraft maker's bubble car with tandem seating.",
  "fso-polonez": "Poland's home-grown hatchback stayed in production 24 years.",
  "zastava-yugo": "A cheap Yugoslav hatchback once notorious on US used-car lots.",
  "autobianchi-bianchina": "A stylish 1957 microcar built on humble Fiat 500 mechanicals.",
  "panhard-dyna-z": "A 1954 French sedan with an aluminum body ahead of its time.",
};
