// E25 "Guess the Football Club" — answer = club name, image = official club badge/crest.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
// Hard content rules: no Israeli clubs (Maccabi Tel Aviv, Hapoel Tel Aviv, Beitar Jerusalem, etc.) — screened out entirely.
export const CLUB_BADGES_E25 = [
  // EASY (18) — globally iconic, instantly recognized worldwide
  { slug: "real-madrid", name: "Real Madrid", level: "easy" },
  { slug: "fc-barcelona", name: "FC Barcelona", level: "easy" },
  { slug: "manchester-united", name: "Manchester United", level: "easy" },
  { slug: "liverpool", name: "Liverpool", level: "easy" },
  { slug: "manchester-city", name: "Manchester City", level: "easy" },
  { slug: "chelsea", name: "Chelsea", level: "easy" },
  { slug: "arsenal", name: "Arsenal", level: "easy" },
  { slug: "bayern-munich", name: "Bayern Munich", level: "easy" },
  { slug: "juventus", name: "Juventus", level: "easy" },
  { slug: "paris-saint-germain", name: "Paris Saint-Germain", level: "easy" },
  { slug: "ac-milan", name: "AC Milan", level: "easy" },
  { slug: "inter-milan", name: "Inter Milan", level: "easy" },
  { slug: "tottenham-hotspur", name: "Tottenham Hotspur", level: "easy" },
  { slug: "borussia-dortmund", name: "Borussia Dortmund", level: "easy" },
  { slug: "atletico-madrid", name: "Atletico Madrid", level: "easy" },
  { slug: "as-roma", name: "AS Roma", level: "easy" },
  { slug: "ajax", name: "Ajax", level: "easy" },
  { slug: "boca-juniors", name: "Boca Juniors", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "river-plate", name: "River Plate", level: "medium" },
  { slug: "napoli", name: "Napoli", level: "medium" },
  { slug: "newcastle-united", name: "Newcastle United", level: "medium" },
  { slug: "west-ham-united", name: "West Ham United", level: "medium" },
  { slug: "everton", name: "Everton", level: "medium" },
  { slug: "leicester-city", name: "Leicester City", level: "medium" },
  { slug: "sevilla", name: "Sevilla", level: "medium" },
  { slug: "valencia", name: "Valencia", level: "medium" },
  { slug: "porto", name: "Porto", level: "medium" },
  { slug: "benfica", name: "Benfica", level: "medium" },
  { slug: "marseille", name: "Marseille", level: "medium" },
  { slug: "lyon", name: "Lyon", level: "medium" },
  { slug: "bayer-leverkusen", name: "Bayer Leverkusen", level: "medium" },
  { slug: "flamengo", name: "Flamengo", level: "medium" },
  { slug: "fenerbahce", name: "Fenerbahce", level: "medium" },
  { slug: "galatasaray", name: "Galatasaray", level: "medium" },
  { slug: "celtic", name: "Celtic", level: "medium" },
  { slug: "schalke-04", name: "Schalke 04", level: "medium" },

  // HARD (18) — recognizable to serious football enthusiasts
  { slug: "sporting-cp", name: "Sporting CP", level: "hard" },
  { slug: "rb-leipzig", name: "RB Leipzig", level: "hard" },
  { slug: "villarreal", name: "Villarreal", level: "hard" },
  { slug: "athletic-bilbao", name: "Athletic Bilbao", level: "hard" },
  { slug: "real-sociedad", name: "Real Sociedad", level: "hard" },
  { slug: "monaco", name: "Monaco", level: "hard" },
  { slug: "lille", name: "Lille", level: "hard" },
  { slug: "wolfsburg", name: "Wolfsburg", level: "hard" },
  { slug: "werder-bremen", name: "Werder Bremen", level: "hard" },
  { slug: "feyenoord", name: "Feyenoord", level: "hard" },
  { slug: "psv-eindhoven", name: "PSV Eindhoven", level: "hard" },
  { slug: "rangers", name: "Rangers", level: "hard" },
  { slug: "palmeiras", name: "Palmeiras", level: "hard" },
  { slug: "corinthians", name: "Corinthians", level: "hard" },
  { slug: "santos", name: "Santos", level: "hard" },
  { slug: "al-ahly", name: "Al Ahly", level: "hard" },
  { slug: "club-america", name: "Club America", level: "hard" },
  { slug: "al-hilal", name: "Al Hilal", level: "hard" },

  // IMPOSSIBLE (17) — obscure even to enthusiasts
  { slug: "anderlecht", name: "Anderlecht", level: "impossible" },
  { slug: "club-brugge", name: "Club Brugge", level: "impossible" },
  { slug: "red-bull-salzburg", name: "Red Bull Salzburg", level: "impossible" },
  { slug: "dynamo-kyiv", name: "Dynamo Kyiv", level: "impossible" },
  { slug: "shakhtar-donetsk", name: "Shakhtar Donetsk", level: "impossible" },
  { slug: "olympiacos", name: "Olympiacos", level: "impossible" },
  { slug: "panathinaikos", name: "Panathinaikos", level: "impossible" },
  { slug: "aik", name: "AIK", level: "impossible" },
  { slug: "malmo-ff", name: "Malmo FF", level: "impossible" },
  { slug: "rosenborg", name: "Rosenborg", level: "impossible" },
  { slug: "legia-warsaw", name: "Legia Warsaw", level: "impossible" },
  { slug: "slavia-prague", name: "Slavia Prague", level: "impossible" },
  { slug: "sparta-prague", name: "Sparta Prague", level: "impossible" },
  { slug: "ferencvaros", name: "Ferencvaros", level: "impossible" },
  { slug: "dinamo-zagreb", name: "Dinamo Zagreb", level: "impossible" },
  { slug: "universidad-de-chile", name: "Universidad de Chile", level: "impossible" },
  { slug: "fc-copenhagen", name: "FC Copenhagen", level: "impossible" },
];
