export const CLUB_BADGES_E25_FACTS = {
  "real-madrid": "Real Madrid have won more European Cups than any other club.",
  "fc-barcelona": "Barcelona's motto is 'More than a club' (Mes que un club).",
  "manchester-united": "Manchester United are nicknamed 'The Red Devils'.",
  "liverpool": "Liverpool's anthem is 'You'll Never Walk Alone'.",
  "manchester-city": "Manchester City's stadium is named after an airline sponsor.",
  "chelsea": "Chelsea's crest features a lion holding a staff.",
  "arsenal": "Arsenal are nicknamed 'The Gunners' after their cannon badge.",
  "bayern-munich": "Bayern Munich have won the Bundesliga more than any other club.",
  "juventus": "Juventus are nicknamed 'The Old Lady' (La Vecchia Signora).",
  "paris-saint-germain": "PSG's crest features the Eiffel Tower.",
  "ac-milan": "AC Milan share the San Siro stadium with Inter Milan.",
  "inter-milan": "Inter Milan is the only Italian club never relegated from Serie A.",
  "tottenham-hotspur": "Tottenham's badge features a cockerel standing on a ball.",
  "borussia-dortmund": "Borussia Dortmund's stadium has the famous 'Yellow Wall' terrace.",
  "atletico-madrid": "Atletico Madrid's crest features a bear and a strawberry tree.",
  "as-roma": "AS Roma's crest features the she-wolf of Roman legend.",
  "ajax": "Ajax's badge shows the Greek hero Ajax in profile.",
  "boca-juniors": "Boca Juniors play in the famous La Bombonera stadium.",

  "river-plate": "River Plate are nicknamed 'Los Millonarios' (The Millionaires).",
  "napoli": "Napoli won their first Serie A title with Diego Maradona.",
  "newcastle-united": "Newcastle United play at St James' Park.",
  "west-ham-united": "West Ham United are nicknamed 'The Hammers'.",
  "everton": "Everton are nicknamed 'The Toffees'.",
  "leicester-city": "Leicester City won the Premier League as 5000-1 outsiders in 2016.",
  "sevilla": "Sevilla have won the UEFA Europa League a record number of times.",
  "valencia": "Valencia's stadium is nicknamed 'Mestalla'.",
  "porto": "FC Porto's crest bears the motto 'Invicta' (unconquered).",
  "benfica": "Benfica's crest features an eagle above a shield.",
  "marseille": "Marseille won the Champions League in 1993, France's first title.",
  "lyon": "Lyon won seven straight Ligue 1 titles in the 2000s.",
  "bayer-leverkusen": "Bayer Leverkusen were founded by employees of a chemical company.",
  "flamengo": "Flamengo is one of the most-supported clubs in Brazil.",
  "fenerbahce": "Fenerbahce's crest features a yellow band and green leaves.",
  "galatasaray": "Galatasaray are nicknamed 'The Lions' by their fans.",
  "celtic": "Celtic were founded to raise money for Glasgow's poor.",
  "schalke-04": "Schalke 04 is based in the German city of Gelsenkirchen.",

  "sporting-cp": "Sporting CP's crest features a rampant lion.",
  "rb-leipzig": "RB Leipzig was founded in 2009 and rose rapidly through the leagues.",
  "villarreal": "Villarreal are nicknamed 'The Yellow Submarine'.",
  "athletic-bilbao": "Athletic Bilbao field only Basque-born or trained players.",
  "real-sociedad": "Real Sociedad once had a Basque-only policy like Athletic Bilbao.",
  "monaco": "AS Monaco is based in the tiny principality of Monaco.",
  "lille": "Lille won the French league and cup double in 2011.",
  "wolfsburg": "Wolfsburg was founded by workers of the Volkswagen car factory.",
  "werder-bremen": "Werder Bremen's crest features a stylized letter W.",
  "feyenoord": "Feyenoord's stadium is nicknamed 'De Kuip' (The Tub).",
  "psv-eindhoven": "PSV Eindhoven was founded by workers of the Philips company.",
  "rangers": "Rangers' crest features a rampant lion of Scotland.",
  "palmeiras": "Palmeiras was founded by Italian immigrants in Sao Paulo.",
  "corinthians": "Corinthians' crest features an anchor and crossed oars.",
  "santos": "Pele played almost his entire career for Santos FC.",
  "al-ahly": "Al Ahly is Egypt's oldest football club, founded in 1907.",
  "club-america": "Club America's crest shows a map of the Americas.",
  "al-hilal": "Al Hilal is one of Saudi Arabia's most decorated clubs.",

  "anderlecht": "Anderlecht is Belgium's most decorated football club.",
  "club-brugge": "Club Brugge play their home matches in Bruges, Belgium.",
  "red-bull-salzburg": "Red Bull Salzburg is owned by the energy drink company.",
  "dynamo-kyiv": "Dynamo Kyiv's crest displays three championship stars.",
  "shakhtar-donetsk": "Shakhtar Donetsk are nicknamed 'The Miners'.",
  "olympiacos": "Olympiacos are based in the port city of Piraeus, Greece.",
  "panathinaikos": "Panathinaikos's crest features a shamrock (clover) emblem.",
  "aik": "AIK is one of Stockholm's oldest sports clubs, founded in 1891.",
  "malmo-ff": "Malmo FF has won more Swedish league titles than any other club.",
  "rosenborg": "Rosenborg won 13 straight Norwegian league titles.",
  "legia-warsaw": "Legia Warsaw is the most decorated club in Polish football.",
  "slavia-prague": "Slavia Prague's crest features a red star on white.",
  "sparta-prague": "Sparta Prague is one of the Czech Republic's oldest clubs.",
  "ferencvaros": "Ferencvaros is Hungary's most decorated football club.",
  "dinamo-zagreb": "Dinamo Zagreb's crest features Croatia's checkered pattern.",
  "universidad-de-chile": "Universidad de Chile's crest features an owl called the 'chuncho'.",
  "fc-copenhagen": "FC Copenhagen formed in 1992 from a merger of two clubs.",
};
