export const COFFEE_TEA_E100_FACTS = {
  // EASY
  espresso: "Espresso means 'pressed out' in Italian, describing how hot water is forced through fine grounds under intense pressure.",
  cappuccino: "Cappuccino is named after Capuchin friars, whose brown robes and pointed hoods reminded people of its ring of milk foam.",
  "caffe-latte": "Order just 'a latte' in Italy and you'll get a glass of milk — 'latte' means milk, so cafés there call this drink 'caffè latte.'",
  americano: "One popular story says the Americano was born when WWII GIs in Italy diluted strong espresso with hot water to taste like home.",
  "iced-coffee": "Iced coffee may trace back to 1840s Algeria, where French soldiers cooled their coffee with ice in a drink called 'mazagran.'",
  "caffe-mocha": "Caffè mocha takes its name from Mocha, Yemen, a Red Sea port that was once the world's main hub for the coffee trade.",
  frappuccino: "The Frappuccino wasn't invented by Starbucks — a Boston coffee chain trademarked it first, and Starbucks later bought the name.",
  "espresso-macchiato": "Macchiato means 'stained' in Italian, referring to the single dollop of foamed milk that lightly 'stains' the dark espresso.",
  "cold-brew-coffee": "Cold brew steeps in cold water for up to 24 hours and never touches heat, which makes the result naturally less acidic.",
  "black-tea": "Black, green, white, and oolong tea all come from the exact same plant — only how the leaves are processed sets them apart.",
  "green-tea": "Green tea leaves are heated right after picking to stop oxidation entirely, which is what keeps them green instead of dark.",
  "iced-tea": "Sweet tea became a Southern US staple partly because ice was scarce and expensive until railroads made large-scale ice shipping possible.",
  "bubble-tea": "Bubble tea's chewy tapioca pearls were reportedly dreamed up in 1980s Taiwan when a vendor dropped tapioca balls into iced tea.",
  "matcha-latte": "Matcha is made by grinding shade-grown tea leaves into a fine powder, so unlike steeped tea, you actually drink the whole leaf.",
  "chamomile-tea": "Chamomile tea isn't brewed from tea leaves at all — it's an herbal infusion made from the plant's small, daisy-like flowers.",
  "earl-grey-tea": "Earl Grey is simply black tea flavored with oil from the bergamot orange, a citrus fruit grown mainly in southern Italy.",
  "thai-iced-tea": "Thai iced tea's bright orange color usually comes from food coloring added to spiced black tea, before it's poured over milk.",
  kombucha: "Kombucha is fermented using a SCOBY, a rubbery mat of bacteria and yeast that looks a bit like a pancake floating in the jar.",

  // MEDIUM
  cortado: "Cortado means 'cut' in Spanish, describing how a small splash of milk 'cuts' the espresso's sharpness without masking it.",
  "flat-white": "The flat white emerged from Australia and New Zealand in the 1980s, and baristas from both countries still argue over who invented it.",
  "turkish-coffee": "Turkish coffee is boiled, not brewed, in a small pot called a cezve, and served unfiltered with the grounds left right in the cup.",
  affogato: "Affogato means 'drowned' in Italian — a hot shot of espresso is poured directly over a scoop of vanilla gelato or ice cream.",
  "latte-macchiato": "A latte macchiato is built backwards from a regular latte: the steamed milk goes into the glass first, then espresso on top.",
  "greek-frappe": "The Greek frappé was invented by accident in 1957 when a Nescafé rep at a trade fair had no hot water and shook instant coffee with ice.",
  "irish-coffee": "Irish coffee was created in the 1940s at a flying-boat terminal in County Limerick to warm up cold, weary transatlantic passengers.",
  "cafe-au-lait": "Café au lait is just strong brewed coffee mixed with hot milk in roughly equal parts, traditionally served in France in a wide bowl.",
  "pumpkin-spice-latte": "Starbucks' original 2003 pumpkin spice latte recipe famously contained no actual pumpkin until the formula changed in 2015.",
  "moroccan-mint-tea": "Moroccan mint tea is poured from high above the glass on purpose — the height whips up a light foam considered a mark of skill.",
  "turkish-tea": "Turkey drinks more tea per person than any other country on Earth, brewed in a stacked double teapot called a çaydanlık.",
  "oolong-tea": "Oolong tea sits between green and black tea in processing, partially oxidized anywhere from about 8% up to 80%.",
  "peppermint-tea": "Peppermint tea isn't a true tea at all — it's a caffeine-free herbal infusion made purely from dried or fresh peppermint leaves.",
  "jasmine-tea": "Jasmine tea gets its scent by layering fresh jasmine blossoms with tea leaves overnight so the leaves soak up the flowers' fragrance.",
  "hibiscus-tea": "Hibiscus tea's deep red color and tart, cranberry-like flavor come from the dried calyces of the roselle flower, not its petals.",
  "rooibos-tea": "Rooibos isn't a true tea at all — it's a South African red bush that's naturally caffeine-free and turns reddish only after fermenting.",
  "white-tea": "White tea is the least processed of all true teas, picked as young leaf buds still covered in fine silvery-white hairs.",
  "london-fog": "The London Fog wasn't invented in Britain — a 1990s Vancouver café created it after a pregnant customer asked for Earl Grey with steamed milk.",

  // HARD
  doppio: "A doppio is simply a double shot of espresso, pulled through a larger portafilter basket with twice the usual ground coffee.",
  ristretto: "Ristretto means 'restricted' in Italian — the same amount of coffee is pulled with less water, making it shorter and more intense.",
  "cafe-cubano": "Café Cubano is sweetened by whipping the very first drops of espresso with sugar into a foamy paste before the rest is added.",
  "vietnamese-iced-coffee": "Vietnamese iced coffee brews drop by drop through a small metal filter called a phin, straight into sweetened condensed milk.",
  "kapeng-barako": "Kapeng barako means 'stud coffee' in Filipino, named for its bold, intense flavor from a rare bean species called Liberica.",
  "caffe-corretto": "Caffè corretto means 'corrected coffee' in Italian — an espresso 'corrected' with a splash of liquor, usually grappa or sambuca.",
  "caffe-shakerato": "Caffè shakerato is made by shaking hot espresso with ice and sugar in a cocktail shaker until it turns cold and frothy.",
  "masala-chai": "Masala chai simply means 'spiced tea' in Hindi — the exact mix of ginger, cardamom, cinnamon, and cloves varies by household.",
  "yerba-mate": "Yerba mate is traditionally sipped through a metal straw called a bombilla from a hollowed gourd, often shared in a circle of friends.",
  genmaicha: "Genmaicha blends green tea with roasted, popped brown rice, a combination once used in Japan to stretch costly tea leaves further.",
  hojicha: "Hōjicha is made by roasting green tea leaves over high heat, which turns them reddish-brown and strips out most of the caffeine.",
  "puer-tea": "Pu'er tea is deliberately aged and fermented, sometimes for decades, and is often pressed into hard discs called 'cakes' for storage.",
  "kashmiri-kahwa": "Kashmiri kahwa is brewed in a copper samovar with saffron, cinnamon, and cardamom, then topped with crushed almonds or walnuts.",
  "chrysanthemum-tea": "Chrysanthemum tea has been made in China since at least the Song dynasty, brewed from dried flower heads instead of any tea leaf.",
  "darjeeling-tea": "Darjeeling tea grows only in a small strip of the Indian Himalayas and is sometimes nicknamed the 'champagne of teas.'",
  "gunpowder-tea": "Gunpowder tea gets its name from leaves rolled tightly into small pellets, said to resemble grains of old-fashioned gunpowder.",

  // IMPOSSIBLE
  einspanner: "The Einspänner is said to be named for Vienna's one-horse carriage drivers, who topped their coffee with cream to keep it warm.",
  "cafe-de-olla": "Café de olla is simmered with cinnamon and raw cane sugar in a clay pot, said to have first fueled troops in the Mexican Revolution.",
  "kopi-joss": "Kopi joss is served with a chunk of burning charcoal dropped straight into the cup, named for the sizzling sound it makes.",
  "kopi-tubruk": "Kopi tubruk is made by simply pouring hot water over coarse grounds with no filter, letting them settle at the bottom of the glass.",
  yuenyeung: "Yuenyeung blends coffee with Hong Kong-style milk tea, named after mandarin ducks, a Chinese symbol of a loving, inseparable pair.",
  "vietnamese-egg-coffee": "Vietnamese egg coffee was invented in 1946 Hanoi when a bartender whipped egg yolks and condensed milk into foam during a milk shortage.",
  "cafe-touba": "Café Touba is roasted with Guinea pepper and named for the Senegalese city where the founder of the Mouride Sufi order is buried.",
  "indian-filter-coffee": "Indian filter coffee is traditionally poured back and forth between cup and tumbler from a height, cooling it into a frothy top.",
  "ipoh-white-coffee": "Ipoh white coffee gets its pale color from beans roasted in margarine instead of sugar, a method born in a Malaysian mining town.",
  "nanyang-coffee": "Traditional Nanyang-style kopi is roasted with sugar and sometimes margarine, giving old-school Southeast Asian coffee shops their aroma.",
  "butter-tea": "Tibetan butter tea is churned with salt and yak butter instead of sugar, prized in the Himalayas for its warming, high-calorie punch.",
  "suutei-tsai": "Suutei tsai is a salty Mongolian milk tea sometimes made with fried millet stirred in, poured from a height to aerate it.",
  "teh-tarik": "Teh tarik means 'pulled tea' in Malay, named for the dramatic back-and-forth pouring between cups that gives it a frothy head.",
  "hong-kong-milk-tea": "Hong Kong-style milk tea is traditionally strained through a cloth bag so fine it's nicknamed 'silk stocking' milk tea.",
  "yuja-tea": "Yuja tea isn't brewed from any leaf — it's just hot water stirred into a thick citron-and-honey marmalade called yuja-cheong.",
  "ceremonial-matcha": "In the traditional Japanese tea ceremony, matcha powder is whisked, not steeped, with a bamboo whisk called a chasen until frothy.",
  "noon-chai": "Noon chai gets its pink color from green tea leaves boiled for hours with baking soda, then finished with milk and a pinch of salt.",
  "ginger-tea": "The Filipino ginger tea called salabat is a traditional cold-and-cough remedy, and folk belief says it also improves your singing voice.",
};
