export const COFFEE_TEA_E100 = [
  // ===== EASY (18) =====
  { slug: "espresso", name: "Espresso", level: "easy", wiki: "Espresso" },
  { slug: "cappuccino", name: "Cappuccino", level: "easy", wiki: "Cappuccino" },
  { slug: "caffe-latte", name: "Caffè Latte", level: "easy", wiki: "Latte" },
  { slug: "americano", name: "Americano", level: "easy", wiki: "Caffè americano" },
  { slug: "iced-coffee", name: "Iced Coffee", level: "easy", wiki: "Iced coffee" },
  { slug: "caffe-mocha", name: "Caffè Mocha", level: "easy", wiki: "Caffè mocha" },
  { slug: "frappuccino", name: "Frappuccino", level: "easy", wiki: "Frappuccino" },
  { slug: "espresso-macchiato", name: "Espresso Macchiato", level: "easy", wiki: "Caffè macchiato" },
  { slug: "cold-brew-coffee", name: "Cold Brew Coffee", level: "easy", wiki: "Cold brew coffee" },
  { slug: "black-tea", name: "Black Tea", level: "easy", wiki: "Black tea" },
  { slug: "green-tea", name: "Green Tea", level: "easy", wiki: "Green tea" },
  { slug: "iced-tea", name: "Iced Tea", level: "easy", wiki: "Iced tea" },
  { slug: "bubble-tea", name: "Bubble Tea", level: "easy", wiki: "Bubble tea" },
  { slug: "matcha-latte", name: "Matcha Latte", level: "easy", wiki: "Matcha latte" },
  { slug: "chamomile-tea", name: "Chamomile Tea", level: "easy", wiki: "Chamomile tea" },
  { slug: "earl-grey-tea", name: "Earl Grey Tea", level: "easy", wiki: "Earl Grey tea" },
  { slug: "thai-iced-tea", name: "Thai Iced Tea", level: "easy", wiki: "Thai tea" },
  { slug: "kombucha", name: "Kombucha", level: "easy", wiki: "Kombucha" },

  // ===== MEDIUM (18) =====
  { slug: "cortado", name: "Cortado", level: "medium", wiki: "Cortado" },
  { slug: "flat-white", name: "Flat White", level: "medium", wiki: "Flat white" },
  { slug: "turkish-coffee", name: "Turkish Coffee", level: "medium", wiki: "Turkish coffee" },
  { slug: "affogato", name: "Affogato", level: "medium", wiki: "Affogato" },
  { slug: "latte-macchiato", name: "Latte Macchiato", level: "medium", wiki: "Latte macchiato" },
  { slug: "greek-frappe", name: "Greek Frappé", level: "medium", wiki: "Frappé coffee" },
  { slug: "irish-coffee", name: "Irish Coffee", level: "medium", wiki: "Irish coffee" },
  { slug: "cafe-au-lait", name: "Café au Lait", level: "medium", wiki: "Café au lait" },
  { slug: "pumpkin-spice-latte", name: "Pumpkin Spice Latte", level: "medium", wiki: "Pumpkin spice latte" },
  { slug: "moroccan-mint-tea", name: "Moroccan Mint Tea", level: "medium", wiki: "Maghrebi mint tea" },
  { slug: "turkish-tea", name: "Turkish Tea", level: "medium", wiki: "Tea in Turkey" },
  { slug: "oolong-tea", name: "Oolong Tea", level: "medium", wiki: "Oolong" },
  { slug: "peppermint-tea", name: "Peppermint Tea", level: "medium", wiki: "Mint tea (herbal tea)" },
  { slug: "jasmine-tea", name: "Jasmine Tea", level: "medium", wiki: "Jasmine tea" },
  { slug: "hibiscus-tea", name: "Hibiscus Tea", level: "medium", wiki: "Hibiscus tea" },
  { slug: "rooibos-tea", name: "Rooibos Tea", level: "medium", wiki: "Rooibos" },
  { slug: "white-tea", name: "White Tea", level: "medium", wiki: "White tea" },
  { slug: "london-fog", name: "London Fog", level: "medium", wiki: "London fog (drink)" },

  // ===== HARD (16) =====
  { slug: "doppio", name: "Doppio", level: "hard", wiki: "Doppio" },
  { slug: "ristretto", name: "Ristretto", level: "hard", wiki: "Ristretto" },
  { slug: "cafe-cubano", name: "Café Cubano", level: "hard", wiki: "Cuban espresso" },
  { slug: "vietnamese-iced-coffee", name: "Vietnamese Iced Coffee", level: "hard", wiki: "Vietnamese iced coffee" },
  { slug: "kapeng-barako", name: "Kapeng Barako", level: "hard", wiki: "Kapeng barako" },
  { slug: "caffe-corretto", name: "Caffè Corretto", level: "hard", wiki: "Caffè corretto" },
  { slug: "caffe-shakerato", name: "Caffè Shakerato", level: "hard", wiki: "Caffè shakerato" },
  { slug: "masala-chai", name: "Masala Chai", level: "hard", wiki: "Masala chai" },
  { slug: "yerba-mate", name: "Yerba Mate", level: "hard", wiki: "Mate (drink)" },
  { slug: "genmaicha", name: "Genmaicha", level: "hard", wiki: "Genmaicha" },
  { slug: "hojicha", name: "Hōjicha", level: "hard", wiki: "Hōjicha" },
  { slug: "puer-tea", name: "Pu'er Tea", level: "hard", wiki: "Pu'er tea" },
  { slug: "kashmiri-kahwa", name: "Kashmiri Kahwa", level: "hard", wiki: "Kahwah" },
  { slug: "chrysanthemum-tea", name: "Chrysanthemum Tea", level: "hard", wiki: "Chrysanthemum tea" },
  { slug: "darjeeling-tea", name: "Darjeeling Tea", level: "hard", wiki: "Darjeeling tea" },
  { slug: "gunpowder-tea", name: "Gunpowder Tea", level: "hard", wiki: "Gunpowder tea" },

  // ===== IMPOSSIBLE (18) =====
  { slug: "einspanner", name: "Einspänner", level: "impossible", wiki: "Einspänner" },
  { slug: "cafe-de-olla", name: "Café de Olla", level: "impossible", wiki: "Café de olla" },
  { slug: "kopi-joss", name: "Kopi Joss", level: "impossible", wiki: "Kopi joss" },
  { slug: "kopi-tubruk", name: "Kopi Tubruk", level: "impossible", wiki: "Kopi tubruk" },
  { slug: "yuenyeung", name: "Yuenyeung", level: "impossible", wiki: "Yuenyeung" },
  { slug: "vietnamese-egg-coffee", name: "Vietnamese Egg Coffee", level: "impossible", wiki: "Egg coffee" },
  { slug: "cafe-touba", name: "Café Touba", level: "impossible", wiki: "Café Touba" },
  { slug: "indian-filter-coffee", name: "Indian Filter Coffee", level: "impossible", wiki: "Indian filter coffee" },
  { slug: "ipoh-white-coffee", name: "Ipoh White Coffee", level: "impossible", wiki: "Ipoh white coffee" },
  { slug: "nanyang-coffee", name: "Nanyang Coffee", level: "impossible", wiki: "Kopi (drink)" },
  { slug: "butter-tea", name: "Butter Tea", level: "impossible", wiki: "Butter tea" },
  { slug: "suutei-tsai", name: "Suutei Tsai", level: "impossible", wiki: "Suutei tsai" },
  { slug: "teh-tarik", name: "Teh Tarik", level: "impossible", wiki: "Teh tarik" },
  { slug: "hong-kong-milk-tea", name: "Hong Kong-Style Milk Tea", level: "impossible", wiki: "Hong Kong–style milk tea" },
  { slug: "yuja-tea", name: "Yuja Tea", level: "impossible", wiki: "Yuja tea" },
  { slug: "ceremonial-matcha", name: "Ceremonial Matcha", level: "impossible", wiki: "Matcha" },
  { slug: "noon-chai", name: "Noon Chai", level: "impossible", wiki: "Noon chai" },
  { slug: "ginger-tea", name: "Ginger Tea", level: "impossible", wiki: "Ginger tea" },
];
