export const CONSTELLATIONS_E86_FACTS = {
  orion: "Its three-star belt is one of the sky's most recognized patterns.",
  "ursa-major": "The Big Dipper is just part of this larger constellation.",
  "ursa-minor": "Polaris, the North Star, sits at the tip of its tail.",
  cassiopeia: "Its stars form a distinctive W or M shape.",
  leo: "One of the few constellations that actually looks like its name.",
  scorpius: "Its curved tail ends in a stinger of two bright stars.",
  taurus: "Marked by the bright red giant star Aldebaran, its 'eye.'",
  gemini: "Named for its two brightest stars, Castor and Pollux.",
  cancer: "One of the dimmest constellations in the zodiac.",
  virgo: "Home to Spica, one of the brightest stars in the sky.",
  libra: "The only zodiac constellation representing an object.",
  aries: "Its stars are fairly faint next to other zodiac signs.",
  sagittarius: "Its 'teapot' shape points toward the galaxy's center.",
  capricornus: "One of the faintest constellations in the zodiac.",
  aquarius: "Depicts a figure pouring water from a jar.",
  pisces: "Its two fish are tied together by a long cosmic cord.",
  draco: "Winds around Ursa Minor and never sets for northern viewers.",
  "canis-major": "Home to Sirius, the brightest star in the night sky.",
  andromeda: "Named after a mythical princess, not the galaxy within it.",
  perseus: "Home to the Perseid meteor shower's radiant point.",
  pegasus: "Its Great Square is one of the sky's easiest shapes to spot.",
  cygnus: "Also called the Northern Cross for its shape.",
  lyra: "Home to Vega, one of the brightest stars in the sky.",
  aquila: "Its name means 'eagle' in Latin.",
  hercules: "Contains M13, one of the brightest globular clusters.",
  centaurus: "Home to Alpha Centauri, our closest neighboring star system.",
  crux: "Known as the Southern Cross, it's on several national flags.",
  "corona-borealis": "Its curved shape represents a jeweled crown.",
  cepheus: "Named for a mythical king, husband of Cassiopeia.",
  auriga: "Its name means 'charioteer' in Latin.",
  bootes: "Its name means 'the herdsman' or 'ox driver.'",
  "canis-minor": "Represents the smaller of Orion's two hunting dogs.",
  hydra: "The largest of all 88 official constellations.",
  lepus: "Represents a hare, sitting just below Orion's feet.",
  sagitta: "One of the smallest constellations, shaped like an arrow.",
  delphinus: "A small but distinct pattern representing a dolphin.",
  ophiuchus: "Sometimes called the 13th zodiac sign, though rarely used.",
  cetus: "Represents a sea monster in Greek mythology.",
  eridanus: "One of the longest constellations, representing a river.",
  lynx: "Named for stars faint enough to need sharp eyes to see.",
  camelopardalis: "Its name literally means 'giraffe.'",
  lacerta: "A small, faint constellation representing a lizard.",
  vulpecula: "Its name means 'little fox' in Latin.",
  serpens: "The only constellation officially split into two parts.",
  corvus: "Represents a crow sent by Apollo in Greek myth.",
  crater: "Represents a cup, sitting beside the constellation Corvus.",
  sculptor: "Depicts a sculptor's studio, with a chisel and carved head.",
  fornax: "Represents a furnace, named in the 18th century.",
  pyxis: "Represents a mariner's compass, added in the 1750s.",
  antlia: "Represents an air pump, one of the newer constellations.",
  columba: "Represents a dove, tied to the biblical story of Noah.",
  monoceros: "Represents a unicorn, despite having no bright stars.",
  mensa: "The only constellation named after a real place, Table Mountain.",
  norma: "Represents a carpenter's square or level.",
  reticulum: "Its name means 'the net,' after a survey instrument.",
  caelum: "One of the faintest constellations, named for an engraving tool.",
  circinus: "Represents a drafting compass used for drawing circles.",
  telescopium: "Named to honor the invention of the telescope.",
  microscopium: "Named to honor the invention of the microscope.",
  pictor: "Originally named for a painter's easel.",
  volans: "Represents a flying fish, found in the southern sky.",
  dorado: "Represents a dolphinfish, also called mahi-mahi.",
  chamaeleon: "A small southern constellation representing a chameleon.",
  musca: "Represents a fly, one of the smallest constellations.",
  apus: "Represents a bird-of-paradise, named for the exotic bird.",
  octans: "Contains the south celestial pole, like Polaris up north.",
  indus: "Represents an indigenous person, from 16th-century exploration.",
  horologium: "Represents a pendulum clock, a genuinely faint constellation.",
  sextans: "Represents an astronomer's sextant for measuring angles.",
  tucana: "Represents a toucan, home to a bright globular cluster.",
};

export default CONSTELLATIONS_E86_FACTS;
