export const CONSTELLATIONS_E86 = [
  // EASY (18) — near-universal, ~70-95% global recognition
  { slug: "orion", name: "Orion", wiki: "Orion (constellation)", level: "easy" },
  { slug: "ursa-major", name: "Ursa Major", wiki: "Ursa Major", level: "easy" },
  { slug: "ursa-minor", name: "Ursa Minor", wiki: "Ursa Minor", level: "easy" },
  { slug: "cassiopeia", name: "Cassiopeia", wiki: "Cassiopeia (constellation)", level: "easy" },
  { slug: "leo", name: "Leo", wiki: "Leo (constellation)", level: "easy" },
  { slug: "scorpius", name: "Scorpius", wiki: "Scorpius", level: "easy" },
  { slug: "taurus", name: "Taurus", wiki: "Taurus (constellation)", level: "easy" },
  { slug: "gemini", name: "Gemini", wiki: "Gemini (constellation)", level: "easy" },
  { slug: "cancer", name: "Cancer", wiki: "Cancer (constellation)", level: "easy" },
  { slug: "virgo", name: "Virgo", wiki: "Virgo (constellation)", level: "easy" },
  { slug: "libra", name: "Libra", wiki: "Libra (constellation)", level: "easy" },
  { slug: "aries", name: "Aries", wiki: "Aries (constellation)", level: "easy" },
  { slug: "sagittarius", name: "Sagittarius", wiki: "Sagittarius (constellation)", level: "easy" },
  { slug: "capricornus", name: "Capricornus", wiki: "Capricornus", level: "easy" },
  { slug: "aquarius", name: "Aquarius", wiki: "Aquarius (constellation)", level: "easy" },
  { slug: "pisces", name: "Pisces", wiki: "Pisces (constellation)", level: "easy" },
  { slug: "draco", name: "Draco", wiki: "Draco (constellation)", level: "easy" },
  { slug: "canis-major", name: "Canis Major", wiki: "Canis Major", level: "easy" },

  // MEDIUM (18) — most have seen it, ~35-70%
  { slug: "andromeda", name: "Andromeda", wiki: "Andromeda (constellation)", level: "medium" },
  { slug: "perseus", name: "Perseus", wiki: "Perseus (constellation)", level: "medium" },
  { slug: "pegasus", name: "Pegasus", wiki: "Pegasus (constellation)", level: "medium" },
  { slug: "cygnus", name: "Cygnus", wiki: "Cygnus (constellation)", level: "medium" },
  { slug: "lyra", name: "Lyra", wiki: "Lyra", level: "medium" },
  { slug: "aquila", name: "Aquila", wiki: "Aquila (constellation)", level: "medium" },
  { slug: "hercules", name: "Hercules", wiki: "Hercules (constellation)", level: "medium" },
  { slug: "centaurus", name: "Centaurus", wiki: "Centaurus", level: "medium" },
  { slug: "crux", name: "Crux", wiki: "Crux", level: "medium" },
  { slug: "corona-borealis", name: "Corona Borealis", wiki: "Corona Borealis", level: "medium" },
  { slug: "cepheus", name: "Cepheus", wiki: "Cepheus (constellation)", level: "medium" },
  { slug: "auriga", name: "Auriga", wiki: "Auriga (constellation)", level: "medium" },
  { slug: "bootes", name: "Boötes", wiki: "Boötes", level: "medium" },
  { slug: "canis-minor", name: "Canis Minor", wiki: "Canis Minor", level: "medium" },
  { slug: "hydra", name: "Hydra", wiki: "Hydra (constellation)", level: "medium" },
  { slug: "lepus", name: "Lepus", wiki: "Lepus (constellation)", level: "medium" },
  { slug: "sagitta", name: "Sagitta", wiki: "Sagitta", level: "medium" },
  { slug: "delphinus", name: "Delphinus", wiki: "Delphinus", level: "medium" },

  // HARD (16) — enthusiasts/well-read recognize
  { slug: "ophiuchus", name: "Ophiuchus", wiki: "Ophiuchus", level: "hard" },
  { slug: "cetus", name: "Cetus", wiki: "Cetus", level: "hard" },
  { slug: "eridanus", name: "Eridanus", wiki: "Eridanus (constellation)", level: "hard" },
  { slug: "lynx", name: "Lynx", wiki: "Lynx (constellation)", level: "hard" },
  { slug: "camelopardalis", name: "Camelopardalis", wiki: "Camelopardalis", level: "hard" },
  { slug: "lacerta", name: "Lacerta", wiki: "Lacerta", level: "hard" },
  { slug: "vulpecula", name: "Vulpecula", wiki: "Vulpecula", level: "hard" },
  { slug: "serpens", name: "Serpens", wiki: "Serpens", level: "hard" },
  { slug: "corvus", name: "Corvus", wiki: "Corvus (constellation)", level: "hard" },
  { slug: "crater", name: "Crater", wiki: "Crater (constellation)", level: "hard" },
  { slug: "sculptor", name: "Sculptor", wiki: "Sculptor (constellation)", level: "hard" },
  { slug: "fornax", name: "Fornax", wiki: "Fornax", level: "hard" },
  { slug: "pyxis", name: "Pyxis", wiki: "Pyxis", level: "hard" },
  { slug: "antlia", name: "Antlia", wiki: "Antlia", level: "hard" },
  { slug: "columba", name: "Columba", wiki: "Columba (constellation)", level: "hard" },
  { slug: "monoceros", name: "Monoceros", wiki: "Monoceros", level: "hard" },

  // IMPOSSIBLE (18) — genuinely obscure, mostly modern southern-sky constellations
  { slug: "mensa", name: "Mensa", wiki: "Mensa (constellation)", level: "impossible" },
  { slug: "norma", name: "Norma", wiki: "Norma (constellation)", level: "impossible" },
  { slug: "reticulum", name: "Reticulum", wiki: "Reticulum", level: "impossible" },
  { slug: "caelum", name: "Caelum", wiki: "Caelum", level: "impossible" },
  { slug: "circinus", name: "Circinus", wiki: "Circinus (constellation)", level: "impossible" },
  { slug: "telescopium", name: "Telescopium", wiki: "Telescopium", level: "impossible" },
  { slug: "microscopium", name: "Microscopium", wiki: "Microscopium", level: "impossible" },
  { slug: "pictor", name: "Pictor", wiki: "Pictor", level: "impossible" },
  { slug: "volans", name: "Volans", wiki: "Volans", level: "impossible" },
  { slug: "dorado", name: "Dorado", wiki: "Dorado", level: "impossible" },
  { slug: "chamaeleon", name: "Chamaeleon", wiki: "Chamaeleon (constellation)", level: "impossible" },
  { slug: "musca", name: "Musca", wiki: "Musca", level: "impossible" },
  { slug: "apus", name: "Apus", wiki: "Apus", level: "impossible" },
  { slug: "octans", name: "Octans", wiki: "Octans", level: "impossible" },
  { slug: "indus", name: "Indus", wiki: "Indus (constellation)", level: "impossible" },
  { slug: "horologium", name: "Horologium", wiki: "Horologium", level: "impossible" },
  { slug: "sextans", name: "Sextans", wiki: "Sextans", level: "impossible" },
  { slug: "tucana", name: "Tucana", wiki: "Tucana", level: "impossible" },
];

export default CONSTELLATIONS_E86;
