// Episode 6 "Guess the Country by Shape" — 100 items, absolute-difficulty calibrated.
// Images: mapsicon (github.com/djaiss/mapsicon) black country-outline SVGs, free with attribution.
export const COUNTRY_SHAPES_E06 = [
  // EASY (25)
  { iso: "it", name: "Italy", level: "easy" },
  { iso: "us", name: "United States", level: "easy" },
  { iso: "gb", name: "United Kingdom", level: "easy" },
  { iso: "au", name: "Australia", level: "easy" },
  { iso: "jp", name: "Japan", level: "easy" },
  { iso: "in", name: "India", level: "easy" },
  { iso: "br", name: "Brazil", level: "easy" },
  { iso: "cl", name: "Chile", level: "easy" },
  { iso: "sa", name: "Saudi Arabia", level: "easy" },
  { iso: "za", name: "South Africa", level: "easy" },
  { iso: "nz", name: "New Zealand", level: "easy" },
  { iso: "eg", name: "Egypt", level: "easy" },
  { iso: "tr", name: "Turkey", level: "easy" },
  { iso: "no", name: "Norway", level: "easy" },
  { iso: "se", name: "Sweden", level: "easy" },
  { iso: "kr", name: "South Korea", level: "easy" },
  { iso: "cu", name: "Cuba", level: "easy" },
  { iso: "vn", name: "Vietnam", level: "easy" },
  { iso: "th", name: "Thailand", level: "easy" },
  { iso: "mx", name: "Mexico", level: "easy" },
  { iso: "ca", name: "Canada", level: "easy" },
  { iso: "ru", name: "Russia", level: "easy" },
  { iso: "cn", name: "China", level: "easy" },
  { iso: "fr", name: "France", level: "easy" },
  { iso: "es", name: "Spain", level: "easy" },
  // MEDIUM (25)
  { iso: "ar", name: "Argentina", level: "medium" },
  { iso: "is", name: "Iceland", level: "medium" },
  { iso: "ie", name: "Ireland", level: "medium" },
  { iso: "pt", name: "Portugal", level: "medium" },
  { iso: "gr", name: "Greece", level: "medium" },
  { iso: "id", name: "Indonesia", level: "medium" },
  { iso: "ph", name: "Philippines", level: "medium" },
  { iso: "mg", name: "Madagascar", level: "medium" },
  { iso: "lk", name: "Sri Lanka", level: "medium" },
  { iso: "np", name: "Nepal", level: "medium" },
  { iso: "ir", name: "Iran", level: "medium" },
  { iso: "iq", name: "Iraq", level: "medium" },
  { iso: "pk", name: "Pakistan", level: "medium" },
  { iso: "co", name: "Colombia", level: "medium" },
  { iso: "pe", name: "Peru", level: "medium" },
  { iso: "ve", name: "Venezuela", level: "medium" },
  { iso: "fi", name: "Finland", level: "medium" },
  { iso: "dk", name: "Denmark", level: "medium" },
  { iso: "hr", name: "Croatia", level: "medium" },
  { iso: "ch", name: "Switzerland", level: "medium" },
  { iso: "de", name: "Germany", level: "medium" },
  { iso: "pl", name: "Poland", level: "medium" },
  { iso: "ua", name: "Ukraine", level: "medium" },
  { iso: "ma", name: "Morocco", level: "medium" },
  { iso: "kz", name: "Kazakhstan", level: "medium" },
  // HARD (25)
  { iso: "so", name: "Somalia", level: "hard" },
  { iso: "et", name: "Ethiopia", level: "hard" },
  { iso: "mn", name: "Mongolia", level: "hard" },
  { iso: "bd", name: "Bangladesh", level: "hard" },
  { iso: "mm", name: "Myanmar", level: "hard" },
  { iso: "bo", name: "Bolivia", level: "hard" },
  { iso: "py", name: "Paraguay", level: "hard" },
  { iso: "sd", name: "Sudan", level: "hard" },
  { iso: "ly", name: "Libya", level: "hard" },
  { iso: "uz", name: "Uzbekistan", level: "hard" },
  { iso: "kh", name: "Cambodia", level: "hard" },
  { iso: "la", name: "Laos", level: "hard" },
  { iso: "na", name: "Namibia", level: "hard" },
  { iso: "bw", name: "Botswana", level: "hard" },
  { iso: "gh", name: "Ghana", level: "hard" },
  { iso: "cd", name: "Democratic Republic of the Congo", level: "hard" },
  { iso: "ao", name: "Angola", level: "hard" },
  { iso: "mz", name: "Mozambique", level: "hard" },
  { iso: "tz", name: "Tanzania", level: "hard" },
  { iso: "ug", name: "Uganda", level: "hard" },
  { iso: "sn", name: "Senegal", level: "hard" },
  { iso: "ml", name: "Mali", level: "hard" },
  { iso: "ne", name: "Niger", level: "hard" },
  { iso: "td", name: "Chad", level: "hard" },
  { iso: "ng", name: "Nigeria", level: "hard" },
  // IMPOSSIBLE (25)
  { iso: "rw", name: "Rwanda", level: "impossible" },
  { iso: "mw", name: "Malawi", level: "impossible" },
  { iso: "ls", name: "Lesotho", level: "impossible" },
  { iso: "gm", name: "Gambia", level: "impossible" },
  { iso: "gw", name: "Guinea-Bissau", level: "impossible" },
  { iso: "dj", name: "Djibouti", level: "impossible" },
  { iso: "er", name: "Eritrea", level: "impossible" },
  { iso: "gq", name: "Equatorial Guinea", level: "impossible" },
  { iso: "tl", name: "Timor-Leste", level: "impossible" },
  { iso: "sr", name: "Suriname", level: "impossible" },
  { iso: "gy", name: "Guyana", level: "impossible" },
  { iso: "bz", name: "Belize", level: "impossible" },
  { iso: "tj", name: "Tajikistan", level: "impossible" },
  { iso: "kg", name: "Kyrgyzstan", level: "impossible" },
  { iso: "sb", name: "Solomon Islands", level: "impossible" },
  { iso: "vu", name: "Vanuatu", level: "impossible" },
  { iso: "cv", name: "Cabo Verde", level: "impossible" },
  { iso: "ss", name: "South Sudan", level: "impossible" },
  { iso: "md", name: "Moldova", level: "impossible" },
  { iso: "al", name: "Albania", level: "impossible" },
  { iso: "ba", name: "Bosnia and Herzegovina", level: "impossible" },
  { iso: "sk", name: "Slovakia", level: "impossible" },
  { iso: "si", name: "Slovenia", level: "impossible" },
  { iso: "bg", name: "Bulgaria", level: "impossible" },
  { iso: "cm", name: "Cameroon", level: "impossible" },
];
export default COUNTRY_SHAPES_E06;
