// Episode 6 "Guess the Country by Shape" — one verified ≤70-char fact per country, keyed by iso.
// Verified via 4 parallel research agents (WebSearch-sourced) + quiz-fact-verifier pass.
export const COUNTRY_SHAPES_E06_FACTS = {
  // EASY
  "it": "Italy fully surrounds two countries: Vatican City & San Marino.",
  "us": "Alaska is the US's northernmost, easternmost & westernmost state.",
  "gb": "Big Ben is actually the bell's name, not the tower's.",
  "au": "Australia is wider east-to-west than the Moon's diameter.",
  "jp": "A 2023 survey found Japan has 14,125 islands, not 6,852.",
  "in": "India's 2011 census logged 19,569 mother-tongue names.",
  "br": "Brazil borders every South American country except Chile & Ecuador.",
  "cl": "Chile stretches 4,300 km long but averages just 175 km wide.",
  "sa": "Saudi Arabia has no permanent rivers at all.",
  "za": "South Africa has 3 capitals: Pretoria, Cape Town, Bloemfontein.",
  "nz": "New Zealand let women vote in 1893 - a world first.",
  "eg": "About 95% of Egypt's land is desert.",
  "tr": "Istanbul is the only major city split across two continents.",
  "no": "Svalbard, Norway sees 125 straight days of midnight sun.",
  "se": "Sweden has over 267,000 islands, more than any country.",
  "kr": "Most Korean households own a dedicated kimchi fridge.",
  "cu": "Cuba's streets are full of 1950s US cars due to the embargo.",
  "vn": "Vietnam has been the top cashew exporter for 18 years straight.",
  "th": "Thailand is Southeast Asia's only never-colonized nation.",
  "mx": "Parts of Mexico City sink nearly a foot every year.",
  "ca": "Canada has more total lake area than any other country.",
  "ru": "Russia spans 11 time zones, all within one country.",
  "cn": "China uses just one time zone for its entire vast territory.",
  "fr": "France has 12 time zones - more than any other country.",
  "es": "Spain's Ceuta & Melilla give it a land border with Africa.",

  // MEDIUM
  "ar": "Argentina solved the world's first fingerprint murder case in 1892.",
  "is": "Iceland's parliament, founded in 930, is the world's oldest.",
  "ie": "The word 'boycott' comes from an 1880 Irish land dispute.",
  "pt": "Portugal and England signed the world's oldest active alliance.",
  "gr": "Greece's 9 flag stripes represent 'Freedom or Death'.",
  "id": "Female Komodo dragons can lay eggs without ever mating.",
  "ph": "A Filipino invented the first 16-bit microchip calculator.",
  "mg": "About 90% of Madagascar's species exist nowhere else on Earth.",
  "lk": "The word 'serendipity' comes from Sri Lanka's old name, Serendip.",
  "np": "Nepal's flag is the only national flag that isn't rectangular.",
  "ir": "Ancient Persia built the first empire-wide postal relay system.",
  "iq": "Ancient Iraq invented the 60-minute hour, 5,000 years ago.",
  "pk": "Mohenjo-daro in Pakistan had flush toilets 4,500 years ago.",
  "co": "Colombia has more bird species than any other country.",
  "pe": "Peru is home to over 4,000 varieties of potato.",
  "ve": "Angel Falls water often turns to mist before reaching ground.",
  "fi": "Finland publishes every citizen's income on 'National Jealousy Day.'",
  "dk": "LEGO bricks made in 1958 still fit ones made today.",
  "hr": "The necktie was invented by 17th-century Croatian soldiers.",
  "ch": "The World Wide Web was invented in Switzerland, not the US.",
  "de": "Germany invented the MP3 format used worldwide.",
  "pl": "Marie Curie named polonium after her homeland, Poland.",
  "ua": "Ukraine is the world's top exporter of sunflower oil.",
  "ma": "Morocco has the world's oldest university, founded in 859.",
  "kz": "Kazakhstan is home to Baikonur, the world's first spaceport.",

  // HARD
  "so": "Somalia has the longest coastline on mainland Africa.",
  "et": "Ethiopia's calendar is 7-8 years behind the Gregorian one.",
  "mn": "Mongolia is the least densely populated country on Earth.",
  "bd": "Bangladesh is home to the world's largest mangrove forest.",
  "mm": "Myanmar's Bagan holds over 2,200 ancient Buddhist temples.",
  "bo": "Bolivia has two capitals: Sucre and La Paz.",
  "py": "Landlocked Paraguay has the world's largest landlocked navy.",
  "sd": "Sudan has more pyramids than Egypt - over 200 of them.",
  "ly": "Libya holds Africa's largest proven oil reserves.",
  "uz": "Uzbekistan is one of only two 'double-landlocked' nations.",
  "kh": "Cambodia's Angkor Wat is the world's largest religious site.",
  "la": "Laos is the most heavily bombed country per capita ever.",
  "na": "Namibia's Namib is the world's oldest desert.",
  "bw": "Botswana has more elephants than any other country.",
  "gh": "Ghana's Lake Volta is the largest reservoir by area.",
  "cd": "The Congo River is the world's deepest river.",
  "ao": "Luanda, Angola was once the world's costliest city.",
  "mz": "Mozambique's flag is the only one bearing an AK-47.",
  "tz": "Tanzania has Africa's tallest peak and deepest lake.",
  "ug": "Uganda is home to over half the world's mountain gorillas.",
  "sn": "Senegal hosts the westernmost point of mainland Africa.",
  "ml": "Timbuktu, in Mali, was a major hub of Islamic scholarship.",
  "ne": "Niger has the highest fertility rate of any country.",
  "td": "Lake Chad has shrunk by about 90% since the 1960s.",
  "ng": "Nigeria's Nollywood outproduces Hollywood in films yearly.",

  // IMPOSSIBLE
  "rw": "Rwanda banned all plastic bags nationwide back in 2008.",
  "mw": "Lake Malawi holds more fish species than any lake on Earth.",
  "ls": "Lesotho is the only country entirely above 1,000 meters high.",
  "gm": "Gambia once merged with Senegal into a state called Senegambia.",
  "gw": "Cashews make up most of Guinea-Bissau's export economy.",
  "dj": "Djibouti's Lake Assal is Africa's lowest and saltiest point.",
  "er": "Asmara, Eritrea's capital, is a UNESCO Art Deco time capsule.",
  "gq": "It's Africa's only country with Spanish as an official language.",
  "tl": "Timor-Leste is one of Asia's only two Catholic-majority nations.",
  "sr": "Suriname is the most forested country on Earth: 93% jungle.",
  "gy": "Guyana is the only English-speaking country in South America.",
  "bz": "Belize is Central America's only English-speaking country.",
  "tj": "Tajikistan's Pamir Highway is the world's 2nd-highest highway.",
  "kg": "Kyrgyzstan's Lake Issyk-Kul never freezes, even in deep winter.",
  "sb": "The Solomon Islands are made up of nearly 1,000 islands.",
  "vu": "Vanuatu's ancient land-diving ritual inspired bungee jumping.",
  "cv": "Cabo Verde had zero native people before Portugal settled it.",
  "ss": "South Sudan is the world's youngest country, born in 2011.",
  "md": "Moldova hides the world's largest wine cellar: 1.5M+ bottles.",
  "al": "Albania once outlawed religion, declaring itself fully atheist.",
  "ba": "Sarajevo once hosted the Winter Olympics, back in 1984.",
  "sk": "Slovakia has more castles per person than any other country.",
  "si": "Slovenia is the only country with 'love' inside its name.",
  "bg": "In Bulgaria, nodding your head can actually mean 'no.'",
  "cm": "Cameroon is nicknamed 'Africa in miniature' for its climates.",
};
export default COUNTRY_SHAPES_E06_FACTS;
