// Episode 8 "Guess the Country by Food" — 71 items, absolute-difficulty calibrated.
// 18/18/18/17 split. Answer = country (not the dish name) — engine nameField is "country".
// Every dish-country attribution WebSearch-verified; contested/political origins screened out
// (no Israel; dropped hummus/falafel/shawarma/dolma/baklava-vs-Greece/Jollof-Wars-ambiguity/etc.,
// substituting uncontested dishes for the same region — see build notes).
// No country repeats within any single tier (MC distractors are drawn from the same tier).
export const COUNTRY_BY_FOOD_E08 = [
  // EASY (18)
  { slug: "sushi", dish: "Sushi", country: "Japan", level: "easy" },
  { slug: "pizza-margherita", dish: "Pizza Margherita", country: "Italy", level: "easy" },
  { slug: "tacos", dish: "Tacos", country: "Mexico", level: "easy" },
  { slug: "croissant", dish: "Croissant", country: "France", level: "easy" },
  { slug: "hamburger", dish: "Hamburger", country: "United States", level: "easy" },
  { slug: "butter-chicken", dish: "Butter Chicken", country: "India", level: "easy" },
  { slug: "peking-duck", dish: "Peking Duck", country: "China", level: "easy" },
  { slug: "pad-thai", dish: "Pad Thai", country: "Thailand", level: "easy" },
  { slug: "kimchi", dish: "Kimchi", country: "South Korea", level: "easy" },
  { slug: "bratwurst", dish: "Bratwurst", country: "Germany", level: "easy" },
  { slug: "paella", dish: "Paella", country: "Spain", level: "easy" },
  { slug: "pho", dish: "Pho", country: "Vietnam", level: "easy" },
  { slug: "cheese-fondue", dish: "Cheese Fondue", country: "Switzerland", level: "easy" },
  { slug: "moussaka", dish: "Moussaka", country: "Greece", level: "easy" },
  { slug: "pierogi", dish: "Pierogi", country: "Poland", level: "easy" },
  { slug: "goulash", dish: "Goulash", country: "Hungary", level: "easy" },
  { slug: "fish-and-chips", dish: "Fish and Chips", country: "United Kingdom", level: "easy" },
  { slug: "turkish-delight", dish: "Turkish Delight", country: "Turkey", level: "easy" },
  // MEDIUM (18)
  { slug: "chicken-tagine", dish: "Chicken Tagine", country: "Morocco", level: "medium" },
  { slug: "ghormeh-sabzi", dish: "Ghormeh Sabzi", country: "Iran", level: "medium" },
  { slug: "asado", dish: "Asado", country: "Argentina", level: "medium" },
  { slug: "feijoada", dish: "Feijoada", country: "Brazil", level: "medium" },
  { slug: "ceviche", dish: "Ceviche", country: "Peru", level: "medium" },
  { slug: "rendang", dish: "Rendang", country: "Indonesia", level: "medium" },
  { slug: "chicken-adobo", dish: "Chicken Adobo", country: "Philippines", level: "medium" },
  { slug: "borscht", dish: "Borscht", country: "Ukraine", level: "medium" },
  { slug: "pastel-de-nata", dish: "Pastel de Nata", country: "Portugal", level: "medium" },
  { slug: "belgian-waffles", dish: "Belgian Waffles", country: "Belgium", level: "medium" },
  { slug: "wiener-schnitzel", dish: "Wiener Schnitzel", country: "Austria", level: "medium" },
  { slug: "nasi-lemak", dish: "Nasi Lemak", country: "Malaysia", level: "medium" },
  { slug: "chili-crab", dish: "Chili Crab", country: "Singapore", level: "medium" },
  { slug: "kottu-roti", dish: "Kottu Roti", country: "Sri Lanka", level: "medium" },
  { slug: "koshari", dish: "Koshari", country: "Egypt", level: "medium" },
  { slug: "thieboudienne", dish: "Thieboudienne", country: "Senegal", level: "medium" },
  { slug: "bandeja-paisa", dish: "Bandeja Paisa", country: "Colombia", level: "medium" },
  { slug: "swedish-meatballs", dish: "Swedish Meatballs", country: "Sweden", level: "medium" },
  // HARD (18)
  { slug: "doro-wat", dish: "Doro Wat", country: "Ethiopia", level: "hard" },
  { slug: "egusi-soup", dish: "Egusi Soup", country: "Nigeria", level: "hard" },
  { slug: "plov", dish: "Plov", country: "Uzbekistan", level: "hard" },
  { slug: "khachapuri", dish: "Khachapuri", country: "Georgia", level: "hard" },
  { slug: "saltenas", dish: "Salteñas", country: "Bolivia", level: "hard" },
  { slug: "pastel-de-choclo", dish: "Pastel de Choclo", country: "Chile", level: "hard" },
  { slug: "ropa-vieja", dish: "Ropa Vieja", country: "Cuba", level: "hard" },
  { slug: "fish-amok", dish: "Fish Amok", country: "Cambodia", level: "hard" },
  { slug: "larb", dish: "Larb", country: "Laos", level: "hard" },
  { slug: "mohinga", dish: "Mohinga", country: "Myanmar", level: "hard" },
  { slug: "dal-bhat", dish: "Dal Bhat", country: "Nepal", level: "hard" },
  { slug: "ema-datshi", dish: "Ema Datshi", country: "Bhutan", level: "hard" },
  { slug: "hakarl", dish: "Hákarl", country: "Iceland", level: "hard" },
  { slug: "hangi", dish: "Hangi", country: "New Zealand", level: "hard" },
  { slug: "karjalanpiirakka", dish: "Karjalanpiirakka", country: "Finland", level: "hard" },
  { slug: "bobotie", dish: "Bobotie", country: "South Africa", level: "hard" },
  { slug: "buuz", dish: "Buuz", country: "Mongolia", level: "hard" },
  { slug: "beshbarmak", dish: "Beshbarmak", country: "Kazakhstan", level: "hard" },
  // IMPOSSIBLE (17)
  { slug: "cepelinai", dish: "Cepelinai", country: "Lithuania", level: "impossible" },
  { slug: "mulgipuder", dish: "Mulgipuder", country: "Estonia", level: "impossible" },
  { slug: "pastizzi", dish: "Pastizzi", country: "Malta", level: "impossible" },
  { slug: "grey-peas-with-bacon", dish: "Grey Peas with Bacon", country: "Latvia", level: "impossible" },
  { slug: "draniki", dish: "Draniki", country: "Belarus", level: "impossible" },
  { slug: "mamaliga", dish: "Mămăligă", country: "Moldova", level: "impossible" },
  { slug: "sopa-paraguaya", dish: "Sopa Paraguaya", country: "Paraguay", level: "impossible" },
  { slug: "pepperpot", dish: "Pepperpot", country: "Guyana", level: "impossible" },
  { slug: "pom", dish: "Pom", country: "Suriname", level: "impossible" },
  { slug: "camel-tibs", dish: "Camel Tibs", country: "Djibouti", level: "impossible" },
  { slug: "laplap", dish: "Laplap", country: "Vanuatu", level: "impossible" },
  { slug: "kokoda", dish: "Kokoda", country: "Fiji", level: "impossible" },
  { slug: "mumu", dish: "Mumu", country: "Papua New Guinea", level: "impossible" },
  { slug: "qurutob", dish: "Qurutob", country: "Tajikistan", level: "impossible" },
  { slug: "kuurdak", dish: "Kuurdak", country: "Kyrgyzstan", level: "impossible" },
  { slug: "langouste-a-la-vanille", dish: "Langouste à la Vanille", country: "Comoros", level: "impossible" },
  { slug: "gutap", dish: "Gutap", country: "Turkmenistan", level: "impossible" },
];
export default COUNTRY_BY_FOOD_E08;
