// Episode 8 "Guess the Country by Food" — one verified <=70-char fact per item, keyed by slug.
export const COUNTRY_BY_FOOD_E08_FACTS = {
  sushi: "Sushi originally referred to the fermented rice, not the fish.",
  "pizza-margherita": "Legend says Margherita pizza was named for Italy's queen in 1889.",
  tacos: "Tacos likely predate the Spanish conquest of Mexico.",
  croissant: "The croissant's crescent shape may trace back to Austrian pastries.",
  hamburger: "The hamburger is named after Hamburg, Germany, not the US.",
  "butter-chicken": "Butter Chicken is widely credited to a Delhi restaurant in the 1950s.",
  "peking-duck": "Peking Duck has been made in China since the imperial era.",
  "pad-thai": "Pad Thai was promoted nationally by Thailand's government in the 1930s.",
  kimchi: "Korea has thousands of regional kimchi variations.",
  bratwurst: "Bratwurst recipes in Germany date back to the 1300s.",
  paella: "Paella takes its name from the pan it's cooked in.",
  pho: "Pho likely emerged in northern Vietnam in the early 1900s.",
  "cheese-fondue": "Fondue became a national Swiss dish through a 1930s marketing push.",
  moussaka: "Moussaka got its modern layered form from a Greek chef in the 1920s.",
  pierogi: "Pierogi have been a staple in Poland since the Middle Ages.",
  goulash: "Goulash began as a stew cooked by Hungarian cattle herders.",
  "fish-and-chips": "Fish and chips became a British staple in the 1860s.",
  "turkish-delight": "Turkish Delight dates back to the Ottoman Empire.",
  "chicken-tagine": "Tagine is named after the cone-shaped clay pot it's cooked in.",
  "ghormeh-sabzi": "Ghormeh Sabzi is often called Iran's national dish.",
  asado: "Asado is a beloved grilling tradition across Argentina and Uruguay.",
  feijoada: "Feijoada is Brazil's national dish, built around black beans.",
  ceviche: "Ceviche is UNESCO-listed as part of Peru's cultural heritage.",
  rendang: "Rendang was declared Indonesia's national dish in 2018.",
  "chicken-adobo": "Adobo is considered the unofficial national dish of the Philippines.",
  borscht: "UNESCO recognized borscht as part of Ukraine's culture in 2022.",
  "pastel-de-nata": "The original custard tart recipe comes from a Lisbon monastery.",
  "belgian-waffles": "Belgium actually has two distinct waffle styles, not one.",
  "wiener-schnitzel": "Wiener Schnitzel must be made with veal to carry that name in Austria.",
  "nasi-lemak": "Nasi Lemak is often called Malaysia's national dish.",
  "chili-crab": "Chili crab was invented by a Singapore street-food couple in 1956.",
  "kottu-roti": "Kottu is made by chopping flatbread on a hot griddle.",
  koshari: "Koshari mixes rice, lentils, pasta, and chickpeas in one dish.",
  thieboudienne: "Thieboudienne is Senegal's national dish, built on rice and fish.",
  "bandeja-paisa": "Bandeja Paisa comes from Colombia's Antioquia region.",
  "swedish-meatballs": "IKEA now serves Swedish meatballs in stores worldwide.",
  "doro-wat": "Doro Wat is eaten by hand, scooped up with injera bread.",
  "egusi-soup": "Egusi soup is thickened with ground melon seeds.",
  plov: "Plov is often cooked in huge communal pots for celebrations.",
  khachapuri: "Khachapuri is Georgia's cheese-filled bread, shaped differently by region.",
  saltenas: "Salteñas are eaten carefully to avoid spilling their hot broth.",
  "pastel-de-choclo": "Pastel de Choclo is topped with a sweet corn crust, not pastry.",
  "ropa-vieja": "Ropa Vieja means 'old clothes' in Spanish, for its shredded look.",
  "fish-amok": "Fish Amok is steamed in banana leaves, a Cambodian classic.",
  larb: "Larb is often considered the national dish of Laos.",
  mohinga: "Mohinga is widely eaten as a breakfast dish in Myanmar.",
  "dal-bhat": "Dal Bhat is eaten daily by most households across Nepal.",
  "ema-datshi": "Ema Datshi is Bhutan's national dish, built on chili and cheese.",
  hakarl: "Hakarl is shark meat cured for months to make it safe to eat.",
  hangi: "Hangi food is cooked underground with heated stones.",
  karjalanpiirakka: "Karjalanpiirakka comes from Finland's Karelia region.",
  bobotie: "Bobotie is a spiced meat dish topped with an egg custard.",
  buuz: "Buuz are steamed dumplings eaten especially at Mongolian New Year.",
  beshbarmak: "Beshbarmak is a national dish across Kazakhstan and Kyrgyzstan.",
  cepelinai: "Cepelinai are named for their resemblance to zeppelin airships.",
  mulgipuder: "Mulgipuder mashes potatoes and barley together, an Estonian classic.",
  pastizzi: "Pastizzi are flaky pastries sold at kiosks across Malta.",
  "grey-peas-with-bacon": "Grey peas with bacon is a traditional Latvian winter dish.",
  draniki: "Draniki are fried potato pancakes central to Belarusian cooking.",
  mamaliga: "Mamaliga is a cornmeal staple shared by Moldova and Romania.",
  "sopa-paraguaya": "Sopa Paraguaya is technically a cornbread, not a soup.",
  pepperpot: "Pepperpot is Guyana's national dish, flavored with cassareep.",
  pom: "Pom is a festive Surinamese dish made with grated taro root.",
  "camel-tibs": "Camel meat is a valued specialty in Djiboutian cooking.",
  laplap: "Laplap is considered the national dish of Vanuatu.",
  kokoda: "Kokoda is Fiji's take on ceviche, made with coconut milk.",
  mumu: "A mumu is a Papua New Guinean feast cooked in an underground oven.",
  qurutob: "Qurutob is eaten by hand, torn from a shared communal plate.",
  kuurdak: "Kuurdak is a fried-meat dish common across Kyrgyz households.",
  "langouste-a-la-vanille": "This Comorian lobster dish is flavored with the islands' own vanilla.",
  gutap: "Gutap is a fried stuffed flatbread popular across Turkmenistan.",
};
export default COUNTRY_BY_FOOD_E08_FACTS;
