// Episode 17 "Guess the Desert" — one verified <=70-char fact per item, keyed by slug.
export const DESERTS_E17_FACTS = {
  "grand-erg-oriental-algeria": "Grand Erg Oriental is a vast sea of shifting sand dunes.",
  "death-valley-usa": "Death Valley holds the record for hottest air temperature on Earth.",
  "namib-desert-namibia": "The Namib is believed to be the world's oldest desert.",
  "atacama-desert-chile": "The Atacama is the driest non-polar desert on Earth.",
  "gobi-desert-mongolia": "The Gobi Desert was once home to dinosaur nesting grounds.",
  "salar-de-uyuni-bolivia": "Salar de Uyuni is the world's largest salt flat.",
  "arabian-desert-saudi-arabia": "The Arabian Desert covers most of the Arabian Peninsula.",
  "thar-desert-india": "The Thar Desert is one of the most densely populated deserts.",
  "kalahari-desert-botswana": "The Kalahari isn't a true desert — it gets enough rain for plants.",
  "taklamakan-desert-china": "Taklamakan means 'you can enter but never leave' in local lore.",
  "karakum-desert-turkmenistan": "Karakum hosts a fiery crater nicknamed the Door to Hell.",
  "chihuahuan-desert-mexico": "The Chihuahuan is one of the most biodiverse deserts on Earth.",
  "patagonian-desert-argentina": "The Patagonian Desert is the largest desert in the Americas.",
  "richat-structure-mauritania": "The Richat Structure is a giant bullseye visible from space.",
  "great-victoria-desert-australia": "The Great Victoria is Australia's largest desert.",
  "white-desert-egypt": "Egypt's White Desert is famous for wind-carved chalk formations.",
  "dasht-e-lut-iran": "Dasht-e Lut is tied for the hottest land surface temperature ever.",
  "karoo-south-africa": "The Karoo holds one of the richest fossil records on Earth.",
  "mojave-desert-usa": "The Mojave Desert is home to the iconic Joshua Tree.",
  "great-rann-of-kutch-india": "The Great Rann of Kutch floods into a giant salt marsh yearly.",
  "sinai-desert-egypt": "The Sinai Desert sits between Africa and Asia.",
  "simpson-desert-australia": "The Simpson Desert has the world's longest parallel sand dunes.",
  "badain-jaran-desert-china": "Badain Jaran has some of the tallest stationary dunes on Earth.",
  "syrian-desert-syria": "The Syrian Desert once hosted ancient caravan trade routes.",
  "kyzylkum-desert-uzbekistan": "Kyzylkum means 'red sand' in the Turkic languages.",
  "makgadikgadi-pan-botswana": "Makgadikgadi Pan was once one of Africa's largest lakes.",
  "rub-al-khali-saudi-arabia": "Rub' al Khali is the largest continuous sand desert on Earth.",
  "nubian-desert-sudan": "The Nubian Desert holds more ancient pyramids than Egypt.",
  "nazca-desert-peru": "Peru's coastal desert holds the mysterious Nazca Lines.",
  "valle-de-la-luna-chile": "Valle de la Luna's landscape resembles the surface of the moon.",
  "great-sand-sea-libya": "The Great Sand Sea covers roughly 72,000 square kilometers.",
  "liwa-desert-uae": "The Liwa Desert has some of the tallest dunes in Arabia.",
  "tabernas-desert-spain": "Tabernas Desert doubled for the American West in old Westerns.",
  "tenere-desert-niger": "The Ténéré was once a lush region full of ancient rock art.",
  "dasht-e-kavir-iran": "Dasht-e Kavir is famous for its salty, cracked terrain.",
  "khongoryn-els-mongolia": "Khongoryn Els is nicknamed the Singing Dunes for their sound.",
  "white-sands-usa": "White Sands is made of rare gypsum crystal sand.",
  "pinnacles-desert-australia": "The Pinnacles Desert is filled with thousands of limestone spires.",
  "chott-el-djerid-tunisia": "Chott el Djerid is a vast dry salt lake in the Sahara.",
  "black-desert-egypt": "Egypt's Black Desert gets its color from volcanic rock.",
  "registan-desert-afghanistan": "Registan means 'place of sand' in Persian.",
  "salvador-dali-desert-bolivia": "The Salvador Dalí Desert is named for its surreal landscape.",
  "monte-desert-argentina": "The Monte Desert stretches along Argentina's dry interior.",
  "carcross-desert-canada": "Carcross is often called the world's smallest desert.",
  "sechura-desert-peru": "The Sechura Desert briefly blooms with flowers after rare rains.",
  "la-guajira-desert-colombia": "La Guajira is Colombia's only true desert region.",
  "bardenas-reales-spain": "Bardenas Reales has appeared as a filming location for Star Wars.",
  "gran-desierto-de-altar-mexico": "Gran Desierto de Altar is North America's largest active dune field.",
  "khor-al-adaid-qatar": "Khor Al Adaid is a rare inland sea surrounded by desert.",
  "cholistan-desert-pakistan": "The Cholistan Desert hosts an annual jeep rally race.",
  "chalbi-desert-kenya": "The Chalbi Desert was once the bed of a prehistoric lake.",
  "skeleton-coast-namibia": "Skeleton Coast is named for the many shipwrecks along its shore.",
  "ubari-sand-sea-libya": "Ubari Sand Sea hides small freshwater lakes among its dunes.",
  "varzaneh-desert-iran": "Varzaneh Desert has some of Iran's most photographed dunes.",
  "sonoran-desert-usa": "The Sonoran Desert is the only home of the giant saguaro cactus.",
  "great-sandy-desert-australia": "The Great Sandy Desert is Australia's second-largest desert.",
  "betpak-dala-kazakhstan": "Betpak-Dala means 'hungry steppe' in Kazakh.",
  "ennedi-plateau-chad": "The Ennedi Plateau hides ancient rock art in its sandstone canyons.",
  "bayuda-desert-sudan": "The Bayuda Desert sits inside a giant bend of the Nile River.",
  "kumtag-desert-china": "The Kumtag Desert connects two of China's driest regions.",
  "kharan-desert-pakistan": "The Kharan Desert is one of Pakistan's most remote regions.",
  "ad-dahna-desert-saudi-arabia": "Ad-Dahna is called the river of sand for its narrow red shape.",
  "medanos-de-coro-venezuela": "Médanos de Coro is Venezuela's only true sand dune desert.",
  "chara-sands-russia": "Chara Sands is a tiny desert surrounded by Siberian mountains.",
  "grand-bara-desert-djibouti": "Grand Bara Desert hosts an annual race across its flat clay plain.",
  "guban-somalia": "Guban means 'burnt land' in Somali.",
  "erg-chech-mali": "Erg Chech is one of the largest ergs in the western Sahara.",
  "issaouane-erg-algeria": "Issaouane Erg has star dunes and barchan dunes up to 120km long.",
  "vizcaino-desert-mexico": "The Vizcaíno Desert shares its name with a whale sanctuary nearby.",
  "maranjab-desert-iran": "Maranjab Desert sits beside one of Iran's largest salt lakes.",
  "gilf-kebir-egypt": "Gilf Kebir inspired scenes in The English Patient film.",
};
