export const DINOSAURS_E92_FACTS = {
  "tyrannosaurus-rex": "Its bite force is estimated among the strongest of any land animal, capable of crushing bone.",
  triceratops: "Its frill and horns may have been used for display and species recognition as much as for combat.",
  stegosaurus: "Its brain was roughly the size of a walnut, tiny relative to its 9-meter body length.",
  velociraptor: "Fossil evidence shows it was covered in feathers, though it could not fly.",
  brachiosaurus: "Its nostrils sat in a bony arch atop its head, an unusual feature among long-necked dinosaurs.",
  brontosaurus: "The name means 'thunder lizard' — it was ruled invalid for a century before being reinstated in 2015.",
  pterodactylus: "It's a pterosaur, not technically a dinosaur, and was one of the first ever discovered — giving us the word 'pterodactyl.'",
  ankylosaurus: "Its tail club was made of fused bone and could likely deliver bone-breaking blows to attackers.",
  spinosaurus: "A 2020 study found its tail was fin-shaped, hinting it may have swum — though this is still debated.",
  diplodocus: "It may have been able to crack its whip-like tail through the air faster than the speed of sound.",
  pteranodon: "Despite often being called a flying dinosaur, it was a pterosaur, a separate group of flying reptiles.",
  iguanodon: "Its thumb spikes were originally mistaken for a horn on its nose when first reconstructed in the 1800s.",
  allosaurus: "It was among the most common large predators of the Late Jurassic, known from hundreds of fossils.",
  archaeopteryx: "It had both bird-like feathers and reptile-like features such as teeth and a long bony tail.",
  mosasaurus: "Despite resembling a giant lizard, it was a marine reptile, not a dinosaur, with a shark-like tail fin.",
  plesiosaurus: "A marine reptile, not a dinosaur — its long-necked body plan likely inspired Loch Ness Monster imagery.",
  parasaurolophus: "Its hollow head crest may have worked like a trombone, producing deep resonant calls.",
  dilophosaurus: "Real Dilophosaurus had no neck frill and could not spit venom — those were Jurassic Park inventions.",
  pachycephalosaurus: "Its skull dome could be over 20cm thick, possibly used for head-butting contests.",
  compsognathus: "It's one of the smallest known non-avian dinosaurs, roughly the size of a large chicken.",
  megalosaurus: "In 1824 it became the first dinosaur genus ever formally named and scientifically described.",
  carnotaurus: "It had proportionally the smallest arms of almost any known theropod, even shorter than a T. rex's.",
  therizinosaurus: "It had some of the longest claws of any known animal, the largest reaching over half a meter.",
  gallimimus: "Built for speed, it may have run as fast as an ostrich, among the swiftest of all dinosaurs.",
  deinonychus: "Its discovery in the 1960s inspired the raptor image later used for Velociraptor in Jurassic Park.",
  utahraptor: "Its foot claw could grow to around 22 centimeters long, the largest of any known dromaeosaur.",
  styracosaurus: "Its name means 'spiked lizard,' referring to the ring of long spikes around its neck frill.",
  corythosaurus: "Its rounded head crest housed looping nasal passages that likely amplified its calls.",
  quetzalcoatlus: "This pterosaur, not a dinosaur, had an estimated 10+ meter wingspan — among the largest fliers ever known.",
  ichthyosaurus: "A marine reptile, not a dinosaur, it gave birth to live young at sea instead of laying eggs on land.",
  elasmosaurus: "A marine reptile, not a dinosaur, its neck held around 70 bones — among the most of any known animal.",
  baryonyx: "Its curved thumb claw and fish scales found near its stomach suggest it hunted fish along riverbanks.",
  giganotosaurus: "It rivaled Tyrannosaurus rex in length, though which was truly larger is still debated.",
  kentrosaurus: "Unlike its relative Stegosaurus, its armor shifts from small plates in front to sharp spikes toward the tail.",
  maiasaura: "Its name means 'good mother lizard,' after fossil nests showing it cared for its hatchlings.",
  oviraptor: "Though named 'egg thief,' evidence suggests it and its relatives were incubating their own nests, not stealing them.",
  coelophysis: "Hundreds of its skeletons were found together at one site in New Mexico, suggesting group living.",
  herrerasaurus: "It lived roughly 231 million years ago, making it one of the oldest known dinosaurs.",
  plateosaurus: "It was one of the first dinosaurs to grow to a large size, reaching up to about 10 meters long.",
  edmontosaurus: "Rare fossilized skin impressions show it had a soft fleshy comb on its head, invisible from bones alone.",
  lambeosaurus: "Its hollow crest connected to its nasal passages and likely helped produce a distinct honking call.",
  pentaceratops: "Its skull, including its bony frill, ranks among the largest of any known land animal.",
  protoceratops: "A famous fossil captured it locked in combat with a Velociraptor, likely buried by a collapsing dune.",
  dimorphodon: "A pterosaur, not a dinosaur, its unusually large head led early researchers to compare it to a flying puffin.",
  rhamphorhynchus: "This pterosaur, not a dinosaur, had a diamond-shaped tail vane that likely acted like a rudder in flight.",
  liopleurodon: "A short-necked marine reptile, not a dinosaur, with proportionally one of the largest heads of its group.",
  amargasaurus: "Its double row of neck spines is unlike any other known sauropod's, and their function is still debated.",
  suchomimus: "Its name means 'crocodile mimic,' referring to its narrow, fish-catching snout.",
  dreadnoughtus: "Its name means 'fears nothing' — among the heaviest land animals known from a well-preserved skeleton.",
  yutyrannus: "At roughly 9 meters long, it's the largest dinosaur known to be covered in feathers.",
  sinosauropteryx: "It was the first non-avian dinosaur ever confirmed to have feathers, revealed by 1990s fossils from China.",
  microraptor: "Studies of its fossil feathers suggest it had a glossy black, iridescent sheen similar to a crow.",
  epidexipteryx: "It lacked long flight feathers, suggesting its odd ribbon tail plumage was for display, not flight.",
  "yi-qi": "It's one of only two known dinosaurs with bat-style membrane wings instead of feathers.",
  masiakasaurus: "Its odd forward-facing front teeth may have helped it spear slippery prey like fish.",
  nigersaurus: "It carried over 500 slender teeth, continuously replacing them every few weeks.",
  concavenator: "Bumps on its forearm bones resemble structures in birds that anchor large feathers.",
  guanlong: "It's one of the earliest known tyrannosauroids, living about 90 million years before T. rex.",
  segisaurus: "It's one of the few dinosaurs known to have hollow limb bones like modern birds.",
  buitreraptor: "Its long, narrow snout is unusual among raptors and may have helped it snap up small, quick prey.",
  shuvuuia: "Its odd single-clawed arms may have been used to dig into insect nests.",
  tsintaosaurus: "Its unusual single spike crest was long debated, with reconstructions unsure exactly how it sat on the skull.",
  muttaburrasaurus: "It's known from one of the most complete dinosaur skeletons ever found in Australia.",
  leaellynasaura: "It lived within the Antarctic Circle, and its large eyes may have helped it see during months of polar darkness.",
  minmi: "Unlike most armored dinosaurs, it had extra bony plates protecting its belly as well as its back.",
  yinlong: "As one of the earliest known ceratopsians, it shows how the group's frill began as just a small ridge.",
  psittacosaurus: "A fossil with preserved skin pigment shows it had a dark back and pale belly for camouflage.",
  anchiornis: "Fossil pigment studies let scientists reconstruct its plumage colors, including a rusty-red head crest.",
  eoraptor: "As one of the earliest known dinosaurs, it shows a mix of primitive features from near the dawn of the lineage.",
  scutellosaurus: "It's one of the earliest known armored dinosaurs, before later relatives evolved to walk on all fours.",
};
