// E23 "Guess the Dog Breed" — answer = breed name.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
// Hard content rules: no Israel/Jerusalem/West Bank/Gaza content of any kind.
export const DOG_BREEDS_E23 = [
  // EASY (18) — instantly recognizable worldwide
  { slug: "labrador-retriever", name: "Labrador Retriever", sci: "Canis familiaris", level: "easy" },
  { slug: "golden-retriever", name: "Golden Retriever", sci: "Canis familiaris", level: "easy" },
  { slug: "german-shepherd", name: "German Shepherd", sci: "Canis familiaris", level: "easy" },
  { slug: "poodle", name: "Poodle", sci: "Canis familiaris", level: "easy" },
  { slug: "french-bulldog", name: "French Bulldog", sci: "Canis familiaris", level: "easy" },
  { slug: "chihuahua", name: "Chihuahua", sci: "Canis familiaris", level: "easy" },
  { slug: "dachshund", name: "Dachshund", sci: "Canis familiaris", level: "easy" },
  { slug: "beagle", name: "Beagle", sci: "Canis familiaris", level: "easy" },
  { slug: "rottweiler", name: "Rottweiler", sci: "Canis familiaris", level: "easy" },
  { slug: "siberian-husky", name: "Siberian Husky", sci: "Canis familiaris", level: "easy" },
  { slug: "pug", name: "Pug", sci: "Canis familiaris", level: "easy" },
  { slug: "boxer", name: "Boxer", sci: "Canis familiaris", level: "easy" },
  { slug: "great-dane", name: "Great Dane", sci: "Canis familiaris", level: "easy" },
  { slug: "doberman-pinscher", name: "Doberman Pinscher", sci: "Canis familiaris", level: "easy" },
  { slug: "border-collie", name: "Border Collie", sci: "Canis familiaris", level: "easy" },
  { slug: "pembroke-welsh-corgi", name: "Pembroke Welsh Corgi", sci: "Canis familiaris", level: "easy" },
  { slug: "shih-tzu", name: "Shih Tzu", sci: "Canis familiaris", level: "easy" },
  { slug: "yorkshire-terrier", name: "Yorkshire Terrier", sci: "Canis familiaris", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "cocker-spaniel", name: "Cocker Spaniel", sci: "Canis familiaris", level: "medium" },
  { slug: "australian-shepherd", name: "Australian Shepherd", sci: "Canis familiaris", level: "medium" },
  { slug: "boston-terrier", name: "Boston Terrier", sci: "Canis familiaris", level: "medium" },
  { slug: "bernese-mountain-dog", name: "Bernese Mountain Dog", sci: "Canis familiaris", level: "medium" },
  { slug: "cane-corso", name: "Cane Corso", sci: "Canis familiaris", level: "medium" },
  { slug: "saint-bernard", name: "Saint Bernard", sci: "Canis familiaris", level: "medium" },
  { slug: "bichon-frise", name: "Bichon Frise", sci: "Canis familiaris", level: "medium" },
  { slug: "shiba-inu", name: "Shiba Inu", sci: "Canis familiaris", level: "medium" },
  { slug: "maltese", name: "Maltese", sci: "Canis familiaris", level: "medium" },
  { slug: "weimaraner", name: "Weimaraner", sci: "Canis familiaris", level: "medium" },
  { slug: "basset-hound", name: "Basset Hound", sci: "Canis familiaris", level: "medium" },
  { slug: "dalmatian", name: "Dalmatian", sci: "Canis familiaris", level: "medium" },
  { slug: "pomeranian", name: "Pomeranian", sci: "Canis familiaris", level: "medium" },
  { slug: "bull-terrier", name: "Bull Terrier", sci: "Canis familiaris", level: "medium" },
  { slug: "akita", name: "Akita", sci: "Canis familiaris", level: "medium" },
  { slug: "newfoundland", name: "Newfoundland", sci: "Canis familiaris", level: "medium" },
  { slug: "cavalier-king-charles-spaniel", name: "Cavalier King Charles Spaniel", sci: "Canis familiaris", level: "medium" },
  { slug: "alaskan-malamute", name: "Alaskan Malamute", sci: "Canis familiaris", level: "medium" },

  // HARD (18) — recognizable to enthusiasts
  { slug: "whippet", name: "Whippet", sci: "Canis familiaris", level: "hard" },
  { slug: "vizsla", name: "Vizsla", sci: "Canis familiaris", level: "hard" },
  { slug: "chow-chow", name: "Chow Chow", sci: "Canis familiaris", level: "hard" },
  { slug: "samoyed", name: "Samoyed", sci: "Canis familiaris", level: "hard" },
  { slug: "rhodesian-ridgeback", name: "Rhodesian Ridgeback", sci: "Canis familiaris", level: "hard" },
  { slug: "belgian-malinois", name: "Belgian Malinois", sci: "Canis familiaris", level: "hard" },
  { slug: "bloodhound", name: "Bloodhound", sci: "Canis familiaris", level: "hard" },
  { slug: "irish-setter", name: "Irish Setter", sci: "Canis familiaris", level: "hard" },
  { slug: "chinese-crested", name: "Chinese Crested", sci: "Canis familiaris", level: "hard" },
  { slug: "papillon", name: "Papillon", sci: "Canis familiaris", level: "hard" },
  { slug: "basenji", name: "Basenji", sci: "Canis familiaris", level: "hard" },
  { slug: "afghan-hound", name: "Afghan Hound", sci: "Canis familiaris", level: "hard" },
  { slug: "old-english-sheepdog", name: "Old English Sheepdog", sci: "Canis familiaris", level: "hard" },
  { slug: "airedale-terrier", name: "Airedale Terrier", sci: "Canis familiaris", level: "hard" },
  { slug: "jack-russell-terrier", name: "Jack Russell Terrier", sci: "Canis familiaris", level: "hard" },
  { slug: "shar-pei", name: "Shar Pei", sci: "Canis familiaris", level: "hard" },
  { slug: "great-pyrenees", name: "Great Pyrenees", sci: "Canis familiaris", level: "hard" },
  { slug: "english-springer-spaniel", name: "English Springer Spaniel", sci: "Canis familiaris", level: "hard" },

  // IMPOSSIBLE (17) — obscure even to enthusiasts
  { slug: "xoloitzcuintli", name: "Xoloitzcuintli", sci: "Canis familiaris", level: "impossible" },
  { slug: "azawakh", name: "Azawakh", sci: "Canis familiaris", level: "impossible" },
  { slug: "otterhound", name: "Otterhound", sci: "Canis familiaris", level: "impossible" },
  { slug: "bergamasco", name: "Bergamasco Shepherd", sci: "Canis familiaris", level: "impossible" },
  { slug: "mudi", name: "Mudi", sci: "Canis familiaris", level: "impossible" },
  { slug: "barbet", name: "Barbet", sci: "Canis familiaris", level: "impossible" },
  { slug: "peruvian-inca-orchid", name: "Peruvian Inca Orchid", sci: "Canis familiaris", level: "impossible" },
  { slug: "norwegian-lundehund", name: "Norwegian Lundehund", sci: "Canis familiaris", level: "impossible" },
  { slug: "thai-ridgeback", name: "Thai Ridgeback", sci: "Canis familiaris", level: "impossible" },
  { slug: "karelian-bear-dog", name: "Karelian Bear Dog", sci: "Canis familiaris", level: "impossible" },
  { slug: "stabyhoun", name: "Stabyhoun", sci: "Canis familiaris", level: "impossible" },
  { slug: "cirneco-dell-etna", name: "Cirneco dell'Etna", sci: "Canis familiaris", level: "impossible" },
  { slug: "kooikerhondje", name: "Kooikerhondje", sci: "Canis familiaris", level: "impossible" },
  { slug: "sloughi", name: "Sloughi", sci: "Canis familiaris", level: "impossible" },
  { slug: "lagotto-romagnolo", name: "Lagotto Romagnolo", sci: "Canis familiaris", level: "impossible" },
  { slug: "schipperke", name: "Schipperke", sci: "Canis familiaris", level: "impossible" },
  { slug: "puli", name: "Puli", sci: "Canis familiaris", level: "impossible" },
];
