export const DOG_BREEDS_E23_FACTS = {
  "labrador-retriever": "Labradors were America's top dog breed for a record 31 straight years.",
  "golden-retriever": "Golden Retrievers were bred in Scotland to retrieve waterfowl.",
  "german-shepherd": "German Shepherds are widely used as police and service dogs.",
  "poodle": "Poodles were originally bred in Germany as water retrievers.",
  "french-bulldog": "French Bulldogs can't swim well due to their heavy front bodies.",
  "chihuahua": "The Chihuahua is named after a state in Mexico.",
  "dachshund": "Dachshunds were bred to hunt badgers in narrow burrows.",
  "beagle": "Beagles have one of the best senses of smell of any dog.",
  "rottweiler": "Rottweilers descend from Roman cattle-driving dogs.",
  "siberian-husky": "Huskies were bred by the Chukchi people of Siberia to pull sleds.",
  "pug": "Pugs were prized companions of Chinese emperors.",
  "boxer": "The Boxer descends from the German Bullenbeisser, an ancient hunting dog.",
  "great-dane": "Great Danes are called the 'Apollo of dogs' for their size.",
  "doberman-pinscher": "The Doberman was bred by a German tax collector for protection.",
  "border-collie": "Border Collies are considered the most intelligent dog breed.",
  "pembroke-welsh-corgi": "Corgis were bred to herd cattle by nipping at their heels.",
  "shih-tzu": "Shih Tzus were bred as companion dogs for Chinese royalty.",
  "yorkshire-terrier": "Yorkshire Terriers were originally bred to catch rats in mills.",
  "cocker-spaniel": "Cocker Spaniels are named for hunting woodcock birds.",
  "australian-shepherd": "Despite the name, Australian Shepherds were bred in the USA.",
  "boston-terrier": "The Boston Terrier is nicknamed the 'American Gentleman.'",
  "bernese-mountain-dog": "Bernese Mountain Dogs were bred to pull carts in the Alps.",
  "cane-corso": "Cane Corso descends from ancient Roman war dogs.",
  "saint-bernard": "Saint Bernards were bred by monks to rescue Alpine travelers.",
  "bichon-frise": "Bichon Frise means 'curly lap dog' in French.",
  "shiba-inu": "The Shiba Inu is one of Japan's oldest native dog breeds.",
  "maltese": "The Maltese breed dates back over 2,000 years.",
  "weimaraner": "Weimaraners are nicknamed the 'Grey Ghost' for their coat.",
  "basset-hound": "Basset Hounds have an extraordinary sense of smell despite short legs.",
  "dalmatian": "Dalmatians were historically used as carriage escort dogs.",
  "pomeranian": "Pomeranians were bred down in size from larger sled dogs.",
  "bull-terrier": "The Bull Terrier is known for its unique egg-shaped head.",
  "akita": "The Akita is a symbol of loyalty and good health in Japan.",
  "newfoundland": "Newfoundlands have webbed feet for strong swimming ability.",
  "cavalier-king-charles-spaniel": "This breed is named after English King Charles II.",
  "alaskan-malamute": "Malamutes are one of the oldest Arctic sled dog breeds.",
  "whippet": "Whippets can reach speeds of up to 35 miles per hour.",
  "vizsla": "Vizslas are known as 'velcro dogs' for staying close to owners.",
  "chow-chow": "Chow Chows are one of the few breeds with a blue-black tongue.",
  "samoyed": "Samoyeds were bred to herd reindeer in Siberia.",
  "rhodesian-ridgeback": "The Ridgeback's name comes from the ridge of hair on its back.",
  "belgian-malinois": "Malinois are favored by military and police worldwide.",
  "bloodhound": "A Bloodhound's scent trail evidence can be used in court.",
  "irish-setter": "Irish Setters were bred to locate game birds in open fields.",
  "chinese-crested": "Chinese Crested dogs come in hairless and powderpuff varieties.",
  "papillon": "Papillon means 'butterfly' in French, for its ear shape.",
  "basenji": "Basenjis are known as the barkless dog of Africa.",
  "afghan-hound": "The Afghan Hound has one of the oldest dog lineages known.",
  "old-english-sheepdog": "Old English Sheepdogs were bred to herd cattle to market.",
  "airedale-terrier": "The Airedale is called the 'King of Terriers' for its size.",
  "jack-russell-terrier": "Jack Russells were bred in England for fox hunting.",
  "shar-pei": "Shar Peis are famous for their deeply wrinkled skin.",
  "great-pyrenees": "This breed guarded sheep in the Pyrenees mountains for centuries.",
  "english-springer-spaniel": "Springer Spaniels flush game birds into the open to hunt.",
  "xoloitzcuintli": "The Xolo is an ancient hairless breed sacred to the Aztecs.",
  "azawakh": "The Azawakh is a sighthound from the Sahara desert region.",
  "otterhound": "Otterhounds are one of the rarest dog breeds in the world.",
  "bergamasco": "The Bergamasco's coat naturally forms thick woolly mats.",
  "mudi": "The Mudi is a rare Hungarian herding breed.",
  "barbet": "The Barbet is a French water dog with a thick curly coat.",
  "peruvian-inca-orchid": "This hairless breed was cherished by pre-Inca cultures.",
  "norwegian-lundehund": "This breed has six toes on each foot for climbing cliffs.",
  "thai-ridgeback": "The Thai Ridgeback has a distinct ridge of reversed fur.",
  "karelian-bear-dog": "Karelian Bear Dogs were bred in Finland to hunt large game.",
  "stabyhoun": "The Stabyhoun is a rare Dutch breed from Friesland.",
  "cirneco-dell-etna": "This ancient sighthound comes from Sicily's Mount Etna area.",
  "kooikerhondje": "Dutch hunters used this breed to lure ducks into traps.",
  "sloughi": "The Sloughi is a sighthound bred by North African nomads.",
  "lagotto-romagnolo": "This Italian breed is prized for hunting truffles by scent.",
  "schipperke": "Schipperkes were mascots on Belgian canal barges.",
  "puli": "The Puli's coat naturally forms long corded dreadlocks.",
};
