export const ELEMENTS_E52_FACTS = {
  // EASY
  "gold": "Atomic number 79; so unreactive it never tarnishes or rusts.",
  "silver": "Best electrical conductor of any metal; tarnishes to black sulfide.",
  "copper": "Turns green (patina) when it corrodes, like the Statue of Liberty.",
  "iron": "Most-produced metal on Earth; also the core of red blood cells.",
  "carbon": "Same element as graphite and diamond, just different bonding.",
  "oxygen": "Makes up 21% of air; liquid oxygen is pale blue and magnetic.",
  "hydrogen": "Lightest element and most abundant in the universe.",
  "helium": "Second-lightest element; never bonds with anything else.",
  "nitrogen": "Fills 78% of Earth's air; liquid nitrogen boils at -196C.",
  "aluminum": "Once pricier than gold; now among the cheapest, most-used metals.",
  "sulfur": "Bright yellow solid; gives rotten eggs their notorious smell.",
  "mercury": "Only metal that's liquid at room temperature.",
  "neon": "Glows orange-red in tubes; powers classic neon signage.",
  "zinc": "Coats steel to stop rust, a process called galvanizing.",
  "lead": "Very dense and soft; once used in pipes and paint before bans.",
  "tin": "Coats steel cans; a bar of pure tin can 'cry' as it bends.",
  "platinum": "Denser and rarer than gold; used in catalytic converters.",
  "titanium": "Strong as steel but 45% lighter; used in jets and implants.",
  "sodium": "Explodes on contact with water; stored in oil to stay safe.",

  // MEDIUM
  "chlorine": "Greenish-yellow gas used to disinfect drinking water and pools.",
  "iodine": "Purple-black solid that turns straight into violet vapor.",
  "bromine": "One of only two elements that are liquid at room temperature.",
  "nickel": "Named after a 'mischievous' German gnome by frustrated miners.",
  "chromium": "Gives stainless steel its shine and rust resistance.",
  "cobalt": "Named for goblins; gives glass and paint their deep blue color.",
  "tungsten": "Highest melting point of any metal; once lit light bulbs.",
  "silicon": "Second most common element in Earth's crust; powers every chip.",
  "bismuth": "Grows rainbow, staircase-shaped crystals as it cools.",
  "gallium": "Melts in your hand at just above body temperature.",
  "argon": "Makes up nearly 1% of air; fills incandescent light bulbs.",
  "phosphorus": "Glows faintly in the dark; its name means 'light-bearer'.",
  "potassium": "Soft metal that bursts into a lilac flame in water.",
  "calcium": "Makes bones and teeth strong; burns with a brick-red flame.",
  "magnesium": "Burns with a blinding white flame; used in fireworks.",
  "manganese": "Essential to steelmaking; without it, steel would be brittle.",
  "uranium": "Fuels nuclear reactors; its glass makes uranium glass glow green.",
  "neodymium": "Makes the strongest permanent magnets ever produced.",
  "lithium": "Lightest metal; powers phone and electric-car batteries.",

  // HARD
  "boron": "Key ingredient in borosilicate glass and detergent boosters.",
  "germanium": "Powered the first transistors before silicon took over.",
  "cadmium": "Toxic metal once used to make bright yellow pigments.",
  "antimony": "Alloyed with lead to harden bullets and battery plates.",
  "arsenic": "Notorious poison; also used to make semiconductors today.",
  "cesium": "Defines the second; atomic clocks use its vibrations.",
  "rubidium": "Soft, silvery metal that ignites instantly in air.",
  "strontium": "Burns bright red; the color source in red fireworks.",
  "barium": "Its compounds glow in X-rays taken of the digestive tract.",
  "vanadium": "Strengthens steel alloys used in tools and jet engines.",
  "molybdenum": "Toughens steel for high-heat uses like engine parts.",
  "zirconium": "Resists corrosion; used to clad nuclear fuel rods.",
  "palladium": "Absorbs up to 900x its own volume in hydrogen gas.",
  "rhodium": "Rarest traded precious metal; coats white gold jewelry.",
  "iridium": "Marks the dinosaur-extinction layer in rock worldwide.",
  "osmium": "The densest naturally occurring element known.",
  "ruthenium": "Hardens platinum and palladium alloys for durability.",
  "selenium": "Its conductivity shifts with light; used in old photocells.",
  "tellurium": "So rare its traces make breath smell of garlic for weeks.",

  // IMPOSSIBLE
  "hafnium": "Used in reactor control rods; found hiding inside zirconium ore.",
  "niobium": "Superconducting metal used in MRI magnet wiring.",
  "tantalum": "Corrosion-proof metal used inside tiny capacitors.",
  "scandium": "Rare metal that lightens aluminum alloys for aerospace.",
  "yttrium": "Used in the red phosphors that colored old TV screens.",
  "thorium": "Radioactive metal once proposed as a nuclear reactor fuel.",
  "radium": "Glowed in the dark; once painted on watch hands, with fatal results.",
  "polonium": "Discovered by Marie Curie; a single gram could kill millions.",
  "actinium": "Glows faint blue in the dark from its own radioactivity.",
  "protactinium": "Among the rarest, most radioactive elements in nature.",
  "francium": "So unstable only ounces exist on Earth at any moment.",
  "astatine": "Rarest naturally occurring element on the entire planet.",
  "technetium": "First artificially made element; used in medical scans.",
  "promethium": "Named for the fire-stealing Titan; glows a faint blue.",
  "rutherfordium": "Named after physicist Ernest Rutherford, a nuclear-science pioneer.",
  "darmstadtium": "Made one atom at a time by fusing nickel and lead nuclei.",
  "tennessine": "Named for the U.S. state whose labs helped create it.",
  "oganesson": "Heaviest confirmed element; only a few atoms ever made.",
  "livermorium": "Superheavy element that decays in a fraction of a second.",
};
