export const EMOJI_E84_FACTS = {
  "red-heart": "One of the most-used emojis on the planet today.",
  fire: "Often called the 'lit' emoji for something impressive.",
  "thumbs-up": "In some cultures, a thumbs-up is considered rude.",
  star: "Often used to mark something as a favorite or top pick.",
  sun: "One of the original emoji created in Japan back in 1999.",
  crown: "Often used online to mean 'the best' or 'royalty.'",
  skull: "Gen Z often uses it to mean 'I'm dead' from laughing.",
  ghost: "Also the shape of Pac-Man's classic video game enemies.",
  robot: "Its blocky face echoes classic sci-fi robot designs.",
  alien: "Often paired with a UFO emoji in internet jokes.",
  rainbow: "Widely used as a symbol of LGBTQ+ pride.",
  rocket: "Often used to mean something is about to take off.",
  balloon: "A classic symbol for birthdays and celebrations.",
  "wrapped-gift": "Its ribbon color varies slightly across different apps.",
  trophy: "Used across nearly every platform to mark an achievement.",
  "gem-stone": "Often used to describe something as a 'hidden gem.'",
  "high-voltage": "Commonly used to mean 'wow' or sudden excitement.",
  "direct-hit": "A classic symbol for hitting a goal exactly right.",
  kite: "Kites were first flown in ancient China over 2,000 years ago.",
  anchor: "A classic tattoo symbol for sailors and stability.",
  compass: "Used long before GPS to navigate by magnetic north.",
  hourglass: "Its sand-flip design dates back to ancient timekeeping.",
  telescope: "Galileo used an early version to study the moon.",
  lantern: "Modeled after traditional Japanese paper lanterns.",
  "yo-yo": "One of the oldest toys, dating back over 2,000 years.",
  accordion: "Squeezed to push air through its internal reeds.",
  banjo: "Its design traces back to instruments from West Africa.",
  ladder: "Walking under one is considered bad luck in folklore.",
  broom: "Often linked to witches flying through the night sky.",
  shield: "A classic symbol for protection and safety settings.",
  scroll: "Used before books to record ancient texts and laws.",
  amphora: "Ancient Greeks used these jars to store wine and oil.",
  "magic-wand": "A classic prop for stage magicians and fictional wizards.",
  pinata: "Traditionally broken open at Mexican birthday parties.",
  magnet: "Naturally occurring versions are called lodestones.",
  boomerang: "Some are designed to fly back to the thrower's hand.",
  abacus: "One of the earliest tools ever used for arithmetic.",
  "nazar-amulet": "Worn from Turkey to South Asia to ward off the evil eye.",
  moai: "These giant stone statues were carved on Easter Island.",
  "shinto-shrine": "Its gate marks the entrance to a sacred Shinto site.",
  "hindu-temple": "Represents sacred worship spaces found across South Asia.",
  hut: "A simple shelter design used across many cultures.",
  gear: "Used across apps everywhere to open device settings.",
  alembic: "An ancient device once used to distill liquids.",
  "crystal-ball": "A classic prop for fortune tellers in fiction.",
  "diya-lamp": "Lit during Diwali, the Hindu festival of lights.",
  "ringed-planet": "Its design was clearly inspired by Saturn.",
  "test-tube": "A staple tool found in nearly every science lab.",
  "petri-dish": "Named after the German scientist who invented it.",
  dna: "Its twisted-ladder shape is called a double helix.",
  joystick: "A staple control stick for classic arcade games.",
  yarn: "Wound into balls before being knitted or crocheted.",
  ninja: "Trained in stealth and espionage in feudal Japan.",
  "anatomical-heart": "Shows the real four-chambered organ, not the symbol.",
  lungs: "The organ pair that lets you breathe in and out.",
  "x-ray": "Discovered almost by accident in a lab in 1895.",
  hamsa: "A hand-shaped charm believed to ward off evil.",
  "mirror-ball": "A dance-floor staple since the disco era.",
  jar: "Often shown holding preserves like jam or pickles.",
  "playground-slide": "A childhood classic found in parks worldwide.",
  wheel: "One of humanity's most important early inventions.",
  "ring-buoy": "Thrown to swimmers in trouble as a life-saving device.",
  "hair-pick": "Designed with wide teeth for curly, textured hair.",
  flute: "One of the oldest known musical instruments.",
  hook: "Commonly used to catch fish or hang up items.",
  "nesting-dolls": "Known as matryoshka, each one holds a smaller one.",
  "long-drum": "Played by hand across many African musical traditions.",
  "low-battery": "A modern icon almost everyone recognizes instantly.",
  "ballet-shoes": "Worn en pointe by classically trained dancers.",
  sari: "A traditional garment worn by draping one long cloth.",
};

export default EMOJI_E84_FACTS;
