export const EMOJI_E84 = [
  // EASY (18) — near-universal, ~70-95% recognize the emoji's official name
  { slug: "red-heart", name: "Red Heart", emoji: "❤️", level: "easy" },
  { slug: "fire", name: "Fire", emoji: "\u{1F525}", level: "easy" },
  { slug: "thumbs-up", name: "Thumbs Up", emoji: "\u{1F44D}", level: "easy" },
  { slug: "star", name: "Star", emoji: "⭐", level: "easy" },
  { slug: "sun", name: "Sun", emoji: "☀️", level: "easy" },
  { slug: "crown", name: "Crown", emoji: "\u{1F451}", level: "easy" },
  { slug: "skull", name: "Skull", emoji: "\u{1F480}", level: "easy" },
  { slug: "ghost", name: "Ghost", emoji: "\u{1F47B}", level: "easy" },
  { slug: "robot", name: "Robot", emoji: "\u{1F916}", level: "easy" },
  { slug: "alien", name: "Alien", emoji: "\u{1F47D}", level: "easy" },
  { slug: "rainbow", name: "Rainbow", emoji: "\u{1F308}", level: "easy" },
  { slug: "rocket", name: "Rocket", emoji: "\u{1F680}", level: "easy" },
  { slug: "balloon", name: "Balloon", emoji: "\u{1F388}", level: "easy" },
  { slug: "wrapped-gift", name: "Wrapped Gift", emoji: "\u{1F381}", level: "easy" },
  { slug: "trophy", name: "Trophy", emoji: "\u{1F3C6}", level: "easy" },
  { slug: "gem-stone", name: "Gem Stone", emoji: "\u{1F48E}", level: "easy" },
  { slug: "high-voltage", name: "High Voltage", emoji: "⚡", level: "easy" },
  { slug: "direct-hit", name: "Bullseye", emoji: "\u{1F3AF}", level: "easy" },

  // MEDIUM (18) — most have seen it, ~35-70%
  { slug: "kite", name: "Kite", emoji: "\u{1FA81}", level: "medium" },
  { slug: "anchor", name: "Anchor", emoji: "⚓", level: "medium" },
  { slug: "compass", name: "Compass", emoji: "\u{1F9ED}", level: "medium" },
  { slug: "hourglass", name: "Hourglass Not Done", emoji: "⏳", level: "medium" },
  { slug: "telescope", name: "Telescope", emoji: "\u{1F52D}", level: "medium" },
  { slug: "lantern", name: "Red Paper Lantern", emoji: "\u{1F3EE}", level: "medium" },
  { slug: "yo-yo", name: "Yo-Yo", emoji: "\u{1FA80}", level: "medium" },
  { slug: "accordion", name: "Accordion", emoji: "\u{1FA97}", level: "medium" },
  { slug: "banjo", name: "Banjo", emoji: "\u{1FA95}", level: "medium" },
  { slug: "ladder", name: "Ladder", emoji: "\u{1FA9C}", level: "medium" },
  { slug: "broom", name: "Broom", emoji: "\u{1F9F9}", level: "medium" },
  { slug: "shield", name: "Shield", emoji: "\u{1F6E1}️", level: "medium" },
  { slug: "scroll", name: "Scroll", emoji: "\u{1F4DC}", level: "medium" },
  { slug: "amphora", name: "Amphora", emoji: "\u{1F3FA}", level: "medium" },
  { slug: "magic-wand", name: "Magic Wand", emoji: "\u{1FA84}", level: "medium" },
  { slug: "pinata", name: "Piñata", emoji: "\u{1FA85}", level: "medium" },
  { slug: "magnet", name: "Magnet", emoji: "\u{1F9F2}", level: "medium" },
  { slug: "boomerang", name: "Boomerang", emoji: "\u{1FA83}", level: "medium" },

  // HARD (16) — enthusiasts recognize, casual public often doesn't
  { slug: "abacus", name: "Abacus", emoji: "\u{1F9EE}", level: "hard" },
  { slug: "nazar-amulet", name: "Nazar Amulet", emoji: "\u{1F9FF}", level: "hard" },
  { slug: "moai", name: "Moai", emoji: "\u{1F5FF}", level: "hard" },
  { slug: "shinto-shrine", name: "Shinto Shrine", emoji: "⛩️", level: "hard" },
  { slug: "hindu-temple", name: "Hindu Temple", emoji: "\u{1F6D5}", level: "hard" },
  { slug: "hut", name: "Hut", emoji: "\u{1F6D6}", level: "hard" },
  { slug: "gear", name: "Gear", emoji: "⚙️", level: "hard" },
  { slug: "alembic", name: "Alembic", emoji: "⚗️", level: "hard" },
  { slug: "crystal-ball", name: "Crystal Ball", emoji: "\u{1F52E}", level: "hard" },
  { slug: "diya-lamp", name: "Diya Lamp", emoji: "\u{1FA94}", level: "hard" },
  { slug: "ringed-planet", name: "Ringed Planet", emoji: "\u{1FA90}", level: "hard" },
  { slug: "test-tube", name: "Test Tube", emoji: "\u{1F9EA}", level: "hard" },
  { slug: "petri-dish", name: "Petri Dish", emoji: "\u{1F9EB}", level: "hard" },
  { slug: "dna", name: "DNA", emoji: "\u{1F9EC}", level: "hard" },
  { slug: "joystick", name: "Joystick", emoji: "\u{1F579}️", level: "hard" },
  { slug: "yarn", name: "Yarn", emoji: "\u{1F9F6}", level: "hard" },

  // IMPOSSIBLE (18) — genuinely obscure, mostly recent Unicode additions
  { slug: "ninja", name: "Ninja", emoji: "\u{1F977}", level: "impossible" },
  { slug: "anatomical-heart", name: "Anatomical Heart", emoji: "\u{1FAC0}", level: "impossible" },
  { slug: "lungs", name: "Lungs", emoji: "\u{1FAC1}", level: "impossible" },
  { slug: "x-ray", name: "X-Ray", emoji: "\u{1FA7B}", level: "impossible" },
  { slug: "hamsa", name: "Hamsa", emoji: "\u{1FAAC}", level: "impossible" },
  { slug: "mirror-ball", name: "Mirror Ball", emoji: "\u{1FAA9}", level: "impossible" },
  { slug: "jar", name: "Jar", emoji: "\u{1FAD9}", level: "impossible" },
  { slug: "playground-slide", name: "Playground Slide", emoji: "\u{1F6DD}", level: "impossible" },
  { slug: "wheel", name: "Wheel", emoji: "\u{1F6DE}", level: "impossible" },
  { slug: "ring-buoy", name: "Ring Buoy", emoji: "\u{1F6DF}", level: "impossible" },
  { slug: "hair-pick", name: "Hair Pick", emoji: "\u{1FAAE}", level: "impossible" },
  { slug: "flute", name: "Flute", emoji: "\u{1FA88}", level: "impossible" },
  { slug: "hook", name: "Hook", emoji: "\u{1FA9D}", level: "impossible" },
  { slug: "nesting-dolls", name: "Nesting Dolls", emoji: "\u{1FA86}", level: "impossible" },
  { slug: "long-drum", name: "Long Drum", emoji: "\u{1FA98}", level: "impossible" },
  { slug: "low-battery", name: "Low Battery", emoji: "\u{1FAAB}", level: "impossible" },
  { slug: "ballet-shoes", name: "Ballet Shoes", emoji: "\u{1FA70}", level: "impossible" },
  { slug: "sari", name: "Sari", emoji: "\u{1F97B}", level: "impossible" },
];

export default EMOJI_E84;
