export const EMOJI_MOVIES_E36_FACTS = {
  "titanic": "Titanic held the box-office record for 12 years after release.",
  "the-lion-king": "The Lion King's plot draws loosely on Hamlet's story.",
  "frozen": "Frozen was loosely inspired by Andersen's The Snow Queen.",
  "jaws": "Jaws is widely credited as cinema's first true summer blockbuster.",
  "jurassic-park": "Jurassic Park's dinosaur roars were mixed from real animal sounds.",
  "star-wars": "Star Wars was originally released simply as Star Wars in 1977.",
  "home-alone": "Home Alone was the highest-grossing comedy for over a decade.",
  "the-matrix": "The Matrix popularized the visual effect known as 'bullet time.'",
  "finding-nemo": "Finding Nemo was Pixar's best-selling DVD of its era.",
  "toy-story": "Toy Story was the first entirely computer-animated feature film.",
  "the-wizard-of-oz": "The Wizard of Oz's ruby slippers were silver in the original book.",
  "shrek": "Shrek won the first-ever Academy Award for Best Animated Feature.",
  "avatar": "Avatar held the all-time box-office record for a decade.",
  "cast-away": "Cast Away's production paused for a year so Hanks could lose weight.",
  "the-shining": "The Shining's hotel maze set didn't exist in Stephen King's novel.",
  "rocky": "Stallone wrote Rocky's earliest draft in about three days.",
  "e-t": "E.T. overtook Star Wars as the highest-grossing film for a decade.",
  "up": "Up was the first animated film to open the Cannes Film Festival.",
  "inception": "Inception's spinning top ending remains famously ambiguous.",
  "the-godfather": "The Godfather's cat was a stray found on the studio lot that day.",
  "forrest-gump": "Forrest Gump's park bench scenes used a bench that traveled by truck.",
  "gladiator": "Gladiator's Colosseum crowd used digital extras to fill the seats.",
  "black-panther": "Black Panther was the first Marvel film nominated for Best Picture.",
  "the-pianist": "The Pianist's director, like his story's hero, survived the Holocaust.",
  "whiplash": "Whiplash was expanded from a short film shot in three days.",
  "a-quiet-place": "A Quiet Place's cast learned real American Sign Language for filming.",
  "slumdog-millionaire": "Slumdog Millionaire swept eight Academy Awards including Best Picture.",
  "la-la-land": "La La Land was mistakenly announced as Best Picture before correction.",
  "life-of-pi": "Life of Pi used a real tiger alongside CGI for its ocean scenes.",
  "the-revenant": "The Revenant was shot almost entirely using natural light.",
  "moneyball": "Moneyball is based on the real Oakland Athletics' 2002 season.",
  "the-social-network": "The Social Network was scripted before Facebook had one billion users.",
  "no-country-for-old-men": "No Country for Old Men won Best Picture with almost no music score.",
  "there-will-be-blood": "There Will Be Blood was loosely based on Upton Sinclair's novel Oil!.",
  "birdman": "Birdman was edited to look like one continuous unbroken shot.",
  "the-grand-budapest-hotel": "The Grand Budapest Hotel used a real early-1900s German store.",
  "parasite": "Parasite was the first non-English film to win Best Picture.",
  "amelie": "Amélie's Paris café set became a real tourist spot after release.",
  "roma": "Roma was shot in black and white to evoke the director's own memories.",
  "pans-labyrinth": "Pan's Labyrinth's faun costume required hours of daily makeup.",
  "in-the-mood-for-love": "In the Mood for Love took over 15 months of intermittent filming.",
  "city-of-god": "City of God cast many real favela residents as actors.",
  "oldboy": "Oldboy's famous hallway fight was filmed in a single continuous take.",
  "the-lives-of-others": "The Lives of Others is set inside East Germany's Stasi state.",
  "a-separation": "A Separation was Iran's first film to win an Academy Award.",
  "cinema-paradiso": "Cinema Paradiso is a love letter to small-town Italian movie houses.",
  "the-seventh-seal": "The Seventh Seal's chess-with-Death scene became a cultural icon.",
  "wild-strawberries": "Wild Strawberries follows an old professor's single day of reflection.",
  "rashomon": "Rashomon gave its name to the 'Rashomon effect' of clashing accounts.",
  "persona": "Persona's opening montage is one of cinema's most analyzed scenes.",
  "ordet": "Ordet centers on a family torn apart by clashing religious faiths.",
  "the-cranes-are-flying": "The Cranes Are Flying won the Palme d'Or, rare for a Soviet film.",
  "ikiru": "Ikiru's title translates simply to 'to live' in Japanese.",
  "late-spring": "Late Spring follows a father's quiet wish to see his daughter wed.",
  "stalker": "Stalker was filmed at deserted Soviet hydro plants near Tallinn.",
  "mirror": "Mirror weaves the director's own childhood memories into its story.",
  "the-turin-horse": "The Turin Horse is told in only thirty long, unbroken takes.",
  "werckmeister-harmonies": "Werckmeister Harmonies has fewer than forty shots in its runtime.",
  "satantango": "Sátántangó runs over seven hours, one of the longest films ever made.",
  "uncle-boonmee": "Uncle Boonmee won the Palme d'Or blending ghosts with rural Thai life.",
  "tropical-malady": "Tropical Malady splits into two contrasting halves of one story.",
  "the-exterminating-angel": "The Exterminating Angel traps dinner guests who simply cannot leave.",
  "weekend": "Weekend's traffic-jam tracking shot runs nearly eight minutes long.",
  "celine-and-julie-go-boating": "Céline and Julie Go Boating blends mystery with dreamlike logic.",
  "sans-soleil": "Sans Soleil is a essay film narrated through a woman's letters.",
  "la-jetee": "La Jetée is built almost entirely from still photographs, not motion.",
  "come-and-see": "Come and See depicts a boy's descent into wartime horror in Belarus.",
  "the-ascent": "The Ascent follows two Soviet partisans captured behind enemy lines.",
  "man-with-a-movie-camera": "Man with a Movie Camera has no actors, sets, or intertitles at all.",
  "koyaanisqatsi": "Koyaanisqatsi has no dialogue, only imagery and Philip Glass's score.",
  "meshes-of-the-afternoon": "Meshes of the Afternoon was shot on a home-movie budget of under $300.",
};
