// E36 "Guess the Movie by Emoji" — answer = movie title, image = a composed row of emoji
// depicting the title/plot (no posters/stills used, avoiding movie-image copyright entirely).
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
export const EMOJI_MOVIES_E36 = [
  // EASY (18) — globally iconic blockbusters
  { slug: "titanic", name: "Titanic", year: "1997", level: "easy", emoji: ["🚢", "❄️", "💔"] },
  { slug: "the-lion-king", name: "The Lion King", year: "1994", level: "easy", emoji: ["🦁", "👑"] },
  { slug: "frozen", name: "Frozen", year: "2013", level: "easy", emoji: ["❄️", "👸", "⛄"] },
  { slug: "jaws", name: "Jaws", year: "1975", level: "easy", emoji: ["🦈", "🌊"] },
  { slug: "jurassic-park", name: "Jurassic Park", year: "1993", level: "easy", emoji: ["🦖", "🏝️"] },
  { slug: "star-wars", name: "Star Wars", year: "1977", level: "easy", emoji: ["⭐", "⚔️", "🚀"] },
  { slug: "home-alone", name: "Home Alone", year: "1990", level: "easy", emoji: ["🏠", "🧒", "🎄"] },
  { slug: "the-matrix", name: "The Matrix", year: "1999", level: "easy", emoji: ["💊", "🕶️", "🖥️"] },
  { slug: "finding-nemo", name: "Finding Nemo", year: "2003", level: "easy", emoji: ["🐠", "🔍", "🌊"] },
  { slug: "toy-story", name: "Toy Story", year: "1995", level: "easy", emoji: ["🤠", "🚀", "🧸"] },
  { slug: "the-wizard-of-oz", name: "The Wizard of Oz", year: "1939", level: "easy", emoji: ["🌪️", "👠", "🌈"] },
  { slug: "shrek", name: "Shrek", year: "2001", level: "easy", emoji: ["🧌", "🐴", "👸"] },
  { slug: "avatar", name: "Avatar", year: "2009", level: "easy", emoji: ["🌳", "💙", "👽"] },
  { slug: "cast-away", name: "Cast Away", year: "2000", level: "easy", emoji: ["🏝️", "🙋", "🏐"] },
  { slug: "the-shining", name: "The Shining", year: "1980", level: "easy", emoji: ["🏨", "🪓", "👦"] },
  { slug: "rocky", name: "Rocky", year: "1976", level: "easy", emoji: ["🥊", "🏃", "🏆"] },
  { slug: "e-t", name: "E.T. the Extra-Terrestrial", year: "1982", level: "easy", emoji: ["👽", "🚲", "🌙"] },
  { slug: "up", name: "Up", year: "2009", level: "easy", emoji: ["🎈", "🏠", "👴"] },

  // MEDIUM (18)
  { slug: "inception", name: "Inception", year: "2010", level: "medium", emoji: ["🌀", "🛌", "🏙️"] },
  { slug: "the-godfather", name: "The Godfather", year: "1972", level: "medium", emoji: ["🐴", "🔫", "🍝"] },
  { slug: "forrest-gump", name: "Forrest Gump", year: "1994", level: "medium", emoji: ["🏃", "🍫", "📦"] },
  { slug: "gladiator", name: "Gladiator", year: "2000", level: "medium", emoji: ["⚔️", "🏛️", "🦁"] },
  { slug: "black-panther", name: "Black Panther", year: "2018", level: "medium", emoji: ["🐆", "👑", "🌍"] },
  { slug: "the-pianist", name: "The Pianist", year: "2002", level: "medium", emoji: ["🎹", "🇵🇱", "🏃"] },
  { slug: "whiplash", name: "Whiplash", year: "2014", level: "medium", emoji: ["🥁", "😤", "🎼"] },
  { slug: "a-quiet-place", name: "A Quiet Place", year: "2018", level: "medium", emoji: ["🤫", "👂", "👽"] },
  { slug: "slumdog-millionaire", name: "Slumdog Millionaire", year: "2008", level: "medium", emoji: ["💰", "🏙️", "❓"] },
  { slug: "la-la-land", name: "La La Land", year: "2016", level: "medium", emoji: ["🎷", "💃", "🌆"] },
  { slug: "life-of-pi", name: "Life of Pi", year: "2012", level: "medium", emoji: ["🐯", "🚣", "🌊"] },
  { slug: "the-revenant", name: "The Revenant", year: "2015", level: "medium", emoji: ["🐻", "🌲", "🔫"] },
  { slug: "moneyball", name: "Moneyball", year: "2011", level: "medium", emoji: ["⚾", "💵", "📊"] },
  { slug: "the-social-network", name: "The Social Network", year: "2010", level: "medium", emoji: ["💻", "👥", "💔"] },
  { slug: "no-country-for-old-men", name: "No Country for Old Men", year: "2007", level: "medium", emoji: ["🤠", "🔫", "🪙"] },
  { slug: "there-will-be-blood", name: "There Will Be Blood", year: "2007", level: "medium", emoji: ["🛢️", "👨", "🩸"] },
  { slug: "birdman", name: "Birdman", year: "2014", level: "medium", emoji: ["🦅", "🎭", "🚪"] },
  { slug: "the-grand-budapest-hotel", name: "The Grand Budapest Hotel", year: "2014", level: "medium", emoji: ["🏨", "🎩", "📦"] },

  // HARD (18)
  { slug: "parasite", name: "Parasite", year: "2019", level: "hard", emoji: ["🏠", "🕳️", "🐛"] },
  { slug: "amelie", name: "Amélie", year: "2001", level: "hard", emoji: ["👩", "🥄", "🇫🇷"] },
  { slug: "roma", name: "Roma", year: "2018", level: "hard", emoji: ["👩‍🍼", "🚗", "⚫"] },
  { slug: "pans-labyrinth", name: "Pan's Labyrinth", year: "2006", level: "hard", emoji: ["🐐", "🌀", "🗝️"] },
  { slug: "in-the-mood-for-love", name: "In the Mood for Love", year: "2000", level: "hard", emoji: ["🚬", "👘", "💔"] },
  { slug: "city-of-god", name: "City of God", year: "2002", level: "hard", emoji: ["🔫", "🏙️", "🇧🇷"] },
  { slug: "oldboy", name: "Oldboy", year: "2003", level: "hard", emoji: ["🔨", "🐙", "🔒"] },
  { slug: "the-lives-of-others", name: "The Lives of Others", year: "2006", level: "hard", emoji: ["🎧", "🇩🇪", "👂"] },
  { slug: "a-separation", name: "A Separation", year: "2011", level: "hard", emoji: ["💔", "⚖️", "🇮🇷"] },
  { slug: "cinema-paradiso", name: "Cinema Paradiso", year: "1988", level: "hard", emoji: ["🎥", "🇮🇹", "👦"] },
  { slug: "the-seventh-seal", name: "The Seventh Seal", year: "1957", level: "hard", emoji: ["♟️", "💀", "⛪"] },
  { slug: "wild-strawberries", name: "Wild Strawberries", year: "1957", level: "hard", emoji: ["🍓", "🚗", "🇸🇪"] },
  { slug: "rashomon", name: "Rashomon", year: "1950", level: "hard", emoji: ["🗿", "⚔️", "❓"] },
  { slug: "persona", name: "Persona", year: "1966", level: "hard", emoji: ["🎭", "👩", "👩"] },
  { slug: "ordet", name: "Ordet", year: "1955", level: "hard", emoji: ["✝️", "🕊️", "🇩🇰"] },
  { slug: "the-cranes-are-flying", name: "The Cranes Are Flying", year: "1957", level: "hard", emoji: ["🕊️", "🇷🇺", "💔"] },
  { slug: "ikiru", name: "Ikiru", year: "1952", level: "hard", emoji: ["⏳", "👴", "🎡"] },
  { slug: "late-spring", name: "Late Spring", year: "1949", level: "hard", emoji: ["🌸", "🇯🇵", "👨"] },

  // IMPOSSIBLE (17)
  { slug: "stalker", name: "Stalker", year: "1979", level: "impossible", emoji: ["🚪", "☢️", "🌲"] },
  { slug: "mirror", name: "Mirror", year: "1975", level: "impossible", emoji: ["🪞", "🇷🇺", "👦"] },
  { slug: "the-turin-horse", name: "The Turin Horse", year: "2011", level: "impossible", emoji: ["🐎", "🌪️", "⚫"] },
  { slug: "werckmeister-harmonies", name: "Werckmeister Harmonies", year: "2000", level: "impossible", emoji: ["🐳", "🇭🇺", "🌑"] },
  { slug: "satantango", name: "Sátántangó", year: "1994", level: "impossible", emoji: ["🌧️", "🐄", "🇭🇺"] },
  { slug: "uncle-boonmee", name: "Uncle Boonmee Who Can Recall His Past Lives", year: "2010", level: "impossible", emoji: ["👻", "🐒", "🇹🇭"] },
  { slug: "tropical-malady", name: "Tropical Malady", year: "2004", level: "impossible", emoji: ["🐅", "🌴", "💫"] },
  { slug: "the-exterminating-angel", name: "The Exterminating Angel", year: "1962", level: "impossible", emoji: ["🐑", "🚪", "🚫"] },
  { slug: "weekend", name: "Weekend", year: "1967", level: "impossible", emoji: ["🚗", "💥", "🇫🇷"] },
  { slug: "celine-and-julie-go-boating", name: "Céline and Julie Go Boating", year: "1974", level: "impossible", emoji: ["🚣", "🎩", "🔮"] },
  { slug: "sans-soleil", name: "Sans Soleil", year: "1983", level: "impossible", emoji: ["📷", "🌍", "💭"] },
  { slug: "la-jetee", name: "La Jetée", year: "1962", level: "impossible", emoji: ["📷", "⏳", "✈️"] },
  { slug: "come-and-see", name: "Come and See", year: "1985", level: "impossible", emoji: ["🔥", "👦", "🇧🇾"] },
  { slug: "the-ascent", name: "The Ascent", year: "1977", level: "impossible", emoji: ["❄️", "⚔️", "🇧🇾"] },
  { slug: "man-with-a-movie-camera", name: "Man with a Movie Camera", year: "1929", level: "impossible", emoji: ["📷", "🎬", "🏭"] },
  { slug: "koyaanisqatsi", name: "Koyaanisqatsi", year: "1982", level: "impossible", emoji: ["🏙️", "⏩", "🌄"] },
  { slug: "meshes-of-the-afternoon", name: "Meshes of the Afternoon", year: "1943", level: "impossible", emoji: ["🔑", "🪞", "🌙"] },
];
