// One verified "did you know" fact per empire in EMPIRES_E96, keyed by slug.
export const EMPIRES_E96_FACTS = {
  // ---- easy ----
  "roman-empire": "At its height under Trajan in 117 AD, the Roman Empire covered about 5 million square kilometers across three continents.",
  "british-empire": "The British Empire once covered about a quarter of Earth's land and population, inspiring the phrase 'the empire on which the sun never sets.'",
  "ottoman-empire": "The Ottoman Empire lasted over 600 years, from 1299 to 1922, ruled the whole time by a single dynasty founded by Osman I.",
  "mongol-empire": "The Mongol Empire became the largest contiguous land empire in history, stretching from Korea to Eastern Europe under Genghis Khan's successors.",
  "ancient-egypt": "Ancient Egyptian civilization lasted over 3,000 years, and at its New Kingdom peak its rulers pushed control deep into Nubia and the Levant.",
  "napoleonic-france": "At its 1811 peak, Napoleon's French Empire directly controlled or dominated most of continental Europe, from Spain to the Polish border.",
  "spanish-empire": "The Spanish Empire was among the first ever called 'the empire on which the sun never sets,' spanning most of the Americas and the Philippines.",
  "macedonian-empire": "Alexander the Great built his empire in just over a decade, reportedly never losing a battle before his death at 32 in Babylon.",
  "qing-dynasty": "China's Qing Dynasty roughly tripled the territory of the preceding Ming Dynasty, adding Tibet, Xinjiang, Mongolia, and Taiwan.",
  "russian-empire": "By 1895, the Russian Empire covered roughly a sixth of the world's land, spanning eleven time zones from Poland to the Pacific.",
  "japanese-empire": "At its 1942 wartime peak, the Empire of Japan controlled territory stretching from the Aleutian Islands to the edge of Australia's coast.",
  "portuguese-empire": "Portugal's colonial empire lasted almost 600 years, making it one of the longest-lived colonial empires in world history.",
  "french-colonial-empire": "At its 1920s peak, France's colonial empire was the second-largest in the world, spanning territory across Africa and Southeast Asia.",
  "dutch-empire": "During its 17th-century Golden Age, the small Dutch Republic ran trade colonies stretching from New Amsterdam (New York) to Indonesia.",
  "german-empire": "Germany's colonial empire, seized largely in the 1880s 'Scramble for Africa,' was entirely stripped away after its World War One defeat.",
  "assyrian-empire": "The Neo-Assyrian Empire briefly conquered Egypt in the 7th century BC, becoming one of history's first empires to rule both the Nile and Mesopotamia.",
  "babylonian-empire": "King Nebuchadnezzar II's Neo-Babylonian Empire is remembered for destroying Jerusalem's temple and for the legendary Hanging Gardens.",
  "mughal-empire": "Under Emperor Aurangzeb around 1700, the Mughal Empire reached its largest extent, ruling nearly the entire Indian subcontinent.",

  // ---- medium ----
  "byzantine-empire": "Emperor Justinian I briefly reconquered Italy, North Africa, and part of Spain in the 6th century, restoring much of the old Roman Mediterranean.",
  "achaemenid-persian-empire": "The Achaemenid Persian Empire's Royal Road and relay riders are said to have inspired the modern US Postal Service's unofficial motto.",
  "aztec-empire": "The Aztec Empire had no wheeled transport or beasts of burden, yet built the lake-city capital Tenochtitlan, home to over 200,000 people.",
  "inca-empire": "The Inca Empire built over 30,000 kilometers of roads through the Andes without the wheel, iron tools, or a system of writing.",
  "mali-empire": "Mali's Mansa Musa gave away so much gold on his 1324 pilgrimage to Mecca that he reportedly caused years of inflation in Cairo.",
  "holy-roman-empire": "Voltaire famously quipped the Holy Roman Empire was 'neither holy, nor Roman, nor an empire' — yet it lasted nearly a thousand years.",
  "umayyad-caliphate": "At its height in 750 AD, the Umayyad Caliphate was the largest empire the world had yet seen, stretching from Spain to India's border.",
  "abbasid-caliphate": "The Abbasid capital Baghdad became a global center of learning, home to a great research academy known as the House of Wisdom.",
  "han-dynasty": "China's Han Dynasty gave its name to the Han ethnic majority and opened Silk Road trade routes linking China to Central Asia and Rome.",
  "gupta-empire": "India's Gupta Empire is often called a golden age of science, home to astronomer Aryabhata, who helped pioneer the use of zero and place-value numerals.",
  "safavid-empire": "The Safavid Empire made Shia Islam Iran's state religion, a decision that still shapes Iran's religious identity centuries later.",
  "austro-hungarian-empire": "The Austro-Hungarian Empire was a rare 'dual monarchy,' with one emperor presiding over two separate parliaments and legal systems.",
  "zulu-kingdom": "King Shaka transformed the small Zulu clan into a powerful kingdom by introducing new weapons and battle tactics like the 'buffalo horns' formation.",
  "timurid-empire": "Conqueror Timur (Tamerlane) built an empire from Central Asia to India, then died in 1405 while marching to invade Ming China.",
  "sassanid-empire": "The Sassanid Persian Empire ruled for over 400 years and was considered Rome and Byzantium's equal, fighting them in wars for centuries.",
  "ethiopian-empire": "Ethiopia under Menelik II defeated an invading Italian army at the 1896 Battle of Adwa, remaining the only African state to repel colonization.",
  "kingdom-of-kush": "The Kingdom of Kush once conquered and ruled ancient Egypt itself, becoming Egypt's 25th dynasty of so-called 'Black Pharaohs' around 700 BC.",
  "carthaginian-empire": "Carthage was a Phoenician trading empire whose general Hannibal famously marched war elephants across the Alps to invade Roman Italy.",

  // ---- hard ----
  "khmer-empire": "The Khmer Empire built Angkor Wat, widely cited as the largest religious monument on Earth by land area, inside a capital bigger than medieval Paris.",
  "songhai-empire": "At its 16th-century peak, the Songhai Empire was the largest empire in West African history, controlling the fabled trading city of Timbuktu.",
  "maratha-empire": "The Maratha Empire grew from guerrilla warfare against the Mughals into briefly controlling nearly a third of the Indian subcontinent by 1760.",
  "seleucid-empire": "Formed from Alexander the Great's shattered empire, the Seleucid Empire once stretched from modern Turkey to the borders of India.",
  "visigothic-kingdom": "The Visigothic Kingdom ruled most of Spain and Portugal for nearly 300 years, until the Umayyad conquest of 711 AD ended it.",
  "silla-korea": "Unified Silla became the first kingdom to rule most of the Korean Peninsula under one government, after allying with China's Tang Dynasty.",
  "ptolemaic-egypt": "Founded by one of Alexander the Great's own generals, Ptolemaic Egypt ended with Cleopatra VII, its last and most famous ruler.",
  "ghana-empire": "The medieval Ghana Empire grew rich taxing trans-Saharan gold and salt caravans, even though it never actually touched modern Ghana.",
  "srivijaya-empire": "The maritime Srivijaya Empire controlled the Strait of Malacca for centuries, taxing much of the trade passing between India and China.",
  "majapahit-empire": "Java's Majapahit Empire is considered Indonesia's largest pre-colonial state, with some accounts claiming influence across the whole archipelago.",
  "bulgarian-empire": "Under Tsar Simeon I around 915 AD, the First Bulgarian Empire stretched from near the Adriatic Sea to the Black Sea, rivaling Byzantium.",
  "seljuk-empire": "The Great Seljuk Empire's 1071 victory at Manzikert opened Anatolia to Turkish settlement, reshaping a region later home to the Ottomans.",
  "kingdom-of-aksum": "Ancient Aksum minted its own gold coinage and was one of the first major kingdoms to officially adopt Christianity, around 330 AD.",
  "toltec-empire": "The Toltec civilization of central Mexico was so revered that later Aztec rulers claimed descent from Toltec kings to legitimize their power.",
  "hittite-empire": "The Hittite Empire, among the first to master ironworking, fought Egypt's Ramesses II at Kadesh in one of history's earliest known peace treaties.",
  "benin-empire": "The Benin Empire's royal court produced thousands of intricate brass and bronze plaques, looted by a British military expedition in 1897.",

  // ---- impossible ----
  "kanem-bornu-empire": "Centered on Lake Chad, the Kanem-Bornu Empire lasted roughly a thousand years under one dynasty, among the longest-lived states in African history.",
  "ghaznavid-empire": "The Ghaznavid Empire's Mahmud of Ghazni led around 17 military campaigns into northern India, spreading Persianate Islamic culture across the region.",
  "chola-empire": "The Chola Empire built a navy strong enough to conquer Sri Lanka and launch overseas raids against the Srivijaya Empire in distant Sumatra.",
  "vijayanagara-empire": "Visiting Portuguese and Persian travelers described the Vijayanagara Empire's capital city as larger and richer than Rome.",
  "mutapa-empire": "The Mutapa Empire grew out of the gold-trading civilization that built Great Zimbabwe, one of sub-Saharan Africa's largest ancient stone complexes.",
  "wari-empire": "Peru's Wari Empire predated the Inca by centuries and built an extensive road network that the later Inca Empire adapted and expanded on.",
  "tiwanaku-empire": "The Tiwanaku Empire thrived over 3,800 meters above sea level near Lake Titicaca, using raised-field farming to survive the harsh altiplano.",
  "funan-kingdom": "The kingdom of Funan built the Mekong Delta port of Oc Eo, where archaeologists have found Roman coins showing trade links across Eurasia.",
  "oyo-empire": "The Yoruba Oyo Empire built its power on savanna cavalry warfare, even though tsetse flies made horse-breeding difficult across West Africa.",
  "ashanti-empire": "The Ashanti Empire fought several wars against the British over control of a Golden Stool believed to hold the soul of the Ashanti nation.",
  "kingdom-of-kongo": "The Kingdom of Kongo's king converted to Christianity in 1491 and exchanged ambassadors and letters directly with the kings of Portugal.",
  "rashtrakuta-empire": "A medieval Arab traveler once ranked the Rashtrakuta Empire among the world's four greatest states, alongside Baghdad, Byzantium, and Tang China.",
  "pala-empire": "The Buddhist Pala Empire of Bengal built Somapura Mahavihara, once one of the largest Buddhist monasteries in the ancient world.",
  "xiongnu-confederation": "The nomadic Xiongnu Confederation was such a persistent threat to Han China that it helped drive construction of the early Great Wall.",
  "avar-khaganate": "The Avar Khaganate ruled Central Europe for over two centuries until Charlemagne's Frankish armies finally destroyed it in the 790s.",
  "tui-tonga-empire": "The Tu'i Tonga Empire projected power across the Pacific using huge double-hulled canoes capable of carrying up to 200 warriors.",
  "gokturk-khaganate": "The Gokturk Khaganate left some of the earliest known Turkic-language writing, carved onto stone monuments called the Orkhon inscriptions.",
  "sokoto-caliphate": "The Sokoto Caliphate, founded after an 1804 jihad led by scholar Usman dan Fodio, became one of Africa's largest 19th-century states.",
};
