export const EVCARS_E70_FACTS = {
  "tesla-model-s": "Its 2012 launch helped prove EVs could be genuinely desirable.",
  "tesla-model-3": "Once was the world's best-selling electric car.",
  "tesla-model-x": "Known for its distinctive falcon-wing rear doors.",
  "tesla-model-y": "Built on the same platform as the Tesla Model 3.",
  "tesla-cybertruck": "Its stainless steel body is designed to resist dents and rust.",
  "nissan-leaf": "One of the first mass-market electric cars, launched in 2010.",
  "bmw-i3": "Its body was built largely from carbon fiber reinforced plastic.",
  "chevrolet-bolt-ev": "One of the first affordable EVs with over 200 miles of range.",
  "porsche-taycan": "Porsche's first all-electric production car.",
  "volkswagen-id4": "Built on VW's dedicated MEB electric vehicle platform.",
  "ford-mustang-mach-e": "Borrows the Mustang name for an electric SUV, not a coupe.",
  "audi-e-tron-gt": "Shares its platform with the Porsche Taycan.",
  "hyundai-ioniq-5": "Its boxy retro design nods to the 1970s Hyundai Pony.",
  "kia-ev6": "Shares its E-GMP platform with the Hyundai Ioniq 5.",
  "rivian-r1t": "One of the first all-electric pickup trucks sold in the US.",
  "mercedes-benz-eqs": "An electric flagship sedan built on a dedicated EV platform.",
  "jaguar-i-pace": "Jaguar's first all-electric production model.",
  "volkswagen-e-golf": "An electric version of VW's popular Golf hatchback.",

  "tesla-roadster": "Tesla's first car, built on a modified Lotus Elise chassis.",
  "rivian-r1s": "A three-row electric SUV sharing its platform with the R1T.",
  "lucid-air": "Once held the record for longest EV range on a single charge.",
  "polestar-2": "Built by a brand spun off from Volvo and Geely.",
  "bmw-ix": "One of BMW's first EVs built on a dedicated electric platform.",
  "audi-e-tron": "Audi's first mass-production all-electric SUV.",
  "volvo-xc40-recharge": "Volvo's first fully electric production model.",
  "hyundai-ioniq-6": "Its streamlined shape was designed to cut wind resistance.",
  "kia-ev9": "A three-row electric SUV, one of Kia's largest EVs.",
  "chevrolet-silverado-ev": "An electric version of Chevrolet's full-size pickup truck.",
  "ford-f-150-lightning": "An electric version of America's best-selling pickup truck.",
  "gmc-hummer-ev": "Revived the Hummer name as an electric pickup and SUV.",
  "cadillac-lyriq": "Cadillac's first dedicated all-electric model.",
  "genesis-gv60": "Hyundai's luxury brand's first dedicated electric model.",
  "byd-seal": "A Chinese electric sedan positioned against the Tesla Model 3.",
  "mini-cooper-se": "An electric version of the classic Mini Cooper hatchback.",
  "smart-eq-fortwo": "An electric version of Smart's tiny two-seat city car.",
  "renault-zoe": "Once one of Europe's best-selling electric cars.",

  "nio-et7": "A Chinese electric sedan offering swappable battery packs.",
  "xpeng-p7": "A Chinese electric sedan known for its long, sloped roofline.",
  "byd-han": "A Chinese electric sedan named after the Han dynasty.",
  "polestar-3": "Polestar's first electric SUV model.",
  "lucid-gravity": "Lucid's first electric SUV, following the Air sedan.",
  "fisker-ocean": "An electric SUV from a startup that later filed for bankruptcy.",
  "vinfast-vf8": "An electric SUV from Vietnam's first major car manufacturer.",
  "genesis-gv70-electrified": "An all-electric version of Genesis's GV70 SUV.",
  "volvo-ex30": "One of Volvo's smallest and most affordable electric models.",
  "volvo-c40-recharge": "A coupe-styled electric SUV, sold only as an EV.",
  "chevrolet-blazer-ev": "An electric SUV reviving the Blazer nameplate.",
  "dodge-charger-daytona": "An all-electric muscle car with a simulated exhaust sound.",
  "rivian-r2": "A smaller, more affordable electric SUV than the R1S.",
  "zeekr-001": "A Chinese electric shooting-brake from a Geely-owned brand.",
  "smart-1": "Smart's first SUV, built after its shift under new ownership.",
  "maxus-mifa-9": "An electric minivan from a Chinese-owned commercial brand.",

  "ora-good-cat": "A Chinese electric hatchback with a retro, round-headlight design.",
  "mg4-electric": "An electric hatchback from the revived MG brand, now Chinese-owned.",
  "byd-atto-3": "A compact electric SUV exported by BYD to global markets.",
  "byd-dolphin": "A compact electric hatchback named after a sea animal.",
  "nissan-ariya": "Nissan's electric SUV, built after the pioneering Leaf.",
  "toyota-bz4x": "Toyota's first dedicated all-electric SUV.",
  "subaru-solterra": "Co-developed with Toyota, sharing its platform with the bZ4X.",
  "mazda-mx-30": "Mazda's first mass-production electric vehicle.",
  "honda-e": "A compact EV known for its retro, rounded city-car design.",
  "fiat-500e": "An electric version of Fiat's compact 500 city car.",
  "renault-megane-e-tech": "An electric hatchback version of Renault's Megane.",
  "peugeot-e-208": "An electric version of Peugeot's popular 208 hatchback.",
  "opel-corsa-e": "An electric version of Opel's long-running Corsa hatchback.",
  "skoda-enyaq": "Skoda's first dedicated electric SUV.",
  "cupra-born": "An electric hatchback from VW's sporty Spanish brand, Cupra.",
  "ds-3-crossback-e-tense": "An electric version of DS Automobiles' compact SUV.",
  "citroen-e-c4": "An electric version of Citroën's C4 hatchback.",
  "aptera": "A three-wheeled EV designed to run partly on solar power.",
};

export default EVCARS_E70_FACTS;
