// E70 "Guess the Electric Car" — 70 real modern EVs, second of 5 planned car-themed episodes.
// Distinct sub-theme from E07 (car brand logos), E53 (pre-EV-era classic/iconic cars), and E69
// (modern gas/hybrid supercars — this episode is exclusively battery-electric vehicles).
// image: evcars70/<slug>.jpg | wiki: exact Wikipedia article title | Zero Israel content (standing hard rule).
export const EVCARS_E70 = [
  // EASY (18)
  { slug: "tesla-model-s", name: "Tesla Model S", wiki: "Tesla Model S", level: "easy" },
  { slug: "tesla-model-3", name: "Tesla Model 3", wiki: "Tesla Model 3", level: "easy" },
  { slug: "tesla-model-x", name: "Tesla Model X", wiki: "Tesla Model X", level: "easy" },
  { slug: "tesla-model-y", name: "Tesla Model Y", wiki: "Tesla Model Y", level: "easy" },
  { slug: "tesla-cybertruck", name: "Tesla Cybertruck", wiki: "Tesla Cybertruck", level: "easy" },
  { slug: "nissan-leaf", name: "Nissan Leaf", wiki: "Nissan Leaf", level: "easy" },
  { slug: "bmw-i3", name: "BMW i3", wiki: "BMW i3", level: "easy" },
  { slug: "chevrolet-bolt-ev", name: "Chevrolet Bolt EV", wiki: "Chevrolet Bolt", level: "easy" },
  { slug: "porsche-taycan", name: "Porsche Taycan", wiki: "Porsche Taycan", level: "easy" },
  { slug: "volkswagen-id4", name: "Volkswagen ID.4", wiki: "Volkswagen ID.4", level: "easy" },
  { slug: "ford-mustang-mach-e", name: "Ford Mustang Mach-E", wiki: "Ford Mustang Mach-E", level: "easy" },
  { slug: "audi-e-tron-gt", name: "Audi e-tron GT", wiki: "Audi e-tron GT", level: "easy" },
  { slug: "hyundai-ioniq-5", name: "Hyundai Ioniq 5", wiki: "Hyundai Ioniq 5", level: "easy" },
  { slug: "kia-ev6", name: "Kia EV6", wiki: "Kia EV6", level: "easy" },
  { slug: "rivian-r1t", name: "Rivian R1T", wiki: "Rivian R1T", level: "easy" },
  { slug: "mercedes-benz-eqs", name: "Mercedes-Benz EQS", wiki: "Mercedes-Benz EQS", level: "easy" },
  { slug: "jaguar-i-pace", name: "Jaguar I-Pace", wiki: "Jaguar I-Pace", level: "easy" },
  { slug: "volkswagen-e-golf", name: "Volkswagen e-Golf", wiki: "Volkswagen e-Golf", level: "easy" },

  // MEDIUM (18)
  { slug: "tesla-roadster", name: "Tesla Roadster", wiki: "Tesla Roadster (2008)", level: "medium" },
  { slug: "rivian-r1s", name: "Rivian R1S", wiki: "Rivian R1S", level: "medium" },
  { slug: "lucid-air", name: "Lucid Air", wiki: "Lucid Air", level: "medium" },
  { slug: "polestar-2", name: "Polestar 2", wiki: "Polestar 2", level: "medium" },
  { slug: "bmw-ix", name: "BMW iX", wiki: "BMW iX", level: "medium" },
  { slug: "audi-e-tron", name: "Audi e-tron", wiki: "Audi e-tron (automobile)", level: "medium" },
  { slug: "volvo-xc40-recharge", name: "Volvo XC40 Recharge Pure Electric", wiki: "Volvo XC40", level: "medium" },
  { slug: "hyundai-ioniq-6", name: "Hyundai Ioniq 6", wiki: "Hyundai Ioniq 6", level: "medium" },
  { slug: "kia-ev9", name: "Kia EV9", wiki: "Kia EV9", level: "medium" },
  { slug: "chevrolet-silverado-ev", name: "Chevrolet Silverado EV", wiki: "Chevrolet Silverado EV", level: "medium" },
  { slug: "ford-f-150-lightning", name: "Ford F-150 Lightning", wiki: "Ford F-150 Lightning", level: "medium" },
  { slug: "gmc-hummer-ev", name: "GMC Hummer EV", wiki: "GMC Hummer EV", level: "medium" },
  { slug: "cadillac-lyriq", name: "Cadillac Lyriq", wiki: "Cadillac Lyriq", level: "medium" },
  { slug: "genesis-gv60", name: "Genesis GV60", wiki: "Genesis GV60", level: "medium" },
  { slug: "byd-seal", name: "BYD Seal", wiki: "BYD Seal", level: "medium" },
  { slug: "mini-cooper-se", name: "Mini Cooper SE", wiki: "Mini Electric", level: "medium" },
  { slug: "smart-eq-fortwo", name: "Smart EQ Fortwo", wiki: "Smart Fortwo", level: "medium" },
  { slug: "renault-zoe", name: "Renault Zoe", wiki: "Renault Zoe", level: "medium" },

  // HARD (16)
  { slug: "nio-et7", name: "NIO ET7", wiki: "NIO ET7", level: "hard" },
  { slug: "xpeng-p7", name: "XPeng P7", wiki: "XPeng P7", level: "hard" },
  { slug: "byd-han", name: "BYD Han", wiki: "BYD Han", level: "hard" },
  { slug: "polestar-3", name: "Polestar 3", wiki: "Polestar 3", level: "hard" },
  { slug: "lucid-gravity", name: "Lucid Gravity", wiki: "Lucid Gravity", level: "hard" },
  { slug: "fisker-ocean", name: "Fisker Ocean", wiki: "Fisker Ocean", level: "hard" },
  { slug: "vinfast-vf8", name: "VinFast VF8", wiki: "VinFast VF8", level: "hard" },
  { slug: "genesis-gv70-electrified", name: "Genesis GV70 Electrified", wiki: "Genesis GV70", level: "hard" },
  { slug: "volvo-ex30", name: "Volvo EX30", wiki: "Volvo EX30", level: "hard" },
  { slug: "volvo-c40-recharge", name: "Volvo C40 Recharge", wiki: "Volvo C40 Recharge", level: "hard" },
  { slug: "chevrolet-blazer-ev", name: "Chevrolet Blazer EV", wiki: "Chevrolet Blazer EV", level: "hard" },
  { slug: "dodge-charger-daytona", name: "Dodge Charger Daytona", wiki: "Dodge Charger Daytona (2024)", level: "hard" },
  { slug: "rivian-r2", name: "Rivian R2", wiki: "Rivian R2", level: "hard" },
  { slug: "zeekr-001", name: "Zeekr 001", wiki: "Zeekr 001", level: "hard" },
  { slug: "smart-1", name: "Smart #1", wiki: "Smart 1", level: "hard" },
  { slug: "maxus-mifa-9", name: "Maxus Mifa 9", wiki: "Maxus G90", level: "hard" },

  // IMPOSSIBLE (18)
  { slug: "ora-good-cat", name: "Ora Good Cat", wiki: "Ora Good Cat", level: "impossible" },
  { slug: "mg4-electric", name: "MG4 Electric", wiki: "MG4 Electric", level: "impossible" },
  { slug: "byd-atto-3", name: "BYD Atto 3", wiki: "BYD Atto 3", level: "impossible" },
  { slug: "byd-dolphin", name: "BYD Dolphin", wiki: "BYD Dolphin", level: "impossible" },
  { slug: "nissan-ariya", name: "Nissan Ariya", wiki: "Nissan Ariya", level: "impossible" },
  { slug: "toyota-bz4x", name: "Toyota bZ4X", wiki: "Toyota bZ4X", level: "impossible" },
  { slug: "subaru-solterra", name: "Subaru Solterra", wiki: "Subaru Solterra", level: "impossible" },
  { slug: "mazda-mx-30", name: "Mazda MX-30", wiki: "Mazda MX-30", level: "impossible" },
  { slug: "honda-e", name: "Honda e", wiki: "Honda E", level: "impossible" },
  { slug: "fiat-500e", name: "Fiat 500e", wiki: "Fiat 500e", level: "impossible" },
  { slug: "renault-megane-e-tech", name: "Renault Megane E-Tech", wiki: "Renault Megane E-Tech Electric", level: "impossible" },
  { slug: "peugeot-e-208", name: "Peugeot e-208", wiki: "Peugeot e-208", level: "impossible" },
  { slug: "opel-corsa-e", name: "Opel Corsa-e", wiki: "Opel Corsa-e", level: "impossible" },
  { slug: "skoda-enyaq", name: "Skoda Enyaq", wiki: "Škoda Enyaq iV", level: "impossible" },
  { slug: "cupra-born", name: "Cupra Born", wiki: "Cupra Born", level: "impossible" },
  { slug: "ds-3-crossback-e-tense", name: "DS 3 Crossback E-Tense", wiki: "DS 3 Crossback", level: "impossible" },
  { slug: "citroen-e-c4", name: "Citroën ë-C4", wiki: "Citroën C4 (2020)", level: "impossible" },
  { slug: "aptera", name: "Aptera", wiki: "Aptera Motors", level: "impossible" },
];

export default EVCARS_E70;
