export const FAMOUS_CASTLES_E32_FACTS = {
  "neuschwanstein-castle": "Neuschwanstein inspired Disney's Sleeping Beauty Castle design.",
  "windsor-castle": "Windsor is the world's oldest and largest inhabited castle.",
  "edinburgh-castle": "Edinburgh Castle sits atop an extinct volcanic rock.",
  "chateau-de-chambord": "Chambord has 426 rooms but was rarely lived in by its builder.",
  "himeji-castle": "Himeji Castle survived WWII bombing that destroyed the city around it.",
  "prague-castle": "Prague Castle is the largest ancient castle complex in the world.",
  "alhambra": "The Alhambra's name means 'the red one' in Arabic.",
  "bran-castle": "Bran Castle is marketed as Dracula's, though Vlad never lived there.",
  "osaka-castle": "Osaka Castle's current tower is a 1931 concrete reconstruction.",
  "tower-of-london": "The Tower of London has housed the Crown Jewels since the 1600s.",
  "mont-saint-michel": "Mont-Saint-Michel becomes an island only at high tide.",
  "chateau-de-chenonceau": "Chenonceau is the only French château built directly over a river.",
  "warwick-castle": "Warwick Castle began as a wooden fort built by William the Conqueror.",
  "malbork-castle": "Malbork Castle is the largest castle in the world by land area.",
  "hohenzollern-castle": "Hohenzollern Castle was the ancestral seat of Prussia's royal family.",
  "alcazar-of-segovia": "The Alcázar of Segovia inspired Disney's Cinderella Castle.",
  "carcassonne": "Carcassonne's double walls stretch nearly 3 kilometers.",
  "kronborg-castle": "Kronborg Castle is the setting for Shakespeare's Hamlet.",
  "stirling-castle": "Stirling Castle changed hands 8 times during Scotland's wars.",
  "caernarfon-castle": "Caernarfon Castle hosts the investiture of the Prince of Wales.",
  "conwy-castle": "Conwy Castle took Edward I only about 4 years to build.",
  "dover-castle": "Dover Castle is nicknamed the Key to England.",
  "leeds-castle": "Leeds Castle sits on two islands within its own lake.",
  "blarney-castle": "Kissing the Blarney Stone supposedly grants the gift of eloquence.",
  "kilkenny-castle": "Kilkenny Castle was home to the Butler family for 500 years.",
  "peles-castle": "Peleș Castle was Romania's first castle wired for electricity.",
  "wawel-castle": "Wawel Castle was the residence of Polish kings for 500 years.",
  "burg-eltz": "Burg Eltz has never been destroyed in over 800 years.",
  "chateau-de-amboise": "Leonardo da Vinci is buried in a chapel at Amboise.",
  "hohensalzburg-fortress": "Hohensalzburg is one of Europe's largest preserved fortresses.",
  "chillon-castle": "Chillon Castle inspired Byron's poem 'The Prisoner of Chillon'.",
  "alnwick-castle": "Alnwick Castle was filmed as Hogwarts in early Harry Potter films.",
  "highclere-castle": "Highclere Castle is the real-life setting of Downton Abbey.",
  "nagoya-castle": "Nagoya Castle's roof is topped with golden shachihoko statues.",
  "matsumoto-castle": "Matsumoto Castle is nicknamed the Crow Castle for its black walls.",
  "hearst-castle": "Hearst Castle was built for newspaper tycoon William Randolph Hearst.",
  "corvin-castle": "Corvin Castle was the stronghold of the Hunyadi noble family.",
  "spis-castle": "Spiš Castle is one of the largest castle complexes in Central Europe.",
  "bojnice-castle": "Bojnice Castle was rebuilt in a French romantic style around 1900.",
  "trakai-island-castle": "Trakai Castle sits on an island in Lake Galvė.",
  "marksburg-castle": "Marksburg is the only Rhine hilltop castle never destroyed.",
  "chateau-de-pierrefonds": "Pierrefonds was restored in the 1800s under Napoleon III.",
  "chateau-d-angers": "Château d'Angers houses the medieval Apocalypse Tapestry.",
  "predjama-castle": "Predjama Castle is built into the mouth of a cave.",
  "eilean-donan-castle": "Eilean Donan sits on its own tiny island in a Scottish loch.",
  "cardiff-castle": "Cardiff Castle hides a Roman fort beneath its Norman keep.",
  "bodiam-castle": "Bodiam Castle was built for coastal defense in the 1300s.",
  "arundel-castle": "Arundel Castle has housed the Dukes of Norfolk for centuries.",
  "castel-sant-angelo": "Castel Sant'Angelo began as a mausoleum for Emperor Hadrian.",
  "castel-del-monte": "Castel del Monte has no moat, drawbridge, or defensive walls.",
  "castello-sforzesco": "Leonardo da Vinci helped design Castello Sforzesco's defenses.",
  "alcazar-of-toledo": "The Alcázar of Toledo was rebuilt after its 1936 destruction.",
  "alcazar-of-seville": "The Alcázar of Seville is Europe's oldest royal palace still in use.",
  "casa-loma": "Casa Loma was Canada's largest private residence when built.",
  "egeskov-castle": "Egeskov Castle is built almost entirely on wooden piles in a lake.",
  "frederiksborg-castle": "Frederiksborg now houses Denmark's National History Museum.",
  "sigmaringen-castle": "Sigmaringen Castle sits on a cliff above the Danube valley.",
  "wartburg-castle": "Martin Luther translated the Bible into German at Wartburg.",
  "karlstejn-castle": "Karlštejn Castle once held the Bohemian crown jewels.",
  "ksiaz-castle": "Książ Castle is Poland's third-largest castle.",
  "ogrodzieniec-castle": "Ogrodzieniec sits on limestone rocks called the Eagles' Nests.",
  "chapultepec-castle": "Chapultepec is the only royal castle in the Americas.",
  "cape-coast-castle": "Cape Coast Castle was a major hub of the Atlantic slave trade.",
  "elmina-castle": "Elmina Castle is the oldest European building in sub-Saharan Africa.",
  "citadel-of-qaitbay": "Qaitbay's citadel sits where the Alexandria Lighthouse once stood.",
  "aleppo-citadel": "Aleppo's Citadel hill has been inhabited since the 3rd millennium BC.",
  "masyaf-castle": "Masyaf Castle was a stronghold of the Assassins under Rashid al-Din.",
  "amber-fort": "Amber Fort is built from pale yellow and pink sandstone.",
  "mehrangarh-fort": "Mehrangarh Fort rises about 400 feet above Jodhpur.",
  "kumamoto-castle": "Kumamoto Castle's walls curve outward to repel climbers.",
  "shuri-castle": "Shuri Castle burned down again in 2019 and is being rebuilt.",
};
