// E32 "Guess the Castle" — answer = castle/fortress name, image = real photo of the castle.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
export const FAMOUS_CASTLES_E32 = [
  // EASY (18) — globally iconic castles
  { slug: "neuschwanstein-castle", name: "Neuschwanstein Castle", country: "Germany", level: "easy" },
  { slug: "windsor-castle", name: "Windsor Castle", country: "England", level: "easy" },
  { slug: "edinburgh-castle", name: "Edinburgh Castle", country: "Scotland", level: "easy" },
  { slug: "chateau-de-chambord", name: "Château de Chambord", country: "France", level: "easy" },
  { slug: "himeji-castle", name: "Himeji Castle", country: "Japan", level: "easy" },
  { slug: "prague-castle", name: "Prague Castle", country: "Czech Republic", level: "easy" },
  { slug: "alhambra", name: "Alhambra", country: "Spain", level: "easy" },
  { slug: "bran-castle", name: "Bran Castle", country: "Romania", level: "easy" },
  { slug: "osaka-castle", name: "Osaka Castle", country: "Japan", level: "easy" },
  { slug: "tower-of-london", name: "Tower of London", country: "England", level: "easy" },
  { slug: "mont-saint-michel", name: "Mont-Saint-Michel", country: "France", level: "easy" },
  { slug: "chateau-de-chenonceau", name: "Château de Chenonceau", country: "France", level: "easy" },
  { slug: "warwick-castle", name: "Warwick Castle", country: "England", level: "easy" },
  { slug: "malbork-castle", name: "Malbork Castle", country: "Poland", level: "easy" },
  { slug: "hohenzollern-castle", name: "Hohenzollern Castle", country: "Germany", level: "easy" },
  { slug: "alcazar-of-segovia", name: "Alcázar of Segovia", country: "Spain", level: "easy" },
  { slug: "carcassonne", name: "Carcassonne", country: "France", level: "easy" },
  { slug: "kronborg-castle", name: "Kronborg Castle", country: "Denmark", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "stirling-castle", name: "Stirling Castle", country: "Scotland", level: "medium" },
  { slug: "caernarfon-castle", name: "Caernarfon Castle", country: "Wales", level: "medium" },
  { slug: "conwy-castle", name: "Conwy Castle", country: "Wales", level: "medium" },
  { slug: "dover-castle", name: "Dover Castle", country: "England", level: "medium" },
  { slug: "leeds-castle", name: "Leeds Castle", country: "England", level: "medium" },
  { slug: "blarney-castle", name: "Blarney Castle", country: "Ireland", level: "medium" },
  { slug: "kilkenny-castle", name: "Kilkenny Castle", country: "Ireland", level: "medium" },
  { slug: "peles-castle", name: "Peleș Castle", country: "Romania", level: "medium" },
  { slug: "wawel-castle", name: "Wawel Castle", country: "Poland", level: "medium" },
  { slug: "burg-eltz", name: "Burg Eltz", country: "Germany", level: "medium" },
  { slug: "chateau-de-amboise", name: "Château d'Amboise", country: "France", level: "medium" },
  { slug: "hohensalzburg-fortress", name: "Hohensalzburg Fortress", country: "Austria", level: "medium" },
  { slug: "chillon-castle", name: "Chillon Castle", country: "Switzerland", level: "medium" },
  { slug: "alnwick-castle", name: "Alnwick Castle", country: "England", level: "medium" },
  { slug: "highclere-castle", name: "Highclere Castle", country: "England", level: "medium" },
  { slug: "nagoya-castle", name: "Nagoya Castle", country: "Japan", level: "medium" },
  { slug: "matsumoto-castle", name: "Matsumoto Castle", country: "Japan", level: "medium" },
  { slug: "hearst-castle", name: "Hearst Castle", country: "United States", level: "medium" },

  // HARD (18) — recognizable to history/travel enthusiasts
  { slug: "corvin-castle", name: "Corvin Castle", country: "Romania", level: "hard" },
  { slug: "spis-castle", name: "Spiš Castle", country: "Slovakia", level: "hard" },
  { slug: "bojnice-castle", name: "Bojnice Castle", country: "Slovakia", level: "hard" },
  { slug: "trakai-island-castle", name: "Trakai Island Castle", country: "Lithuania", level: "hard" },
  { slug: "marksburg-castle", name: "Marksburg Castle", country: "Germany", level: "hard" },
  { slug: "chateau-de-pierrefonds", name: "Château de Pierrefonds", country: "France", level: "hard" },
  { slug: "chateau-d-angers", name: "Château d'Angers", country: "France", level: "hard" },
  { slug: "predjama-castle", name: "Predjama Castle", country: "Slovenia", level: "hard" },
  { slug: "eilean-donan-castle", name: "Eilean Donan Castle", country: "Scotland", level: "hard" },
  { slug: "cardiff-castle", name: "Cardiff Castle", country: "Wales", level: "hard" },
  { slug: "bodiam-castle", name: "Bodiam Castle", country: "England", level: "hard" },
  { slug: "arundel-castle", name: "Arundel Castle", country: "England", level: "hard" },
  { slug: "castel-sant-angelo", name: "Castel Sant'Angelo", country: "Italy", level: "hard" },
  { slug: "castel-del-monte", name: "Castel del Monte", country: "Italy", level: "hard" },
  { slug: "castello-sforzesco", name: "Castello Sforzesco", country: "Italy", level: "hard" },
  { slug: "alcazar-of-toledo", name: "Alcázar of Toledo", country: "Spain", level: "hard" },
  { slug: "alcazar-of-seville", name: "Alcázar of Seville", country: "Spain", level: "hard" },
  { slug: "casa-loma", name: "Casa Loma", country: "Canada", level: "hard" },

  // IMPOSSIBLE (17) — genuinely obscure even to enthusiasts
  { slug: "egeskov-castle", name: "Egeskov Castle", country: "Denmark", level: "impossible" },
  { slug: "frederiksborg-castle", name: "Frederiksborg Castle", country: "Denmark", level: "impossible" },
  { slug: "sigmaringen-castle", name: "Sigmaringen Castle", country: "Germany", level: "impossible" },
  { slug: "wartburg-castle", name: "Wartburg Castle", country: "Germany", level: "impossible" },
  { slug: "karlstejn-castle", name: "Karlštejn Castle", country: "Czech Republic", level: "impossible" },
  { slug: "ksiaz-castle", name: "Książ Castle", country: "Poland", level: "impossible" },
  { slug: "ogrodzieniec-castle", name: "Ogrodzieniec Castle", country: "Poland", level: "impossible" },
  { slug: "chapultepec-castle", name: "Chapultepec Castle", country: "Mexico", level: "impossible" },
  { slug: "cape-coast-castle", name: "Cape Coast Castle", country: "Ghana", level: "impossible" },
  { slug: "elmina-castle", name: "Elmina Castle", country: "Ghana", level: "impossible" },
  { slug: "citadel-of-qaitbay", name: "Citadel of Qaitbay", country: "Egypt", level: "impossible" },
  { slug: "aleppo-citadel", name: "Aleppo Citadel", country: "Syria", level: "impossible" },
  { slug: "masyaf-castle", name: "Masyaf Castle", country: "Syria", level: "impossible" },
  { slug: "amber-fort", name: "Amber Fort", country: "India", level: "impossible" },
  { slug: "mehrangarh-fort", name: "Mehrangarh Fort", country: "India", level: "impossible" },
  { slug: "kumamoto-castle", name: "Kumamoto Castle", country: "Japan", level: "impossible" },
  { slug: "shuri-castle", name: "Shuri Castle", country: "Japan", level: "impossible" },
];
