// E29 "Guess the Fashion Brand" — answer = brand name, image = official brand logo.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
export const FASHION_BRAND_LOGOS_E29 = [
  // EASY (18) — globally iconic, instantly recognized worldwide
  { slug: "nike", name: "Nike", level: "easy" },
  { slug: "adidas", name: "Adidas", level: "easy" },
  { slug: "gucci", name: "Gucci", level: "easy" },
  { slug: "louis-vuitton", name: "Louis Vuitton", level: "easy" },
  { slug: "chanel", name: "Chanel", level: "easy" },
  { slug: "zara", name: "Zara", level: "easy" },
  { slug: "hm", name: "H&M", level: "easy" },
  { slug: "levis", name: "Levi's", level: "easy" },
  { slug: "puma", name: "Puma", level: "easy" },
  { slug: "calvin-klein", name: "Calvin Klein", level: "easy" },
  { slug: "ralph-lauren", name: "Ralph Lauren", level: "easy" },
  { slug: "converse", name: "Converse", level: "easy" },
  { slug: "versace", name: "Versace", level: "easy" },
  { slug: "vans", name: "Vans", level: "easy" },
  { slug: "tommy-hilfiger", name: "Tommy Hilfiger", level: "easy" },
  { slug: "prada", name: "Prada", level: "easy" },
  { slug: "dior", name: "Dior", level: "easy" },
  { slug: "under-armour", name: "Under Armour", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "new-balance", name: "New Balance", level: "medium" },
  { slug: "reebok", name: "Reebok", level: "medium" },
  { slug: "lacoste", name: "Lacoste", level: "medium" },
  { slug: "burberry", name: "Burberry", level: "medium" },
  { slug: "armani", name: "Armani", level: "medium" },
  { slug: "hugo-boss", name: "Hugo Boss", level: "medium" },
  { slug: "uniqlo", name: "Uniqlo", level: "medium" },
  { slug: "the-north-face", name: "The North Face", level: "medium" },
  { slug: "guess", name: "Guess", level: "medium" },
  { slug: "diesel", name: "Diesel", level: "medium" },
  { slug: "skechers", name: "Skechers", level: "medium" },
  { slug: "timberland", name: "Timberland", level: "medium" },
  { slug: "fila", name: "Fila", level: "medium" },
  { slug: "forever-21", name: "Forever 21", level: "medium" },
  { slug: "abercrombie-fitch", name: "Abercrombie & Fitch", level: "medium" },
  { slug: "patagonia", name: "Patagonia", level: "medium" },
  { slug: "champion", name: "Champion", level: "medium" },
  { slug: "columbia-sportswear", name: "Columbia Sportswear", level: "medium" },

  // HARD (18) — recognizable to fashion enthusiasts
  { slug: "michael-kors", name: "Michael Kors", level: "hard" },
  { slug: "balenciaga", name: "Balenciaga", level: "hard" },
  { slug: "valentino", name: "Valentino", level: "hard" },
  { slug: "givenchy", name: "Givenchy", level: "hard" },
  { slug: "fendi", name: "Fendi", level: "hard" },
  { slug: "moschino", name: "Moschino", level: "hard" },
  { slug: "supreme", name: "Supreme", level: "hard" },
  { slug: "dolce-gabbana", name: "Dolce & Gabbana", level: "hard" },
  { slug: "yves-saint-laurent", name: "Saint Laurent", level: "hard" },
  { slug: "salvatore-ferragamo", name: "Salvatore Ferragamo", level: "hard" },
  { slug: "jimmy-choo", name: "Jimmy Choo", level: "hard" },
  { slug: "off-white", name: "Off-White", level: "hard" },
  { slug: "bottega-veneta", name: "Bottega Veneta", level: "hard" },
  { slug: "kenzo", name: "Kenzo", level: "hard" },
  { slug: "marc-jacobs", name: "Marc Jacobs", level: "hard" },
  { slug: "tory-burch", name: "Tory Burch", level: "hard" },
  { slug: "missoni", name: "Missoni", level: "hard" },
  { slug: "stone-island", name: "Stone Island", level: "hard" },

  // IMPOSSIBLE (17) — obscure even to most fashion enthusiasts
  { slug: "alexander-mcqueen", name: "Alexander McQueen", level: "impossible" },
  { slug: "comme-des-garcons", name: "Comme des Garçons", level: "impossible" },
  { slug: "max-mara", name: "Max Mara", level: "impossible" },
  { slug: "furla", name: "Furla", level: "impossible" },
  { slug: "acne-studios", name: "Acne Studios", level: "impossible" },
  { slug: "apc", name: "A.P.C.", level: "impossible" },
  { slug: "maison-margiela", name: "Maison Margiela", level: "impossible" },
  { slug: "trussardi", name: "Trussardi", level: "impossible" },
  { slug: "ermenegildo-zegna", name: "Zegna", level: "impossible" },
  { slug: "brioni", name: "Brioni", level: "impossible" },
  { slug: "loro-piana", name: "Loro Piana", level: "impossible" },
  { slug: "balmain", name: "Balmain", level: "impossible" },
  { slug: "celine", name: "Celine", level: "impossible" },
  { slug: "loewe", name: "Loewe", level: "impossible" },
  { slug: "chloe", name: "Chloé", level: "impossible" },
  { slug: "isabel-marant", name: "Isabel Marant", level: "impossible" },
  { slug: "vetements", name: "Vetements", level: "impossible" },
];
