export const FASHION_BRAND_LOGOS_E29_FACTS = {
  "nike": "Nike is named after the Greek goddess of victory.",
  "adidas": "Adidas was founded by Adolf 'Adi' Dassler in Germany.",
  "gucci": "Gucci was founded in Florence, Italy, in 1921.",
  "louis-vuitton": "Louis Vuitton started as a trunk-making business in 1854.",
  "chanel": "Chanel's founder popularized the 'little black dress.'",
  "zara": "Zara is owned by the Spanish company Inditex.",
  "hm": "H&M stands for Hennes & Mauritz.",
  "levis": "Levi's patented the first riveted blue jeans in 1873.",
  "puma": "Puma was founded by Rudolf Dassler, brother of Adidas's founder.",
  "calvin-klein": "Calvin Klein pioneered designer jeans in the 1970s.",
  "ralph-lauren": "Ralph Lauren's logo features a polo player on horseback.",
  "converse": "Converse created the Chuck Taylor All Star sneaker.",
  "versace": "Versace's logo features the head of Medusa.",
  "vans": "Vans was founded by the Van Doren brothers in 1966.",
  "tommy-hilfiger": "Tommy Hilfiger's logo uses the colors of the American flag.",
  "prada": "Prada began as a leather goods shop in Milan in 1913.",
  "dior": "Christian Dior launched fashion's 'New Look' in 1947.",
  "under-armour": "Under Armour was founded by a former college football player.",

  "new-balance": "New Balance still manufactures some shoes in the USA.",
  "reebok": "Reebok is named after an African antelope, the rhebok.",
  "lacoste": "Lacoste's crocodile logo honors founder René Lacoste's nickname.",
  "burberry": "Burberry invented the waterproof fabric gabardine.",
  "armani": "Giorgio Armani dressed the cast of American Gigolo in 1980.",
  "hugo-boss": "Hugo Boss was founded in Metzingen, Germany, in 1924.",
  "uniqlo": "Uniqlo is short for 'Unique Clothing Warehouse.'",
  "the-north-face": "The North Face is named for the coldest side of a mountain.",
  "guess": "Guess was founded by four Marciano brothers in 1981.",
  "diesel": "Diesel's slogan is 'For Successful Living.'",
  "skechers": "Skechers is named using slang for restless energy.",
  "timberland": "Timberland's yellow boot became a 1990s streetwear icon.",
  "fila": "FILA was founded in Italy but is now Korean-owned.",
  "forever-21": "Forever 21 was founded by Korean immigrants in Los Angeles.",
  "abercrombie-fitch": "Abercrombie & Fitch began as an outdoor sporting goods store.",
  "patagonia": "Patagonia's founder pledged the company's profits to the planet.",
  "champion": "Champion invented the modern sweatshirt in the 1920s.",
  "columbia-sportswear": "Columbia Sportswear started as a hat distributor in Oregon.",

  "michael-kors": "Michael Kors was a judge on Project Runway.",
  "balenciaga": "Balenciaga was founded by designer Cristóbal Balenciaga.",
  "valentino": "Valentino is famous for its signature shade of red.",
  "givenchy": "Givenchy dressed Audrey Hepburn in Breakfast at Tiffany's.",
  "fendi": "Fendi's double-F logo was designed by Karl Lagerfeld.",
  "moschino": "Moschino is known for its bold, satirical fashion designs.",
  "supreme": "Supreme's box logo was inspired by artist Barbara Kruger.",
  "dolce-gabbana": "Dolce & Gabbana was founded by two Italian designers in 1985.",
  "yves-saint-laurent": "Saint Laurent dropped 'Yves' from its name in 2012.",
  "salvatore-ferragamo": "Salvatore Ferragamo made shoes for Hollywood stars in the 1920s.",
  "jimmy-choo": "Jimmy Choo trained as a shoemaker in London.",
  "off-white": "Off-White was founded by designer Virgil Abloh.",
  "bottega-veneta": "Bottega Veneta is known for its woven leather 'Intrecciato.'",
  "kenzo": "Kenzo was founded by Japanese designer Kenzo Takada in Paris.",
  "marc-jacobs": "Marc Jacobs once served as Louis Vuitton's creative director.",
  "tory-burch": "Tory Burch's logo is a double-T medallion.",
  "missoni": "Missoni is famous for its colorful knitwear patterns.",
  "stone-island": "Stone Island is known for its compass rose 'Badge.'",

  "alexander-mcqueen": "Alexander McQueen trained as a Savile Row tailor.",
  "comme-des-garcons": "Comme des Garçons means 'like the boys' in French.",
  "max-mara": "Max Mara is known for its camel coat design.",
  "furla": "Furla started as a leather goods shop in Bologna in 1927.",
  "acne-studios": "Acne Studios started as an art collective in Stockholm.",
  "apc": "A.P.C. stands for Atelier de Production et de Création.",
  "maison-margiela": "Maison Margiela pioneered deconstructed fashion design.",
  "trussardi": "Trussardi began as an Italian glove-making business.",
  "ermenegildo-zegna": "Zegna was founded by Ermenegildo Zegna in Italy in 1910.",
  "brioni": "Brioni is known for tailoring James Bond's suits.",
  "loro-piana": "Loro Piana specializes in fine cashmere and wool fabrics.",
  "balmain": "Balmain was founded by French designer Pierre Balmain.",
  "celine": "Celine dropped the accent from its name in a 2018 rebrand.",
  "loewe": "Loewe began as a leather workshop in Madrid in 1846.",
  "chloe": "Chloé was one of the first ready-to-wear fashion houses.",
  "isabel-marant": "Isabel Marant popularized the bohemian 'French girl' look.",
  "vetements": "Vetements means 'clothing' in French.",
};
