export const FAST_FOOD_LOGOS_E27_FACTS = {
  "mcdonalds": "McDonald's is the world's largest fast food chain by revenue.",
  "kfc": "KFC's 'secret recipe' uses 11 herbs and spices.",
  "burger-king": "Burger King is famous for its flame-grilled burgers.",
  "subway": "Subway lets customers build their own sandwiches.",
  "pizza-hut": "Pizza Hut opened its first restaurant in Wichita, Kansas.",
  "dominos-pizza": "Domino's built its brand on fast pizza delivery.",
  "starbucks": "Starbucks is named after a character in Moby-Dick.",
  "taco-bell": "Taco Bell popularized Mexican-inspired fast food in the US.",
  "dunkin": "Dunkin' dropped 'Donuts' from its official name in 2019.",
  "wendys": "Wendy's mascot is named after founder Dave Thomas's daughter.",
  "papa-johns": "Papa John's slogan is 'Better Ingredients. Better Pizza.'",
  "chick-fil-a": "Chick-fil-A restaurants are closed every Sunday.",
  "baskin-robbins": "Baskin-Robbins is known for offering 31 ice cream flavors.",
  "popeyes": "Popeyes is named after a movie cop, not the cartoon sailor.",
  "dairy-queen": "Dairy Queen is known for its soft-serve 'Blizzard' treats.",
  "little-caesars": "Little Caesars popularized the 'Hot-N-Ready' pizza concept.",
  "panda-express": "Panda Express popularized American Chinese fast food.",
  "five-guys": "Five Guys is named after the founder's five sons.",

  "hardees": "Hardee's merged with Carl's Jr. under one parent company.",
  "carls-jr": "Carl's Jr. is Hardee's sister brand, mainly out west.",
  "sonic-drive-in": "Sonic Drive-In restaurants use classic carhop service.",
  "chipotle": "Chipotle helped pioneer the 'fast casual' restaurant format.",
  "panera-bread": "Panera Bread is known for its bread bowls and bakery-cafes.",
  "jimmy-johns": "Jimmy John's promotes 'freaky fast' sandwich delivery.",
  "arbys": "Arby's slogan plays on the phrase 'we have the meats.'",
  "in-n-out-burger": "In-N-Out Burger has a secret 'Animal Style' menu option.",
  "jack-in-the-box": "Jack in the Box's mascot is a clown-headed businessman.",
  "krispy-kreme": "Krispy Kreme lights a 'Hot Now' sign for fresh doughnuts.",
  "tim-hortons": "Tim Hortons was founded by a Canadian hockey player.",
  "nandos": "Nando's specializes in Portuguese-style peri-peri chicken.",
  "shake-shack": "Shake Shack began as a hot dog cart in a New York park.",
  "wingstop": "Wingstop specializes in cooked-to-order chicken wings.",
  "churchs-chicken": "Church's Chicken was founded near the Alamo in Texas.",
  "whataburger": "Whataburger's orange-and-white stripes are a Texas icon.",
  "culvers": "Culver's is known for its ButterBurgers and frozen custard.",
  "zaxbys": "Zaxby's specializes in chicken fingers and wings.",

  "jollibee": "Jollibee is the Philippines' largest fast food chain.",
  "aw-restaurants": "A&W Restaurants is famous for its root beer floats.",
  "long-john-silvers": "Long John Silver's specializes in seafood, not burgers.",
  "el-pollo-loco": "El Pollo Loco specializes in fire-grilled chicken.",
  "raising-canes": "Raising Cane's menu focuses almost entirely on chicken fingers.",
  "bojangles": "Bojangles blends Cajun spice with Southern-style chicken.",
  "cook-out": "Cook Out is known for its large tray combo meals.",
  "del-taco": "Del Taco blends Mexican and American fast food menus.",
  "white-castle": "White Castle popularized the small square hamburger slider.",
  "checkers-rallys": "Checkers and Rally's operate as one company with two brands.",
  "freddys": "Freddy's is known for steakburgers and frozen custard.",
  "captain-ds": "Captain D's specializes in seafood, like Long John Silver's.",
  "fatburger": "Fatburger was founded in Los Angeles in 1952.",
  "skyline-chili": "Skyline Chili tops spaghetti with its signature chili.",
  "portillos": "Portillo's began as a hot dog stand in Illinois.",
  "braums": "Braum's makes its own ice cream from its own dairy farms.",
  "steak-n-shake": "Steak 'n Shake blends a steakhouse and milkshake diner.",
  "wienerschnitzel": "Wienerschnitzel specializes in hot dogs, not schnitzel.",

  "nathans-famous": "Nathan's Famous started as a Coney Island hot dog stand.",
  "habit-burger-grill": "Habit Burger Grill is known for its Santa Barbara char burger.",
  "golden-chick": "Golden Chick is a Texas-based fried chicken chain.",
  "mod-pizza": "MOD Pizza lets customers build individual pizzas fast.",
  "blaze-pizza": "Blaze Pizza fires custom pizzas in a fast-casual format.",
  "noodles-company": "Noodles & Company serves noodle dishes from around the world.",
  "which-wich": "Which Wich has customers mark their order on the bag.",
  "firehouse-subs": "Firehouse Subs was founded by two brothers who were firefighters.",
  "jersey-mikes": "Jersey Mike's slices meats fresh in-store for each sub.",
  "charleys-philly-steaks": "Charleys Philly Steaks specializes in Philly cheesesteaks.",
  "slim-chickens": "Slim Chickens started as a single restaurant in Arkansas.",
  "golden-corral": "Golden Corral is known for its all-you-can-eat buffet.",
  "lotteria": "Lotteria is one of South Korea's largest fast food chains.",
  "mos-burger": "MOS Burger's name stands for Mountain, Ocean, and Sun.",
  "steers": "Steers is a South African chain known for flame-grilled burgers.",
  "quick": "Quick is a Belgian-French fast food burger chain.",
  "roy-rogers": "Roy Rogers Restaurants is named after the American cowboy actor.",
};
