// E27 "Guess the Fast Food Chain" — answer = chain name, image = official brand logo.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
// Hard content rules: no Israeli chains — screened out entirely.
export const FAST_FOOD_LOGOS_E27 = [
  // EASY (18) — globally iconic, instantly recognized worldwide
  { slug: "mcdonalds", name: "McDonald's", level: "easy" },
  { slug: "kfc", name: "KFC", level: "easy" },
  { slug: "burger-king", name: "Burger King", level: "easy" },
  { slug: "subway", name: "Subway", level: "easy" },
  { slug: "pizza-hut", name: "Pizza Hut", level: "easy" },
  { slug: "dominos-pizza", name: "Domino's Pizza", level: "easy" },
  { slug: "starbucks", name: "Starbucks", level: "easy" },
  { slug: "taco-bell", name: "Taco Bell", level: "easy" },
  { slug: "dunkin", name: "Dunkin'", level: "easy" },
  { slug: "wendys", name: "Wendy's", level: "easy" },
  { slug: "papa-johns", name: "Papa John's", level: "easy" },
  { slug: "chick-fil-a", name: "Chick-fil-A", level: "easy" },
  { slug: "baskin-robbins", name: "Baskin-Robbins", level: "easy" },
  { slug: "popeyes", name: "Popeyes", level: "easy" },
  { slug: "dairy-queen", name: "Dairy Queen", level: "easy" },
  { slug: "little-caesars", name: "Little Caesars", level: "easy" },
  { slug: "panda-express", name: "Panda Express", level: "easy" },
  { slug: "five-guys", name: "Five Guys", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "hardees", name: "Hardee's", level: "medium" },
  { slug: "carls-jr", name: "Carl's Jr.", level: "medium" },
  { slug: "sonic-drive-in", name: "Sonic Drive-In", level: "medium" },
  { slug: "chipotle", name: "Chipotle Mexican Grill", level: "medium" },
  { slug: "panera-bread", name: "Panera Bread", level: "medium" },
  { slug: "jimmy-johns", name: "Jimmy John's", level: "medium" },
  { slug: "arbys", name: "Arby's", level: "medium" },
  { slug: "in-n-out-burger", name: "In-N-Out Burger", level: "medium" },
  { slug: "jack-in-the-box", name: "Jack in the Box", level: "medium" },
  { slug: "krispy-kreme", name: "Krispy Kreme", level: "medium" },
  { slug: "tim-hortons", name: "Tim Hortons", level: "medium" },
  { slug: "nandos", name: "Nando's", level: "medium" },
  { slug: "shake-shack", name: "Shake Shack", level: "medium" },
  { slug: "wingstop", name: "Wingstop", level: "medium" },
  { slug: "churchs-chicken", name: "Church's Chicken", level: "medium" },
  { slug: "whataburger", name: "Whataburger", level: "medium" },
  { slug: "culvers", name: "Culver's", level: "medium" },
  { slug: "zaxbys", name: "Zaxby's", level: "medium" },

  // HARD (18) — recognizable to regional/enthusiast fans
  { slug: "jollibee", name: "Jollibee", level: "hard" },
  { slug: "aw-restaurants", name: "A&W Restaurants", level: "hard" },
  { slug: "long-john-silvers", name: "Long John Silver's", level: "hard" },
  { slug: "el-pollo-loco", name: "El Pollo Loco", level: "hard" },
  { slug: "raising-canes", name: "Raising Cane's", level: "hard" },
  { slug: "bojangles", name: "Bojangles", level: "hard" },
  { slug: "cook-out", name: "Cook Out", level: "hard" },
  { slug: "del-taco", name: "Del Taco", level: "hard" },
  { slug: "white-castle", name: "White Castle", level: "hard" },
  { slug: "checkers-rallys", name: "Checkers and Rally's", level: "hard" },
  { slug: "freddys", name: "Freddy's Frozen Custard", level: "hard" },
  { slug: "captain-ds", name: "Captain D's", level: "hard" },
  { slug: "fatburger", name: "Fatburger", level: "hard" },
  { slug: "skyline-chili", name: "Skyline Chili", level: "hard" },
  { slug: "portillos", name: "Portillo's", level: "hard" },
  { slug: "braums", name: "Braum's", level: "hard" },
  { slug: "steak-n-shake", name: "Steak 'n Shake", level: "hard" },
  { slug: "wienerschnitzel", name: "Wienerschnitzel", level: "hard" },

  // IMPOSSIBLE (17) — obscure even to fast food enthusiasts
  { slug: "nathans-famous", name: "Nathan's Famous", level: "impossible" },
  { slug: "habit-burger-grill", name: "Habit Burger Grill", level: "impossible" },
  { slug: "golden-chick", name: "Golden Chick", level: "impossible" },
  { slug: "mod-pizza", name: "MOD Pizza", level: "impossible" },
  { slug: "blaze-pizza", name: "Blaze Pizza", level: "impossible" },
  { slug: "noodles-company", name: "Noodles & Company", level: "impossible" },
  { slug: "which-wich", name: "Which Wich", level: "impossible" },
  { slug: "firehouse-subs", name: "Firehouse Subs", level: "impossible" },
  { slug: "jersey-mikes", name: "Jersey Mike's", level: "impossible" },
  { slug: "charleys-philly-steaks", name: "Charleys Philly Steaks", level: "impossible" },
  { slug: "slim-chickens", name: "Slim Chickens", level: "impossible" },
  { slug: "roy-rogers", name: "Roy Rogers Restaurants", level: "impossible" },
  { slug: "golden-corral", name: "Golden Corral", level: "impossible" },
  { slug: "lotteria", name: "Lotteria", level: "impossible" },
  { slug: "mos-burger", name: "MOS Burger", level: "impossible" },
  { slug: "steers", name: "Steers", level: "impossible" },
  { slug: "quick", name: "Quick", level: "impossible" },
];
