// Episode 2 "Guess the Flag" — 100 items, absolute-difficulty calibrated (25/tier).
// Calibrated relative to the flags topic's own recognition scale (flags skill notes
// only ~15-20 flags clear 70% global recognition, unlike animals/logos).
// HARD RULE: Israel is excluded — verified absent from this list.
export const FLAGS_E02 = [
  // EASY (25)
  { iso: "us", name: "United States", level: "easy" },
  { iso: "jp", name: "Japan", level: "easy" },
  { iso: "gb", name: "United Kingdom", level: "easy" },
  { iso: "ca", name: "Canada", level: "easy" },
  { iso: "br", name: "Brazil", level: "easy" },
  { iso: "de", name: "Germany", level: "easy" },
  { iso: "in", name: "India", level: "easy" },
  { iso: "kr", name: "South Korea", level: "easy" },
  { iso: "cn", name: "China", level: "easy" },
  { iso: "mx", name: "Mexico", level: "easy" },
  { iso: "it", name: "Italy", level: "easy" },
  { iso: "fr", name: "France", level: "easy" },
  { iso: "ch", name: "Switzerland", level: "easy" },
  { iso: "za", name: "South Africa", level: "easy" },
  { iso: "au", name: "Australia", level: "easy" },
  { iso: "ar", name: "Argentina", level: "easy" },
  { iso: "es", name: "Spain", level: "easy" },
  { iso: "tr", name: "Turkey", level: "easy" },
  { iso: "jm", name: "Jamaica", level: "easy" },
  { iso: "sa", name: "Saudi Arabia", level: "easy" },
  { iso: "eg", name: "Egypt", level: "easy" },
  { iso: "gr", name: "Greece", level: "easy" },
  { iso: "se", name: "Sweden", level: "easy" },
  { iso: "ke", name: "Kenya", level: "easy" },
  { iso: "cu", name: "Cuba", level: "easy" },

  // MEDIUM (25)
  { iso: "ru", name: "Russia", level: "medium" },
  { iso: "nl", name: "Netherlands", level: "medium" },
  { iso: "nz", name: "New Zealand", level: "medium" },
  { iso: "no", name: "Norway", level: "medium" },
  { iso: "dk", name: "Denmark", level: "medium" },
  { iso: "fi", name: "Finland", level: "medium" },
  { iso: "is", name: "Iceland", level: "medium" },
  { iso: "pl", name: "Poland", level: "medium" },
  { iso: "ie", name: "Ireland", level: "medium" },
  { iso: "ua", name: "Ukraine", level: "medium" },
  { iso: "pt", name: "Portugal", level: "medium" },
  { iso: "ng", name: "Nigeria", level: "medium" },
  { iso: "pk", name: "Pakistan", level: "medium" },
  { iso: "bd", name: "Bangladesh", level: "medium" },
  { iso: "vn", name: "Vietnam", level: "medium" },
  { iso: "th", name: "Thailand", level: "medium" },
  { iso: "id", name: "Indonesia", level: "medium" },
  { iso: "ir", name: "Iran", level: "medium" },
  { iso: "ae", name: "United Arab Emirates", level: "medium" },
  { iso: "co", name: "Colombia", level: "medium" },
  { iso: "ve", name: "Venezuela", level: "medium" },
  { iso: "ec", name: "Ecuador", level: "medium" },
  { iso: "ph", name: "Philippines", level: "medium" },
  { iso: "np", name: "Nepal", level: "medium" },
  { iso: "cl", name: "Chile", level: "medium" },

  // HARD (25)
  { iso: "lk", name: "Sri Lanka", level: "hard" },
  { iso: "kh", name: "Cambodia", level: "hard" },
  { iso: "mm", name: "Myanmar", level: "hard" },
  { iso: "mn", name: "Mongolia", level: "hard" },
  { iso: "kz", name: "Kazakhstan", level: "hard" },
  { iso: "et", name: "Ethiopia", level: "hard" },
  { iso: "gh", name: "Ghana", level: "hard" },
  { iso: "cm", name: "Cameroon", level: "hard" },
  { iso: "sn", name: "Senegal", level: "hard" },
  { iso: "ml", name: "Mali", level: "hard" },
  { iso: "ma", name: "Morocco", level: "hard" },
  { iso: "dz", name: "Algeria", level: "hard" },
  { iso: "tn", name: "Tunisia", level: "hard" },
  { iso: "lb", name: "Lebanon", level: "hard" },
  { iso: "qa", name: "Qatar", level: "hard" },
  { iso: "jo", name: "Jordan", level: "hard" },
  { iso: "pg", name: "Papua New Guinea", level: "hard" },
  { iso: "mt", name: "Malta", level: "hard" },
  { iso: "cy", name: "Cyprus", level: "hard" },
  { iso: "hr", name: "Croatia", level: "hard" },
  { iso: "al", name: "Albania", level: "hard" },
  { iso: "ro", name: "Romania", level: "hard" },
  { iso: "td", name: "Chad", level: "hard" },
  { iso: "ge", name: "Georgia", level: "hard" },
  { iso: "bt", name: "Bhutan", level: "hard" },

  // IMPOSSIBLE (25)
  { iso: "nr", name: "Nauru", level: "impossible" },
  { iso: "ki", name: "Kiribati", level: "impossible" },
  { iso: "tv", name: "Tuvalu", level: "impossible" },
  { iso: "pw", name: "Palau", level: "impossible" },
  { iso: "mh", name: "Marshall Islands", level: "impossible" },
  { iso: "fm", name: "Micronesia", level: "impossible" },
  { iso: "vu", name: "Vanuatu", level: "impossible" },
  { iso: "sb", name: "Solomon Islands", level: "impossible" },
  { iso: "km", name: "Comoros", level: "impossible" },
  { iso: "st", name: "Sao Tome and Principe", level: "impossible" },
  { iso: "gw", name: "Guinea-Bissau", level: "impossible" },
  { iso: "gq", name: "Equatorial Guinea", level: "impossible" },
  { iso: "dj", name: "Djibouti", level: "impossible" },
  { iso: "er", name: "Eritrea", level: "impossible" },
  { iso: "bi", name: "Burundi", level: "impossible" },
  { iso: "ls", name: "Lesotho", level: "impossible" },
  { iso: "sz", name: "Eswatini", level: "impossible" },
  { iso: "cf", name: "Central African Republic", level: "impossible" },
  { iso: "ga", name: "Gabon", level: "impossible" },
  { iso: "cg", name: "Republic of the Congo", level: "impossible" },
  { iso: "mr", name: "Mauritania", level: "impossible" },
  { iso: "tm", name: "Turkmenistan", level: "impossible" },
  { iso: "tj", name: "Tajikistan", level: "impossible" },
  { iso: "kg", name: "Kyrgyzstan", level: "impossible" },
  { iso: "md", name: "Moldova", level: "impossible" },
];
export default FLAGS_E02;
