// Episode 2 "Guess the Flag" — one verified ≤70-char fact per country, keyed by ISO code.
// Verified via quiz-fact-verifier agent pass (6 corrections applied: ca, jp, pt, gr, fi, tm).
export const FLAGS_E02_FACTS = {
  "us": "The Grand Canyon is over 1 mile deep in places.",
  "jp": "A 2023 survey found Japan actually has 14,125 islands.",
  "gb": "The London Underground opened in 1863, the world's first.",
  "ca": "Canada has more lake area than any other single country.",
  "br": "Brazil is home to about 60% of the Amazon rainforest.",
  "de": "Germany has over 1,500 different types of sausage.",
  "in": "India recognizes 22 scheduled languages.",
  "kr": "South Korea's alphabet, Hangul, was created in 1443.",
  "cn": "The Great Wall of China stretches over 13,000 miles.",
  "mx": "Mexico City is slowly sinking into an old lakebed.",
  "it": "Rome, Italy's capital, is nicknamed the Eternal City.",
  "fr": "France is the most visited country in the world.",
  "ch": "Switzerland has four official national languages.",
  "za": "South Africa has three capital cities, not one.",
  "au": "Australia is home to more kangaroos than people.",
  "ar": "Argentina is home to the widest avenue in the world.",
  "es": "Spaniards traditionally eat dinner after 9 p.m.",
  "tr": "Istanbul, Turkey's largest city, spans two continents.",
  "jm": "Usain Bolt, the fastest man ever, is Jamaican.",
  "sa": "Saudi Arabia is home to Islam's two holiest cities.",
  "eg": "Egypt's Great Pyramid was the world's tallest building for ages.",
  "gr": "Greece has more than 110 archaeological museums nationwide.",
  "se": "Sweden has more than 100,000 islands along its coast.",
  "ke": "Kenya's Great Rift Valley is visible from space.",
  "cu": "Cuba is the largest island in the Caribbean Sea.",
  "ru": "Russia spans 11 time zones, the most of any country.",
  "nl": "About a quarter of the Netherlands lies below sea level.",
  "nz": "New Zealand was the first country to give women the vote.",
  "no": "Norway has more fjords than any other country on Earth.",
  "dk": "Denmark is made up of over 400 named islands.",
  "fi": "Finland has roughly one sauna for every two people.",
  "is": "Iceland has no mosquitoes anywhere on the island.",
  "pl": "Poland is home to one of Europe's oldest universities.",
  "ie": "Ireland is nicknamed the Emerald Isle for its green hills.",
  "ua": "Ukraine is Europe's largest country by land area.",
  "pt": "Portugal borders have remained largely unchanged since 1139.",
  "ng": "Nigeria is Africa's most populous country by far.",
  "pk": "Pakistan is home to K2, the world's second-highest peak.",
  "bd": "Bangladesh has the world's largest river delta.",
  "vn": "Vietnam is the world's largest exporter of cashews.",
  "th": "Thailand is the only Southeast Asian nation never colonized.",
  "id": "Indonesia is made up of more than 17,000 islands.",
  "ir": "Iran was known as Persia until it was renamed in 1935.",
  "ae": "The UAE's Burj Khalifa is the world's tallest building.",
  "co": "Colombia grows more species of orchids than any nation.",
  "ve": "Venezuela has Angel Falls, the world's tallest waterfall.",
  "ec": "Ecuador is named after the equator, which crosses it.",
  "ph": "The Philippines is made up of over 7,000 islands.",
  "np": "Nepal is home to Mount Everest, the world's highest peak.",
  "cl": "Chile is one of the longest, narrowest countries on Earth.",
  "lk": "First nation to elect a female prime minister.",
  "kh": "Angkor Wat is the world's largest religious monument.",
  "mm": "Myanmar was known as Burma until 1989.",
  "mn": "Mongolia has the lowest population density on Earth.",
  "kz": "Kazakhstan is the world's largest landlocked country.",
  "et": "Ethiopia was never colonized by a European power.",
  "gh": "Ghana was the first sub-Saharan nation to gain independence.",
  "cm": "Cameroon is nicknamed 'Africa in miniature.'",
  "sn": "Senegal has mainland Africa's westernmost point.",
  "ml": "Mali is home to the ancient city of Timbuktu.",
  "ma": "Morocco has the world's oldest continuously run university.",
  "dz": "Algeria is the largest country in Africa by area.",
  "tn": "Star Wars' Tatooine scenes were filmed in Tunisia.",
  "lb": "Lebanon's flag features its ancient, iconic cedar tree.",
  "qa": "Qatar has one of the highest GDP per capita worldwide.",
  "jo": "Jordan is home to Petra, one of the New7Wonders.",
  "pg": "Papua New Guinea has over 800 spoken languages.",
  "mt": "Malta is one of the EU's smallest, most crowded states.",
  "cy": "In myth, Cyprus is said to be the birthplace of Aphrodite.",
  "hr": "The necktie traces its origin to Croatian soldiers.",
  "al": "Albania's flag bears one of the oldest national emblems.",
  "ro": "Romania's Transylvania inspired the legend of Dracula.",
  "td": "Chad is named after Lake Chad, once a huge lake.",
  "ge": "Georgia is widely considered the birthplace of wine.",
  "bt": "Bhutan measures Gross National Happiness, not GDP.",
  "nr": "Nauru is the world's smallest island nation, 21 km².",
  "ki": "Kiribati is the only nation in all four hemispheres.",
  "tv": "Tuvalu earns about a tenth of its revenue from '.tv' domains.",
  "pw": "Palau created the world's first shark sanctuary in 2009.",
  "mh": "The US tested 23 nuclear bombs at Bikini Atoll, 1946-58.",
  "fm": "Yap islanders once used giant stone discs as money.",
  "vu": "Vanuatu's land-diving ritual inspired bungee jumping.",
  "sb": "Solomon Islands' Guadalcanal was a turning point in WWII.",
  "km": "Comoros produces most of the world's ylang-ylang oil.",
  "st": "Sao Tome and Principe is Africa's 2nd-smallest country.",
  "gw": "Guinea-Bissau ranks among the world's top cashew growers.",
  "gq": "Equatorial Guinea is Africa's only Spanish-speaking nation.",
  "dj": "Djibouti hosts US, French, Chinese and Japanese military bases.",
  "er": "Asmara, Eritrea's capital, is Africa's first modernist UNESCO site.",
  "bi": "Burundi borders Lake Tanganyika, the world's 2nd-deepest lake.",
  "ls": "Lesotho is entirely above 1,000m and encircled by South Africa.",
  "sz": "Eswatini is Africa's last remaining absolute monarchy.",
  "cf": "Central African Republic has rich diamond deposits.",
  "ga": "Over 88% of Gabon is covered by dense rainforest.",
  "cg": "The Congo River, its border, is the world's deepest river.",
  "mr": "Mauritania was the last country to abolish slavery, in 1981.",
  "tm": "Turkmenistan gas crater has burned for decades.",
  "tj": "Tajikistan's Pamir Highway is the world's 2nd-highest road.",
  "kg": "Kyrgyzstan's Issyk-Kul is the world's 2nd-largest alpine lake.",
  "md": "Moldova's Milestii Mici is the world's largest wine cellar.",
};
export default FLAGS_E02_FACTS;
