export const FONTS_E87 = [
  // EASY (18) — near-universal, widely used/recognized font names
  { slug: "roboto", name: "Roboto", weight: "700", level: "easy" },
  { slug: "open-sans", name: "Open Sans", weight: "700", level: "easy" },
  { slug: "lato", name: "Lato", weight: "700", level: "easy" },
  { slug: "montserrat", name: "Montserrat", weight: "700", level: "easy" },
  { slug: "poppins", name: "Poppins", weight: "700", level: "easy" },
  { slug: "oswald", name: "Oswald", weight: "600", level: "easy" },
  { slug: "raleway", name: "Raleway", weight: "700", level: "easy" },
  { slug: "merriweather", name: "Merriweather", weight: "700", level: "easy" },
  { slug: "playfair-display", name: "Playfair Display", weight: "700", level: "easy" },
  { slug: "nunito", name: "Nunito", weight: "800", level: "easy" },
  { slug: "ubuntu", name: "Ubuntu", weight: "700", level: "easy" },
  { slug: "bebas-neue", name: "Bebas Neue", weight: "400", level: "easy" },
  { slug: "pacifico", name: "Pacifico", weight: "400", level: "easy" },
  { slug: "lobster", name: "Lobster", weight: "400", level: "easy" },
  { slug: "dancing-script", name: "Dancing Script", weight: "700", level: "easy" },
  { slug: "caveat", name: "Caveat", weight: "700", level: "easy" },
  { slug: "indie-flower", name: "Indie Flower", weight: "400", level: "easy" },
  { slug: "permanent-marker", name: "Permanent Marker", weight: "400", level: "easy" },

  // MEDIUM (18) — most design-aware people have seen it, ~35-70%
  { slug: "anton", name: "Anton", weight: "400", level: "medium" },
  { slug: "righteous", name: "Righteous", weight: "400", level: "medium" },
  { slug: "bangers", name: "Bangers", weight: "400", level: "medium" },
  { slug: "fredoka", name: "Fredoka", weight: "700", level: "medium" },
  { slug: "comfortaa", name: "Comfortaa", weight: "700", level: "medium" },
  { slug: "quicksand", name: "Quicksand", weight: "700", level: "medium" },
  { slug: "josefin-sans", name: "Josefin Sans", weight: "700", level: "medium" },
  { slug: "cabin", name: "Cabin", weight: "700", level: "medium" },
  { slug: "pt-sans", name: "PT Sans", weight: "700", level: "medium" },
  { slug: "source-sans-pro", name: "Source Sans Pro", weight: "700", level: "medium" },
  { slug: "crimson-text", name: "Crimson Text", weight: "700", level: "medium" },
  { slug: "libre-baskerville", name: "Libre Baskerville", weight: "700", level: "medium" },
  { slug: "cormorant-garamond", name: "Cormorant Garamond", weight: "700", level: "medium" },
  { slug: "abril-fatface", name: "Abril Fatface", weight: "400", level: "medium" },
  { slug: "archivo-black", name: "Archivo Black", weight: "400", level: "medium" },
  { slug: "passion-one", name: "Passion One", weight: "700", level: "medium" },
  { slug: "alfa-slab-one", name: "Alfa Slab One", weight: "400", level: "medium" },
  { slug: "shrikhand", name: "Shrikhand", weight: "400", level: "medium" },

  // HARD (16) — design enthusiasts recognize, casual public often doesn't
  { slug: "zilla-slab", name: "Zilla Slab", weight: "700", level: "hard" },
  { slug: "rubik", name: "Rubik", weight: "700", level: "hard" },
  { slug: "karla", name: "Karla", weight: "700", level: "hard" },
  { slug: "dm-serif-display", name: "DM Serif Display", weight: "400", level: "hard" },
  { slug: "spectral", name: "Spectral", weight: "700", level: "hard" },
  { slug: "vollkorn", name: "Vollkorn", weight: "700", level: "hard" },
  { slug: "bitter", name: "Bitter", weight: "700", level: "hard" },
  { slug: "sarabun", name: "Sarabun", weight: "700", level: "hard" },
  { slug: "chivo", name: "Chivo", weight: "700", level: "hard" },
  { slug: "barlow", name: "Barlow", weight: "700", level: "hard" },
  { slug: "manrope", name: "Manrope", weight: "800", level: "hard" },
  { slug: "work-sans", name: "Work Sans", weight: "700", level: "hard" },
  { slug: "ibm-plex-sans", name: "IBM Plex Sans", weight: "700", level: "hard" },
  { slug: "space-mono", name: "Space Mono", weight: "700", level: "hard" },
  { slug: "jetbrains-mono", name: "JetBrains Mono", weight: "700", level: "hard" },
  { slug: "inconsolata", name: "Inconsolata", weight: "700", level: "hard" },

  // IMPOSSIBLE (18) — genuinely niche, even typography enthusiasts may not know
  { slug: "syne", name: "Syne", weight: "700", level: "impossible" },
  { slug: "unbounded", name: "Unbounded", weight: "700", level: "impossible" },
  { slug: "familjen-grotesk", name: "Familjen Grotesk", weight: "700", level: "impossible" },
  { slug: "fraunces", name: "Fraunces", weight: "700", level: "impossible" },
  { slug: "sora", name: "Sora", weight: "700", level: "impossible" },
  { slug: "outfit", name: "Outfit", weight: "700", level: "impossible" },
  { slug: "plus-jakarta-sans", name: "Plus Jakarta Sans", weight: "700", level: "impossible" },
  { slug: "lexend", name: "Lexend", weight: "700", level: "impossible" },
  { slug: "onest", name: "Onest", weight: "700", level: "impossible" },
  { slug: "instrument-serif", name: "Instrument Serif", weight: "400", level: "impossible" },
  { slug: "bricolage-grotesque", name: "Bricolage Grotesque", weight: "700", level: "impossible" },
  { slug: "schibsted-grotesk", name: "Schibsted Grotesk", weight: "700", level: "impossible" },
  { slug: "newsreader", name: "Newsreader", weight: "600", level: "impossible" },
  { slug: "literata", name: "Literata", weight: "700", level: "impossible" },
  { slug: "recursive", name: "Recursive", weight: "700", level: "impossible" },
  { slug: "hanken-grotesk", name: "Hanken Grotesk", weight: "700", level: "impossible" },
  { slug: "red-hat-display", name: "Red Hat Display", weight: "700", level: "impossible" },
  { slug: "space-grotesk", name: "Space Grotesk", weight: "700", level: "impossible" },
];

export default FONTS_E87;
