export const FONTS_E87_FACTS = {
  roboto: "Designed for Android, it's the default system font on most Google devices.",
  "open-sans": "One of the most-used typefaces on the web, designed by Steve Matteson.",
  lato: "Its name means 'summer' in Polish, the language of its designer.",
  montserrat: "Inspired by old street signs and posters from a Buenos Aires neighborhood.",
  poppins: "A geometric sans designed to pair Latin letters with Devanagari script.",
  oswald: "A condensed sans reworked from a classic early-1900s gothic style.",
  raleway: "Started as a single elegant thin weight before more weights were added.",
  merriweather: "A serif built specifically to stay readable on small screens.",
  "playfair-display": "Inspired by transitional typefaces from the 18th-century Enlightenment.",
  nunito: "A rounded sans-serif with soft, friendly curved terminals.",
  ubuntu: "Commissioned for the Ubuntu operating system's branding and interface.",
  "bebas-neue": "A free, redrawn revival of a bold all-caps display font.",
  pacifico: "A flowing script inspired by 1950s American surf culture.",
  lobster: "A bold retro script that became one of the most popular free fonts online.",
  "dancing-script": "A lively, bouncy script designed to feel like casual handwriting.",
  caveat: "Designed to imitate natural handwriting, with letters that vary slightly.",
  "indie-flower": "A carefree, bubbly handwriting font popular since the early 2010s.",
  "permanent-marker": "Designed to look like text written with a felt-tip marker pen.",
  anton: "An extra-bold condensed sans built for big, punchy headlines.",
  righteous: "A rounded display face inspired by 1930s Art Deco poster lettering.",
  bangers: "Modeled on the hand-lettering found in vintage comic books.",
  fredoka: "A rounded, playful display font popular in casual app branding.",
  comfortaa: "A geometric rounded sans built almost entirely from circular shapes.",
  quicksand: "A display sans built from simple geometric circles and lines.",
  "josefin-sans": "Inspired by geometric typefaces popular in 1930s fashion advertising.",
  cabin: "A humanist sans influenced by classics like Gill Sans and Edward Johnston.",
  "pt-sans": "Commissioned for a public project supporting both Cyrillic and Latin text.",
  "source-sans-pro": "Adobe's first typeface released as open-source.",
  "crimson-text": "An old-style serif inspired by late Renaissance book printing.",
  "libre-baskerville": "A redesign of the classic 18th-century Baskerville for screen reading.",
  "cormorant-garamond": "A display revival inspired by Claude Garamont's Renaissance-era type.",
  "abril-fatface": "An ultra-bold 'fatface' style drawn from 19th-century poster lettering.",
  "archivo-black": "The heaviest weight of a grotesque family, built for maximum impact.",
  "passion-one": "A bold, rounded display face made for punchy short headlines.",
  "alfa-slab-one": "An extra-heavy slab serif designed for large-scale display text.",
  shrikhand: "Its bold, curvy shapes are named after a creamy Indian sweet dish.",
  "zilla-slab": "Commissioned by Mozilla for its web properties.",
  rubik: "A geometric sans with slightly rounded corners on its letterforms.",
  karla: "A grotesque sans with distinctive, slightly quirky curves.",
  "dm-serif-display": "A high-contrast display serif companion to the DM Sans family.",
  spectral: "An old-style serif designed specifically for comfortable on-screen reading.",
  vollkorn: "One of the first freely licensed Google Fonts; its name means 'whole grain' in German.",
  bitter: "A slab serif originally built for comfortable reading on screens.",
  sarabun: "Adopted as an official typeface for Thai government documents.",
  chivo: "A grotesque sans-serif originally designed in Argentina.",
  barlow: "Inspired by the lettering on California license plates and highway signs.",
  manrope: "An open-source geometric sans released as a variable font.",
  "work-sans": "Optimized for on-screen text at medium sizes, like interfaces.",
  "ibm-plex-sans": "IBM's first custom corporate typeface, replacing Helvetica in its branding.",
  "space-mono": "A monospaced font drawing on mid-century American display lettering.",
  "jetbrains-mono": "Designed to reduce eye strain for programmers reading code all day.",
  inconsolata: "A widely used monospaced font designed by a single independent type designer.",
  syne: "Commissioned for the visual identity of a Paris contemporary art center.",
  unbounded: "A variable font with a distinctly blocky, geometric display look.",
  "familjen-grotesk": "Designed by a Swedish studio; 'familjen' means 'the family' in Swedish.",
  fraunces: "A deliberately 'wonky' old-style serif designed to feel warm and human.",
  sora: "A rounded geometric sans built for a clean, modern interface look.",
  outfit: "A geometric sans-serif designed for clean, modern UI use.",
  "plus-jakarta-sans": "Commissioned as the official typeface for the city of Jakarta.",
  lexend: "Designed based on reading-research studies aimed at improving reading proficiency.",
  onest: "A neutral, modern grotesque built for everyday interface use.",
  "instrument-serif": "A display serif with quirky, hand-finished touches on its letters.",
  "bricolage-grotesque": "A variable grotesque font with a playful, hand-assembled feel.",
  "schibsted-grotesk": "Commissioned by the Scandinavian media company Schibsted.",
  newsreader: "A serif specifically designed to mimic classic newspaper article text.",
  literata: "Originally commissioned by Google specifically for reading e-books.",
  recursive: "A single variable font that can morph between monospace and proportional styles.",
  "hanken-grotesk": "A neutral, minimal grotesque sans built for clean branding.",
  "red-hat-display": "Commissioned by the tech company Red Hat for its corporate branding.",
  "space-grotesk": "A proportional sans redrawn from the fixed-width Space Mono.",
};

export default FONTS_E87_FACTS;
