// Episode 4 "Guess the Food" — one verified ≤70-char fact per dish, keyed by slug.
// Verified via 4 parallel research agents (WebSearch-sourced) + quiz-fact-verifier pass.
export const FOODS_E04_FACTS = {
  // EASY
  "pizza": "Margherita pizza's royal-queen origin story is likely a forgery.",
  "hamburger": "Hamburg, Germany gave the burger its name, not its bun.",
  "french-fries": "Belgium claims fries were invented before France did.",
  "ice-cream-cone": "Ice cream cones existed years before their famous 1904 fair debut.",
  "sushi": "Sushi first meant fermented fish preserved in rice, not raw fish.",
  "spaghetti-with-tomato-sauce": "Tomatoes were once feared as poisonous in Europe.",
  "fried-chicken": "Fried chicken blends Scottish and West African cooking.",
  "hot-dog": "The hot dog name's cartoonist origin story is a myth.",
  "donut": "A sea captain claims he invented the donut hole in 1847.",
  "tacos": "\"Taco\" may have named a mining gunpowder charge, historians say.",
  "pancakes": "Olney's pancake race for women has run since 1445.",
  "popcorn": "Popcorn remains have been found dating back 6,700 years.",
  "croissant": "The croissant descends from Austria's kipferl, not France.",
  "fried-egg": "\"Sunny side up\" got its name from the yolk's sun-like look.",
  "waffles": "Medieval waffle irons were engraved with family coats of arms.",
  "chocolate-cake": "Devil's food cake got its name as chocolate's answer to angel food.",
  "nachos": "Nachos were invented in 1943 when the chef was away.",
  "burrito": "\"Burrito\" literally translates to \"little donkey\" in Spanish.",
  "lasagna": "The earliest lasagna-like recipe on record is English.",
  "soft-pretzel": "Pretzels' twisted shape is said to mimic arms in prayer.",
  "apple-pie": "Apples aren't native to America, they came from Asia.",
  "bacon-and-eggs": "A 1920s PR campaign made bacon and eggs the classic breakfast.",
  "grilled-cheese-sandwich": "Grilled cheese was once open-faced, until the 1960s.",
  "french-toast": "French toast's name existed before its popular origin myth.",
  "chicken-wings": "Buffalo wings were invented in 1964 by a bar owner's wife.",

  // MEDIUM
  "ramen": "Japan voted instant ramen its top 20th-century invention.",
  "fish-and-chips": "Churchill refused to ration fish and chips in WWII.",
  "paella": "Paella is Valencian for 'frying pan,' not the dish.",
  "fajitas": "Fajitas began as ranch hands' pay in 1930s Texas.",
  "guacamole": "Guacamole means 'avocado sauce' in Aztec Nahuatl.",
  "churros": "Churros are named after horned Spanish sheep.",
  "doner-kebab": "Berlin, not Turkey, claims to have invented doner kebab.",
  "pad-thai": "Pad Thai was created by a 1930s nationalist campaign.",
  "shawarma": "Shawarma's name means 'turning' in Turkish.",
  "dumplings": "Chinese dumplings are shaped like ancient gold ingots.",
  "baklava": "Ottoman sultans gave soldiers baklava each Ramadan.",
  "spring-rolls": "Spring rolls symbolize gold bars for Lunar New Year.",
  "peking-duck": "Peking duck is traditionally carved into 108 slices.",
  "falafel": "The largest falafel ever made weighed over 100 kg.",
  "samosa": "Samosas were praised by a poet in India's Delhi Sultanate.",
  "chicken-biryani": "Biryani's name means 'fried' in Persian.",
  "tom-yum-soup": "Tom yum literally means 'boil' plus 'mix' in Thai.",
  "risotto": "Italy's first risotto recipe wasn't written until 1809.",
  "miso-soup": "Samurai carried portable miso soup into battle.",
  "tempura": "Tempura came from Portuguese Catholic fasting food.",
  "hummus": "The oldest hummus recipe is from 13th-century Syria.",
  "pho": "Pho's name origin is debated: French or Cantonese.",
  "pierogi": "Pierogi are one of Poland's 12 sacred Christmas dishes.",
  "gnocchi": "Roman soldiers ate gnocchi centuries before potatoes.",
  "goulash": "Goulash began as dried meat carried by Hungarian herders.",

  // HARD
  "bibimbap": "Kimchi was specially irradiated germ-free for a Korean astronaut.",
  "ceviche": "Peru declared ceviche a national cultural treasure in 2004.",
  "poutine": "In Quebec slang, 'poutine' literally means 'a mess'.",
  "beef-wellington": "Beef Wellington's first known recipe appeared in 1940.",
  "shakshuka": "Shakshuka's name means 'all mixed up' in Arabic.",
  "takoyaki": "Takoyaki was invented in 1935 by an Osaka street vendor.",
  "xiaolongbao": "Xiaolongbao's soup comes from broth chilled into jelly.",
  "borscht": "UNESCO fast-tracked Ukrainian borscht as heritage in 2022.",
  "tteokbokki": "Original tteokbokki was a mild, non-spicy royal dish.",
  "tagine": "A tagine is named after the clay pot, not the food.",
  "okonomiyaki": "Okonomiyaki means 'cooked how you like it' in Japanese.",
  "laksa": "Penang's assam laksa ranked CNN's 7th-best food on Earth.",
  "arepa": "Arepas date back roughly 3,000 years in South America.",
  "haggis": "Haggis hurling began in 1977 as a practical joke.",
  "feijoada": "Feijoada's 'invented by slaves' origin story is a myth.",
  "currywurst": "Currywurst's secret sauce recipe died with its creator.",
  "nasi-goreng": "Nasi goreng was one of Obama's favorite childhood meals.",
  "injera-with-wat": "Injera serves as Ethiopia's edible plate and utensil.",
  "bouillabaisse": "Bouillabaisse began as a stew of fish nobody would buy.",
  "dolma": "Dolma's name just means 'stuffed' in Turkish.",
  "rendang": "Rendang was voted the world's tastiest food by CNN.",
  "jollof-rice": "Jollof rice traces its roots to West Africa's Senegambia region.",
  "adobo": "Adobo existed in the Philippines before Spanish rule.",
  "pupusa": "El Salvador has an official National Pupusa Day.",
  "khachapuri": "Georgia has dozens of regional khachapuri variations.",

  // IMPOSSIBLE
  "cuy-roasted-guinea-pig": "A Cusco Cathedral painting shows Jesus's Last Supper with guinea pig.",
  "century-egg": "Century eggs cure in weeks, not the 100 years the name implies.",
  "balut": "Balut was introduced to the Philippines by Chinese traders in 1565.",
  "fugu-sashimi": "Most fugu poisonings in Japan trace back to amateur home cooks.",
  "natto": "Natto has over 100 times more vitamin K2 than most cheeses.",
  "rocky-mountain-oysters": "The related 'mountain oyster' nickname dates back to 1857.",
  "stinky-tofu": "A 2012 study found 39 chemical compounds in stinky tofu's smell.",
  "shark-fin-soup": "Shark fins are flavorless; all the taste comes from the broth.",
  "sannakji": "Sannakji's tentacles can still grip a throat after being cut.",
  "surstromming": "In 2014, a warehouse fire made 1,000 surstromming cans explode.",
  "chapulines": "Oaxacans have eaten chapulines for over 3,000 years.",
  "beondegi": "Beondegi used pupae left over from Korea's silk industry.",
  "lutefisk": "Lutefisk was first documented in Norway back in 1555.",
  "hakarl": "Hakarl comes from a shark that's toxic before fermenting.",
  "fried-tarantula": "Cambodia's fried-tarantula tradition began in Khmer Rouge famine.",
  "hongeohoe-fermented-skate": "Hongeo ferments in its own urea, since skates lack bladders.",
  "casu-marzu": "Casu marzu's live maggots can leap up to 6 inches when disturbed.",
  "escamoles": "Escamoles are nicknamed 'the farty ant' larvae in Mexico.",
  "huitlacoche": "Huitlacoche roughly means 'sleeping excrescence' in Nahuatl.",
  "pacha-sheep-head-soup": "In pacha, the sheep's cheeks and tongue are prized parts.",
  "fesikh": "In 1991, tainted fesikh killed 18 people in one Egyptian holiday.",
  "witchetty-grub": "Just 10 witchetty grubs cover an adult's daily protein needs.",
  "mopane-worms": "Mopane worms have roughly 3x more protein than beef.",
  "rakfisk": "Rakfisk has been recorded in Norway since as early as 1348.",
  "ikizukuri": "Ikizukuri fish are served with gills still moving on the plate.",
};
export default FOODS_E04_FACTS;
