// Episode 4 "Guess the Food" — 100 items, absolute-difficulty calibrated (25/tier).
// Judged by global visual recognizability of the dish as photographed.
export const FOODS_E04 = [
  // EASY (25)
  { slug: "pizza", name: "Pizza", level: "easy" },
  { slug: "hamburger", name: "Hamburger", level: "easy" },
  { slug: "french-fries", name: "French Fries", level: "easy" },
  { slug: "ice-cream-cone", name: "Ice Cream Cone", level: "easy" },
  { slug: "sushi", name: "Sushi", level: "easy" },
  { slug: "spaghetti-with-tomato-sauce", name: "Spaghetti with Tomato Sauce", level: "easy" },
  { slug: "fried-chicken", name: "Fried Chicken", level: "easy" },
  { slug: "hot-dog", name: "Hot Dog", level: "easy" },
  { slug: "donut", name: "Donut", level: "easy" },
  { slug: "tacos", name: "Tacos", level: "easy" },
  { slug: "pancakes", name: "Pancakes", level: "easy" },
  { slug: "popcorn", name: "Popcorn", level: "easy" },
  { slug: "croissant", name: "Croissant", level: "easy" },
  { slug: "fried-egg", name: "Fried Egg", level: "easy" },
  { slug: "waffles", name: "Waffles", level: "easy" },
  { slug: "chocolate-cake", name: "Chocolate Cake", level: "easy" },
  { slug: "nachos", name: "Nachos", level: "easy" },
  { slug: "burrito", name: "Burrito", level: "easy" },
  { slug: "lasagna", name: "Lasagna", level: "easy" },
  { slug: "soft-pretzel", name: "Soft Pretzel", level: "easy" },
  { slug: "apple-pie", name: "Apple Pie", level: "easy" },
  { slug: "bacon-and-eggs", name: "Bacon and Eggs", level: "easy" },
  { slug: "grilled-cheese-sandwich", name: "Grilled Cheese Sandwich", level: "easy" },
  { slug: "french-toast", name: "French Toast", level: "easy" },
  { slug: "chicken-wings", name: "Chicken Wings", level: "easy" },

  // MEDIUM (25)
  { slug: "ramen", name: "Ramen", level: "medium" },
  { slug: "fish-and-chips", name: "Fish and Chips", level: "medium" },
  { slug: "paella", name: "Paella", level: "medium" },
  { slug: "fajitas", name: "Fajitas", level: "medium" },
  { slug: "guacamole", name: "Guacamole", level: "medium" },
  { slug: "churros", name: "Churros", level: "medium" },
  { slug: "doner-kebab", name: "Doner Kebab", level: "medium" },
  { slug: "pad-thai", name: "Pad Thai", level: "medium" },
  { slug: "shawarma", name: "Shawarma", level: "medium" },
  { slug: "dumplings", name: "Dumplings", level: "medium" },
  { slug: "baklava", name: "Baklava", level: "medium" },
  { slug: "spring-rolls", name: "Spring Rolls", level: "medium" },
  { slug: "peking-duck", name: "Peking Duck", level: "medium" },
  { slug: "falafel", name: "Falafel", level: "medium" },
  { slug: "samosa", name: "Samosa", level: "medium" },
  { slug: "chicken-biryani", name: "Chicken Biryani", level: "medium" },
  { slug: "tom-yum-soup", name: "Tom Yum Soup", level: "medium" },
  { slug: "risotto", name: "Risotto", level: "medium" },
  { slug: "miso-soup", name: "Miso Soup", level: "medium" },
  { slug: "tempura", name: "Tempura", level: "medium" },
  { slug: "hummus", name: "Hummus", level: "medium" },
  { slug: "pho", name: "Pho", level: "medium" },
  { slug: "pierogi", name: "Pierogi", level: "medium" },
  { slug: "gnocchi", name: "Gnocchi", level: "medium" },
  { slug: "goulash", name: "Goulash", level: "medium" },

  // HARD (25)
  { slug: "bibimbap", name: "Bibimbap", level: "hard" },
  { slug: "ceviche", name: "Ceviche", level: "hard" },
  { slug: "poutine", name: "Poutine", level: "hard" },
  { slug: "beef-wellington", name: "Beef Wellington", level: "hard" },
  { slug: "shakshuka", name: "Shakshuka", level: "hard" },
  { slug: "takoyaki", name: "Takoyaki", level: "hard" },
  { slug: "xiaolongbao", name: "Xiaolongbao", level: "hard" },
  { slug: "borscht", name: "Borscht", level: "hard" },
  { slug: "tteokbokki", name: "Tteokbokki", level: "hard" },
  { slug: "tagine", name: "Tagine", level: "hard" },
  { slug: "okonomiyaki", name: "Okonomiyaki", level: "hard" },
  { slug: "laksa", name: "Laksa", level: "hard" },
  { slug: "arepa", name: "Arepa", level: "hard" },
  { slug: "haggis", name: "Haggis", level: "hard" },
  { slug: "feijoada", name: "Feijoada", level: "hard" },
  { slug: "currywurst", name: "Currywurst", level: "hard" },
  { slug: "nasi-goreng", name: "Nasi Goreng", level: "hard" },
  { slug: "injera-with-wat", name: "Injera with Wat", level: "hard" },
  { slug: "bouillabaisse", name: "Bouillabaisse", level: "hard" },
  { slug: "dolma", name: "Dolma", level: "hard" },
  { slug: "rendang", name: "Rendang", level: "hard" },
  { slug: "jollof-rice", name: "Jollof Rice", level: "hard" },
  { slug: "adobo", name: "Adobo", level: "hard" },
  { slug: "pupusa", name: "Pupusa", level: "hard" },
  { slug: "khachapuri", name: "Khachapuri", level: "hard" },

  // IMPOSSIBLE (25)
  { slug: "cuy-roasted-guinea-pig", name: "Cuy (Roasted Guinea Pig)", level: "impossible" },
  { slug: "century-egg", name: "Century Egg", level: "impossible" },
  { slug: "balut", name: "Balut", level: "impossible" },
  { slug: "fugu-sashimi", name: "Fugu Sashimi", level: "impossible" },
  { slug: "natto", name: "Natto", level: "impossible" },
  { slug: "rocky-mountain-oysters", name: "Rocky Mountain Oysters", level: "impossible" },
  { slug: "stinky-tofu", name: "Stinky Tofu", level: "impossible" },
  { slug: "shark-fin-soup", name: "Shark Fin Soup", level: "impossible" },
  { slug: "sannakji", name: "Sannakji", level: "impossible" },
  { slug: "surstromming", name: "Surströmming", level: "impossible" },
  { slug: "chapulines", name: "Chapulines", level: "impossible" },
  { slug: "beondegi", name: "Beondegi", level: "impossible" },
  { slug: "lutefisk", name: "Lutefisk", level: "impossible" },
  { slug: "hakarl", name: "Hákarl", level: "impossible" },
  { slug: "fried-tarantula", name: "Fried Tarantula", level: "impossible" },
  { slug: "hongeohoe-fermented-skate", name: "Hongeohoe", level: "impossible" },
  { slug: "casu-marzu", name: "Casu Marzu", level: "impossible" },
  { slug: "escamoles", name: "Escamoles", level: "impossible" },
  { slug: "huitlacoche", name: "Huitlacoche", level: "impossible" },
  { slug: "pacha-sheep-head-soup", name: "Pacha", level: "impossible" },
  { slug: "fesikh", name: "Fesikh", level: "impossible" },
  { slug: "witchetty-grub", name: "Witchetty Grub", level: "impossible" },
  { slug: "mopane-worms", name: "Mopane Worms", level: "impossible" },
  { slug: "rakfisk", name: "Rakfisk", level: "impossible" },
  { slug: "ikizukuri", name: "Ikizukuri", level: "impossible" },
];
export default FOODS_E04;
