export const FORTS_E63_FACTS = {
  // EASY
  "red-fort": "Where India's Prime Minister raises the flag every Independence Day.",
  "tower-of-london": "Once held the Crown Jewels and famous royal prisoners.",
  "el-morro-san-juan": "A 16th-century Spanish citadel guarding San Juan Bay.",
  "citadel-of-aleppo": "One of the world's oldest and largest castles.",
  "fort-santiago": "A Spanish citadel where national hero José Rizal was held.",
  "fortaleza-santa-catalina": "Guards the entrance to Salvador's Bay of All Saints.",
  "castel-sant-angelo": "Built as a mausoleum, later used as a papal fortress.",
  "amber-fort": "Built from pale yellow and pink sandstone near Jaipur.",
  "fort-jesus": "A Portuguese fort shaped like a human figure.",
  "fort-george": "An 18th-century Highland fortress near Inverness.",
  "citadel-of-quebec": "North America's largest British-era fortress.",
  "fort-sumter": "Where the first shots of the American Civil War were fired.",
  "golconda-fort": "Once famous for trading the world's finest diamonds.",
  "fortress-of-suomenlinna": "A sea fortress spread across six islands in Helsinki.",
  "fort-cochin": "A coastal fort shaped by Portuguese, Dutch, and British rule.",
  "castillo-de-san-marcos": "The oldest masonry fort in the continental United States.",
  "fort-alcatraz": "A former military fort turned notorious federal prison.",
  "edinburgh-castle": "Sits atop an extinct volcano overlooking the city.",

  // MEDIUM
  "fort-canning": "Sits atop a hill once home to ancient Malay kings.",
  "fort-zeelandia": "The Dutch colonial fort that gave old Taiwan its name.",
  "fort-jodhpur-mehrangarh": "Rises dramatically atop a rocky hill in Rajasthan.",
  "fort-manoel": "A star-shaped fortress built by the Knights of Malta.",
  "castle-of-good-hope": "The oldest surviving colonial building in South Africa.",
  "fortaleza-de-san-carlos": "One of the largest Spanish forts ever built in the Americas.",
  "fort-william-calcutta": "An octagonal fort built by the British East India Company.",
  "citadel-of-erbil": "One of the longest continuously inhabited sites on Earth.",
  "fort-santa-cruz-oran": "A French-built fort overlooking Oran's harbor.",
  "fort-rosecrans": "Guards the entrance to San Diego Bay.",
  "citadel-of-lille": "Designed by the master military engineer Vauban.",
  "fort-carre": "A star-shaped fort overlooking Antibes' harbor.",
  "fortress-of-louisbourg": "A rebuilt 18th-century French fortress in Nova Scotia.",
  "elmina-castle": "The oldest European building south of the Sahara.",
  "fort-santiago-de-bocachica": "Guards a narrow channel into Cartagena's bay.",
  "fort-jaisalmer": "A living fort still home to thousands of residents.",
  "fort-belvedere-florence": "A Medici-built fortress overlooking Florence.",
  "fort-george-bermuda": "One of several forts once called 'Gibraltar of the West'.",

  // HARD
  "fort-santa-barbara-alicante": "A hilltop castle overlooking Alicante's beaches.",
  "fort-ricasoli": "One of the largest fortifications built by the Knights of Malta.",
  "fort-augustus-scotland": "A Highland fort that gave a Scottish town its name.",
  "fort-tigne": "A star-shaped fort at the tip of Sliema.",
  "fort-santa-cruz-lisbon": "Guards the mouth of the Tagus River.",
  "fort-galle": "A Dutch-built fort encircling an entire old town.",
  "fort-sao-miguel": "A Portuguese colonial fort overlooking Luanda's bay.",
  "fort-mosede": "A Danish coastal fort built to guard Copenhagen.",
  "fort-drum-philippines": "A concrete warship-shaped fort in Manila Bay.",
  "fort-shirvan-baku": "A walled fortress at the heart of Baku's old city.",
  "fort-cornwallis": "A star-shaped fort marking Penang's founding.",
  "fort-tholen-netherlands": "A star-shaped fortified town in the Netherlands.",
  "fort-santa-elena-cartagena": "The largest fort ever built by the Spanish in the Americas.",
  "fort-santo-antonio-macau": "A 17th-century fort now overlooking Macau's skyline.",
  "fort-sao-filipe-cabo-verde": "Overlooks the historic town of Cidade Velha.",
  "fort-nagle": "A small coastal battery guarding Malta's Grand Harbour.",
  "fort-jefferson-florida": "The largest brick masonry structure in the Americas.",
  "fort-santiago-manila-alt": "A colonial fort in Mexico's Veracruz coast.",

  // IMPOSSIBLE
  "fort-frederiksted": "A Danish fort on the western tip of St. Croix.",
  "fort-cristobal-puerto-rico": "The largest fortification built by Spain in the New World.",
  "fort-oranje-aruba": "A small 17th-century Dutch fort in Oranjestad.",
  "fort-amsterdam-curacao": "Houses the governor's residence in Willemstad.",
  "fort-zoutman-aruba": "Aruba's oldest surviving building.",
  "fort-christiansborg-ghana": "A former Danish castle later used as Ghana's seat of government.",
  "fort-sao-sebastiao-mozambique": "One of the oldest European buildings in the Southern Hemisphere.",
  "fort-victoria-mahe": "Guards the harbor of Victoria, Seychelles' capital.",
  "fort-santiago-annobon": "A colonial-era fort overlooking Colonia, Uruguay.",
  "fort-james-gambia": "A former slave-trading fort on an island in the Gambia River.",
  "fort-frederik-hendrik": "A Dutch fort guarding Suriname's Coppename River.",
  "fort-zeelandia-suriname": "Guards the historic center of Paramaribo.",
  "fort-nassau-ghana": "The first Dutch fort built on the Gold Coast.",
  "fort-san-lorenzo-panama": "Guards the mouth of the Chagres River.",
  "fort-santa-teresa-uruguay": "One of South America's largest colonial fortresses.",
  "fort-san-domingo-tamsui": "A red fort in Tamsui, first built by the Spanish in 1629.",
};

export default FORTS_E63_FACTS;
