// E63 "Guess the Fort" — 70 real, standing forts/fortresses worldwide.
// Absolute difficulty: easy = globally iconic (~70-95% recognition of the shown structure),
// impossible = genuinely obscure regional forts (<10%, most <3%).
// Zero Israel content (standing hard rule, all episodes).
export const FORTS_E63 = [
  // EASY (18)
  { slug: "red-fort", name: "Red Fort", country: "India", level: "easy" },
  { slug: "tower-of-london", name: "Tower of London", country: "United Kingdom", level: "easy" },
  { slug: "el-morro-san-juan", name: "Castillo San Felipe del Morro", country: "Puerto Rico", level: "easy" },
  { slug: "citadel-of-aleppo", name: "Citadel of Aleppo", country: "Syria", level: "easy" },
  { slug: "fort-santiago", name: "Fort Santiago", country: "Philippines", level: "easy" },
  { slug: "fortaleza-santa-catalina", name: "Fortaleza de Santa Catalina", country: "Brazil", level: "easy" },
  { slug: "castel-sant-angelo", name: "Castel Sant'Angelo", country: "Italy", level: "easy" },
  { slug: "amber-fort", name: "Amber Fort", country: "India", level: "easy" },
  { slug: "fort-jesus", name: "Fort Jesus", country: "Kenya", level: "easy" },
  { slug: "fort-george", name: "Fort George (Scotland)", country: "United Kingdom", level: "easy" },
  { slug: "citadel-of-quebec", name: "Citadelle of Quebec", country: "Canada", level: "easy" },
  { slug: "fort-sumter", name: "Fort Sumter", country: "USA", level: "easy" },
  { slug: "golconda-fort", name: "Golconda Fort", country: "India", level: "easy" },
  { slug: "fortress-of-suomenlinna", name: "Suomenlinna", country: "Finland", level: "easy" },
  { slug: "sigiriya-rock-fortress", name: "Sigiriya", country: "Sri Lanka", level: "easy" },
  { slug: "castillo-de-san-marcos", name: "Castillo de San Marcos", country: "USA", level: "easy" },
  { slug: "fort-alcatraz", name: "Alcatraz", country: "USA", level: "easy" },
  { slug: "edinburgh-castle", name: "Edinburgh Castle", country: "United Kingdom", level: "easy" },

  // MEDIUM (18)
  { slug: "fort-canning", name: "Fort Canning", country: "Singapore", level: "medium" },
  { slug: "fort-zeelandia", name: "Fort Zeelandia (Taiwan)", country: "Taiwan", level: "medium" },
  { slug: "fort-jodhpur-mehrangarh", name: "Mehrangarh Fort", country: "India", level: "medium" },
  { slug: "fort-manoel", name: "Fort Manoel", country: "Malta", level: "medium" },
  { slug: "castle-of-good-hope", name: "Castle of Good Hope", country: "South Africa", level: "medium" },
  { slug: "fortaleza-de-san-carlos", name: "Fortaleza San Carlos de la Cabaña", country: "Cuba", level: "medium" },
  { slug: "trakai-island-castle", name: "Trakai Island Castle", country: "Lithuania", level: "medium" },
  { slug: "citadel-of-erbil", name: "Citadel of Erbil", country: "Iraq", level: "medium" },
  { slug: "fort-santa-cruz-oran", name: "Fort Santa Cruz", country: "Algeria", level: "medium" },
  { slug: "fort-rosecrans", name: "Fort Rosecrans", country: "USA", level: "medium" },
  { slug: "citadel-of-lille", name: "Citadel of Lille", country: "France", level: "medium" },
  { slug: "fort-carre", name: "Fort Carré", country: "France", level: "medium" },
  { slug: "fortress-of-louisbourg", name: "Fortress of Louisbourg", country: "Canada", level: "medium" },
  { slug: "elmina-castle", name: "Elmina Castle", country: "Ghana", level: "medium" },
  { slug: "fort-santiago-de-bocachica", name: "Fuerte de San Fernando de Bocachica", country: "Colombia", level: "medium" },
  { slug: "fort-jaisalmer", name: "Jaisalmer Fort", country: "India", level: "medium" },
  { slug: "fort-belvedere-florence", name: "Forte di Belvedere", country: "Italy", level: "medium" },
  { slug: "fort-george-bermuda", name: "Fort George (Bermuda)", country: "Bermuda", level: "medium" },

  // HARD (18)
  { slug: "fort-santa-barbara-alicante", name: "Santa Bárbara Castle", country: "Spain", level: "hard" },
  { slug: "fort-ricasoli", name: "Fort Ricasoli", country: "Malta", level: "hard" },
  { slug: "fort-fredriksten-norway", name: "Fort Fredriksten", country: "Norway", level: "hard" },
  { slug: "fort-tigne", name: "Fort Tigné", country: "Malta", level: "hard" },
  { slug: "fort-santa-cruz-lisbon", name: "Forte de São Julião da Barra", country: "Portugal", level: "hard" },
  { slug: "fort-galle", name: "Galle Fort", country: "Sri Lanka", level: "hard" },
  { slug: "fort-sao-miguel", name: "Forte de São Miguel", country: "Angola", level: "hard" },
  { slug: "fort-mosede", name: "Mosede Fort", country: "Denmark", level: "hard" },
  { slug: "fort-drum-philippines", name: "Fort Drum", country: "Philippines", level: "hard" },
  { slug: "maiden-tower-baku", name: "Maiden Tower", country: "Azerbaijan", level: "hard" },
  { slug: "fort-cornwallis", name: "Fort Cornwallis", country: "Malaysia", level: "hard" },
  { slug: "fort-tholen-netherlands", name: "Fort Bourtange", country: "Netherlands", level: "hard" },
  { slug: "fort-santa-elena-cartagena", name: "Castillo de San Felipe de Barajas", country: "Colombia", level: "hard" },
  { slug: "fort-santo-antonio-macau", name: "Fortaleza do Monte", country: "Macau", level: "hard" },
  { slug: "fort-sao-filipe-cabo-verde", name: "Real Forte de São Filipe", country: "Cape Verde", level: "hard" },
  { slug: "fort-nagle", name: "Fort Nagle", country: "Malta", level: "hard" },
  { slug: "fort-jefferson-florida", name: "Fort Jefferson", country: "USA", level: "hard" },
  { slug: "fuerte-san-diego-acapulco", name: "Fuerte de San Diego", country: "Mexico", level: "hard" },

  // IMPOSSIBLE (16)
  { slug: "fort-frederiksted", name: "Fort Frederik", country: "US Virgin Islands", level: "impossible" },
  { slug: "fort-cristobal-puerto-rico", name: "Castillo San Cristóbal", country: "Puerto Rico", level: "impossible" },
  { slug: "fort-oranje-bonaire", name: "Fort Oranje", country: "Bonaire", level: "impossible" },
  { slug: "fort-amsterdam-curacao", name: "Fort Amsterdam", country: "Curaçao", level: "impossible" },
  { slug: "fort-zoutman-aruba", name: "Fort Zoutman", country: "Aruba", level: "impossible" },
  { slug: "fort-christiansborg-ghana", name: "Christiansborg Castle", country: "Ghana", level: "impossible" },
  { slug: "fort-sao-sebastiao-mozambique", name: "Fort São Sebastião", country: "Mozambique", level: "impossible" },
  { slug: "moorish-castle-gibraltar", name: "Moorish Castle", country: "Gibraltar", level: "impossible" },
  { slug: "fortaleza-de-san-miguel-uruguay", name: "Fortaleza de San Miguel", country: "Uruguay", level: "impossible" },
  { slug: "fort-james-gambia", name: "Fort James", country: "The Gambia", level: "impossible" },
  { slug: "fort-frederik-hendrik", name: "Fort Frederik Hendrik", country: "Mauritius", level: "impossible" },
  { slug: "fort-zeelandia-suriname", name: "Fort Zeelandia (Suriname)", country: "Suriname", level: "impossible" },
  { slug: "fort-nassau-ghana", name: "Fort Nassau", country: "Ghana", level: "impossible" },
  { slug: "fort-san-lorenzo-panama", name: "Fort San Lorenzo", country: "Panama", level: "impossible" },
  { slug: "fort-santa-teresa-uruguay", name: "Fortaleza de Santa Teresa", country: "Uruguay", level: "impossible" },
  { slug: "fort-san-domingo-tamsui", name: "Fort San Domingo", country: "Taiwan", level: "impossible" },
];

export default FORTS_E63;
