// E43 "Guess the Fruit" — real whole-fruit photos (not cross-sections/cut).
// Cross-section-risk sourcing note (image step): watermelon, kiwifruit, coconut, papaya,
// pomegranate, avocado, dragon-fruit, passion-fruit, guava, fig, tamarind, custard-apple,
// jackfruit, grapefruit, mangosteen, soursop, prickly-pear, cherimoya, cupuacu, star-fruit,
// salak, horned-melon — default Wikipedia photos for these often show the fruit halved;
// deliberately Commons-search for the whole/uncut variant.
export const FRUITS_E43 = [
  // EASY (18)
  { slug: "apple", name: "Apple", level: "easy" },
  { slug: "banana", name: "Banana", level: "easy" },
  { slug: "orange", name: "Orange", level: "easy" },
  { slug: "strawberry", name: "Strawberry", level: "easy" },
  { slug: "grape", name: "Grape", level: "easy" },
  { slug: "watermelon", name: "Watermelon", level: "easy" },
  { slug: "pineapple", name: "Pineapple", level: "easy" },
  { slug: "mango", name: "Mango", level: "easy" },
  { slug: "lemon", name: "Lemon", level: "easy" },
  { slug: "peach", name: "Peach", level: "easy" },
  { slug: "pear", name: "Pear", level: "easy" },
  { slug: "cherry", name: "Cherry", level: "easy" },
  { slug: "coconut", name: "Coconut", level: "easy" },
  { slug: "kiwifruit", name: "Kiwifruit", level: "easy" },
  { slug: "avocado", name: "Avocado", level: "easy" },
  { slug: "blueberry", name: "Blueberry", level: "easy" },
  { slug: "lime", name: "Lime", level: "easy" },
  { slug: "pomegranate", name: "Pomegranate", level: "easy" },

  // MEDIUM (18)
  { slug: "papaya", name: "Papaya", level: "medium" },
  { slug: "raspberry", name: "Raspberry", level: "medium" },
  { slug: "blackberry", name: "Blackberry", level: "medium" },
  { slug: "cantaloupe", name: "Cantaloupe", level: "medium" },
  { slug: "honeydew-melon", name: "Honeydew Melon", level: "medium" },
  { slug: "grapefruit", name: "Grapefruit", level: "medium" },
  { slug: "fig", name: "Fig", level: "medium" },
  { slug: "plum", name: "Plum", level: "medium" },
  { slug: "apricot", name: "Apricot", level: "medium" },
  { slug: "passion-fruit", name: "Passion Fruit", level: "medium" },
  { slug: "guava", name: "Guava", level: "medium" },
  { slug: "dragon-fruit", name: "Dragon Fruit", level: "medium" },
  { slug: "persimmon", name: "Persimmon", level: "medium" },
  { slug: "pomelo", name: "Pomelo", level: "medium" },
  { slug: "tangerine", name: "Tangerine", level: "medium" },
  { slug: "cranberry", name: "Cranberry", level: "medium" },
  { slug: "nectarine", name: "Nectarine", level: "medium" },
  { slug: "lychee", name: "Lychee", level: "medium" },

  // HARD (18)
  { slug: "star-fruit", name: "Star Fruit", level: "hard" },
  { slug: "custard-apple", name: "Custard Apple", level: "hard" },
  { slug: "soursop", name: "Soursop", level: "hard" },
  { slug: "jackfruit", name: "Jackfruit", level: "hard" },
  { slug: "durian", name: "Durian", level: "hard" },
  { slug: "rambutan", name: "Rambutan", level: "hard" },
  { slug: "kumquat", name: "Kumquat", level: "hard" },
  { slug: "prickly-pear", name: "Prickly Pear", level: "hard" },
  { slug: "tamarind", name: "Tamarind", level: "hard" },
  { slug: "mangosteen", name: "Mangosteen", level: "hard" },
  { slug: "loquat", name: "Loquat", level: "hard" },
  { slug: "quince", name: "Quince", level: "hard" },
  { slug: "elderberry", name: "Elderberry", level: "hard" },
  { slug: "gooseberry", name: "Gooseberry", level: "hard" },
  { slug: "ackee", name: "Ackee", level: "hard" },
  { slug: "breadfruit", name: "Breadfruit", level: "hard" },
  { slug: "cherimoya", name: "Cherimoya", level: "hard" },
  { slug: "longan", name: "Longan", level: "hard" },

  // IMPOSSIBLE (17)
  { slug: "salak", name: "Salak", level: "impossible" },
  { slug: "horned-melon", name: "Horned Melon", level: "impossible" },
  { slug: "cupuacu", name: "Cupuaçu", level: "impossible" },
  { slug: "miracle-fruit", name: "Miracle Fruit", level: "impossible" },
  { slug: "buddhas-hand", name: "Buddha's Hand", level: "impossible" },
  { slug: "jabuticaba", name: "Jabuticaba", level: "impossible" },
  { slug: "feijoa", name: "Feijoa", level: "impossible" },
  { slug: "medlar", name: "Medlar", level: "impossible" },
  { slug: "pawpaw", name: "Pawpaw", level: "impossible" },
  { slug: "ugli-fruit", name: "Ugli Fruit", level: "impossible" },
  { slug: "langsat", name: "Langsat", level: "impossible" },
  { slug: "santol", name: "Santol", level: "impossible" },
  { slug: "marula", name: "Marula", level: "impossible" },
  { slug: "noni", name: "Noni", level: "impossible" },
  { slug: "genip", name: "Genip", level: "impossible" },
  { slug: "white-sapote", name: "White Sapote", level: "impossible" },
  { slug: "black-sapote", name: "Black Sapote", level: "impossible" },
];
