export const FRUITS_E43_FACTS = {
  "apple": "Apples float because they're about 25% air by volume.",
  "banana": "Bananas are classified as berries; strawberries aren't.",
  "orange": "Oranges stay green in fully tropical climates, even ripe.",
  "strawberry": "Strawberries carry their seeds on the outside, not inside.",
  "grape": "Grapes can spark and flame if microwaved improperly.",
  "watermelon": "Watermelon is about 92% water by weight.",
  "pineapple": "A pineapple takes roughly two years to fully mature.",
  "mango": "Mango trees can live and bear fruit for over 100 years.",
  "lemon": "Lemons are a natural hybrid of bitter orange and citron.",
  "peach": "Peaches belong to the rose family, Rosaceae.",
  "pear": "Pears ripen from the inside out, not outside in.",
  "cherry": "Cherry trees typically bloom for only about two weeks a year.",
  "coconut": "Coconuts can float and drift across oceans for months.",
  "kiwifruit": "Kiwifruit has more vitamin C than an orange, gram for gram.",
  "avocado": "Avocados are technically a single-seeded berry.",
  "blueberry": "Blueberries are one of the few naturally blue foods.",
  "lime": "Sailors once carried limes on ships to prevent scurvy.",
  "pomegranate": "Pomegranates typically hold 200 to 1,400 seeds inside.",

  "papaya": "Papaya seeds are edible and taste sharp and peppery.",
  "raspberry": "Each raspberry is made of about 100 tiny fruit segments.",
  "blackberry": "Blackberries turn from red to black as they ripen.",
  "cantaloupe": "True cantaloupes are mostly grown in Europe, not the US.",
  "honeydew-melon": "Honeydew is one of the few melons with smooth, waxy skin.",
  "grapefruit": "Grapefruit is named for growing in grape-like clusters.",
  "fig": "A fig is really a cluster of tiny flowers turned inward.",
  "plum": "Plums were among the first fruits ever domesticated.",
  "apricot": "Apricots are close relatives of peaches and almonds.",
  "passion-fruit": "Passion fruit vines can grow 15 to 20 feet in one season.",
  "guava": "Guava can hold four times the vitamin C of an orange.",
  "dragon-fruit": "Dragon fruit blooms only at night on a climbing cactus.",
  "persimmon": "Unripe persimmons taste extremely bitter and chalky.",
  "pomelo": "Pomelo is the largest citrus fruit, up to 25 cm wide.",
  "tangerine": "Tangerines are named after the port of Tangier, Morocco.",
  "cranberry": "Ripe cranberries bounce, a trick once used to test them.",
  "nectarine": "Nectarines are just peaches lacking the fuzzy-skin gene.",
  "lychee": "Lychee skin turns brown within days of being picked.",

  "star-fruit": "Sliced star fruit forms a near-perfect five-point star.",
  "custard-apple": "Custard apple flesh is often eaten straight with a spoon.",
  "soursop": "A single soursop fruit can grow larger than a human head.",
  "jackfruit": "Jackfruit is the largest tree-borne fruit in the world.",
  "durian": "Durian is banned on many public transit systems in Asia.",
  "rambutan": "Rambutan means 'hairy' in Malay, for its spiky skin.",
  "kumquat": "Kumquats are small enough to eat whole, peel and all.",
  "prickly-pear": "Prickly pear spines can be nearly invisible to the eye.",
  "tamarind": "Tamarind pulp is a key souring agent in cuisines worldwide.",
  "mangosteen": "Explorer David Fairchild nicknamed mangosteen the 'queen of fruits'.",
  "loquat": "Loquats ripen in spring, earlier than most tree fruit.",
  "quince": "Raw quince is too hard and sour to eat without cooking.",
  "elderberry": "Raw elderberries are mildly toxic and must be cooked first.",
  "gooseberry": "Gooseberries range from tart to sweet depending on ripeness.",
  "ackee": "Unripe ackee is toxic; it must open naturally to be safe.",
  "breadfruit": "Roasted breadfruit is often described as tasting like bread.",
  "cherimoya": "Mark Twain reportedly called cherimoya 'the most delicious'.",
  "longan": "Longan means 'dragon eye' for its dark, glossy seed.",

  "salak": "Salak is nicknamed 'snake fruit' for its scaly red skin.",
  "horned-melon": "Horned melon is also called kiwano or jelly melon.",
  "cupuacu": "Cupuaçu's aroma is often likened to chocolate and pineapple.",
  "miracle-fruit": "Miracle fruit makes sour foods taste sweet for about an hour.",
  "buddhas-hand": "Buddha's hand citrus has no juice, only fragrant peel.",
  "jabuticaba": "Jabuticaba fruit grows straight out of the tree's trunk.",
  "feijoa": "Feijoa tastes like a mix of pineapple, guava, and mint.",
  "medlar": "Medlars must soften and 'blet' before they're edible.",
  "pawpaw": "Pawpaw is North America's largest native edible fruit.",
  "ugli-fruit": "Ugli Fruit is a trademarked Jamaican citrus hybrid name.",
  "langsat": "Langsat grows in grape-like clusters on tropical trees.",
  "santol": "Santol's tangy pulp surrounds large seeds in a thick husk.",
  "marula": "Marula fruit ferments naturally after falling to the ground.",
  "noni": "Noni fruit is notorious for its strong, cheese-like odor.",
  "genip": "Genip is also called mamoncillo or Spanish lime.",
  "white-sapote": "White sapote tastes like a blend of banana and peach.",
  "black-sapote": "Black sapote is nicknamed the chocolate pudding fruit.",
};
