// E30 "Guess the Gaming Console" — answer = console/brand name, image = official console logo.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
export const GAMING_CONSOLE_LOGOS_E30 = [
  // EASY (18) — globally iconic gaming consoles
  { slug: "playstation", name: "PlayStation", level: "easy" },
  { slug: "xbox", name: "Xbox", level: "easy" },
  { slug: "nintendo-switch", name: "Nintendo Switch", level: "easy" },
  { slug: "wii", name: "Wii", level: "easy" },
  { slug: "game-boy", name: "Game Boy", level: "easy" },
  { slug: "nintendo-64", name: "Nintendo 64", level: "easy" },
  { slug: "sega-genesis", name: "Sega Genesis", level: "easy" },
  { slug: "playstation-2", name: "PlayStation 2", level: "easy" },
  { slug: "xbox-360", name: "Xbox 360", level: "easy" },
  { slug: "wii-u", name: "Wii U", level: "easy" },
  { slug: "nintendo-ds", name: "Nintendo DS", level: "easy" },
  { slug: "playstation-4", name: "PlayStation 4", level: "easy" },
  { slug: "xbox-one", name: "Xbox One", level: "easy" },
  { slug: "gamecube", name: "GameCube", level: "easy" },
  { slug: "sega-dreamcast", name: "Sega Dreamcast", level: "easy" },
  { slug: "atari-2600", name: "Atari 2600", level: "easy" },
  { slug: "playstation-5", name: "PlayStation 5", level: "easy" },
  { slug: "xbox-series-x", name: "Xbox Series X", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "super-nintendo", name: "Super Nintendo", level: "medium" },
  { slug: "nes", name: "Nintendo Entertainment System", level: "medium" },
  { slug: "sega-saturn", name: "Sega Saturn", level: "medium" },
  { slug: "sega-master-system", name: "Sega Master System", level: "medium" },
  { slug: "nintendo-3ds", name: "Nintendo 3DS", level: "medium" },
  { slug: "playstation-portable", name: "PlayStation Portable", level: "medium" },
  { slug: "playstation-vita", name: "PlayStation Vita", level: "medium" },
  { slug: "sega-game-gear", name: "Sega Game Gear", level: "medium" },
  { slug: "neo-geo", name: "Neo Geo", level: "medium" },
  { slug: "turbografx-16", name: "TurboGrafx-16", level: "medium" },
  { slug: "commodore-64", name: "Commodore 64", level: "medium" },
  { slug: "colecovision", name: "ColecoVision", level: "medium" },
  { slug: "intellivision", name: "Intellivision", level: "medium" },
  { slug: "virtual-boy", name: "Virtual Boy", level: "medium" },
  { slug: "steam-deck", name: "Steam Deck", level: "medium" },
  { slug: "nintendo-switch-lite", name: "Nintendo Switch Lite", level: "medium" },
  { slug: "playstation-3", name: "PlayStation 3", level: "medium" },
  { slug: "atari-5200", name: "Atari 5200", level: "medium" },

  // HARD (18) — recognizable to gaming enthusiasts
  { slug: "atari-7800", name: "Atari 7800", level: "hard" },
  { slug: "atari-jaguar", name: "Atari Jaguar", level: "hard" },
  { slug: "3do-interactive-multiplayer", name: "3DO Interactive Multiplayer", level: "hard" },
  { slug: "sega-32x", name: "Sega 32X", level: "hard" },
  { slug: "philips-cd-i", name: "Philips CD-i", level: "hard" },
  { slug: "nokia-n-gage", name: "Nokia N-Gage", level: "hard" },
  { slug: "wonderswan", name: "WonderSwan", level: "hard" },
  { slug: "neo-geo-pocket", name: "Neo Geo Pocket", level: "hard" },
  { slug: "magnavox-odyssey", name: "Magnavox Odyssey", level: "hard" },
  { slug: "vectrex", name: "Vectrex", level: "hard" },
  { slug: "atari-lynx", name: "Atari Lynx", level: "hard" },
  { slug: "sega-nomad", name: "Sega Nomad", level: "hard" },
  { slug: "pokemon-mini", name: "Pokémon Mini", level: "hard" },
  { slug: "gizmondo", name: "Gizmondo", level: "hard" },
  { slug: "ouya", name: "Ouya", level: "hard" },
  { slug: "nvidia-shield", name: "Nvidia Shield Portable", level: "hard" },
  { slug: "sega-cd", name: "Sega CD", level: "hard" },
  { slug: "amstrad-gx4000", name: "Amstrad GX4000", level: "hard" },

  // IMPOSSIBLE (17) — obscure even to most gaming enthusiasts
  { slug: "fairchild-channel-f", name: "Fairchild Channel F", level: "impossible" },
  { slug: "rca-studio-ii", name: "RCA Studio II", level: "impossible" },
  { slug: "atari-xegs", name: "Atari XEGS", level: "impossible" },
  { slug: "emerson-arcadia-2001", name: "Emerson Arcadia 2001", level: "impossible" },
  { slug: "entex-adventure-vision", name: "Entex Adventure Vision", level: "impossible" },
  { slug: "coleco-telstar", name: "Coleco Telstar", level: "impossible" },
  { slug: "apf-imagination-machine", name: "APF Imagination Machine", level: "impossible" },
  { slug: "interton-vc-4000", name: "Interton VC 4000", level: "impossible" },
  { slug: "vtech-creativision", name: "VTech CreatiVision", level: "impossible" },
  { slug: "casio-pv-1000", name: "Casio PV-1000", level: "impossible" },
  { slug: "turboexpress", name: "TurboExpress", level: "impossible" },
  { slug: "evercade", name: "Evercade", level: "impossible" },
  { slug: "watara-supervision", name: "Watara Supervision", level: "impossible" },
  { slug: "playstation-tv", name: "PlayStation TV", level: "impossible" },
  { slug: "amiga-cd32", name: "Amiga CD32", level: "impossible" },
  { slug: "pioneer-laseractive", name: "Pioneer LaserActive", level: "impossible" },
  { slug: "gp2x", name: "GP2X", level: "impossible" },
];
