export const GAMING_CONSOLE_LOGOS_E30_FACTS = {
  "playstation": "Sony's original PlayStation sold over 102 million units.",
  "xbox": "Microsoft launched the original Xbox in November 2001.",
  "nintendo-switch": "The Switch is Nintendo's first hybrid console/handheld.",
  "wii": "The Wii's motion controls sparked a global fitness-gaming trend.",
  "game-boy": "Game Boy and Game Boy Color sold over 118 million units combined.",
  "nintendo-64": "The N64 was the last major console to use cartridges.",
  "sega-genesis": "Known as the Mega Drive everywhere outside North America.",
  "playstation-2": "The PS2 is the best-selling console ever, 155M+ units.",
  "xbox-360": "The Xbox 360 popularized unified gaming Achievements.",
  "wii-u": "The Wii U was Nintendo's first eighth-generation console.",
  "nintendo-ds": "The DS brought a touchscreen to mainstream handhelds.",
  "playstation-4": "The PS4 became Sony's best-selling eighth-gen console.",
  "xbox-one": "The Xbox One originally launched bundled with Kinect.",
  "gamecube": "The GameCube was Nintendo's first disc-based console.",
  "sega-dreamcast": "The Dreamcast was the first console with a built-in modem.",
  "atari-2600": "The 2600 popularized swappable cartridges in the late 1970s.",
  "playstation-5": "The PS5 launched in November 2020, alongside Series X.",
  "xbox-series-x": "The Series X is Microsoft's most powerful console yet.",
  "super-nintendo": "The SNES introduced Mode 7 scaling to home consoles.",
  "nes": "The NES revived the US console market after the 1983 crash.",
  "sega-saturn": "The Saturn ran on two processors, unusual for its era.",
  "sega-master-system": "Sega's Master System outsold the NES across parts of Europe.",
  "nintendo-3ds": "The 3DS showed 3D visuals with no special glasses needed.",
  "playstation-portable": "The PSP was Sony's first handheld, launched in 2004.",
  "playstation-vita": "The Vita had a rear touchpad, unusual for a handheld.",
  "sega-game-gear": "The Game Gear ran on six AA batteries at once.",
  "neo-geo": "Neo Geo cartridges could cost over $200 at launch.",
  "turbografx-16": "Known as the PC Engine in Japan, released back in 1987.",
  "commodore-64": "The C64 is the best-selling single computer model ever.",
  "colecovision": "ColecoVision ran near-arcade-quality Donkey Kong at home.",
  "intellivision": "Intellivision was Mattel's answer to the Atari 2600.",
  "virtual-boy": "The Virtual Boy displayed graphics only in red and black.",
  "steam-deck": "Valve's Steam Deck runs a Linux-based operating system.",
  "nintendo-switch-lite": "The Switch Lite has fixed, non-detachable controls.",
  "playstation-3": "The PS3 was the first console with a built-in Blu-ray player.",
  "atari-5200": "The 5200 reused parts from Atari's 8-bit home computers.",
  "atari-7800": "The 7800 launched in 1986, years after it was developed.",
  "atari-jaguar": "Atari marketed the Jaguar as the first 64-bit console.",
  "3do-interactive-multiplayer": "The 3DO was licensed to several rival manufacturers.",
  "sega-32x": "The 32X was an add-on for the Genesis, not standalone.",
  "philips-cd-i": "The CD-i played both interactive movies and games.",
  "nokia-n-gage": "The N-Gage doubled as a mobile phone, unlike rivals.",
  "wonderswan": "Game Boy creator Gunpei Yokoi designed the WonderSwan.",
  "neo-geo-pocket": "The Neo Geo Pocket Color rivaled Bandai's WonderSwan in Japan.",
  "magnavox-odyssey": "The 1972 Odyssey was the first home video game console.",
  "vectrex": "The Vectrex is unique for its built-in vector-graphics screen.",
  "atari-lynx": "The Lynx was the first handheld with a color LCD screen.",
  "sega-nomad": "The Nomad let players take Genesis cartridges on the go.",
  "pokemon-mini": "The Pokémon Mini is one of the smallest consoles ever made.",
  "gizmondo": "The Gizmondo shipped with a built-in GPS receiver.",
  "ouya": "Ouya launched in 2013 after a record-breaking Kickstarter.",
  "nvidia-shield": "The Shield Portable ran Android and streamed PC games.",
  "sega-cd": "The Sega CD added full-motion video to the Genesis.",
  "amstrad-gx4000": "The GX4000 shared its cartridge slot with the CPC Plus computers.",
  "fairchild-channel-f": "The Channel F used swappable cartridges before the 2600.",
  "rca-studio-ii": "The Studio II displayed graphics only in black and white.",
  "atari-xegs": "The XEGS merged Atari's 8-bit computer line with a console.",
  "emerson-arcadia-2001": "Arcadia 2001 games were also sold under other brand names.",
  "entex-adventure-vision": "It used a spinning-mirror display instead of an LCD screen.",
  "coleco-telstar": "Coleco secured its full 1976 chip order despite a shortage.",
  "apf-imagination-machine": "It paired a game console with an add-on keyboard.",
  "interton-vc-4000": "The VC 4000 shared hardware roots with the Radofin 1292.",
  "vtech-creativision": "CreatiVision doubled as a console and a home computer.",
  "casio-pv-1000": "The PV-1000 was pulled from shelves within months of launch.",
  "turboexpress": "The TurboExpress played the same cards as the TurboGrafx-16.",
  "evercade": "Evercade revives retro games via physical cartridge sets.",
  "watara-supervision": "The Supervision was a budget rival to the original Game Boy.",
  "playstation-tv": "The PS Vita TV let Vita games be played on a television.",
  "amiga-cd32": "The CD32 was among the first 32-bit consoles with a CD drive.",
  "pioneer-laseractive": "The LaserActive ran games using LaserDisc technology.",
  "gp2x": "The GP2X ran open-source Linux software for homebrew games.",
};
