export const GEMSTONES_E50_FACTS = {
  // EASY
  "diamond": "Pure carbon; the hardest natural material, a 10 on the Mohs scale.",
  "ruby": "Ruby is corundum colored red by traces of chromium.",
  "emerald": "A green beryl; nearly all are oiled to hide surface fractures.",
  "sapphire": "The same mineral as ruby, corundum, just not colored red.",
  "amethyst": "Purple quartz colored by trace iron under natural irradiation.",
  "opal": "Its flashing colors come from tiny silica spheres, not layers.",
  "pearl": "Forms inside mollusks as coat after coat of nacre.",
  "gold": "So malleable that one ounce can be drawn into 50 miles of wire.",
  "quartz": "Earth's most common mineral; piezoelectric quartz powers watches.",
  "turquoise": "A copper-aluminum phosphate mined since ancient Egypt.",
  "jade": "The name covers two different minerals: jadeite and nephrite.",
  "garnet": "January's birthstone; it occurs in nearly every color but blue.",
  "citrine": "Yellow quartz; most sold today is heat-treated amethyst.",
  "rose-quartz": "Pink quartz, its color linked to trace titanium or manganese.",
  "pyrite": "Nicknamed fool's gold for its brassy, perfectly cubic crystals.",
  "malachite": "Banded green copper ore, too soft for everyday ring wear.",
  "onyx": "Most black 'onyx' jewelry today is dyed chalcedony.",

  // MEDIUM
  "aquamarine": "A blue-green beryl named for the color of seawater.",
  "peridot": "Forms deep in Earth's mantle; some has arrived via meteorites.",
  "topaz": "Comes in many natural colors; most blue topaz is treated.",
  "lapis-lazuli": "Ground into ultramarine, the pigment in old master paintings.",
  "moonstone": "Its glow, called adularescence, comes from light in layered feldspar.",
  "tourmaline": "One crystal can grow several colors banded together.",
  "obsidian": "Volcanic glass once shaped into sharp ceremonial blades.",
  "agate": "Banded chalcedony that fills gas bubbles in cooling lava.",
  "tigers-eye": "Quartz with parallel fibers that create a silky, shifting sheen.",
  "amber": "Fossilized tree resin that sometimes traps ancient insects.",
  "fluorite": "Glows under UV light; it gave 'fluorescence' its name.",
  "selenite": "A soft gypsum crystal you can scratch with a fingernail.",
  "calcite": "Fizzes with acid; it's the main mineral in limestone.",
  "jasper": "An opaque quartz prized for swirling, painterly patterns.",
  "aventurine": "Green quartz that sparkles from tiny included mica flakes.",
  "rhodochrosite": "Pink-and-white banded manganese carbonate, mined in Argentina.",
  "alexandrite": "Looks green in daylight, red under incandescent light.",

  // HARD
  "tanzanite": "Blue-violet zoisite found in just one small area of Tanzania.",
  "kunzite": "A pink-lilac gem that can fade if left in strong sunlight.",
  "zircon": "Not cubic zirconia; a natural silicate used to date rocks.",
  "spinel": "Long mistaken for ruby; some famous crown 'rubies' are spinel.",
  "iolite": "Nicknamed the Viking's Compass for its polarized light effect.",
  "labradorite": "A feldspar that flashes blue-green light called labradorescence.",
  "sunstone": "Feldspar with copper flecks that glitter like tiny sparks.",
  "chrysoprase": "Apple-green chalcedony colored by traces of nickel.",
  "azurite": "A deep blue copper ore that slowly weathers into green malachite.",
  "rhodonite": "A pink manganese silicate streaked through with black veins.",
  "sodalite": "Deep blue feldspathoid often mistaken for lapis lazuli.",
  "larimar": "A blue pectolite found in only one place: the Dominican Republic.",
  "kyanite": "A blue silicate whose hardness changes with crystal direction.",
  "chalcopyrite": "An iridescent copper ore nicknamed 'peacock ore' when tarnished.",
  "galena": "A heavy lead sulfide that grows glinting, perfectly cubic crystals.",
  "cinnabar": "A toxic mercury ore once ground into red vermilion pigment.",
  "halite": "Ordinary rock salt, naturally growing as cubic crystals.",

  // IMPOSSIBLE
  "painite": "Once Guinness-listed as the world's rarest gem mineral.",
  "grandidierite": "A blue-green mineral so rare few clean gems exist.",
  "jeremejevite": "A sky-blue borate known from only a handful of localities.",
  "taaffeite": "Identified in 1945 after being mistaken for spinel.",
  "benitoite": "California's official state gem, found almost nowhere else.",
  "poudretteite": "Named for a Quebec quarry; gem-quality crystals are tiny.",
  "musgravite": "A cousin of taaffeite, long ranked among Earth's rarest gems.",
  "serendibite": "Named for Serendib, old Sri Lanka; facetable stones are tiny.",
  "red-beryl": "Rarer than diamond; found almost only in Utah's Wah Wah Mountains.",
  "ammolite": "An organic gem made from fossilized ammonite shell.",
  "charoite": "A swirling purple mineral known from one Siberian river only.",
  "sugilite": "A purple manganese mineral first described in Japan in 1944.",
  "papagoite": "A rare blue copper silicate usually seen as tiny crystal coats.",
  "hackmanite": "A sodalite variety that changes color in sunlight, then fades.",
  "tugtupite": "A Greenlandic mineral that glows pink-red under UV light.",
  "stichtite": "A fibrous pink-purple mineral often intergrown with serpentine.",
  "ekanite": "A rare radioactive mineral whose crystal structure is disordered.",
};
