export const HISTORICAL_FIGURES_E93_FACTS = {
  "albert-einstein": "Einstein worked as a patent clerk in Switzerland while developing his theory of relativity, published in 1905.",
  "leonardo-da-vinci": "Leonardo filled notebooks with anatomical studies and inventions written in mirror script, though few designs were built in his lifetime.",
  "cleopatra-vii": "Cleopatra was fluent in several languages and was the last active ruler of Egypt's Ptolemaic dynasty before Roman annexation.",
  "abraham-lincoln": "Lincoln signed the Emancipation Proclamation in 1863 and delivered the Gettysburg Address later that same year.",
  "napoleon-bonaparte": "Napoleon crowned himself Emperor of the French in 1804 and was later exiled to Elba, then finally to Saint Helena.",
  "william-shakespeare": "Shakespeare wrote about three dozen plays and 154 sonnets, and coined or popularized hundreds of English words still used today.",
  "julius-caesar": "Caesar's crossing of the Rubicon River with his army in 49 BCE triggered a civil war that ended the Roman Republic.",
  "christopher-columbus": "Columbus's 1492 voyage, funded by the Spanish crown, never reached mainland North America — he landed in the Bahamas.",
  "isaac-newton": "Newton developed key ideas about gravity and motion while Cambridge was closed due to plague in 1665-1666.",
  "genghis-khan": "Genghis Khan united the Mongol tribes, founding an empire that his successors expanded into the largest contiguous land empire in history.",
  "alexander-the-great": "Alexander built an empire stretching from Greece to northwest India by the time of his death at age 32.",
  "mahatma-gandhi": "Gandhi led the 1930 Salt March, a roughly 240-mile walk protesting the British salt tax, as part of his nonviolent resistance campaign.",
  "marie-curie": "Marie Curie was the first person to win Nobel Prizes in two different sciences — physics in 1903 and chemistry in 1911.",
  "charles-darwin": "Darwin's five-year voyage aboard HMS Beagle provided key observations that shaped his theory of evolution by natural selection.",
  "vincent-van-gogh": "Van Gogh sold very few paintings in his lifetime, yet he produced over 2,000 artworks in roughly a decade of work.",
  "wolfgang-amadeus-mozart": "Mozart began composing music at around age five and had performed for European royalty before he turned ten.",
  "queen-victoria": "Victoria's 63-year reign was the longest of any British monarch until Elizabeth II surpassed it in 2015.",
  "george-washington": "Washington voluntarily stepped down after two presidential terms, setting a precedent later written into US law.",
  "elizabeth-i": "Elizabeth I never married, and her 45-year reign saw the English defeat of the Spanish Armada in 1588.",
  saladin: "Saladin founded the Ayyubid dynasty and recaptured Jerusalem from Crusader forces in 1187.",
  "joan-of-arc": "Joan of Arc led French troops to victory at the Siege of Orleans in 1429 as a teenager and was executed in 1431.",
  michelangelo: "Michelangelo spent about four years painting the Sistine Chapel ceiling, working on scaffolding of his own design.",
  "marco-polo": "Marco Polo's account of his travels along the Silk Road to Kublai Khan's court helped introduce Asia to medieval Europeans.",
  "nikola-tesla": "Tesla's alternating-current (AC) system, developed in the 1880s-90s, became the standard for electrical power transmission worldwide.",
  "thomas-edison": "Edison held over 1,000 US patents, including for the phonograph and a commercially practical incandescent light bulb.",
  "benjamin-franklin": "Franklin's 1752 kite experiment studied electricity, and he later helped draft and edit the US Declaration of Independence.",
  "catherine-the-great": "Catherine the Great expanded Russia's territory significantly during her 34-year reign and patronized Enlightenment arts and ideas.",
  "frederick-douglass": "Frederick Douglass escaped slavery in 1838 and became a leading writer and orator in the American abolitionist movement.",
  "florence-nightingale": "Nightingale's statistical analysis of sanitation during the Crimean War helped reform hospital practices and modern nursing.",
  "louis-pasteur": "Pasteur developed the pasteurization process and created vaccines for rabies and anthrax.",
  "ludwig-van-beethoven": "Beethoven composed some of his most celebrated works, including his Ninth Symphony, after he had become almost completely deaf.",
  "simon-bolivar": "Simon Bolivar led independence movements that freed several South American nations from Spanish colonial rule in the early 1800s.",
  "nelson-mandela": "Mandela spent 27 years in prison before becoming South Africa's first Black president in 1994.",
  "sitting-bull": "Sitting Bull was a Hunkpapa Lakota leader who helped unite Plains tribes in resistance, including at the 1876 Battle of the Little Bighorn.",
  "amelia-earhart": "Earhart became the first woman to fly solo across the Atlantic in 1932 and vanished during a round-the-world flight in 1937.",
  "galileo-galilei": "Galileo's telescopic observations supported the Copernican model of the solar system, leading to his trial by the Roman Inquisition.",
  "attila-the-hun": "Attila ruled the Hunnic Empire and led invasions into the Eastern and Western Roman Empires before his death in 453 CE.",
  "suleiman-the-magnificent": "Suleiman the Magnificent ruled the Ottoman Empire for 46 years, its longest reign, and oversaw major legal and cultural reforms.",
  akbar: "The Mughal emperor Akbar promoted religious tolerance and formed alliances with Rajput royal families to strengthen his empire.",
  "sun-yat-sen": "Sun Yat-sen became the first provisional president of the Republic of China after the 1911 revolution ended imperial rule.",
  ashoka: "After the bloody Kalinga War, Emperor Ashoka embraced Buddhism and promoted nonviolence through edicts carved across his empire.",
  "hannibal-barca": "Hannibal famously led a Carthaginian army, including war elephants, across the Alps to invade Italy during the Second Punic War.",
  boudica: "Boudica led an uprising of British tribes against Roman occupation around 60-61 CE, burning several major Roman settlements.",
  "toussaint-louverture": "Toussaint Louverture rose from slavery to lead the Haitian Revolution, helping end slavery in the colony by 1795.",
  "mansa-musa": "Mansa Musa's 1324 pilgrimage to Mecca reportedly involved so much gold that his spending affected Cairo's economy for years.",
  "cyrus-the-great": "Cyrus the Great founded the Achaemenid Persian Empire, and the Cyrus Cylinder credits him with freeing captive peoples in Babylon.",
  "emiliano-zapata": "Emiliano Zapata led peasant forces during the Mexican Revolution under the slogan 'Land and Liberty' before his 1919 assassination.",
  "zheng-he": "Admiral Zheng He commanded massive Ming dynasty fleets on seven voyages across the Indian Ocean, reaching as far as East Africa.",
  "vlad-the-impaler": "Vlad III of Wallachia, known as Vlad the Impaler, inspired Bram Stoker's Dracula and was infamous for impaling his enemies.",
  "empress-dowager-cixi": "Empress Dowager Cixi effectively controlled China's Qing government for nearly five decades from behind the throne.",
  "queen-nzinga": "Queen Nzinga ruled the Central African kingdoms of Ndongo and Matamba in the 1600s and resisted Portuguese colonization for decades.",
  avicenna: "The Persian scholar Avicenna (Ibn Sina) wrote The Canon of Medicine, a textbook used in European universities for centuries.",
  behanzin: "King Behanzin of Dahomey led armed resistance against French colonization in the 1890s before being defeated and exiled to Martinique.",
  zenobia: "Queen Zenobia of Palmyra briefly conquered Egypt and much of the Roman Near East before her defeat by Emperor Aurelian in 272 CE.",
  "wu-zetian": "Wu Zetian is the only woman known to have ruled China in her own right as emperor, founding the short-lived Zhou dynasty.",
  aethelflaed: "Aethelflaed, daughter of Alfred the Great, ruled Mercia alone for seven years and built fortified towns against Viking raids.",
  cetshwayo: "Zulu King Cetshwayo's forces won a famous victory over British troops at the Battle of Isandlwana in 1879.",
  "empress-suiko": "Empress Suiko became Japan's first reigning empress in 593 CE and ruled the country for 35 years.",
  taharqa: "Taharqa was a Kushite pharaoh of Egypt's 25th dynasty who built one of the largest pyramids in the Nubian region.",
  "ibn-khaldun": "The 14th-century scholar Ibn Khaldun's Muqaddimah introduced early ideas about social cohesion later linked to modern sociology.",
  "grace-omalley": "Irish seafarer Grace O'Malley commanded her own fleet of ships and met Queen Elizabeth I in person in 1593.",
  "bartolome-de-las-casas": "Bartolome de las Casas, a former colonist turned friar, wrote accounts condemning the treatment of Indigenous peoples in the Spanish Americas.",
  "olaudah-equiano": "Olaudah Equiano's 1789 autobiography about his enslavement became a bestseller that helped fuel Britain's abolitionist movement.",
  "ida-b-wells": "Journalist Ida B. Wells investigated and published statistical records documenting lynching in the American South in the 1890s.",
  "mary-seacole": "Mary Seacole, a Jamaican-born nurse, funded her own travel to the Crimean War and opened a support post near the front lines.",
  "phillis-wheatley": "Phillis Wheatley's 1773 poetry collection made her the first published African-American, and one of the first American women, to publish a book.",
  "rani-of-jhansi": "The Rani of Jhansi led her troops against British forces during the 1857 Indian Rebellion before dying in battle in 1858.",
  "menelik-ii": "Emperor Menelik II led Ethiopian forces to victory over Italy at the Battle of Adwa in 1896, preserving Ethiopian independence.",
  "al-khwarizmi": "The mathematician Al-Khwarizmi's 9th-century works gave rise to the terms 'algebra' and 'algorithm'.",
  "ada-lovelace": "Ada Lovelace's 1840s notes on Charles Babbage's Analytical Engine are considered an early description of a computer algorithm.",
};
