export const HORSE_BREEDS_E97 = [
  // ===== EASY (18) =====
  { slug: "arabian-horse", name: "Arabian Horse", level: "easy", wiki: "Arabian horse" },
  { slug: "thoroughbred", name: "Thoroughbred", level: "easy", wiki: "Thoroughbred" },
  { slug: "clydesdale", name: "Clydesdale", level: "easy", wiki: "Clydesdale horse" },
  { slug: "shetland-pony", name: "Shetland Pony", level: "easy", wiki: "Shetland pony" },
  { slug: "mustang", name: "Mustang", level: "easy", wiki: "Mustang" },
  { slug: "appaloosa", name: "Appaloosa", level: "easy", wiki: "Appaloosa" },
  { slug: "friesian-horse", name: "Friesian Horse", level: "easy", wiki: "Friesian horse" },
  { slug: "percheron", name: "Percheron", level: "easy", wiki: "Percheron" },
  { slug: "andalusian-horse", name: "Andalusian Horse", level: "easy", wiki: "Andalusian horse" },
  { slug: "shire-horse", name: "Shire Horse", level: "easy", wiki: "Shire horse" },
  { slug: "quarter-horse", name: "American Quarter Horse", level: "easy", wiki: "American Quarter Horse" },
  { slug: "icelandic-horse", name: "Icelandic Horse", level: "easy", wiki: "Icelandic horse" },
  { slug: "welsh-pony", name: "Welsh Pony", level: "easy", wiki: "Welsh Pony and Cob" },
  { slug: "belgian-draft", name: "Belgian Draft Horse", level: "easy", wiki: "American Belgian Draft" },
  { slug: "paint-horse", name: "American Paint Horse", level: "easy", wiki: "American Paint Horse" },
  { slug: "haflinger", name: "Haflinger", level: "easy", wiki: "Haflinger" },
  { slug: "lipizzaner", name: "Lipizzaner", level: "easy", wiki: "Lipizzan" },
  { slug: "miniature-horse", name: "Miniature Horse", level: "easy", wiki: "American Miniature Horse" },

  // ===== MEDIUM (18) =====
  { slug: "hanoverian", name: "Hanoverian", level: "medium", wiki: "Hanoverian horse" },
  { slug: "akhal-teke", name: "Akhal-Teke", level: "medium", wiki: "Akhal-Teke" },
  { slug: "morgan-horse", name: "Morgan Horse", level: "medium", wiki: "Morgan horse" },
  { slug: "tennessee-walking-horse", name: "Tennessee Walking Horse", level: "medium", wiki: "Tennessee Walking Horse" },
  { slug: "gypsy-vanner", name: "Gypsy Vanner", level: "medium", wiki: "Gypsy horse" },
  { slug: "fjord-horse", name: "Fjord Horse", level: "medium", wiki: "Fjord horse" },
  { slug: "standardbred", name: "Standardbred", level: "medium", wiki: "Standardbred" },
  { slug: "falabella", name: "Falabella", level: "medium", wiki: "Falabella" },
  { slug: "suffolk-punch", name: "Suffolk Punch", level: "medium", wiki: "Suffolk Punch" },
  { slug: "cleveland-bay", name: "Cleveland Bay", level: "medium", wiki: "Cleveland Bay" },
  { slug: "missouri-fox-trotter", name: "Missouri Fox Trotter", level: "medium", wiki: "Missouri Fox Trotter" },
  { slug: "criollo-horse", name: "Criollo Horse", level: "medium", wiki: "Criollo horse" },
  { slug: "paso-fino", name: "Paso Fino", level: "medium", wiki: "Paso Fino" },
  { slug: "american-saddlebred", name: "American Saddlebred", level: "medium", wiki: "American Saddlebred" },
  { slug: "connemara-pony", name: "Connemara Pony", level: "medium", wiki: "Connemara pony" },
  { slug: "dartmoor-pony", name: "Dartmoor Pony", level: "medium", wiki: "Dartmoor pony" },
  { slug: "trakehner", name: "Trakehner", level: "medium", wiki: "Trakehner" },
  { slug: "holsteiner", name: "Holsteiner", level: "medium", wiki: "Holsteiner" },

  // ===== HARD (16) =====
  { slug: "marwari-horse", name: "Marwari Horse", level: "hard", wiki: "Marwari horse" },
  { slug: "camargue-horse", name: "Camargue Horse", level: "hard", wiki: "Camargue horse" },
  { slug: "gotland-pony", name: "Gotland Pony", level: "hard", wiki: "Gotland Russ" },
  { slug: "curly-horse", name: "Curly Horse", level: "hard", wiki: "American Bashkir Curly" },
  { slug: "knabstrupper", name: "Knabstrupper", level: "hard", wiki: "Knabstrupper" },
  { slug: "noriker-horse", name: "Noriker Horse", level: "hard", wiki: "Noriker" },
  { slug: "fell-pony", name: "Fell Pony", level: "hard", wiki: "Fell pony" },
  { slug: "highland-pony", name: "Highland Pony", level: "hard", wiki: "Highland pony" },
  { slug: "caspian-horse", name: "Caspian Horse", level: "hard", wiki: "Caspian horse" },
  { slug: "rocky-mountain-horse", name: "Rocky Mountain Horse", level: "hard", wiki: "Rocky Mountain Horse" },
  { slug: "australian-stock-horse", name: "Australian Stock Horse", level: "hard", wiki: "Australian Stock Horse" },
  { slug: "canadian-horse", name: "Canadian Horse", level: "hard", wiki: "Canadian horse" },
  { slug: "nokota-horse", name: "Nokota Horse", level: "hard", wiki: "Nokota horse" },
  { slug: "sorraia", name: "Sorraia", level: "hard", wiki: "Sorraia" },
  { slug: "konik", name: "Konik", level: "hard", wiki: "Konik" },
  { slug: "ardennais", name: "Ardennes Horse", level: "hard", wiki: "Ardennais" },

  // ===== IMPOSSIBLE (18) =====
  { slug: "boerperd", name: "Boerperd", level: "impossible", wiki: "Boerperd" },
  { slug: "brumby", name: "Brumby", level: "impossible", wiki: "Brumby" },
  { slug: "yonaguni-horse", name: "Yonaguni Horse", level: "impossible", wiki: "Yonaguni horse" },
  { slug: "kiso-horse", name: "Kiso Horse", level: "impossible", wiki: "Kiso Horse" },
  { slug: "bosnian-mountain-horse", name: "Bosnian Mountain Horse", level: "impossible", wiki: "Bosnian Mountain Horse" },
  { slug: "mongolian-horse", name: "Mongolian Horse", level: "impossible", wiki: "Mongolian horse" },
  { slug: "yakutian-horse", name: "Yakutian Horse", level: "impossible", wiki: "Yakutian horse" },
  { slug: "kabarda-horse", name: "Kabarda Horse", level: "impossible", wiki: "Kabarda horse" },
  { slug: "karabakh-horse", name: "Karabakh Horse", level: "impossible", wiki: "Karabakh horse" },
  { slug: "kathiawari-horse", name: "Kathiawari Horse", level: "impossible", wiki: "Kathiawari horse" },
  { slug: "galiceno", name: "Galiceno", level: "impossible", wiki: "Galiceno" },
  { slug: "florida-cracker-horse", name: "Florida Cracker Horse", level: "impossible", wiki: "Florida Cracker Horse" },
  { slug: "newfoundland-pony", name: "Newfoundland Pony", level: "impossible", wiki: "Newfoundland pony" },
  { slug: "sable-island-horse", name: "Sable Island Horse", level: "impossible", wiki: "Sable Island horse" },
  { slug: "pantaneiro-horse", name: "Pantaneiro Horse", level: "impossible", wiki: "Pantaneiro (horse breed)" },
  { slug: "timor-pony", name: "Timor Pony", level: "impossible", wiki: "Timor Pony" },
  { slug: "sandalwood-pony", name: "Sandalwood Pony", level: "impossible", wiki: "Sandalwood Pony" },
  { slug: "pottok", name: "Pottok", level: "impossible", wiki: "Pottok" },
];
