export const HORSE_BREEDS_E97_FACTS = {
  // EASY
  "arabian-horse": "Arabian horses typically have one fewer lumbar vertebra and up to two fewer tail bones than most other breeds.",
  "thoroughbred": "Secretariat's 1:59 2/5 Kentucky Derby time from 1973 remains unbeaten by any Thoroughbred five decades later.",
  "clydesdale": "Budweiser's beer commercials made the feather-legged Clydesdale one of the most recognizable horses on Earth.",
  "shetland-pony": "Despite standing under 42 inches tall, a Shetland pony can pull roughly twice its own body weight.",
  "mustang": "Mustangs are feral descendants of Spanish horses, not a formal breed, yet a 1971 US law protects them as living history.",
  "appaloosa": "The gene behind the Appaloosa's spotted coat is also linked to a form of inherited night blindness in the breed.",
  "friesian-horse": "Dutch nobility once used solid-black Friesians to pull funeral carriages because of their somber, elegant look.",
  "percheron": "Percherons are thought to carry Arabian bloodlines from stallions crossed into French mares centuries ago.",
  "andalusian-horse": "The Andalusian's official name, Pura Raza Espanola, means Pure Spanish Horse and reflects its closed studbook.",
  "shire-horse": "A Shire gelding named Sampson, later called Mammoth, stood 21.2½ hands in 1850 - the tallest horse ever recorded.",
  "quarter-horse": "With millions registered, the American Quarter Horse is the most numerous and most popular horse breed on Earth.",
  "icelandic-horse": "Icelandic law bans importing horses, so once an Icelandic horse leaves the island it can never legally return.",
  "welsh-pony": "The Welsh Pony and Cob registry actually covers four distinct size sections, from tiny ponies to sturdy cobs.",
  "belgian-draft": "American Belgians were bred taller and lighter than their Old-World cousins and are now the US's top draft breed.",
  "paint-horse": "American Paint Horses must have both stock-horse build and pinto-style markings to qualify for their registry.",
  "haflinger": "Every registered Haflinger traces through one of seven sire lines back to a single 1874 foundation stallion.",
  "lipizzaner": "Lipizzaner foals are born nearly black and don't reach their famous snow-white coat until about 6 to 10 years old.",
  "miniature-horse": "American Miniature Horses are bred to keep a full-sized horse's exact proportions while standing under 34 inches tall.",

  // MEDIUM
  "hanoverian": "The Hanoverian began as a coach and cavalry horse at a royal German stud founded in 1735, now a top Olympic sport horse.",
  "akhal-teke": "The Akhal-Teke's coat has a natural metallic shimmer, earning Turkmenistan's ancient breed the nickname Golden Horse.",
  "morgan-horse": "Every Morgan horse today descends from a single 18th-century stallion once known simply as Figure.",
  "tennessee-walking-horse": "The Tennessee Walking Horse's signature running-walk lets a rider glide along smoothly at up to 10-20 mph.",
  "gypsy-vanner": "Gypsy Vanners were bred by Romani Travellers to pull ornately decorated vardo wagon-homes across Britain and Ireland.",
  "fjord-horse": "A Fjord horse's mane is naturally two-toned, and owners often trim it short so both colors stand up in a neat crest.",
  "standardbred": "The Standardbred's name comes from an early rule requiring a 'standard' mile time before a horse could join the registry.",
  "falabella": "Falabellas from Argentina can stand under 30 inches tall, making them among the smallest horse breeds on the planet.",
  "suffolk-punch": "Every Suffolk Punch is chestnut in color, with breed rules for over two centuries never allowing any other shade.",
  "cleveland-bay": "Cleveland Bays make up the bulk of the horses that pull carriages for Britain's royal family at the Royal Mews.",
  "missouri-fox-trotter": "In its signature gait, a Missouri Fox Trotter walks with its front legs while trotting with its hind legs.",
  "criollo-horse": "A pair of Argentine Criollo horses once carried rider Aime Tschiffely nearly 10,000 miles to Washington, DC in 1928.",
  "paso-fino": "A Paso Fino's natural four-beat lateral gait is so smooth that riders can carry a full glass without spilling it.",
  "american-saddlebred": "Nicknamed 'the horse America made,' the Saddlebred was bred as a smooth-riding mount for plantation owners and officers.",
  "connemara-pony": "The Connemara is Ireland's only native pony breed, developed in the rugged coastal region of County Galway.",
  "dartmoor-pony": "Dartmoor ponies have roamed the moors of Devon, England semi-wild for at least a thousand years.",
  "trakehner": "In the brutal winter of 1944-45, refugees fled East Prussia with Trakehners, and only around 1,500 of 30,000 survived.",
  "holsteiner": "Breeding records for the Holsteiner in northern Germany's Schleswig-Holstein region stretch back to the 13th century.",

  // HARD
  "marwari-horse": "A Marwari horse's ears curve inward and can rotate a full 180 degrees, almost touching tip to tip.",
  "camargue-horse": "Camargue horses live semi-wild in France's Rhone delta marshes, where gardians ride them to herd black bulls.",
  "gotland-pony": "Sweden's Gotland Russ may descend from ancient wild tarpan-type horses, making it one of the country's oldest breeds.",
  "curly-horse": "Curly Horses often grow curled eyelashes and ear hair along with their signature curly coat and mane.",
  "knabstrupper": "Prized for its leopard-spotted coat, the endangered Danish Knabstrupper has long been a favorite circus performer.",
  "noriker-horse": "The sure-footed Noriker draft horse of the Austrian Alps takes its name from the ancient Roman province of Noricum.",
  "fell-pony": "Fell ponies once packed lead ore across Cumbria's fells, with trains of them covering up to 240 miles a week.",
  "highland-pony": "Highland ponies, called garrons, are still used on Scottish estates to carry shot deer carcasses down steep hillsides.",
  "caspian-horse": "Thought extinct for 1,300 years, the tiny Caspian horse was rediscovered in Iran's mountains by Louise Firouz in 1965.",
  "rocky-mountain-horse": "Despite its name, the Rocky Mountain Horse actually originated in Kentucky's Appalachian foothills, not the Rocky Mountains at all.",
  "australian-stock-horse": "Australian Stock Horses were bred to muster cattle in the outback and starred in The Man from Snowy River.",
  "canadian-horse": "Nicknamed 'the little iron horse,' Canada's national horse breed survived two brushes with near-extinction.",
  "nokota-horse": "Nokota horses of the North Dakota badlands are believed to descend partly from ponies once owned by Sitting Bull.",
  "sorraia": "DNA studies have found striking similarities between Portugal's rare Sorraia horse and some American mustangs.",
  "konik": "Semi-feral Konik horses now graze rewilding reserves across Europe, restoring wetlands that livestock won't touch.",
  "ardennais": "The hardy Ardennes horse hauled artillery through Napoleon's disastrous 1812 retreat when other breeds couldn't.",

  // IMPOSSIBLE
  "boerperd": "South Africa's Boerperd was bred to recreate the extinct Cape Horse, tracing to 17th-century Dutch settler bloodlines.",
  "brumby": "More than 400,000 brumbies, Australia's free-roaming feral horses, were counted living wild across the country in 2011.",
  "yonaguni-horse": "Only about 100 Yonaguni horses remain on their remote Japanese island, where tourists ride them into the sea.",
  "kiso-horse": "The Kiso is Honshu's only native horse breed, and Japan's imperial army once ordered its stallions gelded for being too small.",
  "bosnian-mountain-horse": "The Bosnian Mountain Horse makes up about 70 percent of Bosnia and Herzegovina's entire horse population, its only native breed.",
  "mongolian-horse": "Mongolia's horses outnumber its human population, and the hardy breed still lives outdoors through -40C winters.",
  "yakutian-horse": "Yakutian horses of Siberia grow an extremely thick winter coat that lets them survive outdoors down to -70C.",
  "kabarda-horse": "The Kabarda horse's blood has a heightened oxygen-carrying capacity, an adaptation that helps it work at altitude in the Caucasus Mountains.",
  "karabakh-horse": "Azerbaijan's national animal, the Karabakh horse, once ran 1,000 meters in just over a minute at a 2004 timed trial.",
  "kathiawari-horse": "The Kathiawari horse of India has unusual ears that curve inward and is still used in the sport of tent-pegging.",
  "galiceno": "Galiceno horses descend from stock brought to Mexico by conquistador Hernan Cortes in the 16th century.",
  "florida-cracker-horse": "Descended from 16th-century Spanish stock, the Florida Cracker Horse became Florida's official state horse in 2008.",
  "newfoundland-pony": "Mechanization nearly wiped out the Newfoundland pony before it became a protected heritage breed of the province in 1997.",
  "sable-island-horse": "Sable Island's feral horses have been legally protected from human interference since 1960 and roam the island freely.",
  "pantaneiro-horse": "Brazil's Pantaneiro horse developed through 300 years of natural selection in the flooded wetlands of the Pantanal.",
  "timor-pony": "Timor Ponies exported from Indonesia to Australia helped found the modern Australian Pony breed.",
  "sandalwood-pony": "Named for the trees exported from its home islands, Indonesia's Arabian-blooded Sandalwood Pony is prized for racing speed.",
  "pottok": "The Basque Pottok pony grows an extra-thick winter coat called the borra, which can reach about 10cm long on young ponies.",
};
