// Episode 15 "Guess the Island" — one verified <=70-char fact per item, keyed by slug.
export const ISLANDS_E15_FACTS = {
  "sicily": "Sicily is the largest island in the Mediterranean Sea.",
  "oahu-hawaii": "Oʻahu is home to Honolulu and the famous Waikiki Beach.",
  "greenland": "Greenland is the world's largest island that isn't a continent.",
  "iceland": "Iceland sits directly on the Mid-Atlantic volcanic ridge.",
  "madagascar": "Madagascar has been isolated from Africa for over 150 million years.",
  "sri-lanka": "Sri Lanka was known as Ceylon until it changed its name in 1972.",
  "easter-island": "Easter Island is famous for its giant carved Moai statues.",
  "mont-saint-michel": "Mont-Saint-Michel becomes a true island only at high tide.",
  "ibiza": "Ibiza is a Balearic island known worldwide for its nightlife.",
  "galapagos": "The Galápagos Islands inspired Darwin's theory of evolution.",
  "jamaica": "Jamaica is the birthplace of reggae music and Bob Marley.",
  "cuba": "Cuba is the largest island in the Caribbean Sea.",
  "singapore": "Singapore is one of the world's few sovereign island city-states.",
  "phuket": "Phuket is Thailand's largest island, in the Andaman Sea.",
  "bermuda": "Bermuda is actually made of about 181 small islands.",
  "robben-island": "Nelson Mandela was imprisoned on Robben Island for 18 years.",
  "crete": "Crete is home to the ruins of the ancient Minoan civilization.",
  "tasmania": "Tasmania is separated from mainland Australia by Bass Strait.",
  "sardinia": "Sardinia has some of the world's longest-living people.",
  "alcatraz": "Alcatraz once held a maximum-security federal prison.",
  "corsica": "Corsica is the birthplace of Napoleon Bonaparte.",
  "tenerife": "Tenerife is home to Spain's tallest peak, Mount Teide.",
  "mykonos": "Mykonos is famous for its windmills and whitewashed streets.",
  "malta": "Malta is one of the smallest and most densely populated countries.",
  "barbados": "Barbados became the world's newest republic in 2021.",
  "mauritius": "Mauritius was once home to the now-extinct dodo bird.",
  "saint-lucia": "Saint Lucia's twin Pitons rise straight from the Caribbean Sea.",
  "curacao": "Curaçao's capital Willemstad has colorful Dutch colonial buildings.",
  "java": "Java is the world's most populous island.",
  "palawan": "Palawan is home to an underground river inside a cave system.",
  "koh-samui": "Koh Samui is Thailand's second-largest island.",
  "langkawi": "Langkawi is an archipelago of 99 islands off Malaysia.",
  "okinawa": "Okinawa's residents have some of the world's longest lifespans.",
  "isle-of-skye": "The Isle of Skye is linked to mainland Scotland by a bridge.",
  "vancouver-island": "Vancouver Island is the largest Pacific island in North America.",
  "cozumel": "Cozumel sits beside the second-largest coral reef on Earth.",
  "capri": "Capri's Blue Grotto glows from sunlight reflecting underwater.",
  "key-west": "Key West sits closer to Cuba than to Miami, Florida.",
  "reunion": "Réunion is home to one of the world's most active volcanoes.",
  "menorca": "Menorca is a UNESCO Biosphere Reserve in the Balearic Islands.",
  "rhodes": "Rhodes once held the Colossus, one of the Seven Wonders.",
  "cebu": "Cebu hosted the first Catholic Mass in the Philippines in 1521.",
  "aruba": "Aruba sits outside the Caribbean hurricane belt.",
  "lombok": "Lombok is home to Mount Rinjani, one of Indonesia's tallest volcanoes.",
  "penang": "Penang's capital George Town is a UNESCO World Heritage Site.",
  "hokkaido": "Hokkaido is Japan's second-largest and northernmost main island.",
  "isle-of-man": "The Isle of Man hosts the famous TT motorcycle races.",
  "prince-edward-island": "Prince Edward Island inspired the novel Anne of Green Gables.",
  "havelock-island": "Havelock Island is part of India's Andaman archipelago.",
  "lofoten": "The Lofoten islands sit above the Arctic Circle in Norway.",
  "gotland": "Gotland is the largest island in the Baltic Sea.",
  "goree-island": "Gorée Island's House of Slaves is a UNESCO-listed memorial.",
  "whitsunday-islands": "The Whitsunday Islands sit beside the Great Barrier Reef.",
  "trinidad": "Trinidad is the birthplace of steelpan music and calypso.",
  "elba": "Napoleon was exiled to the island of Elba in 1814.",
  "marthas-vineyard": "Martha's Vineyard is a popular summer retreat off Massachusetts.",
  "new-caledonia": "New Caledonia has one of the world's largest lagoons.",
  "lanzarote": "Lanzarote's landscape was shaped by 1730s volcanic eruptions.",
  "svalbard": "Svalbard hosts a global seed vault deep inside a mountain.",
  "bornholm": "Bornholm is a Danish island known for its round churches.",
  "saaremaa": "Saaremaa is Estonia's largest island, dotted with windmills.",
  "aland-islands": "The Åland Islands are Swedish-speaking but belong to Finland.",
  "sakhalin": "Sakhalin is Russia's largest island, north of Japan.",
  "christmas-island": "Christmas Island is famous for its annual red crab migration.",
  "chiloe": "Chiloé Island is known for its stilt houses and wooden churches.",
  "bioko": "Bioko Island is home to Equatorial Guinea's capital, Malabo.",
  "principe": "Príncipe belongs to one of Africa's least-visited nations.",
  "nauru": "Nauru is the world's third-smallest country by land area.",
  "funafuti": "Funafuti is the capital atoll of the tiny nation of Tuvalu.",
  "efate": "Efate is home to Port Vila, the capital of Vanuatu.",
  "bikini-atoll": "Bikini Atoll's name inspired the swimsuit after 1946 nuclear tests.",
};
