// E73 "Guess the JDM/Tuner Car" — 70 real Japanese performance/tuner cars, fifth and final of 5 planned car-themed episodes.
// Disambiguated from E53 "Classic Cars" (which already used generic "Nissan Skyline GT-R (R34)", "Toyota Supra (A80)",
// "Toyota Corolla AE86 (Trueno)", "Honda NSX", "Mitsubishi Lancer Evolution", "Subaru Impreza WRX STI", "Datsun 240Z/510",
// "Mazda MX-5 (Miata)", "Honda Civic", "Toyota Corolla", "Nissan GT-R", "Nissan GT-R50", "Lexus LFA", "Toyota Land Cruiser")
// by using distinct generations/trims/models throughout.
export const JDM_CARS_E73 = [
  // EASY (18)
  { slug: "mazda-rx7-fd", name: "Mazda RX-7 (FD3S)", wiki: "Mazda RX-7", level: "easy" },
  { slug: "nissan-350z", name: "Nissan 350Z", wiki: "Nissan 350Z", level: "easy" },
  { slug: "nissan-silvia-s15", name: "Nissan Silvia S15", wiki: "Nissan Silvia (S15)", level: "easy" },
  { slug: "honda-s2000", name: "Honda S2000", wiki: "Honda S2000", level: "easy" },
  { slug: "toyota-celica-gt-four", name: "Toyota Celica GT-Four", wiki: "Toyota Celica GT-Four", level: "easy" },
  { slug: "toyota-mr2", name: "Toyota MR2", wiki: "Toyota MR2", level: "easy" },
  { slug: "toyota-gr-supra", name: "Toyota GR Supra", wiki: "Toyota Supra (A90)", level: "easy" },
  { slug: "nissan-z-rz34", name: "Nissan Z", wiki: "Nissan Z (RZ34)", level: "easy" },
  { slug: "toyota-gr86", name: "Toyota GR86", wiki: "Toyota GR86", level: "easy" },
  { slug: "mazda-rx8", name: "Mazda RX-8", wiki: "Mazda RX-8", level: "easy" },
  { slug: "honda-integra-type-r", name: "Honda Integra Type R", wiki: "Honda Integra Type R", level: "easy" },
  { slug: "nissan-300zx", name: "Nissan Fairlady Z (300ZX)", wiki: "Nissan 300ZX", level: "easy" },
  { slug: "honda-civic-type-r-fk8", name: "Honda Civic Type R (FK8)", wiki: "Honda Civic Type R", level: "easy" },
  { slug: "nissan-skyline-gtr-r32", name: "Nissan Skyline GT-R (R32)", wiki: "Nissan Skyline GT-R (R32)", level: "easy" },
  { slug: "nissan-180sx", name: "Nissan 180SX", wiki: "Nissan 180SX", level: "easy" },
  { slug: "toyota-chaser", name: "Toyota Chaser", wiki: "Toyota Chaser", level: "easy" },
  { slug: "subaru-brz", name: "Subaru BRZ", wiki: "Subaru BRZ", level: "easy" },
  { slug: "mitsubishi-3000gt", name: "Mitsubishi 3000GT", wiki: "Mitsubishi GTO", level: "easy" },

  // MEDIUM (18)
  { slug: "nissan-skyline-gtr-r33", name: "Nissan Skyline GT-R (R33)", wiki: "Nissan Skyline GT-R (R33)", level: "medium" },
  { slug: "nissan-silvia-s14", name: "Nissan Silvia S14", wiki: "Nissan Silvia (S14)", level: "medium" },
  { slug: "nissan-silvia-s13", name: "Nissan Silvia S13", wiki: "Nissan Silvia (S13)", level: "medium" },
  { slug: "toyota-supra-a70", name: "Toyota Supra (A70)", wiki: "Toyota Supra (A70)", level: "medium" },
  { slug: "mazda-rx7-fc", name: "Mazda RX-7 (FC3S)", wiki: "Mazda RX-7", level: "medium" },
  { slug: "toyota-mark-ii-jzx100", name: "Toyota Mark II (JZX100)", wiki: "Toyota Mark II", level: "medium" },
  { slug: "mitsubishi-eclipse-gsx", name: "Mitsubishi Eclipse GSX", wiki: "Mitsubishi Eclipse", level: "medium" },
  { slug: "honda-civic-type-r-ek9", name: "Honda Civic Type R (EK9)", wiki: "Honda Civic Type R", level: "medium" },
  { slug: "toyota-soarer", name: "Toyota Soarer", wiki: "Toyota Soarer", level: "medium" },
  { slug: "nissan-skyline-hakosuka", name: "Nissan Skyline 2000 GT-R (Hakosuka)", wiki: "Nissan Skyline GT-R", level: "medium" },
  { slug: "subaru-impreza-22b", name: "Subaru Impreza 22B STI", wiki: "Subaru Impreza WRX STI", level: "medium" },
  { slug: "mitsubishi-starion", name: "Mitsubishi Starion", wiki: "Mitsubishi Starion", level: "medium" },
  { slug: "toyota-aristo", name: "Toyota Aristo", wiki: "Toyota Aristo", level: "medium" },
  { slug: "honda-prelude", name: "Honda Prelude", wiki: "Honda Prelude", level: "medium" },
  { slug: "mazda-familia-gtx", name: "Mazda Familia GTX", wiki: "Mazda Familia", level: "medium" },
  { slug: "toyota-altezza", name: "Toyota Altezza", wiki: "Lexus IS", level: "medium" },
  { slug: "nissan-pulsar-gti-r", name: "Nissan Pulsar GTI-R", wiki: "Nissan Pulsar GTI-R", level: "medium" },
  { slug: "mitsubishi-evo-ix", name: "Mitsubishi Lancer Evolution IX", wiki: "Mitsubishi Lancer Evolution", level: "medium" },

  // HARD (16)
  { slug: "toyota-starlet-gt-turbo", name: "Toyota Starlet GT Turbo", wiki: "Toyota Starlet", level: "hard" },
  { slug: "mitsubishi-fto", name: "Mitsubishi FTO", wiki: "Mitsubishi FTO", level: "hard" },
  { slug: "honda-crx", name: "Honda CR-X", wiki: "Honda CR-X", level: "hard" },
  { slug: "nissan-cefiro", name: "Nissan Cefiro", wiki: "Nissan Cefiro", level: "hard" },
  { slug: "subaru-legacy-gt", name: "Subaru Legacy GT", wiki: "Subaru Legacy", level: "hard" },
  { slug: "nissan-skyline-kenmeri", name: "Nissan Skyline GT-R (Kenmeri)", wiki: "Nissan Skyline GT-R", level: "hard" },
  { slug: "mazda-cosmo", name: "Mazda Cosmo (110S)", wiki: "Mazda Cosmo", level: "hard" },
  { slug: "isuzu-piazza", name: "Isuzu Piazza", wiki: "Isuzu Piazza", level: "hard" },
  { slug: "nissan-laurel", name: "Nissan Laurel", wiki: "Nissan Laurel", level: "hard" },
  { slug: "honda-beat", name: "Honda Beat", wiki: "Honda Beat", level: "hard" },
  { slug: "suzuki-cappuccino", name: "Suzuki Cappuccino", wiki: "Suzuki Cappuccino", level: "hard" },
  { slug: "subaru-svx", name: "Subaru SVX", wiki: "Subaru SVX", level: "hard" },
  { slug: "mitsubishi-pajero-evolution", name: "Mitsubishi Pajero Evolution", wiki: "Mitsubishi Pajero Evolution", level: "hard" },
  { slug: "nissan-figaro", name: "Nissan Figaro", wiki: "Nissan Figaro", level: "hard" },
  { slug: "autozam-az1", name: "Autozam AZ-1", wiki: "Autozam AZ-1", level: "hard" },
  { slug: "isuzu-117-coupe", name: "Isuzu 117 Coupé", wiki: "Isuzu 117 Coupé", level: "hard" },

  // IMPOSSIBLE (18)
  { slug: "toyota-sera", name: "Toyota Sera", wiki: "Toyota Sera", level: "impossible" },
  { slug: "nissan-pao", name: "Nissan Pao", wiki: "Nissan Pao", level: "impossible" },
  { slug: "nissan-be1", name: "Nissan Be-1", wiki: "Nissan Be-1", level: "impossible" },
  { slug: "nissan-s-cargo", name: "Nissan S-Cargo", wiki: "Nissan S-Cargo", level: "impossible" },
  { slug: "honda-city-turbo-ii", name: "Honda City Turbo II", wiki: "Honda City", level: "impossible" },
  { slug: "nissan-exa", name: "Nissan Exa", wiki: "Nissan EXA", level: "impossible" },
  { slug: "mitsubishi-minica-dangan-zz", name: "Mitsubishi Minica Dangan ZZ", wiki: "Mitsubishi Minica", level: "impossible" },
  { slug: "suzuki-alto-works", name: "Suzuki Alto Works", wiki: "Suzuki Alto Works", level: "impossible" },
  { slug: "daihatsu-mira-trxx", name: "Daihatsu Mira TR-XX", wiki: "Daihatsu Mira", level: "impossible" },
  { slug: "subaru-vivio-rxr", name: "Subaru Vivio RX-R", wiki: "Subaru Vivio", level: "impossible" },
  { slug: "honda-today", name: "Honda Today", wiki: "Honda Today", level: "impossible" },
  { slug: "toyota-cynos", name: "Toyota Cynos", wiki: "Toyota Paseo", level: "impossible" },
  { slug: "daihatsu-copen", name: "Daihatsu Copen", wiki: "Daihatsu Copen", level: "impossible" },
  { slug: "toyota-publica", name: "Toyota Publica", wiki: "Toyota Publica", level: "impossible" },
  { slug: "daihatsu-leeza-spider", name: "Daihatsu Leeza Spider", wiki: "Daihatsu Leeza", level: "impossible" },
  { slug: "toyota-corona-mark-ii", name: "Toyota Corona Mark II", wiki: "Toyota Mark II", level: "impossible" },
  { slug: "isuzu-bellett-gt", name: "Isuzu Bellett GT", wiki: "Isuzu Bellett", level: "impossible" },
  { slug: "datsun-fairlady-sr311", name: "Datsun Fairlady 2000 (SR311)", wiki: "Datsun Sports", level: "impossible" },
];
export default JDM_CARS_E73;
