export const JDM_CARS_E73_FACTS = {
  "mazda-rx7-fd": "Powered by a twin-rotor Wankel engine, not a piston V6.",
  "nissan-350z": "Revived the Z name after a six-year gap in the US market.",
  "nissan-silvia-s15": "The final Silvia generation, never officially sold in the US.",
  "honda-s2000": "Its F20C engine revved to a screaming 9,000 RPM, rare for a road car.",
  "toyota-celica-gt-four": "An all-wheel-drive rally homologation special.",
  "toyota-mr2": "A mid-engine sports car, rare for a mainstream Toyota.",
  "toyota-gr-supra": "Co-developed with BMW, sharing its platform with the Z4.",
  "nissan-z-rz34": "Brings back a twin-turbo V6 after the naturally aspirated 370Z.",
  "toyota-gr86": "A rear-wheel-drive coupe co-developed with Subaru.",
  "mazda-rx8": "Used unique rear-hinged half-doors for easier back seat access.",
  "honda-integra-type-r": "Hand-ported cylinder heads made its VTEC engine legendary.",
  "nissan-300zx": "Its twin-turbo version was one of Japan's fastest cars in 1990.",
  "honda-civic-type-r-fk8": "Succeeded the FK2 as an early turbocharged Civic Type R.",
  "nissan-skyline-gtr-r32": "Nicknamed \"Godzilla\" for dominating Group A touring car racing.",
  "nissan-180sx": "Shared its chassis with the Silvia but kept fixed headlights.",
  "toyota-chaser": "A sport sedan sharing its platform with the Mark II and Cresta.",
  "subaru-brz": "Co-developed with Toyota, sold there as the 86/GR86.",
  "mitsubishi-3000gt": "Sold in Japan as the GTO, badged 3000GT for export.",
  "nissan-skyline-gtr-r33": "Nissan claimed a sub-8-minute Nürburgring lap for it in 1995.",
  "nissan-silvia-s14": "Grew wider and longer than the S13 it replaced.",
  "nissan-silvia-s13": "A favorite of early drift drivers for its balanced chassis.",
  "toyota-supra-a70": "The first Supra generation with a turbocharged inline-six.",
  "mazda-rx7-fc": "Brought the RX-7's turbo rotary engine to the US market.",
  "toyota-mark-ii-jzx100": "Its 1JZ-GTE six is a smaller sibling of the Supra's 2JZ-GTE.",
  "mitsubishi-eclipse-gsx": "Its GSX trim added Mitsubishi's all-wheel-drive system.",
  "honda-civic-type-r-ek9": "The first Civic Type R, sold only in Japan.",
  "toyota-soarer": "Sold in the US as the Lexus SC, its more luxurious sibling.",
  "nissan-skyline-hakosuka": "Nicknamed \"Hakosuka,\" meaning boxy Skyline in Japanese.",
  "subaru-impreza-22b": "A limited 400-unit run built to mark Subaru's rally titles.",
  "mitsubishi-starion": "One of Mitsubishi's first turbocharged, rear-wheel-drive sports cars.",
  "toyota-aristo": "Sold overseas as the Lexus GS with a different badge.",
  "honda-prelude": "Introduced four-wheel steering to a mainstream Honda coupe.",
  "mazda-familia-gtx": "A rally homologation version of Mazda's compact Familia.",
  "toyota-altezza": "Sold internationally as the first-generation Lexus IS.",
  "nissan-pulsar-gti-r": "An all-wheel-drive rally homologation hatchback.",
  "mitsubishi-evo-ix": "Used Mitsubishi's MIVEC variable valve timing for the first time.",
  "toyota-starlet-gt-turbo": "A pocket-sized hot hatch with a turbocharged 1.3L engine.",
  "mitsubishi-fto": "Its name stood for \"Fresh Touring Origination.\"",
  "honda-crx": "Praised for its light weight and sharp handling.",
  "nissan-cefiro": "Later generations were rebadged overseas as the Infiniti I30.",
  "subaru-legacy-gt": "Paired a turbocharged boxer engine with all-wheel drive.",
  "nissan-skyline-kenmeri": "Nicknamed \"Kenmeri\" after a famous ad campaign duo.",
  "mazda-cosmo": "Mazda's first car with a twin-rotor Wankel engine.",
  "isuzu-piazza": "Styled by famed Italian designer Giorgetto Giugiaro.",
  "nissan-laurel": "A mid-size sedan that shared its platform with the Skyline.",
  "honda-beat": "Honda's first mid-engine, rear-wheel-drive kei car.",
  "suzuki-cappuccino": "A tiny kei roadster with a removable targa-style roof.",
  "subaru-svx": "Featured a distinctive glass-within-glass window design.",
  "mitsubishi-pajero-evolution": "Built to homologate Mitsubishi's Dakar Rally racer.",
  "nissan-figaro": "Sold only through a lottery due to overwhelming demand.",
  "autozam-az1": "A kei sports car with dramatic upward-swinging gullwing doors.",
  "isuzu-117-coupe": "Early models were hand-assembled at a low production rate.",
  "toyota-sera": "Known for its glass-topped roof and gullwing doors.",
  "nissan-pao": "Part of Nissan's retro-styled \"Pike Factory\" series.",
  "nissan-be1": "The car that launched Nissan's retro Pike Factory lineup.",
  "nissan-s-cargo": "Its name is a pun on the French word for snail.",
  "honda-city-turbo-ii": "Came with a matching folding scooter that stored in its trunk.",
  "nissan-exa": "Offered swappable body panels to change its look.",
  "mitsubishi-minica-dangan-zz": "Its name means \"bullet\" in Japanese, hinting at its speed.",
  "suzuki-alto-works": "A performance kei car with a turbocharged three-cylinder engine.",
  "daihatsu-mira-trxx": "A turbocharged kei hatchback aimed at enthusiast drivers.",
  "subaru-vivio-rxr": "A supercharged kei car built for rally-style performance.",
  "honda-today": "One of Honda's smallest and most affordable kei cars.",
  "toyota-cynos": "Sold overseas under the name Toyota Paseo.",
  "daihatsu-copen": "A small kei roadster with a retractable hardtop.",
  "toyota-publica": "One of Toyota's first affordable economy cars.",
  "daihatsu-leeza-spider": "A kei car with a removable targa-style roof panel.",
  "toyota-corona-mark-ii": "Later split off to become its own Mark II model line.",
  "isuzu-bellett-gt": "One of Japan's earliest dedicated sports coupes.",
  "datsun-fairlady-sr311": "An early ancestor of the later Datsun 240Z sports car.",
};
