export const LAKES_E19_FACTS = {
  "lake-superior": "Lake Superior is the largest freshwater lake by surface area.",
  "lake-victoria": "Lake Victoria is Africa's largest lake by surface area.",
  "lake-baikal": "Lake Baikal holds about a fifth of the world's fresh water.",
  "lake-titicaca": "Lake Titicaca is the world's highest navigable lake.",
  "loch-ness": "Loch Ness holds more water than all of England's lakes combined.",
  "lake-como": "Lake Como is one of Europe's deepest lakes, over 400 meters.",
  "lake-tahoe": "Lake Tahoe is the largest alpine lake in North America.",
  "caspian-sea": "The Caspian Sea is the largest inland body of water on Earth.",
  "lake-geneva": "Lake Geneva is the largest lake in the Alps by volume.",
  "lake-bled": "Lake Bled has a tiny island with a church reached only by boat.",
  "lake-malawi": "Lake Malawi holds more fish species than any other lake.",
  "lake-toba": "Lake Toba fills the crater of the largest eruption in 2 million years.",
  "lake-balaton": "Lake Balaton is Central Europe's largest lake.",
  "lake-atitlan": "Lake Atitlan formed in a caldera ringed by three volcanoes.",
  "lake-maracaibo": "Lake Maracaibo sees more lightning than anywhere on Earth.",
  "lake-nasser": "Lake Nasser formed behind the Aswan High Dam in the 1960s.",
  "lake-chad": "Lake Chad has shrunk by over 90 percent since the 1960s.",
  "lake-turkana": "Lake Turkana is the world's largest permanent desert lake.",
  "lake-louise": "Lake Louise turns turquoise from glacial rock flour each summer.",
  "lake-constance": "Lake Constance borders three countries along the Rhine.",
  "lake-garda": "Lake Garda is Italy's largest lake.",
  "great-salt-lake": "The Great Salt Lake is the largest saltwater lake in the Americas.",
  "lake-tanganyika": "Lake Tanganyika is the world's second-deepest lake.",
  "lake-kariba": "Lake Kariba is the world's largest reservoir by volume.",
  "lake-nicaragua": "Lake Nicaragua is home to rare freshwater bull sharks.",
  "lake-van": "Lake Van is Turkey's largest lake, fed by no rivers out.",
  "chitgar-lake": "Chitgar Lake is an artificial lake built in western Tehran.",
  "lake-biwa": "Lake Biwa is Japan's largest freshwater lake.",
  "lake-kivu": "Lake Kivu traps huge pockets of methane gas deep below.",
  "lake-nakuru": "Lake Nakuru once hosted over a million flamingos at once.",
  "lake-ohrid": "Lake Ohrid is one of Europe's oldest lakes, over a million years.",
  "lake-skadar": "Lake Skadar is the Balkans' largest lake.",
  "lake-ladoga": "Lake Ladoga is the largest lake in Europe.",
  "lake-sevan": "Lake Sevan supplies most of Armenia's drinking and irrigation water.",
  "issyk-kul": "Issyk-Kul is one of the world's largest alpine lakes.",
  "lake-vanern": "Lake Vanern is Sweden's largest lake.",
  "lake-wanaka": "Lake Wanaka has a tiny island with its own tiny lake on top.",
  "lake-powell": "Lake Powell formed behind the Glen Canyon Dam in the 1960s.",
  "lake-bunyonyi": "Lake Bunyonyi is dotted with 29 small islands.",
  "lake-peipus": "Lake Peipus is Europe's largest cross-border lake.",
  "lake-saimaa": "Lake Saimaa is Finland's largest lake, home to a rare seal.",
  "kolsai-lake": "Kolsai Lake is known as the pearl of the northern Tian Shan.",
  "tianchi-lake": "Tianchi Lake sits at the foot of Bogda Peak in the Tian Shan.",
  "lake-retba": "Lake Retba turns bubblegum pink from salt-loving algae.",
  "lake-hillier": "Lake Hillier's pink comes from salt-loving microbes in its brine.",
  "lake-myvatn": "Lake Myvatn formed from a massive basalt lava eruption.",
  "laguna-colorada": "Laguna Colorada turns red from algae and mineral sediment.",
  "lake-naivasha": "Lake Naivasha is one of only two freshwater lakes in Kenya's Rift.",
  "chilika-lake": "Chilika Lake is Asia's largest brackish-water lagoon.",
  "songkhla-lake": "Songkhla Lake is Thailand's largest natural lake.",
  "lake-general-carrera": "Lake General Carrera hides marble caves carved by centuries of waves.",
  "lake-kawaguchi": "Lake Kawaguchi mirrors Mount Fuji on calm, clear mornings.",
  "lake-winnipeg": "Lake Winnipeg is one of the world's largest lakes by area.",
  "lake-onega": "Lake Onega is the second-largest lake in Europe.",
  "lake-assal": "Lake Assal sits below sea level in a volcanic depression.",
  "lake-bogoria": "Lake Bogoria has hot geysers steaming right at its shoreline.",
  "lake-manyara": "Lake Manyara sits at the base of the Great Rift Valley wall.",
  "ranau-lake": "Ranau Lake formed from an ancient volcanic caldera.",
  "lake-nahuel-huapi": "Lake Nahuel Huapi has its own local lake-monster legend.",
  "lake-pehoe": "Lake Pehoe glows turquoise from glacial meltwater sediment.",
  "lake-inari": "Lake Inari freezes solid enough to drive across in winter.",
  "lake-zurich": "Lake Zurich curves through Switzerland for about 25 miles.",
  "lugu-lake": "Lugu Lake is home to the matrilineal Mosuo people.",
  "lake-prespa": "Lake Prespa is shared by three Balkan countries.",
  "lake-tota": "Lake Tota is Colombia's largest natural lake.",
  "lake-enriquillo": "Lake Enriquillo sits below sea level and keeps rising.",
  "lake-peten-itza": "Lake Peten Itza hides Maya ruins beneath its surface.",
  "lake-rotorua": "Lake Rotorua sits in a volcanic crater and smells of sulfur.",
  "lake-toplitz": "Lake Toplitz has long been rumored to hide Nazi treasure.",
  "lake-karakul": "Lake Karakul formed from a meteorite impact millions of years ago.",
  "lake-hovsgol": "Lake Hovsgol holds about 70 percent of Mongolia's fresh water.",
};
