export const LANGUAGES_E90_FACTS = {
  "mandarin-chinese": "Chinese writing has no alphabet at all — it uses logographic characters, and while over 50,000 exist historically, only about 3,000 are needed for everyday newspaper literacy.",
  japanese: "Japanese is the only major living language that routinely mixes three different scripts — kanji, hiragana, and katakana — within a single sentence.",
  "korean-hangul": "Hangul was deliberately invented in 1443 by King Sejong the Great so commoners could become literate quickly, and linguists still cite it as one of the most scientifically designed writing systems ever made.",
  "russian-cyrillic": "The Cyrillic alphabet is named after Saint Cyril but was actually devised by his students, and today it writes over 50 languages across Eastern Europe and Central Asia.",
  arabic: "Arabic script runs right to left, and most of its letters change shape depending on whether they sit at the start, middle, or end of a word.",
  hebrew: "Modern Hebrew is one of the only languages in history to be successfully revived as an everyday spoken language after centuries of surviving solely in religious and literary use.",
  greek: "The Greek alphabet, created around the 8th century BC, was the first writing system in history to include dedicated letters for vowel sounds.",
  "hindi-devanagari": "Devanagari words are written hanging from a horizontal line called a shirorekha, which connects the tops of most letters in a word.",
  thai: "Thai script leaves no spaces between words in a sentence — spaces are reserved for marking the boundaries between clauses or full sentences.",
  armenian: "The Armenian alphabet was created around 405 AD by the monk Mesrop Mashtots and has stayed remarkably unchanged for over 1,600 years.",
  georgian: "Georgian script has no uppercase or lowercase distinction at all — every letter exists in only one form.",
  "amharic-ethiopic": "Ethiopic is an abugida where each symbol encodes a full consonant-vowel pair, giving the script well over 200 distinct character forms.",
  bengali: "The Bengali script, linked by a horizontal headline like its Devanagari cousin, is shared by two major languages — it's used to write both Bengali and Assamese.",
  tamil: "Tamil has one of the longest unbroken literary traditions of any language still written in its original script today, with texts dating back over 2,000 years.",
  "urdu-nastaliq": "Urdu and Hindi share nearly identical everyday grammar and vocabulary, but Urdu is written in the flowing Perso-Arabic Nastaliq style while Hindi uses Devanagari.",
  "punjabi-gurmukhi": "Gurmukhi was standardized in the 16th century by Guru Angad, the second Sikh Guru, specifically to record Sikh scripture in a script distinct from Persian and Devanagari.",
  khmer: "The Khmer alphabet has 74 letters, making it one of the longest alphabets used anywhere in the world today.",
  "mongolian-traditional": "Traditional Mongolian script is written top-to-bottom in vertical columns that progress left to right across the page — one of the very few scripts in the world oriented this way.",
  telugu: "Telugu's rounded letterforms, like those of several South Indian scripts, likely developed because letters were once incised into palm leaves, where straight strokes would tear the leaf.",
  kannada: "Kannada and Telugu scripts share the same rounded, curvy look because both evolved from the same ancient Kadamba script of southern India.",
  malayalam: "Malayalam has one of the largest letter inventories of any Indian script, partly because it kept extra symbols specifically to spell Sanskrit loanwords precisely.",
  gujarati: "Gujarati is the only major Indian script that dropped the horizontal headline (shirorekha) found in its close relatives Devanagari and Bengali.",
  sinhala: "Sinhala's rounded letters, like other South Asian scripts once etched into palm leaves, evolved that shape because straight-line strokes would have split the leaf.",
  "myanmar-burmese": "Burmese script is built almost entirely from circles and curves, a legacy of being traditionally scratched onto palm leaves with a stylus that couldn't manage sharp straight lines.",
  lao: "Lao script is a close cousin of Thai script — both descend from the same 13th-century Khmer-influenced Sukhothai writing tradition.",
  tibetan: "Tibetan script was created in the 7th century by the minister Thonmi Sambhota expressly so Buddhist scriptures could be translated into Tibetan from Sanskrit.",
  cherokee: "The Cherokee syllabary was invented single-handedly in the 1820s by Sequoyah, who could not read or write any language when he began — a nearly unmatched feat in writing-system history.",
  "canadian-aboriginal-syllabics": "Canadian Aboriginal Syllabics began as a system devised for Ojibwe and Cree in the 1840s and were later adapted for Inuktitut, ending up used to write more than a dozen Indigenous languages across Canada.",
  "vietnamese-diacritics": "Vietnamese uses the Latin alphabet, but piles on so many tone marks and diacritics that it ends up with well over 130 distinct letter-and-mark combinations.",
  nko: "N'Ko was invented in 1949 by Solomana Kanté partly to prove West African languages could have a dignified writing system of their own, independent of European or Arabic script.",
  tifinagh: "Tifinagh descends from an ancient Libyco-Berber script over 2,000 years old, making it one of the oldest alphabets still in active daily use.",
  syriac: "Syriac is a direct descendant of the Aramaic script used across the ancient Near East, the same language family Jesus is traditionally believed to have spoken.",
  coptic: "Coptic script is built from the Greek alphabet plus seven extra letters borrowed from Demotic Egyptian, making it a rare direct bridge between Greek writing and ancient Egyptian writing.",
  thaana: "Thaana is one of the few scripts in the world whose letters were derived partly from numerals — several characters trace back to Arabic and Indian number symbols.",
  javanese: "Javanese letters are traditionally taught through a 20-letter pangram poem that tells the legend of two loyal servants who fought each other to the death defending their master's honor.",
  balinese: "Balinese script was traditionally inscribed on dried palm leaves called lontar, a medium still used today to preserve sacred religious texts.",
  adlam: "Adlam was created in 1989 by teenage brothers Ibrahima and Abdoulaye Barry, and its name is an acronym of its first four letters meaning 'the alphabet that protects the peoples from vanishing.'",
  vai: "The Vai syllabary was invented around 1832 by Momolu Duwalu Bukele, who by his own account was shown the letters in a dream, before he had ever learned to read or write any language.",
  wancho: "Wancho script was designed between 2001 and 2012 by a single schoolteacher, Banwang Losu, to give the Wancho language of India's Arunachal Pradesh its own writing system.",
  "yi-nuosu": "The modern Yi syllabary was standardized by the Chinese government in the 1970s, selecting 819 characters out of many thousands of variant symbols used across different Yi regions.",
  batak: "Batak script was traditionally used by shamans called datu to write magical and divination texts on folded bark books known as pustaha.",
  baybayin: "Baybayin was the script used across the Philippines before Spanish colonization, and its name literally means 'to spell' in Tagalog.",
  ogham: "Ogham letters were carved as clusters of notches along the sharp edge of a standing stone, a design perfectly suited to cutting into a corner rather than a flat face.",
  "elder-futhark": "Elder Futhark takes its name from its first six letters, F-U-Þ-A-R-K, the exact same naming trick that gave Greek's alpha-beta the word 'alphabet.'",
  glagolitic: "Glagolitic, not Cyrillic, was actually the first alphabet created for the Slavic languages, devised in the 9th century by the missionary later canonized as Saint Cyril.",
  gothic: "The Gothic alphabet was invented in the 4th century by Bishop Wulfila so he could translate the Bible into Gothic, producing one of the oldest substantial texts surviving in any Germanic language.",
  "old-italic-etruscan": "The Etruscan alphabet, ancestor of the Latin alphabet English is written in today, is known largely from an abecedarium — a full alphabet carved in order onto an ivory tablet found at Marsiliana, Italy.",
  osmanya: "Osmanya was invented in the 1920s by Osman Yusuf Kenadid to give Somali, previously written only informally in Arabic script, its own dedicated alphabet.",
  samaritan: "The Samaritan alphabet descends directly from the ancient Paleo-Hebrew script used before the Babylonian exile, making its letterforms older in style than the square Hebrew script used today.",
  avestan: "The Avestan alphabet was custom-built to capture the precise pronunciation of Zoroastrian religious chants, giving it far more vowel symbols than most scripts of the ancient world.",
  deseret: "The Deseret alphabet was commissioned in the 1850s by Brigham Young for Utah Territory to make English spelling more phonetic, but it never caught on beyond a handful of printed books.",
  shavian: "The Shavian alphabet exists because playwright George Bernard Shaw left money in his will specifically to fund a new, more efficient phonetic alphabet for English.",
  "egyptian-hieroglyphs": "Egyptian hieroglyphs sat undeciphered for over 1,400 years until the 1799 discovery of the Rosetta Stone finally gave scholars a bilingual key to crack the script.",
  cuneiform: "Cuneiform, created by the Sumerians over 5,000 years ago, is among the very oldest writing systems, originally pressed into wet clay with a cut reed stylus.",
  "old-persian-cuneiform": "Old Persian cuneiform was commissioned under Darius the Great and is far simpler than its Mesopotamian relatives, using only around 36 signs instead of many hundreds.",
  "linear-b": "Linear B was deciphered in 1952 by architect Michael Ventris, an amateur outsider to academia, who proved it recorded an early form of Greek nearly a thousand years older than Homer.",
  phoenician: "The Phoenician alphabet, spread across the Mediterranean by seafaring traders, is the common ancestor of the Greek, Latin, Cyrillic, Hebrew, and Arabic alphabets used today.",
  "cypriot-syllabary": "The Cypriot syllabary kept being used to write Greek on Cyprus for centuries after most of the Greek-speaking world had already switched over to the alphabet.",
  ugaritic: "Ugaritic, unearthed on clay tablets in 1928, is technically a true alphabet even though its letters are pressed with wedge-shaped strokes like cuneiform — it borrowed the writing tool, not the writing system.",
  "old-hungarian": "Old Hungarian is one of the rare European scripts traditionally written right to left, and it lingered in limited use among the Székely people of Transylvania long after Hungary adopted the Latin alphabet.",
  kharoshthi: "Kharoshthi was used for some of Emperor Ashoka's 3rd-century BC edicts and was largely deciphered thanks to bilingual coins minted by Indo-Greek kings that paired it with Greek script.",
  "bassa-vah": "According to a contested oral tradition, it survived among enslaved Bassa people in the Americas before its 20th-century revival in Liberia.",
  osage: "The Osage script was created as recently as 2006 by Herman Mongrain Lookout, because Latin letters kept tripping up students who read Osage spellings with English pronunciation habits.",
  "old-turkic-gokturk": "Old Turkic runes were carved into the great Orkhon inscriptions of Mongolia, which are considered the oldest surviving substantial texts in any Turkic language.",
  lepcha: "Lepcha's vowel signs can wrap around their base consonant on several sides at once, letting the script pack in Lepcha's rich set of consonant clusters and tones.",
  limbu: "The Limbu script is also called Sirijanga, after a legendary Limbu hero-scholar credited with first devising it, centuries before it was formally revived in the 1920s.",
  "meetei-mayek": "Meetei Mayek's individual letters are named after parts of the human body, reflecting an old belief that the script's forms were modeled on the human figure.",
  chakma: "Beyond writing the Chakma language, this script is also used today to record Pali Buddhist texts.",
  "sora-sompeng": "Sora Sompeng's letters are each named after a different deity in the Sora pantheon, reflecting the script's roots in a 1936 religious reform movement.",
  "warang-citi": "Warang Citi's creator, Lako Bodra, said in the 1950s that its letters came to him in visions, and the script remains tied to the indigenous Sarna religious identity of the Ho people.",
};

export default LANGUAGES_E90_FACTS;
