export const LIGHTHOUSES_E62_FACTS = {
  // EASY
  "cape-hatteras-lighthouse": "America's tallest brick lighthouse, moved inland in 1999.",
  "portland-head-light": "Commissioned by George Washington in 1791.",
  "peggys-point-lighthouse": "One of the most photographed lighthouses in the world.",
  "eddystone-lighthouse": "The fourth lighthouse built on this treacherous reef.",
  "fastnet-lighthouse": "Nicknamed 'Ireland's Teardrop' by emigrants leaving home.",
  "cape-of-good-hope-lighthouse": "Warns ships near the tip of the African continent.",
  "jeddah-light": "One of the tallest lighthouses in the world.",
  "split-rock-lighthouse": "Built after a deadly 1905 storm on Lake Superior.",
  "pigeon-point-lighthouse": "Named after a ship that wrecked nearby in 1853.",
  "la-jument-lighthouse": "Made famous by a 1989 photo of a giant wave.",
  "cape-reinga-lighthouse": "Marks where the Tasman Sea meets the Pacific Ocean.",
  "sumburgh-head-lighthouse": "Scotland's first Northern Lighthouse Board light.",
  "cabo-da-roca-lighthouse": "Stands at continental Europe's westernmost point.",
  "genoa-lanterna": "One of the oldest lighthouses still active in the world.",
  "hook-lighthouse": "One of the oldest operating lighthouses on Earth.",
  "cape-byron-lighthouse": "Marks the easternmost point of mainland Australia.",
  "st-augustine-lighthouse": "Guards America's oldest continuously occupied city.",
  "green-point-lighthouse": "The oldest working lighthouse in South Africa.",

  // MEDIUM
  "bass-harbor-head-light": "Sits inside Acadia National Park in Maine.",
  "point-reyes-lighthouse": "One of the foggiest and windiest spots on the coast.",
  "longstone-lighthouse": "Site of Grace Darling's famous 1838 sea rescue.",
  "belle-tout-lighthouse": "Was moved back from crumbling cliffs in 1999.",
  "cape-otway-lighthouse": "Mainland Australia's oldest surviving lighthouse.",
  "amedee-lighthouse": "A cast-iron tower shipped from France in pieces.",
  "kjeungskjaer-lighthouse": "A striking octagonal red lighthouse on its own islet.",
  "cape-spear-lighthouse": "Marks the easternmost point of North America.",
  "les-eclaireurs-lighthouse": "Sits near Ushuaia, at the tip of South America.",
  "kannon-zaki-lighthouse": "Japan's second Western-style lighthouse, built in 1869.",
  "table-bluff-lighthouse": "Now a private aid to navigation in California.",
  "cabo-polonio-lighthouse": "Guides ships past Uruguay's remote seal colony.",
  "punta-delgada-lighthouse": "Overlooks a cliffside penguin and seal colony.",
  "cape-columbine-lighthouse": "The last major manned lighthouse built in South Africa.",
  "tolbukhin-lighthouse": "One of Russia's oldest lighthouses, built under Peter the Great.",
  "dunree-head-lighthouse": "Guards Ireland's Lough Swilly from an old fort site.",
  "kullens-fyr": "One of Sweden's most powerful lighthouse beams.",
  "rubjerg-knude-lighthouse": "Moved 70 meters inland in 2019 to escape erosion.",

  // HARD
  "wolf-rock-lighthouse": "Built on a wave-battered rock feared by sailors.",
  "bishop-rock-lighthouse": "Once listed as the world's tallest rock lighthouse.",
  "cordouan-lighthouse": "France's oldest lighthouse, a UNESCO World Heritage Site.",
  "cape-agulhas-lighthouse": "Marks the true meeting point of two oceans.",
  "chania-venetian-lighthouse": "One of the oldest lighthouses in the Mediterranean.",
  "punta-della-maestra-lighthouse": "Guards the marshy edge of Italy's Po Delta.",
  "cape-blanco-lighthouse": "Oregon's oldest and westernmost lighthouse.",
  "montauk-point-lighthouse": "New York's oldest lighthouse, commissioned by Washington.",
  "el-morro-lighthouse-havana": "Stands beside a 16th-century Spanish fortress.",
  "cape-arkona-lighthouse": "One of two lighthouses standing side by side on Rügen.",
  "ile-vierge-lighthouse": "The tallest stone lighthouse in Europe.",
  "cape-moreton-lighthouse": "Queensland's oldest lighthouse, built in 1857.",
  "nugget-point-lighthouse": "Named for jagged rock islets scattered offshore.",
  "cabo-san-isidro-lighthouse": "Overlooks the Strait of Magellan near Punta Arenas.",
  "isla-magdalena-lighthouse": "Shares its island with a huge penguin colony.",
  "cap-de-barbaria-lighthouse": "Stands on Formentera's rugged southern tip.",
  "cape-espichel-lighthouse": "One of Portugal's oldest lighthouses, built in 1790.",
  "ponta-do-calcanhar-lighthouse": "Marks Brazil's easternmost coastal point.",

  // IMPOSSIBLE
  "aniva-lighthouse": "An abandoned Soviet-era tower off Sakhalin Island.",
  "great-isaac-cay-lighthouse": "Linked to unsolved disappearances of its keepers.",
  "tourlitis-lighthouse": "Built on a tiny rock just offshore an Aegean island.",
  "evangelistas-lighthouse": "Guards the Pacific entrance to the Strait of Magellan.",
  "bell-rock-lighthouse": "The oldest surviving sea-washed lighthouse on Earth.",
  "cabo-raso-lighthouse": "Overlooks a windswept Patagonian bay in Argentina.",
  "cabo-san-antonio-lighthouse-cuba": "Marks the westernmost point of Cuba.",
  "cape-recife-lighthouse": "One of South Africa's oldest coastal lighthouses.",
  "punta-mogotes-lighthouse": "Guards a rocky point near Mar del Plata, Argentina.",
  "cape-race-lighthouse": "Received the Titanic's distress signal in 1912.",
  "matinicus-rock-light": "Sits on a remote island seabird sanctuary in Maine.",
  "cape-naturaliste-lighthouse": "Guards a whale-watching coastline in Western Australia.",
  "green-cape-lighthouse": "The last lighthouse built in 19th-century New South Wales.",
  "cape-borda-lighthouse": "Overlooks rugged cliffs on Kangaroo Island.",
  "farol-da-barra": "Brazil's oldest lighthouse, dating to the 1690s.",
  "farol-de-santa-marta": "Sits beside a historic fort in Cascais, Portugal.",
};

export default LIGHTHOUSES_E62_FACTS;
