// E62 "Guess the Lighthouse" — 70 real, standing lighthouses worldwide.
// Absolute difficulty: easy = globally iconic (~70-95% recognition of the shown structure),
// impossible = genuinely obscure regional lighthouses (<10%, most <3%).
// Zero Israel content (standing hard rule, all episodes).
export const LIGHTHOUSES_E62 = [
  // EASY (18)
  { slug: "cape-hatteras-lighthouse", name: "Cape Hatteras Lighthouse", country: "USA", level: "easy" },
  { slug: "portland-head-light", name: "Portland Head Light", country: "USA", level: "easy" },
  { slug: "peggys-point-lighthouse", name: "Peggy's Point Lighthouse", country: "Canada", level: "easy" },
  { slug: "eddystone-lighthouse", name: "Eddystone Lighthouse", country: "United Kingdom", level: "easy" },
  { slug: "fastnet-lighthouse", name: "Fastnet Lighthouse", country: "Ireland", level: "easy" },
  { slug: "cape-of-good-hope-lighthouse", name: "Cape Point Lighthouse", country: "South Africa", level: "easy" },
  { slug: "yokohama-marine-tower", name: "Yokohama Marine Tower", country: "Japan", level: "easy" },
  { slug: "split-rock-lighthouse", name: "Split Rock Lighthouse", country: "USA", level: "easy" },
  { slug: "pigeon-point-lighthouse", name: "Pigeon Point Lighthouse", country: "USA", level: "easy" },
  { slug: "la-jument-lighthouse", name: "La Jument Lighthouse", country: "France", level: "easy" },
  { slug: "cape-reinga-lighthouse", name: "Cape Reinga Lighthouse", country: "New Zealand", level: "easy" },
  { slug: "sumburgh-head-lighthouse", name: "Sumburgh Head Lighthouse", country: "United Kingdom", level: "easy" },
  { slug: "cabo-da-roca-lighthouse", name: "Cabo da Roca Lighthouse", country: "Portugal", level: "easy" },
  { slug: "genoa-lanterna", name: "Lanterna di Genova", country: "Italy", level: "easy" },
  { slug: "hook-lighthouse", name: "Hook Lighthouse", country: "Ireland", level: "easy" },
  { slug: "cape-byron-lighthouse", name: "Cape Byron Lighthouse", country: "Australia", level: "easy" },
  { slug: "st-augustine-lighthouse", name: "St. Augustine Lighthouse", country: "USA", level: "easy" },
  { slug: "green-point-lighthouse", name: "Green Point Lighthouse", country: "South Africa", level: "easy" },

  // MEDIUM (18)
  { slug: "bass-harbor-head-light", name: "Bass Harbor Head Light", country: "USA", level: "medium" },
  { slug: "point-reyes-lighthouse", name: "Point Reyes Lighthouse", country: "USA", level: "medium" },
  { slug: "longstone-lighthouse", name: "Longstone Lighthouse", country: "United Kingdom", level: "medium" },
  { slug: "belle-tout-lighthouse", name: "Belle Tout Lighthouse", country: "United Kingdom", level: "medium" },
  { slug: "cape-otway-lighthouse", name: "Cape Otway Lighthouse", country: "Australia", level: "medium" },
  { slug: "amedee-lighthouse", name: "Amédée Lighthouse", country: "New Caledonia", level: "medium" },
  { slug: "kjeungskjaer-lighthouse", name: "Kjeungskjær Lighthouse", country: "Norway", level: "medium" },
  { slug: "cape-spear-lighthouse", name: "Cape Spear Lighthouse", country: "Canada", level: "medium" },
  { slug: "les-eclaireurs-lighthouse", name: "Les Éclaireurs Lighthouse", country: "Argentina", level: "medium" },
  { slug: "kannon-zaki-lighthouse", name: "Kannon-zaki Lighthouse", country: "Japan", level: "medium" },
  { slug: "table-bluff-lighthouse", name: "Table Bluff Lighthouse", country: "USA", level: "medium" },
  { slug: "cabo-polonio-lighthouse", name: "Cabo Polonio Lighthouse", country: "Uruguay", level: "medium" },
  { slug: "punta-delgada-lighthouse", name: "Punta Delgada Lighthouse", country: "Argentina", level: "medium" },
  { slug: "cape-columbine-lighthouse", name: "Cape Columbine Lighthouse", country: "South Africa", level: "medium" },
  { slug: "tolbukhin-lighthouse", name: "Tolbukhin Lighthouse", country: "Russia", level: "medium" },
  { slug: "dunree-head-lighthouse", name: "Dunree Head Lighthouse", country: "Ireland", level: "medium" },
  { slug: "kullens-fyr", name: "Kullen Lighthouse", country: "Sweden", level: "medium" },
  { slug: "rubjerg-knude-lighthouse", name: "Rubjerg Knude Lighthouse", country: "Denmark", level: "medium" },

  // HARD (18)
  { slug: "wolf-rock-lighthouse", name: "Wolf Rock Lighthouse", country: "United Kingdom", level: "hard" },
  { slug: "bishop-rock-lighthouse", name: "Bishop Rock Lighthouse", country: "United Kingdom", level: "hard" },
  { slug: "cordouan-lighthouse", name: "Cordouan Lighthouse", country: "France", level: "hard" },
  { slug: "ponta-do-calcanhar-lighthouse", name: "Ponta do Calcanhar Lighthouse", country: "Brazil", level: "hard" },
  { slug: "cape-agulhas-lighthouse", name: "Cape Agulhas Lighthouse", country: "South Africa", level: "hard" },
  { slug: "chania-venetian-lighthouse", name: "Venetian Lighthouse", country: "Greece", level: "hard" },
  { slug: "capo-spartivento-lighthouse", name: "Capo Spartivento Lighthouse", country: "Italy", level: "hard" },
  { slug: "cape-blanco-lighthouse", name: "Cape Blanco Lighthouse", country: "USA", level: "hard" },
  { slug: "montauk-point-lighthouse", name: "Montauk Point Lighthouse", country: "USA", level: "hard" },
  { slug: "el-morro-lighthouse-havana", name: "El Morro Lighthouse", country: "Cuba", level: "hard" },
  { slug: "cape-arkona-lighthouse", name: "Cape Arkona Lighthouse", country: "Germany", level: "hard" },
  { slug: "ile-vierge-lighthouse", name: "Île Vierge Lighthouse", country: "France", level: "hard" },
  { slug: "cape-moreton-lighthouse", name: "Cape Moreton Lighthouse", country: "Australia", level: "hard" },
  { slug: "nugget-point-lighthouse", name: "Nugget Point Lighthouse", country: "New Zealand", level: "hard" },
  { slug: "cabo-san-isidro-lighthouse", name: "Cabo San Isidro Lighthouse", country: "Chile", level: "hard" },
  { slug: "isla-magdalena-lighthouse", name: "Isla Magdalena Lighthouse", country: "Chile", level: "hard" },
  { slug: "cap-de-barbaria-lighthouse", name: "Cap de Barbaria Lighthouse", country: "Spain", level: "hard" },
  { slug: "cape-espichel-lighthouse", name: "Cape Espichel Lighthouse", country: "Portugal", level: "hard" },

  // IMPOSSIBLE (16)
  { slug: "aniva-lighthouse", name: "Aniva Lighthouse", country: "Russia", level: "impossible" },
  { slug: "great-isaac-cay-lighthouse", name: "Great Isaac Cay Lighthouse", country: "Bahamas", level: "impossible" },
  { slug: "tourlitis-lighthouse", name: "Tourlitis Lighthouse", country: "Greece", level: "impossible" },
  { slug: "evangelistas-lighthouse", name: "Evangelistas Lighthouse", country: "Chile", level: "impossible" },
  { slug: "bell-rock-lighthouse", name: "Bell Rock Lighthouse", country: "United Kingdom", level: "impossible" },
  { slug: "faro-recalada-bahia-blanca", name: "Recalada a Bahía Blanca Lighthouse", country: "Argentina", level: "impossible" },
  { slug: "cabo-san-antonio-lighthouse-cuba", name: "Cabo San Antonio Lighthouse", country: "Cuba", level: "impossible" },
  { slug: "cape-recife-lighthouse", name: "Cape Recife Lighthouse", country: "South Africa", level: "impossible" },
  { slug: "punta-mogotes-lighthouse", name: "Punta Mogotes Lighthouse", country: "Argentina", level: "impossible" },
  { slug: "cape-race-lighthouse", name: "Cape Race Lighthouse", country: "Canada", level: "impossible" },
  { slug: "matinicus-rock-light", name: "Matinicus Rock Light", country: "USA", level: "impossible" },
  { slug: "cape-naturaliste-lighthouse", name: "Cape Naturaliste Lighthouse", country: "Australia", level: "impossible" },
  { slug: "green-cape-lighthouse", name: "Green Cape Lighthouse", country: "Australia", level: "impossible" },
  { slug: "cape-borda-lighthouse", name: "Cape Borda Lighthouse", country: "Australia", level: "impossible" },
  { slug: "farol-da-barra", name: "Farol da Barra", country: "Brazil", level: "impossible" },
  { slug: "farol-de-santa-marta", name: "Santa Marta Lighthouse", country: "Portugal", level: "impossible" },
];

export default LIGHTHOUSES_E62;
