// Episode 3 "Guess the Logo" — 100 items, absolute-difficulty calibrated (25/tier).
// Judged by LOGO MARK recognizability, not company fame.
// HARD RULE: no Israeli companies — verified absent (Wix considered and excluded).
// Slugs match Simple Icons (simpleicons.org) exactly; 23 originally-planned brands
// aren't on Simple Icons (Amazon, Disney, Adobe, Slack, Canva, etc.) and were swapped
// for same-tier alternatives that ARE available, to keep sourcing 100% consistent.
// Car logos capped at 7 to leave room for a future dedicated car-logos episode.
export const LOGOS_E03 = [
  // EASY (25)
  { slug: "google", name: "Google", level: "easy" },
  { slug: "apple", name: "Apple", level: "easy" },
  { slug: "nike", name: "Nike", level: "easy" },
  { slug: "mcdonalds", name: "McDonald's", level: "easy" },
  { slug: "cocacola", name: "Coca-Cola", level: "easy" },
  { slug: "youtube", name: "YouTube", level: "easy" },
  { slug: "facebook", name: "Facebook", level: "easy" },
  { slug: "instagram", name: "Instagram", level: "easy" },
  { slug: "whatsapp", name: "WhatsApp", level: "easy" },
  { slug: "toyota", name: "Toyota", level: "easy" },
  { slug: "netflix", name: "Netflix", level: "easy" },
  { slug: "tiktok", name: "TikTok", level: "easy" },
  { slug: "snapchat", name: "Snapchat", level: "easy" },
  { slug: "ford", name: "Ford", level: "easy" },
  { slug: "bmw", name: "BMW", level: "easy" },
  { slug: "ferrari", name: "Ferrari", level: "easy" },
  { slug: "shell", name: "Shell", level: "easy" },
  { slug: "starbucks", name: "Starbucks", level: "easy" },
  { slug: "kfc", name: "KFC", level: "easy" },
  { slug: "mastercard", name: "Mastercard", level: "easy" },
  { slug: "visa", name: "Visa", level: "easy" },
  { slug: "samsung", name: "Samsung", level: "easy" },
  { slug: "android", name: "Android", level: "easy" },
  { slug: "playstation", name: "PlayStation", level: "easy" },
  { slug: "sony", name: "Sony", level: "easy" },

  // MEDIUM (25)
  { slug: "spotify", name: "Spotify", level: "medium" },
  { slug: "airbnb", name: "Airbnb", level: "medium" },
  { slug: "reddit", name: "Reddit", level: "medium" },
  { slug: "pinterest", name: "Pinterest", level: "medium" },
  { slug: "adidas", name: "Adidas", level: "medium" },
  { slug: "puma", name: "Puma", level: "medium" },
  { slug: "underarmour", name: "Under Armour", level: "medium" },
  { slug: "handm", name: "H&M", level: "medium" },
  { slug: "zara", name: "Zara", level: "medium" },
  { slug: "uber", name: "Uber", level: "medium" },
  { slug: "intel", name: "Intel", level: "medium" },
  { slug: "paypal", name: "PayPal", level: "medium" },
  { slug: "ebay", name: "eBay", level: "medium" },
  { slug: "nvidia", name: "Nvidia", level: "medium" },
  { slug: "steam", name: "Steam", level: "medium" },
  { slug: "duolingo", name: "Duolingo", level: "medium" },
  { slug: "volkswagen", name: "Volkswagen", level: "medium" },
  { slug: "audi", name: "Audi", level: "medium" },
  { slug: "honda", name: "Honda", level: "medium" },
  { slug: "ikea", name: "IKEA", level: "medium" },
  { slug: "reebok", name: "Reebok", level: "medium" },
  { slug: "monster", name: "Monster Energy", level: "medium" },
  { slug: "redbull", name: "Red Bull", level: "medium" },
  { slug: "burgerking", name: "Burger King", level: "medium" },
  { slug: "zoom", name: "Zoom", level: "medium" },

  // HARD (25)
  { slug: "figma", name: "Figma", level: "hard" },
  { slug: "notion", name: "Notion", level: "hard" },
  { slug: "twitch", name: "Twitch", level: "hard" },
  { slug: "docker", name: "Docker", level: "hard" },
  { slug: "discord", name: "Discord", level: "hard" },
  { slug: "dropbox", name: "Dropbox", level: "hard" },
  { slug: "trello", name: "Trello", level: "hard" },
  { slug: "asana", name: "Asana", level: "hard" },
  { slug: "github", name: "GitHub", level: "hard" },
  { slug: "etsy", name: "Etsy", level: "hard" },
  { slug: "soundcloud", name: "SoundCloud", level: "hard" },
  { slug: "vimeo", name: "Vimeo", level: "hard" },
  { slug: "grammarly", name: "Grammarly", level: "hard" },
  { slug: "unity", name: "Unity", level: "hard" },
  { slug: "coursera", name: "Coursera", level: "hard" },
  { slug: "corsair", name: "Corsair", level: "hard" },
  { slug: "newbalance", name: "New Balance", level: "hard" },
  { slug: "razer", name: "Razer", level: "hard" },
  { slug: "porsche", name: "Porsche", level: "hard" },
  { slug: "mailchimp", name: "Mailchimp", level: "hard" },
  { slug: "shopify", name: "Shopify", level: "hard" },
  { slug: "squarespace", name: "Squarespace", level: "hard" },
  { slug: "behance", name: "Behance", level: "hard" },
  { slug: "evernote", name: "Evernote", level: "hard" },
  { slug: "udemy", name: "Udemy", level: "hard" },

  // IMPOSSIBLE (25)
  { slug: "okta", name: "Okta", level: "impossible" },
  { slug: "datadog", name: "Datadog", level: "impossible" },
  { slug: "splunk", name: "Splunk", level: "impossible" },
  { slug: "pagerduty", name: "PagerDuty", level: "impossible" },
  { slug: "kubernetes", name: "Kubernetes", level: "impossible" },
  { slug: "zendesk", name: "Zendesk", level: "impossible" },
  { slug: "hubspot", name: "HubSpot", level: "impossible" },
  { slug: "mongodb", name: "MongoDB", level: "impossible" },
  { slug: "cockroachlabs", name: "Cockroach Labs", level: "impossible" },
  { slug: "grafana", name: "Grafana", level: "impossible" },
  { slug: "hashicorp", name: "HashiCorp", level: "impossible" },
  { slug: "circleci", name: "CircleCI", level: "impossible" },
  { slug: "postman", name: "Postman", level: "impossible" },
  { slug: "airtable", name: "Airtable", level: "impossible" },
  { slug: "miro", name: "Miro", level: "impossible" },
  { slug: "calendly", name: "Calendly", level: "impossible" },
  { slug: "loom", name: "Loom", level: "impossible" },
  { slug: "buffer", name: "Buffer", level: "impossible" },
  { slug: "intercom", name: "Intercom", level: "impossible" },
  { slug: "netlify", name: "Netlify", level: "impossible" },
  { slug: "snowflake", name: "Snowflake", level: "impossible" },
  { slug: "prometheus", name: "Prometheus", level: "impossible" },
  { slug: "fastly", name: "Fastly", level: "impossible" },
  { slug: "sentry", name: "Sentry", level: "impossible" },
  { slug: "newrelic", name: "New Relic", level: "impossible" },
];
export default LOGOS_E03;
