// Episode 3 "Guess the Logo" — one verified ≤70-char fact per brand, keyed by slug.
// Verified via quiz-fact-verifier agent pass (2 corrections applied: mastercard, calendly).
export const LOGOS_E03_FACTS = {
  "google": "Google was originally named 'Backrub'.",
  "apple": "Apple's logo once featured Isaac Newton under a tree.",
  "nike": "Nike's Swoosh logo was designed for just $35.",
  "mcdonalds": "McDonald's first mascot was 'Speedee,' not Ronald.",
  "cocacola": "Coca-Cola was originally sold as a medicine tonic.",
  "youtube": "YouTube's first video was 'Me at the zoo' in 2005.",
  "facebook": "Facebook began as a Harvard dorm-room project in 2004.",
  "instagram": "Instagram's first photo was a dog at a taco stand.",
  "whatsapp": "WhatsApp's name is a pun on 'What's Up?'",
  "toyota": "Toyota began as a loom-making company in Japan.",
  "netflix": "Netflix launched in 1998 renting DVDs by mail.",
  "tiktok": "TikTok grew from the Chinese app Douyin, launched 2016.",
  "snapchat": "Snapchat began as a class project called Picaboo.",
  "ford": "Ford's Model T made cars affordable for average people.",
  "bmw": "BMW originally made aircraft engines, not cars.",
  "ferrari": "Ferrari's prancing horse honored a WWI flying ace.",
  "shell": "Shell began as a shop selling seashells in London.",
  "starbucks": "Starbucks is named after a character in Moby-Dick.",
  "kfc": "KFC's founder started the franchise in his 60s.",
  "mastercard": "Mastercard's interlocking circles logo has run since 1968.",
  "visa": "Visa began as BankAmericard in California, 1958.",
  "samsung": "Samsung started in 1938 as a grocery trading firm.",
  "android": "Android was named after its founder's robot nickname.",
  "playstation": "PlayStation began as a Nintendo-Sony joint project.",
  "sony": "Sony's first product was an electric rice cooker.",
  "spotify": "Spotify was founded in Sweden by Daniel Ek in 2006.",
  "airbnb": "Airbnb's original name was AirBed & Breakfast.",
  "reddit": "Reddit's name comes from the phrase 'read it'.",
  "pinterest": "Pinterest's name blends the words 'pin' and 'interest'.",
  "adidas": "Adidas' name blends founder Adi Dassler's nickname.",
  "puma": "Puma was founded by Adidas founder Adi Dassler's brother.",
  "underarmour": "Under Armour was founded by ex-football player Kevin Plank.",
  "handm": "H&M started in Sweden in 1947 as 'Hennes' (hers).",
  "zara": "Zara was founded in Spain in 1975 by Amancio Ortega.",
  "uber": "Uber's original name when founded in 2009 was UberCab.",
  "intel": "Intel's name blends the words 'integrated electronics'.",
  "paypal": "PayPal began in 1998 under the name Confinity.",
  "ebay": "eBay was originally launched in 1995 as AuctionWeb.",
  "nvidia": "Nvidia was co-founded in 1993 by Jensen Huang.",
  "steam": "Valve launched the Steam platform back in 2003.",
  "duolingo": "Duolingo's co-founder Luis von Ahn co-created CAPTCHA.",
  "volkswagen": "Volkswagen means 'people's car' in German.",
  "audi": "Audi is Latin for 'listen,' a play on founder Horch's name.",
  "honda": "Honda began as a piston ring maker before making cars.",
  "ikea": "IKEA is an acronym of founder Ingvar Kamprad's name.",
  "reebok": "Reebok is named after an African antelope, the rhebok.",
  "monster": "Monster Energy launched in 2002 by Hansen Natural Corp.",
  "redbull": "Red Bull was inspired by a Thai drink, Krating Daeng.",
  "burgerking": "Burger King was originally called Insta-Burger King.",
  "zoom": "Zoom's founder Eric Yuan once worked on Cisco's Webex.",
  "figma": "Adobe's $20B deal to buy Figma collapsed in 2023.",
  "notion": "Notion nearly died in 2015 before its 2016 relaunch.",
  "twitch": "Amazon bought Twitch for $970 million in 2014.",
  "docker": "Docker began as a company called dotCloud.",
  "discord": "Discord began as a failed video game studio.",
  "dropbox": "Dropbox's founder once turned down an offer from Steve Jobs.",
  "trello": "Trello was acquired by Atlassian for $425 million.",
  "asana": "Asana was founded by a Facebook co-founder.",
  "github": "Microsoft bought GitHub for $7.5 billion in 2018.",
  "etsy": "Etsy launched in 2005 from a Brooklyn apartment.",
  "soundcloud": "SoundCloud was founded by two Swedes in Berlin.",
  "vimeo": "Vimeo began in 2004 as a CollegeHumor side project.",
  "grammarly": "Grammarly was founded by Ukrainians in Kyiv.",
  "unity": "Unity Technologies was founded in Copenhagen, Denmark.",
  "coursera": "Coursera was founded by two Stanford professors.",
  "corsair": "Corsair began in 1994 making PC memory modules.",
  "newbalance": "New Balance still makes some shoes in the USA.",
  "razer": "Razer is dual-headquartered in the US and Singapore.",
  "porsche": "Porsche's first car, the Type 64, was built in 1939.",
  "mailchimp": "Mailchimp never took VC funding before its $12B sale.",
  "shopify": "Shopify began as an online snowboard shop.",
  "squarespace": "Squarespace started in a college dorm room in 2003.",
  "behance": "Adobe acquired Behance for about $150 million in 2012.",
  "evernote": "Evernote's elephant logo nods to 'never forgets'.",
  "udemy": "Udemy's name blends the words 'you' and 'academy'.",
  "okta": "Okta's name comes from a meteorology term for cloud cover.",
  "datadog": "Datadog's name comes from a nickname for database servers: dogs.",
  "splunk": "Splunk's name derives from 'spelunking,' meaning cave exploring.",
  "pagerduty": "PagerDuty began in 2009 solving on-call incident response.",
  "kubernetes": "Kubernetes' logo has 7 spokes, a nod to Google's 'Project Seven'.",
  "zendesk": "Zendesk was founded in Copenhagen, Denmark, not the US.",
  "hubspot": "HubSpot popularized the term 'inbound marketing.'",
  "mongodb": "MongoDB's name comes from the word 'humongous.'",
  "cockroachlabs": "CockroachDB is named for the bug's legendary near-indestructibility.",
  "grafana": "Grafana began in 2014 as a fork of the Kibana dashboard tool.",
  "hashicorp": "HashiCorp's name honors founder Hashimoto; 'hashi' means bridge.",
  "circleci": "CircleCI, founded in 2011, was an early CI-as-a-service pioneer.",
  "postman": "Postman began in 2012 as one dev's side-project Chrome extension.",
  "airtable": "Airtable, founded in 2012, blends a spreadsheet with a database.",
  "miro": "Miro was called RealtimeBoard until rebranding in 2019.",
  "calendly": "Calendly stayed nearly bootstrapped until its first big 2021 raise.",
  "loom": "Loom was acquired by Atlassian in 2023 for $975 million.",
  "buffer": "Buffer has publicly shared every employee's salary since 2013.",
  "intercom": "Intercom, the customer messaging platform, was founded in Dublin.",
  "netlify": "Netlify's founders coined the term 'Jamstack' in 2015.",
  "snowflake": "Snowflake's 2020 IPO was the largest software IPO ever.",
  "prometheus": "Prometheus monitoring was created at SoundCloud in 2012.",
  "fastly": "In 2021, a Fastly bug broke huge chunks of the internet.",
  "sentry": "Sentry began as an internal tool at Disqus in 2010.",
  "newrelic": "New Relic's name is an anagram of founder Lew Cirne's name.",
};
export default LOGOS_E03_FACTS;
