export const MLB_E80_FACTS = {
  "new-york-yankees": "Has won 27 World Series titles, by far the most of any team.",
  "los-angeles-dodgers": "Jackie Robinson broke MLB's color line with this team in 1947.",
  "boston-red-sox": "Went 86 title-less years — fans called it the Curse of the Bambino.",
  "chicago-cubs": "Ended a 108-year title drought, the longest in North American sports.",
  "san-francisco-giants": "Moved from New York to San Francisco in 1958.",
  "st-louis-cardinals": "Has won 11 World Series titles, the most of any National League team.",
  "atlanta-braves": "Is MLB's oldest continuously operating franchise, dating to 1871.",
  "new-york-mets": "Won its first World Series in just its eighth season, in 1969.",
  "houston-astros": "Switched from the National League to the American League in 2013.",
  "philadelphia-phillies": "Holds the record for most losses ever by a pro sports franchise.",
  "toronto-blue-jays": "Is the only MLB team based outside the United States.",
  "chicago-white-sox": "Its 1919 World Series scandal became known as the Black Sox Scandal.",
  "texas-rangers": "Began in 1961 as the Washington Senators before relocating in 1972.",
  "san-diego-padres": "Has reached the World Series twice but never won one.",
  "seattle-mariners": "Is the only 1969-77 expansion team never to reach a World Series.",
  "baltimore-orioles": "Was the St. Louis Browns before moving to Baltimore in 1954.",
  "detroit-tigers": "Is one of eight charter American League franchises from 1901.",
  "minnesota-twins": "Began as the original Washington Senators before moving in 1961.",
  "cleveland-guardians": "Was renamed from the Indians to the Guardians for the 2022 season.",
  "milwaukee-brewers": "Is the only team to host an All-Star Game in both leagues.",
  "cincinnati-reds": "Cincinnati fielded the first all-pro team, the 1869 Red Stockings.",
  "pittsburgh-pirates": "Played in the first modern World Series, back in 1903.",
  "arizona-diamondbacks": "Won the World Series in just its fourth season, in 2001.",
  "kansas-city-royals": "Was named via a fan contest, after the American Royal livestock show.",
  "colorado-rockies": "Plays at MLB's highest-altitude park, about 5,200 feet up.",
  "tampa-bay-rays": "Reached its first World Series in just its 11th season, in 2008.",
  "miami-marlins": "Won the World Series in only its fifth season, in 1997.",
  "athletics": "Dropped its city name in 2025 while awaiting a new Las Vegas ballpark.",
  "washington-nationals": "Was the Montreal Expos before relocating to Washington in 2005.",
  "los-angeles-angels": "Has played under five different names since its 1961 founding.",
};

export default MLB_E80_FACTS;
