export const MOSQUES_E61_FACTS = {
  // EASY
  "sheikh-zayed-grand-mosque": "Holds one of the world's largest hand-knotted carpets.",
  "blue-mosque": "Named for the blue tiles lining its interior walls.",
  "masjid-al-haram": "Surrounds Islam's holiest site, the Kaaba.",
  "al-masjid-an-nabawi": "The Prophet Muhammad's tomb lies within its grounds.",
  "faisal-mosque": "Its tent-like design has no traditional dome.",
  "hassan-ii-mosque": "Home to one of the tallest minarets on Earth.",
  "suleymaniye-mosque": "Designed by the master architect Mimar Sinan.",
  "badshahi-mosque": "Was once the largest mosque in the world.",
  "jama-masjid-delhi": "Built by the same emperor who built the Taj Mahal.",
  "sultan-omar-ali-saifuddien-mosque": "Its dome is covered in real gold.",
  "putra-mosque": "Built almost entirely from rose-tinted granite.",
  "istiqlal-mosque": "The largest mosque in Southeast Asia.",
  "king-abdullah-i-mosque": "Topped by a striking blue mosaic dome.",
  "sheikh-lotfollah-mosque": "Famous for its cream-colored dome that shifts color.",
  "shah-mosque-isfahan": "A UNESCO site famed for its seven-color tilework.",
  "crystal-mosque": "Appears to float above the water it overlooks.",
  "koutoubia-mosque": "Its minaret inspired towers in Seville and Rabat.",
  "grand-mosque-of-paris": "Built to honor North African WWI soldiers.",

  // MEDIUM
  "mohammed-al-amin-mosque": "Built by PM Rafic Hariri; completed in 2008.",
  "zahir-mosque": "One of Malaysia's oldest and grandest mosques.",
  "baiturrahman-grand-mosque": "Survived the devastating 2004 tsunami largely intact.",
  "great-mosque-of-djenne": "The world's largest mudbrick building.",
  "great-mosque-of-kairouan": "One of the oldest places of worship in Islam.",
  "al-azhar-mosque": "Attached to one of the world's oldest universities.",
  "ibn-tulun-mosque": "Cairo's largest mosque by land area.",
  "muhammad-ali-mosque": "Overlooks Cairo from atop its ancient citadel.",
  "sultan-hassan-mosque": "A masterpiece of Mamluk-era architecture.",
  "masjid-negara": "Its roof folds like an 18-pointed star.",
  "shah-alam-mosque": "Its blue dome is among the largest in the world.",
  "istanbul-new-mosque": "Took nearly 60 years to complete, with a long pause.",
  "sultan-qaboos-grand-mosque": "Once held the world's largest single hand-woven carpet.",
  "king-hussein-bin-talal-mosque": "One of Jordan's largest and most modern mosques.",
  "great-mosque-of-xian": "Blends Chinese pagoda architecture with Islamic design.",
  "niujie-mosque": "Beijing's oldest and largest mosque.",
  "kul-sharif-mosque": "Rebuilt inside the Kazan Kremlin after centuries.",
  "moscow-cathedral-mosque": "One of the largest mosques in Europe.",

  // HARD
  "rustem-pasha-mosque": "Famed for its wall-to-wall Iznik tilework.",
  "selimiye-mosque": "Considered Mimar Sinan's finest architectural work.",
  "mosque-cathedral-of-cordoba": "Famous for its forest of red-and-white striped arches.",
  "great-mosque-of-sanaa": "One of the oldest mosques in the Islamic world.",
  "baitul-mukarram": "Bangladesh's national mosque.",
  "star-mosque-dhaka": "Covered in star-shaped mosaic tiles, mostly blue.",
  "id-kah-mosque": "China's largest mosque, in Kashgar.",
  "great-mosque-of-herat": "Also known as the Friday Mosque of Herat.",
  "blue-mosque-mazar-i-sharif": "Said to hold the tomb of Ali, cousin of Muhammad.",
  "bibi-khanym-mosque": "Once one of the largest mosques in the Islamic world.",
  "kalyan-mosque": "Stands beside Bukhara's towering Kalyan Minaret.",
  "hazrat-sultan-mosque": "Central Asia's largest mosque.",
  "central-mosque-almaty": "Kazakhstan's largest city's main mosque.",
  "grand-mosque-of-kuwait": "Kuwait's national mosque, opened in 1986.",
  "imam-muhammad-ibn-abdul-wahhab-mosque": "Qatar's official state mosque.",
  "jumeirah-mosque": "One of the few Dubai mosques open to non-Muslim visitors.",
  "wazir-khan-mosque": "Famous for its intricate Persian-style tile mosaics.",
  "great-mosque-of-aleppo": "Heavily damaged during Syria's civil war.",

  // IMPOSSIBLE
  "tin-mal-mosque": "One of the few Moroccan mosques open to non-Muslims.",
  "jameh-mosque-of-yazd": "Its portal holds two of Iran's tallest minarets.",
  "jameh-mosque-of-isfahan": "Showcases 1,200 years of Islamic architecture styles.",
  "nasir-al-mulk-mosque": "Nicknamed the Pink Mosque for its rose-colored tiles.",
  "vakil-mosque": "Famous for its 48 spiral-carved stone columns.",
  "male-grand-friday-mosque": "The Maldives' largest mosque, topped with a gold dome.",
  "jamiul-alfar-mosque": "A candy-striped red-and-white landmark in Colombo.",
  "lala-mustafa-pasha-mosque": "A former Gothic cathedral converted into a mosque.",
  "islamic-center-of-america": "The largest mosque in North America.",
  "baitul-futuh-mosque": "Called Western Europe's largest mosque at its 2003 opening.",
  "cologne-central-mosque": "Germany's largest mosque, opened in 2018.",
  "grand-mosque-of-rome": "The largest mosque in Western Europe.",
  "tokyo-camii": "Japan's largest mosque, built in Ottoman style.",
  "auwal-mosque": "South Africa's oldest mosque.",
  "jamia-mosque-nairobi": "Nairobi's oldest and most prominent mosque.",
  "king-fahd-islamic-center-buenos-aires": "The largest mosque in Latin America.",
  "blue-mosque-yerevan": "The only functioning mosque in Armenia.",
  "jinnah-memorial-mosque": "Named for Pakistan's founder, Muhammad Ali Jinnah.",
};

export default MOSQUES_E61_FACTS;
