// E75 "Guess the Motorcycle" — 70 real motorcycles/scooters, easy->impossible. First
// motorcycle-themed episode on the channel (distinct from all prior car episodes).
export const MOTORCYCLES_E75 = [
  // EASY (18)
  { slug: "harley-davidson-fat-boy", name: "Harley-Davidson Fat Boy", wiki: "Harley-Davidson Softail", level: "easy" },
  { slug: "vespa", name: "Vespa", wiki: "Vespa", level: "easy" },
  { slug: "honda-super-cub", name: "Honda Super Cub", wiki: "Honda Super Cub", level: "easy" },
  { slug: "ducati-panigale", name: "Ducati Panigale", wiki: "Ducati Panigale", level: "easy" },
  { slug: "kawasaki-ninja", name: "Kawasaki Ninja H2", wiki: "Kawasaki Ninja H2", level: "easy" },
  { slug: "triumph-bonneville", name: "Triumph Bonneville", wiki: "Triumph Bonneville", level: "easy" },
  { slug: "bmw-r1250gs", name: "BMW R 1250 GS", wiki: "BMW R1250GS", level: "easy" },
  { slug: "harley-davidson-sportster", name: "Harley-Davidson Sportster", wiki: "Harley-Davidson Sportster", level: "easy" },
  { slug: "yamaha-yzf-r1", name: "Yamaha YZF-R1", wiki: "Yamaha YZF-R1", level: "easy" },
  { slug: "suzuki-hayabusa", name: "Suzuki Hayabusa", wiki: "Suzuki Hayabusa", level: "easy" },
  { slug: "honda-gold-wing", name: "Honda Gold Wing", wiki: "Honda Gold Wing", level: "easy" },
  { slug: "royal-enfield-bullet", name: "Royal Enfield Bullet", wiki: "Royal Enfield Bullet", level: "easy" },
  { slug: "harley-davidson-road-king", name: "Harley-Davidson Road King", wiki: "Harley-Davidson Touring", level: "easy" },
  { slug: "ducati-monster", name: "Ducati Monster", wiki: "Ducati Monster", level: "easy" },
  { slug: "ktm-duke", name: "KTM Duke", wiki: "KTM Duke", level: "easy" },
  { slug: "honda-cbr600rr", name: "Honda CBR600RR", wiki: "Honda CBR600RR", level: "easy" },
  { slug: "yamaha-mt-07", name: "Yamaha MT-07", wiki: "Yamaha MT-07", level: "easy" },
  { slug: "indian-scout", name: "Indian Scout", wiki: "Indian Scout", level: "easy" },

  // MEDIUM (18)
  { slug: "kawasaki-z900", name: "Kawasaki Z900", wiki: "Kawasaki Z900", level: "medium" },
  { slug: "suzuki-gsx-r750", name: "Suzuki GSX-R750", wiki: "Suzuki GSX-R750", level: "medium" },
  { slug: "triumph-street-triple", name: "Triumph Street Triple", wiki: "Triumph Street Triple", level: "medium" },
  { slug: "ducati-diavel", name: "Ducati Diavel", wiki: "Ducati Diavel", level: "medium" },
  { slug: "bmw-s1000rr", name: "BMW S 1000 RR", wiki: "BMW S1000RR", level: "medium" },
  { slug: "harley-davidson-street-glide", name: "Harley-Davidson Street Glide", wiki: "Harley-Davidson Touring", level: "medium" },
  { slug: "honda-africa-twin", name: "Honda Africa Twin", wiki: "Honda Africa Twin", level: "medium" },
  { slug: "yamaha-tenere-700", name: "Yamaha Ténéré 700", wiki: "Yamaha Ténéré", level: "medium" },
  { slug: "ktm-1290-super-duke", name: "KTM 1290 Super Duke R", wiki: "KTM 1290 Super Duke R", level: "medium" },
  { slug: "aprilia-rsv4", name: "Aprilia RSV4", wiki: "Aprilia RSV4", level: "medium" },
  { slug: "moto-guzzi-v7", name: "Moto Guzzi V7", wiki: "Moto Guzzi V7", level: "medium" },
  { slug: "triumph-tiger", name: "Triumph Tiger", wiki: "Triumph Tiger (motorcycle)", level: "medium" },
  { slug: "kawasaki-vulcan", name: "Kawasaki Vulcan", wiki: "Kawasaki Vulcan", level: "medium" },
  { slug: "suzuki-boulevard", name: "Suzuki Boulevard", wiki: "Suzuki Boulevard M109R", level: "medium" },
  { slug: "honda-rebel", name: "Honda Rebel", wiki: "Honda Rebel 500", level: "medium" },
  { slug: "yamaha-bolt", name: "Yamaha Bolt", wiki: "Yamaha Bolt", level: "medium" },
  { slug: "indian-chief", name: "Indian Chief", wiki: "Indian Chief", level: "medium" },
  { slug: "harley-davidson-iron-883", name: "Harley-Davidson Iron 883", wiki: "Harley-Davidson Sportster", level: "medium" },

  // HARD (16)
  { slug: "mv-agusta-f4", name: "MV Agusta F4", wiki: "MV Agusta F4", level: "hard" },
  { slug: "ducati-scrambler", name: "Ducati Scrambler", wiki: "Ducati Scrambler", level: "hard" },
  { slug: "norton-commando", name: "Norton Commando", wiki: "Norton Commando", level: "hard" },
  { slug: "bsa-gold-star", name: "BSA Gold Star", wiki: "BSA Gold Star", level: "hard" },
  { slug: "vespa-gts", name: "Vespa GTS", wiki: "Vespa GTS", level: "hard" },
  { slug: "piaggio-liberty", name: "Piaggio Liberty", wiki: "Piaggio Liberty", level: "hard" },
  { slug: "harley-davidson-livewire", name: "Harley-Davidson LiveWire", wiki: "LiveWire (motorcycle)", level: "hard" },
  { slug: "energica-ego", name: "Energica Ego", wiki: "Energica Motor Company", level: "hard" },
  { slug: "husqvarna-vitpilen", name: "Husqvarna Vitpilen", wiki: "Husqvarna Vitpilen 401", level: "hard" },
  { slug: "benelli-tnt", name: "Benelli TNT", wiki: "Benelli TnT", level: "hard" },
  { slug: "royal-enfield-himalayan", name: "Royal Enfield Himalayan", wiki: "Royal Enfield Himalayan", level: "hard" },
  { slug: "honda-monkey", name: "Honda Monkey", wiki: "Honda Monkey", level: "hard" },
  { slug: "yamaha-sr400", name: "Yamaha SR400", wiki: "Yamaha SR400", level: "hard" },
  { slug: "kawasaki-klr650", name: "Kawasaki KLR650", wiki: "Kawasaki KLR650", level: "hard" },
  { slug: "suzuki-v-strom", name: "Suzuki V-Strom", wiki: "Suzuki V-Strom", level: "hard" },
  { slug: "lambretta-li", name: "Lambretta LI", wiki: "Lambretta", level: "hard" },

  // IMPOSSIBLE (18)
  { slug: "bimota-tesi", name: "Bimota Tesi", wiki: "Bimota Tesi", level: "impossible" },
  { slug: "megola", name: "Megola", wiki: "Megola", level: "impossible" },
  { slug: "brough-superior-ss100", name: "Brough Superior SS100", wiki: "Brough Superior SS100", level: "impossible" },
  { slug: "vincent-black-shadow", name: "Vincent Black Shadow", wiki: "Vincent Black Shadow", level: "impossible" },
  { slug: "ariel-square-four", name: "Ariel Square Four", wiki: "Ariel Square Four", level: "impossible" },
  { slug: "cushman-eagle", name: "Cushman Eagle", wiki: "Cushman", level: "impossible" },
  { slug: "ossa-mar", name: "Ossa Mick Andrews Replica", wiki: "OSSA", level: "impossible" },
  { slug: "bultaco-sherpa", name: "Bultaco Sherpa", wiki: "Bultaco", level: "impossible" },
  { slug: "jawa-350", name: "Jawa 350", wiki: "Jawa Moto", level: "impossible" },
  { slug: "mz-etz", name: "MZ ETZ", wiki: "MZ Motorrad- und Zweiradwerk", level: "impossible" },
  { slug: "ural-gear-up", name: "Ural Gear-Up", wiki: "Ural Motorcycles", level: "impossible" },
  { slug: "cz-175", name: "Čezeta", wiki: "Čezeta", level: "impossible" },
  { slug: "rokon-trail-breaker", name: "Rokon Trail-Breaker", wiki: "Rokon", level: "impossible" },
  { slug: "britten-v1000", name: "Britten V1000", wiki: "Britten V1000", level: "impossible" },
  { slug: "vyrus-987", name: "Vyrus 987", wiki: "Vyrus", level: "impossible" },
  { slug: "horex-vr6", name: "Horex VR6", wiki: "Horex", level: "impossible" },
  { slug: "voxan-wattman", name: "Voxan Wattman", wiki: "Voxan", level: "impossible" },
  { slug: "royal-enfield-continental-gt", name: "Royal Enfield Continental GT", wiki: "Royal Enfield Continental GT", level: "impossible" },
];
export default MOTORCYCLES_E75;
