export const MOTORCYCLES_E75_FACTS = {
  "harley-davidson-fat-boy": "Featured a solid steel-look wheel design when it launched in 1990.",
  "vespa": "Its name means \"wasp\" in Italian, inspired by its body shape.",
  "honda-super-cub": "The best-selling motor vehicle in history, with over 100 million made.",
  "ducati-panigale": "Named after the small Italian town where Ducati was founded.",
  "kawasaki-ninja": "The H2 version uses a supercharged engine, rare for a production bike.",
  "triumph-bonneville": "Named after a land-speed record set on Utah's Bonneville Salt Flats.",
  "bmw-r1250gs": "Its boxer engine has cylinders that stick out sideways from the bike.",
  "harley-davidson-sportster": "Introduced in 1957, one of Harley's longest-running model lines.",
  "yamaha-yzf-r1": "Its name pays tribute to Yamaha's YZR-M1 MotoGP race bike.",
  "suzuki-hayabusa": "Named after a falcon known for diving at extremely high speed.",
  "honda-gold-wing": "A touring motorcycle so large it's nicknamed a \"land yacht.\"",
  "royal-enfield-bullet": "The longest continuously produced motorcycle design in history.",
  "harley-davidson-road-king": "Part of Harley's Touring family, built for long highway rides.",
  "ducati-monster": "Its stripped-down, engine-exposed look defined the naked bike genre.",
  "ktm-duke": "KTM markets its naked-bike lineup under the slogan \"Ready to Race.\"",
  "honda-cbr600rr": "Developed using technology borrowed from Honda's MotoGP program.",
  "yamaha-mt-07": "Part of Yamaha's \"Master of Torque\" naked bike lineup.",
  "indian-scout": "First launched in 1920, decades before Harley's Sportster rival.",
  "kawasaki-z900": "Revives the name of Kawasaki's legendary 1970s Z1 superbike family.",
  "suzuki-gsx-r750": "Nicknamed the \"Gixxer,\" a pioneer of the modern sportbike class.",
  "triumph-street-triple": "Powered by a three-cylinder engine, unusual among naked bikes.",
  "ducati-diavel": "Its name is Bolognese dialect for \"devil.\"",
  "bmw-s1000rr": "BMW's first modern inline-four superbike, launched in 2009.",
  "harley-davidson-street-glide": "Recognizable by its shark-nose front fairing design.",
  "honda-africa-twin": "Named for Honda's dominance at the Paris-Dakar Rally.",
  "yamaha-tenere-700": "Named after the Ténéré desert region of the Sahara.",
  "ktm-1290-super-duke": "Nicknamed \"The Beast\" for its powerful V-twin engine.",
  "aprilia-rsv4": "One of the few superbikes built around a V4 engine layout.",
  "moto-guzzi-v7": "Powered by a transverse V-twin, a Moto Guzzi trademark layout.",
  "triumph-tiger": "Triumph's long-running adventure-touring model family.",
  "kawasaki-vulcan": "Named after the Roman god of fire, fitting a V-twin cruiser.",
  "suzuki-boulevard": "Suzuki's cruiser lineup, aimed squarely at American-style riding.",
  "honda-rebel": "A beginner-friendly cruiser popular for its low seat height.",
  "yamaha-bolt": "Styled after 1970s American bobber customs.",
  "indian-chief": "Indian's flagship cruiser, first built in the 1920s.",
  "harley-davidson-iron-883": "Part of Harley's blacked-out \"Dark Custom\" Sportster series.",
  "mv-agusta-f4": "Its design was penned by famed stylist Massimo Tamburini.",
  "ducati-scrambler": "Revives a playful, retro off-road model line from the 1960s.",
  "norton-commando": "Named Britain's Motor Cycle of the Year five years running.",
  "bsa-gold-star": "Named for a badge awarded to riders who lapped Brooklands at 100 mph.",
  "vespa-gts": "A larger, more powerful evolution of the classic Vespa scooter.",
  "piaggio-liberty": "One of Piaggio's most popular everyday commuter scooters.",
  "harley-davidson-livewire": "Harley's first electric model, with no clutch or gears to shift.",
  "energica-ego": "An Italian-built electric superbike aimed at track performance.",
  "husqvarna-vitpilen": "Its name means \"white arrow\" in Swedish.",
  "benelli-tnt": "TNT stands for \"Tornado Naked Tre,\" referencing its triple engine.",
  "royal-enfield-himalayan": "Built specifically to handle the rugged terrain of its namesake range.",
  "honda-monkey": "A tiny mini-bike originally designed for a Japanese amusement park.",
  "yamaha-sr400": "Kept its kick-start-only design long after most bikes went electric.",
  "kawasaki-klr650": "A dual-sport bike famous for reliably crossing continents.",
  "suzuki-v-strom": "Its name blends \"V-twin\" with the Swedish word for \"stream.\"",
  "lambretta-li": "Vespa's biggest scooter rival, born in postwar Milan.",
  "bimota-tesi": "Used an unusual hub-center steering system instead of forks.",
  "confederate-wraith": "A boutique American brand known for aircraft-grade aluminum frames.",
  "brough-superior-ss100": "Once called \"the Rolls-Royce of motorcycles\" by a magazine.",
  "vincent-black-shadow": "Was the world's fastest production motorcycle in its era.",
  "ariel-square-four": "Used a rare engine with four cylinders arranged in a square.",
  "cushman-eagle": "An American scooter brand that began by making motorized carts.",
  "ossa-mar": "A Spanish trials bike that won European Championship glory in 1971.",
  "bultaco-sherpa": "Helped kickstart the sport of modern trials riding.",
  "jawa-350": "A Czech two-stroke twin popular across the former Eastern Bloc.",
  "mz-etz": "An East German motorcycle exported widely during the Cold War.",
  "ural-gear-up": "A Russian sidecar bike that can power its third wheel too.",
  "cz-175": "A pre-war Czech motorcycle from a maker once known for weapons.",
  "rokon-trail-breaker": "Unusual for having power sent to both of its wheels.",
  "britten-v1000": "A radical hand-built New Zealand superbike, only ten ever made.",
  "vyrus-987": "A boutique Italian brand using hub-center steering like Bimota.",
  "horex-vr6": "Its engine crams six cylinders into a narrow VR configuration.",
  "voxan-wattman": "Once held the land speed record for an electric motorcycle.",
  "royal-enfield-continental-gt": "A café racer inspired by 1960s British coffee-bar culture.",
};
