// Episode 14 "Guess the Mountain" — one verified <=70-char fact per item, keyed by slug.
export const MOUNTAINS_E14_FACTS = {
  "mount-everest": "Everest grows about 4mm taller every year from tectonic uplift.",
  "kilimanjaro": "Kilimanjaro is Earth's tallest free-standing peak above sea level.",
  "mount-vesuvius": "Vesuvius buried the city of Pompeii in ash back in 79 AD.",
  "table-mountain": "Table Mountain is often capped by clouds called the 'tablecloth.'",
  "sugarloaf-mountain": "Sugarloaf Mountain is a giant slab of solid granite and quartz.",
  "mont-blanc": "Mont Blanc is the tallest peak in the Alps and Western Europe.",
  "denali": "Denali means 'the tall one' in the Koyukon Athabascan language.",
  "mount-olympus": "Ancient Greeks believed Mount Olympus was home to their gods.",
  "ben-nevis": "Ben Nevis is the highest mountain in the British Isles.",
  "aoraki-mount-cook": "Aoraki is New Zealand's tallest peak and a Maori sacred site.",
  "mount-elbrus": "Mount Elbrus is Europe's tallest peak, formed by a dormant volcano.",
  "cotopaxi": "Cotopaxi is one of the highest active volcanoes on Earth.",
  "huangshan": "Huangshan inspired centuries of Chinese painting and poetry.",
  "fitz-roy": "Fitz Roy's jagged spire inspired the Patagonia clothing logo.",
  "mount-kinabalu": "Mount Kinabalu is Borneo's tallest peak and a UNESCO site.",
  "zugspitze": "Zugspitze is Germany's highest peak, shared with Austria's border.",
  "mount-bromo": "Mount Bromo sits inside a vast volcanic sea of ash and sand.",
  "mount-kenya": "Mount Kenya is an extinct volcano and Africa's second-tallest peak.",
  "popocatepetl": "Popocatépetl's name means 'smoking mountain' in Nahuatl.",
  "jungfrau": "The Jungfrau railway station is Europe's highest, at 3,454m.",
  "mount-roraima": "Mount Roraima's flat summit inspired the movie Up.",
  "mount-kosciuszko": "Mount Kosciuszko is Australia's tallest mainland peak.",
  "mayon-volcano": "Mayon Volcano is famous for its near-perfect cone shape.",
  "mount-logan": "Mount Logan is Canada's tallest peak and North America's second.",
  "grossglockner": "Grossglockner is Austria's highest mountain, capped by a glacier.",
  "mount-damavand": "Mount Damavand is the tallest volcano in all of Asia.",
  "huascaran": "Huascarán is Peru's tallest peak in the Cordillera Blanca range.",
  "adams-peak": "Adam's Peak is a pilgrimage site for four different religions.",
  "drakensberg": "The Drakensberg range's name means 'dragon mountains' in Afrikaans.",
  "mount-rainier": "Mount Rainier is an active volcano near Seattle, Washington.",
  "aconcagua": "Aconcagua is the tallest peak outside of Asia.",
  "annapurna": "Annapurna has one of the highest fatality rates of any 8,000m peak.",
  "mount-etna": "Mount Etna is one of the most active volcanoes on Earth.",
  "mount-nemrut": "Mount Nemrut's summit holds ancient royal tomb statues.",
  "nanda-devi": "Nanda Devi is India's second-tallest peak, named for a goddess.",
  "mount-aso": "Mount Aso holds one of the largest volcanic calderas on Earth.",
  "mount-kailash": "Mount Kailash is sacred to four religions and remains unclimbed.",
  "toubkal": "Toubkal is the tallest peak in North Africa's Atlas Mountains.",
  "fansipan": "Fansipan is the tallest peak in Indochina, reached by cable car.",
  "mount-nyiragongo": "Nyiragongo holds one of the world's largest lava lakes.",
  "triglav": "Triglav is Slovenia's tallest peak and appears on its flag.",
  "margherita-peak": "Margherita Peak sits on the fabled 'Mountains of the Moon.'",
  "illimani": "Illimani towers over the Bolivian capital city of La Paz.",
  "carrauntoohil": "Carrauntoohil is the tallest mountain on the island of Ireland.",
  "blue-mountain-peak": "The Blue Mountains here grow some of the world's priciest coffee.",
  "ras-dashen": "Ras Dashen is Ethiopia's tallest peak in the Simien Mountains.",
  "mount-cameroon": "Mount Cameroon is West Africa's tallest peak and an active volcano.",
  "hallasan": "Hallasan is South Korea's tallest peak, atop Jeju Island.",
  "puncak-jaya": "Puncak Jaya is Earth's tallest island peak, near the equator.",
  "pico-de-orizaba": "Pico de Orizaba is Mexico's tallest peak and a dormant volcano.",
  "chimborazo": "Chimborazo's summit is the farthest point from Earth's center.",
  "eiger": "The Eiger's north face is one of the deadliest climbs in the Alps.",
  "mount-robson": "Mount Robson is the tallest peak in Canada's Rocky Mountains.",
  "mount-apo": "Mount Apo is the Philippines' tallest peak and a dormant volcano.",
  "dhaulagiri": "Dhaulagiri was briefly believed to be the world's tallest peak.",
  "galdhopiggen": "Galdhøpiggen is the tallest mountain in Norway and Scandinavia.",
  "kebnekaise": "Kebnekaise's icy summit has slowly shrunk due to melting glaciers.",
  "mulhacen": "Mulhacén is mainland Spain's tallest peak, named after a Moorish king.",
  "musala": "Musala is the tallest peak in Bulgaria and the Balkan Peninsula.",
  "pico-ruivo": "Pico Ruivo is the tallest peak on Portugal's island of Madeira.",
  "cerro-chirripo": "Cerro Chirripó is Costa Rica's tallest peak, with views of two oceans.",
  "mount-karisimbi": "Mount Karisimbi is home to some of the last mountain gorillas.",
  "brandberg": "Brandberg Mountain is Namibia's tallest peak, named 'fire mountain.'",
  "moldoveanu-peak": "Moldoveanu Peak is Romania's tallest point, in the Carpathians.",
  "volcan-baru": "Volcán Barú is Panama's tallest peak, an inactive volcano.",
  "mount-mulanje": "Mount Mulanje is Malawi's tallest peak, nicknamed 'Island in the Sky.'",
  "emi-koussi": "Emi Koussi is Chad's tallest peak, a volcano in the Sahara desert.",
  "mount-tahat": "Mount Tahat is Algeria's tallest peak in the Sahara's Hoggar range.",
  "gerlachovsky-stit": "Gerlachovský štít is the tallest peak in Slovakia's Tatra Mountains.",
  "halti": "Halti is Finland's tallest point, on the border with Norway.",
  "thabana-ntlenyana": "Thabana Ntlenyana is the tallest peak in southern Africa.",
};
