export const MOVIE_STUDIO_LOGOS_E28_FACTS = {
  "walt-disney-pictures": "The Disney logo castle blends Sleeping Beauty and Cinderella Castles.",
  "warner-bros-pictures": "Warner Bros. was founded in 1923 by four brothers.",
  "universal-pictures": "Universal Pictures is one of the oldest studios, founded 1912.",
  "pixar": "Pixar's first feature film was 1995's Toy Story.",
  "paramount-pictures": "Paramount Pictures traces its origin back to 1912.",
  "20th-century-studios": "20th Century Studios was renamed from 20th Century Fox in 2020.",
  "sony-pictures": "Sony Pictures owns the historic Columbia Pictures brand.",
  "marvel-studios": "Marvel Studios launched the MCU with Iron Man in 2008.",
  "dreamworks-animation": "DreamWorks was co-founded by Steven Spielberg in 1994.",
  "netflix": "Netflix began as a DVD-by-mail rental service in 1997.",
  "columbia-pictures": "Columbia Pictures' logo lady is nicknamed the 'Torch Lady.'",
  "metro-goldwyn-mayer": "MGM's roaring lion mascot has been used since the 1920s.",
  "lucasfilm": "Lucasfilm was founded by George Lucas in 1971.",
  "hbo": "HBO launched in 1972 as the first US pay TV network.",
  "new-line-cinema": "New Line Cinema produced the Lord of the Rings trilogy.",
  "amazon-mgm-studios": "Amazon acquired MGM Studios for $8.45 billion in 2022.",
  "illumination": "Illumination created the Minions from Despicable Me.",
  "blue-sky-studios": "Blue Sky Studios made the Ice Age film franchise.",

  "miramax": "Miramax was named after founders' parents, Mira and Max.",
  "lionsgate": "Lionsgate distributed the Hunger Games film series.",
  "a24": "A24 won Best Picture for Moonlight and Everything Everywhere.",
  "focus-features": "Focus Features specializes in art-house and indie films.",
  "studio-ghibli": "Studio Ghibli was co-founded by director Hayao Miyazaki.",
  "legendary-pictures": "Legendary co-produced Nolan's Dark Knight trilogy.",
  "screen-gems": "Screen Gems began as Columbia Pictures' TV production arm.",
  "tristar-pictures": "TriStar Pictures' logo features a winged flying horse.",
  "touchstone-pictures": "Touchstone Pictures let Disney release more mature films.",
  "castle-rock-entertainment": "Castle Rock is named after a fictional Stephen King town.",
  "orion-pictures": "Orion Pictures won the Best Picture Oscar four times.",
  "village-roadshow-pictures": "Village Roadshow co-financed The Matrix film trilogy.",
  "relativity-media": "Relativity Media pioneered new Hollywood film financing deals.",
  "summit-entertainment": "Summit Entertainment released the Twilight Saga films.",
  "stx-entertainment": "STX Entertainment launched as a mini-major studio in 2014.",
  "working-title-films": "Working Title Films made Bridget Jones's Diary and Notting Hill.",
  "imagine-entertainment": "Imagine Entertainment was co-founded by Ron Howard and Brian Grazer.",
  "amblin-entertainment": "Amblin Entertainment's logo shows a scene from E.T.",

  "toho": "Toho is the Japanese studio behind the Godzilla franchise.",
  "studiocanal": "StudioCanal is a major French film production company.",
  "gramercy-pictures": "Gramercy Pictures released the Coen Brothers' Fargo in 1996.",
  "hollywood-pictures": "Hollywood Pictures was a Disney label active in the 1990s.",
  "carolco-pictures": "Carolco Pictures produced the Rambo and Terminator sequels.",
  "cannon-films": "Cannon Films was known for cheap 1980s action movies.",
  "vertigo-entertainment": "Vertigo Entertainment produced The Ring horror remake.",
  "participant-media": "Participant Media made films focused on social issues.",
  "annapurna-pictures": "Annapurna Pictures was founded by Megan Ellison in 2011.",
  "bleecker-street": "Bleecker Street is named after a street in Manhattan.",
  "neon": "Neon distributed the Oscar-winning film Parasite.",
  "filmdistrict": "FilmDistrict released Insidious and Drive in 2011.",
  "overture-films": "Overture Films was a short-lived Starz-owned studio.",
  "millennium-films": "Millennium Media renamed itself from Millennium Films in 2017.",
  "constantin-film": "Constantin Film is one of Germany's biggest movie studios.",
  "europacorp": "EuropaCorp was founded by director Luc Besson in France.",
  "aardman-animations": "Aardman made Wallace & Gromit using Plasticine models.",
  "laika": "Laika makes stop-motion films like Coraline and ParaNorman.",

  "rankin-bass-productions": "Rankin/Bass made classic stop-motion holiday TV specials.",
  "embassy-pictures": "Embassy Pictures released The Graduate in 1967.",
  "american-international-pictures": "AIP specialized in low-budget teen and horror B-movies.",
  "filmation": "Filmation produced classic Saturday morning cartoons.",
  "empire-international-pictures": "Empire International Pictures made 1980s fantasy B-movies.",
  "vestron-pictures": "Vestron Pictures started as a home video distributor.",
  "new-world-pictures": "New World Pictures was founded by director Roger Corman.",
  "cinergi-pictures": "Cinergi Pictures produced Die Hard with a Vengeance.",
  "morgan-creek-entertainment": "Morgan Creek produced the Ace Ventura comedy films.",
  "polygram-filmed-entertainment": "PolyGram Filmed Entertainment was owned by a music company.",
  "trimark-pictures": "Trimark Pictures released the Leprechaun horror series.",
  "full-moon-features": "Full Moon Features made the Puppet Master horror films.",
  "troma-entertainment": "Troma Entertainment created The Toxic Avenger character.",
  "the-weinstein-company": "The Weinstein Company was founded by Harvey and Bob Weinstein.",
  "rko-pictures": "RKO Pictures produced the original King Kong in 1933.",
  "republic-pictures": "Republic Pictures was known for classic Western films.",
  "monogram-pictures": "Monogram Pictures made low-budget B-movies in the 1930s-40s.",
};
