// Episode 12 "Guess the Movie Character" — one verified <=70-char fact per item, keyed by slug.
export const MOVIE_CHARACTERS_E12_FACTS = {
  "mickey-mouse": "Mickey Mouse debuted in the 1928 short Steamboat Willie.",
  "elsa-frozen": "Elsa can create ice and snow just by touching things.",
  shrek: "Shrek is based on a 1990 picture book by William Steig.",
  minions: "The Minions speak a made-up language called Minionese.",
  "woody-toy-story": "Woody is a cowboy doll voiced by Tom Hanks.",
  "buzz-lightyear": "Buzz Lightyear insists his flying is 'falling with style.'",
  simba: "Simba means 'lion' in Swahili.",
  "ariel-little-mermaid": "Ariel gives up her voice in a deal with Ursula.",
  dory: "Dory has short-term memory loss, a defining trait.",
  "genie-aladdin": "The Genie was famously voiced by Robin Williams in 1992.",
  stitch: "Stitch was designed as Experiment 626, an alien fugitive.",
  "snow-white": "Snow White was Disney's first full-length animated film in 1937.",
  nemo: "Nemo has a smaller fin, referred to as his 'lucky fin.'",
  gru: "Gru originally plans to steal the moon.",
  "winnie-the-pooh": "Winnie the Pooh loves honey more than almost anything.",
  olaf: "Olaf is a snowman brought to life by Elsa's powers.",
  "mike-wazowski": "Mike Wazowski is a one-eyed green monster.",
  sulley: "Sulley is short for James P. Sullivan, a giant blue monster.",
  "anna-frozen": "Anna is Elsa's younger sister and heir to Arendelle.",
  belle: "Belle falls for the Beast despite his frightening looks.",
  "donkey-shrek": "Donkey never stops talking, much to Shrek's annoyance.",
  "lightning-mcqueen": "Lightning McQueen dreams of winning the Piston Cup.",
  "wall-e": "WALL-E spends centuries alone compacting trash on Earth.",
  toothless: "Toothless is a rare Night Fury dragon.",
  "po-kung-fu-panda": "Po becomes the legendary Dragon Warrior by surprise.",
  "judy-hopps": "Judy Hopps is Zootopia's first rabbit police officer.",
  baymax: "Baymax is an inflatable healthcare companion robot.",
  totoro: "Totoro is a forest spirit only children can easily see.",
  "mater": "Mater is a rusty tow truck and Lightning's best friend.",
  "puss-in-boots": "Puss in Boots first appeared as a hired assassin in Shrek 2.",
  "fiona-shrek": "Fiona turns into an ogre every night under a curse.",
  "remy-ratatouille": "Remy is a rat with a gifted sense of smell and taste.",
  hiccup: "Hiccup is the first Viking to befriend a dragon.",
  "carl-fredricksen": "Carl ties thousands of balloons to lift his house.",
  "rapunzel-tangled": "Rapunzel's magical hair glows when she sings.",
  moana: "Moana sails across the ocean to restore a stolen heart.",
  "mr-incredible": "Mr. Incredible has superhuman strength and durability.",
  "joy-inside-out": "Joy is one of five emotions living inside Riley's mind.",
  "mulan-character": "Mulan disguises herself as a man to join the army.",
  "scar-lion-king": "Scar is Mufasa's jealous younger brother.",
  ursula: "Ursula is a sea witch with octopus tentacles.",
  "maleficent-animated": "Maleficent curses Aurora after being snubbed at a party.",
  merida: "Merida is a skilled archer and Scottish princess.",
  scrat: "Scrat spends every Ice Age film chasing a single acorn.",
  "sid-sloth": "Sid is a clumsy, talkative ground sloth.",
  "anastasia-1997": "Anastasia is loosely inspired by the last Russian grand duchess.",
  jafar: "Jafar is the Sultan's scheming royal vizier.",
  "miles-morales-animated": "Miles Morales becomes a new Spider-Man after a spider bite.",
  "nick-wilde": "Nick Wilde is a sly fox turned honest cop partner.",
  "alex-the-lion": "Alex the Lion is the star attraction at the Central Park Zoo.",
  "grinch-animated": "The Grinch tries to stop Christmas by stealing all its gifts.",
  "edna-mode": "Edna Mode designs supersuits for the Incredible family.",
  "coraline-jones": "Coraline discovers an 'Other' version of her family.",
  gromit: "Gromit is a silent, expressive dog smarter than his owner.",
  "milo-thatch": "Milo Thatch searches for the lost city of Atlantis.",
  "iron-giant": "The Iron Giant is a massive robot that fell from the sky.",
  balto: "Balto was a real sled dog who helped save Nome from diphtheria.",
  littlefoot: "Littlefoot is a young Apatosaurus searching for a new home.",
  kubo: "Kubo tells stories using a magical paper origami art.",
  "robyn-goodfellowe": "Robyn befriends a wild wolfwalker in 1650s Ireland.",
  "saoirse-song-of-the-sea": "Saoirse is a selkie who can transform into a seal.",
  "brendan-secret-of-kells": "Brendan illustrates the real illuminated Book of Kells.",
  "max-mary-and-max": "Max has Asperger's syndrome in this claymation film.",
  "klaus-2019": "Klaus reimagines how Santa Claus's legend began.",
  "cale-tucker": "Cale Tucker searches for a lost human ark ship.",
  "kayley-quest-for-camelot": "Kayley dreams of joining King Arthur's Knights of the Round Table.",
  "fievel-mousekewitz": "Fievel gets separated from his family sailing to America.",
  "sinbad-legend-seven-seas": "Sinbad sails the seas as a legendary sailor and thief.",
  "chanticleer-rock-a-doodle": "Chanticleer is a rooster whose crowing makes the sun rise.",
  "odette-swan-princess": "Odette is cursed to transform into a swan by day.",
  oliver: "Oliver is an orphaned kitten taken in by a gang of dogs.",
};
export default MOVIE_CHARACTERS_E12_FACTS;
