// E28 "Guess the Movie Studio" — answer = studio name, image = official studio logo.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
export const MOVIE_STUDIO_LOGOS_E28 = [
  // EASY (18) — globally iconic, instantly recognized worldwide
  { slug: "walt-disney-pictures", name: "Walt Disney Pictures", level: "easy" },
  { slug: "warner-bros-pictures", name: "Warner Bros. Pictures", level: "easy" },
  { slug: "universal-pictures", name: "Universal Pictures", level: "easy" },
  { slug: "pixar", name: "Pixar", level: "easy" },
  { slug: "paramount-pictures", name: "Paramount Pictures", level: "easy" },
  { slug: "20th-century-studios", name: "20th Century Studios", level: "easy" },
  { slug: "sony-pictures", name: "Sony Pictures", level: "easy" },
  { slug: "marvel-studios", name: "Marvel Studios", level: "easy" },
  { slug: "dreamworks-animation", name: "DreamWorks Animation", level: "easy" },
  { slug: "netflix", name: "Netflix", level: "easy" },
  { slug: "columbia-pictures", name: "Columbia Pictures", level: "easy" },
  { slug: "metro-goldwyn-mayer", name: "Metro-Goldwyn-Mayer", level: "easy" },
  { slug: "lucasfilm", name: "Lucasfilm", level: "easy" },
  { slug: "hbo", name: "HBO", level: "easy" },
  { slug: "new-line-cinema", name: "New Line Cinema", level: "easy" },
  { slug: "amazon-mgm-studios", name: "Amazon MGM Studios", level: "easy" },
  { slug: "illumination", name: "Illumination", level: "easy" },
  { slug: "blue-sky-studios", name: "Blue Sky Studios", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "miramax", name: "Miramax", level: "medium" },
  { slug: "lionsgate", name: "Lionsgate", level: "medium" },
  { slug: "a24", name: "A24", level: "medium" },
  { slug: "focus-features", name: "Focus Features", level: "medium" },
  { slug: "studio-ghibli", name: "Studio Ghibli", level: "medium" },
  { slug: "legendary-pictures", name: "Legendary Pictures", level: "medium" },
  { slug: "screen-gems", name: "Screen Gems", level: "medium" },
  { slug: "tristar-pictures", name: "TriStar Pictures", level: "medium" },
  { slug: "touchstone-pictures", name: "Touchstone Pictures", level: "medium" },
  { slug: "castle-rock-entertainment", name: "Castle Rock Entertainment", level: "medium" },
  { slug: "orion-pictures", name: "Orion Pictures", level: "medium" },
  { slug: "village-roadshow-pictures", name: "Village Roadshow Pictures", level: "medium" },
  { slug: "relativity-media", name: "Relativity Media", level: "medium" },
  { slug: "summit-entertainment", name: "Summit Entertainment", level: "medium" },
  { slug: "stx-entertainment", name: "STX Entertainment", level: "medium" },
  { slug: "working-title-films", name: "Working Title Films", level: "medium" },
  { slug: "imagine-entertainment", name: "Imagine Entertainment", level: "medium" },
  { slug: "amblin-entertainment", name: "Amblin Entertainment", level: "medium" },

  // HARD (18) — recognizable to film enthusiasts
  { slug: "toho", name: "Toho", level: "hard" },
  { slug: "studiocanal", name: "StudioCanal", level: "hard" },
  { slug: "gramercy-pictures", name: "Gramercy Pictures", level: "hard" },
  { slug: "hollywood-pictures", name: "Hollywood Pictures", level: "hard" },
  { slug: "carolco-pictures", name: "Carolco Pictures", level: "hard" },
  { slug: "cannon-films", name: "Cannon Films", level: "hard" },
  { slug: "vertigo-entertainment", name: "Vertigo Entertainment", level: "hard" },
  { slug: "participant-media", name: "Participant Media", level: "hard" },
  { slug: "annapurna-pictures", name: "Annapurna Pictures", level: "hard" },
  { slug: "bleecker-street", name: "Bleecker Street", level: "hard" },
  { slug: "neon", name: "Neon", level: "hard" },
  { slug: "filmdistrict", name: "FilmDistrict", level: "hard" },
  { slug: "overture-films", name: "Overture Films", level: "hard" },
  { slug: "millennium-films", name: "Millennium Media", level: "hard" },
  { slug: "constantin-film", name: "Constantin Film", level: "hard" },
  { slug: "europacorp", name: "EuropaCorp", level: "hard" },
  { slug: "aardman-animations", name: "Aardman Animations", level: "hard" },
  { slug: "laika", name: "Laika", level: "hard" },

  // IMPOSSIBLE (17) — obscure even to film enthusiasts
  { slug: "rankin-bass-productions", name: "Rankin/Bass Productions", level: "impossible" },
  { slug: "embassy-pictures", name: "Embassy Pictures", level: "impossible" },
  { slug: "american-international-pictures", name: "American International Pictures", level: "impossible" },
  { slug: "filmation", name: "Filmation", level: "impossible" },
  { slug: "empire-international-pictures", name: "Empire International Pictures", level: "impossible" },
  { slug: "vestron-pictures", name: "Vestron Pictures", level: "impossible" },
  { slug: "new-world-pictures", name: "New World Pictures", level: "impossible" },
  { slug: "cinergi-pictures", name: "Cinergi Pictures", level: "impossible" },
  { slug: "morgan-creek-entertainment", name: "Morgan Creek Entertainment", level: "impossible" },
  { slug: "polygram-filmed-entertainment", name: "PolyGram Filmed Entertainment", level: "impossible" },
  { slug: "trimark-pictures", name: "Trimark Pictures", level: "impossible" },
  { slug: "full-moon-features", name: "Full Moon Features", level: "impossible" },
  { slug: "troma-entertainment", name: "Troma Entertainment", level: "impossible" },
  { slug: "the-weinstein-company", name: "The Weinstein Company", level: "impossible" },
  { slug: "rko-pictures", name: "RKO Pictures", level: "impossible" },
  { slug: "republic-pictures", name: "Republic Pictures", level: "impossible" },
  { slug: "monogram-pictures", name: "Monogram Pictures", level: "impossible" },
];
