// E37 "Guess the Instrument" — answer = instrument name, image = real photo of the instrument.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
export const MUSICAL_INSTRUMENTS_E37 = [
  // EASY (17) — globally familiar instruments
  { slug: "guitar", name: "Guitar", origin: "Spain", level: "easy" },
  { slug: "piano", name: "Piano", origin: "Italy", level: "easy" },
  { slug: "violin", name: "Violin", origin: "Italy", level: "easy" },
  { slug: "drum-kit", name: "Drum Kit", origin: "United States", level: "easy" },
  { slug: "flute", name: "Flute", origin: "Global", level: "easy" },
  { slug: "trumpet", name: "Trumpet", origin: "Global", level: "easy" },
  { slug: "saxophone", name: "Saxophone", origin: "Belgium", level: "easy" },
  { slug: "cello", name: "Cello", origin: "Italy", level: "easy" },
  { slug: "harmonica", name: "Harmonica", origin: "Germany", level: "easy" },
  { slug: "accordion", name: "Accordion", origin: "Austria", level: "easy" },
  { slug: "banjo", name: "Banjo", origin: "United States", level: "easy" },
  { slug: "trombone", name: "Trombone", origin: "Europe", level: "easy" },
  { slug: "clarinet", name: "Clarinet", origin: "Germany", level: "easy" },
  { slug: "bagpipes", name: "Bagpipes", origin: "Scotland", level: "easy" },
  { slug: "ukulele", name: "Ukulele", origin: "Hawaii", level: "easy" },
  { slug: "xylophone", name: "Xylophone", origin: "Southeast Asia", level: "easy" },
  { slug: "tambourine", name: "Tambourine", origin: "Global", level: "easy" },

  // MEDIUM (17)
  { slug: "harp", name: "Harp", origin: "Global", level: "medium" },
  { slug: "double-bass", name: "Double Bass", origin: "Italy", level: "medium" },
  { slug: "oboe", name: "Oboe", origin: "France", level: "medium" },
  { slug: "french-horn", name: "French Horn", origin: "Germany", level: "medium" },
  { slug: "tuba", name: "Tuba", origin: "Germany", level: "medium" },
  { slug: "mandolin", name: "Mandolin", origin: "Italy", level: "medium" },
  { slug: "sitar", name: "Sitar", origin: "India", level: "medium" },
  { slug: "bongo-drums", name: "Bongo Drums", origin: "Cuba", level: "medium" },
  { slug: "marimba", name: "Marimba", origin: "Central America", level: "medium" },
  { slug: "recorder", name: "Recorder", origin: "Europe", level: "medium" },
  { slug: "cajon", name: "Cajón", origin: "Peru", level: "medium" },
  { slug: "djembe", name: "Djembe", origin: "West Africa", level: "medium" },
  { slug: "bass-guitar", name: "Bass Guitar", origin: "United States", level: "medium" },
  { slug: "pipe-organ", name: "Pipe Organ", origin: "Europe", level: "medium" },
  { slug: "triangle", name: "Triangle", origin: "Global", level: "medium" },
  { slug: "castanets", name: "Castanets", origin: "Spain", level: "medium" },
  { slug: "maracas", name: "Maracas", origin: "Latin America", level: "medium" },

  // HARD (17)
  { slug: "bassoon", name: "Bassoon", origin: "Italy", level: "hard" },
  { slug: "viola", name: "Viola", origin: "Italy", level: "hard" },
  { slug: "piccolo", name: "Piccolo", origin: "Italy", level: "hard" },
  { slug: "bouzouki", name: "Bouzouki", origin: "Greece", level: "hard" },
  { slug: "kalimba", name: "Kalimba", origin: "South Africa", level: "hard" },
  { slug: "handpan", name: "Handpan", origin: "Switzerland", level: "hard" },
  { slug: "ocarina", name: "Ocarina", origin: "Italy", level: "hard" },
  { slug: "erhu", name: "Erhu", origin: "China", level: "hard" },
  { slug: "koto", name: "Koto", origin: "Japan", level: "hard" },
  { slug: "zither", name: "Zither", origin: "Central Europe", level: "hard" },
  { slug: "bandoneon", name: "Bandoneon", origin: "Germany", level: "hard" },
  { slug: "steel-pan", name: "Steel Pan", origin: "Trinidad and Tobago", level: "hard" },
  { slug: "theremin", name: "Theremin", origin: "Russia", level: "hard" },
  { slug: "balalaika", name: "Balalaika", origin: "Russia", level: "hard" },
  { slug: "dulcimer", name: "Dulcimer", origin: "United States", level: "hard" },
  { slug: "concertina", name: "Concertina", origin: "England", level: "hard" },
  { slug: "vibraphone", name: "Vibraphone", origin: "United States", level: "hard" },

  // IMPOSSIBLE (17)
  { slug: "shamisen", name: "Shamisen", origin: "Japan", level: "impossible" },
  { slug: "duduk", name: "Duduk", origin: "Armenia", level: "impossible" },
  { slug: "hurdy-gurdy", name: "Hurdy-gurdy", origin: "France", level: "impossible" },
  { slug: "nyckelharpa", name: "Nyckelharpa", origin: "Sweden", level: "impossible" },
  { slug: "sarod", name: "Sarod", origin: "India", level: "impossible" },
  { slug: "tabla", name: "Tabla", origin: "India", level: "impossible" },
  { slug: "rebab", name: "Rebab", origin: "Middle East", level: "impossible" },
  { slug: "oud", name: "Oud", origin: "Middle East", level: "impossible" },
  { slug: "guzheng", name: "Guzheng", origin: "China", level: "impossible" },
  { slug: "pipa", name: "Pipa", origin: "China", level: "impossible" },
  { slug: "cimbalom", name: "Cimbalom", origin: "Hungary", level: "impossible" },
  { slug: "charango", name: "Charango", origin: "Bolivia", level: "impossible" },
  { slug: "hulusi", name: "Hulusi", origin: "China", level: "impossible" },
  { slug: "yangqin", name: "Yangqin", origin: "China", level: "impossible" },
  { slug: "guqin", name: "Guqin", origin: "China", level: "impossible" },
  { slug: "sackbut", name: "Sackbut", origin: "Europe", level: "impossible" },
  { slug: "crumhorn", name: "Crumhorn", origin: "Germany", level: "impossible" },
];
