export const MUSICAL_INSTRUMENTS_E37_FACTS = {
  "guitar": "The modern guitar's six-string form emerged in 19th-century Spain.",
  "piano": "The piano was invented around 1700 by Bartolomeo Cristofori.",
  "violin": "Violin making peaked with Cremona's Italian luthiers.",
  "drum-kit": "The modern drum kit only came together in the early 20th century.",
  "flute": "The flute is among the oldest known musical instruments ever found.",
  "trumpet": "Ancient trumpets had no valves, which were added in the 1800s.",
  "saxophone": "The saxophone was invented in the 1840s by Adolphe Sax.",
  "cello": "The cello's full name, violoncello, means 'little big violin.'",
  "harmonica": "The harmonica was invented in Germany in the early 1820s.",
  "accordion": "The accordion was patented in Vienna in 1829.",
  "banjo": "The banjo descends from West African gourd instruments.",
  "trombone": "The trombone is one of the few brass instruments using a slide.",
  "clarinet": "The clarinet evolved from an earlier instrument called the chalumeau.",
  "bagpipes": "Bagpipes have folk traditions across Europe, not just Scotland.",
  "ukulele": "The ukulele was adapted in Hawaii from Portuguese instruments.",
  "xylophone": "Xylophone means 'wood sound' in Greek.",
  "tambourine": "Tambourines date back thousands of years across many cultures.",
  "harp": "Harps appear in ancient Egyptian and Mesopotamian artwork.",
  "double-bass": "The double bass is the largest and lowest instrument in an orchestra.",
  "oboe": "Orchestras traditionally tune to an oboe's A note.",
  "french-horn": "The French horn's coiled tubing can stretch over 12 feet unrolled.",
  "tuba": "The tuba is the largest and lowest brass instrument in an orchestra.",
  "mandolin": "The mandolin developed from earlier Italian lute instruments.",
  "sitar": "The sitar became globally known through Ravi Shankar's performances.",
  "bongo-drums": "Bongo drums originated in Cuba in the late 19th century.",
  "marimba": "The marimba has deep roots in Central American and African music.",
  "recorder": "The recorder was Europe's most popular flute during the Baroque era.",
  "cajon": "The cajón began as a wooden shipping crate turned into a drum.",
  "djembe": "The djembe is traditionally carved from a single piece of wood.",
  "bass-guitar": "The electric bass guitar was popularized by Fender in the 1950s.",
  "pipe-organ": "The largest pipe organs contain tens of thousands of pipes.",
  "triangle": "The triangle produces sound with no fixed, tunable pitch.",
  "castanets": "Castanets are closely associated with Spanish flamenco dance.",
  "maracas": "Maracas are traditionally made from dried hollow gourds.",
  "bassoon": "The bassoon's double reed sits atop a long folded wooden tube.",
  "viola": "The viola is tuned a fifth lower than the violin.",
  "piccolo": "The piccolo plays an octave higher than the standard flute.",
  "bouzouki": "The bouzouki is central to modern Greek folk and rebetiko music.",
  "kalimba": "The kalimba is a modern Western version of the African mbira.",
  "handpan": "The handpan was only invented in the early 2000s in Switzerland.",
  "ocarina": "Ocarinas have been made from clay for thousands of years.",
  "erhu": "The erhu is a two-stringed instrument played with a bow.",
  "koto": "The koto is Japan's national instrument, with thirteen strings.",
  "zither": "Zithers span many cultures, from Europe to East Asia.",
  "bandoneon": "The bandoneon became central to Argentine tango music.",
  "steel-pan": "The steel pan was invented in Trinidad from oil drums.",
  "theremin": "The theremin is played without ever touching the instrument.",
  "balalaika": "The balalaika has a distinctive triangular wooden body.",
  "dulcimer": "The mountain dulcimer is closely tied to Appalachian folk music.",
  "concertina": "The concertina is a close relative of the accordion.",
  "vibraphone": "The vibraphone uses a motor to create its signature vibrato.",
  "shamisen": "The shamisen is traditionally covered with cat or dog skin.",
  "duduk": "The duduk is carved from apricot wood for its warm tone.",
  "hurdy-gurdy": "The hurdy-gurdy makes sound with a hand-cranked wheel.",
  "nyckelharpa": "The nyckelharpa is Sweden's traditional keyed fiddle.",
  "sarod": "The sarod has no frets, allowing continuous sliding notes.",
  "tabla": "Tabla drums are tuned using a paste called syahi.",
  "rebab": "The rebab is an ancestor of many European bowed instruments.",
  "oud": "The oud is a fretless ancestor of the European lute.",
  "guzheng": "The guzheng is a Chinese zither with movable string bridges.",
  "pipa": "The pipa is a pear-shaped Chinese lute played with picks.",
  "cimbalom": "The cimbalom is played by striking strings with small hammers.",
  "charango": "The charango's body was traditionally made from an armadillo shell.",
  "hulusi": "The hulusi is a Chinese gourd flute with a distinctive buzzing tone.",
  "yangqin": "The yangqin is a Chinese hammered dulcimer with metal strings.",
  "guqin": "The guqin is one of China's oldest instruments, played for millennia.",
  "sackbut": "The sackbut is the Renaissance ancestor of the modern trombone.",
  "crumhorn": "The crumhorn's curved shape gives it a distinctive buzzing reed sound.",
};
