export const MYTHICAL_CREATURES_E83 = [
  // EASY (18) — near-universal, ~70-95% global recognition
  { slug: "dragon", name: "Dragon", wiki: "Dragon", level: "easy" },
  { slug: "unicorn", name: "Unicorn", wiki: "Unicorn", level: "easy" },
  { slug: "mermaid", name: "Mermaid", wiki: "Mermaid", level: "easy" },
  { slug: "phoenix", name: "Phoenix", wiki: "Phoenix (mythology)", level: "easy" },
  { slug: "werewolf", name: "Werewolf", wiki: "Werewolf", level: "easy" },
  { slug: "vampire", name: "Vampire", wiki: "Vampire", level: "easy" },
  { slug: "zombie", name: "Zombie", wiki: "Zombie", level: "easy" },
  { slug: "fairy", name: "Fairy", wiki: "Fairy", level: "easy" },
  { slug: "genie", name: "Genie", wiki: "Jinn", level: "easy" },
  { slug: "cyclops", name: "Cyclops", wiki: "Cyclops", level: "easy" },
  { slug: "griffin", name: "Griffin", wiki: "Griffin", level: "easy" },
  { slug: "centaur", name: "Centaur", wiki: "Centaur", level: "easy" },
  { slug: "leprechaun", name: "Leprechaun", wiki: "Leprechaun", level: "easy" },
  { slug: "medusa", name: "Medusa", wiki: "Medusa", level: "easy" },
  { slug: "minotaur", name: "Minotaur", wiki: "Minotaur", level: "easy" },
  { slug: "pegasus", name: "Pegasus", wiki: "Pegasus", level: "easy" },
  { slug: "kraken", name: "Kraken", wiki: "Kraken", level: "easy" },
  { slug: "ogre", name: "Ogre", wiki: "Ogre", level: "easy" },

  // MEDIUM (18) — most have seen it, ~35-70%
  { slug: "sphinx", name: "Sphinx", wiki: "Sphinx", level: "medium" },
  { slug: "yeti", name: "Yeti", wiki: "Yeti", level: "medium" },
  { slug: "bigfoot", name: "Bigfoot", wiki: "Bigfoot", level: "medium" },
  { slug: "loch-ness-monster", name: "Loch Ness Monster", wiki: "Loch Ness Monster", level: "medium" },
  { slug: "satyr", name: "Satyr", wiki: "Satyr", level: "medium" },
  { slug: "harpy", name: "Harpy", wiki: "Harpy", level: "medium" },
  { slug: "banshee", name: "Banshee", wiki: "Banshee", level: "medium" },
  { slug: "troll", name: "Troll", wiki: "Troll", level: "medium" },
  { slug: "golem", name: "Golem", wiki: "Golem", level: "medium" },
  { slug: "gargoyle", name: "Gargoyle", wiki: "Gargoyle", level: "medium" },
  { slug: "cerberus", name: "Cerberus", wiki: "Cerberus", level: "medium" },
  { slug: "hydra", name: "Hydra", wiki: "Lernaean Hydra", level: "medium" },
  { slug: "chimera", name: "Chimera", wiki: "Chimera (mythology)", level: "medium" },
  { slug: "basilisk", name: "Basilisk", wiki: "Basilisk", level: "medium" },
  { slug: "valkyrie", name: "Valkyrie", wiki: "Valkyrie", level: "medium" },
  { slug: "wyvern", name: "Wyvern", wiki: "Wyvern", level: "medium" },
  { slug: "fenrir", name: "Fenrir", wiki: "Fenrir", level: "medium" },
  { slug: "leviathan", name: "Leviathan", wiki: "Leviathan", level: "medium" },

  // HARD (16) — enthusiasts/well-read recognize, casual public often doesn't
  { slug: "manticore", name: "Manticore", wiki: "Manticore", level: "hard" },
  { slug: "kelpie", name: "Kelpie", wiki: "Kelpie", level: "hard" },
  { slug: "selkie", name: "Selkie", wiki: "Selkie", level: "hard" },
  { slug: "cockatrice", name: "Cockatrice", wiki: "Cockatrice", level: "hard" },
  { slug: "naga", name: "Naga", wiki: "Naga", level: "hard" },
  { slug: "kitsune", name: "Kitsune", wiki: "Kitsune", level: "hard" },
  { slug: "oni", name: "Oni", wiki: "Oni", level: "hard" },
  { slug: "anansi", name: "Anansi", wiki: "Anansi", level: "hard" },
  { slug: "jackalope", name: "Jackalope", wiki: "Jackalope", level: "hard" },
  { slug: "thunderbird", name: "Thunderbird", wiki: "Thunderbird (mythology)", level: "hard" },
  { slug: "roc", name: "Roc", wiki: "Roc (mythology)", level: "hard" },
  { slug: "alkonost", name: "Alkonost", wiki: "Alkonost", level: "hard" },
  { slug: "mothman", name: "Mothman", wiki: "Mothman", level: "hard" },
  { slug: "qilin", name: "Qilin", wiki: "Qilin", level: "hard" },
  { slug: "tarasque", name: "Tarasque", wiki: "Tarasque", level: "hard" },
  { slug: "jormungandr", name: "Jörmungandr", wiki: "Jörmungandr", level: "hard" },

  // IMPOSSIBLE (18) — genuinely obscure, regional folklore
  { slug: "barghest", name: "Barghest", wiki: "Barghest", level: "impossible" },
  { slug: "nuckelavee", name: "Nuckelavee", wiki: "Nuckelavee", level: "impossible" },
  { slug: "tikbalang", name: "Tikbalang", wiki: "Tikbalang", level: "impossible" },
  { slug: "aswang", name: "Aswang", wiki: "Aswang", level: "impossible" },
  { slug: "sleipnir", name: "Sleipnir", wiki: "Sleipnir", level: "impossible" },
  { slug: "baba-yaga", name: "Baba Yaga", wiki: "Baba Yaga", level: "impossible" },
  { slug: "peryton", name: "Peryton", wiki: "Peryton", level: "impossible" },
  { slug: "simurgh", name: "Simurgh", wiki: "Simurgh", level: "impossible" },
  { slug: "la-llorona", name: "La Llorona", wiki: "La Llorona", level: "impossible" },
  { slug: "kappa", name: "Kappa", wiki: "Kappa (folklore)", level: "impossible" },
  { slug: "black-shuck", name: "Black Shuck", wiki: "Black Shuck", level: "impossible" },
  { slug: "rusalka", name: "Rusalka", wiki: "Rusalka", level: "impossible" },
  { slug: "kongamato", name: "Kongamato", wiki: "Kongamato", level: "impossible" },
  { slug: "ammit", name: "Ammit", wiki: "Ammit", level: "impossible" },
  { slug: "baku", name: "Baku", wiki: "Baku (mythology)", level: "impossible" },
  { slug: "nian", name: "Nian", wiki: "Nian", level: "impossible" },
  { slug: "rakshasa", name: "Rakshasa", wiki: "Rakshasa", level: "impossible" },
  { slug: "ziz", name: "Ziz", wiki: "Ziz (giant bird)", level: "impossible" },
];

export default MYTHICAL_CREATURES_E83;
