export const MYTHICAL_CREATURES_E83_FACTS = {
  dragon: "Nearly every culture worldwide has its own dragon legend.",
  unicorn: "Its horn was once believed to detect and cure poison.",
  mermaid: "Sailors often mistook real manatees for mermaids.",
  phoenix: "It's said to burst into flame and rise from its own ashes.",
  werewolf: "A full moon is the classic, though not universal, trigger.",
  vampire: "The word 'vampire' entered English from Slavic folklore.",
  zombie: "The word traces back to the Kikongo word for 'spirit.'",
  fairy: "Old folklore fairies were often feared, not friendly.",
  genie: "Islamic tradition describes jinn as made of smokeless fire.",
  cyclops: "Homer's Odyssey gave the one-eyed giant its lasting fame.",
  griffin: "Ancient Greek and Persian art both depicted the griffin.",
  centaur: "In Greek myth, centaurs were born from a cloud, not a womb.",
  leprechaun: "Traditionally a solitary shoemaker, not a treasure hunter.",
  medusa: "A single glance from her could turn a person to stone.",
  minotaur: "It lived inside a maze built specifically to contain it.",
  pegasus: "It sprang from Medusa's blood when she was slain.",
  kraken: "Scandinavian sailors described it as large enough to sink ships.",
  ogre: "The word entered English through French fairy tales.",
  sphinx: "Egypt's version guards tombs; Greece's version asks riddles.",
  yeti: "Sherpas call it the 'Meh-Teh,' meaning man-bear.",
  bigfoot: "Reported sightings cluster in the Pacific Northwest.",
  "loch-ness-monster": "Its famous 1934 photo was later admitted to be a hoax.",
  satyr: "Roman writers merged it with their own faun.",
  harpy: "Early Greek harpies were wind spirits, not monsters.",
  banshee: "Her wail is said to warn a family of an approaching death.",
  troll: "Scandinavian trolls turn to stone in direct sunlight.",
  golem: "Prague's most famous golem was said to protect its Jewish quarter.",
  gargoyle: "Its open mouth was originally a rain spout, not decoration.",
  cerberus: "Hercules had to capture it alive as his final labor.",
  hydra: "Cutting off one head only made two more grow back.",
  chimera: "It breathed fire and had a lion, goat, and serpent in one body.",
  basilisk: "Legend claimed its gaze alone could kill instantly.",
  valkyrie: "They chose which fallen warriors would go to Valhalla.",
  wyvern: "Unlike a dragon, it has only two legs, not four.",
  fenrir: "Norse myth says he'll break free at the world's end.",
  leviathan: "The Bible describes it as an untamable sea monster.",
  manticore: "Persian legend gave it a scorpion's tail and a man's face.",
  kelpie: "It lures riders onto its back, then drags them underwater.",
  selkie: "In Celtic lore, it sheds its sealskin to become human.",
  cockatrice: "Hatched from a rooster's egg brooded by a serpent, says legend.",
  naga: "Worshipped across Hindu and Buddhist temples in Asia.",
  kitsune: "The more tails it grows, the older and wiser it becomes.",
  oni: "It's the fearsome ogre-demon of Japanese folklore.",
  anansi: "This trickster spider is credited with owning every story.",
  jackalope: "Likely inspired by rabbits with a real horn-causing virus.",
  thunderbird: "Its wingbeats were said to create thunder itself.",
  roc: "Sinbad the Sailor described one large enough to eat elephants.",
  alkonost: "This Slavic bird-woman's song is said to bring joy, not doom.",
  mothman: "First reported in Point Pleasant, West Virginia, in 1966.",
  qilin: "Its rare appearance was said to foretell a great sage's birth.",
  tarasque: "A French town still parades its effigy every summer.",
  jormungandr: "This world serpent is so huge it circles the entire earth.",
  barghest: "This ghostly black dog haunts northern English folklore.",
  nuckelavee: "Orkney legend says it has no skin at all.",
  tikbalang: "This horse-headed trickster is said to lead travelers astray.",
  aswang: "A shapeshifting ghoul from Philippine folklore.",
  sleipnir: "Odin's horse was said to have eight legs, not four.",
  "baba-yaga": "She's said to live in a hut that walks on chicken legs.",
  peryton: "This deer with bird wings supposedly casts a human shadow.",
  simurgh: "Persian myth says it witnessed the world's destruction three times.",
  "la-llorona": "This weeping ghost is said to search rivers for her children.",
  kappa: "This Japanese river spirit is said to love cucumbers.",
  "black-shuck": "This spectral dog is said to roam England's East Anglia.",
  rusalka: "In Slavic lore, she lures men into rivers and lakes.",
  kongamato: "This African cryptid is described as a giant flying reptile.",
  ammit: "Egyptian myth says she devoured hearts unworthy of paradise.",
  baku: "In Japanese folklore, it's said to eat bad dreams.",
  nian: "Loud noises and the color red are said to scare it off.",
  rakshasa: "Hindu epics describe it as a powerful shapeshifting demon.",
  ziz: "Jewish legend calls it a bird so big its wings block the sun.",
};

export default MYTHICAL_CREATURES_E83_FACTS;
