export const NATIONAL_PARKS_E57_FACTS = {
  // EASY
  "yellowstone": "America's first national park, founded in 1872.",
  "grand-canyon": "Carved by the Colorado River over six million years.",
  "yosemite": "Famous for its granite cliffs like El Capitan and Half Dome.",
  "serengeti": "Home to the Great Migration of over a million wildebeest.",
  "kruger": "One of Africa's largest game reserves, home to the Big Five.",
  "banff": "Canada's first national park, founded in 1885.",
  "zion": "Named for its towering red sandstone cliffs in Utah.",
  "torres-del-paine": "Famous for its three granite towers in Patagonia.",
  "plitvice-lakes": "Known for its cascading turquoise lakes and waterfalls.",
  "great-smoky-mountains": "The most visited national park in the United States.",
  "iguazu": "Home to one of the world's largest waterfall systems.",
  "fiordland": "New Zealand's largest park, famous for Milford Sound.",
  "jasper": "The largest national park in the Canadian Rockies.",
  "denali": "Home to North America's tallest peak, Denali.",
  "komodo": "The only place Komodo dragons live in the wild.",
  "galapagos": "Inspired Charles Darwin's theory of evolution.",
  "grand-teton": "Named for its jagged, glacier-carved mountain range.",
  "kilimanjaro": "Surrounds Africa's tallest mountain, a dormant volcano.",

  // MEDIUM
  "arches": "Home to over 2,000 natural sandstone arches in Utah.",
  "glacier": "Nicknamed the 'Crown of the Continent' in Montana.",
  "rocky-mountain": "Its Trail Ridge Road is the highest paved road in the US.",
  "everglades": "A vast subtropical wetland home to alligators and manatees.",
  "bryce-canyon": "Famous for its unique red rock spires called hoodoos.",
  "joshua-tree": "Named for its twisted, spiky desert trees.",
  "table-mountain": "Overlooks Cape Town from its flat-topped summit.",
  "amboseli": "Offers classic views of elephants beneath Kilimanjaro.",
  "etosha": "Centered on a vast salt pan visible from space.",
  "chapada-diamantina": "A former diamond-mining region full of canyons.",
  "sagarmatha": "Contains Mount Everest, the world's highest peak.",
  "los-glaciares": "Home to the advancing Perito Moreno Glacier.",
  "lake-district": "England's largest national park, inspiring poet Wordsworth.",
  "cinque-terre": "Protects Italy's five colorful cliffside fishing villages.",
  "tongariro": "New Zealand's oldest park, with three active volcanoes.",
  "canaima": "Home to Angel Falls, the world's tallest waterfall.",
  "sequoia": "Home to General Sherman, the largest tree by volume.",
  "olympic": "Contains rainforest, coastline, and glaciers in one park.",

  // HARD
  "torngat-mountains": "A remote, roadless park in northern Labrador, Canada.",
  "sarek": "A remote Swedish wilderness with no marked trails.",
  "durmitor": "Home to the deep Tara River Canyon in Montenegro.",
  "gunung-mulu": "Home to some of the world's largest cave chambers.",
  "khao-yai": "One of Thailand's oldest and largest national parks.",
  "los-haitises": "A coastal park of limestone karst domes called mogotes.",
  "hells-canyon": "North America's deepest river gorge, on the Snake River.",
  "gran-paradiso": "Italy's oldest national park, once a royal hunting ground.",
  "vatnajokull": "Named for Europe's largest ice cap, in Iceland.",
  "cradle-mountain": "A rugged Tasmanian park along the Overland Track.",
  "purnululu": "Home to the striped, beehive-shaped Bungle Bungle domes.",
  "waterton-lakes": "Forms a peace park joined with Montana's Glacier park.",
  "goreme": "Famous for its fairy chimney rock formations in Turkey.",
  "abisko": "A prime spot for viewing the Northern Lights in Sweden.",
  "kakadu": "Australia's largest park, rich in Aboriginal rock art.",
  "morne-trois-pitons": "A volcanic park home to Dominica's Boiling Lake.",
  "nahanni": "Home to Virginia Falls, twice as tall as Niagara.",
  "huascaran": "Surrounds Peru's highest peak in the Andes.",

  // IMPOSSIBLE
  "wood-buffalo": "Canada's largest national park, home to wild bison.",
  "gates-of-the-arctic": "A remote Alaskan park with no roads or trails.",
  "khangchendzonga": "Surrounds the world's third-highest mountain in India.",
  "simien-mountains": "Home to the rare gelada, Ethiopia's 'bleeding-heart' monkey.",
  "manu": "One of the most biodiverse protected areas on Earth.",
  "salonga": "Africa's largest rainforest reserve, reachable only by river.",
  "phong-nha-ke-bang": "Home to Hang Sơn Đoòng, the world's largest cave.",
  "ranomafana": "A Madagascar rainforest known for its lemurs.",
  "los-katios": "A remote Colombian park bordering the Darién Gap.",
  "doi-inthanon": "Surrounds Thailand's highest peak and its twin pagodas.",
  "el-yunque": "The only tropical rainforest in the US National Forest System.",
  "korup": "One of Africa's oldest rainforests, in Cameroon.",
  "virunga": "Africa's oldest national park, home to mountain gorillas.",
  "tsingy-de-bemaraha": "Named for its sharp limestone 'forest' of stone spires.",
  "rondane": "Norway's first national park, established in 1962.",
  "aggtelek": "Home to the vast Baradla Cave system in Hungary.",
};

export default NATIONAL_PARKS_E57_FACTS;
