export const NBA_E78_FACTS = {
  "los-angeles-lakers": "Won 17 NBA championships, second-most in league history.",
  "chicago-bulls": "Won six titles in the 1990s, all led by Michael Jordan.",
  "boston-celtics": "Has more NBA championships than any other franchise.",
  "golden-state-warriors": "Widely credited with popularizing today's three-point-heavy style.",
  "miami-heat": "Won three titles, including two led by LeBron James.",
  "brooklyn-nets": "Played as the New Jersey Nets before moving in 2012.",
  "toronto-raptors": "The only NBA team based outside the United States.",
  "new-york-knicks": "One of the NBA's original teams, founded in 1946.",
  "san-antonio-spurs": "Duncan led all five titles; Parker and Ginobili joined for four.",
  "houston-rockets": "Won back-to-back titles in the mid-1990s.",
  "dallas-mavericks": "Won its only title in 2011, led by Dirk Nowitzki.",
  "philadelphia-76ers": "Its name honors the year of the Declaration of Independence.",
  "phoenix-suns": "Has reached the Finals three times but never won a title.",
  "portland-trail-blazers": "Won its only championship back in 1977.",
  "memphis-grizzlies": "Moved from Vancouver to Memphis in 2001.",
  "oklahoma-city-thunder": "Was the Seattle SuperSonics before relocating in 2008.",
  "atlanta-hawks": "Has moved cities three times since its founding in 1946.",
  "charlotte-hornets": "The original Hornets left for New Orleans in 2002.",
  "cleveland-cavaliers": "Won its first title in 2016, ending a 52-year city drought.",
  "detroit-pistons": "Won back-to-back titles in 1989 and 1990.",
  "indiana-pacers": "Joined the NBA in 1976 after the ABA-NBA merger.",
  "milwaukee-bucks": "Won its first title in 50 years back in 2021.",
  "orlando-magic": "Has reached the Finals twice but never won a title.",
  "denver-nuggets": "Won its first NBA championship in 2023.",
  "minnesota-timberwolves": "Joined the NBA as an expansion team in 1989.",
  "new-orleans-pelicans": "Was the New Orleans Hornets before renaming in 2013.",
  "sacramento-kings": "One of the NBA's oldest franchises, dating back to 1923.",
  "utah-jazz": "Kept its name after moving from New Orleans, where jazz began.",
  "washington-wizards": "Was known as the Bullets before renaming in 1997.",
  "la-clippers": "Moved from Buffalo to San Diego, then to Los Angeles.",
};

export default NBA_E78_FACTS;
