export const NFL_E79_FACTS = {
  "dallas-cowboys": "Nicknamed 'America's Team' for its nationwide fan base.",
  "green-bay-packers": "Owned by its fans, not a single billionaire owner.",
  "pittsburgh-steelers": "Has won six Super Bowls, tied for the most of any team.",
  "san-francisco-49ers": "Named after prospectors from the 1849 California Gold Rush.",
  "las-vegas-raiders": "Moved from Oakland to Las Vegas in 2020.",
  "new-england-patriots": "Won six Super Bowls, all under coach Bill Belichick.",
  "miami-dolphins": "The only NFL team with a perfect undefeated season, in 1972.",
  "philadelphia-eagles": "Its name honors a New Deal-era eagle symbol from the 1930s.",
  "chicago-bears": "One of only two NFL teams dating back to the league's 1920 founding.",
  "denver-broncos": "Won back-to-back Super Bowls in the late 1990s.",
  "kansas-city-chiefs": "Named after the mayor who helped bring the team to the city.",
  "seattle-seahawks": "Its fans once held the world record for loudest stadium roar.",
  "baltimore-ravens": "Named for 'The Raven' by Poe, who is buried in the city.",
  "minnesota-vikings": "Has reached four Super Bowls but never won one.",
  "cincinnati-bengals": "Its tiger-stripe helmet design debuted in 1981.",
  "new-york-giants": "One of the NFL's oldest franchises, founded in 1925.",
  "buffalo-bills": "Reached four straight Super Bowls in the early 1990s, losing all four.",
  "cleveland-browns": "Its helmet has never had a logo, just plain orange.",
  "detroit-lions": "Hosts an NFL game every Thanksgiving, a tradition since 1934.",
  "tennessee-titans": "Was the Houston Oilers before relocating in 1997.",
  "indianapolis-colts": "Moved from Baltimore to Indianapolis overnight in 1984.",
  "los-angeles-rams": "Was the first NFL team to add a logo to its helmet.",
  "atlanta-falcons": "Joined the NFL as an expansion team in 1966.",
  "new-orleans-saints": "Its name nods to the city's 'When the Saints Go Marching In.'",
  "arizona-cardinals": "The NFL's oldest continuously run franchise, dating to 1898.",
  "carolina-panthers": "Joined the NFL as an expansion team in 1995.",
  "houston-texans": "The NFL's newest franchise, joining the league in 2002.",
  "jacksonville-jaguars": "Joined the NFL in 1995 alongside the Carolina Panthers.",
  "los-angeles-chargers": "Moved from San Diego back to Los Angeles in 2017.",
  "new-york-jets": "Won its only Super Bowl in 1969, led by Joe Namath.",
  "tampa-bay-buccaneers": "Lost its first 26 games ever, an NFL futility record.",
  "washington-commanders": "Adopted its current name and logo in 2022.",
};

export default NFL_E79_FACTS;
