export const NHL_E81_FACTS = {
  "toronto-maple-leafs": "Has won 13 Stanley Cups, second only to Montreal's 24.",
  "montreal-canadiens": "Has won more Stanley Cups than any other NHL franchise, 24.",
  "boston-bruins": "Is one of the NHL's six 'Original Six' teams, founded in 1924.",
  "new-york-rangers": "Was the first US-based NHL team to win the Cup, 1928.",
  "chicago-blackhawks": "Is one of the NHL's six 'Original Six' teams, founded in 1926.",
  "detroit-red-wings": "Its fans famously toss octopuses onto the ice during playoffs.",
  "pittsburgh-penguins": "Won back-to-back Stanley Cups in 2016 and 2017.",
  "edmonton-oilers": "Won five Stanley Cups from 1984 to 1990, four with Gretzky.",
  "tampa-bay-lightning": "Won back-to-back Stanley Cups in 2020 and 2021.",
  "vegas-golden-knights": "Reached the Stanley Cup Final in its very first season, 2018.",
  "washington-capitals": "Won its first Stanley Cup in 2018, led by Alex Ovechkin.",
  "colorado-avalanche": "Moved from Quebec City and won the Cup in its first Denver season.",
  "vancouver-canucks": "Has reached the Stanley Cup Final three times but never won it.",
  "philadelphia-flyers": "Was nicknamed the Broad Street Bullies for its physical 1970s style.",
  "los-angeles-kings": "Won its first Stanley Cup in 2012 as an eighth-seed underdog.",
  "st-louis-blues": "Won its first Stanley Cup in 2019 after last place in January.",
  "calgary-flames": "Won its only Stanley Cup in 1989, beating Montreal.",
  "dallas-stars": "Was the Minnesota North Stars before relocating in 1993.",
  "florida-panthers": "Won back-to-back Stanley Cups in 2024 and 2025.",
  "new-york-islanders": "Won four straight Stanley Cups from 1980 to 1983.",
  "san-jose-sharks": "Joined the NHL in 1991 as an expansion team.",
  "winnipeg-jets": "Was the original Atlanta Thrashers before moving north in 2011.",
  "carolina-hurricanes": "Was the Hartford Whalers before relocating in 1997.",
  "ottawa-senators": "Revived a historic name after the original club folded in 1934.",
  "new-jersey-devils": "Won three Stanley Cups in the 1990s and 2000s.",
  "minnesota-wild": "Joined the NHL in 2000 as an expansion team.",
  "nashville-predators": "Joined the NHL in 1998 as an expansion team.",
  "buffalo-sabres": "Has never won a Stanley Cup despite joining the NHL in 1970.",
  "columbus-blue-jackets": "Swept its way to its first-ever playoff series win in 2019.",
  "anaheim-ducks": "Was originally named after the Disney movie The Mighty Ducks.",
  "seattle-kraken": "Joined the NHL in 2021, named for a mythical sea monster.",
  "utah-mammoth": "Took its permanent name in 2025 after relocating from Arizona.",
};

export default NHL_E81_FACTS;
