export const NOKIA_E68_FACTS = {
  "nokia-105": "One of the best-selling phones ever, with over 200 million sold.",
  "nokia-6600": "One of Nokia's most popular early Symbian smartphones.",
  "nokia-8210": "Its swappable Xpress-on covers helped launch mobile customization.",
  "nokia-6310": "Beloved for battery life so long it became an office legend.",
  "nokia-8850": "Its sliding keypad cover was made from brushed aluminum alloy.",
  "nokia-5800-xpressmusic": "Nicknamed the 'Tube', it was Nokia's first S60 touchscreen phone.",
  "nokia-6700-classic": "Built with a stainless steel body for extra durability.",
  "nokia-lumia-920": "Featured PureView optical image stabilization, rare in 2012.",
  "nokia-lumia-1020": "Packed a 41-megapixel camera sensor, huge for a phone.",
  "nokia-8800": "Its body was precision-crafted from polished stainless steel.",
  "nokia-3510": "Successor to the 3310, with a monochrome screen and games.",
  "nokia-7650": "Nokia's first phone with a built-in camera.",
  "nokia-e63": "A budget QWERTY phone aimed at students and young professionals.",
  "nokia-6100": "One of the smallest and lightest Nokia phones of its time.",
  "nokia-3410": "Included a built-in antenna and Nokia's Xpress-on covers.",
  "nokia-6310i": "An updated 6310 with added tri-band support for global roaming.",
  "nokia-lumia-800": "Nokia's first Windows Phone, based on the N9's design.",
  "nokia-n70": "A Symbian smartphone with a fixed 2-megapixel camera.",

  "nokia-2610": "A simple, low-cost candybar phone popular in emerging markets.",
  "nokia-1208": "An ultra-basic phone designed for markets with limited budgets.",
  "nokia-asha-305": "Part of the Asha line, aimed at affordable touch-and-type phones.",
  "nokia-6210": "One of the first Nokia phones with WAP internet browsing.",
  "nokia-6510": "A slim business phone with a monochrome screen and infrared.",
  "nokia-6630": "One of the first 3G phones with a Symbian smartphone OS.",
  "nokia-7110": "Introduced Nokia's spring-loaded slide cover mechanism.",
  "nokia-8910": "A titanium-bodied phone marketed as part of Nokia's fashion line.",
  "nokia-3200": "Had a swappable Xpress-on cover with a perforated design.",
  "nokia-6220-classic": "Included a 5-megapixel camera with Carl Zeiss optics.",
  "nokia-n73": "Marketed as a 'multimedia computer' with a 3.2MP camera.",
  "nokia-n8": "Its 12-megapixel camera used a large sensor, rare on phones then.",
  "nokia-e72": "A business-focused QWERTY phone with a full metal body.",
  "nokia-6303-classic": "A slim candybar phone with a 3.2-megapixel camera.",
  "nokia-lumia-900": "Was AT&T's exclusive flagship Windows Phone in the US.",
  "nokia-lumia-520": "Became the best-selling Windows Phone model ever made.",
  "nokia-x6": "Marketed as a 'comes with music' phone with free downloads.",
  "nokia-1110": "One of the best-selling mobile phones in history.",

  "nokia-6131": "A slider phone that also came in a rare NFC-enabled version.",
  "nokia-7250": "Featured interchangeable front covers called 'Xpress-on'.",
  "nokia-9210-communicator": "Ran the Symbian-based EPOC OS with a flip-open keyboard.",
  "nokia-3300": "Aimed at teens, with an FM radio and MP3 playback.",
  "nokia-2100": "A simple, affordable candybar phone from the early 2000s.",
  "nokia-6260": "Its clamshell design revealed a full keypad when opened.",
  "nokia-6820": "A flip-open phone with a hidden QWERTY keyboard inside.",
  "nokia-7710": "Nokia's first touchscreen phone, announced in 2004.",
  "nokia-n80": "Had dual cameras and could stream video over 3G.",
  "nokia-n90": "Its swivel design let the screen rotate like a camcorder.",
  "nokia-n93": "Nokia's most camera-focused smartphone of the mid-2000s.",
  "nokia-e61": "Lacked a camera, a rare choice for a Nokia smartphone.",
  "nokia-n97": "Combined a touchscreen with a slide-out QWERTY keyboard.",
  "nokia-c6": "A cheaper N97 Mini spin-off with a slide-out QWERTY keyboard.",
  "nokia-c7": "Had a curved stainless steel unibody design.",
  "nokia-lumia-1520": "Nokia's first phablet, with a 6-inch full HD display.",

  "nokia-c3-00": "A budget QWERTY phone aimed at social-media-focused users.",
  "nokia-e5": "A business phone with a QWERTY keyboard and long battery life.",
  "nokia-x2-01": "A budget dual-SIM phone popular in developing markets.",
  "nokia-9110-communicator": "Its flip-open design revealed a small internal keyboard.",
  "nokia-asha-200": "Had dual physical keypads laid out for easy texting.",
  "nokia-7360": "Part of Nokia's 'L'Amour' fashion collection of phones.",
  "nokia-7370": "Its case was wrapped in a fabric-like textured finish.",
  "nokia-7600": "Had an unusual teardrop shape unlike any typical phone.",
  "nokia-7700": "Announced in 2003 but its planned launch was later cancelled.",
  "nokia-n91": "Nokia's only phone built with a hard disk drive for storage.",
  "nokia-e90-communicator": "Opened like a small laptop with a full keyboard inside.",
  "nokia-lumia-630": "Was one of the first phones to run Windows Phone 8.1.",
  "nokia-8-2017": "Marked Nokia's return to flagship phones after years away.",
  "nokia-9-pureview": "Used five rear cameras working together for extra detail.",
  "nokia-7-plus": "Co-designed with Zeiss for its dual rear camera lenses.",
  "nokia-6021": "A simple candybar phone with a basic built-in camera.",
  "nokia-e7": "Had a large tilting screen that hid a slide-out keyboard.",
  "nokia-2110i": "An early digital-era Nokia phone with a slide-out antenna.",
};

export default NOKIA_E68_FACTS;
