export const PAINTINGS_E49_FACTS = {
  // EASY
  "mona-lisa": "Leonardo never delivered it; he kept it until his death in 1519.",
  "the-starry-night": "Van Gogh painted it from memory inside an asylum, not from life.",
  "the-last-supper": "Painted directly on a monastery wall, not on canvas.",
  "the-scream": "Munch made four painted or pastel versions between 1893 and 1910.",
  "girl-with-a-pearl-earring": "Not a portrait of a real person; it's a 'tronie' character study.",
  "the-birth-of-venus": "Painted on canvas, unusual for its era of wood panels.",
  "american-gothic": "The models were Wood's sister and his dentist, not a couple.",
  "sunflowers": "Van Gogh painted this series to decorate a room for Gauguin's visit.",
  "the-great-wave-off-kanagawa": "Part of a series of views of Mount Fuji, seen tiny in back.",
  "whistlers-mother": "Whistler titled it 'Arrangement in Grey and Black No. 1'.",
  "las-meninas": "Velazquez painted himself into the scene, working at an easel.",
  "liberty-leading-the-people": "Marks France's 1830 July Revolution, not the 1789 one.",
  "the-creation-of-adam": "One of nine Genesis scenes on the Sistine Chapel ceiling.",
  "water-lilies": "Monet painted roughly 250 Water Lilies canvases in his garden.",
  "the-kiss": "Klimt covered the couple in real gold and silver leaf.",
  "impression-sunrise": "This painting's title gave the Impressionist movement its name.",
  "a-sunday-on-la-grande-jatte": "Made of tiny dots of pure color, a technique called pointillism.",
  "the-night-watch": "Its real title names a militia company, not a night scene.",

  // MEDIUM
  "the-garden-of-earthly-delights": "A triptych that folds shut like a book, with two outer wings.",
  "ophelia": "Millais painted the riverbank on site, the model later in his studio.",
  "the-arnolfini-portrait": "A convex mirror behind the couple reflects two more figures.",
  "luncheon-of-the-boating-party": "Renoir's future wife Aline sits lower left with a small dog.",
  "the-third-of-may-1808": "Depicts Spanish civilians executed by Napoleon's soldiers.",
  "saturn-devouring-his-son": "One of 14 'Black Paintings' Goya painted onto his own walls.",
  "the-hay-wain": "Shows a real spot on the River Stour that Constable knew well.",
  "wanderer-above-the-sea-of-fog": "The wanderer's face is never shown; he faces away from us.",
  "the-death-of-marat": "Painted hours after revolutionary Marat was stabbed in his bath.",
  "napoleon-crossing-the-alps": "David painted five versions of this same equestrian scene.",
  "the-blue-boy": "The sitter was likely a hardware merchant's son, Jonathan Buttall.",
  "lady-with-an-ermine": "The ermine may nod to the sitter's lover, Ludovico Sforza.",
  "hunters-in-the-snow": "Part of a series Bruegel painted showing months of the year.",
  "a-bar-at-the-folies-bergere": "The barmaid's mirror reflection defies real-world optics.",
  "olympia": "Shocked 1865 Paris for the model's bold, direct gaze at the viewer.",
  "the-sleeping-gypsy": "Rousseau never left France, yet painted this imagined desert scene.",
  "where-do-we-come-from": "Gauguin painted it in Tahiti before attempting suicide.",
  "cafe-terrace-at-night": "One of Van Gogh's first paintings using a starry night sky.",

  // HARD
  "the-school-of-athens": "Raphael gave Plato the face of his rival, Leonardo da Vinci.",
  "judith-slaying-holofernes": "Painted after Gentileschi survived a real 1612 assault trial.",
  "the-tower-of-babel": "Bruegel modeled the tower partly on Rome's Colosseum.",
  "the-anatomy-lesson-of-dr-tulp": "Shows a real public dissection of an executed criminal.",
  "venus-of-urbino": "Likely commissioned to mark a duke's wedding in Urbino.",
  "the-ambassadors": "Its warped skull only resolves when viewed from a sharp angle.",
  "massacre-of-the-innocents": "Painted soon after Rubens returned from years studying in Italy.",
  "the-death-of-socrates": "Socrates reaches for the hemlock cup while still mid-lecture.",
  "the-raft-of-the-medusa": "Based on a real 1816 shipwreck and its survivors' ordeal.",
  "the-oxbow": "Cole painted a tiny self-portrait sketching inside his own landscape.",
  "washington-crossing-the-delaware": "Painted in Germany; the river looks more like the Rhine.",
  "portrait-of-dr-gachet": "Van Gogh called Gachet as nervously ill as he was himself.",
  "the-third-class-carriage": "Daumier left it unfinished when he died in 1879.",
  "broadway-boogie-woogie": "Mondrian swapped his usual black grid lines for bright colors.",
  "composition-vii": "Kandinsky considered it the most complex work he ever painted.",
  "the-isle-of-the-dead": "Bocklin painted five versions of this scene between 1880-1886.",
  "the-jewish-bride": "The identity of the couple shown has never been confirmed.",
  "bacchus-and-ariadne": "Ariadne's pose echoes a figure on an ancient Roman sarcophagus.",

  // IMPOSSIBLE
  "the-death-of-general-wolfe": "West controversially dressed the figures in modern uniforms.",
  "watson-and-the-shark": "Depicts a real 1749 shark attack on a boy in Havana harbor.",
  "a-philosopher-lecturing-on-the-orrery": "An orrery is a mechanical model of the solar system.",
  "an-experiment-on-a-bird-in-the-air-pump": "Shows a real device testing if a vacuum kills a bird.",
  "marriage-a-la-mode-the-settlement": "First of six Hogarth panels satirizing an arranged marriage.",
  "the-tribute-money": "Among the earliest paintings to use true linear perspective.",
  "the-effects-of-good-government-in-the-city": "Part of Siena's town-hall murals on good versus bad rule.",
  "the-money-changer-and-his-wife": "A tiny convex mirror on the table reflects a hidden figure.",
  "the-straw-manikin": "Shows women tossing a straw dummy in a blanket, a folk game.",
  "boy-bitten-by-a-lizard": "Caravaggio may have used his own face for the startled boy.",
  "a-woman-bathing-in-a-stream": "The model was Hendrickje, Rembrandt's own companion.",
  "portrait-of-a-man-in-a-turban": "Widely believed to be Van Eyck's own self-portrait.",
  "the-blue-rigi": "One of Turner's 'sample studies' painted to test buyer interest.",
  "the-death-of-actaeon": "Left unfinished in Titian's studio at the time of his death.",
  "mrs-siddons-as-the-tragic-muse": "Reynolds signed his name on the trim of her painted robe.",
  "the-geographer": "Likely a pendant, paired with Vermeer's 'The Astronomer'.",
  "officer-and-laughing-girl": "Infrared scans show Vermeer reworked parts of this scene.",
  "woman-holding-a-balance": "The scale's pans are empty; she isn't weighing anything.",
};
