export const PALACES_E59_FACTS = {
  // EASY
  "buckingham-palace": "The London residence of the British monarch since 1837.",
  "palace-of-versailles": "Home to the dazzling Hall of Mirrors.",
  "forbidden-city": "Home to Chinese emperors for nearly 500 years.",
  "potala-palace": "Once the winter residence of the Dalai Lama.",
  "topkapi-palace": "Home to Ottoman sultans for nearly 400 years.",
  "alhambra": "A Moorish royal palace overlooking Granada, Spain.",
  "schonbrunn-palace": "The former summer residence of Austria's Habsburgs.",
  "peterhof-palace": "Nicknamed the 'Russian Versailles' for its fountains.",
  "winter-palace": "Now home to part of the Hermitage Museum.",
  "doges-palace": "The seat of Venice's ruling doge for centuries.",
  "royal-palace-madrid": "Europe's largest royal palace by floor area.",
  "catherine-palace": "Home to the famous, long-lost Amber Room.",
  "hampton-court-palace": "A former residence of King Henry VIII.",
  "elysee-palace": "The official residence of France's president.",
  "blenheim-palace": "The birthplace of Winston Churchill.",
  "pena-palace": "A colorful hilltop palace above Sintra, Portugal.",
  "amalienborg-palace": "Home to Denmark's royal family since 1794.",
  "royal-palace-caserta": "One of the largest palaces built in 18th-century Europe.",

  // MEDIUM
  "royal-palace-brussels": "The official palace of the King of the Belgians.",
  "royal-palace-oslo": "Built for a king who never lived to see it finished.",
  "royal-palace-stockholm": "One of the largest palaces still in royal use.",
  "drottningholm-palace": "The private residence of the Swedish royal family.",
  "het-loo-palace": "A former hunting lodge turned royal palace.",
  "sanssouci-palace": "Prussia's answer to the Palace of Versailles.",
  "nymphenburg-palace": "The birthplace of Bavaria's 'Mad King' Ludwig II.",
  "wurzburg-residence": "Its ceiling fresco is the world's largest.",
  "royal-palace-naples": "One of four royal palaces built for Naples' Bourbon kings.",
  "quirinal-palace": "Now the official residence of Italy's president.",
  "gyeongbokgung": "The main royal palace of Korea's Joseon dynasty.",
  "changdeokgung": "A UNESCO site famed for its secret rear garden.",
  "imperial-palace-tokyo": "Built on the site of the old Edo Castle.",
  "mysore-palace": "Lit by nearly 100,000 lightbulbs on special nights.",
  "city-palace-jaipur": "Still home to Jaipur's former royal family.",
  "hue-imperial-city": "The former seat of Vietnam's Nguyễn emperors.",
  "grand-palace-bangkok": "Home to Thailand's revered Emerald Buddha.",
  "malacanang-palace": "The official residence of the Philippine president.",

  // HARD
  "queluz-palace": "A pink rococo palace nicknamed Portugal's Versailles.",
  "royal-palace-turin": "A former seat of Italy's House of Savoy.",
  "rundale-palace": "Designed by the architect behind the Winter Palace.",
  "christiansborg-palace": "Houses Denmark's parliament, courts, and monarchy.",
  "royal-palace-phnom-penh": "Home to Cambodia's Silver Pagoda.",
  "royal-palace-luang-prabang": "Now a museum for Laos's former royal family.",
  "iolani-palace": "The only royal palace on United States soil.",
  "dolmabahce-palace": "Where Ottoman sultans replaced Topkapi as their home.",
  "beylerbeyi-palace": "A former Ottoman summer palace on the Bosphorus.",
  "princes-palace-monaco": "Home to Monaco's ruling Grimaldi family since 1297.",
  "grand-ducal-palace-luxembourg": "The official residence of Luxembourg's Grand Duke.",
  "royal-alcazar-seville": "Still used by Spain's royal family when in Seville.",
  "kadriorg-palace": "Built by Peter the Great for his wife Catherine.",
  "wilanow-palace": "One of the few Polish royal residences to survive WWII.",
  "esterhazy-palace": "Once home to composer Joseph Haydn's patrons.",
  "golestan-palace": "The oldest of Tehran's historic royal complexes.",
  "palace-of-fontainebleau": "Home to French royalty for over 700 years.",
  "royal-palace-milan": "A former seat of Milan's dukes and Austrian rulers.",

  // IMPOSSIBLE
  "jubilee-palace": "A former imperial palace in Addis Ababa, Ethiopia.",
  "narayanhity-palace": "The former royal palace of Nepal's monarchy.",
  "royal-palaces-abomey": "Earthen palaces of the historic Kingdom of Dahomey.",
  "royal-palace-fez": "Its golden doors are a landmark of the city.",
  "royal-palace-rabat": "The official residence of Morocco's king.",
  "al-alam-palace": "The ceremonial palace of Oman's sultan.",
  "murabba-palace": "A historic mud-brick palace in Riyadh.",
  "rova-antananarivo": "The former royal compound of Madagascar's monarchy.",
  "kraton-yogyakarta": "Still home to the Sultan of Yogyakarta today.",
  "mandalay-palace": "The last royal palace of the Burmese monarchy.",
  "bogd-khan-palace": "The former home of Mongolia's last king.",
  "dadiani-palace": "A former residence of Georgia's Dadiani princes.",
  "presidential-palace-vientiane": "Built as Laos's royal palace, finished after the monarchy fell.",
  "kings-palace-nyanza": "A reconstructed royal residence of Rwanda's kings.",
  "tirana-presidential-palace": "The official residence of Albania's president.",
  "istana-negara": "The official residence of Malaysia's king.",
};

export default PALACES_E59_FACTS;
