export const PASTA_SHAPES_E99_FACTS = {
  // EASY
  spaghetti: "Spaghetti comes from the Italian word 'spago,' meaning string or twine — literally describing its long, thin shape.",
  macaroni: "The 'Macaroni' in Yankee Doodle's cap wasn't pasta — it mocked 1700s dandies obsessed with fashionable Continental food and style.",
  penne: "Penne means 'quills' or 'pens' in Italian, named for its diagonally cut ends that resemble the nib of an old dip pen.",
  ravioli: "Ravioli's name may come from the Italian 'riavvolgere' (to wrap), or from 'rava,' a turnip once used in its earliest fillings.",
  lasagna: "Some historians trace 'lasagna' back to the ancient Greek 'laganon,' a flatbread cut into strips that may be the earliest pasta on record.",
  fettuccine: "Fettuccine means 'little ribbons,' and Fettuccine Alfredo was invented in Rome to tempt a new mother's appetite after childbirth.",
  linguine: "Linguine means 'little tongues' in Italian — a flattened cousin of spaghetti traditionally paired with seafood in Liguria.",
  rigatoni: "Rigatoni takes its name from 'rigato,' meaning ridged or lined, describing the grooves that help sauce cling to every tube.",
  tortellini: "Legend says a Bolognese innkeeper peeked through a keyhole at the goddess Venus's navel and modeled tortellini after what he saw.",
  gnocchi: "Gnocchi likely comes from 'nocchio,' an Italian word for a knot in wood, describing its small, knuckle-shaped dumpling form.",
  vermicelli: "Vermicelli literally means 'little worms' in Italian, describing the long, thin strands of this classic dried pasta.",
  cannelloni: "Cannelloni means 'large reeds' in Italian, describing the wide, hollow tubes made specifically for stuffing with filling.",
  tagliatelle: "Legend says tagliatelle's thin ribbons were inspired by the golden hair of a Renaissance bride, Lucrezia Borgia, on her wedding day.",
  "angel-hair-pasta": "Angel hair pasta, called 'capelli d'angelo' in Italian, is so thin it's traditionally boiled for barely two minutes.",
  manicotti: "Manicotti means 'little sleeves' in Italian, describing the wide tubes designed to be stuffed with cheese and baked in sauce.",
  conchiglie: "Conchiglie means 'seashells' in Italian, its ridged curves designed specifically to cup chunky sauce inside each shell.",
  orzo: "Despite looking like rice, orzo is true wheat pasta — its name actually means 'barley' in Italian, describing its small grain shape.",
  ziti: "Ziti's name may come from 'zita,' an old Italian word for bride, since the pasta was traditionally served at southern Italian wedding feasts.",

  // MEDIUM
  farfalle: "Farfalle means 'butterflies' in Italian, formed by pinching small squares of dough at the center into their signature bow-tie shape.",
  fusilli: "Fusilli takes its name from 'fuso,' the spindle once used by hand to twist strands of dough into its corkscrew shape.",
  orecchiette: "Orecchiette means 'little ears' in Italian, hand-shaped in Puglia by dragging a knife through dough and flipping it with a thumb.",
  bucatini: "Bucatini means 'little holes,' and its hollow center comes from being extruded around a thin rod that's pulled out before drying.",
  cavatappi: "Cavatappi means 'corkscrew' in Italian, and Barilla once sold this exact shape under the trademarked name 'Cellentani.'",
  pappardelle: "Pappardelle's name comes from the Italian verb 'pappare,' meaning to gobble up — fitting for Tuscany's widest ribbon pasta.",
  rotelle: "Rotelle means 'small wheels' in Italian, its spoked wagon-wheel design built to trap chunky sauce inside every gap.",
  "alphabet-pasta": "Alphabet pasta has been documented since at least 1877, when Parisian grocers first stocked tiny letter-shaped noodles for soup.",
  gemelli: "Gemelli means 'twins' in Italian, but it isn't two strands twisted together at all — it's one S-shaped strand coiled into a spiral.",
  campanelle: "Campanelle means 'little bells' in Italian, its ruffled, cone-like shape designed to trap chunky sauce inside the flared edge.",
  ditalini: "Ditalini means 'little thimbles' in Italian, a tiny tube pasta traditionally simmered in soups like pasta e fagioli.",
  mafaldine: "Mafaldine's wavy ribbon shape was named in 1902 to honor the newborn Princess Mafalda of Savoy.",
  casarecce: "Casarecce means 'homemade' in Italian, its short scrolled twist traditionally rolled by hand around a thin knitting needle.",
  agnolotti: "Agnolotti, a stuffed pasta from Piedmont, was traditionally made by farmhands to use up leftover roasted meat from Sunday dinner.",
  radiatori: "Radiatori's radiator-like ridges are said to date to between the World Wars, though its exact origin is disputed.",
  stelline: "Stelline means 'little stars' in Italian, a tiny pasta shape that has been feeding kids in soup since at least the 19th century.",
  "israeli-couscous": "Israeli couscous was invented in 1953 as a rice substitute during a food shortage, at the request of Prime Minister David Ben-Gurion.",
  lanterne: "Lanterne means 'oil lanterns' in Italian, its curved, deeply ridged shape built to trap thick, chunky sauces inside.",

  // HARD
  strozzapreti: "Strozzapreti means 'priest choker' in Italian — legend blames either greedy priests gobbling it too fast or exhausted housewives twisting it.",
  trofie: "Trofie, a tightly twisted little pasta from Liguria, is the traditional partner for pesto and is believed to have originated in the town of Sori.",
  cavatelli: "Cavatelli comes from 'cavare,' meaning 'to hollow out,' describing how each little shell is pressed and curled by hand.",
  garganelli: "Garganelli is rolled one piece at a time by hand over a ridged wooden comb, which is what gives each one its grooved lines.",
  paccheri: "Paccheri gets its name from Neapolitan slang for a slap, supposedly describing the sound this giant tube pasta makes while eaten.",
  tagliolini: "Tagliolini is cut even thinner than tagliatelle and is the traditional pasta served with prized white truffles in Piedmont.",
  anelli: "Anelli means 'rings' in Italian, and in Sicily these little loops are baked into timballo, a festive molded pasta pie.",
  tortiglioni: "Tortiglioni takes its name from the Latin word for 'twist,' referring to the spiral grooves wrapping around this larger cousin of rigatoni.",
  malloreddus: "Malloreddus's name may come from 'malloru,' Sardinian for bull, making these little shell shapes' name loosely mean 'little calves.'",
  "acini-di-pepe": "Acini di pepe means 'peppercorns' in Italian, and this pinhead-sized pasta is added to Italian wedding soup as a symbol of fertility.",
  busiate: "Busiate is twisted around a 'busa,' a thin reed-like stalk from a local grass, which is how this Sicilian pasta got its name.",
  bigoli: "Bigoli, a thick Venetian noodle, is named after the 'bigolaro,' the bronze extrusion press a local pasta maker patented back in 1604.",
  passatelli: "Passatelli isn't made from flour at all — it's pressed from a dough of breadcrumbs, egg, and Parmesan straight into boiling broth.",
  sedani: "Sedani pasta was originally called 'elephant tusks,' but was renamed after celery once the ivory trade was banned.",
  calamarata: "Calamarata is often dyed black with squid ink specifically so its thick rings resemble sliced calamari, the seafood it's named after.",
  cascatelli: "Cascatelli is one of the only pasta shapes invented this century — a podcaster co-designed it in 2021 to be easier to scoop onto a fork.",

  // IMPOSSIBLE
  corzetti: "Corzetti are stamped with hand-carved wooden dies bearing family crests, a Ligurian tradition once used to show off a household's wealth.",
  pizzoccheri: "Pizzoccheri is made partly from buckwheat, not wheat, and has carried protected EU status as a Valtellina specialty since 2016.",
  fregula: "Fregula is rolled into tiny balls and then toasted in an oven, giving Sardinia's answer to couscous its distinctive nutty flavor.",
  testaroli: "Testaroli may be Italy's oldest pasta, cooked on a hot terracotta disc since Etruscan times, long before anyone thought to boil dough.",
  culurgiones: "Culurgiones, Sardinian stuffed dumplings, are hand-pinched into an intricate wheat-ear pattern treated almost like a folk art.",
  lorighittas: "Lorighittas are hand-braided from two twisted strands of dough into a ring, a technique traditionally known in just one Sardinian village.",
  scialatielli: "Scialatielli is one of Italy's newest traditional pastas — an Amalfi Coast chef invented it in the late 1960s to pair with seafood.",
  maltagliati: "Maltagliati means 'badly cut' in Italian, since it's traditionally made from irregular dough scraps left over from other pasta shapes.",
  casoncelli: "Casoncelli, a stuffed pasta from Lombardy, is traditionally tossed with butter, sage, and crisped pancetta.",
  fileja: "Fileja is rolled by hand around a thin cane called a 'dinaciulu,' a technique specific to Calabria's Vibo Valentia province.",
  filindeu: "Filindeu's name means 'threads of God,' and it's so difficult to hand-pull that only a handful of people worldwide still know how.",
  casunziei: "Casunziei, half-moon ravioli from Cortina d'Ampezzo, come in a 'red' beet-and-potato version for winter and a 'green' spinach one for summer.",
  fagottini: "Fagottini means 'little bundles' in Italian, made by folding pasta squares like a gift-wrapped parcel around a vegetable filling.",
  "foglie-d-ulivo": "Foglie d'ulivo means 'olive leaves' in Italian, hand-shaped to mimic the leaves of the trees that define its home regions.",
  sagnarelli: "Sagnarelli is a fluted ribbon pasta from Abruzzo, a wider cousin of the ancient hand-cut shape called sagne.",
  cencioni: "Cencioni means 'little rags' in Italian, its petal-like curve made rougher and grippier than its cousin, orecchiette.",
  "spoja-lorda": "Spoja lorda literally means 'dirty dough sheet' in dialect, describing how thinly its cheese filling is spread before sealing.",
  farfel: "Farfel, a pellet-shaped pasta from Ashkenazi Jewish cuisine, gets a special Passover version made by simply breaking matzah into pieces.",
};
