export const PASTA_SHAPES_E99 = [
  // ===== EASY (18) =====
  { slug: "spaghetti", name: "Spaghetti", level: "easy", wiki: "Spaghetti" },
  { slug: "macaroni", name: "Macaroni", level: "easy", wiki: "Macaroni" },
  { slug: "penne", name: "Penne", level: "easy", wiki: "Penne" },
  { slug: "ravioli", name: "Ravioli", level: "easy", wiki: "Ravioli" },
  { slug: "lasagna", name: "Lasagna", level: "easy", wiki: "Lasagna" },
  { slug: "fettuccine", name: "Fettuccine", level: "easy", wiki: "Fettuccine" },
  { slug: "linguine", name: "Linguine", level: "easy", wiki: "Linguine" },
  { slug: "rigatoni", name: "Rigatoni", level: "easy", wiki: "Rigatoni" },
  { slug: "tortellini", name: "Tortellini", level: "easy", wiki: "Tortellini" },
  { slug: "gnocchi", name: "Gnocchi", level: "easy", wiki: "Gnocchi" },
  { slug: "vermicelli", name: "Vermicelli", level: "easy", wiki: "Vermicelli" },
  { slug: "cannelloni", name: "Cannelloni", level: "easy", wiki: "Cannelloni" },
  { slug: "tagliatelle", name: "Tagliatelle", level: "easy", wiki: "Tagliatelle" },
  { slug: "angel-hair-pasta", name: "Angel Hair Pasta", level: "easy", wiki: "Capellini" },
  { slug: "manicotti", name: "Manicotti", level: "easy", wiki: "Manicotti" },
  { slug: "conchiglie", name: "Conchiglie", level: "easy", wiki: "Conchiglie" },
  { slug: "orzo", name: "Orzo", level: "easy", wiki: "Orzo" },
  { slug: "ziti", name: "Ziti", level: "easy", wiki: "Ziti" },

  // ===== MEDIUM (18) =====
  { slug: "farfalle", name: "Farfalle", level: "medium", wiki: "Farfalle" },
  { slug: "fusilli", name: "Fusilli", level: "medium", wiki: "Fusilli" },
  { slug: "orecchiette", name: "Orecchiette", level: "medium", wiki: "Orecchiette" },
  { slug: "bucatini", name: "Bucatini", level: "medium", wiki: "Bucatini" },
  { slug: "cavatappi", name: "Cavatappi", level: "medium", wiki: "Cavatappi" },
  { slug: "pappardelle", name: "Pappardelle", level: "medium", wiki: "Pappardelle" },
  { slug: "rotelle", name: "Rotelle", level: "medium", wiki: "Rotelle" },
  { slug: "alphabet-pasta", name: "Alphabet Pasta", level: "medium", wiki: "Alphabet pasta" },
  { slug: "gemelli", name: "Gemelli", level: "medium", wiki: "Gemelli pasta" },
  { slug: "campanelle", name: "Campanelle", level: "medium", wiki: "Campanelle" },
  { slug: "ditalini", name: "Ditalini", level: "medium", wiki: "Ditalini" },
  { slug: "mafaldine", name: "Mafaldine", level: "medium", wiki: "Mafaldine" },
  { slug: "casarecce", name: "Casarecce", level: "medium", wiki: "Casarecce" },
  { slug: "agnolotti", name: "Agnolotti", level: "medium", wiki: "Agnolotti" },
  { slug: "radiatori", name: "Radiatori", level: "medium", wiki: "Radiatori" },
  { slug: "stelline", name: "Stelline", level: "medium", wiki: "Stelline" },
  { slug: "israeli-couscous", name: "Israeli Couscous", level: "medium", wiki: "Israeli couscous" },
  { slug: "lanterne", name: "Lanterne", level: "medium", wiki: "Lanterne (pasta)" },

  // ===== HARD (16) =====
  { slug: "strozzapreti", name: "Strozzapreti", level: "hard", wiki: "Strozzapreti" },
  { slug: "trofie", name: "Trofie", level: "hard", wiki: "Trofie" },
  { slug: "cavatelli", name: "Cavatelli", level: "hard", wiki: "Cavatelli" },
  { slug: "garganelli", name: "Garganelli", level: "hard", wiki: "Garganelli" },
  { slug: "paccheri", name: "Paccheri", level: "hard", wiki: "Paccheri" },
  { slug: "tagliolini", name: "Tagliolini", level: "hard", wiki: "Tagliolini" },
  { slug: "anelli", name: "Anelli", level: "hard", wiki: "Anelli" },
  { slug: "tortiglioni", name: "Tortiglioni", level: "hard", wiki: "Tortiglioni" },
  { slug: "malloreddus", name: "Malloreddus", level: "hard", wiki: "Malloreddus" },
  { slug: "acini-di-pepe", name: "Acini di Pepe", level: "hard", wiki: "Acini di pepe" },
  { slug: "busiate", name: "Busiate", level: "hard", wiki: "Busiate" },
  { slug: "bigoli", name: "Bigoli", level: "hard", wiki: "Bigoli" },
  { slug: "passatelli", name: "Passatelli", level: "hard", wiki: "Passatelli" },
  { slug: "sedani", name: "Sedani", level: "hard", wiki: "Sedani" },
  { slug: "calamarata", name: "Calamarata", level: "hard", wiki: "Calamarata" },
  { slug: "cascatelli", name: "Cascatelli", level: "hard", wiki: "Cascatelli" },

  // ===== IMPOSSIBLE (18) =====
  { slug: "corzetti", name: "Corzetti", level: "impossible", wiki: "Corzetti" },
  { slug: "pizzoccheri", name: "Pizzoccheri", level: "impossible", wiki: "Pizzoccheri" },
  { slug: "fregula", name: "Fregula", level: "impossible", wiki: "Fregula" },
  { slug: "testaroli", name: "Testaroli", level: "impossible", wiki: "Testaroli" },
  { slug: "culurgiones", name: "Culurgiones", level: "impossible", wiki: "Culurgiones" },
  { slug: "lorighittas", name: "Lorighittas", level: "impossible", wiki: "Lorighittas" },
  { slug: "scialatielli", name: "Scialatielli", level: "impossible", wiki: "Scialatielli" },
  { slug: "maltagliati", name: "Maltagliati", level: "impossible", wiki: "Maltagliati" },
  { slug: "casoncelli", name: "Casoncelli", level: "impossible", wiki: "Casoncelli" },
  { slug: "fileja", name: "Fileja", level: "impossible", wiki: "Fileja" },
  { slug: "filindeu", name: "Filindeu", level: "impossible", wiki: "Filindeu" },
  { slug: "casunziei", name: "Casunziei", level: "impossible", wiki: "Casunziei" },
  { slug: "fagottini", name: "Fagottini", level: "impossible", wiki: "Fagottini" },
  { slug: "foglie-d-ulivo", name: "Foglie d'Ulivo", level: "impossible", wiki: "Foglie d'ulivo" },
  { slug: "sagnarelli", name: "Sagnarelli", level: "impossible", wiki: "Sagnarelli" },
  { slug: "cencioni", name: "Cencioni", level: "impossible", wiki: "Cencioni" },
  { slug: "spoja-lorda", name: "Spoja Lorda", level: "impossible", wiki: "Spoja lorda" },
  { slug: "farfel", name: "Farfel", level: "impossible", wiki: "Farfel" },
];
