export const PHONE_LOGOS_E67_FACTS = {
  "blackberry": "Company was named Research In Motion until rebranding in 2013.",
  "htc": "Once built phones for Google and Microsoft as an OEM.",
  "philips": "Its shield-and-stars logo dates back to 1938.",
  "ericsson": "Founded in Stockholm in 1876 by Lars Magnus Ericsson.",
  "toshiba": "Made early laptops and, briefly, its own mobile phones.",
  "casio": "Best known for calculators and G-Shock, also made rugged phones.",
  "palm": "Its PalmPilot popularized the PDA before smartphones existed.",
  "caterpillar": "Rugged 'Cat' phones are made under license by the UK's Bullitt Group.",
  "alcatel": "French phone brand now owned and licensed by China's TCL.",
  "sharp": "Company took its name from its 'Ever-Sharp' mechanical pencil.",
  "realme": "Spun off from Oppo/BBK Electronics in 2018.",
  "nec": "Was a major maker of early Japanese mobile handsets.",
  "kyocera": "Absorbed Sanyo's mobile phone business in 2008.",
  "honor": "Spun off from Huawei as an independent company in 2020.",
  "zte": "Ranked among the world's top-5 phone makers around 2012.",
  "tcl": "Sells phones under its own name and the Alcatel brand.",
  "benq": "Briefly merged with Siemens Mobile as BenQ-Siemens.",
  "meizu": "Early Chinese smartphone maker once compared closely to Apple.",
  "sanyo": "Its phone division was absorbed by Kyocera in 2008.",
  "micromax": "Once topped India's phone shipments ahead of Samsung, per Canalys.",
  "redmi": "Xiaomi's budget sub-brand, spun off separately in 2019.",
  "fairphone": "Dutch brand that designs modular, repairable phones.",
  "jio": "Its near-free JioPhone helped drive India's 4G boom.",
  "coolpad": "Was once part-owned by LeEco before LeEco's collapse.",
  "gionee": "Chinese brand that filed for bankruptcy restructuring in 2019.",
  "infinix": "Owned by Transsion; a top-selling brand across Africa.",
  "tecno": "Transsion's flagship brand, dominant in African markets.",
  "vertu": "Made ultra-luxury phones once priced well over $10,000.",
  "karbonn": "Indian budget-phone brand launched in 2009.",
  "itel": "Transsion's entry-level brand for price-sensitive markets.",
  "blu-products": "Miami-based brand selling budget Android phones in the US.",
  "archos": "French firm better known for early MP3 players and tablets.",
  "qmobile": "Long the top-selling phone brand in Pakistan.",
  "crosscall": "French maker of rugged, outdoor-focused smartphones.",
  "doogee": "Chinese brand known for huge-battery rugged phones.",
  "ulefone": "Chinese brand focused on rugged, outdoor-ready phones.",
  "umidigi": "Chinese budget brand known for big-battery 'flagship killers'.",
  "jolla": "Finnish startup founded by former Nokia MeeGo engineers.",
  "bq": "Spanish brand that made some of Google's first Android One phones.",
  "purism": "Makes the privacy-focused Librem 5 Linux phone.",
};

export default PHONE_LOGOS_E67_FACTS;