export const PHONES_E65_FACTS = {
  "apple-iphone-2007": "Announced by Steve Jobs Jan 9 2007; had no App Store until mid-2008.",
  "nokia-3310": "Became an internet meme for being nearly indestructible.",
  "motorola-razr-v3": "Ultra-thin metal clamshell that sold over 130 million units.",
  "motorola-dynatac-8000x": "First commercially available handheld mobile phone, weighed 2.5 lbs.",
  "apple-iphone-4": "First iPhone with a front camera; its steel band caused \"Antennagate.\"",
  "samsung-galaxy-fold": "Samsung's first foldable phone; unfolds into a small tablet.",
  "motorola-startac": "First clamshell phone sized like a pager; launched near $1,000.",
  "nokia-8110": "Curved sliding cover earned it \"the banana phone\"; seen in The Matrix.",
  "samsung-galaxy-s-iii": "One of the best-selling Android phones ever, 70M+ units sold.",
  "danger-t-mobile-sidekick": "Screen flipped and rotated to reveal a hidden keyboard underneath.",
  "nokia-n95": "Dual-slide design; first Nokia phone with built-in GPS.",
  "samsung-galaxy-note-2011": "Widely credited with creating the modern \"phablet\" category.",
  "lg-chocolate-kg800": "Touch-sensitive slider with a red glow that sold 20M+ units.",
  "nokia-3210": "First Nokia phone sold with an internal, not external, antenna.",
  "htc-dream-t-mobile-g1": "First commercially released Android phone, launched Oct 2008.",
  "nokia-n-gage": "Combined phone and game console; mocked as a \"taco\" when calling.",
  "nokia-5110": "Popularized colorful, swappable Xpress-On front covers.",
  "blackberry-bold-9000": "First BlackBerry combining WiFi, 3G and GPS in one device.",
  "samsung-galaxy-s-2010": "Samsung's first Galaxy S flagship, launching its dominant phone line.",
  "nokia-6110": "First Nokia phone to ship with the game Snake built in.",
  "blackberry-pearl-8100": "First BlackBerry with a camera; navigated with a trackball.",
  "nokia-1100": "Best-selling mobile phone in history, over 250 million sold.",
  "sony-ericsson-t610": "Breakthrough model combining camera, Bluetooth and a color screen.",
  "sony-ericsson-w800": "First phone to carry the Walkman music-player branding.",
  "google-pixel-2016": "Google's first in-house-designed phone, replacing the Nexus line.",
  "nokia-e71": "Slim QWERTY business phone often called a Nokia \"cult classic.\"",
  "ericsson-t28s": "Update to the T28, remarkably thin with a lithium-polymer battery.",
  "htc-one-m7": "Aluminum unibody praised as among the best-built phones of 2013.",
  "huawei-p20-pro": "First smartphone with a triple rear camera system.",
  "google-nexus-one": "Google's first self-branded phone, built with HTC and sold unlocked.",
  "palm-treo-650": "Early PDA-phone hybrid running Palm OS with a physical keyboard.",
  "blackberry-storm": "Touchscreen physically \"clicked\" down via SurePress technology.",
  "palm-pre": "Debuted webOS with a slide-out keyboard; Palm's last major phone.",
  "sony-xperia-z": "Among the first mainstream phones that was fully waterproof.",
  "oneplus-one": "Debut phone marketed as a \"flagship killer,\" invite-only to buy.",
  "nokia-2110": "Introduced the iconic \"Nokia Tune\" ringtone to the world.",
  "oneplus-7-pro": "Selfie camera mechanically pops up from inside the phone's body.",
  "lg-prada-ke850": "Co-designed with Prada; beat the iPhone to market by months.",
  "sony-ericsson-p900": "Flip-cover touchscreen smartphone on the Symbian UIQ platform.",
  "blackberry-passport": "Square screen deliberately sized to match a real passport booklet.",
  "nokia-3650": "Unique circular keypad inspired by a rotary telephone dial.",
  "htc-touch-diamond": "Faceted, diamond-cut rear panel on a Windows Mobile handset.",
  "sony-ericsson-xperia-x1": "First Xperia-branded phone; slide-out QWERTY on an arc hinge.",
  "ericsson-r380s": "First device its own maker ever marketed as a \"smartphone.\"",
  "xiaomi-mi-1": "Xiaomi's first phone, marking its jump from software into hardware.",
  "sony-ericsson-xperia-play": "Slide-out gamepad earned it the nickname \"PlayStation Phone.\"",
  "nokia-n9": "Nokia's only MeeGo phone; pioneered swipe gestures, no home button.",
  "amazon-fire-phone": "Amazon's only phone; four front cameras made a 3D \"Dynamic\" effect.",
  "lg-g-flex": "Curved phone with a self-healing back cover for small scratches.",
  "motorola-rokr-e1": "First phone with iTunes built in, but capped at 100 songs.",
  "lg-env-vx9900": "Flip phone opened sideways to reveal a full QWERTY keyboard.",
  "htc-touch": "HTC's first touch-focused phone, debuting the TouchFLO interface.",
  "huawei-ascend-mate": "Huawei's first Mate-series phone, with a then-huge 6.1-inch screen.",
  "zte-blade-v880": "Budget Android phone that sold over 8 million units in 50+ countries.",
  "motorola-v70": "Circular flip design where the keypad rotates open sideways.",
  "palm-centro": "One of the last Palm OS phones; launched at just $99.",
  "nokia-asha-501": "Budget touch phone aimed at first-time buyers in emerging markets.",
  "siemens-s55": "Offered an optional clip-on camera before cameras were standard.",
  "motorola-i860": "First Nextel iDEN phone with a built-in camera and push-to-talk.",
  "motorola-aura": "Luxury phone with the first circular display, priced near $2,000.",
  "essential-phone-ph-1": "Titanium-and-ceramic phone from Android co-founder Andy Rubin.",
  "nokia-7280": "No keypad — dialed via a rotating \"Navi Wheel\"; the \"lipstick phone.\"",
  "siemens-sx1": "Keys sat in two vertical strips flanking the screen, no normal keypad.",
  "motorola-cliq": "Motorola's first Android phone, using the custom MOTOBLUR interface.",
  "alcatel-one-touch-300": "Basic monochrome handset from Alcatel's early One Touch lineup.",
  "sagem-myx-7": "French candybar phone from Sagem's budget myX series.",
  "ericsson-r310s": "Rugged, splash-resistant candybar from Ericsson's budget R-series.",
  "kyocera-6035": "One of the very first US smartphones, combining a phone with Palm OS.",
  "sharp-j-sh04": "World's first mass-market mobile phone with a built-in camera.",
  "samsung-sgh-t100": "First mobile phone with a thin-film-transistor color display.",
};

export default PHONES_E65_FACTS;