export const PICKUPS_E71_FACTS = {
  "ford-f-150": "America's best-selling pickup truck for over 40 years.",
  "chevrolet-silverado": "Named after a former top trim level on older Chevy trucks.",
  "ram-1500": "Ram split off from Dodge to become its own brand in 2010.",
  "toyota-tacoma": "One of the best-selling midsize pickups in America.",
  "toyota-hilux": "Famous for surviving brutal durability tests on Top Gear.",
  "toyota-tundra": "Toyota's full-size pickup, built to compete with US trucks.",
  "nissan-titan": "Nissan's full-size pickup, built specifically for the US market.",
  "gmc-sierra": "Shares its platform with the Chevrolet Silverado.",
  "ford-ranger": "A midsize truck sold globally long before it returned to the US.",
  "chevrolet-colorado": "Chevrolet's midsize pickup, smaller than the Silverado.",
  "honda-ridgeline": "Built on a car-like unibody frame, unlike most pickups.",
  "ford-f-250-super-duty": "Part of Ford's heavy-duty truck lineup above the F-150.",
  "nissan-frontier": "Nissan's midsize pickup, sold in the US since the 1990s.",
  "jeep-gladiator": "A pickup version of the Jeep Wrangler.",
  "chevrolet-el-camino": "A car-truck hybrid built on a Chevelle-based platform.",
  "volkswagen-amarok": "Its second generation was co-developed with Ford.",
  "mitsubishi-l200": "Also sold under the name Mitsubishi Triton in some markets.",
  "isuzu-d-max": "Isuzu's global pickup, related to past Chevrolet Colorados.",

  "ford-maverick": "A compact pickup built on the same platform as the Ford Escape.",
  "hyundai-santa-cruz": "Hyundai's first pickup truck sold in North America.",
  "ram-2500": "A heavy-duty Ram built for towing and hauling.",
  "gmc-canyon": "GMC's version of the Chevrolet Colorado midsize truck.",
  "ford-f-350": "A heavier Super Duty truck, offered with dual rear wheels.",
  "chevrolet-avalanche": "Combined a pickup bed with an SUV-style cabin.",
  "dodge-dakota": "Once marketed as the first midsize pickup with a V8 option.",
  "nissan-navara": "Nissan's global pickup, sold as the Frontier in North America.",
  "great-wall-steed": "A pickup from one of China's largest automakers.",
  "ssangyong-musso": "A Korean pickup name revived decades after the original model.",
  "mazda-bt-50": "Built on the same platform as the Isuzu D-Max in later generations.",
  "chevrolet-luv": "Its name stood for 'Light Utility Vehicle'.",
  "datsun-620": "Sold under the Datsun name before Nissan phased it out.",
  "toyota-stout": "An early Toyota pickup that predates the Hilux.",
  "subaru-brat": "Had rear-facing jump seats bolted into its truck bed.",
  "volkswagen-caddy-pickup": "Known in the US as the Volkswagen Rabbit Pickup.",
  "holden-ute": "An Australian-market pickup based on a sedan platform.",
  "mahindra-scorpio-pik-up": "A pickup version of Mahindra's Scorpio SUV.",

  "chevrolet-ssr": "A retractable hardtop pickup styled after 1940s trucks.",
  "dodge-ram-srt-10": "Powered by the Dodge Viper's V10 engine.",
  "ford-svt-lightning": "A high-performance F-150 built by Ford's Special Vehicle Team.",
  "studebaker-champ": "One of the last truck models Studebaker ever built.",
  "willys-jeep-truck": "Built by the same company behind the original military Jeep.",
  "dodge-power-wagon": "Originally developed from a World War II military truck.",
  "chevrolet-cheyenne": "Once a trim level, later sold as its own model in Mexico.",
  "gmc-syclone": "A turbocharged pickup that could outrun some sports cars.",
  "toyota-pickup-1980s": "Sold simply as 'Toyota Pickup' before the Tacoma name existed.",
  "ford-ranger-raptor": "A high-performance off-road version of the Ranger.",
  "isuzu-hombre": "A rebadged version of the Chevrolet S-10.",
  "suzuki-equator": "A rebadged version of the Nissan Frontier.",
  "fiat-strada": "A compact pickup popular in South American markets.",
  "volkswagen-saveiro": "A pickup version of the Volkswagen Gol, popular in Brazil.",
  "renault-duster-oroch": "A pickup version of the Renault Duster SUV.",
  "tata-xenon": "One of Tata Motors' pickups sold in international markets.",

  "skoda-felicia-pickup": "A pickup version of Škoda's compact Felicia hatchback.",
  "peugeot-landtrek": "Peugeot's return to the pickup segment after decades away.",
  "gwm-poer": "A pickup line from Great Wall Motors' GWM brand.",
  "jac-t8": "A pickup from Chinese manufacturer JAC Motors.",
  "foton-tunland": "A pickup from Chinese truck maker Foton.",
  "ldv-t60": "Built by a brand that traces its roots to British Leyland.",
  "maxus-t90": "One of the larger pickups sold under the Maxus name.",
  "changan-hunter": "A pickup from Chinese automaker Changan.",
  "mahindra-bolero-pickup": "A pickup version of Mahindra's popular Bolero SUV.",
  "nissan-np300": "Also sold as the Nissan Hardbody in some markets.",
  "ashok-leyland-dost": "A small commercial truck from Indian maker Ashok Leyland.",
  "piaggio-porter": "A tiny Italian truck often used for deliveries in narrow streets.",
  "dfsk-super-cab": "A budget pickup from Chinese brand DFSK.",
  "jmc-vigus": "A pickup from JMC, a Chinese automaker partly owned by Ford.",
  "great-wall-wingle": "The Wingle is Great Wall's domestic name for the Steed.",
  "ford-courier": "A Mazda-based compact pickup Ford sold in the US, 1972-1982.",
  "datsun-720": "A later generation of the Datsun pickup line.",
  "opel-campo": "A rebadged version of the Isuzu Faster sold by Opel.",
};

export default PICKUPS_E71_FACTS;
