// E71 "Guess the Pickup Truck" — 70 real gas/diesel pickup trucks, third of 5 planned car-themed episodes.
// Distinct sub-theme from E07 (car brand logos), E53 (general classic cars, no pickups), E69 (ICE
// supercars), and E70 (this episode excludes every EV pickup already used there — Tesla Cybertruck,
// Rivian R1T, Ford F-150 Lightning, Chevrolet Silverado EV, GMC Hummer EV — this episode is gas/diesel only).
// image: pickups71/<slug>.jpg | wiki: exact Wikipedia article title | Zero Israel content (standing hard rule).
export const PICKUPS_E71 = [
  // EASY (18)
  { slug: "ford-f-150", name: "Ford F-150", wiki: "Ford F-150", level: "easy" },
  { slug: "chevrolet-silverado", name: "Chevrolet Silverado", wiki: "Chevrolet Silverado", level: "easy" },
  { slug: "ram-1500", name: "Ram 1500", wiki: "Ram Pickup", level: "easy" },
  { slug: "toyota-tacoma", name: "Toyota Tacoma", wiki: "Toyota Tacoma", level: "easy" },
  { slug: "toyota-hilux", name: "Toyota Hilux", wiki: "Toyota Hilux", level: "easy" },
  { slug: "toyota-tundra", name: "Toyota Tundra", wiki: "Toyota Tundra", level: "easy" },
  { slug: "nissan-titan", name: "Nissan Titan", wiki: "Nissan Titan", level: "easy" },
  { slug: "gmc-sierra", name: "GMC Sierra", wiki: "GMC Sierra", level: "easy" },
  { slug: "ford-ranger", name: "Ford Ranger", wiki: "Ford Ranger", level: "easy" },
  { slug: "chevrolet-colorado", name: "Chevrolet Colorado", wiki: "Chevrolet Colorado", level: "easy" },
  { slug: "honda-ridgeline", name: "Honda Ridgeline", wiki: "Honda Ridgeline", level: "easy" },
  { slug: "ford-f-250-super-duty", name: "Ford F-250 Super Duty", wiki: "Ford Super Duty", level: "easy" },
  { slug: "nissan-frontier", name: "Nissan Frontier", wiki: "Nissan Frontier", level: "easy" },
  { slug: "jeep-gladiator", name: "Jeep Gladiator", wiki: "Jeep Gladiator (JT)", level: "easy" },
  { slug: "chevrolet-el-camino", name: "Chevrolet El Camino", wiki: "Chevrolet El Camino", level: "easy" },
  { slug: "volkswagen-amarok", name: "Volkswagen Amarok", wiki: "Volkswagen Amarok", level: "easy" },
  { slug: "mitsubishi-l200", name: "Mitsubishi L200", wiki: "Mitsubishi Triton", level: "easy" },
  { slug: "isuzu-d-max", name: "Isuzu D-Max", wiki: "Isuzu D-Max", level: "easy" },

  // MEDIUM (18)
  { slug: "ford-maverick", name: "Ford Maverick", wiki: "Ford Maverick (2021)", level: "medium" },
  { slug: "hyundai-santa-cruz", name: "Hyundai Santa Cruz", wiki: "Hyundai Santa Cruz", level: "medium" },
  { slug: "ram-2500", name: "Ram 2500", wiki: "Ram Pickup", level: "medium" },
  { slug: "gmc-canyon", name: "GMC Canyon", wiki: "GMC Canyon", level: "medium" },
  { slug: "ford-f-350", name: "Ford F-350", wiki: "Ford Super Duty", level: "medium" },
  { slug: "chevrolet-avalanche", name: "Chevrolet Avalanche", wiki: "Chevrolet Avalanche", level: "medium" },
  { slug: "dodge-dakota", name: "Dodge Dakota", wiki: "Dodge Dakota", level: "medium" },
  { slug: "nissan-navara", name: "Nissan Navara", wiki: "Nissan Navara", level: "medium" },
  { slug: "great-wall-steed", name: "Great Wall Steed", wiki: "Great Wall Steed", level: "medium" },
  { slug: "ssangyong-musso", name: "SsangYong Musso", wiki: "SsangYong Musso (2018)", level: "medium" },
  { slug: "mazda-bt-50", name: "Mazda BT-50", wiki: "Mazda BT-50", level: "medium" },
  { slug: "chevrolet-luv", name: "Chevrolet LUV", wiki: "Chevrolet LUV", level: "medium" },
  { slug: "datsun-620", name: "Datsun 620", wiki: "Datsun Truck", level: "medium" },
  { slug: "toyota-stout", name: "Toyota Stout", wiki: "Toyota Stout", level: "medium" },
  { slug: "subaru-brat", name: "Subaru BRAT", wiki: "Subaru BRAT", level: "medium" },
  { slug: "volkswagen-caddy-pickup", name: "Volkswagen Caddy Pickup", wiki: "Volkswagen Caddy", level: "medium" },
  { slug: "holden-ute", name: "Holden Ute", wiki: "Holden Ute", level: "medium" },
  { slug: "mahindra-scorpio-pik-up", name: "Mahindra Scorpio Pik-Up", wiki: "Mahindra Scorpio", level: "medium" },

  // HARD (16)
  { slug: "chevrolet-ssr", name: "Chevrolet SSR", wiki: "Chevrolet SSR", level: "hard" },
  { slug: "dodge-ram-srt-10", name: "Dodge Ram SRT-10", wiki: "Dodge Ram SRT-10", level: "hard" },
  { slug: "ford-svt-lightning", name: "Ford SVT Lightning", wiki: "Ford SVT Lightning", level: "hard" },
  { slug: "studebaker-champ", name: "Studebaker Champ", wiki: "Studebaker Champ", level: "hard" },
  { slug: "willys-jeep-truck", name: "Willys Jeep Truck", wiki: "Willys Jeep Truck", level: "hard" },
  { slug: "dodge-power-wagon", name: "Dodge Power Wagon", wiki: "Dodge Power Wagon", level: "hard" },
  { slug: "chevrolet-cheyenne", name: "Chevrolet Cheyenne", wiki: "Chevrolet Cheyenne", level: "hard" },
  { slug: "gmc-syclone", name: "GMC Syclone", wiki: "GMC Syclone", level: "hard" },
  { slug: "toyota-pickup-1980s", name: "Toyota Pickup", wiki: "Toyota Hilux", level: "hard" },
  { slug: "ford-ranger-raptor", name: "Ford Ranger Raptor", wiki: "Ford Ranger Raptor", level: "hard" },
  { slug: "isuzu-hombre", name: "Isuzu Hombre", wiki: "Isuzu Hombre", level: "hard" },
  { slug: "suzuki-equator", name: "Suzuki Equator", wiki: "Suzuki Equator", level: "hard" },
  { slug: "fiat-strada", name: "Fiat Strada", wiki: "Fiat Strada", level: "hard" },
  { slug: "volkswagen-saveiro", name: "Volkswagen Saveiro", wiki: "Volkswagen Saveiro", level: "hard" },
  { slug: "renault-duster-oroch", name: "Renault Duster Oroch", wiki: "Renault Duster Oroch", level: "hard" },
  { slug: "tata-xenon", name: "Tata Xenon", wiki: "Tata Xenon", level: "hard" },

  // IMPOSSIBLE (18)
  { slug: "skoda-felicia-pickup", name: "Škoda Felicia Pickup", wiki: "Škoda Felicia", level: "impossible" },
  { slug: "peugeot-landtrek", name: "Peugeot Landtrek", wiki: "Peugeot Landtrek", level: "impossible" },
  { slug: "gwm-poer", name: "GWM Poer", wiki: "GWM Poer", level: "impossible" },
  { slug: "jac-t8", name: "JAC T8", wiki: "JAC T8", level: "impossible" },
  { slug: "foton-tunland", name: "Foton Tunland", wiki: "Foton Tunland", level: "impossible" },
  { slug: "ldv-t60", name: "LDV T60", wiki: "LDV T60", level: "impossible" },
  { slug: "maxus-t90", name: "Maxus T90", wiki: "Maxus T90", level: "impossible" },
  { slug: "changan-hunter", name: "Changan Hunter", wiki: "Changan Hunter", level: "impossible" },
  { slug: "mahindra-bolero-pickup", name: "Mahindra Bolero Pickup", wiki: "Mahindra Bolero", level: "impossible" },
  { slug: "nissan-np300", name: "Nissan NP300", wiki: "Nissan NP300 Hardbody", level: "impossible" },
  { slug: "ashok-leyland-dost", name: "Ashok Leyland Dost", wiki: "Ashok Leyland Dost", level: "impossible" },
  { slug: "piaggio-porter", name: "Piaggio Porter", wiki: "Piaggio Porter", level: "impossible" },
  { slug: "dfsk-super-cab", name: "DFSK Super Cab", wiki: "DFSK Super Cab", level: "impossible" },
  { slug: "jmc-vigus", name: "JMC Vigus", wiki: "JMC Vigus", level: "impossible" },
  { slug: "great-wall-wingle", name: "Great Wall Wingle", wiki: "Great Wall Wingle", level: "impossible" },
  { slug: "ford-courier", name: "Ford Courier", wiki: "Ford Courier (pickup truck)", level: "impossible" },
  { slug: "datsun-720", name: "Datsun 720", wiki: "Datsun Truck", level: "impossible" },
  { slug: "opel-campo", name: "Opel Campo", wiki: "Opel Campo", level: "impossible" },
];

export default PICKUPS_E71;
