export const PLANETS_SPACE_E40_FACTS = {
  "earth": "Earth is the only known planet to host life.",
  "sun": "The Sun holds 99.8% of the Solar System's total mass.",
  "moon": "The Moon drifts about 3.8 cm farther from Earth yearly.",
  "saturn": "Saturn's rings are made mostly of ice chunks and rock.",
  "mars": "Mars hosts Olympus Mons, the tallest volcano known.",
  "jupiter": "Jupiter's Great Red Spot is a storm bigger than Earth.",
  "space-shuttle": "The Space Shuttle flew 135 missions from 1981 to 2011.",
  "iss": "The ISS orbits Earth roughly every 90 minutes.",
  "milky-way": "The Milky Way holds an estimated 100-400 billion stars.",
  "hubble": "Hubble has orbited Earth since 1990 and still works.",
  "apollo-lm": "The Lunar Module first landed astronauts on the Moon in 1969.",
  "venus": "Venus spins backward and is the hottest planet.",
  "saturn-v": "Saturn V is the only rocket to launch humans to the Moon.",
  "mercury": "Mercury has no moons and almost no atmosphere.",
  "jwst": "JWST launched Dec 25, 2021, orbiting 1.5M km from Earth.",
  "pluto": "Pluto has a heart-shaped glacier the size of Texas.",
  "neptune": "Neptune has the fastest winds in the Solar System.",
  "uranus": "Uranus rotates nearly sideways, tilted 98 degrees.",

  "andromeda-galaxy": "Andromeda may collide with the Milky Way billions of years from now.",
  "curiosity-rover": "Curiosity has explored Mars' Gale Crater since 2012.",
  "voyager-probe": "Voyager 1 is the farthest human-made object from Earth.",
  "eagle-nebula": "The Pillars of Creation photo was taken by Hubble in 1995.",
  "halleys-comet": "Halley's Comet returns to Earth's skies every ~76 years.",
  "orion-nebula": "The Orion Nebula is visible to the naked eye as a fuzzy star.",
  "pleiades": "The Pleiades cluster holds over 1,000 stars, not seven.",
  "europa": "Europa's icy shell may hide an ocean with twice Earth's water.",
  "titan": "Titan is the only moon with a thick atmosphere and lakes.",
  "perseverance-rover": "Perseverance hunts for signs of ancient microbial life.",
  "sputnik-1": "Sputnik 1 was the first artificial satellite, launched 1957.",
  "crab-nebula": "The Crab Nebula formed from a supernova seen in 1054 AD.",
  "io": "Io is the most volcanically active body in the Solar System.",
  "ganymede": "Ganymede is the largest moon, bigger than Mercury.",
  "enceladus": "Enceladus shoots water-ice geysers from its south pole.",
  "cassini-probe": "Cassini spent 13 years orbiting Saturn before its 2017 dive.",
  "mimas": "Mimas's giant crater gives it a real-life 'Death Star' look.",
  "ring-nebula": "The Ring Nebula is a dying star's glowing gas shell.",

  "ceres": "Ceres is the largest object in the asteroid belt.",
  "whirlpool-galaxy": "The Whirlpool Galaxy is interacting with a smaller companion.",
  "sombrero-galaxy": "The Sombrero Galaxy's core hides a 9-billion-solar-mass black hole.",
  "horsehead-nebula": "The Horsehead Nebula is a dust cloud silhouetted in red gas.",
  "helix-nebula": "The Helix Nebula is nicknamed the 'Eye of God.'",
  "new-horizons-probe": "New Horizons gave humanity its first close-up of Pluto in 2015.",
  "callisto": "Callisto is Jupiter's most heavily cratered moon.",
  "hale-bopp-comet": "Comet Hale-Bopp stayed visible to the naked eye for a record 18 months.",
  "philae-lander": "Philae was the first spacecraft to land softly on a comet.",
  "triton": "Triton orbits Neptune backward, opposite the planet's spin.",
  "neowise-comet": "Comet NEOWISE dazzled skywatchers in summer 2020.",
  "triangulum-galaxy": "The Triangulum Galaxy is third-largest in our Local Group.",
  "vesta": "Vesta is bright enough to sometimes see without a telescope.",
  "kepler-telescope": "Kepler discovered over 2,600 confirmed exoplanets.",
  "charon": "Charon is so large that Pluto and Charon orbit a shared point.",
  "carina-nebula": "The Carina Nebula hosts some of the biggest stars known.",
  "bennu": "NASA's OSIRIS-REx grabbed asteroid Bennu samples in 2020.",
  "parker-solar-probe": "Parker Solar Probe flew closer to the Sun than any craft.",

  "phobos": "Phobos orbits Mars so fast it rises twice a day.",
  "juno-probe": "Juno has orbited Jupiter's poles since arriving in 2016.",
  "miranda": "Miranda has some of the tallest cliffs in the Solar System.",
  "pinwheel-galaxy": "The Pinwheel Galaxy contains roughly a trillion stars.",
  "titania": "Titania is Uranus' largest moon, named after a fairy queen.",
  "chandra-observatory": "Chandra studies X-rays from black holes and dead stars.",
  "omega-centauri": "Omega Centauri holds millions of stars in one dense cluster.",
  "comet-67p": "Comet 67P was orbited and mapped by ESA's Rosetta mission.",
  "lagoon-nebula": "The Lagoon Nebula spans about 100 light-years across.",
  "cartwheel-galaxy": "The Cartwheel Galaxy's ring formed from a head-on collision.",
  "deimos": "Deimos is Mars's tiny, potato-shaped outer moon.",
  "ryugu": "Asteroid Ryugu is shaped like a spinning top.",
  "hyperion": "Hyperion tumbles chaotically instead of spinning smoothly.",
  "butterfly-nebula": "The Butterfly Nebula's wings glow from a dying star.",
  "antennae-galaxies": "The Antennae Galaxies are two spirals merging into one.",
  "itokawa": "Itokawa was the first asteroid sampled and returned to Earth.",
  "iapetus": "Iapetus has one bright and one dark hemisphere.",
  "amalthea": "Amalthea is a small, reddish, potato-shaped moon of Jupiter.",
};
