// E40 "Guess the Space Object" — answer = object name, image = real photo (NASA/ESA/JAXA sourced).
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
export const PLANETS_SPACE_E40 = [
  // EASY (18)
  { slug: "earth", name: "Earth", category: "planet", level: "easy" },
  { slug: "sun", name: "Sun", category: "star", level: "easy" },
  { slug: "moon", name: "The Moon", category: "moon", level: "easy" },
  { slug: "saturn", name: "Saturn", category: "planet", level: "easy" },
  { slug: "mars", name: "Mars", category: "planet", level: "easy" },
  { slug: "jupiter", name: "Jupiter", category: "planet", level: "easy" },
  { slug: "space-shuttle", name: "Space Shuttle", category: "spacecraft", level: "easy" },
  { slug: "iss", name: "International Space Station", category: "spacecraft", level: "easy" },
  { slug: "milky-way", name: "Milky Way", category: "galaxy", level: "easy" },
  { slug: "hubble", name: "Hubble Space Telescope", category: "spacecraft", level: "easy" },
  { slug: "apollo-lm", name: "Apollo Lunar Module", category: "spacecraft", level: "easy" },
  { slug: "venus", name: "Venus", category: "planet", level: "easy" },
  { slug: "saturn-v", name: "Saturn V Rocket", category: "spacecraft", level: "easy" },
  { slug: "mercury", name: "Mercury", category: "planet", level: "easy" },
  { slug: "jwst", name: "James Webb Space Telescope", category: "spacecraft", level: "easy" },
  { slug: "pluto", name: "Pluto", category: "dwarf planet", level: "easy" },
  { slug: "neptune", name: "Neptune", category: "planet", level: "easy" },
  { slug: "uranus", name: "Uranus", category: "planet", level: "easy" },

  // MEDIUM (18)
  { slug: "andromeda-galaxy", name: "Andromeda Galaxy", category: "galaxy", level: "medium" },
  { slug: "curiosity-rover", name: "Curiosity Rover", category: "spacecraft", level: "medium" },
  { slug: "voyager-probe", name: "Voyager Probe", category: "spacecraft", level: "medium" },
  { slug: "eagle-nebula", name: "Eagle Nebula", category: "nebula", level: "medium" },
  { slug: "halleys-comet", name: "Halley's Comet", category: "comet", level: "medium" },
  { slug: "orion-nebula", name: "Orion Nebula", category: "nebula", level: "medium" },
  { slug: "pleiades", name: "Pleiades", category: "star cluster", level: "medium" },
  { slug: "europa", name: "Europa", category: "moon", level: "medium" },
  { slug: "titan", name: "Titan", category: "moon", level: "medium" },
  { slug: "perseverance-rover", name: "Perseverance Rover", category: "spacecraft", level: "medium" },
  { slug: "sputnik-1", name: "Sputnik 1", category: "spacecraft", level: "medium" },
  { slug: "crab-nebula", name: "Crab Nebula", category: "nebula", level: "medium" },
  { slug: "io", name: "Io", category: "moon", level: "medium" },
  { slug: "ganymede", name: "Ganymede", category: "moon", level: "medium" },
  { slug: "enceladus", name: "Enceladus", category: "moon", level: "medium" },
  { slug: "cassini-probe", name: "Cassini Probe", category: "spacecraft", level: "medium" },
  { slug: "mimas", name: "Mimas", category: "moon", level: "medium" },
  { slug: "ring-nebula", name: "Ring Nebula", category: "nebula", level: "medium" },

  // HARD (18)
  { slug: "ceres", name: "Ceres", category: "dwarf planet", level: "hard" },
  { slug: "whirlpool-galaxy", name: "Whirlpool Galaxy", category: "galaxy", level: "hard" },
  { slug: "sombrero-galaxy", name: "Sombrero Galaxy", category: "galaxy", level: "hard" },
  { slug: "horsehead-nebula", name: "Horsehead Nebula", category: "nebula", level: "hard" },
  { slug: "helix-nebula", name: "Helix Nebula", category: "nebula", level: "hard" },
  { slug: "new-horizons-probe", name: "New Horizons Probe", category: "spacecraft", level: "hard" },
  { slug: "callisto", name: "Callisto", category: "moon", level: "hard" },
  { slug: "hale-bopp-comet", name: "Comet Hale-Bopp", category: "comet", level: "hard" },
  { slug: "philae-lander", name: "Philae Lander", category: "spacecraft", level: "hard" },
  { slug: "triton", name: "Triton", category: "moon", level: "hard" },
  { slug: "neowise-comet", name: "Comet NEOWISE", category: "comet", level: "hard" },
  { slug: "triangulum-galaxy", name: "Triangulum Galaxy", category: "galaxy", level: "hard" },
  { slug: "vesta", name: "Vesta", category: "asteroid", level: "hard" },
  { slug: "kepler-telescope", name: "Kepler Space Telescope", category: "spacecraft", level: "hard" },
  { slug: "charon", name: "Charon", category: "moon", level: "hard" },
  { slug: "carina-nebula", name: "Carina Nebula", category: "nebula", level: "hard" },
  { slug: "bennu", name: "Bennu", category: "asteroid", level: "hard" },
  { slug: "parker-solar-probe", name: "Parker Solar Probe", category: "spacecraft", level: "hard" },

  // IMPOSSIBLE (18)
  { slug: "phobos", name: "Phobos", category: "moon", level: "impossible" },
  { slug: "juno-probe", name: "Juno Probe", category: "spacecraft", level: "impossible" },
  { slug: "miranda", name: "Miranda", category: "moon", level: "impossible" },
  { slug: "pinwheel-galaxy", name: "Pinwheel Galaxy", category: "galaxy", level: "impossible" },
  { slug: "titania", name: "Titania", category: "moon", level: "impossible" },
  { slug: "chandra-observatory", name: "Chandra X-ray Observatory", category: "spacecraft", level: "impossible" },
  { slug: "omega-centauri", name: "Omega Centauri", category: "star cluster", level: "impossible" },
  { slug: "comet-67p", name: "Comet 67P", category: "comet", level: "impossible" },
  { slug: "lagoon-nebula", name: "Lagoon Nebula", category: "nebula", level: "impossible" },
  { slug: "cartwheel-galaxy", name: "Cartwheel Galaxy", category: "galaxy", level: "impossible" },
  { slug: "deimos", name: "Deimos", category: "moon", level: "impossible" },
  { slug: "ryugu", name: "Ryugu", category: "asteroid", level: "impossible" },
  { slug: "hyperion", name: "Hyperion", category: "moon", level: "impossible" },
  { slug: "butterfly-nebula", name: "Butterfly Nebula", category: "nebula", level: "impossible" },
  { slug: "antennae-galaxies", name: "Antennae Galaxies", category: "galaxy", level: "impossible" },
  { slug: "itokawa", name: "Itokawa", category: "asteroid", level: "impossible" },
  { slug: "iapetus", name: "Iapetus", category: "moon", level: "impossible" },
  { slug: "amalthea", name: "Amalthea", category: "moon", level: "impossible" },
];
