export const RELIGION_SYMBOLS_E91_FACTS = {
  "christian-cross": "The cross became a widely used Christian symbol only from the 4th century onward, after it stopped being a common Roman method of execution.",
  "islamic-star-and-crescent": "The star and crescent predates Islam by centuries as an ancient Near Eastern and Byzantine emblem, and only became widely linked to Islam after the Ottoman Empire adopted it on its flag.",
  "star-of-david": "The six-pointed star was used decoratively by many cultures for centuries before it became a specifically Jewish emblem in the Middle Ages.",
  "om-symbol": "Om is considered a sacred sound believed to be the first vibration of creation, and is chanted at the start of most Hindu prayers and rituals.",
  "dharma-wheel": "The eight spokes represent the Noble Eightfold Path, the Buddha's core teaching on the way to end suffering.",
  khanda: "The Khanda's central circle, the chakkar, has no beginning or end and represents the eternal, undivided nature of God in Sikh belief.",
  "yin-yang": "The yin-yang predates organized Taoism, but Taoist philosophy adopted it to represent how opposite forces are interconnected and always in dynamic balance.",
  ankh: "Ancient Egyptian art frequently shows gods holding the ankh to the noses of pharaohs, symbolizing the \"breath of life.\"",
  mjolnir: "Thousands of small Mjölnir pendants have been found across Scandinavia, and archaeologists believe Vikings wore them the way many people today wear cross necklaces.",
  ichthys: "Early Christians reportedly used the fish outline as a covert identification mark, since the Greek letters of \"ichthys\" (fish) form an acronym for \"Jesus Christ, Son of God, Savior.\"",
  menorah: "The seven-branched menorah, distinct from the nine-branched Hanukkah menorah (hanukkiah), is one of the oldest continuously used symbols of Judaism, described in the Hebrew Bible's account of the Tabernacle.",
  "lotus-flower": "The lotus is used as a Buddhist symbol because the flower rises clean and unstained out of muddy water, representing purity and enlightenment emerging from difficulty.",
  "torii-gate": "Torii gates mark the transition from ordinary space into a Shinto shrine's sacred grounds, and many are painted vermillion red for protective and ceremonial reasons.",
  dreamcatcher: "The dreamcatcher originated with the Ojibwe (Chippewa) people, who traditionally hung it over a cradle or bed believing its web would filter out bad dreams.",
  "dove-holy-spirit": "The dove is used in Christian art to represent the Holy Spirit specifically because all four Gospels describe the Spirit descending like a dove at Jesus's baptism.",
  "the-kaaba": "Muslims around the world face the direction of the Kaaba in Mecca during each of their five daily prayers, a direction known as the qibla.",
  "tablets-of-the-law": "The two-tablet shape with rounded tops is a European artistic convention; the Hebrew Bible's own description of the tablets Moses received does not specify their exact shape.",
  "trident-of-poseidon": "In Greek myth, Poseidon's trident could strike the earth to summon storms or earthquakes, reflecting his role as god of the sea and of earthquakes alike.",
  faravahar: "Scholars still debate exactly what the Faravahar represents - common interpretations include the guardian spirit (fravashi), the human soul, or royal glory, rather than one single agreed meaning.",
  "bahai-nine-pointed-star": "The number nine is significant in the Baha'i Faith partly because, in the Arabic Abjad numeral system, the letters of the word \"Baha\" (glory) add up to nine.",
  "jain-ahimsa-hand": "The wheel in the palm represents samsara, the cycle of rebirth, and its 24 spokes stand for the 24 Tirthankaras, the enlightened teachers of Jainism.",
  "orthodox-cross": "The slanted lowest bar is traditionally explained as a footrest, tilted to represent one thief crucified beside Jesus repenting and rising toward heaven while the other did not.",
  "endless-knot": "The endless knot is one of the Eight Auspicious Symbols of Buddhism and represents the interweaving of wisdom and compassion, and the interdependence of all things.",
  "lion-of-judah": "The Lion of Judah is an ancient emblem referring to the biblical tribe of Judah that was used in Ethiopian Christian tradition for centuries before Rastafari adopted it in the 20th century.",
  "triple-moon": "The Triple Moon represents three phases of the Goddess in Wicca - Maiden, Mother, and Crone - mirroring the waxing, full, and waning moon.",
  "allah-calligraphy": "Islamic tradition generally discourages figural religious imagery, so calligraphy of God's name became one of the most widespread visual expressions of Islamic devotion.",
  trishula: "The trishula's three prongs are often interpreted as representing the three fundamental powers of creation, preservation, and destruction associated with the Hindu trinity.",
  "celtic-cross": "The ring on a Celtic cross is thought by some historians to derive from earlier Celtic sun-symbol imagery blended with the Christian cross after Ireland's conversion.",
  shimenawa: "A shimenawa marks the boundary of a sacred space in Shinto, and is often wrapped around shrine gates, sacred trees, or unusual rock formations believed to house a kami (spirit).",
  "ik-onkar": "Ik Onkar is the opening phrase of the Guru Granth Sahib, the central Sikh scripture, and translates roughly to \"There is one God.\"",
  "chi-rho": "The Chi-Rho combines the first two Greek letters of \"Christ\" (Christos) and was reportedly the sign the Roman emperor Constantine had painted on his soldiers' shields before a decisive battle in 312 CE.",
  "bodhi-leaf": "The bodhi leaf represents the pipal (fig) tree under which the Buddha is said to have attained enlightenment while meditating.",
  valknut: "The valknut appears on Viking-era memorial stones alongside images linked to Odin, leading most scholars to connect it with death and the afterlife in Norse belief.",
  caduceus: "The caduceus belongs to Hermes, the messenger god, and is often mistaken for a medical symbol - the actual traditional medical symbol is the Rod of Asclepius, which has only one snake and no wings.",
  bagua: "Each of the eight trigrams in the bagua is built from combinations of solid (yang) and broken (yin) lines, and together they are traditionally used to represent the fundamental forces and cycles of nature.",
  "eye-of-horus": "The Eye of Horus was widely used as a protective amulet in ancient Egypt, worn to guard the wearer's health and ward off evil; its Egyptian name, wedjat, means \"the whole one.\"",
  yggdrasil: "In Norse mythology, Yggdrasil's branches and roots were believed to connect and hold together all nine worlds of the cosmos, from the realm of the gods to the realm of the dead.",
  "owl-of-athena": "The little owl was sacred to Athena, goddess of wisdom, and its image was stamped on ancient Athenian coins for centuries.",
  triskelion: "The triple spiral appears carved into the entrance stone of Newgrange in Ireland, a Neolithic monument built roughly 5,000 years ago, long before the Celts arrived there.",
  triquetra: "The triquetra's three-fold symmetry made it useful for representing triple concepts in more than one tradition - it appears in pre-Christian Celtic art and was later adopted by some Christians to represent the Trinity.",
  ollin: "Ollin means \"movement\" or \"earthquake\" in Nahuatl, and named the current era in Aztec cosmology, which they believed would one day end in destruction by earthquakes.",
  "zoroastrian-fire-altar": "Fire is a central symbol of purity in Zoroastrianism, and sacred fires are kept perpetually burning in Zoroastrian fire temples, some reportedly alight for centuries.",
  zulfiqar: "The Zulfiqar is remembered in Islamic tradition as the sword of Ali, cousin and son-in-law of the Prophet Muhammad, and remains an especially important image in Shia devotional art.",
  "gye-nyame": "Gye Nyame is an Adinkra symbol from the Akan people of West Africa whose name translates to \"except for God,\" expressing belief in a supreme being's ultimate authority.",
  "sami-sun-symbol": "Traditional Sámi shaman drums (goavddis) were painted with figures representing the sun, animals, and spirits, and were used by a noaidi (shaman) to journey between worlds in trance.",
  "shri-yantra": "The Shri Yantra's nine triangles are believed to represent the union of masculine and feminine divine energy, and it is used in some Hindu traditions as a focus for meditation.",
  "hamsa-hand": "Known in Jewish tradition as the Hand of Miriam, this protective amulet has been used to ward off misfortune for centuries.",
  labrys: "The double-headed axe was a major sacred symbol in Bronze Age Minoan Crete, appearing carved into the walls of the palace of Knossos, home of the later Greek myth of the labyrinth.",
  "medicine-wheel": "Medicine wheels are large stone structures built by Plains Indigenous nations across North America, some over a thousand years old, and are still used for prayer and ceremony today.",
  vajra: "Vajra means both \"thunderbolt\" and \"diamond\" in Sanskrit, representing a spiritual power believed to be as unbreakable as a diamond and as swift as lightning.",
  "alpha-omega": "\"Alpha and Omega,\" the first and last letters of the Greek alphabet, is a title used in the Book of Revelation to describe God as the beginning and the end of all things.",
  "scarab-beetle": "Ancient Egyptians associated the scarab beetle with the god Khepri and the rising sun because they observed the beetles rolling dung balls across the ground, which they linked to the sun's daily journey across the sky.",
  "star-of-ishtar": "The eight-pointed star represented the planet Venus and the goddess Ishtar (also known as Inanna), and appears on Mesopotamian cylinder seals and boundary stones (kudurru) dating back over 4,000 years.",
  "symbol-of-marduk": "The mushhushshu, or \"furious snake,\" is depicted in rows of glazed brick relief on Babylon's Ishtar Gate and was closely associated with the chief Babylonian god Marduk.",
  "mithraic-bull": "Mithraism was a mystery religion popular among soldiers in the Roman Empire, and its meeting halls (mithraea) were often built underground to evoke a cave.",
  "manichaean-cross-of-light": "Manichaeism, founded by the prophet Mani in 3rd-century Persia, taught a cosmic struggle between light and darkness and spread from North Africa to China before eventually dying out.",
  "veve-papa-legba": "A veve is a ritual diagram drawn on the ground, traditionally in cornmeal or flour, to invite a specific spirit (lwa) to a Vodou ceremony.",
  "melek-taus-peacock": "In Yazidi belief, Tawûsî Melek (the \"Peacock Angel\") is the chief of seven angels through whom God governs the world, and Yazidis consider him a loyal, benevolent figure rather than a fallen one.",
  "druze-star": "Each color of the Druze star represents a different spiritual principle, such as the mind, the soul, and the word, according to Druze religious tradition.",
  "rainbow-serpent": "The Rainbow Serpent is a major creator-being figure across many Aboriginal Australian Dreaming traditions, associated with waterholes, rivers, and the life-giving power of rain.",
  "baal-lightning-bolt": "Ancient stone carvings from the city of Ugarit show the storm god Baal holding a raised club in one hand and a stylized lightning bolt in the other.",
  "etruscan-lituus": "Etruscan and later Roman religious officials called augurs used the lituus to mark out a section of sky for observing the flight of birds, a practice believed to reveal the will of the gods.",
  ouroboros: "The ouroboros appears in Gnostic texts and gems as a symbol of the eternal cycle of the cosmos, though the image itself is even older, tracing back to ancient Egyptian funerary art.",
  "wacah-chan": "In Maya belief, the World Tree was thought to grow at the center of the world, its branches, trunk, and roots connecting the sky, the earthly realm, and the underworld.",
  "sheaf-of-wheat": "The Eleusinian Mysteries were secret initiation rites held in ancient Greece for nearly two thousand years, centered on the goddess Demeter and her daughter Persephone, and used wheat as a symbol of death and rebirth tied to the harvest cycle.",
  chakana: "The chakana's stepped design is thought to represent the three levels of the Andean cosmos - the underworld, the earthly world, and the upper world - connected through its center.",
  omphalos: "The omphalos at Delphi marked what the ancient Greeks believed was the exact geographical center, or \"navel,\" of the world.",
  "yowa-cross": "The Kongo cosmogram represents the four moments of the sun - dawn, noon, sunset, and midnight - mapping both the daily solar cycle and the journey of the soul between the living and ancestral worlds.",
  fulmen: "The thunderbolt, or fulmen, was the chief attribute of Jupiter, king of the Roman gods, and appeared on Roman coins, standards, and temple carvings as a mark of his supreme authority.",
  "sign-of-tanit": "Thousands of stone markers bearing the Sign of Tanit have been found in the ruins of ancient Carthage, most in a burial ground associated with the goddess Tanit, chief deity of the Punic city.",
};

export default RELIGION_SYMBOLS_E91_FACTS;
