// E24 "Guess the Snake / Reptile" — answer = species name.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
// Hard content rules: no Israel/Jerusalem/West Bank/Gaza content of any kind.
export const REPTILES_E24 = [
  // EASY (18) — instantly recognizable worldwide
  { slug: "king-cobra", name: "King Cobra", sci: "Ophiophagus hannah", level: "easy" },
  { slug: "green-anaconda", name: "Green Anaconda", sci: "Eunectes murinus", level: "easy" },
  { slug: "rattlesnake", name: "Rattlesnake", sci: "Crotalus atrox", level: "easy" },
  { slug: "komodo-dragon", name: "Komodo Dragon", sci: "Varanus komodoensis", level: "easy" },
  { slug: "nile-crocodile", name: "Nile Crocodile", sci: "Crocodylus niloticus", level: "easy" },
  { slug: "american-alligator", name: "American Alligator", sci: "Alligator mississippiensis", level: "easy" },
  { slug: "galapagos-tortoise", name: "Galapagos Tortoise", sci: "Chelonoidis niger", level: "easy" },
  { slug: "veiled-chameleon", name: "Veiled Chameleon", sci: "Chamaeleo calyptratus", level: "easy" },
  { slug: "green-iguana", name: "Green Iguana", sci: "Iguana iguana", level: "easy" },
  { slug: "burmese-python", name: "Burmese Python", sci: "Python bivittatus", level: "easy" },
  { slug: "leopard-gecko", name: "Leopard Gecko", sci: "Eublepharis macularius", level: "easy" },
  { slug: "green-sea-turtle", name: "Green Sea Turtle", sci: "Chelonia mydas", level: "easy" },
  { slug: "boa-constrictor", name: "Boa Constrictor", sci: "Boa constrictor", level: "easy" },
  { slug: "garter-snake", name: "Garter Snake", sci: "Thamnophis sirtalis", level: "easy" },
  { slug: "bearded-dragon", name: "Bearded Dragon", sci: "Pogona vitticeps", level: "easy" },
  { slug: "monitor-lizard", name: "Monitor Lizard", sci: "Varanus salvator", level: "easy" },
  { slug: "corn-snake", name: "Corn Snake", sci: "Pantherophis guttatus", level: "easy" },
  { slug: "box-turtle", name: "Box Turtle", sci: "Terrapene carolina", level: "easy" },

  // MEDIUM (18) — well known, less universally iconic
  { slug: "black-mamba", name: "Black Mamba", sci: "Dendroaspis polylepis", level: "medium" },
  { slug: "copperhead", name: "Copperhead", sci: "Agkistrodon contortrix", level: "medium" },
  { slug: "cottonmouth", name: "Cottonmouth", sci: "Agkistrodon piscivorus", level: "medium" },
  { slug: "gharial", name: "Gharial", sci: "Gavialis gangeticus", level: "medium" },
  { slug: "american-crocodile", name: "American Crocodile", sci: "Crocodylus acutus", level: "medium" },
  { slug: "painted-turtle", name: "Painted Turtle", sci: "Chrysemys picta", level: "medium" },
  { slug: "snapping-turtle", name: "Snapping Turtle", sci: "Chelydra serpentina", level: "medium" },
  { slug: "ball-python", name: "Ball Python", sci: "Python regius", level: "medium" },
  { slug: "milk-snake", name: "Milk Snake", sci: "Lampropeltis triangulum", level: "medium" },
  { slug: "gila-monster", name: "Gila Monster", sci: "Heloderma suspectum", level: "medium" },
  { slug: "horned-lizard", name: "Horned Lizard", sci: "Phrynosoma cornutum", level: "medium" },
  { slug: "chinese-water-dragon", name: "Chinese Water Dragon", sci: "Physignathus cocincinus", level: "medium" },
  { slug: "tokay-gecko", name: "Tokay Gecko", sci: "Gekko gecko", level: "medium" },
  { slug: "red-eared-slider", name: "Red-eared Slider", sci: "Trachemys scripta elegans", level: "medium" },
  { slug: "diamondback-terrapin", name: "Diamondback Terrapin", sci: "Malaclemys terrapin", level: "medium" },
  { slug: "grass-snake", name: "Grass Snake", sci: "Natrix natrix", level: "medium" },
  { slug: "rat-snake", name: "Rat Snake", sci: "Pantherophis obsoletus", level: "medium" },
  { slug: "blue-tongued-skink", name: "Blue-tongued Skink", sci: "Tiliqua scincoides", level: "medium" },

  // HARD (18) — recognizable to enthusiasts
  { slug: "gaboon-viper", name: "Gaboon Viper", sci: "Bitis gabonica", level: "hard" },
  { slug: "saw-scaled-viper", name: "Saw-scaled Viper", sci: "Echis carinatus", level: "hard" },
  { slug: "bushmaster", name: "Bushmaster", sci: "Lachesis muta", level: "hard" },
  { slug: "eyelash-viper", name: "Eyelash Viper", sci: "Bothriechis schlegelii", level: "hard" },
  { slug: "vine-snake", name: "Vine Snake", sci: "Oxybelis aeneus", level: "hard" },
  { slug: "tuatara", name: "Tuatara", sci: "Sphenodon punctatus", level: "hard" },
  { slug: "frilled-lizard", name: "Frilled Lizard", sci: "Chlamydosaurus kingii", level: "hard" },
  { slug: "thorny-devil", name: "Thorny Devil", sci: "Moloch horridus", level: "hard" },
  { slug: "marine-iguana", name: "Marine Iguana", sci: "Amblyrhynchus cristatus", level: "hard" },
  { slug: "basilisk-lizard", name: "Basilisk Lizard", sci: "Basiliscus plumifrons", level: "hard" },
  { slug: "spectacled-caiman", name: "Spectacled Caiman", sci: "Caiman crocodilus", level: "hard" },
  { slug: "green-tree-python", name: "Green Tree Python", sci: "Morelia viridis", level: "hard" },
  { slug: "hognose-snake", name: "Hognose Snake", sci: "Heterodon platirhinos", level: "hard" },
  { slug: "slow-worm", name: "Slow Worm", sci: "Anguis fragilis", level: "hard" },
  { slug: "leatherback-sea-turtle", name: "Leatherback Sea Turtle", sci: "Dermochelys coriacea", level: "hard" },
  { slug: "mata-mata-turtle", name: "Mata Mata Turtle", sci: "Chelus fimbriata", level: "hard" },
  { slug: "panther-chameleon", name: "Panther Chameleon", sci: "Furcifer pardalis", level: "hard" },
  { slug: "draco-lizard", name: "Draco Lizard", sci: "Draco volans", level: "hard" },

  // IMPOSSIBLE (17) — obscure even to enthusiasts
  { slug: "round-island-boa", name: "Round Island Boa", sci: "Casarea dussumieri", level: "impossible" },
  { slug: "uracoan-rattlesnake", name: "Uracoan Rattlesnake", sci: "Crotalus vegrandis", level: "impossible" },
  { slug: "roti-island-snake-necked-turtle", name: "Roti Island Snake-necked Turtle", sci: "Chelodina mccordi", level: "impossible" },
  { slug: "armadillo-girdled-lizard", name: "Armadillo Girdled Lizard", sci: "Ouroborus cataphractus", level: "impossible" },
  { slug: "jacksons-chameleon", name: "Jackson's Chameleon", sci: "Trioceros jacksonii", level: "impossible" },
  { slug: "knight-anole", name: "Knight Anole", sci: "Anolis equestris", level: "impossible" },
  { slug: "rhinoceros-viper", name: "Rhinoceros Viper", sci: "Bitis nasicornis", level: "impossible" },
  { slug: "satanic-leaf-tailed-gecko", name: "Satanic Leaf-tailed Gecko", sci: "Uroplatus phantasticus", level: "impossible" },
  { slug: "pinocchio-lizard", name: "Pinocchio Lizard", sci: "Anolis proboscis", level: "impossible" },
  { slug: "prehensile-tailed-skink", name: "Prehensile-tailed Skink", sci: "Corucia zebrata", level: "impossible" },
  { slug: "big-headed-turtle", name: "Big-headed Turtle", sci: "Platysternon megacephalum", level: "impossible" },
  { slug: "spider-tortoise", name: "Spider Tortoise", sci: "Pyxis arachnoides", level: "impossible" },
  { slug: "egyptian-tortoise", name: "Egyptian Tortoise", sci: "Testudo kleinmanni", level: "impossible" },
  { slug: "blue-coral-snake", name: "Blue Malaysian Coral Snake", sci: "Calliophis bivirgatus", level: "impossible" },
  { slug: "rhinoceros-ratsnake", name: "Rhinoceros Ratsnake", sci: "Gonyosoma boulengeri", level: "impossible" },
  { slug: "solomon-islands-ground-boa", name: "Solomon Islands Ground Boa", sci: "Candoia paulsoni", level: "impossible" },
  { slug: "feas-viper", name: "Fea's Viper", sci: "Azemiops feae", level: "impossible" },
];
