export const REPTILES_E24_FACTS = {
  "king-cobra": "The king cobra is the world's longest venomous snake.",
  "green-anaconda": "Green anacondas are the heaviest snakes in the world.",
  "rattlesnake": "Rattlesnakes shake their tails to warn off predators.",
  "komodo-dragon": "Komodo dragons are the largest living lizard species.",
  "nile-crocodile": "Nile crocodiles can live over 70 years in the wild.",
  "american-alligator": "American alligators can regrow lost teeth repeatedly.",
  "galapagos-tortoise": "Galapagos tortoises can live more than 100 years.",
  "veiled-chameleon": "Veiled chameleons use a helmet-like casque to collect rain.",
  "green-iguana": "Green iguanas can drop their tails to escape predators.",
  "burmese-python": "Burmese pythons can grow to nearly 19 feet long.",
  "leopard-gecko": "Leopard geckos have movable eyelids, unlike most geckos.",
  "green-sea-turtle": "Green sea turtles are named for their greenish body fat.",
  "boa-constrictor": "Boa constrictors kill prey by squeezing, not venom.",
  "garter-snake": "Garter snakes are among the most common snakes in North America.",
  "bearded-dragon": "Bearded dragons puff their throat spikes when threatened.",
  "monitor-lizard": "Monitor lizards have forked tongues, just like snakes.",
  "corn-snake": "Corn snakes are among the most popular pet snakes worldwide.",
  "box-turtle": "Box turtles can fully close their shell for protection.",

  "black-mamba": "Black mambas are named for their ink-black mouth interior.",
  "copperhead": "Copperheads freeze instead of fleeing when threatened.",
  "cottonmouth": "Cottonmouths show a white mouth lining as a warning.",
  "gharial": "Gharials use their thin snout to snap up fish.",
  "american-crocodile": "American crocodiles can tolerate saltwater habitats.",
  "painted-turtle": "Painted turtles are North America's most widespread turtle.",
  "snapping-turtle": "Snapping turtles have a sharp beak instead of teeth.",
  "ball-python": "Ball pythons curl into a ball when they feel threatened.",
  "milk-snake": "Milk snakes mimic venomous coral snakes for protection.",
  "gila-monster": "Gila monsters are one of few venomous lizards on Earth.",
  "horned-lizard": "Horned lizards can squirt blood from their eyes at threats.",
  "chinese-water-dragon": "Chinese water dragons can hold their breath underwater.",
  "tokay-gecko": "Tokay geckos are named for their loud 'to-kay' call.",
  "red-eared-slider": "Red-eared sliders are named for the red stripe by their ear.",
  "diamondback-terrapin": "Diamondback terrapins live in coastal salt marshes.",
  "grass-snake": "Grass snakes often play dead when threatened.",
  "rat-snake": "Rat snakes are skilled climbers that raid bird nests.",
  "blue-tongued-skink": "Blue-tongued skinks flash their tongue to scare predators.",

  "gaboon-viper": "Gaboon vipers have the longest fangs of any snake.",
  "saw-scaled-viper": "Saw-scaled vipers rub their scales together to hiss.",
  "bushmaster": "The bushmaster is the largest pit viper in the Americas.",
  "eyelash-viper": "Eyelash vipers get their name from scales above their eyes.",
  "vine-snake": "Vine snakes have horizontal pupils for sharper depth vision.",
  "tuatara": "Tuataras have a light-sensing third eye atop their head.",
  "frilled-lizard": "Frilled lizards fan out their neck frill to look bigger.",
  "thorny-devil": "Thorny devils drink water through channels in their skin.",
  "marine-iguana": "Marine iguanas are the only lizards that forage in the sea.",
  "basilisk-lizard": "Basilisk lizards can run short distances across water.",
  "spectacled-caiman": "Spectacled caimans are named for a bony ridge between their eyes.",
  "green-tree-python": "Green tree pythons hatch bright yellow or red, not green.",
  "hognose-snake": "Hognose snakes play dead and release a foul smell.",
  "slow-worm": "The slow worm is a legless lizard, not a true snake.",
  "leatherback-sea-turtle": "Leatherback sea turtles lack a hard, bony shell.",
  "mata-mata-turtle": "Mata mata turtles ambush prey with sudden mouth suction.",
  "panther-chameleon": "Panther chameleons can flash bright colors when excited.",
  "draco-lizard": "Draco lizards glide between trees on rib-supported skin.",

  "round-island-boa": "The round island boa lives only near Mauritius.",
  "uracoan-rattlesnake": "The Uracoan rattlesnake is found only in one Venezuelan region.",
  "roti-island-snake-necked-turtle": "This turtle's neck can be as long as its own shell.",
  "armadillo-girdled-lizard": "Armadillo girdled lizards curl into a ball like an armadillo.",
  "jacksons-chameleon": "Male Jackson's chameleons grow three horns like a triceratops.",
  "knight-anole": "The knight anole is Cuba's largest anole lizard species.",
  "rhinoceros-viper": "Rhinoceros vipers have horn-like scales above their nostrils.",
  "satanic-leaf-tailed-gecko": "This gecko's tail is shaped to mimic a dead curled leaf.",
  "pinocchio-lizard": "Male Pinocchio lizards flourish their long snout to court females.",
  "prehensile-tailed-skink": "This skink grips branches with its tail like a fifth limb.",
  "big-headed-turtle": "The big-headed turtle can climb trees with its strong claws.",
  "spider-tortoise": "Spider tortoises have web-like patterns on their shell.",
  "egyptian-tortoise": "The Egyptian tortoise is one of the smallest tortoise species.",
  "blue-coral-snake": "The blue Malaysian coral snake has iridescent blue-black scales.",
  "rhinoceros-ratsnake": "The rhinoceros ratsnake has a horn-like scale on its nose.",
  "solomon-islands-ground-boa": "Solomon Islands ground boas give birth to live young.",
  "feas-viper": "Fea's viper belongs to its own primitive pit-viper subfamily.",
};
