export const RIVERS_E20_FACTS = {
  "nile-river": "The Nile is widely considered the longest river on Earth.",
  "amazon-river": "The Amazon carries more water than the next seven rivers combined.",
  "mississippi-river": "The Mississippi drains all or part of 31 U.S. states.",
  "yangtze-river": "The Yangtze is Asia's longest river.",
  "danube-river": "The Danube flows through more countries than any other river.",
  "rhine-river": "The Rhine is one of Europe's busiest shipping routes.",
  "thames-river": "The River Thames flows right through the heart of London.",
  "seine-river": "The Seine splits Paris into its Left and Right Banks.",
  "ganges-river": "The Ganges is considered sacred by hundreds of millions of Hindus.",
  "volga-river": "The Volga is the longest river in Europe.",
  "congo-river": "The Congo is the world's deepest river, over 220 meters down.",
  "niger-river": "The Niger River bends into a giant curve called the Niger Bend.",
  "mekong-river": "The Mekong flows through six different countries.",
  "euphrates-river": "The Euphrates helped cradle some of humanity's first cities.",
  "zambezi-river": "The Zambezi plunges over Victoria Falls on its way to the sea.",
  "indus-river": "The Indus gave ancient India its very name.",
  "tigris-river": "The Tigris once watered the ancient city of Nineveh.",
  "murray-river": "The Murray is Australia's longest river.",
  "colorado-river": "The Colorado River carved out the Grand Canyon.",
  "yellow-river": "The Yellow River gets its color from carried loess silt.",
  "orinoco-river": "The Orinoco forms part of the Venezuela-Colombia border.",
  "parana-river": "The Parana is South America's second-longest river.",
  "loire-river": "The Loire is France's longest river.",
  "po-river": "The Po is Italy's longest river.",
  "elbe-river": "The Elbe rises in the Czech mountains before reaching Germany.",
  "vistula-river": "The Vistula is Poland's longest river.",
  "dnieper-river": "The Dnieper is one of the longest rivers in Europe.",
  "don-river": "The Don was long seen as a boundary between Europe and Asia.",
  "brahmaputra-river": "The Brahmaputra is one of the few rivers named for a male god.",
  "irrawaddy-river": "The Irrawaddy is Myanmar's most important commercial river.",
  "chao-phraya-river": "The Chao Phraya flows straight through Bangkok.",
  "saint-lawrence-river": "The Saint Lawrence links the Great Lakes to the Atlantic.",
  "rio-grande-river": "The Rio Grande forms much of the US-Mexico border.",
  "douro-river": "The Douro Valley's terraced vineyards line this river's banks.",
  "tagus-river": "The Tagus is the longest river on the Iberian Peninsula.",
  "limpopo-river": "The Limpopo was nicknamed the Great Grey-Green Greasy River.",
  "ob-river": "The Ob has one of the largest drainage basins on Earth.",
  "mackenzie-river": "The Mackenzie is Canada's longest river.",
  "shannon-river": "The Shannon is the longest river in Ireland or Britain.",
  "severn-river": "The Severn is the longest river in Great Britain.",
  "rhone-river": "The Rhone begins as glacial meltwater in the Alps.",
  "ebro-river": "The Ebro is Spain's largest river by volume.",
  "vltava-river": "The Vltava flows straight through the city of Prague.",
  "tiber-river": "The Tiber runs through the heart of ancient Rome.",
  "sao-francisco-river": "The Sao Francisco is known as the River of National Unity.",
  "okavango-river": "The Okavango never reaches the sea, ending in a desert delta.",
  "senegal-river": "The Senegal River touches four West African countries.",
  "gambia-river": "The Gambia River shapes the entire country's narrow borders.",
  "volta-river": "The Volta feeds one of the world's largest man-made lakes.",
  "han-river": "The Han River runs through the middle of Seoul.",
  "red-river-vietnam": "The Red River gets its name from reddish silt it carries.",
  "ural-river": "The Ural River is often called a natural Europe-Asia boundary.",
  "selenge-river": "The Selenge feeds the largest volume of water into Lake Baikal.",
  "godavari-river": "The Godavari is called the Ganges of the South.",
  "yenisei-river": "The Yenisei carries the most water of any Russian river.",
  "guadalquivir-river": "The Guadalquivir is the only major navigable river in Spain.",
  "weser-river": "The Weser forms from two rivers meeting at a town called Munden.",
  "meuse-river": "The Meuse flows through three different countries.",
  "drava-river": "The Drava flows for over 700 kilometers before joining the Danube.",
  "sava-river": "The Sava is the largest tributary of the Danube by volume.",
  "tisza-river": "The Tisza is the second-longest river in Hungary's basin.",
  "marne-river": "The Marne gave its name to a decisive World War One battle.",
  "orange-river": "The Orange is the longest river in South Africa.",
  "chindwin-river": "The Chindwin is the largest tributary of the Irrawaddy.",
  "magdalena-river": "The Magdalena is Colombia's principal river.",
  "berbice-river": "The Berbice River runs entirely within Guyana's borders.",
  "kagera-river": "The Kagera is considered one of the most remote sources of the Nile.",
  "ottawa-river": "The Ottawa River forms much of the Ontario-Quebec border.",
  "narmada-river": "The Narmada is one of the few major Indian rivers flowing west.",
  "amur-river": "The Amur forms a long natural border between two countries.",
  "trent-river": "The Trent is one of the longest rivers in England.",
};
