export const ROADSIGNS_E82_FACTS = {
  stop: "Its eight-sided shape is unique among common road signs.",
  yield: "Its downward triangle needs no words to work worldwide.",
  "no-entry": "One of the few signs with no icon, just a plain bar.",
  "pedestrian-crossing": "Warns drivers that a marked crosswalk lies ahead.",
  "speed-limit": "One of the most common traffic sign designs in the world.",
  "one-way": "A single black arrow shows traffic flows one direction only.",
  "no-parking": "A red circle-slash over a P universally means not allowed.",
  "railroad-crossing": "Its X shape is called a 'crossbuck' by railway engineers.",
  "traffic-signal-ahead": "Warns drivers of a signal they may not yet be able to see.",
  "school-crossing": "Speed limits often drop automatically near this sign.",
  "no-u-turn": "A curved arrow with a slash bans turning back the way you came.",
  hospital: "The blue H sign points drivers toward emergency care.",
  roundabout: "Its circular arrows show the mandatory direction of flow.",
  "no-overtaking": "Two vehicle shapes side by side mean passing is forbidden.",
  "speed-bump": "Forces drivers to slow down or risk jolting their vehicle.",
  "handicap-parking": "The wheelchair symbol was designed by a student in 1968.",
  "gas-station": "A single pump icon needs no translation in any country.",
  "dead-end": "Warns drivers before they reach a road with no through exit.",
  merge: "Shows two lanes narrowing into a single lane ahead.",
  "slippery-road": "Warns of reduced tire grip, often near water or ice.",
  "two-way-traffic": "Marks a road where opposing traffic shares one lane.",
  "wrong-way": "Faces oncoming wrong-way drivers to alert them instantly.",
  "no-trucks": "A truck silhouette with a slash bans heavy vehicles here.",
  "bike-lane": "Marks a lane reserved specifically for cyclists.",
  "height-restriction": "Warns of a clearance lower than many trucks and buses.",
  "deer-crossing": "Deer-vehicle collisions spike sharply during autumn rut.",
  "curve-ahead": "A curved arrow warns of a bend before you can see it.",
  "divided-highway": "Marks where a road splits into two separate carriageways.",
  "no-bicycles": "A bicycle with a slash bans cyclists from this road.",
  "steep-hill": "Shows the road's grade as a percentage, not degrees.",
  "winding-road": "Warns of several curves in a row, not just a single bend.",
  "no-left-turn": "An arrow with a slash bans turning left at this point.",
  "keep-right": "A round blue arrow makes going right mandatory, not optional.",
  parking: "A simple letter P marks a legal parking area.",
  "construction-zone": "Often paired with a lower temporary speed limit.",
  "rest-area": "A picnic-table icon marks facilities for a driving break.",
  "falling-rocks": "Common on roads cut directly through mountainsides.",
  "minimum-speed": "Sets a speed floor, mostly used on fast highway lanes.",
  "weight-limit": "Protects bridges and pavement from overloaded vehicles.",
  airport: "Warns drivers that a runway or flight path is nearby.",
  "toll-road": "Marks a road section where payment is required ahead.",
  "icy-road": "A snowflake icon warns drivers of possible ice or frost.",
  "cattle-crossing": "Common on rural roads where livestock roam freely.",
  "no-horn": "Bans horn use, common near hospitals and schools.",
  "narrow-bridge": "Warns the bridge ahead is narrower than the road itself.",
  "camping-area": "A tent icon marks designated campsites nearby.",
  "emergency-stopping-only": "Reserved for breakdowns, not routine parking.",
  "no-stopping": "Stricter than no-parking — even brief stops are banned.",
  "no-pedestrians": "Common on highways where walking is dangerous.",
  "steep-descent": "Warns of a downhill grade, the mirror of the uphill sign.",
  "road-narrows": "Warns the road ahead loses width on both sides at once.",
  "give-way-to-oncoming-traffic": "Used on narrow roads where only one car fits at a time.",
  "kangaroo-crossing": "A distinctly Australian sign, rare outside that continent.",
  "moose-crossing": "Common across Canada and Scandinavia's northern forests.",
  "avalanche-zone": "Found on mountain roads prone to sudden snow slides.",
  "falling-ice": "Warns of ice falling from cliffs, bridges, or tunnels.",
  ford: "Marks a spot where a road dips through shallow water.",
  "loose-gravel": "Warns tires may lose grip on an unpaved surface ahead.",
  "low-flying-aircraft": "Placed near airfields where planes pass close to roads.",
  "zebra-crossing": "Named for its bold black-and-white stripe pattern.",
  "toad-crossing": "Found in parts of Europe during spring breeding migration.",
  "concealed-entrance": "Warns of a hidden driveway or side road ahead.",
  "adverse-camber": "Warns the road surface tilts the wrong way in a curve.",
  "wombat-crossing": "A quirky Australian sign for a burrowing marsupial.",
  "cyclone-shelter": "Common in tropical regions prone to cyclone landfall.",
  quicksand: "A rare sign found near tidal flats or riverbanks.",
  "unmarked-crossroads": "Warns of an intersection with no priority signs at all.",
  crosswind: "Warns drivers on exposed bridges or open flat plains.",
  "camel-crossing": "Found in desert regions like parts of the Middle East.",
  "beware-of-frogs": "Placed where frogs cross roads during breeding season.",
};

export default ROADSIGNS_E82_FACTS;
