export const ROADSIGNS_E82 = [
  // EASY (18) — near-universal, ~90%+ recognize on sight
  { slug: "stop", name: "Stop", wiki: "Stop sign", level: "easy" },
  { slug: "yield", name: "Yield", wiki: "Yield sign", level: "easy" },
  { slug: "no-entry", name: "No Entry", wiki: "No entry sign", level: "easy" },
  { slug: "pedestrian-crossing", name: "Pedestrian Crossing", wiki: "Pedestrian crossing", level: "easy" },
  { slug: "speed-limit", name: "Speed Limit", wiki: "Speed limit sign", level: "easy" },
  { slug: "one-way", name: "One Way", wiki: "One-way traffic", level: "easy" },
  { slug: "no-parking", name: "No Parking", wiki: "Parking violation", level: "easy" },
  { slug: "railroad-crossing", name: "Railroad Crossing", wiki: "Level crossing", level: "easy" },
  { slug: "traffic-signal-ahead", name: "Traffic Signal Ahead", wiki: "Traffic light", level: "easy" },
  { slug: "school-crossing", name: "School Crossing", wiki: "School zone", level: "easy" },
  { slug: "no-u-turn", name: "No U-Turn", wiki: "U-turn", level: "easy" },
  { slug: "hospital", name: "Hospital", wiki: "Hospital", level: "easy" },
  { slug: "roundabout", name: "Roundabout", wiki: "Roundabout", level: "easy" },
  { slug: "no-overtaking", name: "No Overtaking", wiki: "Overtaking", level: "easy" },
  { slug: "speed-bump", name: "Speed Bump", wiki: "Speed bump", level: "easy" },
  { slug: "handicap-parking", name: "Disabled Parking", wiki: "Disabled parking permit", level: "easy" },
  { slug: "gas-station", name: "Gas Station", wiki: "Filling station", level: "easy" },
  { slug: "dead-end", name: "Dead End", wiki: "Dead end (street)", level: "easy" },

  // MEDIUM (18) — most drivers have seen, not all identify instantly
  { slug: "merge", name: "Merge", wiki: "Merge (traffic)", level: "medium" },
  { slug: "slippery-road", name: "Slippery Road", wiki: "Road slipperiness", level: "medium" },
  { slug: "two-way-traffic", name: "Two-Way Traffic", wiki: "Two-way traffic", level: "medium" },
  { slug: "wrong-way", name: "Wrong Way", wiki: "Wrong-way driving", level: "medium" },
  { slug: "no-trucks", name: "No Trucks", wiki: "Truck", level: "medium" },
  { slug: "bike-lane", name: "Bike Lane", wiki: "Bicycle lane", level: "medium" },
  { slug: "height-restriction", name: "Height Restriction", wiki: "Height restriction", level: "medium" },
  { slug: "deer-crossing", name: "Deer Crossing", wiki: "Wildlife crossing", level: "medium" },
  { slug: "curve-ahead", name: "Curve Ahead", wiki: "Traffic sign", level: "medium" },
  { slug: "divided-highway", name: "Divided Highway", wiki: "Dual carriageway", level: "medium" },
  { slug: "no-bicycles", name: "No Bicycles", wiki: "Bicycle", level: "medium" },
  { slug: "steep-hill", name: "Steep Hill", wiki: "Grade (slope)", level: "medium" },
  { slug: "winding-road", name: "Winding Road", wiki: "Traffic sign", level: "medium" },
  { slug: "no-left-turn", name: "No Left Turn", wiki: "Traffic sign", level: "medium" },
  { slug: "keep-right", name: "Keep Right", wiki: "Traffic sign", level: "medium" },
  { slug: "parking", name: "Parking", wiki: "Parking", level: "medium" },
  { slug: "construction-zone", name: "Road Work Ahead", wiki: "Roadworks", level: "medium" },
  { slug: "rest-area", name: "Rest Area", wiki: "Rest area", level: "medium" },

  // HARD (16) — enthusiasts/frequent drivers recognize, casual public often doesn't
  { slug: "falling-rocks", name: "Falling Rocks", wiki: "Rockfall", level: "hard" },
  { slug: "minimum-speed", name: "Minimum Speed", wiki: "Minimum speed limit", level: "hard" },
  { slug: "weight-limit", name: "Weight Limit", wiki: "Vehicle weight", level: "hard" },
  { slug: "airport", name: "Airport", wiki: "Airport", level: "hard" },
  { slug: "toll-road", name: "Toll Road", wiki: "Toll road", level: "hard" },
  { slug: "icy-road", name: "Icy Road", wiki: "Black ice", level: "hard" },
  { slug: "cattle-crossing", name: "Cattle Crossing", wiki: "Cattle grid", level: "hard" },
  { slug: "no-horn", name: "No Horn", wiki: "Vehicle horn", level: "hard" },
  { slug: "narrow-bridge", name: "Narrow Bridge", wiki: "Bridge", level: "hard" },
  { slug: "camping-area", name: "Camping Area", wiki: "Campsite", level: "hard" },
  { slug: "emergency-stopping-only", name: "Emergency Stopping Only", wiki: "Emergency vehicle", level: "hard" },
  { slug: "no-stopping", name: "No Stopping", wiki: "No stopping", level: "hard" },
  { slug: "no-pedestrians", name: "No Pedestrians", wiki: "Pedestrian", level: "hard" },
  { slug: "steep-descent", name: "Steep Descent", wiki: "Grade (slope)", level: "hard" },
  { slug: "road-narrows", name: "Road Narrows", wiki: "Traffic sign", level: "hard" },
  { slug: "give-way-to-oncoming-traffic", name: "Give Way to Oncoming Traffic", wiki: "Passing loop", level: "hard" },

  // IMPOSSIBLE (18) — genuinely obscure, regional, or novelty signs
  { slug: "kangaroo-crossing", name: "Kangaroo Crossing", wiki: "Wildlife crossing", level: "impossible" },
  { slug: "moose-crossing", name: "Moose Crossing", wiki: "Wildlife crossing", level: "impossible" },
  { slug: "avalanche-zone", name: "Avalanche Zone", wiki: "Avalanche", level: "impossible" },
  { slug: "falling-ice", name: "Falling Ice", wiki: "Icicle", level: "impossible" },
  { slug: "ford", name: "Ford (River Crossing)", wiki: "Ford (crossing)", level: "impossible" },
  { slug: "loose-gravel", name: "Loose Gravel", wiki: "Gravel road", level: "impossible" },
  { slug: "low-flying-aircraft", name: "Low-Flying Aircraft", wiki: "Low-altitude flight", level: "impossible" },
  { slug: "zebra-crossing", name: "Zebra Crossing", wiki: "Zebra crossing", level: "impossible" },
  { slug: "toad-crossing", name: "Toad Crossing", wiki: "Toad", level: "impossible" },
  { slug: "concealed-entrance", name: "Concealed Entrance", wiki: "Traffic sign", level: "impossible" },
  { slug: "adverse-camber", name: "Adverse Camber", wiki: "Camber angle", level: "impossible" },
  { slug: "wombat-crossing", name: "Wombat Crossing", wiki: "Wombat", level: "impossible" },
  { slug: "cyclone-shelter", name: "Cyclone Shelter", wiki: "Storm shelter", level: "impossible" },
  { slug: "quicksand", name: "Quicksand", wiki: "Quicksand", level: "impossible" },
  { slug: "unmarked-crossroads", name: "Unmarked Crossroads", wiki: "Uncontrolled intersection", level: "impossible" },
  { slug: "crosswind", name: "Crosswind", wiki: "Crosswind", level: "impossible" },
  { slug: "camel-crossing", name: "Camel Crossing", wiki: "Wildlife crossing", level: "impossible" },
  { slug: "beware-of-frogs", name: "Frog Crossing", wiki: "Frog", level: "impossible" },
];

export default ROADSIGNS_E82;
