export const SEA_CREATURES_E46_FACTS = {
  // EASY
  "great-white-shark": "Can detect prey blood at astonishingly low concentrations.",
  "bottlenose-dolphin": "Each dolphin has a signature whistle that acts like a name.",
  "blue-whale": "Its heart alone can weigh as much as a small car.",
  "clownfish": "All clownfish are born male; the dominant one turns female.",
  "orca": "Orcas are actually the largest member of the dolphin family.",
  "green-sea-turtle": "Named for the green fat under its shell, not its skin.",
  "common-octopus": "Has three hearts and blue, copper-based blood.",
  "starfish": "Can regenerate a lost arm, sometimes a whole new body.",
  "seahorse": "Male seahorses carry and give birth to the babies.",
  "moon-jellyfish": "Its bell-shaped body is about 95 percent water.",
  "great-hammerhead-shark": "Uses its wide head to pin down stingrays before eating.",
  "california-sea-lion": "The US Navy trains them to locate objects underwater.",
  "walrus": "Uses its tusks to haul its heavy body onto ice floes.",
  "humpback-whale": "Males sing complex songs that can last over 20 minutes.",
  "american-lobster": "Some wild lobsters are estimated to live over 100 years.",
  "blue-crab": "Its scientific name roughly means 'beautiful savory swimmer'.",
  "porcupinefish": "Inflates by swallowing water, erecting its sharp spines.",
  "sea-otter": "Holds hands with other otters while sleeping so they don't drift.",

  // MEDIUM
  "giant-manta-ray": "Has the largest brain-to-body ratio of any fish.",
  "southern-stingray": "Buries in sand with only its eyes and spiracles showing.",
  "beluga-whale": "Can change the shape of its melon to make different sounds.",
  "narwhal": "Its famous 'tusk' is really a long, spiral canine tooth.",
  "west-indian-manatee": "Its closest living relatives are elephants, not dolphins.",
  "green-moray-eel": "Its green look comes from yellow mucus over blue-gray skin.",
  "giant-pacific-octopus": "Its arm span can stretch to roughly 30 feet across.",
  "leatherback-sea-turtle": "The only sea turtle with a leathery shell, not a hard one.",
  "whale-shark": "The largest fish in the world, yet it feeds on plankton.",
  "tiger-shark": "Nicknamed the 'garbage can of the sea' for eating anything.",
  "great-barracuda": "Can reach burst speeds of about 36 mph while hunting.",
  "chambered-nautilus": "Moves by jet propulsion and has up to 90 tentacles.",
  "red-lionfish": "Its venomous spines are for defense, not for hunting.",
  "purple-sea-urchin": "Its five-toothed mouth is called Aristotle's lantern.",
  "common-cuttlefish": "Called the 'chameleon of the sea' for rapid color shifts.",
  "leafy-seadragon": "Its leaf-like fronds are camouflage, not swimming aids.",
  "humpback-anglerfish": "Females lure prey with a glowing rod above their head.",
  "giant-sea-cucumber": "Can expel its own organs to startle off predators.",

  // HARD
  "smalltooth-sawfish": "Slashes schooling fish with its tooth-lined, blade-like snout.",
  "atlantic-flying-fish": "Can glide over 650 feet on wing-like pectoral fins.",
  "queen-angelfish": "Named for the blue 'crown' spot ringed on its forehead.",
  "vaquita": "World's most endangered marine mammal, fewer than 10 remain.",
  "ghost-shark-chimaera": "A shark relative that split off over 400 million years ago.",
  "mantis-shrimp": "Its punch strikes with the force of a .22-caliber bullet.",
  "goblin-shark": "Its jaw can shoot forward to snatch prey, like an alien.",
  "frilled-shark": "Has about 300 trident-shaped teeth in roughly 25 rows.",
  "blobfish": "Its 'blobby' look only appears once out of deep-sea pressure.",
  "giant-squid": "Has eyes up to 10 inches wide, among the largest of any animal.",
  "colossal-squid": "Has swiveling hooks on its tentacles, unlike any other squid.",
  "yeti-crab": "Grows bristly 'hair' on its claws to farm bacteria for food.",
  "vampire-squid": "Despite its name, it feeds on drifting marine debris, not blood.",
  "japanese-spider-crab": "Has the largest leg span of any arthropod, up to 12 feet.",
  "coelacanth": "Thought extinct with the dinosaurs until found alive in 1938.",
  "giant-oarfish": "World's longest bony fish, documented up to 26 feet long.",
  "dumbo-octopus": "Named for its ear-like fins, like Disney's flying elephant.",
  "fangtooth-fish": "Has the largest teeth relative to body size of any fish.",

  // IMPOSSIBLE
  "sea-pig": "A deep-sea cucumber that 'walks' the seafloor on tube feet.",
  "pacific-barreleye-fish": "Its see-through head lets tubular eyes gaze straight up.",
  "sarcastic-fringehead": "Opens its huge mouth wide to wrestle rival fringeheads.",
  "giant-isopod": "Can survive more than five years without eating.",
  "hoff-crab": "Named for its hairy chest, after actor David Hasselhoff.",
  "bloody-belly-comb-jelly": "Its red gut hides glowing prey from would-be predators.",
  "faceless-cusk": "Has no visible eyes; its mouth sits underneath its head.",
  "zombie-worm": "Has no mouth or gut, yet dissolves whale bone with acid.",
  "sloanes-viperfish": "Its fang-like teeth are too long to fit inside its mouth.",
  "silver-hatchetfish": "Its mirrored sides help it vanish in dim mid-ocean light.",
  "stoplight-loosejaw": "Makes red light that most deep-sea animals can't even see.",
  "pink-see-through-fantasia": "A see-through sea cucumber that swims with a webbed hood.",
  "blackfin-icefish": "Its blood is clear; it has no red blood cells or hemoglobin.",
  "mariana-snailfish": "Found living over 26,000 feet deep in the Mariana Trench.",
  "giant-tube-worm": "Has no mouth or gut; bacteria inside make its food.",
  "antarctic-sea-spider": "Breathes through its legs; it has no lungs or gills.",
  "glass-squid": "Its transparent body helps hide it from predators below.",
};
