export const SKYSCRAPERS_E58_FACTS = {
  // EASY
  "burj-khalifa": "The world's tallest building, standing over 828 meters.",
  "empire-state-building": "Held the title of world's tallest building for nearly 40 years.",
  "one-world-trade-center": "Its spire rises to a symbolic 1,776 feet.",
  "shanghai-tower": "Its twisting form reduces wind loads by 24%.",
  "petronas-towers": "Still the tallest twin towers in the world.",
  "taipei-101": "Designed to withstand typhoons and earthquakes.",
  "willis-tower": "Known as the Sears Tower until 2009.",
  "chrysler-building": "Its stainless steel spire was a secret until unveiling.",
  "the-shard": "Its glass facade is meant to evoke a shard of glass.",
  "marina-bay-sands": "Home to the world's largest rooftop infinity pool.",
  "the-gherkin": "Its rounded shape actually reduces wind deflection.",
  "shanghai-world-financial-center": "Nicknamed the 'bottle opener' for its trapezoidal hole.",
  "international-commerce-centre": "Hong Kong's tallest building.",
  "lotte-world-tower": "South Korea's tallest building.",
  "john-hancock-center": "Its X-braced frame is visible on the exterior.",
  "jin-mao-tower": "Its design blends art deco with pagoda-inspired tiers.",
  "flatiron-building": "Named for its distinctive triangular shape.",
  "bank-of-china-tower": "Its angular, prism-like form was designed by I. M. Pei.",

  // MEDIUM
  "landmark-81": "Vietnam's tallest building, shaped like bundled bamboo.",
  "central-park-tower": "The tallest residential-only building in the world.",
  "one-vanderbilt": "Rises beside Grand Central Terminal in Manhattan.",
  "thirty-hudson-yards": "Has an outdoor observation deck called the Edge.",
  "ping-an-finance-centre": "One of Shenzhen's tallest skyscrapers.",
  "citic-tower": "Also known by its nickname, China Zun.",
  "guangzhou-ctf-finance-centre": "Houses offices, a hotel, and residences.",
  "tianjin-ctf-finance-centre": "One of the tallest buildings in northern China.",
  "emirates-towers": "Two triangular towers linked by a boulevard.",
  "princess-tower": "Once the tallest residential building in the world.",
  "eureka-tower": "Its gold trim honors the Eureka Stockade gold rush.",
  "q1-tower": "Was the tallest residential tower in the world at completion.",
  "federation-tower": "Part of the Moscow International Business Center.",
  "mercury-city-tower": "Its bronze-tinted glass changes with the light.",
  "aon-center-chicago": "One of the tallest buildings in Chicago.",
  "trump-tower-chicago": "Overlooks the Chicago River from downtown.",
  "turning-torso": "Twists a full 90 degrees from base to top.",

  // HARD
  "suzhou-ifs": "One of the tallest buildings in Jiangsu province.",
  "wuhan-center-tower": "A supertall skyscraper in central China.",
  "nanjing-greenland-financial-center": "Also known as Zifeng Tower.",
  "kk100": "Once the tallest building in Shenzhen.",
  "the-torch-dubai": "A twisting residential tower in Dubai Marina.",
  "almas-tower": "Home to the Dubai Diamond Exchange.",
  "gate-of-the-orient": "Nicknamed the 'big pants' for its unusual shape.",
  "absolute-world": "Nicknamed the 'Marilyn Monroe' towers for their curves.",
  "cayan-tower": "Twists 90 degrees over its full height.",
  "thirty-park-place": "A supertall residential tower near the WTC site.",
  "thirty-five-hudson-yards": "Combines a hotel, offices, and condos.",
  "salesforce-tower": "The tallest building in San Francisco.",
  "wilshire-grand-center": "The tallest building on the U.S. West Coast.",
  "comcast-technology-center": "Philadelphia's tallest building.",
  "hearst-tower": "A modern tower built atop a historic 1928 base.",
  "torre-reforma": "One of Mexico City's tallest, built to withstand earthquakes.",
  "gran-torre-santiago": "The tallest building in South America.",
  "merdeka-118": "The world's second-tallest building.",

  // IMPOSSIBLE
  "leadenhall-building": "Nicknamed the 'Cheesegrater' for its tapered shape.",
  "kingdom-centre": "Its distinctive top has an inverted parabolic arch.",
  "burj-rafal": "A luxury hotel tower in Riyadh.",
  "al-hamra-tower": "Kuwait's tallest building, with a distinctive twisting shape.",
  "baiyoke-tower-ii": "Once Thailand's tallest building.",
  "one-shenzhen-bay": "Part of a waterfront tower complex in Shenzhen.",
  "wuxi-maoye-city": "A supertall tower in eastern China.",
  "golden-eagle-tiandi": "A mixed-use skyscraper in Nanjing.",
  "chongqing-wfc": "One of the tallest buildings in Chongqing.",
  "iconic-tower-egypt": "Africa's tallest building, near Cairo.",
  "landmark-72": "Once Vietnam's tallest building.",
  "china-resources-headquarters": "Nicknamed 'Spring Bamboo' for its tapered shape.",
  "changsha-ifs-tower-t1": "One of Hunan province's tallest buildings.",
  "shimao-international-plaza": "A supertall tower in central Shanghai.",
  "poly-international-plaza": "A twin-tower complex in Guangzhou.",
};

export default SKYSCRAPERS_E58_FACTS;
