export const SPORTS_MASCOTS_E38_FACTS = {
  "phillie-phanatic": "Designed by the same artist who also helped create Miss Piggy.",
  "gritty": "Debuted in 2018 and instantly became a global internet meme.",
  "san-diego-chicken": "Ted Giannoulas has performed as the Chicken since 1974.",
  "mr-met": "Debuted in 1964, one of the first mascots with a human body.",
  "benny-the-bull": "Mascot since 1969, one of the NBA's longest-serving mascots.",
  "suns-gorilla": "Born in 1980 when a singing-telegram gorilla improvised.",
  "gunnersaurus": "Ozil offered to pay his wages after 2020 layoff news broke.",
  "rocky-nuggets": "A mountain lion mascot known for high-flying dunk stunts.",
  "youppi": "First mascot ever to switch between two major pro leagues.",
  "uga": "The bulldog line began in 1956 and is buried in a mausoleum.",
  "bevo": "Charged toward Georgia's Uga before the 2019 Sugar Bowl.",
  "ralphie": "A live bison has sprinted onto the field before games since 1967.",
  "chief-osceola": "Rides horse Renegade and plants a flaming spear since 1978.",
  "misha-bear": "His giant, tearful farewell closed the 1980 Games ceremony.",
  "sluggerrr": "A lion mascot inducted into the Mascot Hall of Fame.",
  "wally-green-monster": "Named for Fenway's wall; claims he's hidden there since 1947.",
  "fredbird": "Mascot since 1979; entered the Mascot Hall of Fame in 2025.",
  "zakumi": "His name blends South Africa's code 'ZA' and 'kumi' (ten).",

  "blue-colts": "Ranked among the NFL's most-followed mascots on social media.",
  "kc-wolf": "Debuted in 1989 and is known for trampoline backflips.",
  "t-rac": "A raccoon mascot - Tennessee's official state wild animal.",
  "bernie-brewer": "Famous for sliding into a giant beer mug after home runs.",
  "clutch-the-bear": "Performs slam-dunk stunts off a trampoline since 1995.",
  "stuff-magic-dragon": "Named after the 1963 folk song 'Puff, the Magic Dragon.'",
  "jaxson-de-ville": "Known for tightrope walks and rappelling from arena rafters.",
  "lou-seal": "Debuted in 1996 and entered the Mascot Hall of Fame in 2024.",
  "orbit": "A green alien mascot first seen in 1990, revived in 2013.",
  "brutus-buckeye": "Wears an oversized buckeye-nut head; debuted in 1965.",
  "bucky-badger": "Does push-ups counted out after every point Wisconsin scores.",
  "big-al": "An elephant tied to a famous 1930 'elephants are coming' column.",
  "mike-the-tiger": "LSU has both a live tiger and a costumed mascot, both named Mike.",
  "oregon-duck": "Modeled on Donald Duck under a 1947 deal with Walt Disney.",
  "world-cup-willie": "Football's first-ever World Cup mascot, introduced in 1966.",
  "sir-purr": "Has been the Panthers' mascot since the team's first season, 1995.",
  "zabivaka": "His name means 'the one who scores' in Russian.",
  "bing-dwen-dwen": "Its plush toys sold out, with fans queuing hours in 2022.",

  "fred-the-red": "A red devil named for Man United's 'Red Devils' nickname.",
  "hugo-the-hornet": "Followed the Hornets brand to New Orleans, then back in 2014.",
  "slider": "Famous for belly-flopping onto rival dugout roofs since 1990.",
  "dinger": "Hatched from an egg in 1994, inspired by a real 1993 fossil find.",
  "screech": "A green bald eagle who debuted with the team in 2005.",
  "pirate-parrot": "Hatched on April Fools' Day, 1979, inspired by Treasure Island.",
  "billy-the-marlin": "Mascot since the Marlins' inaugural 1993 season.",
  "handsome-dan": "America's first live college mascot, dating to 1889.",
  "testudo": "Students rub its statue's nose for luck before exams.",
  "reveille": "A collie that outranks every cadet in the Corps of Cadets.",
  "traveler": "A white horse ridden by USC's costumed Trojan warrior mascot.",
  "sparky-sun-devil": "Created by a Disney artist; debuted at ASU games in 1951.",
  "cosmo-cougar": "First entered the stadium by parachute back in 1953.",
  "otto-the-orange": "Named in 1990 after 'Opie' was dropped for rhyming with 'dopey.'",
  "stanford-tree": "Won a 1975 mascot contest, beating a manhole and a giant fry.",
  "smokey": "A bluetick coonhound picked by a howling contest in 1953.",
  "wild-wing": "First NHL mascot to descend from the arena rafters.",
  "cocky": "A gamecock mascot with multiple national mascot titles.",

  "rumble-bison": "An American bison mascot known for trampoline dunk stunts.",
  "youdee": "A Fightin' Blue Hen, Delaware's official state bird.",
  "iceburgh": "A king-penguin mascot who debuted for the Penguins in 1992.",
  "goldy-gopher": "A gopher mascot who has performed since 1952.",
  "blitz-seahawks": "A blue-feathered hawk mascot who debuted in 1998.",
  "purdue-pete": "A hard-hat-wearing boilermaker who once wielded a giant mallet.",
  "pat-patriot": "A Minuteman mascot based on the team's original 1961 logo.",
  "cy-cardinal": "Named Cy via a 1954 fan contest, not a real bird.",
  "zampa-the-lion": "Had his head ripped off and drop-kicked by rival mascot Cyril.",
  "cyril-the-swan": "Fined for ripping off a rival mascot's head in 1998.",
  "herky-hawk": "Iowa's hawk mascot has performed since debuting in 1948.",
  "moonchester": "Named after Man City's anthem, 'Blue Moon.'",
  "sebastian-ibis": "An ibis was chosen since the bird is said to survive any storm.",
  "billy-the-badger": "A badger mascot for Fulham, nicknamed 'the Whites.'",
  "berni": "A bear who wears squad number 12, the '12th player.'",
  "sparty": "A muscular Spartan warrior who debuted for Michigan State in 1989.",
  "chirpy-cockerel": "A cockerel mascot taken straight from Tottenham's club crest.",
  "rowdy-utsa": "A roadrunner mascot known for backflips off the arena tunnel.",
};
