export const SPORT_EQUIPMENT_E95_FACTS = {
  "soccer-ball": "A regulation match ball has exactly 32 panels (12 pentagons, 20 hexagons) and must weigh 410-450 grams at kickoff.",
  "basketball-hoop": "The rim sits exactly 10 feet high because inventor James Naismith hung his first peach baskets on a running-track railing that happened to be that height in 1891.",
  "tennis-racket": "Tennis rackets were all wood until graphite composite frames took over by the late 1970s.",
  "boxing-gloves": "Ali and Frazier wore 10-ounce gloves in their legendary 1975 'Thrilla in Manila' fight.",
  "golf-club": "Early golf clubheads were carved from persimmon wood because the hard rubber 'gutty' balls introduced in 1848 shattered anything softer.",
  "baseball-bat": "MLB bats must be a single piece of solid wood no longer than 42 inches, though most players actually swing one closer to 34 inches.",
  "american-football-ball": "The ball is nicknamed a 'pigskin' because early versions used an inflated pig's bladder inside — not actual pigskin leather.",
  volleyball: "Inventor William Morgan set volleyball's original net at just 6 feet 6 inches in 1895 — far lower than today's official height.",
  "swimming-goggles": "Goggles weren't officially allowed in Olympic swimming competition until the 1976 Montreal Games.",
  "table-tennis-paddle": "The pimpled rubber paddle surface was invented in 1902 by Englishman E.C. Goode specifically to put more spin on the ball.",
  dartboard: "The numbers 1-20 aren't arranged in order around the board — they're deliberately scrambled so one bad throw next to a big number costs you dearly.",
  skateboard: "Skateboarding began as 'sidewalk surfing' in 1950s California, invented by surfers looking for something to ride on days with no waves.",
  "bowling-pin": "Regulation bowling pins are carved from a single block of hard maple, then coated in plastic so they don't splinter on impact.",
  "gymnastics-balance-beam": "The beam's top surface is only 10 centimeters (about 4 inches) wide — roughly the width of a gymnast's own foot.",
  "skis-and-poles": "The oldest ski fragments ever found date back roughly 8,000 years in Russia — making skiing older than the invention of the wheel.",
  surfboard: "Ancient Hawaiian chiefs rode enormous 'olo' surfboards carved from lightweight wiliwili wood, some over 15 feet long.",
  "racing-bicycle": "Tour de France organizers banned gear-shifting derailleurs until 1937, fearing they would make the brutal race too easy on riders.",
  "diving-springboard": "Divers can slide the board's roller, called a fulcrum, forward or back to make the board stiffer or springier before they even climb on.",
  shuttlecock: "Feather shuttlecocks use exactly 16 goose feathers, all plucked from the same wing of the bird for aerodynamic consistency.",
  "hockey-puck": "NHL pucks are frozen before every game because a cold puck slides smoother and bounces far less than a room-temperature one.",
  "rugby-ball": "Rugby's oval shape is popularly traced to the sport's early inflated pig-bladder balls, though today's shape is a modern rubber-bladder standard.",
  "archery-bow": "Olympic recurve archers draw the bowstring back with roughly 48 pounds of force for men and about 33 pounds for women.",
  "curling-stone": "Nearly every Olympic curling stone is carved from granite quarried on one tiny uninhabited Scottish island, Ailsa Craig.",
  javelin: "A men's javelin must weigh exactly 800 grams and measure between 260 and 270 centimeters long, by World Athletics rules.",
  "snooker-cue": "A standard snooker cue runs about 58 inches long — noticeably longer than a typical pool cue.",
  "water-polo-cap": "A water polo goalkeeper must wear a cap in a distinct color, usually red, so referees can spot them instantly in the pool.",
  snowboard: "Snowboarding descends from the 'Snurfer,' a toy Sherman Poppen bolted together from two kids' skis for his daughters on Christmas Day, 1965.",
  "field-hockey-stick": "Field hockey players may only strike the ball with the stick's flat face — every stick is effectively made 'right-handed' because of this rule.",
  "sumo-mawashi": "A professional sumo wrestler's mawashi is roughly 9 meters of fabric before being folded and wrapped down to fit the waist.",
  "rowing-oar": "Modern 'hatchet' oar blades are wider and less symmetrical than the traditional spoon-shaped blades they gradually replaced.",
  "fencing-mask": "A fencer's mesh mask must pass a punch-force test — fine enough to see clearly through, yet strong enough to stop a blade's point.",
  "karate-belt": "The colored belt ranking system wasn't invented for karate — it came from judo founder Jigoro Kano and was adopted decades later.",
  "shot-put": "The men's shot put ball weighs 7.26 kg — exactly the same weight as the steel ball used in the hammer throw.",
  "weightlifting-barbell": "A men's Olympic barbell always weighs exactly 20 kilograms — before a single weight plate is even added.",
  "cricket-bat": "Cricket bats are carved from a single willow variety, Salix alba 'Caerulea,' grown almost exclusively in England's Essex and Suffolk.",
  "figure-skate": "That jagged 'toe pick' at the blade's front, missing on hockey skates, is what lets figure skaters launch and land their jumps.",
  "lacrosse-stick": "Lacrosse originated with Native American nations, who originally strung their stick pockets with animal sinew instead of synthetic mesh.",
  "fencing-foil": "A competition foil must weigh under 500 grams total, though most tournament foils actually come in closer to 350 grams.",
  discus: "The men's discus weighs 2 kg while the women's weighs just 1 kg — exactly half, unlike most other Olympic throwing events.",
  "biathlon-rifle": "Biathlon rifles fire only .22 rimfire cartridges, capped by rule at a muzzle velocity of 360 meters per second — far weaker than a hunting rifle.",
  "vaulting-pole": "Vaulters used stiff bamboo poles until the 1950s, when bendy fiberglass poles let athletes clear far greater heights almost overnight.",
  "throwing-hammer": "The hammer's wire is capped at just under 1.22 meters, and the men's ball weighs 7.26 kg — identical to a shot put ball.",
  "luge-sled": "Luge athletes reach speeds over 140 km/h lying on a sled with no brakes and no steering wheel — only body weight steers it.",
  bobsled: "Bobsledding began in 1880s St. Moritz, Switzerland, when guests at a resort bolted two steering sleds together for a faster ride downhill.",
  "squash-racket": "A squash racket's total length is capped at 686mm, and its hollow rubber ball measures barely 40mm across.",
  "water-skis": "Water skiing was invented in 1922 by 18-year-old Ralph Samuelson, who first tried riding barrel staves before building proper skis.",
  "polo-mallet": "Polo mallet shafts are traditionally cut from manau, a tropical rattan cane, not bamboo as many people assume.",
  "kendo-shinai": "A shinai isn't solid bamboo at all — it's four separate slats bound together at three points to mimic a real sword's flex and weight.",
  "croquet-mallet": "Croquet mallets stayed entirely wooden for over a century until carbon-fiber, peripherally-weighted heads took over competitive play in the 1990s.",
  "taekwondo-hogu": "Modern taekwondo hogu contain electronic sensors that automatically register a scoring kick's force and location.",
  "show-jumping-rail": "Every rail knocked to the ground during a round costs the horse and rider four penalty faults, no matter which pole falls.",
  handball: "Players coat their palms and the ball with sticky pine-based resin so it clings to their hand almost like glue.",
  "hurling-hurley": "Hurling's ball, the sliotar, has a cork core wrapped in two pieces of leather, its stitched ridge resembling an oversized baseball seam.",
  "sepak-takraw-ball": "Sepak takraw balls have exactly 12 woven holes, letting players juggle and spike them using only their feet, knees, chest, and head — never their hands.",
  "kabaddi-court-line": "A raiding player must chant the word 'kabaddi' continuously without a breath while tagging opponents in enemy territory.",
  "real-tennis-racket": "Real tennis rackets were built lopsided on purpose, so players could scoop up the ball close to the floor or the court's odd-shaped corners.",
  "pelota-vasca-cesta": "A jai alai ball has been clocked at over 300 km/h, making it the fastest-moving ball recorded in any sport on Earth.",
  "capoeira-berimbau": "The rhythm played on the berimbau actually dictates the speed and style of the capoeira game happening in front of it.",
  "shinty-caman": "Shinty and Irish hurling share a common ancestor game, carried from Ireland to Scotland roughly 2,000 years ago before evolving separately.",
  "muay-thai-mongkol": "The mongkol is blessed by a Buddhist monk and must never touch the ground — only the fighter's coach is allowed to place or remove it.",
  "underwater-hockey-pusher": "Underwater hockey, also called octopush, is played along a swimming pool's floor, with snorkeling players pushing a weighted puck into the goal.",
  "jianzi-shuttlecock": "Jianzi has been played in China for roughly 2,000 years, evolving from a military exercise game dating to the Han Dynasty.",
  "kubb-blocks": "Despite its nickname 'Viking chess,' there's no real historical evidence Vikings ever played kubb — the earliest written record dates only to 1911.",
  "ringette-ring": "Ringette replaces the ice hockey puck with a hollow rubber ring specifically so players can't cradle it and must pass the ring constantly.",
  footbag: "The footbag, later branded Hacky Sack, was invented in 1972 by an Oregon man rehabbing an injured knee by kicking a homemade beanbag.",
  "sport-stacking-cups": "The fastest individual 3-3-3 stack cycle on record is under 1.5 seconds — faster than most people can blink twice.",
  skimboard: "Unlike surfing, skimboarding needs no paddling or waves out at sea — riders launch straight off dry sand onto a thin sheet of water.",
  "hornussen-schindel": "The airborne projectile in hornussen can reach up to 300 km/h, and fielders use these giant wooden paddles, called schindels, just to knock it down.",
  "petanque-boules": "Petanque boules only became hollow metal spheres after World War I, when cannonball-forging techniques were adapted to stamp and weld steel shells.",
  "floorball-stick": "Unlike traditional wooden hockey sticks, floorball sticks are made almost entirely of lightweight molded plastic composite.",
};
