// E38 "Guess the Sports Team Mascot" — answer = mascot name, image = real photo of the mascot costume/character.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
export const SPORTS_MASCOTS_E38 = [
  // EASY (18) — globally/nationally iconic mascots
  { slug: "phillie-phanatic", name: "Phillie Phanatic", team: "Philadelphia Phillies", level: "easy" },
  { slug: "gritty", name: "Gritty", team: "Philadelphia Flyers", level: "easy" },
  { slug: "san-diego-chicken", name: "The San Diego Chicken", team: "San Diego Padres (independent)", level: "easy" },
  { slug: "mr-met", name: "Mr. Met", team: "New York Mets", level: "easy" },
  { slug: "benny-the-bull", name: "Benny the Bull", team: "Chicago Bulls", level: "easy" },
  { slug: "suns-gorilla", name: "The Gorilla", team: "Phoenix Suns", level: "easy" },
  { slug: "gunnersaurus", name: "Gunnersaurus Rex", team: "Arsenal FC", level: "easy" },
  { slug: "rocky-nuggets", name: "Rocky", team: "Denver Nuggets", level: "easy" },
  { slug: "youppi", name: "Youppi!", team: "Montreal Canadiens", level: "easy" },
  { slug: "uga", name: "Uga", team: "Georgia Bulldogs", level: "easy" },
  { slug: "bevo", name: "Bevo", team: "Texas Longhorns", level: "easy" },
  { slug: "ralphie", name: "Ralphie", team: "Colorado Buffaloes", level: "easy" },
  { slug: "chief-osceola", name: "Chief Osceola", team: "Florida State Seminoles", level: "easy" },
  { slug: "misha-bear", name: "Misha the Bear", team: "1980 Moscow Olympics", level: "easy" },
  { slug: "sluggerrr", name: "Sluggerrr", team: "Kansas City Royals", level: "easy" },
  { slug: "wally-green-monster", name: "Wally the Green Monster", team: "Boston Red Sox", level: "easy" },
  { slug: "fredbird", name: "Fredbird", team: "St. Louis Cardinals", level: "easy" },
  { slug: "zakumi", name: "Zakumi", team: "2010 FIFA World Cup", level: "easy" },

  // MEDIUM (18)
  { slug: "blue-colts", name: "Blue", team: "Indianapolis Colts", level: "medium" },
  { slug: "kc-wolf", name: "K.C. Wolf", team: "Kansas City Chiefs", level: "medium" },
  { slug: "t-rac", name: "T-Rac", team: "Tennessee Titans", level: "medium" },
  { slug: "bernie-brewer", name: "Bernie Brewer", team: "Milwaukee Brewers", level: "medium" },
  { slug: "clutch-the-bear", name: "Clutch the Bear", team: "Houston Rockets", level: "medium" },
  { slug: "stuff-magic-dragon", name: "Stuff the Magic Dragon", team: "Orlando Magic", level: "medium" },
  { slug: "jaxson-de-ville", name: "Jaxson de Ville", team: "Jacksonville Jaguars", level: "medium" },
  { slug: "lou-seal", name: "Lou Seal", team: "San Francisco Giants", level: "medium" },
  { slug: "orbit", name: "Orbit", team: "Houston Astros", level: "medium" },
  { slug: "brutus-buckeye", name: "Brutus Buckeye", team: "Ohio State Buckeyes", level: "medium" },
  { slug: "bucky-badger", name: "Bucky Badger", team: "Wisconsin Badgers", level: "medium" },
  { slug: "big-al", name: "Big Al", team: "Alabama Crimson Tide", level: "medium" },
  { slug: "mike-the-tiger", name: "Mike the Tiger", team: "LSU Tigers", level: "medium" },
  { slug: "oregon-duck", name: "The Oregon Duck", team: "Oregon Ducks", level: "medium" },
  { slug: "world-cup-willie", name: "World Cup Willie", team: "1966 FIFA World Cup", level: "medium" },
  { slug: "sir-purr", name: "Sir Purr", team: "Carolina Panthers", level: "medium" },
  { slug: "zabivaka", name: "Zabivaka", team: "2018 FIFA World Cup", level: "medium" },
  { slug: "bing-dwen-dwen", name: "Bing Dwen Dwen", team: "2022 Beijing Winter Olympics", level: "medium" },

  // HARD (18)
  { slug: "fred-the-red", name: "Fred the Red", team: "Manchester United", level: "hard" },
  { slug: "hugo-the-hornet", name: "Hugo the Hornet", team: "Charlotte Hornets", level: "hard" },
  { slug: "slider", name: "Slider", team: "Cleveland Guardians", level: "hard" },
  { slug: "dinger", name: "Dinger", team: "Colorado Rockies", level: "hard" },
  { slug: "screech", name: "Screech", team: "Washington Nationals", level: "hard" },
  { slug: "pirate-parrot", name: "Pirate Parrot", team: "Pittsburgh Pirates", level: "hard" },
  { slug: "billy-the-marlin", name: "Billy the Marlin", team: "Miami Marlins", level: "hard" },
  { slug: "handsome-dan", name: "Handsome Dan", team: "Yale Bulldogs", level: "hard" },
  { slug: "testudo", name: "Testudo", team: "Maryland Terrapins", level: "hard" },
  { slug: "reveille", name: "Reveille", team: "Texas A&M Aggies", level: "hard" },
  { slug: "traveler", name: "Traveler", team: "USC Trojans", level: "hard" },
  { slug: "sparky-sun-devil", name: "Sparky", team: "Arizona State Sun Devils", level: "hard" },
  { slug: "cosmo-cougar", name: "Cosmo the Cougar", team: "BYU Cougars", level: "hard" },
  { slug: "otto-the-orange", name: "Otto the Orange", team: "Syracuse Orange", level: "hard" },
  { slug: "stanford-tree", name: "The Stanford Tree", team: "Stanford Cardinal", level: "hard" },
  { slug: "smokey", name: "Smokey", team: "Tennessee Volunteers", level: "hard" },
  { slug: "wild-wing", name: "Wild Wing", team: "Anaheim Ducks", level: "hard" },
  { slug: "cocky", name: "Cocky", team: "South Carolina Gamecocks", level: "hard" },

  // IMPOSSIBLE (18)
  { slug: "rumble-bison", name: "Rumble", team: "Oklahoma City Thunder", level: "impossible" },
  { slug: "youdee", name: "YoUDee", team: "Delaware Fightin' Blue Hens", level: "impossible" },
  { slug: "iceburgh", name: "Iceburgh", team: "Pittsburgh Penguins", level: "impossible" },
  { slug: "goldy-gopher", name: "Goldy Gopher", team: "Minnesota Golden Gophers", level: "impossible" },
  { slug: "blitz-seahawks", name: "Blitz", team: "Seattle Seahawks", level: "impossible" },
  { slug: "purdue-pete", name: "Purdue Pete", team: "Purdue Boilermakers", level: "impossible" },
  { slug: "pat-patriot", name: "Pat Patriot", team: "New England Patriots", level: "impossible" },
  { slug: "cy-cardinal", name: "Cy the Cardinal", team: "Iowa State Cyclones", level: "impossible" },
  { slug: "zampa-the-lion", name: "Zampa the Lion", team: "Millwall FC", level: "impossible" },
  { slug: "cyril-the-swan", name: "Cyril the Swan", team: "Swansea City", level: "impossible" },
  { slug: "herky-hawk", name: "Herky the Hawk", team: "Iowa Hawkeyes", level: "impossible" },
  { slug: "moonchester", name: "Moonchester", team: "Manchester City", level: "impossible" },
  { slug: "sebastian-ibis", name: "Sebastian the Ibis", team: "Miami Hurricanes", level: "impossible" },
  { slug: "billy-the-badger", name: "Billy the Badger", team: "Fulham FC", level: "impossible" },
  { slug: "berni", name: "Berni", team: "Bayern Munich", level: "impossible" },
  { slug: "sparty", name: "Sparty", team: "Michigan State Spartans", level: "impossible" },
  { slug: "chirpy-cockerel", name: "Chirpy", team: "Tottenham Hotspur", level: "impossible" },
  { slug: "rowdy-utsa", name: "Rowdy", team: "UTSA Roadrunners", level: "impossible" },
];
