export const STADIUMS_E55_FACTS = {
  // EASY
  "wembley-stadium": "Its arch is 133 meters tall, visible across much of London.",
  "camp-nou": "FC Barcelona's home, historically Europe's largest stadium.",
  "maracana": "Built for the 1950 World Cup; hosted two World Cup finals.",
  "san-siro": "Shared by AC Milan and Inter Milan since 1947.",
  "old-trafford": "Nicknamed the Theatre of Dreams, Manchester United's home since 1910.",
  "allianz-arena": "Its exterior panels glow red, blue, or white depending on the team.",
  "santiago-bernabeu": "Real Madrid's home since 1947, named after a former club president.",
  "yankee-stadium": "The current stadium opened in 2009, replacing the 1923 original.",
  "madison-square-garden": "Sits atop Penn Station; this is the fourth venue with that name.",
  "metlife-stadium": "Shared home of the NFL's Giants and Jets in New Jersey.",
  "rose-bowl": "Host of five Super Bowls and the 1994 World Cup final.",
  "beijing-national-stadium": "Its steel lattice design hosted the 2008 and 2022 Olympics.",
  "melbourne-cricket-ground": "Capacity over 100,000, among the largest stadiums on Earth.",
  "michigan-stadium": "College football's largest venue, seating over 107,000 fans.",
  "att-stadium": "Home of the Dallas Cowboys, with a retractable roof.",
  "fenway-park": "Baseball's oldest ballpark still in use, opened in 1912.",
  "lords-cricket-ground": "Nicknamed the Home of Cricket, hosting matches since 1814.",
  "signal-iduna-park": "Its steep south stand is nicknamed the Yellow Wall.",

  // MEDIUM
  "emirates-stadium": "Arsenal's home since 2006, replacing the nearby Highbury.",
  "anfield": "Liverpool's home since 1892, famed for 'You'll Never Walk Alone'.",
  "stamford-bridge": "Chelsea's home since the club's founding in 1905.",
  "etihad-stadium": "Built for the 2002 Commonwealth Games before Manchester City moved in.",
  "parc-des-princes": "Home of Paris Saint-Germain since 1974.",
  "estadio-azteca": "Hosted FIFA World Cup finals in both 1970 and 1986.",
  "la-bombonera": "Boca Juniors' home, famous for its steep, boxy stands.",
  "estadio-monumental-river": "Argentina's largest stadium, hosted the 1978 World Cup final.",
  "wrigley-field": "The Chicago Cubs' home since 1914, famous for ivy-covered walls.",
  "dodger-stadium": "Third-oldest ballpark in Major League Baseball, opened in 1962.",
  "croke-park": "Ireland's largest stadium, home of Gaelic games since 1884.",
  "twickenham-stadium": "The home of English rugby union, seating over 82,000.",
  "eden-gardens": "One of cricket's oldest grounds, opened in Kolkata in 1864.",
  "the-gabba": "A major Australian cricket ground in Brisbane since 1895.",
  "sofi-stadium": "Shared home of the NFL's Rams and Chargers, opened in 2020.",
  "estadio-da-luz": "Benfica's home, its name means 'Stadium of Light'.",
  "johan-cruyff-arena": "Ajax's home in Amsterdam, named after the club's legendary player.",
  "estadio-monumental-peru": "Peru's largest stadium, home of Universitario de Deportes.",

  // HARD
  "celtic-park": "Celtic's home since 1892, nicknamed Paradise by its fans.",
  "ibrox-stadium": "Rangers' home in Glasgow, rebuilt after a 1971 stand disaster.",
  "craven-cottage": "Fulham's riverside home, featuring a distinctive old cottage pavilion.",
  "london-stadium": "Built for the 2012 Olympics, now home to West Ham United.",
  "aviva-stadium": "Ireland's national stadium, opened in 2010 in Dublin.",
  "principality-stadium": "Wales' national stadium, with a retractable roof over its pitch.",
  "stade-de-france": "France's national stadium, built for the 1998 World Cup.",
  "veltins-arena": "Schalke's home, among the first with a fully retractable pitch.",
  "red-bull-arena-leipzig": "Home of RB Leipzig, built inside an older 1956 stadium's shell.",
  "estadio-do-dragao": "Porto's home, opened in 2003 ahead of Euro 2004.",
  "estadio-jose-alvalade": "Sporting CP's home in Lisbon, rebuilt for Euro 2004.",
  "estadio-centenario": "Hosted the first FIFA World Cup final in Uruguay in 1930.",
  "estadio-mineirao": "A major Brazilian stadium in Belo Horizonte, opened in 1965.",
  "soldier-field": "Home of the Chicago Bears, named as a WWI memorial in 1925.",
  "lambeau-field": "The Green Bay Packers' home since 1957, in the NFL's smallest market.",
  "tokyo-dome": "Japan's first fully-covered baseball stadium, opened in 1988.",
  "nissan-stadium-yokohama": "Japan's largest stadium, hosted the 2002 World Cup final.",

  // IMPOSSIBLE
  "estadio-malvinas-argentinas": "A Mendoza stadium named for the Falkland Islands conflict.",
  "kingsmeadow": "A small London ground once shared by two very different clubs.",
  "recreation-ground-bath": "Bath Rugby's historic riverside ground in southwest England.",
  "loftus-versfeld-stadium": "A Pretoria stadium hosting both rugby and football.",
  "independence-park-kingston": "Jamaica's national stadium, opened for independence in 1962.",
  "ullevaal-stadion": "Norway's national football stadium, in Oslo since 1926.",
  "parken-stadium": "Denmark's national stadium, built on the site of an older ground.",
  "tele2-arena": "A Stockholm stadium with a shell-like, wicker-patterned facade.",
  "rheinenergiestadion": "Cologne's home ground, rebuilt for the 2006 World Cup.",
  "volksparkstadion": "Hamburg's home ground, rebuilt entirely between 1998 and 2000.",
  "stadion-miejski-wroclaw": "Built for Euro 2012, its facade evokes woven wicker.",
  "pge-narodowy": "Poland's national stadium, built for Euro 2012 in Warsaw.",
  "puskas-arena": "Hungary's national stadium, named after its famous 1950s striker.",
  "arena-nationala": "Romania's national stadium, opened in Bucharest in 2011.",
  "toumba-stadium": "PAOK's home ground in Thessaloniki, Greece.",
  "oaca-spyros-louis": "The main stadium of the 2004 Athens Olympics.",
  "estadio-defensores-del-chaco": "Paraguay's national football stadium in Asunción.",
};
