export const STATUES_E51_FACTS = {
  // EASY
  "statue-of-liberty": "A gift from France, dedicated in New York Harbor in 1886.",
  "christ-the-redeemer": "Lightning struck it in 2014, cracking a finger and its head.",
  "mount-rushmore": "Took 14 years of carving and dynamite to finish, in 1941.",
  "great-sphinx-of-giza": "Carved from a single limestone ridge over 4,500 years ago.",
  "venus-de-milo": "Discovered by a farmer on the Greek island of Milos in 1820.",
  "lincoln-memorial-statue": "Daniel Chester French's marble Lincoln stands 19 feet tall.",
  "winged-victory-of-samothrace": "Found headless and armless on a Greek island in 1863.",
  "charging-bull": "Arturo Di Modica installed it overnight, uninvited, in 1989.",
  "nelsons-column": "Its statue of Admiral Nelson stands about 5.5 meters tall.",
  "merlion": "Half lion, half fish, symbolizing Singapore's fishing-village past.",
  "angel-of-independence": "Its winged angel was toppled by a 1957 earthquake.",
  "statue-of-unity": "At 597 feet tall, it is the tallest statue on Earth.",
  "iwo-jima-memorial": "Depicts six Marines raising a flag on Iwo Jima in 1945.",
  "tian-tan-buddha": "Sits atop 268 steps on Lantau Island, unveiled in 1993.",
  "great-buddha-of-kamakura": "Survived a 15th-century tsunami that swept away its hall.",
  "angel-of-the-north": "Its steel wings stretch 54 meters from tip to tip.",
  "queen-victoria-memorial": "Topped by a gilded bronze figure of Winged Victory.",
  "fearless-girl": "Originally placed to face Wall Street's Charging Bull.",

  // MEDIUM
  "motherland-calls": "At 85 meters, it was once the tallest statue in the world.",
  "the-thinker-rodin": "Originally titled 'The Poet', part of Rodin's Gates of Hell.",
  "david-michelangelo": "Carved from a huge marble block other sculptors had rejected.",
  "manneken-pis": "Owns a wardrobe of hundreds of tiny costumes.",
  "little-mermaid-copenhagen": "Inspired by Hans Christian Andersen's 1837 fairy tale.",
  "nefertiti-bust": "Its left eye's inlay was never finished by the sculptor.",
  "pieta-michelangelo": "The only work Michelangelo ever signed, on Mary's sash.",
  "martin-luther-king-memorial": "Carved from a single 30-foot block of granite.",
  "great-buddha-of-nara": "Housed inside one of the largest wooden buildings ever built.",
  "wat-pho-reclining-buddha": "Its feet are inlaid with mother-of-pearl designs.",
  "golden-buddha-wat-traimit": "Solid gold statue found under cracked plaster in 1955.",
  "bronze-horseman": "Its pedestal, the Thunder Stone, is a single 1,500-ton rock.",
  "discobolus": "Only Roman marble copies of the lost Greek bronze survive.",
  "christopher-columbus-monument-barcelona": "Columbus points out to sea, sparking a direction debate.",
  "motherland-monument-kyiv": "Its stainless-steel figure rises about 62 meters into the sky.",
  "san-martin-equestrian-statue": "Argentina's first equestrian monument, unveiled in 1862.",
  "laocoon-and-his-sons": "Unearthed in Rome in 1506; Michelangelo saw it dug up.",
  "cristo-rei-almada": "Built to fulfill a 1940 vow after Portugal avoided WWII bombing.",

  // HARD
  "perseus-with-the-head-of-medusa": "Cast in bronze by Cellini for the Medici family in 1554.",
  "leshan-giant-buddha": "Its carved ears alone stretch more than 20 feet long.",
  "colossi-of-memnon": "One statue reportedly 'sang' at dawn from a crack inside it.",
  "heroes-square-millennium-monument": "Marks Hungary's 1,000th anniversary, finished in 1929.",
  "the-kelpies": "Each steel horse-head sculpture stands 30 meters tall.",
  "peter-pan-statue-kensington": "J.M. Barrie secretly arranged its overnight installation.",
  "alice-in-wonderland-statue": "Children are meant to climb on its bronze mushroom.",
  "cristo-de-la-concordia": "Some call it taller than Rio's Christ, pedestal included.",
  "christ-the-king-swiebodzin": "Wears a crown that lights up after dark.",
  "apollo-belvedere": "A Roman copy once hailed as the greatest ancient sculpture.",
  "bamiyan-buddhas": "Destroyed by the Taliban with dynamite in March 2001.",
  "alexander-the-great-skopje": "Officially unnamed to avoid a dispute with Greece.",
  "vulcan-statue-birmingham": "The largest cast-iron statue ever made, cast in 1904.",
  "cristo-blanco-cusco": "Stands on a hilltop above Cusco, lit up every night.",
  "boudicca-statue-london": "Unveiled in 1902, decades after it was first sculpted.",
  "richard-the-lionheart-statue": "A WWII bomb bent its sword in 1940; it was left that way.",
  "spring-temple-buddha": "Its bronze figure rises from atop a massive stone pedestal.",
  "african-renaissance-monument": "Taller than the Statue of Liberty, unveiled in 2010.",

  // IMPOSSIBLE
  "monument-to-the-battle-of-the-nations": "Marks Napoleon's defeat at Leipzig in 1813.",
  "genghis-khan-equestrian-statue": "The world's tallest equestrian statue, wrapped in steel.",
  "ushiku-daibutsu": "Visitors can ride an elevator up inside the statue.",
  "awakening-sculpture": "Only a giant's head, arms and legs emerge from the soil.",
  "virgin-of-el-panecillo": "The only Mary statue made with wings and a chained dragon.",
  "skanderbeg-statue-tirana": "Honors the 15th-century noble who resisted Ottoman rule.",
  "guanyin-of-nanshan": "One of the tallest statues of a female figure on Earth.",
  "diana-princess-of-wales-statue": "Unveiled on what would have been her 60th birthday.",
  "bahubali-statue-shravanabelagola": "Carved from a single granite boulder atop a hill.",
  "lamassu-winged-bull": "Combines a human head, a bull's body, and eagle's wings.",
  "hermannsdenkmal": "Marks a Germanic tribal victory over Rome in 9 AD.",
  "alyosha-monument-plovdiv": "Named after a real Soviet Red Army radio operator.",
  "vercingetorix-statue": "Sculpted by the same artist who made the Statue of Liberty.",
  "bolivar-equestrian-statue-caracas": "Unveiled in 1874 in the plaza that bears his name.",
  "cerro-de-los-angeles-christ": "Rebuilt after the original fell in the Spanish Civil War.",
  "robin-hood-statue-nottingham": "Shows the legendary outlaw drawing his bow, cast in 1952.",
  "ofuna-kannon": "Construction paused for decades before finishing in 1960.",
  "colossus-of-barletta": "A Roman bronze giant, possibly looted during a Crusade.",
};
export default STATUES_E51_FACTS;
