export const STATES_E77_FACTS = {
  ak: "The largest US state, bigger than Texas and California combined.",
  ca: "Home to both the highest and lowest points in the contiguous US.",
  fl: "Its peninsula gives it more coastline than any state except Alaska.",
  hi: "The only US state made up entirely of islands.",
  id: "Its narrow panhandle squeezes it between Washington and Montana.",
  la: "Its boot shape comes from the Mississippi River's sprawling delta.",
  me: "The only state whose name is a single syllable.",
  mi: "Its Lower Peninsula's shape gave it the nickname 'the Mitten.'",
  ny: "Long Island stretches its shape far out into the Atlantic.",
  ok: "Its panhandle is a strip left over from old territorial borders.",
  tx: "The second-largest US state, with a coastline shaped like a hook.",
  ut: "Its northeast corner has a distinctive notch carved out for Wyoming.",
  va: "Its Eastern Shore is cut off from the rest of the state by water.",
  az: "Home to the Grand Canyon, up to 18 miles wide.",
  ky: "Its northern border follows the winding Ohio River.",
  md: "The Chesapeake Bay splits this state into two very different halves.",
  mn: "Nicknamed 'Land of 10,000 Lakes,' though it actually has far more.",
  mo: "Its 'bootheel' exists because a landowner lobbied Congress in 1818.",
  nv: "Nearly all its borders are straight, except along the Colorado River.",
  nj: "One of the most densely populated states despite its small size.",
  nm: "Its southern border includes a small notch called the bootheel.",
  or: "Home to Crater Lake, the deepest lake in the United States.",
  tn: "One of the longest, narrowest states, over 400 miles east to west.",
  wa: "Named after George Washington, the only state named for a president.",
  wv: "Formed by counties that broke away from Virginia during the Civil War.",
  wi: "Its shape includes a narrow peninsula jutting into Lake Michigan.",
  al: "Its short coastline sits between Mississippi and Florida's panhandle.",
  ar: "The only US state with a diamond mine open to the public.",
  ct: "One of the original 13 colonies, in New England's southwest corner.",
  ga: "The largest state east of the Mississippi River by land area.",
  ma: "Cape Cod curls out from its eastern coast like a fishing hook.",
  ms: "Its western border follows the Mississippi River's winding path.",
  nh: "Has just 18 miles of coastline, the shortest of any coastal state.",
  nc: "The Outer Banks form a thin barrier island chain off its coast.",
  oh: "Its northern border curves along the shore of Lake Erie.",
  pa: "Its small Lake Erie shoreline was added through a later land purchase.",
  sc: "Its coast is dotted with sea islands, unlike its northern neighbor.",
  vt: "The only landlocked state in New England.",
  co: "One of the few states whose borders are all straight lines.",
  de: "The second-smallest US state, named after an early colonial governor.",
  il: "A thin strip along Lake Michigan gives Chicago its lakefront.",
  in: "Its name means 'Land of the Indians.'",
  ia: "Bordered on both sides by two of America's great rivers.",
  ks: "Nearly a rectangle, except for a river-carved notch in the northeast.",
  mt: "The fourth-largest state, with a jagged western border in the Rockies.",
  ne: "Its panhandle stretches west between Colorado and South Dakota.",
  nd: "Its borders are almost entirely straight lines drawn by surveyors.",
  ri: "The smallest US state by area, despite its name suggesting an island.",
  sd: "The Missouri River splits this state roughly down the middle.",
  wy: "A near-perfect rectangle, making it hard to tell from Colorado.",
};

export default STATES_E77_FACTS;
