export const SUPERCARS_E69_FACTS = {
  "bugatti-veyron": "Was the world's fastest production car when it launched in 2005.",
  "bugatti-chiron": "Its top speed was electronically limited to 261 mph.",
  "lamborghini-aventador": "Its scissor doors carry on a Lamborghini tradition since the Countach.",
  "lamborghini-huracan": "Named after a champion fighting bull, following Lambo tradition.",
  "ferrari-laferrari": "Ferrari's first hybrid hypercar, pairing a V12 with an electric motor.",
  "ferrari-488-gtb": "Its twin-turbo V8 replaced the naturally aspirated 458's engine.",
  "mclaren-p1": "Part of the 'Holy Trinity' hybrid hypercars, with LaFerrari and 918.",
  "mclaren-720s": "Its headlights double as air intakes for the engine.",
  "porsche-918-spyder": "A plug-in hybrid hypercar that could also run on electric power alone.",
  "nissan-gt-r": "Nicknamed 'Godzilla' for how it outperforms far pricier rivals.",
  "ford-gt": "Returned to Le Mans in 2016, 50 years after the GT40's win.",
  "dodge-viper": "Originally built with no roof, door handles, or air conditioning.",
  "chevrolet-corvette-z06": "Uses a supercharged V8 shared with the Cadillac CTS-V.",
  "mercedes-amg-gt": "Designed by the same team behind the Mercedes SLS AMG.",
  "audi-r8": "Shares its V10 engine with the Lamborghini Huracán.",
  "ferrari-f40": "The last Ferrari personally approved by Enzo Ferrari himself.",
  "koenigsegg-agera": "Its name means 'to act' in Swedish.",
  "pagani-huayra": "Named after a Quechua god of wind.",

  "lexus-lfa": "Took over a decade to develop and used a specially built engine.",
  "acura-nsx": "Uses a hybrid setup with a twin-turbo V6 and three electric motors.",
  "maserati-mc20": "Its name marks Maserati's 2020 return to building supercars.",
  "aston-martin-vanquish": "Its body panels are made from lightweight carbon fiber.",
  "mclaren-senna": "Named after F1 legend Ayrton Senna, a former McLaren driver.",
  "ferrari-sf90-stradale": "Ferrari's first series-production plug-in hybrid road car.",
  "lamborghini-sian": "Its name means 'flash of lightning' in Bolognese dialect.",
  "koenigsegg-jesko": "Named after the founder's father, Jesko von Koenigsegg.",
  "rimac-nevera": "An all-electric hypercar built by a Croatian manufacturer.",
  "pagani-zonda": "Named after a strong, warm wind from the Andes.",
  "bugatti-divo": "Named after French racing driver Albert Divo.",
  "porsche-carrera-gt": "Originally developed from a canceled Le Mans racing program.",
  "ferrari-f8-tributo": "Its name honors Ferrari's V8 engine heritage.",
  "mclaren-f1": "Held the production car speed record for 7 years, until 2005.",
  "lamborghini-murcielago": "Named after a bull that survived a legendary bullfight.",
  "ferrari-enzo": "Named directly after Ferrari's founder, Enzo Ferrari.",
  "aston-martin-dbs-superleggera": "'Superleggera' means 'super light' in Italian.",
  "chevrolet-corvette-zr1": "One of the most powerful Corvettes GM has ever built.",

  "ferrari-f50": "Built using Formula 1-derived carbon fiber construction techniques.",
  "aston-martin-valkyrie": "Co-developed with the Red Bull Racing Formula 1 team.",
  "aston-martin-one-77": "Only 77 units were ever built, matching its name.",
  "mclaren-artura": "McLaren's first series-production plug-in hybrid supercar.",
  "porsche-911-gt2-rs": "One of the fastest rear-wheel-drive cars around the Nürburgring.",
  "ford-gt-2005": "Built to celebrate Ford's 100th anniversary in 2003.",
  "hennessey-venom-gt": "Built on a modified Lotus Exige chassis.",
  "ssc-tuatara": "Named after a reptile found only in New Zealand.",
  "lotus-evija": "Lotus's first all-electric hypercar.",
  "alfa-romeo-4c": "Built with a carbon fiber tub, unusual for its price range.",
  "rimac-concept-one": "One of the first all-electric hypercars ever built.",
  "gordon-murray-t50": "Designed by the creator of the legendary McLaren F1.",
  "ferrari-296-gtb": "Its name reflects a 2.9-liter V6 paired with a hybrid motor.",
  "mclaren-speedtail": "Its central driving seat mirrors the McLaren F1's layout.",
  "ferrari-daytona-sp3": "Inspired by Ferrari prototypes that swept the 1967 Daytona 24 Hours.",
  "lamborghini-revuelto": "Lamborghini's first V12 hybrid production car.",

  "zenvo-ts1": "Built by a small Danish manufacturer founded in 2007.",
  "w-motors-lykan-hypersport": "Featured in the film Furious 7 crashing through skyscrapers.",
  "de-tomaso-p72": "Designed to evoke De Tomaso's 1960s racing prototypes.",
  "apollo-ie": "'IE' stands for Intensa Emozione, Italian for 'intense emotion'.",
  "noble-m600": "Built by a small British firm, with no traction control by default.",
  "spyker-c8": "Built by a Dutch manufacturer that also once made aircraft.",
  "vector-w8": "An American hypercar built with aerospace-inspired engineering.",
  "koenigsegg-ccx": "The first Koenigsegg designed to meet U.S. emissions rules.",
  "koenigsegg-one1": "Its horsepower figure matched its weight in kilograms.",
  "koenigsegg-regera": "Uses no traditional gearbox, only a direct-drive system.",
  "pagani-utopia": "Designed with manual controls, resisting automated driving aids.",
  "hennessey-venom-f5": "Named after the highest category on the Fujita tornado scale.",
  "mercedes-amg-one": "Uses Formula 1 hybrid powertrain technology in a road car.",
  "mclaren-570s": "Part of McLaren's entry-level 'Sports Series' lineup.",
  "alfa-romeo-8c-competizione": "Its name honors Alfa Romeo's straight-eight racing engines.",
  "porsche-911-turbo-s": "One of the quickest-accelerating gas-powered Porsches ever built.",
  "nissan-gt-r50": "Built to mark 50 years of the Nissan GT-R nameplate.",
  "dodge-viper-acr": "ACR stands for American Club Racer, built for track use.",
};

export default SUPERCARS_E69_FACTS;
