export const SUVS_E72_FACTS = {
  "toyota-rav4": "One of the best-selling SUVs in the world.",
  "honda-cr-v": "Its name originally stood for 'Comfortable Runabout Vehicle'.",
  "ford-explorer": "Helped popularize the modern SUV boom in the 1990s.",
  "chevrolet-tahoe": "Named after Lake Tahoe on the California-Nevada border.",
  "jeep-grand-cherokee": "The first Jeep built with unibody, not body-on-frame, construction.",
  "toyota-4runner": "Still uses body-on-frame construction, unlike most rivals.",
  "nissan-rogue": "One of Nissan's best-selling models in the US.",
  "honda-pilot": "Shares its platform with the Honda Odyssey minivan.",
  "chevrolet-suburban": "One of the longest-running vehicle nameplates in history.",
  "gmc-yukon": "Shares its platform with the Chevrolet Tahoe.",
  "ford-expedition": "Ford's full-size SUV, based on the F-150 platform.",
  "toyota-highlander": "Toyota's midsize three-row SUV, smaller than the Sequoia.",
  "subaru-outback": "Blends wagon styling with raised SUV-like ground clearance.",
  "jeep-cherokee": "One of the first compact SUVs on the US market.",
  "mazda-cx-5": "Mazda's best-selling model worldwide.",
  "hyundai-tucson": "Named after the city of Tucson, Arizona.",
  "kia-sportage": "Kia's longest-running SUV nameplate.",
  "volkswagen-tiguan": "Its name blends the German words for tiger and iguana.",

  "bmw-x5": "BMW's first SUV, launched in 1999.",
  "mercedes-benz-gle": "Formerly known as the Mercedes-Benz M-Class.",
  "audi-q7": "Audi's first SUV, sharing its platform with the VW Touareg.",
  "land-rover-discovery": "Originally developed to sit between the Defender and Range Rover.",
  "range-rover-sport": "A sportier, lower-riding version of the standard Range Rover.",
  "porsche-cayenne": "Porsche's first SUV, controversial with fans when launched.",
  "lexus-rx": "The vehicle that helped popularize luxury crossover SUVs.",
  "acura-mdx": "Honda's luxury brand's first three-row SUV.",
  "infiniti-qx60": "Shares its platform with the Nissan Pathfinder.",
  "volvo-xc90": "Volvo's flagship SUV, seats up to seven passengers.",
  "cadillac-escalade": "Built on the same platform as the Chevrolet Tahoe.",
  "lincoln-navigator": "Based on the same platform as the Ford Expedition.",
  "dodge-durango": "One of the few three-row SUVs with a V8 engine option.",
  "chevrolet-traverse": "Chevrolet's largest crossover SUV.",
  "buick-enclave": "Shares its platform with the Chevrolet Traverse.",
  "mitsubishi-outlander": "Also sold with a plug-in hybrid version in many markets.",
  "nissan-pathfinder": "Originally based on a Nissan pickup truck platform.",
  "toyota-sequoia": "Toyota's largest SUV, named after the giant sequoia tree.",

  "bmw-x7": "BMW's largest and most luxurious SUV model.",
  "mercedes-amg-g63": "A high-performance version of the boxy Mercedes G-Class.",
  "land-rover-defender-110": "The longer, five-door version of the modern Defender.",
  "lexus-gx": "Shares its body-on-frame platform with the Land Cruiser Prado.",
  "toyota-land-cruiser-300": "The latest generation of Toyota's long-running flagship SUV.",
  "jeep-wrangler-rubicon": "Its off-road trim named after a famous California trail.",
  "range-rover-autobiography": "Range Rover's top luxury trim level.",
  "kia-telluride": "Named after a ski town in Colorado.",
  "hyundai-palisade": "Hyundai's largest SUV, sharing its platform with the Telluride.",
  "ford-bronco": "Revived in 2021 after a 25-year absence from Ford's lineup.",
  "chevrolet-blazer": "Reintroduced as a car-based crossover, unlike its earlier ancestor.",
  "gmc-acadia": "GMC's midsize crossover, positioned above the Terrain.",
  "subaru-ascent": "Subaru's largest SUV, seating up to eight people.",
  "volkswagen-atlas": "Named after the Atlas Mountains, not the Greek Titan.",
  "nissan-armada": "Based on the same platform as the Nissan Patrol.",
  "infiniti-qx80": "Shares its platform with the Nissan Armada.",

  "ineos-grenadier": "Built by a company founded by a British chemical industrialist.",
  "land-rover-defender-90": "The shorter, three-door version of the modern Defender.",
  "toyota-land-cruiser-prado": "A smaller, related model sold alongside the full-size Land Cruiser.",
  "mitsubishi-pajero": "Sold under different names in some markets due to its name.",
  "nissan-patrol": "One of Nissan's longest-running nameplates, dating to 1951.",
  "suzuki-jimny": "A tiny off-roader with a cult following worldwide.",
  "isuzu-mu-x": "Shares its platform with the Isuzu D-Max pickup truck.",
  "ssangyong-rexton": "A Korean SUV once styled with input from Mercedes-Benz.",
  "mahindra-thar": "An Indian off-roader inspired by the classic Jeep design.",
  "tata-safari": "One of India's earliest sport utility vehicles.",
  "great-wall-haval-h9": "A body-on-frame SUV from Great Wall Motors' Haval brand.",
  "byd-tang": "A plug-in hybrid SUV named after a Chinese dynasty.",
  "geely-okavango": "Named after a river delta in Botswana.",
  "chery-tiggo-8": "A three-row SUV from Chinese automaker Chery.",
  "mg-hs": "A compact SUV from the revived MG brand, now Chinese-owned.",
  "jac-js4": "A compact SUV from Chinese manufacturer JAC Motors.",
  "dongfeng-forthing-t5": "A three-row SUV from Dongfeng's Forthing sub-brand.",
  "changan-cs75": "One of Changan's best-selling SUV models in China.",
};

export default SUVS_E72_FACTS;
