// Episode 13 "Guess the Tourist Destination" — one verified <=70-char fact per item, keyed by slug.
export const TOURIST_SPOTS_E13_FACTS = {
  "maldives-overwater-villas": "The Maldives is made up of over 1,000 coral islands.",
  "santorini-oia": "Santorini's white buildings sit atop a volcanic caldera.",
  "bora-bora-lagoon": "Bora Bora's lagoon is famous for its overwater bungalows.",
  "bali-rice-terraces": "Bali's rice terraces use an ancient irrigation system called subak.",
  "grand-canyon": "The Grand Canyon is about 277 miles long.",
  "great-barrier-reef": "The Great Barrier Reef is visible from outer space.",
  "copacabana-beach-rio": "Copacabana Beach stretches about 2.5 miles along Rio's coast.",
  "venice-canals": "Venice is built across more than 100 small islands.",
  "swiss-alps-matterhorn": "The Matterhorn's peak was first climbed in 1865.",
  "palm-jumeirah-dubai": "Palm Jumeirah is an artificial island shaped like a palm tree.",
  "cancun-riviera-maya": "Cancún's beaches sit along the Yucatán Peninsula's coast.",
  "phi-phi-islands-thailand": "The Phi Phi Islands became famous after the movie The Beach.",
  "iguazu-falls-argentina": "Iguazu Falls is made up of about 275 individual waterfalls.",
  "cappadocia-balloons": "Cappadocia is known for its fairy chimney rock formations.",
  "french-riviera-cote-dazur": "The French Riviera has drawn artists and royalty for centuries.",
  "blue-lagoon-iceland": "The Blue Lagoon's warm water comes from a nearby power plant.",
  "serengeti-tanzania": "The Serengeti hosts the largest land migration on Earth.",
  "ibiza-island": "Ibiza is a Balearic island known for its nightlife scene.",
  "amalfi-coast-italy": "The Amalfi Coast road hugs cliffs above the Tyrrhenian Sea.",
  "boracay-island": "Boracay is known for its White Beach's powdery sand.",
  "seychelles-anse-source-dargent": "This Seychelles beach is famous for its giant granite boulders.",
  "fiji-islands": "Fiji is made up of more than 330 islands.",
  "great-ocean-road-twelve-apostles": "The Twelve Apostles are limestone stacks along Victoria's coast.",
  "yellowstone-national-park": "Yellowstone sits atop one of the world's largest volcanic systems.",
  "banff-lake-louise": "Lake Louise gets its turquoise color from glacial rock flour.",
  "plitvice-lakes-croatia": "Plitvice Lakes has 16 terraced lakes connected by waterfalls.",
  "milford-sound-nz": "Milford Sound is technically a fiord, not a true sound.",
  "jeju-island-korea": "Jeju Island formed from volcanic eruptions long ago.",
  "zanzibar-beaches": "Zanzibar was once a major hub of the spice trade.",
  "geirangerfjord-norway": "Geirangerfjord is a UNESCO World Heritage-listed fjord.",
  "sahara-desert-merzouga-morocco": "The Merzouga dunes near the Sahara can rise over 150 meters.",
  "champs-elysees-paris": "The Champs-Élysées runs from the Arc de Triomphe to Concorde.",
  "shibuya-crossing-tokyo": "Shibuya Crossing can see over 1,000 pedestrians cross at once.",
  "grand-bazaar-istanbul": "Istanbul's Grand Bazaar has over 4,000 shops.",
  "monte-carlo-monaco": "Monte Carlo is famous for its casino and Formula 1 street race.",
  "kerala-backwaters-india": "Kerala's backwaters are a network of lagoons and canals.",
  "torres-del-paine-chile": "Torres del Paine's granite towers rise over 2,500 meters.",
  "jiuzhaigou-valley-china": "Jiuzhaigou Valley is known for its colorful mineral-rich lakes.",
  "lake-baikal-russia": "Lake Baikal holds about a fifth of the world's unfrozen fresh water.",
  "sossusvlei-namibia": "Sossusvlei's dunes are among the tallest in the world.",
  "ninh-binh-trang-an-vietnam": "Trang An's limestone karsts rise from rice paddies and rivers.",
  "komodo-island-indonesia": "Komodo Island is home to the world's largest living lizard.",
  "whistler-canada": "Whistler co-hosted the 2010 Winter Olympics alpine events.",
  "queenstown-new-zealand": "Queenstown is known as the adventure capital of New Zealand.",
  "faroe-islands": "The Faroe Islands lie between Iceland and Norway.",
  "camden-market-london": "Camden Market began as a small canal-side craft market in 1974.",
  "costa-del-sol-spain": "Costa del Sol means 'Coast of the Sun' in Spanish.",
  "chatuchak-market-bangkok": "Chatuchak Market has thousands of stalls across 27 sections.",
  "fernando-de-noronha-brazil": "Fernando de Noronha limits daily visitor numbers to protect its reefs.",
  "aspen-colorado": "Aspen is one of the most famous ski resort towns in the US.",
  "marrakech-medina-jemaa-el-fnaa": "Jemaa el-Fnaa transforms into a food market each evening.",
  "wadi-rum-jordan": "Wadi Rum's red desert has stood in for Mars in several films.",
  "huacachina-oasis-peru": "Huacachina's oasis water is now kept full by pumped water.",
  "blyde-river-canyon-south-africa": "Blyde River Canyon is one of the largest canyons on Earth.",
  "danakil-depression-ethiopia": "The Danakil Depression is one of the hottest places on Earth.",
  "lencois-maranhenses-brazil": "Lençóis Maranhenses fills with rainwater lagoons each rainy season.",
  "lake-hillier-australia": "Lake Hillier's water stays permanently bubblegum pink.",
  "avenue-of-baobabs-madagascar": "The Avenue of the Baobabs' trees can be centuries old.",
  "raja-ampat-indonesia": "Raja Ampat sits within the heart of the Coral Triangle.",
  "guatape-el-penol-colombia": "Climbing El Peñón de Guatapé means 708 steps to the top.",
  "fjadrargljufur-canyon-iceland": "Fjaðrárgljúfur Canyon was carved by glacial rivers over ice ages.",
  "harbour-island-pink-sand-bahamas": "Harbour Island's pink sand comes from tiny foraminifera shells.",
  "blue-eye-spring-albania": "Albania's Blue Eye Spring plunges to depths still not fully mapped.",
  "tunnel-of-love-ukraine": "Ukraine's Tunnel of Love forms around an active rail line.",
  "lake-bled-slovenia": "Lake Bled has a tiny island reachable only by boat or swimming.",
  "wahiba-sands-oman": "Wahiba Sands is home to Bedouin communities among its dunes.",
  "great-blue-hole-belize": "The Great Blue Hole is a giant marine sinkhole in Belize.",
  "banaue-rice-terraces-philippines": "The Banaue Rice Terraces are often called the 'Eighth Wonder.'",
  "lake-natron-tanzania": "Lake Natron's high alkalinity can calcify animals that die in it.",
  "yungas-road-bolivia": "Yungas Road earned the nickname 'Death Road' for its steep drops.",
  "lake-retba-senegal": "Lake Retba turns pink from algae that thrives in its salty water.",
};
export default TOURIST_SPOTS_E13_FACTS;
