export const TOY_GAME_LOGOS_E48_FACTS = {
  // EASY
  "lego": "Its name comes from Danish 'leg godt', meaning play well.",
  "barbie": "Named after Ruth Handler's daughter Barbara; launched in 1959.",
  "monopoly": "Based on Elizabeth Magie's 1904 Landlord's Game patent.",
  "hot-wheels": "Mattel sold over 16 million of the cars in their 1968 debut.",
  "play-doh": "Originally sold in the 1930s as a wallpaper cleaner.",
  "uno": "Invented in 1971 by Ohio barber Merle Robbins.",
  "rubiks-cube": "Ernő Rubik invented it in Budapest in 1974.",
  "crayola": "Its name blends French 'craie' (chalk) with 'oleaginous'.",
  "pokemon-tcg": "First released in Japan in October 1996.",
  "jenga": "Its name comes from 'kujenga', Swahili for 'to build'.",
  "scrabble": "Alfred Butts invented it in 1938; renamed Scrabble in 1948.",
  "transformers": "Built from Takara's Japanese Diaclone and Microman toy molds.",
  "my-little-pony": "Hasbro's toy line launched in 1983 with six pastel ponies.",
  "nerf": "The first Nerf ball launched in 1969 as an indoor foam ball.",
  "risk": "Created by French filmmaker Albert Lamorisse in 1957.",
  "cluedo": "Anthony Pratt patented it in the UK in 1947.",
  "trivial-pursuit": "Two Canadian journalists devised it in one evening in 1979.",
  "twister": "Originally named Pretzel before its 1966 Milton Bradley launch.",

  // MEDIUM
  "fisher-price": "Founded in 1930 in East Aurora, New York.",
  "connect-four": "Milton Bradley first sold it in February 1974.",
  "battleship": "Milton Bradley's plastic-pegs edition debuted in 1967.",
  "the-game-of-life": "Rooted in Milton Bradley's 1860 Checkered Game of Life.",
  "hungry-hungry-hippos": "Milton Bradley released it for Christmas 1978.",
  "operation": "Student John Spinello sold the idea for just $500.",
  "dungeons-and-dragons": "Gary Gygax and Dave Arneson published it in 1974.",
  "matchbox": "Lesney Products launched the brand in Britain in 1953.",
  "bicycle": "The US Playing Card Company debuted the brand in 1885.",
  "care-bears": "American Greetings created them for greeting cards in 1981.",
  "gi-joe": "Hasbro coined the term 'action figure' for it in 1964.",
  "thomas-and-friends": "Based on Rev. Wilbert Awdry's Railway Series, begun 1945.",
  "bratz": "MGA Entertainment launched the doll line in 2001.",
  "lol-surprise": "MGA Entertainment launched the line in 2016.",
  "paw-patrol": "The Spin Master series first aired on Nickelodeon in 2013.",
  "funko": "Mike Becker founded it in 1998; Pop! Vinyls arrived in 2010.",
  "playmobil": "Designer Hans Beck's figures launched in Germany in 1974.",
  "yu-gi-oh": "Konami released the card game in Japan in February 1999.",

  // HARD
  "hasbro": "Founded in 1923 as Hassenfeld Brothers in Rhode Island.",
  "mattel": "Its name blends founders Harold 'Matt' Matson and Elliot.",
  "magic-the-gathering": "Richard Garfield's 1993 design was the first modern TCG.",
  "catan": "Klaus Teuber's design debuted in Germany in 1995.",
  "yahtzee": "It was originally called 'Yacht,' played by a Canadian couple.",
  "sorry": "Based on the ancient game Pachisi; trademarked in 1929.",
  "candy-land": "Eleanor Abbott created it in 1948 while recovering from polio.",
  "mouse-trap": "Ideal Toy Co. released its Rube Goldberg-style trap in 1963.",
  "simon": "Ralph Baer and Howard Morrison's game launched in 1978.",
  "boggle": "Parker Brothers renamed and released it in 1972.",
  "taboo": "Designed by Brian Hersch, published in 1989.",
  "ravensburger": "Founded in Germany in 1883; its first game came in 1884.",
  "little-tikes": "Founded in Ohio in 1970 by Thomas Murdough.",
  "ty-beanie-babies": "Ty Warner launched Beanie Babies in 1993.",
  "leapfrog": "Michael Wood founded it in 1995 to teach his son phonics.",
  "radio-flyer": "Antonio Pasin built his first wagon in Chicago in 1917.",
  "tonka": "Named after Lake Minnetonka, near its Minnesota factory.",
  "etch-a-sketch": "André Cassagnes invented it; Ohio Art launched it in 1960.",

  // IMPOSSIBLE
  "spin-master": "Founded in Toronto in 1994; its first hit was Earth Buddy.",
  "mga-entertainment": "Isaac Larian's company launched Bratz dolls in 2001.",
  "wizards-of-the-coast": "Peter Adkison founded it near Seattle in 1990.",
  "warhammer": "Games Workshop first published it in 1983.",
  "carcassonne": "Klaus-Jürgen Wrede's tile game debuted in Germany in 2000.",
  "ticket-to-ride": "Alan R. Moon's railway game launched in 2004.",
  "pandemic": "Matt Leacock designed it; Z-Man Games released it in 2008.",
  "codenames": "Vlaada Chvátil's word game came out in 2015.",
  "dixit": "Jean-Louis Roubira's card game launched in France in 2008.",
  "bananagrams": "Abraham Nathanson debuted it at London Toy Fair in 2006.",
  "exploding-kittens": "Its 2015 Kickstarter drew a record 219,000+ backers.",
  "schleich": "Friedrich Schleich founded the German firm in 1935.",
  "meccano": "Frank Hornby patented his construction toy in 1901.",
  "lincoln-logs": "John Lloyd Wright, son of Frank Lloyd Wright, made it in 1916.",
  "waddingtons": "The Leeds, England firm released UK Monopoly in 1936.",
  "weebles": "Playskool's slogan: they 'wobble but they don't fall down'.",
  "corgi-toys": "Mettoy launched these UK die-cast cars in 1956.",
};
