// E33 "Guess the Country" — answer = country, image = photo of the country's traditional costume.
// Calibrated by global recognizability (quiz-difficulty-calibration): easy ~90% down to impossible <3%.
export const TRADITIONAL_COSTUMES_E33 = [
  // EASY (17) — globally iconic traditional dress
  { slug: "japan-kimono", country: "Japan", garment: "Kimono", level: "easy" },
  { slug: "india-sari", country: "India", garment: "Sari", level: "easy" },
  { slug: "scotland-kilt", country: "Scotland", garment: "Kilt", level: "easy" },
  { slug: "mexico-china-poblana", country: "Mexico", garment: "China Poblana dress", level: "easy" },
  { slug: "south-korea-hanbok", country: "South Korea", garment: "Hanbok", level: "easy" },
  { slug: "netherlands-volendam", country: "Netherlands", garment: "Volendam costume", level: "easy" },
  { slug: "germany-lederhosen", country: "Germany", garment: "Lederhosen & Dirndl", level: "easy" },
  { slug: "china-qipao", country: "China", garment: "Qipao", level: "easy" },
  { slug: "spain-flamenco", country: "Spain", garment: "Flamenco dress", level: "easy" },
  { slug: "switzerland-tracht", country: "Switzerland", garment: "Swiss Tracht", level: "easy" },
  { slug: "vietnam-ao-dai", country: "Vietnam", garment: "Áo dài", level: "easy" },
  { slug: "norway-bunad", country: "Norway", garment: "Bunad", level: "easy" },
  { slug: "austria-tracht", country: "Austria", garment: "Austrian Tracht", level: "easy" },
  { slug: "greece-fustanella", country: "Greece", garment: "Fustanella", level: "easy" },
  { slug: "philippines-barong", country: "Philippines", garment: "Barong Tagalog & Filipiniana", level: "easy" },
  { slug: "thailand-silk-dress", country: "Thailand", garment: "Traditional Thai silk dress", level: "easy" },
  { slug: "nigeria-agbada", country: "Nigeria", garment: "Agbada", level: "easy" },

  // MEDIUM (16) — well known, less universally iconic
  { slug: "poland-folk-costume", country: "Poland", garment: "Polish folk costume", level: "medium" },
  { slug: "russia-sarafan", country: "Russia", garment: "Sarafan", level: "medium" },
  { slug: "ukraine-vyshyvanka", country: "Ukraine", garment: "Vyshyvanka", level: "medium" },
  { slug: "morocco-djellaba", country: "Morocco", garment: "Djellaba", level: "medium" },
  { slug: "turkey-ottoman-dress", country: "Turkey", garment: "Traditional Turkish dress", level: "medium" },
  { slug: "indonesia-kebaya", country: "Indonesia", garment: "Kebaya", level: "medium" },
  { slug: "ireland-aran-dance", country: "Ireland", garment: "Irish step-dance dress", level: "medium" },
  { slug: "egypt-galabeya", country: "Egypt", garment: "Galabeya", level: "medium" },
  { slug: "kenya-maasai-dress", country: "Kenya", garment: "Maasai traditional dress", level: "medium" },
  { slug: "ghana-kente", country: "Ghana", garment: "Kente cloth attire", level: "medium" },
  { slug: "bolivia-cholita-dress", country: "Bolivia", garment: "Cholita traditional dress", level: "medium" },
  { slug: "guatemala-huipil", country: "Guatemala", garment: "Huipil", level: "medium" },
  { slug: "mongolia-deel", country: "Mongolia", garment: "Deel", level: "medium" },
  { slug: "bhutan-gho-kira", country: "Bhutan", garment: "Gho & Kira", level: "medium" },
  { slug: "sri-lanka-osariya", country: "Sri Lanka", garment: "Osariya", level: "medium" },
  { slug: "ethiopia-habesha-kemis", country: "Ethiopia", garment: "Habesha Kemis", level: "medium" },

  // HARD (14) — recognizable to culture/travel enthusiasts
  { slug: "romania-ie-blouse", country: "Romania", garment: "Ie blouse", level: "hard" },
  { slug: "hungary-folk-dress", country: "Hungary", garment: "Hungarian folk dress", level: "hard" },
  { slug: "slovakia-kroj", country: "Slovakia", garment: "Slovak folk costume", level: "hard" },
  { slug: "bulgaria-folk-dress", country: "Bulgaria", garment: "Bulgarian folk dress", level: "hard" },
  { slug: "serbia-folk-costume", country: "Serbia", garment: "Serbian folk costume", level: "hard" },
  { slug: "croatia-folk-costume", country: "Croatia", garment: "Croatian folk costume", level: "hard" },
  { slug: "nepal-daura-suruwal", country: "Nepal", garment: "Daura-Suruwal & Gunyu Cholo", level: "hard" },
  { slug: "cambodia-sampot", country: "Cambodia", garment: "Sampot", level: "hard" },
  { slug: "myanmar-longyi", country: "Myanmar", garment: "Longyi", level: "hard" },
  { slug: "senegal-boubou", country: "Senegal", garment: "Boubou", level: "hard" },
  { slug: "ivory-coast-traditional-dress", country: "Ivory Coast", garment: "Traditional Ivorian dress", level: "hard" },
  { slug: "madagascar-lamba", country: "Madagascar", garment: "Lamba", level: "hard" },
  { slug: "georgia-chokha", country: "Georgia", garment: "Chokha", level: "hard" },
  { slug: "armenia-taraz", country: "Armenia", garment: "Armenian Taraz", level: "hard" },

  // IMPOSSIBLE (9) — genuinely obscure even to enthusiasts
  { slug: "azerbaijan-traditional-dress", country: "Azerbaijan", garment: "Azerbaijani traditional dress", level: "impossible" },
  { slug: "uzbekistan-traditional-dress", country: "Uzbekistan", garment: "Uzbek traditional dress", level: "impossible" },
  { slug: "kazakhstan-traditional-dress", country: "Kazakhstan", garment: "Kazakh traditional dress", level: "impossible" },
  { slug: "kyrgyzstan-traditional-dress", country: "Kyrgyzstan", garment: "Kyrgyz traditional dress", level: "impossible" },
  { slug: "albania-folk-costume", country: "Albania", garment: "Albanian folk costume", level: "impossible" },
  { slug: "montenegro-folk-costume", country: "Montenegro", garment: "Montenegrin folk costume", level: "impossible" },
  { slug: "north-macedonia-folk-costume", country: "North Macedonia", garment: "Macedonian folk costume", level: "impossible" },
  { slug: "bosnia-folk-costume", country: "Bosnia and Herzegovina", garment: "Bosnian folk costume", level: "impossible" },
  { slug: "panama-pollera", country: "Panama", garment: "Pollera", level: "impossible" },
];
