export const TRADITIONAL_COSTUMES_E33_FACTS = {
  "japan-kimono": "Kimono literally means 'thing to wear' in Japanese.",
  "india-sari": "A sari is one unstitched cloth, unlike sewn Western dresses.",
  "scotland-kilt": "Clan tartans were only formally registered in the 1800s.",
  "mexico-china-poblana": "The China Poblana costume comes from the city of Puebla.",
  "south-korea-hanbok": "Hanbok designs varied by era, social class, and season.",
  "netherlands-volendam": "Volendam's lace cap sits over a metal frame called an oorijzer.",
  "germany-lederhosen": "Lederhosen were originally rugged workwear for farmers.",
  "china-qipao": "The qipao evolved from looser, straight-cut Manchu robes.",
  "spain-flamenco": "Flamenco dresses use ruffled layers called volantes.",
  "switzerland-tracht": "Swiss Tracht designs differ by canton, not just region.",
  "vietnam-ao-dai": "The áo dài is a long tunic worn over loose trousers.",
  "norway-bunad": "Norway has over 200 distinct regional bunad designs.",
  "austria-tracht": "Austrian Tracht inspired the modern dirndl dress style.",
  "greece-fustanella": "The fustanella is a pleated kilt-like skirt worn by men.",
  "philippines-barong": "Barong Tagalog shirts are traditionally sheer and untucked.",
  "thailand-silk-dress": "Thai silk dresses often use hand-woven mudmee silk.",
  "nigeria-agbada": "An agbada is a wide flowing robe worn over other garments.",
  "poland-folk-costume": "Polish folk costumes vary sharply by region, like Łowicz's stripes.",
  "russia-sarafan": "A sarafan is a long sleeveless dress worn over a blouse.",
  "ukraine-vyshyvanka": "Vyshyvanka embroidery once identified a wearer's home region.",
  "morocco-djellaba": "A djellaba is a loose hooded robe worn by men and women.",
  "turkey-ottoman-dress": "Ottoman court dress once signaled rank through color and fabric.",
  "indonesia-kebaya": "The kebaya is a fitted blouse traditionally paired with a sarong.",
  "ireland-aran-dance": "Irish dance dresses are heavily embroidered with Celtic patterns.",
  "egypt-galabeya": "A galabeya is a loose ankle-length robe common in rural Egypt.",
  "kenya-maasai-dress": "Maasai dress is famous for its bright red shuka cloth.",
  "ghana-kente": "Kente cloth patterns are woven, not printed, on narrow looms.",
  "bolivia-cholita-dress": "Cholita dress includes a bowler hat worn tilted to one side.",
  "guatemala-huipil": "Huipil patterns can identify a weaver's specific village.",
  "mongolia-deel": "A deel is a long robe tied with a sash, worn on horseback too.",
  "bhutan-gho-kira": "Bhutan requires citizens to wear the gho or kira in public buildings.",
  "sri-lanka-osariya": "The Kandyan osariya style drapes the sari's pleats at the front.",
  "ethiopia-habesha-kemis": "Habesha kemis is woven from a cotton fabric called shema.",
  "romania-ie-blouse": "The Romanian ie blouse inspired designs by Yves Saint Laurent.",
  "hungary-folk-dress": "Matyó embroidery from Hungary is UNESCO-listed heritage.",
  "slovakia-kroj": "Slovak folk skirts are famously full, needing many meters of fabric.",
  "bulgaria-folk-dress": "Bulgarian folk costumes vary sharply across the country's regions.",
  "serbia-folk-costume": "Serbian costume differs sharply between Šumadija and Vojvodina.",
  "croatia-folk-costume": "Croatia's folk costumes vary dramatically from village to village.",
  "nepal-daura-suruwal": "Nepal's daura has eight strings symbolizing eight goddesses.",
  "cambodia-sampot": "A sampot is wrapped and tucked with no buttons or zippers.",
  "myanmar-longyi": "Both men and women in Myanmar wear the longyi sarong daily.",
  "senegal-boubou": "A boubou is a wide flowing robe worn across West Africa.",
  "ivory-coast-traditional-dress": "Ivorian traditional dress often features vibrant wax-print fabric.",
  "madagascar-lamba": "A lamba is a single woven cloth wrapped around the body.",
  "georgia-chokha": "The chokha's chest pockets once held rifle cartridges.",
  "armenia-taraz": "Taraz embroidery favors floral and geometric ornament patterns.",
  "azerbaijan-traditional-dress": "Azerbaijani dress differs between mountain and lowland regions.",
  "uzbekistan-traditional-dress": "Uzbek dress often uses ikat fabric with blurred dye patterns.",
  "kazakhstan-traditional-dress": "Kazakh costume traditionally used felt and animal fur.",
  "kyrgyzstan-traditional-dress": "Kyrgyz women's headwear once showed marital status by shape.",
  "albania-folk-costume": "Albania has over 200 recorded regional costume variations.",
  "montenegro-folk-costume": "Montenegrin costume often pairs a red cap with gold embroidery.",
  "north-macedonia-folk-costume": "Macedonian costume embroidery often uses black and red thread.",
  "bosnia-folk-costume": "Bosnian costume design reflects Ottoman-era regional influence.",
  "panama-pollera": "A fine Panamanian pollera can take months to embroider by hand.",
};
