export const TROPHIES_E54_FACTS = {
  // EASY
  "fifa-world-cup-trophy": "Solid 18-karat gold; champions keep a gold-plated bronze replica.",
  "stanley-cup": "Winners' names are engraved on bands added to it every year.",
  "wimbledon-trophy": "Champions get a small replica; the silver cup stays at the club.",
  "uefa-champions-league-trophy": "Nicknamed 'Big Ears' for its two oversized curved handles.",
  "vince-lombardi-trophy": "Sterling silver; a brand-new trophy is cast for every Super Bowl.",
  "ballon-dor-trophy": "A gold-plated ball on a stand, awarded by France Football since 1956.",
  "claret-jug": "Officially the Golf Champion Trophy; first awarded in 1873.",
  "larry-obrien-trophy": "Cast in silver and gold vermeil fresh for every NBA season.",
  "fa-cup-trophy": "The current cup is actually the design's fourth version since 1871.",
  "copa-america-trophy": "South America's oldest continental title, contested since 1916.",
  "ryder-cup": "A small gold cup topped with a figure modeled on golfer Abe Mitchell.",
  "uefa-euro-trophy": "Named the Henri Delaunay Cup after the competition's founder.",
  "world-series-trophy": "Its gold flags each represent one Major League Baseball team.",
  "ashes-urn": "A tiny terracotta urn that never actually leaves its museum case.",

  // MEDIUM
  "webb-ellis-cup": "Named for the schoolboy credited with inventing rugby in 1823.",
  "wbc-championship-belt": "Its green leather championship belt design dates to 1963.",
  "americas-cup": "Sailing's oldest trophy, first won in 1851 as a silver ewer.",
  "davis-cup": "One of sport's largest trophies, with panels added most years.",
  "us-open-tennis-trophy": "Men's champions receive a solid silver cup first used in 1965.",
  "coupe-des-mousquetaires": "Named for four French tennis stars of the 1920s-30s.",
  "copa-libertadores-trophy": "South America's top club trophy, first awarded in 1960.",
  "europa-league-trophy": "Formerly the UEFA Cup; renamed for the 2009-10 season.",
  "womens-world-cup-trophy": "Introduced in 1999, its form echoes a victorious figure rising.",
  "cricket-world-cup-trophy": "A gold globe on three curved pillars, unveiled for the 1999 event.",
  "borg-warner-trophy": "Every Indy 500 winner's face is sculpted onto its silver body.",
  "heisman-trophy": "Its stiff-arm pose was modeled on a 1930s college running back.",
  "icc-t20-world-cup-trophy": "A silver trophy with fanned blades, introduced for the 2007 event.",
  "afcon-trophy": "Redesigned in 2021 after the original was retired to a museum.",
  "premier-league-trophy": "Topped by a golden crown with three lions above a ball.",

  // HARD
  "kentucky-derby-trophy": "A solid gold trophy topped with a rearing horse statuette.",
  "concacaf-gold-cup-trophy": "Introduced in 1991, replacing the old CONCACAF Championship.",
  "f1-constructors-trophy": "One trophy gets engraved yearly with every champion team since 1958.",
  "norman-brookes-challenge-cup": "Named for the Australian Open's first men's singles champion.",
  "copa-del-rey-trophy": "Spain's oldest football trophy, first awarded back in 1903.",
  "dfb-pokal": "Germany's cup trophy stands atop a rotating wooden base.",
  "world-snooker-trophy": "Awarded each year at Sheffield's Crucible Theatre since 1977.",
  "fifa-club-world-cup-trophy": "A silver ball resting atop a rising column, introduced in 2000.",
  "six-nations-trophy": "Engraved with the emblems of all six competing nations.",
  "nascar-cup-trophy": "A modern glass and chrome trophy that replaced the old Cup in 2004.",
  "bundesliga-meisterschale": "Nicknamed the 'Salad Bowl' for its wide, flat plate shape.",

  // IMPOSSIBLE
  "afc-asian-cup-trophy": "Redesigned in 2019 with a taller, more modern silver form.",
  "grey-cup": "Canada's oldest sports trophy, first awarded back in 1909.",
  "bledisloe-cup": "A silver cup named for a New Zealand governor-general.",
  "le-mans-trophy": "Its design changes yearly; only the winner keeps a replica.",
  "naismith-trophy": "Named for basketball's inventor, awarded at the FIBA World Cup.",
  "afl-premiership-cup": "A fresh silver cup is awarded to each AFL Grand Final winner.",
  "heineken-champions-cup": "Rugby's top club trophy, first awarded back in 1996.",
  "fedex-cup-trophy": "A season-long golf points race decides who lifts this trophy.",
  "billie-jean-king-cup": "Tennis's top women's team trophy, renamed in her honor in 2020.",
  "atp-finals-trophy": "Awarded to the winner of tennis's season-ending championship.",
  "mls-cup-trophy": "Named the Philip F. Anschutz Trophy after a league investor.",
  "sam-maguire-cup": "Modeled on an ancient Irish chalice; awarded since 1928.",
};
