export const US_STATE_FLAGS_E42_FACTS = {
  "texas": "Its single star gave Texas its nickname: the Lone Star State.",
  "california": "Shows a grizzly bear, a species now extinct in the wild there.",
  "hawaii": "Only U.S. state flag bearing Britain's Union Jack, from colonial ties.",
  "arizona": "13 copper-colored rays represent the original colonies and a sunset.",
  "new-mexico": "Its red Zia sun symbol comes from the Zia Pueblo people.",
  "ohio": "The only non-rectangular U.S. state flag; it's a swallowtail burgee.",
  "maryland": "Merges the Calvert and Crossland families' two heraldic coats of arms.",
  "south-carolina": "Its crescent copies soldiers' silver cap emblems, not a moon.",
  "alaska": "Designed by teenager Benny Benson in a 1927 territorial contest.",
  "colorado": "A red 'C' encircles a gold disk symbolizing abundant sunshine.",

  "tennessee": "Three stars in an unbroken circle mark its three Grand Divisions.",
  "florida": "A red saltire was added in 1900 so it wouldn't resemble surrender.",
  "alabama": "Its crimson cross's exact shade was never legally defined.",
  "louisiana": "A mother pelican wounds her breast to feed her three chicks.",
  "utah": "A gold ring frames a beehive, symbol of the 'Beehive State.'",
  "nevada": "A silver star ringed by sagebrush honors its Civil War statehood.",
  "oklahoma": "An Osage shield holds a peace pipe crossed with an olive branch.",
  "oregon": "The only U.S. state flag with different art on each side.",
  "washington": "Only U.S. state flag with a green field and a real person's portrait.",
  "kansas": "A sunflower, the state flower, was added above the seal in 1927.",
  "wyoming": "A white bison carries the state seal branded on its side.",
  "georgia": "Its blue canton holds the state seal ringed by 13 colony stars.",
  "mississippi": "Its 2020 magnolia is ringed by 21 stars, one for native peoples.",
  "puerto-rico": "Designed in 1895 exile, it mirrors Cuba's flag with colors reversed.",
  "indiana": "A gold torch stands for liberty, ringed by 19 stars for statehood.",
  "virginia": "Shows Virtus standing over a fallen tyrant, spear and sword raised.",

  "illinois": "The word 'ILLINOIS' was added in 1970, after a sailor's petition.",
  "michigan": "An elk and moose flank a shield beneath an eagle with olive branch.",
  "minnesota": "Its 2024 redesign swapped the old seal for an 8-point North Star.",
  "wisconsin": "A badger tops a shield flanked by a sailor and a miner.",
  "iowa": "Its blue-white-red tricolor echoes France's flag from colonial ties.",
  "nebraska": "Shows a blacksmith and steamboat; law never fixed its exact colors.",
  "north-dakota": "Nearly copies the state's WWI-era Army infantry regiment flag.",
  "south-dakota": "Sun rays surround the seal; 'Mount Rushmore State' was added in 1992.",
  "missouri": "Two grizzly bears support a shield ringed by 24 stars for statehood.",
  "kentucky": "A frontiersman and statesman clasp hands beneath goldenrod sprigs.",
  "arkansas": "The only diamond-shaped U.S. flag, honoring its diamond mines.",
  "pennsylvania": "Two black draft horses flank a shield crowned by an eagle.",
  "new-jersey": "Its buff-tan field is topped by a horse's head crest.",
  "delaware": "Its colors match Washington's own Continental Army uniform.",
  "connecticut": "Three grapevines on a shield symbolize its early colonies.",
  "rhode-island": "A single gold anchor sits beneath the word 'Hope' on blue.",
  "vermont": "A pine tree, cow, and wheat sheaves sit on its coat of arms.",
  "west-virginia": "A farmer and miner flank the seal, ringed by rhododendron.",
  "north-carolina": "Displays two dates from its early independence declarations.",
  "district-of-columbia": "Its three red stars and two bars come from Washington's family crest.",

  "new-hampshire": "Seal shows the frigate Raleigh, built in Portsmouth in 1776.",
  "maine": "A farmer and sailor flank a pine tree shield under the word 'Dirigo.'",
  "massachusetts": "Its blue shield shows a figure beneath a sword-wielding arm crest.",
  "idaho": "Its seal is the only U.S. state seal designed by a woman.",
  "montana": "State seal shows Montana's Great Falls, mountains, and mining tools.",
  "new-york": "Liberty and Justice flank a shield under an eagle on a globe.",
  "guam": "Its almond-shaped seal shows a canoe and sling stone on a beach.",
  "american-samoa": "An eagle clutches a Samoan fly-whisk and staff, blending two cultures.",
  "us-virgin-islands": "A simplified U.S. eagle crest sits between the letters 'V' and 'I.'",
  "northern-mariana-islands": "A gray latte stone, an ancient Chamorro pillar, is topped by a star.",
};
