export const VEGETABLES_E74_FACTS = {
  "potato": "Botanically a tuber, not a root, of the nightshade family.",
  "tomato": "Botanically a fruit, though legally classed as a vegetable in the US.",
  "carrot": "The earliest cultivated carrots were purple and yellow, not orange.",
  "onion": "Its sulfur compounds are what make you cry while cutting it.",
  "broccoli": "A cultivated variety bred specifically from wild cabbage.",
  "cucumber": "Made up of about 95% water.",
  "lettuce": "Its name comes from the Latin word for milk, lactuca.",
  "cabbage": "A close relative of broccoli, kale, and Brussels sprouts.",
  "bell-pepper": "One of the few peppers with no capsaicin, so it isn't spicy.",
  "corn": "Each ear typically has an even number of rows of kernels.",
  "garlic": "A member of the allium family, related to onions and leeks.",
  "spinach": "Popeye's favorite food, said to boost strength.",
  "mushroom": "Not a plant at all — it's a fungus.",
  "pumpkin": "Botanically a fruit, technically a type of squash.",
  "zucchini": "Actually a fruit, since it grows from a flowering plant's ovary.",
  "eggplant": "Named for early white varieties that looked like goose eggs.",
  "celery": "One of the lowest-calorie vegetables, at about six calories a stalk.",
  "cauliflower": "Its white color comes from leaves shielding it from sunlight.",
  "sweet-potato": "Not related to the regular potato at all.",
  "radish": "One of the fastest-growing vegetables, ready in under a month.",
  "beet": "Its deep red pigment can turn your urine pink after eating it.",
  "asparagus": "Can grow several inches in a single day under ideal conditions.",
  "brussels-sprout": "Named after the Belgian capital where it was widely cultivated.",
  "leek": "The national emblem of Wales.",
  "artichoke": "The edible part is actually an unopened flower bud.",
  "green-bean": "Also called a string bean for the fiber once common along its seam.",
  "pea": "One of the oldest cultivated crops, grown for over 10,000 years.",
  "butternut-squash": "Named for its smooth, nutty-flavored orange flesh.",
  "kale": "A leafy variety of cabbage that doesn't form a head.",
  "turnip": "Its leafy greens are edible too, often cooked as turnip greens.",
  "okra": "Its pods release a sticky substance often used to thicken stews.",
  "fennel": "Has a mild licorice-like flavor from its anise-like compounds.",
  "bok-choy": "A type of Chinese cabbage that doesn't form a tight head.",
  "chili-pepper": "Its heat is measured on the Scoville scale.",
  "parsnip": "Looks like a pale carrot but tastes sweeter and nuttier.",
  "ginger": "Actually an underground stem, called a rhizome, not a root.",
  "kohlrabi": "Its name comes from German words for cabbage and turnip.",
  "daikon": "A giant white radish common in Japanese and Korean cooking.",
  "rutabaga": "Believed to be a natural cross between cabbage and turnip.",
  "endive": "A leafy vegetable often grown in complete darkness to stay pale.",
  "watercress": "One of the most nutrient-dense leafy greens known.",
  "jicama": "Often eaten raw for its crisp, slightly sweet, apple-like texture.",
  "chayote": "A type of squash originally domesticated in Mesoamerica.",
  "napa-cabbage": "The main ingredient in traditional Korean kimchi.",
  "swiss-chard": "Despite its name, it originated in the Mediterranean, not Switzerland.",
  "yam": "In parts of West Africa, it's a staple crop and cultural symbol.",
  "taro": "Its corm must be cooked before eating to remove natural toxins.",
  "water-chestnut": "Not a nut at all, but the corm of an aquatic plant.",
  "bamboo-shoot": "Harvested young, before the plant hardens into woody bamboo.",
  "bitter-melon": "Prized in many Asian cuisines despite its intensely bitter taste.",
  "snow-pea": "Eaten pod and all, unlike garden peas which are shelled.",
  "collard-greens": "A staple in Southern US cooking, especially on New Year's Day.",
  "celeriac": "Grown for its knobby root, not for stalks like regular celery.",
  "fiddlehead-fern": "The tightly coiled young shoot of certain fern species.",
  "purslane": "A succulent weed in many gardens that's also edible and nutritious.",
  "sunchoke": "Not related to Jerusalem or artichokes — it's a sunflower relative.",
  "horseradish": "Its pungent heat comes from the same compound family as mustard.",
  "sea-kale": "A coastal plant historically foraged along European shorelines.",
  "water-spinach": "A fast-growing green often stir-fried whole, stems and all.",
  "yardlong-bean": "Can grow pods reaching nearly a meter, or three feet, in length.",
  "malabar-spinach": "A vining plant unrelated to true spinach despite the name.",
  "tatsoi": "A small, dark-leafed Asian green often arranged in a flat rosette.",
  "mizuna": "A feathery Japanese mustard green with a peppery bite.",
  "winter-melon": "Its thick waxy skin lets it store for months without spoiling.",
  "gai-lan": "Also called Chinese broccoli, prized for its thick tender stems.",
  "kabocha": "A Japanese winter squash with a naturally sweet, dense flesh.",
  "delicata-squash": "Known as the sweet potato squash for its creamy texture.",
  "cassava": "A starchy root that's a staple food for over 800 million people.",
  "turmeric": "Its bright orange flesh comes from the compound curcumin.",
  "amaranth-greens": "Related to grain amaranth, but this species is grown for its leaves.",
};
