// E74 "Guess the Vegetable" — 70 real vegetables, easy->impossible. Distinct from the legacy
// E21 "Guess the Fruit or Vegetable" mixed-classification quiz (old v1 engine) and from
// E43 "Guess the Fruit" (fruits only) — this is a dedicated vegetable-recognition quiz.
export const VEGETABLES_E74 = [
  // EASY (18)
  { slug: "potato", name: "Potato", wiki: "Potato", level: "easy" },
  { slug: "tomato", name: "Tomato", wiki: "Tomato", level: "easy" },
  { slug: "carrot", name: "Carrot", wiki: "Carrot", level: "easy" },
  { slug: "onion", name: "Onion", wiki: "Onion", level: "easy" },
  { slug: "broccoli", name: "Broccoli", wiki: "Broccoli", level: "easy" },
  { slug: "cucumber", name: "Cucumber", wiki: "Cucumber", level: "easy" },
  { slug: "lettuce", name: "Lettuce", wiki: "Lettuce", level: "easy" },
  { slug: "cabbage", name: "Cabbage", wiki: "Cabbage", level: "easy" },
  { slug: "bell-pepper", name: "Bell Pepper", wiki: "Bell pepper", level: "easy" },
  { slug: "corn", name: "Corn", wiki: "Maize", level: "easy" },
  { slug: "garlic", name: "Garlic", wiki: "Garlic", level: "easy" },
  { slug: "spinach", name: "Spinach", wiki: "Spinach", level: "easy" },
  { slug: "mushroom", name: "Mushroom", wiki: "Edible mushroom", level: "easy" },
  { slug: "pumpkin", name: "Pumpkin", wiki: "Pumpkin", level: "easy" },
  { slug: "zucchini", name: "Zucchini", wiki: "Zucchini", level: "easy" },
  { slug: "eggplant", name: "Eggplant", wiki: "Eggplant", level: "easy" },
  { slug: "celery", name: "Celery", wiki: "Celery", level: "easy" },
  { slug: "cauliflower", name: "Cauliflower", wiki: "Cauliflower", level: "easy" },

  // MEDIUM (18)
  { slug: "sweet-potato", name: "Sweet Potato", wiki: "Sweet potato", level: "medium" },
  { slug: "radish", name: "Radish", wiki: "Radish", level: "medium" },
  { slug: "beet", name: "Beetroot", wiki: "Beetroot", level: "medium" },
  { slug: "asparagus", name: "Asparagus", wiki: "Asparagus", level: "medium" },
  { slug: "brussels-sprout", name: "Brussels Sprout", wiki: "Brussels sprout", level: "medium" },
  { slug: "leek", name: "Leek", wiki: "Leek", level: "medium" },
  { slug: "artichoke", name: "Artichoke", wiki: "Artichoke", level: "medium" },
  { slug: "green-bean", name: "Green Bean", wiki: "Green bean", level: "medium" },
  { slug: "pea", name: "Pea", wiki: "Pea", level: "medium" },
  { slug: "butternut-squash", name: "Butternut Squash", wiki: "Butternut squash", level: "medium" },
  { slug: "kale", name: "Kale", wiki: "Kale", level: "medium" },
  { slug: "turnip", name: "Turnip", wiki: "Turnip", level: "medium" },
  { slug: "okra", name: "Okra", wiki: "Okra", level: "medium" },
  { slug: "fennel", name: "Fennel", wiki: "Fennel", level: "medium" },
  { slug: "bok-choy", name: "Bok Choy", wiki: "Bok choy", level: "medium" },
  { slug: "chili-pepper", name: "Chili Pepper", wiki: "Chili pepper", level: "medium" },
  { slug: "parsnip", name: "Parsnip", wiki: "Parsnip", level: "medium" },
  { slug: "ginger", name: "Ginger", wiki: "Ginger", level: "medium" },

  // HARD (16)
  { slug: "kohlrabi", name: "Kohlrabi", wiki: "Kohlrabi", level: "hard" },
  { slug: "daikon", name: "Daikon", wiki: "Daikon", level: "hard" },
  { slug: "rutabaga", name: "Rutabaga", wiki: "Rutabaga", level: "hard" },
  { slug: "endive", name: "Endive", wiki: "Endive", level: "hard" },
  { slug: "watercress", name: "Watercress", wiki: "Watercress", level: "hard" },
  { slug: "jicama", name: "Jicama", wiki: "Jicama", level: "hard" },
  { slug: "chayote", name: "Chayote", wiki: "Chayote", level: "hard" },
  { slug: "napa-cabbage", name: "Napa Cabbage", wiki: "Napa cabbage", level: "hard" },
  { slug: "swiss-chard", name: "Swiss Chard", wiki: "Chard", level: "hard" },
  { slug: "yam", name: "Yam", wiki: "Yam (vegetable)", level: "hard" },
  { slug: "taro", name: "Taro", wiki: "Taro", level: "hard" },
  { slug: "water-chestnut", name: "Water Chestnut", wiki: "Water chestnut", level: "hard" },
  { slug: "bamboo-shoot", name: "Bamboo Shoot", wiki: "Bamboo shoot", level: "hard" },
  { slug: "bitter-melon", name: "Bitter Melon", wiki: "Bitter melon", level: "hard" },
  { slug: "snow-pea", name: "Snow Pea", wiki: "Snow pea", level: "hard" },
  { slug: "collard-greens", name: "Collard Greens", wiki: "Collard (plant)", level: "hard" },

  // IMPOSSIBLE (18)
  { slug: "celeriac", name: "Celeriac", wiki: "Celeriac", level: "impossible" },
  { slug: "fiddlehead-fern", name: "Fiddlehead Fern", wiki: "Fiddlehead fern", level: "impossible" },
  { slug: "purslane", name: "Purslane", wiki: "Purslane", level: "impossible" },
  { slug: "sunchoke", name: "Sunchoke", wiki: "Jerusalem artichoke", level: "impossible" },
  { slug: "horseradish", name: "Horseradish", wiki: "Horseradish", level: "impossible" },
  { slug: "sea-kale", name: "Sea Kale", wiki: "Crambe maritima", level: "impossible" },
  { slug: "water-spinach", name: "Water Spinach", wiki: "Ipomoea aquatica", level: "impossible" },
  { slug: "yardlong-bean", name: "Yardlong Bean", wiki: "Vigna unguiculata subsp. sesquipedalis", level: "impossible" },
  { slug: "malabar-spinach", name: "Malabar Spinach", wiki: "Basella alba", level: "impossible" },
  { slug: "tatsoi", name: "Tatsoi", wiki: "Tatsoi", level: "impossible" },
  { slug: "mizuna", name: "Mizuna", wiki: "Mizuna", level: "impossible" },
  { slug: "winter-melon", name: "Winter Melon", wiki: "Wax gourd", level: "impossible" },
  { slug: "gai-lan", name: "Gai Lan", wiki: "Gai lan", level: "impossible" },
  { slug: "kabocha", name: "Kabocha", wiki: "Kabocha", level: "impossible" },
  { slug: "delicata-squash", name: "Delicata Squash", wiki: "Delicata squash", level: "impossible" },
  { slug: "cassava", name: "Cassava", wiki: "Cassava", level: "impossible" },
  { slug: "turmeric", name: "Turmeric Root", wiki: "Turmeric", level: "impossible" },
  { slug: "amaranth-greens", name: "Amaranth Greens", wiki: "Amaranthus tricolor", level: "impossible" },
];
export default VEGETABLES_E74;
