// Episode 11 "Guess the Video Game Character" — one verified <=70-char fact per item, keyed by slug.
export const VIDEO_GAME_CHARACTERS_E11_FACTS = {
  mario: "Mario first appeared as 'Jumpman' in Donkey Kong in 1981.",
  luigi: "Luigi is Mario's younger twin brother, introduced in 1983.",
  "princess-peach": "Princess Peach got her own starring game in 2005.",
  bowser: "Bowser is officially the King of the Koopas.",
  "sonic-the-hedgehog": "Sonic can run at speeds beyond the speed of sound.",
  pikachu: "Pikachu is the mascot of the entire Pokémon franchise.",
  "pac-man": "Pac-Man was originally called 'Puck Man' in Japan.",
  "lara-croft": "Lara Croft first appeared in Tomb Raider in 1996.",
  link: "Link almost never speaks in his own games.",
  "master-chief": "Master Chief's real name is John-117.",
  kratos: "Kratos was once a Spartan general before becoming a god.",
  "steve-minecraft": "Steve is Minecraft's original default playable character.",
  "donkey-kong": "Donkey Kong debuted as Mario's rival in a 1981 arcade game.",
  ryu: "Ryu is the original main character of Street Fighter.",
  "chun-li": "Chun-Li was one of fighting games' first female characters.",
  scorpion: "Scorpion's catchphrase 'Get over here!' is iconic in Mortal Kombat.",
  "sub-zero": "Sub-Zero can freeze enemies solid with ice powers.",
  yoshi: "Yoshi first appeared in Super Mario World in 1990.",
  "crash-bandicoot": "Crash Bandicoot was mutated by an evil scientist.",
  "solid-snake": "Solid Snake is a soldier famous for stealth, not combat.",
  "cloud-strife": "Cloud Strife wields an oversized sword called the Buster Sword.",
  kirby: "Kirby can swallow enemies to copy their abilities.",
  "samus-aran": "Samus Aran wears a powered exosuit called the Power Suit.",
  "geralt-of-rivia": "Geralt is a monster hunter known as a witcher.",
  "nathan-drake": "Nathan Drake is a treasure hunter inspired by pulp adventure heroes.",
  "ellie-last-of-us": "Ellie is immune to the infection in The Last of Us.",
  "arthur-morgan": "Arthur Morgan rides with the Van der Linde gang.",
  "agent-47": "Agent 47 is a genetically engineered assassin.",
  "doom-slayer": "The Doom Slayer is known simply for fighting demons alone.",
  "vault-boy": "Vault Boy is Fallout's cheerful, thumbs-up Vault-Tec mascot.",
  dante: "Dante is a half-demon devil hunter armed with dual pistols.",
  "leon-s-kennedy": "Leon Kennedy's first day as a cop was a zombie outbreak.",
  rayman: "Rayman has no arms or legs attached to his body.",
  "spyro-the-dragon": "Spyro is a small purple dragon who breathes fire.",
  sans: "Sans is known for his laid-back attitude and puns.",
  "freddy-fazbear": "Freddy Fazbear is an animatronic bear that turns hostile at night.",
  sephiroth: "Sephiroth was once hailed as a legendary war hero.",
  "ezio-auditore": "Ezio Auditore is a master assassin from Renaissance Italy.",
  bayonetta: "Bayonetta is a witch who fights angels with guns on her heels.",
  "chris-redfield": "Chris Redfield is a founding member of an elite bio-terror unit.",
  "big-daddy": "Big Daddies protect little girls known as Little Sisters.",
  isabelle: "Isabelle is a secretary dog character in Animal Crossing.",
  sackboy: "Sackboy is made of burlap sack material in LittleBigPlanet.",
  "gordon-freeman": "Gordon Freeman never speaks a single line in his games.",
  cortana: "Cortana is an AI companion who guides Master Chief.",
  "marcus-fenix": "Marcus Fenix fights giant subterranean monsters called Locust.",
  aloy: "Aloy hunts robotic creatures in a post-apocalyptic world.",
  banjo: "Banjo the bear teams up with a bird named Kazooie.",
  ratchet: "Ratchet is a Lombax who teams up with a robot named Clank.",
  claptrap: "Claptrap is a chatty one-wheeled robot in Borderlands.",
  "nier-2b": "2B is an android soldier fighting to protect humanity's remnant.",
  ganondorf: "Ganondorf is the Zelda series' recurring king of evil.",
  wario: "Wario is Mario's greedy, garlic-loving rival.",
  sora: "Sora wields a giant key-shaped weapon called a Keyblade.",
  "guybrush-threepwood": "Guybrush Threepwood dreams of becoming a mighty pirate.",
  "max-sam-and-max": "Max is a hyperactive rabbity-thing detective sidekick.",
  alucard: "Alucard is Dracula's son who fights against his own father.",
  wander: "Wander must defeat sixteen giant colossi to revive someone.",
  "corvo-attano": "Corvo Attano is framed for a murder he didn't commit.",
  "big-boss": "Big Boss is the legendary soldier also known as Naked Snake.",
  "revolver-ocelot": "Revolver Ocelot can fire two revolvers at once.",
  "squall-leonhart": "Squall Leonhart fights with a gunblade, part sword, part firearm.",
  conker: "Conker is a foul-mouthed squirrel on a quest for cash.",
  "earthworm-jim": "Earthworm Jim gained his powers from a supersuit.",
  "sam-fisher": "Sam Fisher is a covert operative for a fictional NSA black-ops unit.",
  jak: "Jak was mutated by dark eco as a baby.",
  "q-bert": "Q*bert hops across a pyramid of cubes changing their colors.",
  bomberman: "Bomberman plants bombs to blast through maze-like stages.",
  ori: "Ori is a guardian spirit who restores light to a dying forest.",
  cuphead: "Cuphead made a deal with the devil he must pay off.",
  "duke-nukem": "Duke Nukem is known for one-liners as much as gunfights.",
};
export default VIDEO_GAME_CHARACTERS_E11_FACTS;
