// Episode 16 "Guess the Volcano" — one verified <=70-char fact per item, keyed by slug.
export const VOLCANOES_E16_FACTS = {
  "mount-fuji": "Mount Fuji last erupted in 1707 and is still active today.",
  "santorini-volcano": "Santorini's caldera formed from a massive Bronze Age eruption.",
  "mount-st-helens": "Mount St. Helens' 1980 eruption blew off its entire north face.",
  "krakatoa": "Krakatoa's 1883 eruption was heard nearly 3,000 miles away.",
  "eyjafjallajokull": "Eyjafjallajökull's 2010 ash cloud grounded flights across Europe.",
  "mount-pinatubo": "Mount Pinatubo's 1991 eruption cooled global temperatures briefly.",
  "whakaari-white-island": "Whakaari is New Zealand's most active volcano.",
  "stromboli": "Stromboli has erupted almost continuously for over 2,000 years.",
  "mount-teide": "Mount Teide is Spain's tallest peak, on the island of Tenerife.",
  "villarrica-volcano": "Villarrica is one of Chile's most active volcanoes.",
  "nevado-del-ruiz": "Nevado del Ruiz's 1985 eruption triggered a deadly mudslide.",
  "arenal-volcano": "Arenal Volcano was dormant for centuries before erupting in 1968.",
  "klyuchevskaya-sopka": "Klyuchevskaya Sopka is the tallest active volcano in Eurasia.",
  "hunga-tonga": "Hunga Tonga's 2022 eruption sent a shockwave around the globe.",
  "volcan-de-fuego": "Volcán de Fuego means 'volcano of fire' in Spanish.",
  "mont-pelee": "Mont Pelée's 1902 eruption destroyed the city of Saint-Pierre.",
  "erta-ale": "Erta Ale holds one of the world's few permanent lava lakes.",
  "la-soufriere-st-vincent": "La Soufrière erupted explosively as recently as 2021.",
  "kilauea": "Kilauea is one of the most active volcanoes on Earth.",
  "taal-volcano": "Taal Volcano sits on an island inside a lake inside an island.",
  "mount-tambora": "Mount Tambora's 1815 eruption was the largest in recorded history.",
  "sakurajima": "Sakurajima erupts small ash clouds almost daily.",
  "fagradalsfjall": "Fagradalsfjall erupted in 2021 after lying dormant for 6,000 years.",
  "osorno-volcano": "Osorno's snow-capped cone resembles Japan's Mount Fuji.",
  "poas-volcano": "Poás Volcano has one of the world's largest acidic crater lakes.",
  "ol-doinyo-lengai": "Ol Doinyo Lengai erupts unusual black, cool-flowing lava.",
  "galeras": "Galeras looms directly over the Colombian city of Pasto.",
  "cerro-negro": "Cerro Negro is one of the youngest volcanoes in Central America.",
  "colima-volcano": "Colima Volcano is one of Mexico's most active volcanoes.",
  "el-misti": "El Misti towers above the Peruvian city of Arequipa.",
  "sangay": "Sangay is one of the world's most continuously active volcanoes.",
  "piton-de-la-fournaise": "Piton de la Fournaise erupts nearly every year.",
  "izalco": "Izalco was once nicknamed the 'Lighthouse of the Pacific.'",
  "karthala": "Karthala holds one of the largest volcanic craters on Earth.",
  "pico-do-fogo": "Pico do Fogo means 'peak of fire' in Portuguese.",
  "tavurvur": "Tavurvur's 1994 eruption buried much of Rabaul in ash.",
  "mauna-loa": "Mauna Loa is the largest active volcano on Earth by volume.",
  "mount-unzen": "Mount Unzen's 1991 eruption produced deadly pyroclastic flows.",
  "masaya-volcano": "Masaya Volcano has an active lava lake visible from its rim.",
  "paricutin": "Paricutín grew from a cornfield, starting suddenly in 1943.",
  "kawah-ijen": "Kawah Ijen glows blue at night from burning sulfur gas.",
  "tungurahua": "Tungurahua's name means 'throat of fire' in Quechua.",
  "yasur": "Yasur has erupted almost continuously for centuries.",
  "mount-longonot": "Mount Longonot's crater can be hiked in a few hours.",
  "nyamuragira": "Nyamuragira is one of Africa's most active volcanoes.",
  "manam": "Manam is an active volcano forming its own small island.",
  "mount-erciyes": "Mount Erciyes overlooks Turkey's Cappadocia region.",
  "vulcano-island": "Vulcano gave its name to all volcanoes in the English language.",
  "chaiten-volcano": "Chaitén surprised scientists by erupting suddenly in 2008.",
  "sulphur-springs-st-lucia": "Sulphur Springs is nicknamed the world's only drive-in volcano.",
  "kanlaon": "Kanlaon is the most active volcano on Negros Island.",
  "katla": "Katla lies hidden beneath an Icelandic glacier.",
  "puy-de-dome": "Puy de Dôme is a dormant lava dome in central France.",
  "cumbre-vieja": "Cumbre Vieja erupted for 85 days straight on La Palma in 2021.",
  "ambrym": "Ambrym holds two of the world's most active lava lakes.",
  "ulawun": "Ulawun is the highest mountain on the island of New Britain.",
  "sierra-negra-galapagos": "Sierra Negra has one of the largest craters in the Galápagos.",
  "laacher-see": "Laacher See is a volcanic lake formed 13,000 years ago.",
  "furnas-volcano": "Furnas Volcano heats natural hot springs on São Miguel island.",
  "uturuncu": "Uturuncu's underground magma bulge puzzles scientists.",
  "domuyo": "Domuyo is the tallest volcano in Argentine Patagonia.",
  "menengai": "Menengai holds one of the largest volcanic calderas in Africa.",
  "tolbachik": "Tolbachik erupted for nearly nine months straight starting in 2012.",
  "beerenberg": "Beerenberg is the world's northernmost active volcano.",
  "nevis-peak": "Nevis Peak has had no eruption in recorded history.",
  "morne-trois-pitons": "Morne Trois Pitons gave its name to a UNESCO rainforest park.",
  "mount-aragats": "Mount Aragats is the tallest peak in Armenia.",
  "big-ben-heard-island": "Big Ben sits on a remote Australian island near Antarctica.",
  "ceboruco": "Ceboruco last erupted in the early 1870s in Mexico.",
  "barren-island": "Barren Island is the only active volcano in South Asia.",
  "wudalianchi": "Wudalianchi's lava fields formed lakes across five basins.",
};
