// Episode 18 "Guess the Waterfall" — one verified <=70-char fact per item, keyed by slug.
export const WATERFALLS_E18_FACTS = {
  "niagara-falls": "Niagara Falls moves over 3,000 tons of water every second.",
  "victoria-falls": "Locals call Victoria Falls 'the smoke that thunders.'",
  "angel-falls": "Angel Falls is the world's tallest uninterrupted waterfall.",
  "gullfoss": "Gullfoss drops in two stages into a deep, narrow canyon.",
  "yosemite-falls": "Yosemite Falls is North America's tallest waterfall.",
  "rhine-falls": "Rhine Falls is Europe's most powerful waterfall by water volume.",
  "plitvice-falls": "Plitvice's lakes and falls are famous for turquoise water.",
  "jog-falls": "Jog Falls plunges in four separate distinct streams.",
  "huangguoshu-falls": "Huangguoshu Falls has a walkable cave behind its curtain.",
  "kaieteur-falls": "Kaieteur Falls is one of the world's most powerful falls.",
  "sutherland-falls": "Sutherland Falls drops in three giant leaps down a valley.",
  "marmore-falls": "Cascata delle Marmore was originally built by the ancient Romans.",
  "kegon-falls": "Kegon Falls drops from an ancient volcanic lake outlet.",
  "voringsfossen": "Vøringsfossen is one of Norway's most visited waterfalls.",
  "gocta-falls": "Gocta Falls stayed unknown outside Peru until a 2006 expedition.",
  "powerscourt-waterfall": "Powerscourt Waterfall is Ireland's tallest waterfall.",
  "erawan-falls": "Erawan Falls has seven tiers of turquoise pools.",
  "dunns-river-falls": "Visitors climb Dunn's River Falls in a human chain.",
  "havasu-falls": "Havasu Falls' blue-green color comes from dissolved minerals.",
  "skogafoss": "Skógafoss often produces a full rainbow on sunny days.",
  "krka-falls": "Krka Falls once powered one of Europe's earliest hydroelectric plants.",
  "kravica-falls": "Kravica Falls resembles a smaller version of Niagara Falls.",
  "tugela-falls": "Tugela Falls drops in five dramatic free-falling stages.",
  "blue-nile-falls": "Blue Nile Falls is nicknamed 'water that smokes.'",
  "murchison-falls": "Murchison Falls squeezes the Nile through a narrow gorge.",
  "diyaluma-falls": "Diyaluma is one of Sri Lanka's tallest waterfalls.",
  "cheonjeyeon-falls": "Cheonjeyeon means 'pond of God' in Korean.",
  "tegenungan-waterfall": "Tegenungan Waterfall became famous through Bali social media.",
  "kawasan-falls": "Kawasan Falls is known for its bright turquoise water.",
  "basaseachic-falls": "Basaseachic Falls sits within a deep volcanic canyon.",
  "la-fortuna-waterfall": "La Fortuna Waterfall sits near an active volcano.",
  "tequendama-falls": "Tequendama Falls has inspired local ghost legends for centuries.",
  "pailon-del-diablo": "Pailón del Diablo means 'The Devil's Cauldron' in Spanish.",
  "duden-waterfalls": "Düden Waterfalls empties dramatically straight into the sea.",
  "thomsons-falls": "Thomson's Falls was named after a 19th-century explorer.",
  "zongo-falls": "Zongo Falls drops 65 meters on the Inkisi River near Kinshasa.",
  "multnomah-falls": "Multnomah Falls drops in two tiers beneath a stone footbridge.",
  "seljalandsfoss": "Seljalandsfoss lets visitors walk behind its curtain of water.",
  "dudhsagar-falls": "Dudhsagar means 'sea of milk' for its frothy white water.",
  "nachi-falls": "Nachi Falls is worshipped as a sacred Shinto site.",
  "hukou-waterfalls": "Hukou Waterfalls is the largest yellow waterfall on Earth.",
  "latefossen": "Låtefossen is actually twin waterfalls joining as one.",
  "takakkaw-falls": "Takakkaw means 'it is magnificent' in the Cree language.",
  "kinchkha-waterfall": "Kinchkha Waterfall sits inside a lush Georgian canyon.",
  "baatara-gorge-waterfall": "Baatara Gorge Waterfall drops through a natural stone bridge.",
  "kalambo-falls": "Kalambo Falls stands more than twice as tall as Victoria Falls.",
  "wli-waterfalls": "Wli is the tallest waterfall in West Africa.",
  "savica-falls": "Savica Falls feeds the glacial Lake Bohinj below.",
  "khone-phapheng-falls": "Khone Phapheng is the widest waterfall in Southeast Asia.",
  "kalandula-falls": "Kalandula Falls is among Africa's largest waterfalls by volume.",
  "davis-falls": "Davis Falls is named after a Swiss tourist's tragic accident.",
  "elephant-waterfalls": "Elephant Waterfalls got its name from an elephant-shaped rock.",
  "sipi-falls": "Sipi Falls sits at the base of Mount Elgon.",
  "lata-iskandar-falls": "Lata Iskandar sits right beside the road to Cameron Highlands.",
  "svartifoss": "Svartifoss is framed by dark, organ-pipe basalt columns.",
  "shoshone-falls": "Shoshone Falls is nicknamed the 'Niagara of the West.'",
  "helmcken-falls": "Helmcken Falls freezes into a giant ice cone each winter.",
  "nohkalikai-falls": "Nohkalikai is the tallest plunge waterfall in India.",
  "fukuroda-falls": "Fukuroda Falls fully freezes over during cold winters.",
  "diaoshuilou-falls": "Diaoshuilou Falls formed where lava dammed an ancient lake.",
  "steinsdalsfossen": "Steinsdalsfossen lets visitors walk on a path behind it.",
  "henrhyd-falls": "Henrhyd Falls appeared as a cave entrance in a Batman film.",
  "shaki-waterfall": "Shaki Waterfall flows over an ancient basalt lava ledge.",
  "bigar-waterfall": "Bigar Waterfall spreads thinly over a moss-covered dome.",
  "venta-rapid": "Venta Rapid is the widest waterfall in Europe.",
  "chamarel-falls": "Chamarel Falls drops about 100 meters over ancient lava layers.",
  "krimml-waterfalls": "Krimml Waterfalls is Austria's tallest waterfall.",
  "wentworth-falls": "Wentworth Falls drops in three stages in the Blue Mountains.",
  "jagala-waterfall": "Jägala Waterfall is the widest natural waterfall in Estonia.",
  "materuni-waterfalls": "Materuni Waterfalls sits on the slopes of Mount Kilimanjaro.",
  "haipa-waterfall": "Haipa Waterfall is one of Myanmar's tallest waterfalls.",
};
