export const WEATHER_E85_FACTS = {
  sun: "Clear skies with no cloud cover to block sunlight.",
  rain: "Water droplets fall once cloud droplets grow heavy enough.",
  snow: "Forms when water vapor freezes directly into ice crystals.",
  cloud: "Made of tiny water droplets or ice crystals in the air.",
  thunderstorm: "Always produces lightning, which causes the thunder sound.",
  rainbow: "Formed when sunlight refracts through falling raindrops.",
  fog: "Essentially a cloud that forms right at ground level.",
  windy: "Caused by air moving from high to low pressure areas.",
  "partly-cloudy": "Cloud cover between roughly a quarter and half the sky.",
  hurricane: "Called a typhoon in the Pacific, but the same storm type.",
  tornado: "Its wind speeds can exceed 300 miles per hour.",
  hail: "Forms when strong updrafts carry raindrops through freezing air.",
  blizzard: "Officially needs sustained winds of 35 mph and low visibility.",
  lightning: "Can reach temperatures hotter than the sun's surface.",
  drizzle: "Made of droplets smaller than typical raindrops.",
  frost: "Forms when water vapor turns straight into ice on cold surfaces.",
  heatwave: "Defined differently depending on a region's normal climate.",
  overcast: "Sky cover of essentially 100 percent, wall to wall clouds.",
  sleet: "Ice pellets that were already frozen before hitting the ground.",
  sandstorm: "Common in deserts when strong winds lift loose sand.",
  aurora: "Caused by charged particles from the sun hitting the atmosphere.",
  waterspout: "Only the rarer, storm-linked type is a true tornado.",
  "dust-devil": "Forms on clear, hot days without needing a storm cloud.",
  monsoon: "A seasonal wind shift that brings heavy rain to a region.",
  "freezing-rain": "Falls as liquid but freezes on contact with cold surfaces.",
  whiteout: "Blowing snow can erase the horizon entirely.",
  squall: "A sudden, brief burst of strong wind.",
  "cold-front": "Marks where cooler air is pushing out warmer air.",
  "warm-front": "Marks where warmer air is advancing over cooler air.",
  "high-pressure": "Usually brings clear skies and calmer weather.",
  "low-pressure": "Usually brings clouds, wind, and precipitation.",
  smog: "A mix of smoke and fog, worsened by air pollution.",
  "heat-lightning": "Just distant lightning too far away to hear thunder.",
  "ice-storm": "Coats surfaces in ice thick enough to snap power lines.",
  "wind-chill": "Measures how cold moving air makes skin actually feel.",
  humidity: "Measures how much water vapor is in the air.",
  "occluded-front": "Forms when a cold front catches up to a warm front.",
  "stationary-front": "A front that stops advancing in either direction.",
  "wind-barb": "Its little flags and lines show wind speed on a map.",
  isobar: "A line connecting points of equal air pressure.",
  trough: "An elongated area of relatively low air pressure.",
  ridge: "An elongated area of relatively high air pressure.",
  anticyclone: "Winds rotate clockwise around it up north.",
  "cyclone-spiral": "Winds rotate counterclockwise around it up north.",
  "barometric-pressure": "Measured with an instrument called a barometer.",
  "dew-point": "The temperature air must cool to for dew to form.",
  "beaufort-scale": "Ranks wind force from 0, calm, up to 12, hurricane.",
  "katabatic-wind": "Cold, dense air flowing downhill under gravity.",
  "chinook-wind": "A warm mountain wind that can melt snow in hours.",
  derecho: "A long-lived, fast-moving line of damaging storm wind.",
  haboob: "An intense wall of dust pushed by a collapsing thunderstorm.",
  "polar-vortex": "A band of cold air that normally stays near the poles.",
  "metar-thunderstorm": "'TS' is the real code pilots see in weather reports.",
  "sky-cover-okta": "Cloud cover is measured in eighths, called oktas.",
  "sun-dog": "Sunlight bending through ice crystals creates bright spots.",
  mammatus: "Named for their pouch-like, udder-shaped underside.",
  "anvil-cloud": "A thunderstorm top flattened by high-altitude winds.",
  virga: "Rain that evaporates before ever reaching the ground.",
  graupel: "Soft, crumbly ice pellets, unlike hard hailstones.",
  "rime-ice": "Forms when fog droplets freeze onto exposed surfaces.",
  "diamond-dust": "Tiny ice crystals that sparkle falling from clear sky.",
  "fire-whirl": "A spinning vortex of flame whipped up by wildfire heat.",
  "ball-lightning": "A rare, still-unexplained glowing sphere seen in storms.",
  sprite: "A brief red electrical flash high above a storm.",
  "noctilucent-clouds": "The highest clouds in Earth's sky, seen at twilight.",
  "sea-smoke": "Forms when cold air moves over much warmer open water.",
  thundersnow: "A rare thunderstorm that produces snow instead of rain.",
  "st-elmos-fire": "A blue glow that appears on pointed objects in storms.",
  "snow-roller": "A rare, naturally-formed cylinder of rolled-up snow.",
  "fallstreak-hole": "A gap left when ice crystals fall from a cloud layer.",
};

export default WEATHER_E85_FACTS;
