export const WEATHER_E85 = [
  // EASY (18) — near-universal forecast-app icons, ~70-95% recognize
  { slug: "sun", name: "Sunny", level: "easy" },
  { slug: "rain", name: "Rain", level: "easy" },
  { slug: "snow", name: "Snow", level: "easy" },
  { slug: "cloud", name: "Cloudy", level: "easy" },
  { slug: "thunderstorm", name: "Thunderstorm", level: "easy" },
  { slug: "rainbow", name: "Rainbow", level: "easy" },
  { slug: "fog", name: "Fog", level: "easy" },
  { slug: "windy", name: "Windy", level: "easy" },
  { slug: "partly-cloudy", name: "Partly Cloudy", level: "easy" },
  { slug: "hurricane", name: "Hurricane", level: "easy" },
  { slug: "tornado", name: "Tornado", level: "easy" },
  { slug: "hail", name: "Hail", level: "easy" },
  { slug: "blizzard", name: "Blizzard", level: "easy" },
  { slug: "lightning", name: "Lightning", level: "easy" },
  { slug: "drizzle", name: "Drizzle", level: "easy" },
  { slug: "frost", name: "Frost", level: "easy" },
  { slug: "heatwave", name: "Heatwave", level: "easy" },
  { slug: "overcast", name: "Overcast", level: "easy" },

  // MEDIUM (18) — most have seen it, ~35-70%
  { slug: "sleet", name: "Sleet", level: "medium" },
  { slug: "sandstorm", name: "Sandstorm", level: "medium" },
  { slug: "aurora", name: "Aurora", level: "medium" },
  { slug: "waterspout", name: "Waterspout", level: "medium" },
  { slug: "dust-devil", name: "Dust Devil", level: "medium" },
  { slug: "monsoon", name: "Monsoon", level: "medium" },
  { slug: "freezing-rain", name: "Freezing Rain", level: "medium" },
  { slug: "whiteout", name: "Whiteout", level: "medium" },
  { slug: "squall", name: "Squall", level: "medium" },
  { slug: "cold-front", name: "Cold Front", level: "medium" },
  { slug: "warm-front", name: "Warm Front", level: "medium" },
  { slug: "high-pressure", name: "High Pressure", level: "medium" },
  { slug: "low-pressure", name: "Low Pressure", level: "medium" },
  { slug: "smog", name: "Smog", level: "medium" },
  { slug: "heat-lightning", name: "Heat Lightning", level: "medium" },
  { slug: "ice-storm", name: "Ice Storm", level: "medium" },
  { slug: "wind-chill", name: "Wind Chill", level: "medium" },
  { slug: "humidity", name: "Humidity", level: "medium" },

  // HARD (16) — enthusiasts/meteorology fans recognize, casual public often doesn't
  { slug: "occluded-front", name: "Occluded Front", level: "hard" },
  { slug: "stationary-front", name: "Stationary Front", level: "hard" },
  { slug: "wind-barb", name: "Wind Barb", level: "hard" },
  { slug: "isobar", name: "Isobar", level: "hard" },
  { slug: "trough", name: "Trough", level: "hard" },
  { slug: "ridge", name: "Ridge", level: "hard" },
  { slug: "anticyclone", name: "Anticyclone", level: "hard" },
  { slug: "cyclone-spiral", name: "Cyclone", level: "hard" },
  { slug: "barometric-pressure", name: "Barometric Pressure", level: "hard" },
  { slug: "dew-point", name: "Dew Point", level: "hard" },
  { slug: "beaufort-scale", name: "Beaufort Scale", level: "hard" },
  { slug: "katabatic-wind", name: "Katabatic Wind", level: "hard" },
  { slug: "chinook-wind", name: "Chinook Wind", level: "hard" },
  { slug: "derecho", name: "Derecho", level: "hard" },
  { slug: "haboob", name: "Haboob", level: "hard" },
  { slug: "polar-vortex", name: "Polar Vortex", level: "hard" },

  // IMPOSSIBLE (18) — genuinely obscure meteorological symbols/phenomena
  { slug: "metar-thunderstorm", name: "METAR Thunderstorm Symbol", level: "impossible" },
  { slug: "sky-cover-okta", name: "Sky Cover Symbol", level: "impossible" },
  { slug: "sun-dog", name: "Sun Dog", level: "impossible" },
  { slug: "mammatus", name: "Mammatus Clouds", level: "impossible" },
  { slug: "anvil-cloud", name: "Anvil Cloud", level: "impossible" },
  { slug: "virga", name: "Virga", level: "impossible" },
  { slug: "graupel", name: "Graupel", level: "impossible" },
  { slug: "rime-ice", name: "Rime Ice", level: "impossible" },
  { slug: "diamond-dust", name: "Diamond Dust", level: "impossible" },
  { slug: "fire-whirl", name: "Fire Whirl", level: "impossible" },
  { slug: "ball-lightning", name: "Ball Lightning", level: "impossible" },
  { slug: "sprite", name: "Sprite", level: "impossible" },
  { slug: "noctilucent-clouds", name: "Noctilucent Clouds", level: "impossible" },
  { slug: "sea-smoke", name: "Sea Smoke", level: "impossible" },
  { slug: "thundersnow", name: "Thundersnow", level: "impossible" },
  { slug: "st-elmos-fire", name: "St. Elmo's Fire", level: "impossible" },
  { slug: "snow-roller", name: "Snow Roller", level: "impossible" },
  { slug: "fallstreak-hole", name: "Fallstreak Hole", level: "impossible" },
];

export default WEATHER_E85;
