// Episode 9 "Guess the World Landmark" — one verified <=70-char fact per item, keyed by slug.
export const WORLD_LANDMARKS_E09_FACTS = {
  "eiffel-tower": "The Eiffel Tower was meant to be torn down after 20 years.",
  "statue-of-liberty": "The Statue of Liberty was a gift from France in 1886.",
  "great-wall-of-china": "The Great Wall was built over many centuries, not all at once.",
  "taj-mahal": "The Taj Mahal was built by an emperor as a tomb for his wife.",
  "great-pyramid-of-giza": "The Great Pyramid was the tallest structure on Earth for millennia.",
  colosseum: "The Colosseum could hold an estimated 50,000+ spectators.",
  "big-ben": "'Big Ben' technically refers to the bell, not the tower.",
  "sydney-opera-house": "The Opera House's design was inspired by orange segments.",
  "leaning-tower-of-pisa": "The Tower of Pisa has leaned since it was still being built.",
  "christ-the-redeemer": "Christ the Redeemer's arms span about 28 meters wide.",
  "machu-picchu": "Machu Picchu was brought to global attention by an expedition in 1911.",
  "mount-rushmore": "Mount Rushmore's four faces took 14 years to carve.",
  "golden-gate-bridge": "The Golden Gate Bridge's color is officially 'International Orange.'",
  stonehenge: "No one knows for certain how Stonehenge's stones were moved.",
  "niagara-falls": "At peak flow, Niagara Falls moves nearly 3,000 tons of water per second.",
  "burj-khalifa": "The Burj Khalifa is the tallest building ever built.",
  petra: "Petra was carved directly into rose-colored rock cliffs.",
  "mount-fuji": "Mount Fuji is an active volcano, last erupting in 1707.",
  "neuschwanstein-castle": "Neuschwanstein inspired Disney's Sleeping Beauty Castle.",
  "angkor-wat": "Angkor Wat began as a Hindu temple, later became Buddhist.",
  "chichen-itza": "Chichen Itza's pyramid aligns perfectly with the equinox sun.",
  "acropolis-of-athens": "The Acropolis sits atop a rocky outcrop above Athens.",
  "sagrada-familia": "The Sagrada Familia has been under construction since 1882.",
  "table-mountain": "Table Mountain is older than the Rocky Mountains and the Alps.",
  "cn-tower": "The CN Tower held the record for world's tallest tower for years.",
  "forbidden-city": "The Forbidden City has nearly 1,000 surviving buildings.",
  "hagia-sophia": "Hagia Sophia has served as a church, mosque, and museum.",
  "mont-saint-michel": "Mont Saint-Michel becomes an island only at high tide.",
  "blue-mosque": "The Blue Mosque gets its nickname from its interior tilework.",
  "moai-statues-easter-island": "Easter Island's moai statues were carved from volcanic rock.",
  "victoria-falls": "Locals call Victoria Falls 'The Smoke that Thunders.'",
  uluru: "Uluru is a single massive sandstone rock formation.",
  alhambra: "The Alhambra was built as a fortress for Moorish rulers.",
  "brandenburg-gate": "The Brandenburg Gate once divided East and West Berlin.",
  "empire-state-building": "The Empire State Building was the world's tallest for 39 years.",
  "palace-of-versailles": "Versailles has over 2,000 windows across its facade.",
  "fushimi-inari-shrine": "Fushimi Inari's gates were each donated by individual worshippers.",
  meteora: "Meteora's monasteries sit atop natural rock pillars formed over millions of years.",
  bagan: "Bagan has over 2,000 surviving ancient Buddhist temples.",
  "ha-long-bay": "Ha Long Bay holds nearly 2,000 limestone islands.",
  "salar-de-uyuni": "Salar de Uyuni is the world's largest salt flat.",
  "wat-arun": "Wat Arun's spires are decorated with colorful porcelain.",
  "chand-baori": "Chand Baori has over 3,500 narrow steps down its walls.",
  trolltunga: "Trolltunga's name means 'the troll's tongue' in Norwegian.",
  "zhangjiajie-national-forest": "Zhangjiajie's peaks are said to have inspired Avatar's floating mountains.",
  "antelope-canyon": "Antelope Canyon was carved by flash flooding over centuries.",
  pamukkale: "Pamukkale means 'cotton castle' in Turkish.",
  "ait-benhaddou": "Ait Benhaddou has appeared as a filming location many times.",
  "church-of-the-savior-on-spilled-blood": "This church marks the site where a Russian tsar was assassinated.",
  "potala-palace": "The Potala Palace was once the seat of Tibet's government.",
  "lalibela-rock-hewn-churches": "Lalibela's churches were carved downward out of solid rock.",
  preikestolen: "Preikestolen is a cliff plateau over 600 meters above a fjord.",
  borobudur: "Borobudur is the world's largest Buddhist temple.",
  "chocolate-hills": "The Chocolate Hills turn brown only in the dry season.",
  "kailasa-temple-ellora": "Kailasa Temple was carved top-down from a single rock.",
  "longyou-caves": "The Longyou Caves were hand-carved but their purpose is unknown.",
  "hagar-qim": "Hagar Qim's megaliths predate Stonehenge and the pyramids.",
  hegra: "Hegra was a major trading city of the Nabataean kingdom.",
  "derinkuyu-underground-city": "Derinkuyu could shelter thousands of people underground.",
  "great-zimbabwe": "Great Zimbabwe's walls were built without any mortar.",
  "nan-madol": "Nan Madol was built on a lagoon from huge basalt logs.",
  "ales-stenar": "Ale's Stones form a stone ship shape overlooking the Baltic Sea.",
  "marble-caves-chile": "The Marble Caves were shaped by 6,000 years of wave erosion.",
  "richat-structure": "The Richat Structure is visible from space as a giant bullseye.",
  "tsingy-de-bemaraha": "Tsingy de Bemaraha's spires are needle-sharp limestone pinnacles.",
  "kawah-ijen": "Kawah Ijen's crater lake glows blue at night from burning sulfur.",
  "wave-rock": "Wave Rock is a granite cliff shaped like a breaking ocean wave.",
  "rainbow-mountain-vinicunca": "Vinicunca's stripes come from layers of different mineral deposits.",
  "gobustan-petroglyphs": "Gobustan preserves thousands of ancient rock carvings.",
  "cave-of-crystals": "The Cave of Crystals holds some of the largest crystals ever found.",
  "cocora-valley": "Cocora Valley is home to the world's tallest palm trees.",
};
export default WORLD_LANDMARKS_E09_FACTS;
