export const WORLD_CURRENCIES_E34_FACTS = {
  "usa-dollar": "The US dollar is the world's most-held reserve currency.",
  "eurozone-euro": "The euro is shared by 20 European Union member countries.",
  "japan-yen": "Japan's yen coins and notes both circulate widely side by side.",
  "china-yuan": "Chinese yuan notes all show a portrait of Mao Zedong.",
  "india-rupee": "The rupee symbol ₹ was officially adopted only in 2010.",
  "australia-dollar": "Australia was among the first nations with polymer banknotes.",
  "switzerland-franc": "The Swiss franc is one of the world's most stable currencies.",
  "brazil-real": "Brazil's real replaced a currency wracked by hyperinflation in 1994.",
  "russia-ruble": "The ruble is one of the oldest currencies still circulating.",
  "south-korea-won": "South Korea's won notes feature Confucian scholars and art.",
  "saudi-arabia-riyal": "Saudi riyal notes feature King Abdulaziz and desert landmarks.",
  "turkey-lira": "Turkish lira notes honor Mustafa Kemal Atatürk on every bill.",
  "poland-zloty": "The zloty's name literally means 'golden' in Polish.",
  "indonesia-rupiah": "Indonesia's largest rupiah note is worth about seven US dollars.",
  "philippines-peso": "Philippine peso notes once featured a security thread you could feel.",
  "vietnam-dong": "Vietnam's dong notes are printed on polymer, not paper, today.",
  "egypt-pound": "Egypt's pound notes are shifting from paper to plastic polymer.",
  "czech-koruna": "The Czech koruna's name literally means 'crown' in Czech.",
  "hungary-forint": "Hungary's forint takes its name from the Italian city Florence.",
  "romania-leu": "Romania's leu name means 'lion,' echoing old Dutch lion coins.",
  "ukraine-hryvnia": "Ukraine's hryvnia name comes from an old Slavic weight measure.",
  "ethiopia-birr": "Ethiopia's birr name once literally meant 'silver' in Amharic.",
  "ghana-cedi": "Ghana's cedi is named after the Akan word for cowrie shell.",
  "sri-lanka-rupee": "Sri Lankan rupee notes depict the country's ancient heritage sites.",
  "myanmar-kyat": "Myanmar's kyat notes still show numerals in Burmese script.",
  "jordan-dinar": "Jordan's dinar is among the highest-valued currency units globally.",
  "kuwait-dinar": "Kuwait's dinar is consistently the world's highest-valued currency.",
  "mongolia-tugrik": "Mongolia's tugrik note art often features Genghis Khan.",
  "samoa-tala": "Samoa's tala name is a local pronunciation of 'dollar'.",
  "bahrain-dinar": "Bahrain's dinar is split into 1,000 fils, not 100 subunits.",
  "azerbaijan-manat": "Azerbaijan's manat shares its name root with the Russian 'moneta'.",
  "armenia-dram": "Armenia's dram name comes from the ancient Greek drachma.",
  "georgia-lari": "Georgia's lari takes its name from an old word for treasure.",
  "moldova-leu": "Moldova's leu, like Romania's, means 'lion' in the language.",
};
