// Episode 9 "Guess the World Landmark" — 71 items, absolute-difficulty calibrated.
// 18/18/18/17 split. Answer = landmark name — engine nameField is "name".
// Every landmark WebSearch-verified as real, currently standing, correctly named, with a
// strong photographic representation. No Israel / West Bank / Gaza / disputed-territory
// landmarks anywhere (Jerusalem sites deliberately excluded entirely).
export const WORLD_LANDMARKS_E09 = [
  // EASY (18)
  { slug: "eiffel-tower", name: "Eiffel Tower", country: "France", level: "easy" },
  { slug: "statue-of-liberty", name: "Statue of Liberty", country: "United States", level: "easy" },
  { slug: "great-wall-of-china", name: "Great Wall of China", country: "China", level: "easy" },
  { slug: "taj-mahal", name: "Taj Mahal", country: "India", level: "easy" },
  { slug: "great-pyramid-of-giza", name: "Great Pyramid of Giza", country: "Egypt", level: "easy" },
  { slug: "colosseum", name: "Colosseum", country: "Italy", level: "easy" },
  { slug: "big-ben", name: "Big Ben", country: "United Kingdom", level: "easy" },
  { slug: "sydney-opera-house", name: "Sydney Opera House", country: "Australia", level: "easy" },
  { slug: "leaning-tower-of-pisa", name: "Leaning Tower of Pisa", country: "Italy", level: "easy" },
  { slug: "christ-the-redeemer", name: "Christ the Redeemer", country: "Brazil", level: "easy" },
  { slug: "machu-picchu", name: "Machu Picchu", country: "Peru", level: "easy" },
  { slug: "mount-rushmore", name: "Mount Rushmore", country: "United States", level: "easy" },
  { slug: "golden-gate-bridge", name: "Golden Gate Bridge", country: "United States", level: "easy" },
  { slug: "stonehenge", name: "Stonehenge", country: "United Kingdom", level: "easy" },
  { slug: "niagara-falls", name: "Niagara Falls", country: "Canada / United States", level: "easy" },
  { slug: "burj-khalifa", name: "Burj Khalifa", country: "United Arab Emirates", level: "easy" },
  { slug: "petra", name: "Petra", country: "Jordan", level: "easy" },
  { slug: "mount-fuji", name: "Mount Fuji", country: "Japan", level: "easy" },
  // MEDIUM (18)
  { slug: "neuschwanstein-castle", name: "Neuschwanstein Castle", country: "Germany", level: "medium" },
  { slug: "angkor-wat", name: "Angkor Wat", country: "Cambodia", level: "medium" },
  { slug: "chichen-itza", name: "Chichen Itza", country: "Mexico", level: "medium" },
  { slug: "acropolis-of-athens", name: "Acropolis of Athens", country: "Greece", level: "medium" },
  { slug: "sagrada-familia", name: "Sagrada Familia", country: "Spain", level: "medium" },
  { slug: "table-mountain", name: "Table Mountain", country: "South Africa", level: "medium" },
  { slug: "cn-tower", name: "CN Tower", country: "Canada", level: "medium" },
  { slug: "forbidden-city", name: "Forbidden City", country: "China", level: "medium" },
  { slug: "hagia-sophia", name: "Hagia Sophia", country: "Turkey", level: "medium" },
  { slug: "mont-saint-michel", name: "Mont Saint-Michel", country: "France", level: "medium" },
  { slug: "blue-mosque", name: "Blue Mosque", country: "Turkey", level: "medium" },
  { slug: "moai-statues-easter-island", name: "Moai Statues of Easter Island", country: "Chile", level: "medium" },
  { slug: "victoria-falls", name: "Victoria Falls", country: "Zambia / Zimbabwe", level: "medium" },
  { slug: "uluru", name: "Uluru", country: "Australia", level: "medium" },
  { slug: "alhambra", name: "Alhambra", country: "Spain", level: "medium" },
  { slug: "brandenburg-gate", name: "Brandenburg Gate", country: "Germany", level: "medium" },
  { slug: "empire-state-building", name: "Empire State Building", country: "United States", level: "medium" },
  { slug: "palace-of-versailles", name: "Palace of Versailles", country: "France", level: "medium" },
  // HARD (18)
  { slug: "fushimi-inari-shrine", name: "Fushimi Inari Shrine", country: "Japan", level: "hard" },
  { slug: "meteora", name: "Meteora", country: "Greece", level: "hard" },
  { slug: "bagan", name: "Bagan", country: "Myanmar", level: "hard" },
  { slug: "ha-long-bay", name: "Ha Long Bay", country: "Vietnam", level: "hard" },
  { slug: "salar-de-uyuni", name: "Salar de Uyuni", country: "Bolivia", level: "hard" },
  { slug: "wat-arun", name: "Wat Arun", country: "Thailand", level: "hard" },
  { slug: "chand-baori", name: "Chand Baori", country: "India", level: "hard" },
  { slug: "trolltunga", name: "Trolltunga", country: "Norway", level: "hard" },
  { slug: "zhangjiajie-national-forest", name: "Zhangjiajie National Forest", country: "China", level: "hard" },
  { slug: "antelope-canyon", name: "Antelope Canyon", country: "United States", level: "hard" },
  { slug: "pamukkale", name: "Pamukkale", country: "Turkey", level: "hard" },
  { slug: "ait-benhaddou", name: "Ait Benhaddou", country: "Morocco", level: "hard" },
  { slug: "church-of-the-savior-on-spilled-blood", name: "Church of the Savior on Spilled Blood", country: "Russia", level: "hard" },
  { slug: "potala-palace", name: "Potala Palace", country: "China", level: "hard" },
  { slug: "lalibela-rock-hewn-churches", name: "Rock-Hewn Churches of Lalibela", country: "Ethiopia", level: "hard" },
  { slug: "preikestolen", name: "Preikestolen", country: "Norway", level: "hard" },
  { slug: "borobudur", name: "Borobudur", country: "Indonesia", level: "hard" },
  { slug: "chocolate-hills", name: "Chocolate Hills", country: "Philippines", level: "hard" },
  // IMPOSSIBLE (17)
  { slug: "kailasa-temple-ellora", name: "Kailasa Temple, Ellora Caves", country: "India", level: "impossible" },
  { slug: "longyou-caves", name: "Longyou Caves", country: "China", level: "impossible" },
  { slug: "hagar-qim", name: "Hagar Qim", country: "Malta", level: "impossible" },
  { slug: "hegra", name: "Hegra", country: "Saudi Arabia", level: "impossible" },
  { slug: "derinkuyu-underground-city", name: "Derinkuyu Underground City", country: "Turkey", level: "impossible" },
  { slug: "great-zimbabwe", name: "Great Zimbabwe", country: "Zimbabwe", level: "impossible" },
  { slug: "nan-madol", name: "Nan Madol", country: "Micronesia", level: "impossible" },
  { slug: "ales-stenar", name: "Ales Stenar", country: "Sweden", level: "impossible" },
  { slug: "marble-caves-chile", name: "Marble Caves", country: "Chile", level: "impossible" },
  { slug: "richat-structure", name: "Richat Structure", country: "Mauritania", level: "impossible" },
  { slug: "tsingy-de-bemaraha", name: "Tsingy de Bemaraha", country: "Madagascar", level: "impossible" },
  { slug: "kawah-ijen", name: "Kawah Ijen", country: "Indonesia", level: "impossible" },
  { slug: "wave-rock", name: "Wave Rock", country: "Australia", level: "impossible" },
  { slug: "rainbow-mountain-vinicunca", name: "Rainbow Mountain (Vinicunca)", country: "Peru", level: "impossible" },
  { slug: "gobustan-petroglyphs", name: "Gobustan Petroglyphs", country: "Azerbaijan", level: "impossible" },
  { slug: "cave-of-crystals", name: "Cave of Crystals", country: "Mexico", level: "impossible" },
  { slug: "cocora-valley", name: "Cocora Valley", country: "Colombia", level: "impossible" },
];
export default WORLD_LANDMARKS_E09;
