export const YEARS_E88_FACTS = {
  y1969: "An estimated 650 million people watched the Moon landing live on TV.",
  y2001: "The attacks led to the creation of the US Department of Homeland Security.",
  y1989: "Crowds used hammers and picks to chip away souvenir pieces of the wall.",
  y2020: "Many major cities saw traffic and pollution levels drop dramatically.",
  y1945: "The United Nations was founded the same year to help prevent future wars.",
  y2007: "It had no App Store at launch — that arrived a year later, in 2008.",
  y1912: "Fewer than half of the roughly 2,200 people aboard survived.",
  y1776: "The Declaration was formally adopted on the Fourth of July.",
  y1963: "He was the youngest person ever elected US president at the time.",
  y1997: "She was known worldwide for her charity work and public image.",
  y1991: "It split into 15 separate independent countries.",
  y2008: "The collapse of Lehman Brothers became its most famous single event.",
  y1939: "It began with Germany's invasion of Poland.",
  y2016: "The UK didn't formally leave the EU until years later, in 2020.",
  y1929: "Stock prices took over 25 years to fully recover to their pre-crash peak.",
  y1994: "He had spent 27 years in prison before his release in 1990.",
  y1953: "Edmund Hillary and Tenzing Norgay reached the summit together.",
  y1955: "It cost about $17 million to build — millions over its original budget.",
  y1917: "It happened in two stages, ending centuries of Romanov rule.",
  y1957: "It was about the size of a beach ball and orbited Earth in 98 minutes.",
  y1968: "His assassination sparked riots in more than 100 US cities.",
  y1980: "He was shot by a man who had asked him for an autograph hours earlier.",
  y1986: "It remains the worst nuclear power plant accident in history.",
  y2003: "The stated goal was removing weapons that were never actually found.",
  y1974: "He remains the only US president ever to resign from office.",
  y1947: "The country was partitioned into India and Pakistan at the same time.",
  y1961: "It stood for 28 years before finally coming down.",
  y1965: "He was shot while giving a speech in New York City.",
  y1979: "It replaced the monarchy with an Islamic republic.",
  y1936: "Adolf Hitler had hoped the Games would showcase Aryan superiority.",
  y1918: "The fighting officially stopped at the eleventh hour of the eleventh day.",
  y1971: "It opened with the Magic Kingdom as its very first theme park.",
  y1998: "Its name comes from 'googol,' a mathematical term for a huge number.",
  y2004: "It was originally limited to Harvard students only.",
  y1876: "His patent filing beat rival Elisha Gray's the same day, sparking lasting controversy.",
  y1903: "Their first flight lasted just 12 seconds and covered 120 feet.",
  y1215: "It was one of the first documents to limit a king's power by law.",
  y1789: "The prison held only a handful of inmates when it fell.",
  y1815: "It permanently ended Napoleon's rule over France.",
  y1867: "It united Ontario, Quebec, Nova Scotia, and New Brunswick.",
  y1871: "Prussia's king became the first emperor of a unified Germany.",
  y1901: "They were established using the fortune of dynamite inventor Alfred Nobel.",
  y1928: "He noticed it almost by accident, in an unwashed petri dish.",
  y1937: "She was attempting to fly around the world at the equator.",
  y1959: "It overthrew the US-backed government of Fulgencio Batista.",
  y1975: "It marked the reunification of North and South Vietnam.",
  y1981: "The disease wasn't officially named until the following year.",
  y1993: "It also created the euro currency, introduced a few years later.",
  y1995: "The attack killed 168 people, including 19 children.",
  y1999: "Physical euro coins and banknotes didn't appear until 2002.",
  y1886: "His three-wheeled 'Motorwagen' reached a top speed of about 10 mph.",
  y1922: "It eventually grew to cover 15 constituent republics.",
  y1054: "Chinese and Arab astronomers both recorded the bright new star.",
  y1088: "It still operates today as a fully functioning university.",
  y1440: "It made books dramatically cheaper and faster to produce.",
  y1783: "Their earlier test flight carried a sheep, a duck, and a rooster.",
  y1804: "It followed a 13-year revolt by enslaved people against French rule.",
  y1859: "Its entire first print run of 1,250 copies sold out on day one.",
  y1896: "241 athletes from 14 nations competed in the first Games.",
  y1905: "He published four groundbreaking papers that same year.",
  y1913: "It cut the time to build a Model T from over 12 hours to about 90 minutes.",
  y1923: "Mustafa Kemal Atatürk became its first president.",
  y1930: "It was later reclassified as a 'dwarf planet' in 2006.",
  y1960: "It became known as the 'Year of Africa.'",
  y1962: "The crisis was triggered by Soviet missiles placed in Cuba.",
  y1970: "An estimated 20 million Americans took part in the first event.",
  y1973: "The call was made from a phone that weighed nearly 2.5 pounds.",
  y1982: "The first commercial CD pressed was a Billy Joel album.",
  y1996: "She was named after singer Dolly Parton.",
  y2000: "In the end, the feared widespread computer failures never materialized.",
};

export default YEARS_E88_FACTS;
