// "Guess the Year" — 70 real historical events, each with one undisputed year.
// clue = the on-screen text shown during the guessing window (plays the role
// the photo/pictogram plays in other episodes). name = the year, spoken/shown at reveal.
export const YEARS_E88 = [
  // EASY (18) — world-famous events almost everyone has heard of
  { slug: "y1969", name: "1969", clue: "Neil Armstrong becomes the first person to walk on the Moon.", level: "easy" },
  { slug: "y2001", name: "2001", clue: "Terrorists attack the World Trade Center on September 11.", level: "easy" },
  { slug: "y1989", name: "1989", clue: "The Berlin Wall falls, ending decades of Cold War division.", level: "easy" },
  { slug: "y2020", name: "2020", clue: "The World Health Organization declares COVID-19 a global pandemic.", level: "easy" },
  { slug: "y1945", name: "1945", clue: "World War II comes to an end.", level: "easy" },
  { slug: "y2007", name: "2007", clue: "The first iPhone goes on sale.", level: "easy" },
  { slug: "y1912", name: "1912", clue: "The Titanic sinks on its very first voyage.", level: "easy" },
  { slug: "y1776", name: "1776", clue: "The United States declares independence.", level: "easy" },
  { slug: "y1963", name: "1963", clue: "President John F. Kennedy is assassinated in Dallas.", level: "easy" },
  { slug: "y1997", name: "1997", clue: "Princess Diana dies in a car crash in Paris.", level: "easy" },
  { slug: "y1991", name: "1991", clue: "The Soviet Union officially dissolves.", level: "easy" },
  { slug: "y2008", name: "2008", clue: "A global financial crisis triggers a worldwide recession.", level: "easy" },
  { slug: "y1939", name: "1939", clue: "World War II begins in Europe.", level: "easy" },
  { slug: "y2016", name: "2016", clue: "The United Kingdom votes to leave the European Union.", level: "easy" },
  { slug: "y1929", name: "1929", clue: "The Wall Street Crash triggers the Great Depression.", level: "easy" },
  { slug: "y1994", name: "1994", clue: "Nelson Mandela is elected President of South Africa.", level: "easy" },
  { slug: "y1953", name: "1953", clue: "Mount Everest is climbed for the very first time.", level: "easy" },
  { slug: "y1955", name: "1955", clue: "Disneyland opens its gates in California.", level: "easy" },

  // MEDIUM (18) — widely known, but the exact year takes real recall
  { slug: "y1917", name: "1917", clue: "The Russian Revolution overthrows the Tsar.", level: "medium" },
  { slug: "y1957", name: "1957", clue: "Sputnik 1 becomes the first satellite launched into orbit.", level: "medium" },
  { slug: "y1968", name: "1968", clue: "Martin Luther King Jr. is assassinated in Memphis.", level: "medium" },
  { slug: "y1980", name: "1980", clue: "John Lennon is shot outside his New York apartment.", level: "medium" },
  { slug: "y1986", name: "1986", clue: "The Chernobyl nuclear reactor explodes in Ukraine.", level: "medium" },
  { slug: "y2003", name: "2003", clue: "The United States leads an invasion of Iraq.", level: "medium" },
  { slug: "y1974", name: "1974", clue: "President Nixon resigns over the Watergate scandal.", level: "medium" },
  { slug: "y1947", name: "1947", clue: "India gains independence from British rule.", level: "medium" },
  { slug: "y1961", name: "1961", clue: "The Berlin Wall is built overnight.", level: "medium" },
  { slug: "y1965", name: "1965", clue: "Civil rights leader Malcolm X is assassinated.", level: "medium" },
  { slug: "y1979", name: "1979", clue: "The Iranian Revolution topples the Shah.", level: "medium" },
  { slug: "y1936", name: "1936", clue: "Jesse Owens wins four gold medals at the Berlin Olympics.", level: "medium" },
  { slug: "y1918", name: "1918", clue: "World War I ends with the Armistice.", level: "medium" },
  { slug: "y1971", name: "1971", clue: "Walt Disney World opens in Florida.", level: "medium" },
  { slug: "y1998", name: "1998", clue: "Google is founded in a California garage.", level: "medium" },
  { slug: "y2004", name: "2004", clue: "Facebook is launched from a Harvard dorm room.", level: "medium" },
  { slug: "y1876", name: "1876", clue: "Alexander Graham Bell patents the telephone.", level: "medium" },
  { slug: "y1903", name: "1903", clue: "The Wright brothers achieve the first powered flight.", level: "medium" },

  // HARD (16) — real, significant history, but pinning the exact year is tough
  { slug: "y1215", name: "1215", clue: "England's King John seals the Magna Carta.", level: "hard" },
  { slug: "y1789", name: "1789", clue: "The storming of the Bastille sparks the French Revolution.", level: "hard" },
  { slug: "y1815", name: "1815", clue: "Napoleon is finally defeated at the Battle of Waterloo.", level: "hard" },
  { slug: "y1867", name: "1867", clue: "Canada becomes a self-governing confederation.", level: "hard" },
  { slug: "y1871", name: "1871", clue: "Germany unifies into a single empire.", level: "hard" },
  { slug: "y1901", name: "1901", clue: "The very first Nobel Prizes are awarded.", level: "hard" },
  { slug: "y1928", name: "1928", clue: "Alexander Fleming discovers penicillin.", level: "hard" },
  { slug: "y1937", name: "1937", clue: "Aviator Amelia Earhart vanishes over the Pacific.", level: "hard" },
  { slug: "y1959", name: "1959", clue: "Fidel Castro's revolution takes power in Cuba.", level: "hard" },
  { slug: "y1975", name: "1975", clue: "The Vietnam War ends with the fall of Saigon.", level: "hard" },
  { slug: "y1981", name: "1981", clue: "Doctors report the first known cases of AIDS.", level: "hard" },
  { slug: "y1993", name: "1993", clue: "The Maastricht Treaty formally creates the European Union.", level: "hard" },
  { slug: "y1995", name: "1995", clue: "A truck bomb devastates the federal building in Oklahoma City.", level: "hard" },
  { slug: "y1999", name: "1999", clue: "The euro currency is introduced across Europe.", level: "hard" },
  { slug: "y1886", name: "1886", clue: "Karl Benz patents the world's first practical automobile.", level: "hard" },
  { slug: "y1922", name: "1922", clue: "The Soviet Union is formally established.", level: "hard" },

  // IMPOSSIBLE (18) — real history, but nailing the exact year is a genuine stretch
  { slug: "y1054", name: "1054", clue: "Astronomers record a supernova that later forms the Crab Nebula.", level: "impossible" },
  { slug: "y1088", name: "1088", clue: "The University of Bologna, Europe's oldest university, is founded.", level: "impossible" },
  { slug: "y1440", name: "1440", clue: "Johannes Gutenberg invents Europe's first movable-type printing press.", level: "impossible" },
  { slug: "y1783", name: "1783", clue: "The Montgolfier brothers fly the first hot air balloon.", level: "impossible" },
  { slug: "y1804", name: "1804", clue: "Haiti becomes the world's first Black-led republic.", level: "impossible" },
  { slug: "y1859", name: "1859", clue: "Charles Darwin publishes 'On the Origin of Species.'", level: "impossible" },
  { slug: "y1896", name: "1896", clue: "The first modern Olympic Games are held in Athens.", level: "impossible" },
  { slug: "y1905", name: "1905", clue: "Albert Einstein publishes his theory of special relativity.", level: "impossible" },
  { slug: "y1913", name: "1913", clue: "Henry Ford introduces the moving assembly line.", level: "impossible" },
  { slug: "y1923", name: "1923", clue: "The Republic of Turkey is proclaimed.", level: "impossible" },
  { slug: "y1930", name: "1930", clue: "The dwarf planet Pluto is discovered.", level: "impossible" },
  { slug: "y1960", name: "1960", clue: "Seventeen African nations gain independence in a single year.", level: "impossible" },
  { slug: "y1962", name: "1962", clue: "The Cuban Missile Crisis brings the world to the brink of war.", level: "impossible" },
  { slug: "y1970", name: "1970", clue: "The very first Earth Day is held.", level: "impossible" },
  { slug: "y1973", name: "1973", clue: "The first handheld mobile phone call is made.", level: "impossible" },
  { slug: "y1982", name: "1982", clue: "The compact disc is released to the public.", level: "impossible" },
  { slug: "y1996", name: "1996", clue: "Dolly the sheep, the first mammal cloned from an adult cell, is born.", level: "impossible" },
  { slug: "y2000", name: "2000", clue: "The world holds its breath as feared 'Y2K' computer bugs meet the new millennium.", level: "impossible" },
];

export default YEARS_E88;
