// E39 "Guess the Zodiac Sign" — World Zodiac Symbols: Western + Chinese + Egyptian (modern) + Celtic Tree + Aztec day-signs.
// Calibrated by global recognizability (quiz-difficulty-calibration). Honestly lopsided toward impossible —
// only Western + Chinese zodiacs are broadly known; Egyptian/Celtic/Aztec systems are genuinely obscure worldwide.
export const ZODIAC_SIGNS_E39 = [
  // WESTERN ZODIAC — easy (8) + medium (4)
  { slug: "aries", name: "Aries", culture: "Western", level: "easy" },
  { slug: "taurus", name: "Taurus", culture: "Western", level: "easy" },
  { slug: "gemini", name: "Gemini", culture: "Western", level: "easy" },
  { slug: "cancer", name: "Cancer", culture: "Western", level: "easy" },
  { slug: "leo", name: "Leo", culture: "Western", level: "easy" },
  { slug: "libra", name: "Libra", culture: "Western", level: "easy" },
  { slug: "scorpio", name: "Scorpio", culture: "Western", level: "easy" },
  { slug: "pisces", name: "Pisces", culture: "Western", level: "easy" },
  { slug: "virgo", name: "Virgo", culture: "Western", level: "medium" },
  { slug: "sagittarius", name: "Sagittarius", culture: "Western", level: "medium" },
  { slug: "capricorn", name: "Capricorn", culture: "Western", level: "medium" },
  { slug: "aquarius", name: "Aquarius", culture: "Western", level: "medium" },

  // CHINESE ZODIAC — easy (7) + medium (5)
  { slug: "dragon", name: "Dragon", culture: "Chinese", level: "easy" },
  { slug: "tiger", name: "Tiger", culture: "Chinese", level: "easy" },
  { slug: "rabbit", name: "Rabbit", culture: "Chinese", level: "easy" },
  { slug: "snake", name: "Snake", culture: "Chinese", level: "easy" },
  { slug: "horse", name: "Horse", culture: "Chinese", level: "easy" },
  { slug: "monkey", name: "Monkey", culture: "Chinese", level: "easy" },
  { slug: "dog", name: "Dog", culture: "Chinese", level: "easy" },
  { slug: "rat", name: "Rat", culture: "Chinese", level: "medium" },
  { slug: "ox", name: "Ox", culture: "Chinese", level: "medium" },
  { slug: "pig", name: "Pig", culture: "Chinese", level: "medium" },
  { slug: "rooster", name: "Rooster", culture: "Chinese", level: "medium" },
  { slug: "goat", name: "Goat", culture: "Chinese", level: "medium" },

  // EGYPTIAN ZODIAC (modern pop-astrology) — medium (5) + hard (3) + impossible (4)
  { slug: "isis", name: "Isis", culture: "Egyptian", level: "medium" },
  { slug: "anubis", name: "Anubis", culture: "Egyptian", level: "medium" },
  { slug: "osiris", name: "Osiris", culture: "Egyptian", level: "medium" },
  { slug: "horus", name: "Horus", culture: "Egyptian", level: "medium" },
  { slug: "bastet", name: "Bastet", culture: "Egyptian", level: "medium" },
  { slug: "amun-ra", name: "Amun-Ra", culture: "Egyptian", level: "hard" },
  { slug: "thoth", name: "Thoth", culture: "Egyptian", level: "hard" },
  { slug: "sekhmet", name: "Sekhmet", culture: "Egyptian", level: "hard" },
  { slug: "geb", name: "Geb", culture: "Egyptian", level: "impossible" },
  { slug: "mut", name: "Mut", culture: "Egyptian", level: "impossible" },
  { slug: "seth", name: "Seth", culture: "Egyptian", level: "impossible" },
  { slug: "hapi", name: "Hapi", culture: "Egyptian", level: "impossible" },

  // CELTIC TREE ZODIAC — hard (6) + impossible (7)
  { slug: "oak", name: "Oak", culture: "Celtic", level: "hard" },
  { slug: "holly", name: "Holly", culture: "Celtic", level: "hard" },
  { slug: "willow", name: "Willow", culture: "Celtic", level: "hard" },
  { slug: "vine", name: "Vine", culture: "Celtic", level: "hard" },
  { slug: "ivy", name: "Ivy", culture: "Celtic", level: "hard" },
  { slug: "hazel", name: "Hazel", culture: "Celtic", level: "hard" },
  { slug: "ash", name: "Ash", culture: "Celtic", level: "impossible" },
  { slug: "elder", name: "Elder", culture: "Celtic", level: "impossible" },
  { slug: "hawthorn", name: "Hawthorn", culture: "Celtic", level: "impossible" },
  { slug: "reed", name: "Reed", culture: "Celtic", level: "impossible" },
  { slug: "rowan", name: "Rowan", culture: "Celtic", level: "impossible" },
  { slug: "birch", name: "Birch", culture: "Celtic", level: "impossible" },
  { slug: "alder", name: "Alder", culture: "Celtic", level: "impossible" },

  // AZTEC DAY-SIGNS (Tonalpohualli) — impossible (16)
  { slug: "coatl", name: "Coatl", culture: "Aztec", level: "impossible" },
  { slug: "cuauhtli", name: "Cuauhtli", culture: "Aztec", level: "impossible" },
  { slug: "xochitl", name: "Xochitl", culture: "Aztec", level: "impossible" },
  { slug: "ocelotl", name: "Ocelotl", culture: "Aztec", level: "impossible" },
  { slug: "ehecatl", name: "Ehecatl", culture: "Aztec", level: "impossible" },
  { slug: "ollin", name: "Ollin", culture: "Aztec", level: "impossible" },
  { slug: "cipactli", name: "Cipactli", culture: "Aztec", level: "impossible" },
  { slug: "miquiztli", name: "Miquiztli", culture: "Aztec", level: "impossible" },
  { slug: "tochtli", name: "Tochtli", culture: "Aztec", level: "impossible" },
  { slug: "atl", name: "Atl", culture: "Aztec", level: "impossible" },
  { slug: "itzcuintli", name: "Itzcuintli", culture: "Aztec", level: "impossible" },
  { slug: "ozomatli", name: "Ozomatli", culture: "Aztec", level: "impossible" },
  { slug: "mazatl", name: "Mazatl", culture: "Aztec", level: "impossible" },
  { slug: "tecpatl", name: "Tecpatl", culture: "Aztec", level: "impossible" },
  { slug: "quiahuitl", name: "Quiahuitl", culture: "Aztec", level: "impossible" },
  { slug: "calli", name: "Calli", culture: "Aztec", level: "impossible" },
];
