export const ZODIAC_SIGNS_E39_FACTS = {
  "aries": "Aries is the first sign, symbolized by the ram.",
  "taurus": "Taurus the bull is ruled by Venus, planet of love.",
  "gemini": "Gemini's twins represent Castor and Pollux in myth.",
  "cancer": "Cancer the crab is ruled by the Moon.",
  "leo": "Leo the lion is ruled by the Sun itself.",
  "libra": "Libra's scales are the zodiac's only object symbol.",
  "scorpio": "Scorpio the scorpion is linked to Mars and Pluto.",
  "pisces": "Pisces shows two fish swimming in opposite directions.",
  "virgo": "Virgo the maiden is the zodiac's only female figure.",
  "sagittarius": "Sagittarius is depicted as a centaur archer.",
  "capricorn": "Capricorn blends a goat's body with a fish's tail.",
  "aquarius": "Aquarius the water-bearer is ruled by Uranus.",
  "dragon": "The Dragon is the only mythical creature in the Chinese zodiac.",
  "tiger": "Tiger years are linked to courage and boldness.",
  "rabbit": "Rabbit is called the Cat in the Vietnamese zodiac.",
  "snake": "Snake years are associated with wisdom and mystery.",
  "horse": "Horse people are said to be free-spirited travelers.",
  "monkey": "The Monkey is prized for cleverness and wit.",
  "dog": "The Dog symbolizes loyalty in Chinese tradition.",
  "rat": "The Rat won the mythical zodiac race by trickery.",
  "ox": "The Ox came second in the legendary zodiac race.",
  "pig": "The Pig closes the 12-year Chinese zodiac cycle.",
  "rooster": "Rooster years favor honesty and hard work.",
  "goat": "Goat is also called Sheep or Ram in some regions.",
  "isis": "Isis was ancient Egypt's goddess of magic and motherhood.",
  "anubis": "Anubis, the jackal god, guided souls to the afterlife.",
  "osiris": "Osiris ruled the underworld as god of the dead.",
  "horus": "Horus the falcon god represented kingship and the sky.",
  "bastet": "Bastet, the cat goddess, symbolized protection and home.",
  "amun-ra": "Amun-Ra fused two gods into Egypt's supreme sun deity.",
  "thoth": "Thoth, the ibis god, was credited with inventing writing.",
  "sekhmet": "Sekhmet, the lioness goddess, embodied war and healing.",
  "geb": "Geb was the Egyptian god of the earth itself.",
  "mut": "Mut was worshipped as mother goddess of Thebes.",
  "seth": "Seth, god of chaos and storms, ruled war in Egyptian myth.",
  "hapi": "Hapi, god of the Nile flood, symbolized life and abundance.",
  "oak": "Oak marks the summer solstice in Celtic tree astrology.",
  "holly": "Holly symbolizes protection and strength in Celtic lore.",
  "willow": "Willow is tied to intuition in Celtic tree lore.",
  "vine": "Vine represents balance in the Celtic tree calendar.",
  "ivy": "Ivy symbolizes resilience in Celtic tree astrology.",
  "hazel": "Hazel was linked to wisdom in Celtic tradition.",
  "ash": "Ash rules early spring in the Celtic tree calendar.",
  "elder": "Elder closes out the Celtic tree zodiac year.",
  "hawthorn": "Hawthorn marks a period of change in Celtic lore.",
  "reed": "Reed symbolizes truth-seeking in Celtic astrology.",
  "rowan": "Rowan was believed to ward off evil in Celtic myth.",
  "birch": "Birch begins the Celtic tree calendar in late December.",
  "alder": "Alder represents self-confidence in Celtic tree lore.",
  "coatl": "Coatl, the serpent, is a day-sign in the Aztec calendar.",
  "cuauhtli": "Cuauhtli, the eagle, symbolized strength in Aztec belief.",
  "xochitl": "Xochitl, the flower, closed the Aztec 20-day cycle.",
  "ocelotl": "Ocelotl, the jaguar, stood for Aztec warrior power.",
  "ehecatl": "Ehecatl, the wind, honored the Aztec wind god.",
  "ollin": "Ollin, movement, symbolized the Aztec sun and earthquakes.",
  "cipactli": "Cipactli, a crocodile, opens the Aztec day-sign cycle.",
  "miquiztli": "Miquiztli, death, was the sixth Aztec day-sign.",
  "tochtli": "Tochtli, the rabbit, linked to fertility in Aztec belief.",
  "atl": "Atl, water, represented life's source in Aztec cosmology.",
  "itzcuintli": "Itzcuintli, the dog, guided souls in Aztec myth.",
  "ozomatli": "Ozomatli, the monkey, symbolized play and art.",
  "mazatl": "Mazatl, the deer, stood for grace in Aztec belief.",
  "tecpatl": "Tecpatl, the flint knife, symbolized sacrifice in Aztec ritual.",
  "quiahuitl": "Quiahuitl, rain, honored the Aztec storm god.",
  "calli": "Calli, the house, represented home in Aztec day-signs.",
};
